Wed May 5 15:19:04 2010
Asterisk developer's documentation
app_parkandannounce.c File Reference
ParkAndAnnounce application for Asterisk.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/features.h"
#include "asterisk/say.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Call Parking and Announce Application")
static int load_module (void)
static int parkandannounce_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * app = "ParkAndAnnounce"
Detailed Description
ParkAndAnnounce application for Asterisk.
Author:
Ben Miller <bgmiller@dccinc.com>
With TONS of help from Mark!
Definition in file app_parkandannounce.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Call Parking and Announce Application")
static int load_module (void) [static]
Definition at line 203 of file app_parkandannounce.c.
References ast_register_application_xml, and parkandannounce_exec().
{
   /* return ast_register_application(app, park_exec); */
   return ast_register_application_xml(app, parkandannounce_exec);
}
static int parkandannounce_exec (struct ast_channel * chan, void * data) [static]
Definition at line 88 of file app_parkandannounce.c.
References __ast_request_and_dial(), ast_channel::_state, ARRAY_LEN, AST_APP_ARG, ast_clear_flag, AST_DECLARE_APP_ARGS, ast_exists_extension(), AST_FLAG_IN_AUTOLOOP, AST_FORMAT_SLINEAR, ast_hangup(), ast_log(), ast_masq_park_call(), ast_parseable_goto(), ast_say_digits(), AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_stopstream(), ast_strdupa, ast_streamfile(), ast_strlen_zero(), ast_variable_new(), ast_verb, ast_waitstream(), buf, ast_channel::cid, ast_callerid::cid_name, ast_callerid::cid_num, ast_channel::context, ast_channel::exten, LOG_WARNING, outgoing_helper::parent_channel, ast_channel::priority, s, strsep(), ast_dial::timeout, and outgoing_helper::vars.
Referenced by load_module().
{
   int res = -1;
   int lot, timeout = 0, dres;
   char *dialtech, *tmp[100], buf[13];
   int looptemp, i;
   char *s;
   struct ast_channel *dchan;
   struct outgoing_helper oh = { 0, };
   int outstate;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(template);
      AST_APP_ARG(timeout);
      AST_APP_ARG(dial);
      AST_APP_ARG(return_context);
   );
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "ParkAndAnnounce requires arguments: (announce:template|timeout|dial|[return_context])\n");
      return -1;
   }
   s = ast_strdupa(data);
   AST_STANDARD_APP_ARGS(args, s);
   if (args.timeout)
      timeout = atoi(args.timeout) * 1000;
   if (ast_strlen_zero(args.dial)) {
      ast_log(LOG_WARNING, "PARK: A dial resource must be specified i.e: Console/dsp or DAHDI/g1/5551212\n");
      return -1;
   }
   dialtech = strsep(&args.dial, "/");
   ast_verb(3, "Dial Tech,String: (%s,%s)\n", dialtech, args.dial);
   if (!ast_strlen_zero(args.return_context)) {
      ast_clear_flag(chan, AST_FLAG_IN_AUTOLOOP);
      ast_parseable_goto(chan, args.return_context);
   }
   ast_verb(3, "Return Context: (%s,%s,%d) ID: %s\n", chan->context, chan->exten, chan->priority, chan->cid.cid_num);
      if (!ast_exists_extension(chan, chan->context, chan->exten, chan->priority, chan->cid.cid_num)) {
      ast_verb(3, "Warning: Return Context Invalid, call will return to default|s\n");
      }
   /* we are using masq_park here to protect * from touching the channel once we park it.  If the channel comes out of timeout
   before we are done announcing and the channel is messed with, Kablooeee.  So we use Masq to prevent this.  */
   res = ast_masq_park_call(chan, NULL, timeout, &lot);
   if (res == -1)
      return res;
   ast_verb(3, "Call Parking Called, lot: %d, timeout: %d, context: %s\n", lot, timeout, args.return_context);
   /* Now place the call to the extension */
   snprintf(buf, sizeof(buf), "%d", lot);
   oh.parent_channel = chan;
   oh.vars = ast_variable_new("_PARKEDAT", buf, "");
   dchan = __ast_request_and_dial(dialtech, AST_FORMAT_SLINEAR, args.dial, 30000, &outstate, chan->cid.cid_num, chan->cid.cid_name, &oh);
   if (dchan) {
      if (dchan->_state == AST_STATE_UP) {
         ast_verb(4, "Channel %s was answered.\n", dchan->name);
      } else {
         ast_verb(4, "Channel %s was never answered.\n", dchan->name);
         ast_log(LOG_WARNING, "PARK: Channel %s was never answered for the announce.\n", dchan->name);
         ast_hangup(dchan);
         return -1;
      }
   } else {
      ast_log(LOG_WARNING, "PARK: Unable to allocate announce channel.\n");
      return -1;
   }
   ast_stopstream(dchan);
   /* now we have the call placed and are ready to play stuff to it */
   ast_verb(4, "Announce Template:%s\n", args.template);
   for (looptemp = 0; looptemp < ARRAY_LEN(tmp); looptemp++) {
      if ((tmp[looptemp] = strsep(&args.template, ":")) != NULL)
         continue;
      else
         break;
   }
   for (i = 0; i < looptemp; i++) {
      ast_verb(4, "Announce:%s\n", tmp[i]);
      if (!strcmp(tmp[i], "PARKED")) {
         ast_say_digits(dchan, lot, "", dchan->language);
      } else {
         dres = ast_streamfile(dchan, tmp[i], dchan->language);
         if (!dres) {
            dres = ast_waitstream(dchan, "");
         } else {
            ast_log(LOG_WARNING, "ast_streamfile of %s failed on %s\n", tmp[i], dchan->name);
            dres = 0;
         }
      }
   }
   ast_stopstream(dchan);
   ast_hangup(dchan);
   return res;
}
static int unload_module (void) [static]
Definition at line 198 of file app_parkandannounce.c.
References ast_unregister_application().
{
   return ast_unregister_application(app);
}
Variable Documentation
char* app = "ParkAndAnnounce" [static]
Definition at line 86 of file app_parkandannounce.c.