Wed May 5 15:19:21 2010
Asterisk developer's documentation
app_transfer.c File Reference
Transfer a caller.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/app.h"
#include "asterisk/channel.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Transfers a caller to another extension")
static int load_module (void)
static int transfer_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static const char * app = "Transfer"
Detailed Description
Transfer a caller.
Author:
Mark Spencer <markster@digium.com>
Requires transfer support from channel driver
Definition in file app_transfer.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Transfers a caller to another extension")
static int load_module (void) [static]
Definition at line 137 of file app_transfer.c.
References ast_register_application_xml, and transfer_exec().
{
   return ast_register_application_xml(app, transfer_exec);
}
static int transfer_exec (struct ast_channel * chan, void * data) [static]
Definition at line 77 of file app_transfer.c.
References AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero(), ast_transfer(), len(), LOG_WARNING, parse(), pbx_builtin_setvar_helper(), status, ast_channel::tech, ast_channel_tech::transfer, and ast_channel_tech::type.
Referenced by load_module().
{
   int res;
   int len;
   char *slash;
   char *tech = NULL;
   char *dest = NULL;
   char *status;
   char *parse;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(dest);
   );
   if (ast_strlen_zero((char *)data)) {
      ast_log(LOG_WARNING, "Transfer requires an argument ([Tech/]destination)\n");
      pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "FAILURE");
      return 0;
   } else
      parse = ast_strdupa(data);
   AST_STANDARD_APP_ARGS(args, parse);
   dest = args.dest;
   if ((slash = strchr(dest, '/')) && (len = (slash - dest))) {
      tech = dest;
      dest = slash + 1;
      /* Allow execution only if the Tech/destination agrees with the type of the channel */
      if (strncasecmp(chan->tech->type, tech, len)) {
         pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "FAILURE");
         return 0;
      }
   }
   /* Check if the channel supports transfer before we try it */
   if (!chan->tech->transfer) {
      pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", "UNSUPPORTED");
      return 0;
   }
   res = ast_transfer(chan, dest);
   if (res < 0) {
      status = "FAILURE";
      res = 0;
   } else {
      status = "SUCCESS";
      res = 0;
   }
   pbx_builtin_setvar_helper(chan, "TRANSFERSTATUS", status);
   return res;
}
static int unload_module (void) [static]
Definition at line 132 of file app_transfer.c.
References ast_unregister_application().
{
   return ast_unregister_application(app);
}
Variable Documentation
const char* app = "Transfer" [static]
Definition at line 75 of file app_transfer.c.