Wed May 5 15:18:56 2010
Asterisk developer's documentation
app_image.c File Reference
App to transmit an image.
#include "asterisk.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/image.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Image Transmission Application")
static int load_module (void)
static int sendimage_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * app = "SendImage"
Detailed Description
App to transmit an image.
Author:
Mark Spencer <markster@digium.com>
Definition in file app_image.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Image Transmission Application")
static int load_module (void) [static]
Definition at line 100 of file app_image.c.
References ast_register_application_xml, and sendimage_exec().
{
   return ast_register_application_xml(app, sendimage_exec);
}
static int sendimage_exec (struct ast_channel * chan, void * data) [static]
Definition at line 72 of file app_image.c.
References ast_log(), ast_send_image(), ast_strlen_zero(), ast_supports_images(), LOG_WARNING, and pbx_builtin_setvar_helper().
Referenced by load_module().
{
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "SendImage requires an argument (filename)\n");
      return -1;
   }
   if (!ast_supports_images(chan)) {
      /* Does not support transport */
      pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "UNSUPPORTED");
      return 0;
   }
   if (!ast_send_image(chan, data)) {
      pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "SUCCESS");
   } else {
      pbx_builtin_setvar_helper(chan, "SENDIMAGESTATUS", "FAILURE");
   }
   return 0;
}
static int unload_module (void) [static]
Definition at line 95 of file app_image.c.
References ast_unregister_application().
{
   return ast_unregister_application(app);
}
Variable Documentation
char* app = "SendImage" [static]
Definition at line 36 of file app_image.c.