Wed May 5 15:18:56 2010
Asterisk developer's documentation
app_macro.c File Reference
Dial plan macro Implementation.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/utils.h"
#include "asterisk/lock.h"
Defines
#define MACRO_EXIT_RESULT 1024
#define MAX_ARGS 80
Functions
static int _macro_exec (struct ast_channel *chan, void *data, int exclusive)
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Extension Macros")
static struct ast_exten * find_matching_priority (struct ast_context *c, const char *exten, int priority, const char *callerid)
static int load_module (void)
static int macro_exec (struct ast_channel *chan, void *data)
static int macro_exit_exec (struct ast_channel *chan, void *data)
static void macro_fixup (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static int macroexclusive_exec (struct ast_channel *chan, void *data)
static int macroif_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * app = "Macro"
static char * exclusive_app = "MacroExclusive"
static char * exit_app = "MacroExit"
static char * if_app = "MacroIf"
struct ast_datastore_info macro_ds_info
Detailed Description
Dial plan macro Implementation.
Author:
Mark Spencer <markster@digium.com>
Definition in file app_macro.c.
Define Documentation
#define MACRO_EXIT_RESULT 1024
Definition at line 152 of file app_macro.c.
Referenced by _macro_exec(), and macro_exit_exec().
#define MAX_ARGS 80
Definition at line 149 of file app_macro.c.
Referenced by _macro_exec(), agi_exec_full(), agi_handle_command(), and parse_args().
Function Documentation
static int _macro_exec (struct ast_channel * chan, void * data, int exclusive) [static]
Definition at line 219 of file app_macro.c.
References app2, ast_autoservice_start(), ast_autoservice_stop(), ast_channel_datastore_add(), ast_channel_datastore_find(), ast_channel_lock, ast_channel_unlock, ast_check_hangup(), ast_context_find(), ast_context_lockmacro(), ast_context_unlockmacro(), ast_copy_string(), ast_datastore_alloc, ast_debug, ast_exists_extension(), AST_FLAG_IN_AUTOLOOP, ast_free, ast_get_context_name(), ast_get_extension_app(), ast_get_extension_app_data(), ast_log(), AST_MAX_CONTEXT, ast_rdlock_context(), ast_rdlock_contexts(), ast_set2_flag, ast_set_flag, AST_SOFTHANGUP_ASYNCGOTO, ast_spawn_extension(), ast_strdup, ast_strdupa, ast_strlen_zero(), ast_test_flag, ast_unlock_context(), ast_unlock_contexts(), ast_verb, ast_walk_contexts(), ast_channel::cid, ast_callerid::cid_num, cond, ast_channel::context, DATASTORE_INHERIT_FOREVER, ast_channel::exten, find_matching_priority(), ast_datastore::inheritance, LOG_ERROR, LOG_WARNING, MACRO_EXIT_RESULT, ast_channel::macrocontext, ast_channel::macroexten, ast_channel::macropriority, MAX_ARGS, pbx_builtin_getvar_helper(), pbx_builtin_setvar_helper(), pbx_checkcondition(), pbx_substitute_variables_helper(), ast_channel::priority, s, and strsep().
Referenced by macro_exec(), and macroexclusive_exec().
{
   const char *s;
   char *tmp;
   char *cur, *rest;
   char *macro;
   char fullmacro[80];
   char varname[80];
   char runningapp[80], runningdata[1024];
   char *oldargs[MAX_ARGS + 1] = { NULL, };
   int argc, x;
   int res=0;
   char oldexten[256]="";
   int oldpriority, gosub_level = 0;
   char pc[80], depthc[12];
   char oldcontext[AST_MAX_CONTEXT] = "";
   const char *inhangupc;
   int offset, depth = 0, maxdepth = 7;
   int setmacrocontext=0;
   int autoloopflag, inhangup = 0;
   char *save_macro_exten;
   char *save_macro_context;
   char *save_macro_priority;
   char *save_macro_offset;
   struct ast_datastore *macro_store = ast_channel_datastore_find(chan, &macro_ds_info, NULL);
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Macro() requires arguments. See \"core show application macro\" for help.\n");
      return -1;
   }
   do {
      if (macro_store) {
         break;
      }
      if (!(macro_store = ast_datastore_alloc(&macro_ds_info, NULL))) {
         ast_log(LOG_WARNING, "Unable to allocate new datastore.\n");
         break;
      }
      /* Just the existence of this datastore is enough. */
      macro_store->inheritance = DATASTORE_INHERIT_FOREVER;
      ast_channel_datastore_add(chan, macro_store);
   } while (0);
   /* does the user want a deeper rabbit hole? */
   ast_channel_lock(chan);
   if ((s = pbx_builtin_getvar_helper(chan, "MACRO_RECURSION"))) {
      sscanf(s, "%30d", &maxdepth);
   }
   /* Count how many levels deep the rabbit hole goes */
   if ((s = pbx_builtin_getvar_helper(chan, "MACRO_DEPTH"))) {
      sscanf(s, "%30d", &depth);
   }
   /* Used for detecting whether to return when a Macro is called from another Macro after hangup */
   if (strcmp(chan->exten, "h") == 0)
      pbx_builtin_setvar_helper(chan, "MACRO_IN_HANGUP", "1");
   if ((inhangupc = pbx_builtin_getvar_helper(chan, "MACRO_IN_HANGUP"))) {
      sscanf(inhangupc, "%30d", &inhangup);
   }
   ast_channel_unlock(chan);
   if (depth >= maxdepth) {
      ast_log(LOG_ERROR, "Macro():  possible infinite loop detected.  Returning early.\n");
      return 0;
   }
   snprintf(depthc, sizeof(depthc), "%d", depth + 1);
   pbx_builtin_setvar_helper(chan, "MACRO_DEPTH", depthc);
   tmp = ast_strdupa(data);
   rest = tmp;
   macro = strsep(&rest, ",");
   if (ast_strlen_zero(macro)) {
      ast_log(LOG_WARNING, "Invalid macro name specified\n");
      return 0;
   }
   snprintf(fullmacro, sizeof(fullmacro), "macro-%s", macro);
   if (!ast_exists_extension(chan, fullmacro, "s", 1, chan->cid.cid_num)) {
      if (!ast_context_find(fullmacro))
         ast_log(LOG_WARNING, "No such context '%s' for macro '%s'\n", fullmacro, macro);
      else
         ast_log(LOG_WARNING, "Context '%s' for macro '%s' lacks 's' extension, priority 1\n", fullmacro, macro);
      return 0;
   }
   /* If we are to run the macro exclusively, take the mutex */
   if (exclusive) {
      ast_debug(1, "Locking macrolock for '%s'\n", fullmacro);
      ast_autoservice_start(chan);
      if (ast_context_lockmacro(fullmacro)) {
         ast_log(LOG_WARNING, "Failed to lock macro '%s' as in-use\n", fullmacro);
         ast_autoservice_stop(chan);
         return 0;
      }
      ast_autoservice_stop(chan);
   }
   /* Save old info */
   oldpriority = chan->priority;
   ast_copy_string(oldexten, chan->exten, sizeof(oldexten));
   ast_copy_string(oldcontext, chan->context, sizeof(oldcontext));
   if (ast_strlen_zero(chan->macrocontext)) {
      ast_copy_string(chan->macrocontext, chan->context, sizeof(chan->macrocontext));
      ast_copy_string(chan->macroexten, chan->exten, sizeof(chan->macroexten));
      chan->macropriority = chan->priority;
      setmacrocontext=1;
   }
   argc = 1;
   /* Save old macro variables */
   save_macro_exten = ast_strdup(pbx_builtin_getvar_helper(chan, "MACRO_EXTEN"));
   pbx_builtin_setvar_helper(chan, "MACRO_EXTEN", oldexten);
   save_macro_context = ast_strdup(pbx_builtin_getvar_helper(chan, "MACRO_CONTEXT"));
   pbx_builtin_setvar_helper(chan, "MACRO_CONTEXT", oldcontext);
   save_macro_priority = ast_strdup(pbx_builtin_getvar_helper(chan, "MACRO_PRIORITY"));
   snprintf(pc, sizeof(pc), "%d", oldpriority);
   pbx_builtin_setvar_helper(chan, "MACRO_PRIORITY", pc);
   save_macro_offset = ast_strdup(pbx_builtin_getvar_helper(chan, "MACRO_OFFSET"));
   pbx_builtin_setvar_helper(chan, "MACRO_OFFSET", NULL);
   /* Setup environment for new run */
   chan->exten[0] = 's';
   chan->exten[1] = '\0';
   ast_copy_string(chan->context, fullmacro, sizeof(chan->context));
   chan->priority = 1;
   ast_channel_lock(chan);
   while((cur = strsep(&rest, ",")) && (argc < MAX_ARGS)) {
      const char *argp;
      /* Save copy of old arguments if we're overwriting some, otherwise
         let them pass through to the other macro */
      snprintf(varname, sizeof(varname), "ARG%d", argc);
      if ((argp = pbx_builtin_getvar_helper(chan, varname))) {
         oldargs[argc] = ast_strdup(argp);
      }
      pbx_builtin_setvar_helper(chan, varname, cur);
      argc++;
   }
   ast_channel_unlock(chan);
   autoloopflag = ast_test_flag(chan, AST_FLAG_IN_AUTOLOOP);
   ast_set_flag(chan, AST_FLAG_IN_AUTOLOOP);
   while(ast_exists_extension(chan, chan->context, chan->exten, chan->priority, chan->cid.cid_num)) {
      struct ast_context *c;
      struct ast_exten *e;
      int foundx;
      runningapp[0] = '\0';
      runningdata[0] = '\0';
      /* What application will execute? */
      if (ast_rdlock_contexts()) {
         ast_log(LOG_WARNING, "Failed to lock contexts list\n");
      } else {
         for (c = ast_walk_contexts(NULL), e = NULL; c; c = ast_walk_contexts(c)) {
            if (!strcmp(ast_get_context_name(c), chan->context)) {
               if (ast_rdlock_context(c)) {
                  ast_log(LOG_WARNING, "Unable to lock context?\n");
               } else {
                  e = find_matching_priority(c, chan->exten, chan->priority, chan->cid.cid_num);
                  if (e) { /* This will only be undefined for pbx_realtime, which is majorly broken. */
                     ast_copy_string(runningapp, ast_get_extension_app(e), sizeof(runningapp));
                     ast_copy_string(runningdata, ast_get_extension_app_data(e), sizeof(runningdata));
                  }
                  ast_unlock_context(c);
               }
               break;
            }
         }
      }
      ast_unlock_contexts();
      /* Reset the macro depth, if it was changed in the last iteration */
      pbx_builtin_setvar_helper(chan, "MACRO_DEPTH", depthc);
      if ((res = ast_spawn_extension(chan, chan->context, chan->exten, chan->priority, chan->cid.cid_num, &foundx,1))) {
         /* Something bad happened, or a hangup has been requested. */
         if (((res >= '0') && (res <= '9')) || ((res >= 'A') && (res <= 'F')) ||
            (res == '*') || (res == '#')) {
            /* Just return result as to the previous application as if it had been dialed */
            ast_debug(1, "Oooh, got something to jump out with ('%c')!\n", res);
            break;
         }
         switch(res) {
         case MACRO_EXIT_RESULT:
            res = 0;
            goto out;
         default:
            ast_debug(2, "Spawn extension (%s,%s,%d) exited non-zero on '%s' in macro '%s'\n", chan->context, chan->exten, chan->priority, chan->name, macro);
            ast_verb(2, "Spawn extension (%s, %s, %d) exited non-zero on '%s' in macro '%s'\n", chan->context, chan->exten, chan->priority, chan->name, macro);
            goto out;
         }
      }
      ast_debug(1, "Executed application: %s\n", runningapp);
      if (!strcasecmp(runningapp, "GOSUB")) {
         gosub_level++;
         ast_debug(1, "Incrementing gosub_level\n");
      } else if (!strcasecmp(runningapp, "GOSUBIF")) {
         char tmp2[1024], *cond, *app_arg, *app2 = tmp2;
         pbx_substitute_variables_helper(chan, runningdata, tmp2, sizeof(tmp2) - 1);
         cond = strsep(&app2, "?");
         app_arg = strsep(&app2, ":");
         if (pbx_checkcondition(cond)) {
            if (!ast_strlen_zero(app_arg)) {
               gosub_level++;
               ast_debug(1, "Incrementing gosub_level\n");
            }
         } else {
            if (!ast_strlen_zero(app2)) {
               gosub_level++;
               ast_debug(1, "Incrementing gosub_level\n");
            }
         }
      } else if (!strcasecmp(runningapp, "RETURN")) {
         gosub_level--;
         ast_debug(1, "Decrementing gosub_level\n");
      } else if (!strcasecmp(runningapp, "STACKPOP")) {
         gosub_level--;
         ast_debug(1, "Decrementing gosub_level\n");
      } else if (!strncasecmp(runningapp, "EXEC", 4)) {
         /* Must evaluate args to find actual app */
         char tmp2[1024], *tmp3 = NULL;
         pbx_substitute_variables_helper(chan, runningdata, tmp2, sizeof(tmp2) - 1);
         if (!strcasecmp(runningapp, "EXECIF")) {
            tmp3 = strchr(tmp2, '|');
            if (tmp3)
               *tmp3++ = '\0';
            if (!pbx_checkcondition(tmp2))
               tmp3 = NULL;
         } else
            tmp3 = tmp2;
         if (tmp3)
            ast_debug(1, "Last app: %s\n", tmp3);
         if (tmp3 && !strncasecmp(tmp3, "GOSUB", 5)) {
            gosub_level++;
            ast_debug(1, "Incrementing gosub_level\n");
         } else if (tmp3 && !strncasecmp(tmp3, "RETURN", 6)) {
            gosub_level--;
            ast_debug(1, "Decrementing gosub_level\n");
         } else if (tmp3 && !strncasecmp(tmp3, "STACKPOP", 8)) {
            gosub_level--;
            ast_debug(1, "Decrementing gosub_level\n");
         }
      }
      if (gosub_level == 0 && strcasecmp(chan->context, fullmacro)) {
         ast_verb(2, "Channel '%s' jumping out of macro '%s'\n", chan->name, macro);
         break;
      }
      /* don't stop executing extensions when we're in "h" */
      if (ast_check_hangup(chan) && !inhangup) {
         ast_debug(1, "Extension %s, macroexten %s, priority %d returned normally even though call was hung up\n", chan->exten, chan->macroexten, chan->priority);
         goto out;
      }
      chan->priority++;
   }
   out:
   /* Don't let the channel change now. */
   ast_channel_lock(chan);
   /* Reset the depth back to what it was when the routine was entered (like if we called Macro recursively) */
   snprintf(depthc, sizeof(depthc), "%d", depth);
   pbx_builtin_setvar_helper(chan, "MACRO_DEPTH", depthc);
   ast_set2_flag(chan, autoloopflag, AST_FLAG_IN_AUTOLOOP);
   for (x = 1; x < argc; x++) {
      /* Restore old arguments and delete ours */
      snprintf(varname, sizeof(varname), "ARG%d", x);
      if (oldargs[x]) {
         pbx_builtin_setvar_helper(chan, varname, oldargs[x]);
         ast_free(oldargs[x]);
      } else {
         pbx_builtin_setvar_helper(chan, varname, NULL);
      }
   }
   /* Restore macro variables */
   pbx_builtin_setvar_helper(chan, "MACRO_EXTEN", save_macro_exten);
   pbx_builtin_setvar_helper(chan, "MACRO_CONTEXT", save_macro_context);
   pbx_builtin_setvar_helper(chan, "MACRO_PRIORITY", save_macro_priority);
   if (save_macro_exten)
      ast_free(save_macro_exten);
   if (save_macro_context)
      ast_free(save_macro_context);
   if (save_macro_priority)
      ast_free(save_macro_priority);
   if (setmacrocontext) {
      chan->macrocontext[0] = '\0';
      chan->macroexten[0] = '\0';
      chan->macropriority = 0;
   }
   if (!strcasecmp(chan->context, fullmacro)) {
      /* If we're leaving the macro normally, restore original information */
      chan->priority = oldpriority;
      ast_copy_string(chan->context, oldcontext, sizeof(chan->context));
      if (!(ast_check_hangup(chan) & AST_SOFTHANGUP_ASYNCGOTO)) {
         /* Copy the extension, so long as we're not in softhangup, where we could be given an asyncgoto */
         const char *offsets;
         ast_copy_string(chan->exten, oldexten, sizeof(chan->exten));
         if ((offsets = pbx_builtin_getvar_helper(chan, "MACRO_OFFSET"))) {
            /* Handle macro offset if it's set by checking the availability of step n + offset + 1, otherwise continue
               normally if there is any problem */
            if (sscanf(offsets, "%30d", &offset) == 1) {
               if (ast_exists_extension(chan, chan->context, chan->exten, chan->priority + offset + 1, chan->cid.cid_num)) {
                  chan->priority += offset;
               }
            }
         }
      }
   }
   pbx_builtin_setvar_helper(chan, "MACRO_OFFSET", save_macro_offset);
   if (save_macro_offset)
      ast_free(save_macro_offset);
   /* Unlock the macro */
   if (exclusive) {
      ast_debug(1, "Unlocking macrolock for '%s'\n", fullmacro);
      if (ast_context_unlockmacro(fullmacro)) {
         ast_log(LOG_ERROR, "Failed to unlock macro '%s' - that isn't good\n", fullmacro);
         res = 0;
      }
   }
   ast_channel_unlock(chan);
   return res;
}
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Extension Macros")
static struct ast_exten* find_matching_priority (struct ast_context * c, const char * exten, int priority, const char * callerid) [static, read]
Definition at line 184 of file app_macro.c.
References ast_extension_match(), ast_get_context_name(), ast_get_extension_cidmatch(), ast_get_extension_matchcid(), ast_get_extension_name(), ast_get_extension_priority(), ast_get_include_name(), ast_walk_context_extensions(), ast_walk_context_includes(), ast_walk_contexts(), and ast_walk_extension_priorities().
Referenced by _macro_exec().
{
   struct ast_exten *e;
   struct ast_include *i;
   struct ast_context *c2;
   for (e=ast_walk_context_extensions(c, NULL); e; e=ast_walk_context_extensions(c, e)) {
      if (ast_extension_match(ast_get_extension_name(e), exten)) {
         int needmatch = ast_get_extension_matchcid(e);
         if ((needmatch && ast_extension_match(ast_get_extension_cidmatch(e), callerid)) ||
            (!needmatch)) {
            /* This is the matching extension we want */
            struct ast_exten *p;
            for (p=ast_walk_extension_priorities(e, NULL); p; p=ast_walk_extension_priorities(e, p)) {
               if (priority != ast_get_extension_priority(p))
                  continue;
               return p;
            }
         }
      }
   }
   /* No match; run through includes */
   for (i=ast_walk_context_includes(c, NULL); i; i=ast_walk_context_includes(c, i)) {
      for (c2=ast_walk_contexts(NULL); c2; c2=ast_walk_contexts(c2)) {
         if (!strcmp(ast_get_context_name(c2), ast_get_include_name(i))) {
            e = find_matching_priority(c2, exten, priority, callerid);
            if (e)
               return e;
         }
      }
   }
   return NULL;
}
static int load_module (void) [static]
Definition at line 611 of file app_macro.c.
References ast_register_application_xml, macro_exec(), macro_exit_exec(), macroexclusive_exec(), and macroif_exec().
{
   int res;
   res = ast_register_application_xml(exit_app, macro_exit_exec);
   res |= ast_register_application_xml(if_app, macroif_exec);
   res |= ast_register_application_xml(exclusive_app, macroexclusive_exec);
   res |= ast_register_application_xml(app, macro_exec);
   return res;
}
static int macro_exec (struct ast_channel * chan, void * data) [static]
Definition at line 559 of file app_macro.c.
References _macro_exec().
Referenced by load_module(), and macroif_exec().
{
   return _macro_exec(chan, data, 0);
}
static int macro_exit_exec (struct ast_channel * chan, void * data) [static]
Definition at line 594 of file app_macro.c.
References MACRO_EXIT_RESULT.
Referenced by load_module().
{
   return MACRO_EXIT_RESULT;
}
static void macro_fixup (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) [static]
Definition at line 166 of file app_macro.c.
References pbx_builtin_getvar_helper(), and pbx_builtin_setvar_helper().
{
   int i;
   char varname[10];
   pbx_builtin_setvar_helper(new_chan, "MACRO_DEPTH", "0");
   pbx_builtin_setvar_helper(new_chan, "MACRO_CONTEXT", NULL);
   pbx_builtin_setvar_helper(new_chan, "MACRO_EXTEN", NULL);
   pbx_builtin_setvar_helper(new_chan, "MACRO_PRIORITY", NULL);
   pbx_builtin_setvar_helper(new_chan, "MACRO_OFFSET", NULL);
   for (i = 1; i < 100; i++) {
      snprintf(varname, sizeof(varname), "ARG%d", i);
      while (pbx_builtin_getvar_helper(new_chan, varname)) {
         /* Kill all levels of arguments */
         pbx_builtin_setvar_helper(new_chan, varname, NULL);
      }
   }
}
static int macroexclusive_exec (struct ast_channel * chan, void * data) [static]
Definition at line 564 of file app_macro.c.
References _macro_exec().
Referenced by load_module().
{
   return _macro_exec(chan, data, 1);
}
static int macroif_exec (struct ast_channel * chan, void * data) [static]
Definition at line 569 of file app_macro.c.
References ast_log(), ast_strdupa, LOG_WARNING, macro_exec(), and pbx_checkcondition().
Referenced by load_module().
{
   char *expr = NULL, *label_a = NULL, *label_b = NULL;
   int res = 0;
   if (!(expr = ast_strdupa(data)))
      return -1;
   if ((label_a = strchr(expr, '?'))) {
      *label_a = '\0';
      label_a++;
      if ((label_b = strchr(label_a, ':'))) {
         *label_b = '\0';
         label_b++;
      }
      if (pbx_checkcondition(expr))
         res = macro_exec(chan, label_a);
      else if (label_b)
         res = macro_exec(chan, label_b);
   } else
      ast_log(LOG_WARNING, "Invalid Syntax.\n");
   return res;
}
static int unload_module (void) [static]
Definition at line 599 of file app_macro.c.
References ast_unregister_application().
{
   int res;
   res = ast_unregister_application(if_app);
   res |= ast_unregister_application(exit_app);
   res |= ast_unregister_application(app);
   res |= ast_unregister_application(exclusive_app);
   return res;
}
Variable Documentation
char* app = "Macro" [static]
Definition at line 154 of file app_macro.c.
char* exclusive_app = "MacroExclusive" [static]
Definition at line 156 of file app_macro.c.
char* exit_app = "MacroExit" [static]
Definition at line 157 of file app_macro.c.
char* if_app = "MacroIf" [static]
Definition at line 155 of file app_macro.c.
struct ast_datastore_info macro_ds_info
Initial value:
 {
   .type = "MACRO",
   .chan_fixup = macro_fixup,
}
Definition at line 161 of file app_macro.c.