Wed May 5 15:18:54 2010
Asterisk developer's documentation
app_cdr.c File Reference
Applications connected with CDR engine.
#include "asterisk.h"
#include "asterisk/channel.h"
#include "asterisk/module.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Tell Asterisk to not maintain a CDR for the current call")
static int load_module (void)
static int nocdr_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * nocdr_app = "NoCDR"
Detailed Description
Applications connected with CDR engine.
Author:
Martin Pycko <martinp@digium.com>
Definition in file app_cdr.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Tell Asterisk to not maintain a CDR for the current call")
static int load_module (void) [static]
Definition at line 62 of file app_cdr.c.
References AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, ast_register_application_xml, and nocdr_exec().
{
   if (ast_register_application_xml(nocdr_app, nocdr_exec))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int nocdr_exec (struct ast_channel * chan, void * data) [static]
Definition at line 49 of file app_cdr.c.
References AST_CDR_FLAG_POST_DISABLED, ast_set_flag, and ast_channel::cdr.
Referenced by load_module().
{
   if (chan->cdr)
      ast_set_flag(chan->cdr, AST_CDR_FLAG_POST_DISABLED);
   return 0;
}
static int unload_module (void) [static]
Definition at line 57 of file app_cdr.c.
References ast_unregister_application().
{
   return ast_unregister_application(nocdr_app);
}
Variable Documentation
char* nocdr_app = "NoCDR" [static]
Definition at line 47 of file app_cdr.c.