Wed May 5 15:19:20 2010
Asterisk developer's documentation
app_sayunixtime.c File Reference
SayUnixTime application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/say.h"
#include "asterisk/app.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Say time")
static int load_module (void)
static int sayunixtime_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * app_datetime = "DateTime"
static char * app_sayunixtime = "SayUnixTime"
Detailed Description
SayUnixTime application.
Author:
Tilghman Lesher <app_sayunixtime__200309@the-tilghman.com>
Definition in file app_sayunixtime.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Say time")
static int load_module (void) [static]
Definition at line 132 of file app_sayunixtime.c.
References ast_register_application_xml, and sayunixtime_exec().
{
   int res;
   res = ast_register_application_xml(app_sayunixtime, sayunixtime_exec);
   res |= ast_register_application_xml(app_datetime, sayunixtime_exec);
   return res;
}
static int sayunixtime_exec (struct ast_channel * chan, void * data) [static]
Definition at line 92 of file app_sayunixtime.c.
References ast_channel::_state, ast_answer(), AST_APP_ARG, AST_DECLARE_APP_ARGS, AST_DIGIT_ANY, ast_get_time_t(), ast_say_date_with_format, AST_STANDARD_APP_ARGS, AST_STATE_UP, ast_strdupa, format, and parse().
Referenced by load_module().
{
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(timeval);
      AST_APP_ARG(timezone);
      AST_APP_ARG(format);
   );
   char *parse;
   int res = 0;
   time_t unixtime;
   if (!data)
      return 0;
   parse = ast_strdupa(data);
   AST_STANDARD_APP_ARGS(args, parse);
   ast_get_time_t(args.timeval, &unixtime, time(NULL), NULL);
   if (chan->_state != AST_STATE_UP)
      res = ast_answer(chan);
   if (!res)
      res = ast_say_date_with_format(chan, unixtime, AST_DIGIT_ANY,
                      chan->language, args.format, args.timezone);
   return res;
}
static int unload_module (void) [static]
Definition at line 122 of file app_sayunixtime.c.
References ast_unregister_application().
{
   int res;
   res = ast_unregister_application(app_sayunixtime);
   res |= ast_unregister_application(app_datetime);
   return res;
}
Variable Documentation
char* app_datetime = "DateTime" [static]
Definition at line 90 of file app_sayunixtime.c.
char* app_sayunixtime = "SayUnixTime" [static]
Definition at line 89 of file app_sayunixtime.c.