Wed May 5 15:18:54 2010
Asterisk developer's documentation
app_chanspy.c File Reference
ChanSpy: Listen in on any channel.
#include "asterisk.h"
#include <ctype.h>
#include <errno.h>
#include "asterisk/paths.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/audiohook.h"
#include "asterisk/features.h"
#include "asterisk/app.h"
#include "asterisk/utils.h"
#include "asterisk/say.h"
#include "asterisk/pbx.h"
#include "asterisk/translate.h"
#include "asterisk/manager.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/options.h"
Data Structures
struct chanspy_ds
struct chanspy_translation_helper
Defines
#define AST_NAME_STRLEN 256
#define NUM_SPYGROUPS 128
Enumerations
enum {
OPTION_QUIET = (1 << 0), OPTION_BRIDGED = (1 << 1), OPTION_VOLUME = (1 << 2), OPTION_GROUP = (1 << 3),
OPTION_RECORD = (1 << 4), OPTION_WHISPER = (1 << 5), OPTION_PRIVATE = (1 << 6), OPTION_READONLY = (1 << 7),
OPTION_EXIT = (1 << 8), OPTION_ENFORCED = (1 << 9), OPTION_NOTECH = (1 << 10), OPTION_BARGE = (1 << 11),
OPTION_NAME = (1 << 12), OPTION_DTMF_SWITCH_MODES = (1 << 13)
}
enum {
OPT_ARG_VOLUME = 0, OPT_ARG_GROUP, OPT_ARG_RECORD, OPT_ARG_ENFORCED,
OPT_ARG_NAME, OPT_ARG_ARRAY_SIZE
}
Functions
AST_APP_OPTIONS (spy_opts,{AST_APP_OPTION('q', OPTION_QUIET), AST_APP_OPTION('b', OPTION_BRIDGED), AST_APP_OPTION('B', OPTION_BARGE), AST_APP_OPTION('w', OPTION_WHISPER), AST_APP_OPTION('W', OPTION_PRIVATE), AST_APP_OPTION_ARG('v', OPTION_VOLUME, OPT_ARG_VOLUME), AST_APP_OPTION_ARG('g', OPTION_GROUP, OPT_ARG_GROUP), AST_APP_OPTION_ARG('r', OPTION_RECORD, OPT_ARG_RECORD), AST_APP_OPTION_ARG('e', OPTION_ENFORCED, OPT_ARG_ENFORCED), AST_APP_OPTION('o', OPTION_READONLY), AST_APP_OPTION('X', OPTION_EXIT), AST_APP_OPTION('s', OPTION_NOTECH), AST_APP_OPTION_ARG('n', OPTION_NAME, OPT_ARG_NAME), AST_APP_OPTION('d', OPTION_DTMF_SWITCH_MODES),})
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Listen to the audio of an active channel")
static void change_spy_mode (const char digit, struct ast_flags *flags)
static int channel_spy (struct ast_channel *chan, struct chanspy_ds *spyee_chanspy_ds, int *volfactor, int fd, struct ast_flags *flags, char *exitcontext)
static void chanspy_ds_chan_fixup (void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
static void chanspy_ds_destroy (void *data)
static struct chanspy_ds * chanspy_ds_free (struct chanspy_ds *chanspy_ds)
static int chanspy_exec (struct ast_channel *chan, void *data)
static int common_exec (struct ast_channel *chan, struct ast_flags *flags, int volfactor, const int fd, const char *mygroup, const char *myenforced, const char *spec, const char *exten, const char *context, const char *mailbox, const char *name_context)
static int extenspy_exec (struct ast_channel *chan, void *data)
static int load_module (void)
static struct chanspy_ds * next_channel (struct ast_channel *chan, const struct ast_channel *last, const char *spec, const char *exten, const char *context, struct chanspy_ds *chanspy_ds)
static struct chanspy_ds * setup_chanspy_ds (struct ast_channel *chan, struct chanspy_ds *chanspy_ds)
static void * spy_alloc (struct ast_channel *chan, void *data)
static int spy_generate (struct ast_channel *chan, void *data, int len, int samples)
static void spy_release (struct ast_channel *chan, void *data)
static int start_spying (struct ast_channel *chan, const char *spychan_name, struct ast_audiohook *audiohook)
static int unload_module (void)
Variables
static const char * app_chan = "ChanSpy"
static const char * app_ext = "ExtenSpy"
static struct ast_datastore_info chanspy_ds_info
enum { ... } chanspy_opt_args
enum { ... } chanspy_opt_flags
static int next_unique_id_to_use = 0
static struct ast_generator spygen
Detailed Description
ChanSpy: Listen in on any channel.
Author:
Anthony Minessale II <anthmct@yahoo.com>
Joshua Colp <jcolp@digium.com>
Russell Bryant <russell@digium.com>
Definition in file app_chanspy.c.
Define Documentation
#define AST_NAME_STRLEN 256
Definition at line 54 of file app_chanspy.c.
Referenced by common_exec().
#define NUM_SPYGROUPS 128
Definition at line 55 of file app_chanspy.c.
Referenced by common_exec().
Enumeration Type Documentation
anonymous enum
Enumerator:
OPTION_QUIET
OPTION_BRIDGED
OPTION_VOLUME
OPTION_GROUP
OPTION_RECORD
OPTION_WHISPER
OPTION_PRIVATE
OPTION_READONLY
OPTION_EXIT
OPTION_ENFORCED
OPTION_NOTECH
OPTION_BARGE
OPTION_NAME
OPTION_DTMF_SWITCH_MODES
Definition at line 296 of file app_chanspy.c.
     {
   OPTION_QUIET             = (1 << 0),    /* Quiet, no announcement */
   OPTION_BRIDGED           = (1 << 1),    /* Only look at bridged calls */
   OPTION_VOLUME            = (1 << 2),    /* Specify initial volume */
   OPTION_GROUP             = (1 << 3),    /* Only look at channels in group */
   OPTION_RECORD            = (1 << 4),
   OPTION_WHISPER           = (1 << 5),
   OPTION_PRIVATE           = (1 << 6),    /* Private Whisper mode */
   OPTION_READONLY          = (1 << 7),    /* Don't mix the two channels */
   OPTION_EXIT              = (1 << 8),    /* Exit to a valid single digit extension */
   OPTION_ENFORCED          = (1 << 9),    /* Enforced mode */
   OPTION_NOTECH            = (1 << 10),   /* Skip technology name playback */
   OPTION_BARGE             = (1 << 11),   /* Barge mode (whisper to both channels) */
   OPTION_NAME              = (1 << 12),   /* Say the name of the person on whom we will spy */
   OPTION_DTMF_SWITCH_MODES = (1 << 13),   /*Allow numeric DTMF to switch between chanspy modes */
} chanspy_opt_flags;
anonymous enum
Enumerator:
OPT_ARG_VOLUME
OPT_ARG_GROUP
OPT_ARG_RECORD
OPT_ARG_ENFORCED
OPT_ARG_NAME
OPT_ARG_ARRAY_SIZE
Definition at line 313 of file app_chanspy.c.
     {
   OPT_ARG_VOLUME = 0,
   OPT_ARG_GROUP,
   OPT_ARG_RECORD,
   OPT_ARG_ENFORCED,
   OPT_ARG_NAME,
   OPT_ARG_ARRAY_SIZE,
} chanspy_opt_args;
Function Documentation
AST_APP_OPTIONS (spy_opts)
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Listen to the audio of an active channel")
static void change_spy_mode (const char digit, struct ast_flags * flags) [static]
Definition at line 431 of file app_chanspy.c.
References ast_clear_flag, ast_set_flag, OPTION_BARGE, and OPTION_WHISPER.
Referenced by channel_spy().
{
   if (digit == '4') {
      ast_clear_flag(flags, OPTION_WHISPER);
      ast_clear_flag(flags, OPTION_BARGE);
   } else if (digit == '5') {
      ast_clear_flag(flags, OPTION_BARGE);
      ast_set_flag(flags, OPTION_WHISPER);
   } else if (digit == '6') {
      ast_clear_flag(flags, OPTION_WHISPER);
      ast_set_flag(flags, OPTION_BARGE);
   }
}
static int channel_spy (struct ast_channel * chan, struct chanspy_ds * spyee_chanspy_ds, int * volfactor, int fd, struct ast_flags * flags, char * exitcontext) [static]
Definition at line 445 of file app_chanspy.c.
References ast_activate_generator(), ast_audiohook_destroy(), ast_audiohook_detach(), AST_AUDIOHOOK_DIRECTION_WRITE, ast_audiohook_init(), ast_audiohook_lock, AST_AUDIOHOOK_STATUS_RUNNING, AST_AUDIOHOOK_TYPE_SPY, AST_AUDIOHOOK_TYPE_WHISPER, ast_audiohook_unlock, ast_audiohook_write_frame(), ast_bridged_channel(), ast_channel_lock, ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), ast_channel_trylock, ast_channel_unlock, ast_check_hangup(), ast_clear_flag, ast_copy_flags, ast_deactivate_generator(), ast_debug, AST_FLAG_END_DTMF_ONLY, AST_FLAGS_ALL, AST_FRAME_DTMF, AST_FRAME_VOICE, ast_frfree, ast_goto_if_exists(), ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_read(), ast_set_flag, ast_strdupa, ast_strlen_zero(), ast_test_flag, ast_verb, ast_waitfor(), chanspy_translation_helper::bridge_whisper_audiohook, chanspy_ds::chan, change_spy_mode(), DEADLOCK_AVOIDANCE, EVENT_FLAG_CALL, f, chanspy_translation_helper::fd, ast_frame::frametype, chanspy_ds::lock, LOG_WARNING, manager_event, name, OPTION_BARGE, OPTION_DTMF_SWITCH_MODES, OPTION_EXIT, OPTION_PRIVATE, OPTION_WHISPER, ast_audiohook::options, pbx_builtin_setvar_helper(), ast_audiohook_options::read_volume, chanspy_translation_helper::spy_audiohook, start_spying(), ast_audiohook::status, ast_frame::subclass, chanspy_translation_helper::volfactor, chanspy_translation_helper::whisper_audiohook, and ast_audiohook_options::write_volume.
Referenced by common_exec().
{
   struct chanspy_translation_helper csth;
   int running = 0, res, x = 0;
   char inp[24] = {0};
   char *name;
   struct ast_frame *f;
   struct ast_silence_generator *silgen = NULL;
   struct ast_channel *spyee = NULL, *spyee_bridge = NULL;
   const char *spyer_name;
   ast_channel_lock(chan);
   spyer_name = ast_strdupa(chan->name);
   ast_channel_unlock(chan);
   ast_mutex_lock(&spyee_chanspy_ds->lock);
   while ((spyee = spyee_chanspy_ds->chan) && ast_channel_trylock(spyee)) {
      /* avoid a deadlock here, just in case spyee is masqueraded and
       * chanspy_ds_chan_fixup() is called with the channel locked */
      DEADLOCK_AVOIDANCE(&spyee_chanspy_ds->lock);
   }
   ast_mutex_unlock(&spyee_chanspy_ds->lock);
   if (!spyee) {
      return 0;
   }
   /* We now hold the channel lock on spyee */
   if (ast_check_hangup(chan) || ast_check_hangup(spyee)) {
      ast_channel_unlock(spyee);
      return 0;
   }
   name = ast_strdupa(spyee->name);
   ast_verb(2, "Spying on channel %s\n", name);
   manager_event(EVENT_FLAG_CALL, "ChanSpyStart",
         "SpyerChannel: %s\r\n"
         "SpyeeChannel: %s\r\n",
         spyer_name, name);
   memset(&csth, 0, sizeof(csth));
   ast_copy_flags(&csth.spy_audiohook, flags, AST_FLAGS_ALL);
   ast_audiohook_init(&csth.spy_audiohook, AST_AUDIOHOOK_TYPE_SPY, "ChanSpy");
   if (start_spying(spyee, spyer_name, &csth.spy_audiohook)) {
      ast_audiohook_destroy(&csth.spy_audiohook);
      ast_channel_unlock(spyee);
      return 0;
   }
   ast_audiohook_init(&csth.whisper_audiohook, AST_AUDIOHOOK_TYPE_WHISPER, "ChanSpy");
   ast_audiohook_init(&csth.bridge_whisper_audiohook, AST_AUDIOHOOK_TYPE_WHISPER, "Chanspy");
   if (start_spying(spyee, spyer_name, &csth.whisper_audiohook)) {
      ast_log(LOG_WARNING, "Unable to attach whisper audiohook to spyee %s. Whisper mode disabled!\n", spyee->name);
   }
   if ((spyee_bridge = ast_bridged_channel(spyee))) {
      ast_channel_lock(spyee_bridge);
      if (start_spying(spyee_bridge, spyer_name, &csth.bridge_whisper_audiohook)) {
         ast_log(LOG_WARNING, "Unable to attach barge audiohook on spyee %s. Barge mode disabled!\n", spyee->name);
      }
      ast_channel_unlock(spyee_bridge);
   }
   ast_channel_unlock(spyee);
   spyee = NULL;
   ast_channel_lock(chan);
   ast_set_flag(chan, AST_FLAG_END_DTMF_ONLY);
   ast_channel_unlock(chan);
   csth.volfactor = *volfactor;
   if (csth.volfactor) {
      csth.spy_audiohook.options.read_volume = csth.volfactor;
      csth.spy_audiohook.options.write_volume = csth.volfactor;
   }
   csth.fd = fd;
   if (ast_test_flag(flags, OPTION_PRIVATE))
      silgen = ast_channel_start_silence_generator(chan);
   else
      ast_activate_generator(chan, &spygen, &csth);
   /* We can no longer rely on 'spyee' being an actual channel;
      it can be hung up and freed out from under us. However, the
      channel destructor will put NULL into our csth.spy.chan
      field when that happens, so that is our signal that the spyee
      channel has gone away.
   */
   /* Note: it is very important that the ast_waitfor() be the first
      condition in this expression, so that if we wait for some period
      of time before receiving a frame from our spying channel, we check
      for hangup on the spied-on channel _after_ knowing that a frame
      has arrived, since the spied-on channel could have gone away while
      we were waiting
   */
   while ((res = ast_waitfor(chan, -1) > -1) && csth.spy_audiohook.status == AST_AUDIOHOOK_STATUS_RUNNING) {
      if (!(f = ast_read(chan)) || ast_check_hangup(chan)) {
         running = -1;
         break;
      }
      if (ast_test_flag(flags, OPTION_BARGE) && f->frametype == AST_FRAME_VOICE) {
         ast_audiohook_lock(&csth.whisper_audiohook);
         ast_audiohook_lock(&csth.bridge_whisper_audiohook);
         ast_audiohook_write_frame(&csth.whisper_audiohook, AST_AUDIOHOOK_DIRECTION_WRITE, f);
         ast_audiohook_write_frame(&csth.bridge_whisper_audiohook, AST_AUDIOHOOK_DIRECTION_WRITE, f);
         ast_audiohook_unlock(&csth.whisper_audiohook);
         ast_audiohook_unlock(&csth.bridge_whisper_audiohook);
         ast_frfree(f);
         continue;
      } else if (ast_test_flag(flags, OPTION_WHISPER) && f->frametype == AST_FRAME_VOICE) {
         ast_audiohook_lock(&csth.whisper_audiohook);
         ast_audiohook_write_frame(&csth.whisper_audiohook, AST_AUDIOHOOK_DIRECTION_WRITE, f);
         ast_audiohook_unlock(&csth.whisper_audiohook);
         ast_frfree(f);
         continue;
      }
      res = (f->frametype == AST_FRAME_DTMF) ? f->subclass : 0;
      ast_frfree(f);
      if (!res)
         continue;
      if (x == sizeof(inp))
         x = 0;
      if (res < 0) {
         running = -1;
         break;
      }
      if (ast_test_flag(flags, OPTION_EXIT)) {
         char tmp[2];
         tmp[0] = res;
         tmp[1] = '\0';
         if (!ast_goto_if_exists(chan, exitcontext, tmp, 1)) {
            ast_debug(1, "Got DTMF %c, goto context %s\n", tmp[0], exitcontext);
            pbx_builtin_setvar_helper(chan, "SPY_CHANNEL", name);
            running = -2;
            break;
         } else {
            ast_debug(2, "Exit by single digit did not work in chanspy. Extension %s does not exist in context %s\n", tmp, exitcontext);
         }
      } else if (res >= '0' && res <= '9') {
         if (ast_test_flag(flags, OPTION_DTMF_SWITCH_MODES)) {
            change_spy_mode(res, flags);
         } else {
            inp[x++] = res;
         }
      }
      if (res == '*') {
         running = 0;
         break;
      } else if (res == '#') {
         if (!ast_strlen_zero(inp)) {
            running = atoi(inp);
            break;
         }
         (*volfactor)++;
         if (*volfactor > 4)
            *volfactor = -4;
         ast_verb(3, "Setting spy volume on %s to %d\n", chan->name, *volfactor);
         csth.volfactor = *volfactor;
         csth.spy_audiohook.options.read_volume = csth.volfactor;
         csth.spy_audiohook.options.write_volume = csth.volfactor;
      }
   }
   if (ast_test_flag(flags, OPTION_PRIVATE))
      ast_channel_stop_silence_generator(chan, silgen);
   else
      ast_deactivate_generator(chan);
   ast_channel_lock(chan);
   ast_clear_flag(chan, AST_FLAG_END_DTMF_ONLY);
   ast_channel_unlock(chan);
   ast_audiohook_lock(&csth.whisper_audiohook);
   ast_audiohook_detach(&csth.whisper_audiohook);
   ast_audiohook_unlock(&csth.whisper_audiohook);
   ast_audiohook_destroy(&csth.whisper_audiohook);
   ast_audiohook_lock(&csth.bridge_whisper_audiohook);
   ast_audiohook_detach(&csth.bridge_whisper_audiohook);
   ast_audiohook_unlock(&csth.bridge_whisper_audiohook);
   ast_audiohook_destroy(&csth.bridge_whisper_audiohook);
   ast_audiohook_lock(&csth.spy_audiohook);
   ast_audiohook_detach(&csth.spy_audiohook);
   ast_audiohook_unlock(&csth.spy_audiohook);
   ast_audiohook_destroy(&csth.spy_audiohook);
   ast_verb(2, "Done Spying on channel %s\n", name);
   manager_event(EVENT_FLAG_CALL, "ChanSpyStop", "SpyeeChannel: %s\r\n", name);
   return running;
}
static void chanspy_ds_chan_fixup (void * data, struct ast_channel * old_chan, struct ast_channel * new_chan) [static]
Definition at line 669 of file app_chanspy.c.
References ast_mutex_lock(), ast_mutex_unlock(), chanspy_ds::chan, and chanspy_ds::lock.
{
   struct chanspy_ds *chanspy_ds = data;
   ast_mutex_lock(&chanspy_ds->lock);
   chanspy_ds->chan = new_chan;
   ast_mutex_unlock(&chanspy_ds->lock);
}
static void chanspy_ds_destroy (void * data) [static]
Note:
This relies on the embedded lock to be recursive, as it may be called due to a call to chanspy_ds_free with the lock held there.
Definition at line 656 of file app_chanspy.c.
References ast_mutex_lock(), ast_mutex_unlock(), chanspy_ds::chan, and chanspy_ds::lock.
Referenced by chanspy_ds_free().
{
   struct chanspy_ds *chanspy_ds = data;
   /* Setting chan to be NULL is an atomic operation, but we don't want this
    * value to change while this lock is held.  The lock is held elsewhere
    * while it performs non-atomic operations with this channel pointer */
   ast_mutex_lock(&chanspy_ds->lock);
   chanspy_ds->chan = NULL;
   ast_mutex_unlock(&chanspy_ds->lock);
}
static struct chanspy_ds* chanspy_ds_free (struct chanspy_ds * chanspy_ds) [static, read]
Definition at line 684 of file app_chanspy.c.
References ast_channel_datastore_find(), ast_channel_datastore_remove(), ast_channel_trylock, ast_channel_unlock, ast_datastore_free(), ast_mutex_lock(), ast_mutex_unlock(), chanspy_ds::chan, chan, chanspy_ds_destroy(), ast_datastore::data, DEADLOCK_AVOIDANCE, chanspy_ds::lock, and chanspy_ds::unique_id.
Referenced by common_exec(), and setup_chanspy_ds().
{
   struct ast_channel *chan;
   if (!chanspy_ds) {
      return NULL;
   }
   ast_mutex_lock(&chanspy_ds->lock);
   while ((chan = chanspy_ds->chan)) {
      struct ast_datastore *datastore;
      if (ast_channel_trylock(chan)) {
         DEADLOCK_AVOIDANCE(&chanspy_ds->lock);
         continue;
      }
      if ((datastore = ast_channel_datastore_find(chan, &chanspy_ds_info, chanspy_ds->unique_id))) {
         ast_channel_datastore_remove(chan, datastore);
         /* chanspy_ds->chan is NULL after this call */
         chanspy_ds_destroy(datastore->data);
         datastore->data = NULL;
         ast_datastore_free(datastore);
      }
      ast_channel_unlock(chan);
      break;
   }
   ast_mutex_unlock(&chanspy_ds->lock);
   return NULL;
}
static int chanspy_exec (struct ast_channel * chan, void * data) [static]
Definition at line 1035 of file app_chanspy.c.
References AST_APP_ARG, ast_app_parse_options(), ast_clear_flag, ast_config_AST_MONITOR_DIR, AST_DECLARE_APP_ARGS, AST_FILE_MODE, AST_FLAGS_ALL, AST_FORMAT_SLINEAR, ast_log(), ast_set_flag, ast_set_write_format(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero(), ast_test_flag, common_exec(), LOG_ERROR, LOG_NOTICE, LOG_WARNING, mailbox, OPT_ARG_ARRAY_SIZE, OPT_ARG_ENFORCED, OPT_ARG_GROUP, OPT_ARG_NAME, OPT_ARG_RECORD, OPT_ARG_VOLUME, OPTION_ENFORCED, OPTION_GROUP, OPTION_NAME, OPTION_PRIVATE, OPTION_RECORD, OPTION_VOLUME, OPTION_WHISPER, and ast_channel::writeformat.
Referenced by load_module().
{
   char *myenforced = NULL;
   char *mygroup = NULL;
   char *recbase = NULL;
   int fd = 0;
   struct ast_flags flags;
   int oldwf = 0;
   int volfactor = 0;
   int res;
   char *mailbox = NULL;
   char *name_context = NULL;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(spec);
      AST_APP_ARG(options);
   );
   char *opts[OPT_ARG_ARRAY_SIZE];
   data = ast_strdupa(data);
   AST_STANDARD_APP_ARGS(args, data);
   if (args.spec && !strcmp(args.spec, "all"))
      args.spec = NULL;
   if (args.options) {
      ast_app_parse_options(spy_opts, &flags, opts, args.options);
      if (ast_test_flag(&flags, OPTION_GROUP))
         mygroup = opts[OPT_ARG_GROUP];
      if (ast_test_flag(&flags, OPTION_RECORD) &&
         !(recbase = opts[OPT_ARG_RECORD]))
         recbase = "chanspy";
      if (ast_test_flag(&flags, OPTION_VOLUME) && opts[OPT_ARG_VOLUME]) {
         int vol;
         if ((sscanf(opts[OPT_ARG_VOLUME], "%30d", &vol) != 1) || (vol > 4) || (vol < -4))
            ast_log(LOG_NOTICE, "Volume factor must be a number between -4 and 4\n");
         else
            volfactor = vol;
      }
      if (ast_test_flag(&flags, OPTION_PRIVATE))
         ast_set_flag(&flags, OPTION_WHISPER);
      if (ast_test_flag(&flags, OPTION_ENFORCED))
         myenforced = opts[OPT_ARG_ENFORCED];
      if (ast_test_flag(&flags, OPTION_NAME)) {
         if (!ast_strlen_zero(opts[OPT_ARG_NAME])) {
            char *delimiter;
            if ((delimiter = strchr(opts[OPT_ARG_NAME], '@'))) {
               mailbox = opts[OPT_ARG_NAME];
               *delimiter++ = '\0';
               name_context = delimiter;
            } else {
               mailbox = opts[OPT_ARG_NAME];
            }
         }
      }
   } else
      ast_clear_flag(&flags, AST_FLAGS_ALL);
   oldwf = chan->writeformat;
   if (ast_set_write_format(chan, AST_FORMAT_SLINEAR) < 0) {
      ast_log(LOG_ERROR, "Could Not Set Write Format.\n");
      return -1;
   }
   if (recbase) {
      char filename[PATH_MAX];
      snprintf(filename, sizeof(filename), "%s/%s.%d.raw", ast_config_AST_MONITOR_DIR, recbase, (int) time(NULL));
      if ((fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, AST_FILE_MODE)) <= 0) {
         ast_log(LOG_WARNING, "Cannot open '%s' for recording\n", filename);
         fd = 0;
      }
   }
   res = common_exec(chan, &flags, volfactor, fd, mygroup, myenforced, args.spec, NULL, NULL, mailbox, name_context);
   if (fd)
      close(fd);
   if (oldwf && ast_set_write_format(chan, oldwf) < 0)
      ast_log(LOG_ERROR, "Could Not Set Write Format.\n");
   return res;
}
static int common_exec (struct ast_channel * chan, struct ast_flags * flags, int volfactor, const int fd, const char * mygroup, const char * myenforced, const char * spec, const char * exten, const char * context, const char * mailbox, const char * name_context) [static]
Definition at line 767 of file app_chanspy.c.
References ast_channel::_state, ARRAY_LEN, ast_answer(), ast_app_sayname(), ast_app_separate_args, ast_atomic_fetchadd_int(), ast_bridged_channel(), ast_channel_lock, AST_CHANNEL_NAME, ast_channel_setoption(), ast_channel_unlock, ast_check_hangup(), ast_clear_flag, ast_copy_string(), ast_debug, ast_fileexists(), AST_FLAG_SPYING, ast_get_channel_by_name_prefix_locked(), ast_goto_if_exists(), AST_MAX_CONTEXT, ast_mutex_destroy(), ast_mutex_init(), ast_mutex_lock(), ast_mutex_unlock(), AST_NAME_STRLEN, AST_OPTION_TXGAIN, ast_say_character_str(), ast_say_digits(), ast_set_flag, AST_STATE_UP, ast_streamfile(), ast_strlen_zero(), ast_test_flag, ast_waitfordigit(), ast_waitstream(), channel_spy(), chanspy_ds_free(), ast_channel::context, exitcontext, ext, chanspy_ds::lock, ast_channel::macrocontext, next_channel(), num, NUM_SPYGROUPS, OPTION_BRIDGED, OPTION_EXIT, OPTION_NAME, OPTION_NOTECH, OPTION_QUIET, pbx_builtin_getvar_helper(), s, S_OR, setup_chanspy_ds(), strcasestr(), strsep(), and chanspy_ds::unique_id.
Referenced by chanspy_exec(), and extenspy_exec().
{
   char nameprefix[AST_NAME_STRLEN];
   char peer_name[AST_NAME_STRLEN + 5];
   char exitcontext[AST_MAX_CONTEXT] = "";
   signed char zero_volume = 0;
   int waitms;
   int res;
   char *ptr;
   int num;
   int num_spyed_upon = 1;
   struct chanspy_ds chanspy_ds = { 0, };
   if (ast_test_flag(flags, OPTION_EXIT)) {
      const char *c;
      ast_channel_lock(chan);
      if ((c = pbx_builtin_getvar_helper(chan, "SPY_EXIT_CONTEXT"))) {
         ast_copy_string(exitcontext, c, sizeof(exitcontext));
      } else if (!ast_strlen_zero(chan->macrocontext)) {
         ast_copy_string(exitcontext, chan->macrocontext, sizeof(exitcontext));
      } else {
         ast_copy_string(exitcontext, chan->context, sizeof(exitcontext));
      }
      ast_channel_unlock(chan);
   }
   ast_mutex_init(&chanspy_ds.lock);
   snprintf(chanspy_ds.unique_id, sizeof(chanspy_ds.unique_id), "%d", ast_atomic_fetchadd_int(&next_unique_id_to_use, +1));
   if (chan->_state != AST_STATE_UP)
      ast_answer(chan);
   ast_set_flag(chan, AST_FLAG_SPYING); /* so nobody can spy on us while we are spying */
   waitms = 100;
   for (;;) {
      struct chanspy_ds *peer_chanspy_ds = NULL, *next_chanspy_ds = NULL;
      struct ast_channel *prev = NULL, *peer = NULL;
      if (!ast_test_flag(flags, OPTION_QUIET) && num_spyed_upon) {
         res = ast_streamfile(chan, "beep", chan->language);
         if (!res)
            res = ast_waitstream(chan, "");
         else if (res < 0) {
            ast_clear_flag(chan, AST_FLAG_SPYING);
            break;
         }
         if (!ast_strlen_zero(exitcontext)) {
            char tmp[2];
            tmp[0] = res;
            tmp[1] = '\0';
            if (!ast_goto_if_exists(chan, exitcontext, tmp, 1))
               goto exit;
            else
               ast_debug(2, "Exit by single digit did not work in chanspy. Extension %s does not exist in context %s\n", tmp, exitcontext);
         }
      }
      res = ast_waitfordigit(chan, waitms);
      if (res < 0) {
         ast_clear_flag(chan, AST_FLAG_SPYING);
         break;
      }
      if (!ast_strlen_zero(exitcontext)) {
         char tmp[2];
         tmp[0] = res;
         tmp[1] = '\0';
         if (!ast_goto_if_exists(chan, exitcontext, tmp, 1))
            goto exit;
         else
            ast_debug(2, "Exit by single digit did not work in chanspy. Extension %s does not exist in context %s\n", tmp, exitcontext);
      }
      /* reset for the next loop around, unless overridden later */
      waitms = 100;
      num_spyed_upon = 0;
      for (peer_chanspy_ds = next_channel(chan, prev, spec, exten, context, &chanspy_ds);
           peer_chanspy_ds;
          chanspy_ds_free(peer_chanspy_ds), prev = peer,
           peer_chanspy_ds = next_chanspy_ds ? next_chanspy_ds :
            next_channel(chan, prev, spec, exten, context, &chanspy_ds), next_chanspy_ds = NULL) {
         int igrp = !mygroup;
         int ienf = !myenforced;
         char *s;
         peer = peer_chanspy_ds->chan;
         ast_mutex_unlock(&peer_chanspy_ds->lock);
         if (peer == prev) {
            ast_channel_unlock(peer);
            chanspy_ds_free(peer_chanspy_ds);
            break;
         }
         if (ast_check_hangup(chan)) {
            ast_channel_unlock(peer);
            chanspy_ds_free(peer_chanspy_ds);
            break;
         }
         if (ast_test_flag(flags, OPTION_BRIDGED) && !ast_bridged_channel(peer)) {
            ast_channel_unlock(peer);
            continue;
         }
         if (ast_check_hangup(peer) || ast_test_flag(peer, AST_FLAG_SPYING)) {
            ast_channel_unlock(peer);
            continue;
         }
         if (mygroup) {
            int num_groups = 0;
            int num_mygroups = 0;
            char dup_group[512];
            char dup_mygroup[512];
            char *groups[NUM_SPYGROUPS];
            char *mygroups[NUM_SPYGROUPS];
            const char *group;
            int x;
            int y;
            ast_copy_string(dup_mygroup, mygroup, sizeof(dup_mygroup));
            num_mygroups = ast_app_separate_args(dup_mygroup, ':', mygroups,
               ARRAY_LEN(mygroups));
            if ((group = pbx_builtin_getvar_helper(peer, "SPYGROUP"))) {
               ast_copy_string(dup_group, group, sizeof(dup_group));
               num_groups = ast_app_separate_args(dup_group, ':', groups,
                  ARRAY_LEN(groups));
            }
            for (y = 0; y < num_mygroups; y++) {
               for (x = 0; x < num_groups; x++) {
                  if (!strcmp(mygroups[y], groups[x])) {
                     igrp = 1;
                     break;
                  }
               }
            }
         }
         if (!igrp) {
            ast_channel_unlock(peer);
            continue;
         }
         if (myenforced) {
            char ext[AST_CHANNEL_NAME + 3];
            char buffer[512];
            char *end;
            snprintf(buffer, sizeof(buffer) - 1, ":%s:", myenforced);
            ast_copy_string(ext + 1, peer->name, sizeof(ext) - 1);
            if ((end = strchr(ext, '-'))) {
               *end++ = ':';
               *end = '\0';
            }
            ext[0] = ':';
            if (strcasestr(buffer, ext)) {
               ienf = 1;
            }
         }
         if (!ienf) {
            continue;
         }
         strcpy(peer_name, "spy-");
         strncat(peer_name, peer->name, AST_NAME_STRLEN - 4 - 1);
         ptr = strchr(peer_name, '/');
         *ptr++ = '\0';
         ptr = strsep(&ptr, "-");
         for (s = peer_name; s < ptr; s++)
            *s = tolower(*s);
         /* We have to unlock the peer channel here to avoid a deadlock.
          * So, when we need to dereference it again, we have to lock the
          * datastore and get the pointer from there to see if the channel
          * is still valid. */
         ast_channel_unlock(peer);
         if (!ast_test_flag(flags, OPTION_QUIET)) {
            if (ast_test_flag(flags, OPTION_NAME)) {
               const char *local_context = S_OR(name_context, "default");
               const char *local_mailbox = S_OR(mailbox, ptr);
               res = ast_app_sayname(chan, local_mailbox, local_context);
            }
            if (!ast_test_flag(flags, OPTION_NAME) || res < 0) {
               if (!ast_test_flag(flags, OPTION_NOTECH)) {
                  if (ast_fileexists(peer_name, NULL, NULL) != -1) {
                     res = ast_streamfile(chan, peer_name, chan->language);
                     if (!res) {
                        res = ast_waitstream(chan, "");
                     }
                     if (res) {
                        chanspy_ds_free(peer_chanspy_ds);
                        break;
                     }
                  } else {
                     res = ast_say_character_str(chan, peer_name, "", chan->language);
                  }
               }
               if ((num = atoi(ptr)))
                  ast_say_digits(chan, atoi(ptr), "", chan->language);
            }
         }
         res = channel_spy(chan, peer_chanspy_ds, &volfactor, fd, flags, exitcontext);
         num_spyed_upon++;
         if (res == -1) {
            chanspy_ds_free(peer_chanspy_ds);
            goto exit;
         } else if (res == -2) {
            res = 0;
            chanspy_ds_free(peer_chanspy_ds);
            goto exit;
         } else if (res > 1 && spec) {
            struct ast_channel *next;
            snprintf(nameprefix, AST_NAME_STRLEN, "%s/%d", spec, res);
            if ((next = ast_get_channel_by_name_prefix_locked(nameprefix, strlen(nameprefix)))) {
               peer_chanspy_ds = chanspy_ds_free(peer_chanspy_ds);
               next_chanspy_ds = setup_chanspy_ds(next, &chanspy_ds);
            } else {
               /* stay on this channel, if it is still valid */
               ast_mutex_lock(&peer_chanspy_ds->lock);
               if (peer_chanspy_ds->chan) {
                  ast_channel_lock(peer_chanspy_ds->chan);
                  next_chanspy_ds = peer_chanspy_ds;
                  peer_chanspy_ds = NULL;
               } else {
                  /* the channel is gone */
                  ast_mutex_unlock(&peer_chanspy_ds->lock);
                  next_chanspy_ds = NULL;
               }
            }
            peer = NULL;
         }
      }
      if (res == -1 || ast_check_hangup(chan))
         break;
   }
exit:
   ast_clear_flag(chan, AST_FLAG_SPYING);
   ast_channel_setoption(chan, AST_OPTION_TXGAIN, &zero_volume, sizeof(zero_volume), 0);
   ast_mutex_lock(&chanspy_ds.lock);
   ast_mutex_unlock(&chanspy_ds.lock);
   ast_mutex_destroy(&chanspy_ds.lock);
   return res;
}
static int extenspy_exec (struct ast_channel * chan, void * data) [static]
Definition at line 1127 of file app_chanspy.c.
References AST_APP_ARG, ast_app_parse_options(), ast_clear_flag, ast_config_AST_MONITOR_DIR, AST_DECLARE_APP_ARGS, AST_FILE_MODE, AST_FLAGS_ALL, AST_FORMAT_SLINEAR, ast_log(), ast_set_flag, ast_set_write_format(), AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero(), ast_test_flag, common_exec(), ast_channel::context, context, exten, LOG_ERROR, LOG_NOTICE, LOG_WARNING, mailbox, OPT_ARG_ARRAY_SIZE, OPT_ARG_GROUP, OPT_ARG_NAME, OPT_ARG_RECORD, OPT_ARG_VOLUME, OPTION_GROUP, OPTION_NAME, OPTION_PRIVATE, OPTION_RECORD, OPTION_VOLUME, OPTION_WHISPER, and ast_channel::writeformat.
Referenced by load_module().
{
   char *ptr, *exten = NULL;
   char *mygroup = NULL;
   char *recbase = NULL;
   int fd = 0;
   struct ast_flags flags;
   int oldwf = 0;
   int volfactor = 0;
   int res;
   char *mailbox = NULL;
   char *name_context = NULL;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(context);
      AST_APP_ARG(options);
   );
   data = ast_strdupa(data);
   AST_STANDARD_APP_ARGS(args, data);
   if (!ast_strlen_zero(args.context) && (ptr = strchr(args.context, '@'))) {
      exten = args.context;
      *ptr++ = '\0';
      args.context = ptr;
   }
   if (ast_strlen_zero(args.context))
      args.context = ast_strdupa(chan->context);
   if (args.options) {
      char *opts[OPT_ARG_ARRAY_SIZE];
      ast_app_parse_options(spy_opts, &flags, opts, args.options);
      if (ast_test_flag(&flags, OPTION_GROUP))
         mygroup = opts[OPT_ARG_GROUP];
      if (ast_test_flag(&flags, OPTION_RECORD) &&
         !(recbase = opts[OPT_ARG_RECORD]))
         recbase = "chanspy";
      if (ast_test_flag(&flags, OPTION_VOLUME) && opts[OPT_ARG_VOLUME]) {
         int vol;
         if ((sscanf(opts[OPT_ARG_VOLUME], "%30d", &vol) != 1) || (vol > 4) || (vol < -4))
            ast_log(LOG_NOTICE, "Volume factor must be a number between -4 and 4\n");
         else
            volfactor = vol;
      }
      if (ast_test_flag(&flags, OPTION_PRIVATE))
         ast_set_flag(&flags, OPTION_WHISPER);
      if (ast_test_flag(&flags, OPTION_NAME)) {
         if (!ast_strlen_zero(opts[OPT_ARG_NAME])) {
            char *delimiter;
            if ((delimiter = strchr(opts[OPT_ARG_NAME], '@'))) {
               mailbox = opts[OPT_ARG_NAME];
               *delimiter++ = '\0';
               name_context = delimiter;
            } else {
               mailbox = opts[OPT_ARG_NAME];
            }
         }
      }
   } else
      ast_clear_flag(&flags, AST_FLAGS_ALL);
   oldwf = chan->writeformat;
   if (ast_set_write_format(chan, AST_FORMAT_SLINEAR) < 0) {
      ast_log(LOG_ERROR, "Could Not Set Write Format.\n");
      return -1;
   }
   if (recbase) {
      char filename[PATH_MAX];
      snprintf(filename, sizeof(filename), "%s/%s.%d.raw", ast_config_AST_MONITOR_DIR, recbase, (int) time(NULL));
      if ((fd = open(filename, O_CREAT | O_WRONLY | O_TRUNC, AST_FILE_MODE)) <= 0) {
         ast_log(LOG_WARNING, "Cannot open '%s' for recording\n", filename);
         fd = 0;
      }
   }
   res = common_exec(chan, &flags, volfactor, fd, mygroup, NULL, NULL, exten, args.context, mailbox, name_context);
   if (fd)
      close(fd);
   if (oldwf && ast_set_write_format(chan, oldwf) < 0)
      ast_log(LOG_ERROR, "Could Not Set Write Format.\n");
   return res;
}
static int load_module (void) [static]
Definition at line 1234 of file app_chanspy.c.
References ast_register_application_xml, chanspy_exec(), and extenspy_exec().
{
   int res = 0;
   res |= ast_register_application_xml(app_chan, chanspy_exec);
   res |= ast_register_application_xml(app_ext, extenspy_exec);
   return res;
}
static struct chanspy_ds* next_channel (struct ast_channel * chan, const struct ast_channel * last, const char * spec, const char * exten, const char * context, struct chanspy_ds * chanspy_ds) [static, read]
Definition at line 736 of file app_chanspy.c.
References ast_channel_unlock, ast_channel_walk_locked(), ast_strlen_zero(), ast_walk_channel_by_exten_locked(), ast_walk_channel_by_name_prefix_locked(), and setup_chanspy_ds().
Referenced by common_exec().
{
   struct ast_channel *next;
   const size_t pseudo_len = strlen("DAHDI/pseudo");
redo:
   if (!ast_strlen_zero(spec))
      next = ast_walk_channel_by_name_prefix_locked(last, spec, strlen(spec));
   else if (!ast_strlen_zero(exten))
      next = ast_walk_channel_by_exten_locked(last, exten, context);
   else
      next = ast_channel_walk_locked(last);
   if (!next)
      return NULL;
   if (!strncmp(next->name, "DAHDI/pseudo", pseudo_len)) {
      last = next;
      ast_channel_unlock(next);
      goto redo;
   } else if (next == chan) {
      last = next;
      ast_channel_unlock(next);
      goto redo;
   }
   return setup_chanspy_ds(next, chanspy_ds);
}
static struct chanspy_ds* setup_chanspy_ds (struct ast_channel * chan, struct chanspy_ds * chanspy_ds) [static, read]
Note:
Returns the channel in the chanspy_ds locked as well as the chanspy_ds locked
Definition at line 716 of file app_chanspy.c.
References ast_channel_datastore_add(), ast_channel_unlock, ast_datastore_alloc, ast_mutex_lock(), ast_mutex_unlock(), chanspy_ds::chan, chanspy_ds_free(), ast_datastore::data, chanspy_ds::lock, and chanspy_ds::unique_id.
Referenced by common_exec(), and next_channel().
{
   struct ast_datastore *datastore = NULL;
   ast_mutex_lock(&chanspy_ds->lock);
   if (!(datastore = ast_datastore_alloc(&chanspy_ds_info, chanspy_ds->unique_id))) {
      ast_mutex_unlock(&chanspy_ds->lock);
      chanspy_ds = chanspy_ds_free(chanspy_ds);
      ast_channel_unlock(chan);
      return NULL;
   }
   chanspy_ds->chan = chan;
   datastore->data = chanspy_ds;
   ast_channel_datastore_add(chan, datastore);
   return chanspy_ds;
}
static void* spy_alloc (struct ast_channel * chan, void * data) [static]
Definition at line 350 of file app_chanspy.c.
{
   /* just store the data pointer in the channel structure */
   return data;
}
static int spy_generate (struct ast_channel * chan, void * data, int len, int samples) [static]
Definition at line 361 of file app_chanspy.c.
References AST_AUDIOHOOK_DIRECTION_BOTH, AST_AUDIOHOOK_DIRECTION_READ, ast_audiohook_lock, ast_audiohook_read_frame(), AST_AUDIOHOOK_STATUS_RUNNING, ast_audiohook_unlock, AST_FORMAT_SLINEAR, ast_frfree, AST_LIST_NEXT, ast_log(), ast_test_flag, ast_write(), ast_frame::data, ast_frame::datalen, errno, f, chanspy_translation_helper::fd, LOG_WARNING, OPTION_READONLY, ast_frame::ptr, chanspy_translation_helper::spy_audiohook, and ast_audiohook::status.
{
   struct chanspy_translation_helper *csth = data;
   struct ast_frame *f, *cur;
   ast_audiohook_lock(&csth->spy_audiohook);
   if (csth->spy_audiohook.status != AST_AUDIOHOOK_STATUS_RUNNING) {
      /* Channel is already gone more than likely */
      ast_audiohook_unlock(&csth->spy_audiohook);
      return -1;
   }
   if (ast_test_flag(&csth->spy_audiohook, OPTION_READONLY)) {
      /* Option 'o' was set, so don't mix channel audio */
      f = ast_audiohook_read_frame(&csth->spy_audiohook, samples, AST_AUDIOHOOK_DIRECTION_READ, AST_FORMAT_SLINEAR);
   } else {
      f = ast_audiohook_read_frame(&csth->spy_audiohook, samples, AST_AUDIOHOOK_DIRECTION_BOTH, AST_FORMAT_SLINEAR);
   }
   ast_audiohook_unlock(&csth->spy_audiohook);
   if (!f)
      return 0;
   for (cur = f; cur; cur = AST_LIST_NEXT(cur, frame_list)) {
      if (ast_write(chan, cur)) {
         ast_frfree(f);
         return -1;
      }
      if (csth->fd) {
         if (write(csth->fd, cur->data.ptr, cur->datalen) < 0) {
            ast_log(LOG_WARNING, "write() failed: %s\n", strerror(errno));
         }
      }
   }
   ast_frfree(f);
   return 0;
}
static void spy_release (struct ast_channel * chan, void * data) [static]
Definition at line 356 of file app_chanspy.c.
{
   /* nothing to do */
}
static int start_spying (struct ast_channel * chan, const char * spychan_name, struct ast_audiohook * audiohook) [static]
Definition at line 409 of file app_chanspy.c.
References ast_audiohook_attach(), AST_AUDIOHOOK_SMALL_QUEUE, AST_AUDIOHOOK_TRIGGER_SYNC, ast_bridged_channel(), AST_FLAG_NBRIDGE, ast_log(), ast_set_flag, ast_softhangup(), AST_SOFTHANGUP_UNBRIDGE, ast_test_flag, and LOG_NOTICE.
Referenced by channel_spy().
{
   int res = 0;
   struct ast_channel *peer = NULL;
   ast_log(LOG_NOTICE, "Attaching %s to %s\n", spychan_name, chan->name);
   ast_set_flag(audiohook, AST_AUDIOHOOK_TRIGGER_SYNC | AST_AUDIOHOOK_SMALL_QUEUE);
   res = ast_audiohook_attach(chan, audiohook);
   if (!res && ast_test_flag(chan, AST_FLAG_NBRIDGE) && (peer = ast_bridged_channel(chan))) {
      ast_softhangup(peer, AST_SOFTHANGUP_UNBRIDGE);
   }
   return res;
}
static int unload_module (void) [static]
Definition at line 1224 of file app_chanspy.c.
References ast_unregister_application().
{
   int res = 0;
   res |= ast_unregister_application(app_chan);
   res |= ast_unregister_application(app_ext);
   return res;
}
Variable Documentation
const char* app_chan = "ChanSpy" [static]
Definition at line 292 of file app_chanspy.c.
const char* app_ext = "ExtenSpy" [static]
Definition at line 294 of file app_chanspy.c.
struct ast_datastore_info chanspy_ds_info [static]
Initial value:
 {
   .type = "chanspy",
   .destroy = chanspy_ds_destroy,
   .chan_fixup = chanspy_ds_chan_fixup,
}
Definition at line 678 of file app_chanspy.c.
enum { ... } chanspy_opt_args
enum { ... } chanspy_opt_flags
int next_unique_id_to_use = 0 [static]
Definition at line 339 of file app_chanspy.c.
struct ast_generator spygen [static]
Initial value:
 {
   .alloc = spy_alloc,
   .release = spy_release,
   .generate = spy_generate,
}
Definition at line 403 of file app_chanspy.c.