Wed May 5 15:22:06 2010
Asterisk developer's documentation
format_gsm.c File Reference
Save to raw, headerless GSM data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
#include "msgsm.h"
Defines
#define GSM_FRAME_SIZE 33
#define GSM_SAMPLES 160
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"Raw GSM data",.load=load_module,.unload=unload_module,.load_pri=10,)
static struct ast_frame * gsm_read (struct ast_filestream *s, int *whennext)
static int gsm_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t gsm_tell (struct ast_filestream *fs)
static int gsm_trunc (struct ast_filestream *fs)
static int gsm_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_format gsm_f
char gsm_silence []
Detailed Description
Save to raw, headerless GSM data.
File name extension: gsm
Definition in file format_gsm.c.
Define Documentation
#define GSM_FRAME_SIZE 33
Definition at line 40 of file format_gsm.c.
Referenced by gsm_read(), gsm_seek(), gsm_tell(), gsm_write(), wav_read(), and wav_write().
#define GSM_SAMPLES 160
Definition at line 41 of file format_gsm.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "Raw GSM data" , . load = load_module, . unload = unload_module, . load_pri = 10)
static struct ast_frame* gsm_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 51 of file format_gsm.c.
References AST_FORMAT_GSM, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, ast_frame::data, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, GSM_FRAME_SIZE, GSM_SAMPLES, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int res;
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_GSM;
   AST_FRAME_SET_BUFFER(&(s->fr), s->buf, AST_FRIENDLY_OFFSET, GSM_FRAME_SIZE)
   s->fr.mallocd = 0;
   if ((res = fread(s->fr.data.ptr, 1, GSM_FRAME_SIZE, s->f)) != GSM_FRAME_SIZE) {
      if (res)
         ast_log(LOG_WARNING, "Short read (%d) (%s)!\n", res, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples = GSM_SAMPLES;
   return &s->fr;
}
static int gsm_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 105 of file format_gsm.c.
References ast_log(), errno, ast_filestream::f, fwrite, GSM_FRAME_SIZE, GSM_SAMPLES, LOG_WARNING, ast_frame::offset, and SEEK_FORCECUR.
{
   off_t offset=0,min,cur,max,distance;
   min = 0;
   cur = ftello(fs->f);
   fseeko(fs->f, 0, SEEK_END);
   max = ftello(fs->f);
   /* have to fudge to frame here, so not fully to sample */
   distance = (sample_offset/GSM_SAMPLES) * GSM_FRAME_SIZE;
   if(whence == SEEK_SET)
      offset = distance;
   else if(whence == SEEK_CUR || whence == SEEK_FORCECUR)
      offset = distance + cur;
   else if(whence == SEEK_END)
      offset = max - distance;
   /* Always protect against seeking past the begining. */
   offset = (offset < min)?min:offset;
   if (whence != SEEK_FORCECUR) {
      offset = (offset > max)?max:offset;
   } else if (offset > max) {
      int i;
      fseeko(fs->f, 0, SEEK_END);
      for (i=0; i< (offset - max) / GSM_FRAME_SIZE; i++) {
         if (!fwrite(gsm_silence, 1, GSM_FRAME_SIZE, fs->f)) {
            ast_log(LOG_WARNING, "fwrite() failed: %s\n", strerror(errno));
         }
      }
   }
   return fseeko(fs->f, offset, SEEK_SET);
}
static off_t gsm_tell (struct ast_filestream * fs) [static]
Definition at line 142 of file format_gsm.c.
References ast_filestream::f, GSM_FRAME_SIZE, GSM_SAMPLES, and ast_frame::offset.
{
   off_t offset = ftello(fs->f);
   return (offset/GSM_FRAME_SIZE)*GSM_SAMPLES;
}
static int gsm_trunc (struct ast_filestream * fs) [static]
Definition at line 137 of file format_gsm.c.
References ast_filestream::f.
{
   return ftruncate(fileno(fs->f), ftello(fs->f));
}
static int gsm_write (struct ast_filestream * fs, struct ast_frame * f) [static]
Definition at line 68 of file format_gsm.c.
References AST_FORMAT_GSM, AST_FRAME_VOICE, ast_log(), conv65(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, GSM_FRAME_SIZE, len(), LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res;
   unsigned char gsm[2*GSM_FRAME_SIZE];
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_GSM) {
      ast_log(LOG_WARNING, "Asked to write non-GSM frame (%d)!\n", f->subclass);
      return -1;
   }
   if (!(f->datalen % 65)) {
      /* This is in MSGSM format, need to be converted */
      int len=0;
      while(len < f->datalen) {
         conv65(f->data.ptr + len, gsm);
         if ((res = fwrite(gsm, 1, 2*GSM_FRAME_SIZE, fs->f)) != 2*GSM_FRAME_SIZE) {
            ast_log(LOG_WARNING, "Bad write (%d/66): %s\n", res, strerror(errno));
            return -1;
         }
         len += 65;
      }
   } else {
      if (f->datalen % GSM_FRAME_SIZE) {
         ast_log(LOG_WARNING, "Invalid data length, %d, should be multiple of 33\n", f->datalen);
         return -1;
      }
      if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
            ast_log(LOG_WARNING, "Bad write (%d/33): %s\n", res, strerror(errno));
            return -1;
      }
   }
   return 0;
}
static int load_module (void) [static]
Definition at line 160 of file format_gsm.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&gsm_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 167 of file format_gsm.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(gsm_f.name);
}
Variable Documentation
struct ast_format gsm_f [static]
Definition at line 148 of file format_gsm.c.
char gsm_silence[]
Initial value:
{0xD8,0x20,0xA2,0xE1,0x5A,0x50,0x00,0x49,0x24,0x92,0x49,0x24,0x50,0x00,0x49
,0x24,0x92,0x49,0x24,0x50,0x00,0x49,0x24,0x92,0x49,0x24,0x50,0x00,0x49,0x24
,0x92,0x49,0x24}
Definition at line 45 of file format_gsm.c.