Wed May 5 15:22:07 2010
Asterisk developer's documentation
format_jpeg.c File Reference
JPEG File format support.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/image.h"
#include "asterisk/endian.h"
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"jpeg (joint picture experts group) image format",.load=load_module,.unload=unload_module,.load_pri=10,)
static int jpeg_identify (int fd)
static struct ast_frame * jpeg_read_image (int fd, int len)
static int jpeg_write_image (int fd, struct ast_frame *fr)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_imager jpeg_format
Detailed Description
JPEG File format support.
File name extension: jpeg, jpg
Definition in file format_jpeg.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "jpeg (joint picture experts group) image format" , . load = load_module, . unload = unload_module, . load_pri = 10)
static int jpeg_identify (int fd) [static]
Definition at line 58 of file format_jpeg.c.
References buf.
{
   char buf[10];
   int res;
   res = read(fd, buf, sizeof(buf));
   if (res < sizeof(buf))
      return 0;
   if (memcmp(buf + 6, "JFIF", 4))
      return 0;
   return 1;
}
static struct ast_frame* jpeg_read_image (int fd, int len) [static, read]
Definition at line 36 of file format_jpeg.c.
References AST_FORMAT_JPEG, AST_FRAME_IMAGE, ast_frisolate(), ast_log(), buf, ast_frame::data, ast_frame::datalen, errno, ast_frame::frametype, LOG_WARNING, ast_frame::ptr, ast_frame::src, and ast_frame::subclass.
{
   struct ast_frame fr;
   int res;
   char buf[65536];
   if (len > sizeof(buf) || len < 0) {
      ast_log(LOG_WARNING, "JPEG image too large to read\n");
      return NULL;
   }
   res = read(fd, buf, len);
   if (res < len) {
      ast_log(LOG_WARNING, "Only read %d of %d bytes: %s\n", res, len, strerror(errno));
   }
   memset(&fr, 0, sizeof(fr));
   fr.frametype = AST_FRAME_IMAGE;
   fr.subclass = AST_FORMAT_JPEG;
   fr.data.ptr = buf;
   fr.src = "JPEG Read";
   fr.datalen = len;
   return ast_frisolate(&fr);
}
static int jpeg_write_image (int fd, struct ast_frame * fr) [static]
Definition at line 70 of file format_jpeg.c.
References AST_FORMAT_JPEG, AST_FRAME_IMAGE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_frame::frametype, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res=0;
   if (fr->frametype != AST_FRAME_IMAGE) {
      ast_log(LOG_WARNING, "Not an image\n");
      return -1;
   }
   if (fr->subclass != AST_FORMAT_JPEG) {
      ast_log(LOG_WARNING, "Not a jpeg image\n");
      return -1;
   }
   if (fr->datalen) {
      res = write(fd, fr->data.ptr, fr->datalen);
      if (res != fr->datalen) {
         ast_log(LOG_WARNING, "Only wrote %d of %d bytes: %s\n", res, fr->datalen, strerror(errno));
         return -1;
      }
   }
   return res;
}
static int load_module (void) [static]
Definition at line 101 of file format_jpeg.c.
References ast_image_register(), AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_image_register(&jpeg_format))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 108 of file format_jpeg.c.
References ast_image_unregister().
{
   ast_image_unregister(&jpeg_format);
   return 0;
}
Variable Documentation
struct ast_imager jpeg_format [static]
Definition at line 91 of file format_jpeg.c.