Wed May 5 15:22:07 2010
Asterisk developer's documentation
format_sln.c File Reference
RAW SLINEAR Format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
Defines
#define BUF_SIZE 320
#define SLIN_SAMPLES 160
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"Raw Signed Linear Audio support (SLN)",.load=load_module,.unload=unload_module,.load_pri=10,)
static int load_module (void)
static struct ast_frame * slinear_read (struct ast_filestream *s, int *whennext)
static int slinear_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t slinear_tell (struct ast_filestream *fs)
static int slinear_trunc (struct ast_filestream *fs)
static int slinear_write (struct ast_filestream *fs, struct ast_frame *f)
static int unload_module (void)
Variables
static struct ast_format slin_f
Detailed Description
RAW SLINEAR Format.
File name extensions: sln, raw
Definition in file format_sln.c.
Define Documentation
#define BUF_SIZE 320
Definition at line 33 of file format_sln.c.
#define SLIN_SAMPLES 160
Definition at line 34 of file format_sln.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "Raw Signed Linear Audio support (SLN)" , . load = load_module, . unload = unload_module, . load_pri = 10)
static int load_module (void) [static]
Definition at line 118 of file format_sln.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&slin_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static struct ast_frame* slinear_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 36 of file format_sln.c.
References AST_FORMAT_SLINEAR, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int res;
   /* Send a frame from the file to the appropriate channel */
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_SLINEAR;
   s->fr.mallocd = 0;
   AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
   if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) < 1) {
      if (res)
         ast_log(LOG_WARNING, "Short read (%d) (%s)!\n", res, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples = res/2;
   s->fr.datalen = res;
   return &s->fr;
}
static int slinear_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 73 of file format_sln.c.
References ast_filestream::f, ast_frame::offset, and SEEK_FORCECUR.
{
   off_t offset=0,min,cur,max;
   min = 0;
   sample_offset <<= 1;
   cur = ftello(fs->f);
   fseeko(fs->f, 0, SEEK_END);
   max = ftello(fs->f);
   if (whence == SEEK_SET)
      offset = sample_offset;
   else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
      offset = sample_offset + cur;
   else if (whence == SEEK_END)
      offset = max - sample_offset;
   if (whence != SEEK_FORCECUR) {
      offset = (offset > max)?max:offset;
   }
   /* always protect against seeking past begining. */
   offset = (offset < min)?min:offset;
   return fseeko(fs->f, offset, SEEK_SET);
}
static off_t slinear_tell (struct ast_filestream * fs) [static]
Definition at line 101 of file format_sln.c.
References ast_filestream::f.
{
   return ftello(fs->f) / 2;
}
static int slinear_trunc (struct ast_filestream * fs) [static]
Definition at line 96 of file format_sln.c.
References ast_filestream::f.
{
   return ftruncate(fileno(fs->f), ftello(fs->f));
}
static int slinear_write (struct ast_filestream * fs, struct ast_frame * f) [static]
Definition at line 55 of file format_sln.c.
References AST_FORMAT_SLINEAR, AST_FRAME_VOICE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res;
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_SLINEAR) {
      ast_log(LOG_WARNING, "Asked to write non-slinear frame (%d)!\n", f->subclass);
      return -1;
   }
   if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
         ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
         return -1;
   }
   return 0;
}
static int unload_module (void) [static]
Definition at line 125 of file format_sln.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(slin_f.name);
}
Variable Documentation
struct ast_format slin_f [static]
Definition at line 106 of file format_sln.c.