Wed May 5 15:22:07 2010
Asterisk developer's documentation
format_ilbc.c File Reference
Save to raw, headerless iLBC data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
Defines
#define ILBC_BUF_SIZE 50
#define ILBC_SAMPLES 240
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"Raw iLBC data",.load=load_module,.unload=unload_module,.load_pri=10,)
static struct ast_frame * ilbc_read (struct ast_filestream *s, int *whennext)
static int ilbc_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t ilbc_tell (struct ast_filestream *fs)
static int ilbc_trunc (struct ast_filestream *fs)
static int ilbc_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_format ilbc_f
Detailed Description
Save to raw, headerless iLBC data.
File name extension: ilbc
Definition in file format_ilbc.c.
Define Documentation
#define ILBC_BUF_SIZE 50
Definition at line 40 of file format_ilbc.c.
Referenced by ilbc_read(), ilbc_seek(), and ilbc_tell().
#define ILBC_SAMPLES 240
Definition at line 41 of file format_ilbc.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "Raw iLBC data" , . load = load_module, . unload = unload_module, . load_pri = 10)
static struct ast_frame* ilbc_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 43 of file format_ilbc.c.
References AST_FORMAT_ILBC, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, ILBC_BUF_SIZE, ILBC_SAMPLES, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int res;
   /* Send a frame from the file to the appropriate channel */
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_ILBC;
   s->fr.mallocd = 0;
   AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, ILBC_BUF_SIZE);
   if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
      if (res)
         ast_log(LOG_WARNING, "Short read (%d) (%s)!\n", res, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples = ILBC_SAMPLES;
   return &s->fr;
}
static int ilbc_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 82 of file format_ilbc.c.
References ast_filestream::f, ILBC_BUF_SIZE, ILBC_SAMPLES, ast_frame::offset, and SEEK_FORCECUR.
{
   long bytes;
   off_t min,cur,max,offset=0;
   min = 0;
   cur = ftello(fs->f);
   fseeko(fs->f, 0, SEEK_END);
   max = ftello(fs->f);
   bytes = ILBC_BUF_SIZE * (sample_offset / ILBC_SAMPLES);
   if (whence == SEEK_SET)
      offset = bytes;
   else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
      offset = cur + bytes;
   else if (whence == SEEK_END)
      offset = max - bytes;
   if (whence != SEEK_FORCECUR) {
      offset = (offset > max)?max:offset;
   }
   /* protect against seeking beyond begining. */
   offset = (offset < min)?min:offset;
   if (fseeko(fs->f, offset, SEEK_SET) < 0)
      return -1;
   return 0;
}
static off_t ilbc_tell (struct ast_filestream * fs) [static]
Definition at line 116 of file format_ilbc.c.
References ast_filestream::f, ILBC_BUF_SIZE, ILBC_SAMPLES, and ast_frame::offset.
{
   off_t offset = ftello(fs->f);
   return (offset/ILBC_BUF_SIZE)*ILBC_SAMPLES;
}
static int ilbc_trunc (struct ast_filestream * fs) [static]
Definition at line 108 of file format_ilbc.c.
References ast_filestream::f.
{
   /* Truncate file to current length */
   if (ftruncate(fileno(fs->f), ftello(fs->f)) < 0)
      return -1;
   return 0;
}
static int ilbc_write (struct ast_filestream * fs, struct ast_frame * f) [static]
Definition at line 60 of file format_ilbc.c.
References AST_FORMAT_ILBC, AST_FRAME_VOICE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res;
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_ILBC) {
      ast_log(LOG_WARNING, "Asked to write non-iLBC frame (%d)!\n", f->subclass);
      return -1;
   }
   if (f->datalen % 50) {
      ast_log(LOG_WARNING, "Invalid data length, %d, should be multiple of 50\n", f->datalen);
      return -1;
   }
   if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
         ast_log(LOG_WARNING, "Bad write (%d/50): %s\n", res, strerror(errno));
         return -1;
   }
   return 0;
}
static int load_module (void) [static]
Definition at line 134 of file format_ilbc.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&ilbc_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 141 of file format_ilbc.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(ilbc_f.name);
}
Variable Documentation
struct ast_format ilbc_f [static]
Definition at line 122 of file format_ilbc.c.