Wed May 5 15:22:10 2010
Asterisk developer's documentation
func_sha1.c File Reference
SHA1 digest related dialplan functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"SHA-1 computation dialplan function")
static int load_module (void)
static int sha1 (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_custom_function sha1_function
Detailed Description
SHA1 digest related dialplan functions.
Author:
Claude Patry <cpatry@gmail.com>
Definition in file func_sha1.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "SHA-1 computation dialplan function")
static int load_module (void) [static]
Definition at line 84 of file func_sha1.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&sha1_function);
}
static int sha1 (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) [static]
Definition at line 53 of file func_sha1.c.
References ast_log(), ast_sha1_hash(), ast_strlen_zero(), LOG_ERROR, and LOG_WARNING.
{
   *buf = '\0';
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Syntax: SHA1(<data>) - missing argument!\n");
      return -1;
   }
   if (len >= 41)
      ast_sha1_hash(buf, data);
   else {
      ast_log(LOG_ERROR,
            "Insufficient space to produce SHA1 hash result (%d < 41)\n",
            (int) len);
   }
   return 0;
}
static int unload_module (void) [static]
Definition at line 79 of file func_sha1.c.
References ast_custom_function_unregister().
{
   return ast_custom_function_unregister(&sha1_function);
}
Variable Documentation
struct ast_custom_function sha1_function [static]
Initial value:
 {
   .name = "SHA1",
   .read = sha1,
}
Definition at line 74 of file func_sha1.c.