Wed May 5 15:22:10 2010
Asterisk developer's documentation
func_shell.c File Reference
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Returns the output of a shell command")
static int load_module (void)
static int shell_helper (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_custom_function shell_function
Detailed Description
SHELL function to return the value of a system call.
Note:
Inspiration and Guidance from Russell! Thank You!
Author:
Brandon Kruse <bkruse@digium.com>
Definition in file func_shell.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Returns the output of a shell command")
static int load_module (void) [static]
Definition at line 98 of file func_shell.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&shell_function);
}
static int shell_helper (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) [static]
Definition at line 38 of file func_shell.c.
References ast_autoservice_start(), ast_autoservice_stop(), ast_log(), ast_strlen_zero(), and LOG_WARNING.
{
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Missing Argument!  Example:  Set(foo=${SHELL(echo \"bar\")})\n");
      return -1;
   }
   if (chan)
      ast_autoservice_start(chan);
   if (len >= 1) {
      FILE *ptr;
      char plbuff[4096];
      ptr = popen(data, "r");
      while (fgets(plbuff, sizeof(plbuff), ptr)) {
         strncat(buf, plbuff, len - strlen(buf) - 1);
      }
      pclose(ptr);
   }
   if (chan)
      ast_autoservice_stop(chan);
   return 0;
}
static int unload_module (void) [static]
Definition at line 93 of file func_shell.c.
References ast_custom_function_unregister().
{
   return ast_custom_function_unregister(&shell_function);
}
Variable Documentation
struct ast_custom_function shell_function [static]
Initial value:
 {
   .name = "SHELL",
   .read = shell_helper,
}
Definition at line 88 of file func_shell.c.