Wed May 5 15:22:10 2010
Asterisk developer's documentation
func_version.c File Reference
Return the current Version strings.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/ast_version.h"
#include "asterisk/build.h"
Functions
static int acf_version_exec (struct ast_channel *chan, const char *cmd, char *parse, char *buffer, size_t buflen)
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Get Asterisk Version/Build Info")
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_custom_function acf_version
Detailed Description
Return the current Version strings.
Author:
Steve Murphy (murf@digium.com)
Definition in file func_version.c.
Function Documentation
static int acf_version_exec (struct ast_channel * chan, const char * cmd, char * parse, char * buffer, size_t buflen) [static]
Definition at line 80 of file func_version.c.
References AST_APP_ARG, ast_copy_string(), ast_debug, AST_DECLARE_APP_ARGS, ast_get_version(), ast_get_version_num(), AST_STANDARD_APP_ARGS, ast_strlen_zero(), BUILD_DATE, BUILD_HOSTNAME, BUILD_KERNEL, BUILD_MACHINE, BUILD_OS, and BUILD_USER.
{
   const char *response_char = ast_get_version();
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(info);
   );
   AST_STANDARD_APP_ARGS(args, parse);
   if (!ast_strlen_zero(args.info) ) {
      if (!strcasecmp(args.info,"ASTERISK_VERSION_NUM"))
         response_char = ast_get_version_num();
      else if (!strcasecmp(args.info,"BUILD_USER"))
         response_char = BUILD_USER;
      else if (!strcasecmp(args.info,"BUILD_HOSTNAME"))
         response_char = BUILD_HOSTNAME;
      else if (!strcasecmp(args.info,"BUILD_MACHINE"))
         response_char = BUILD_MACHINE;
      else if (!strcasecmp(args.info,"BUILD_KERNEL"))
         response_char = BUILD_KERNEL;
      else if (!strcasecmp(args.info,"BUILD_OS"))
         response_char = BUILD_OS;
      else if (!strcasecmp(args.info,"BUILD_DATE"))
         response_char = BUILD_DATE;
   }
   ast_debug(1, "VERSION returns %s result, given %s argument\n", response_char, args.info);
   ast_copy_string(buffer, response_char, buflen);
   return 0;
}
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Get Asterisk Version/Build Info")
static int load_module (void) [static]
Definition at line 126 of file func_version.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&acf_version);
}
static int unload_module (void) [static]
Definition at line 119 of file func_version.c.
References ast_custom_function_unregister().
{
   ast_custom_function_unregister(&acf_version);
   return 0;
}
Variable Documentation
struct ast_custom_function acf_version [static]
Initial value:
 {
   .name = "VERSION",
   .read = acf_version_exec,
}
Definition at line 114 of file func_version.c.