Wed May 5 15:22:09 2010
Asterisk developer's documentation
func_base64.c File Reference
Use the base64 as functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/utils.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"base64 encode/decode dialplan functions")
static int base64_decode (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int base64_encode (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_custom_function base64_decode_function
static struct ast_custom_function base64_encode_function
Detailed Description
Use the base64 as functions.
Definition in file func_base64.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "base64 encode/decode dialplan functions")
static int base64_decode (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) [static]
Definition at line 75 of file func_base64.c.
References ast_base64decode(), ast_log(), ast_strlen_zero(), and LOG_WARNING.
{
   int decoded_len;
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Syntax: BASE64_DECODE(<base_64 string>) - missing argument!\n");
      return -1;
   }
   decoded_len = ast_base64decode((unsigned char *) buf, data, len);
   if (decoded_len <= (len - 1)) {     /* if not truncated, */
      buf[decoded_len] = '\0';
   } else {
      buf[len - 1] = '\0';
   }
   return 0;
}
static int base64_encode (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) [static]
Definition at line 62 of file func_base64.c.
References ast_base64encode(), ast_log(), ast_strlen_zero(), and LOG_WARNING.
{
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Syntax: BASE64_ENCODE(<data>) - missing argument!\n");
      return -1;
   }
   ast_base64encode(buf, (unsigned char *) data, strlen(data), len);
   return 0;
}
static int load_module (void) [static]
Definition at line 111 of file func_base64.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&base64_encode_function) |
      ast_custom_function_register(&base64_decode_function);
}
static int unload_module (void) [static]
Definition at line 105 of file func_base64.c.
References ast_custom_function_unregister().
{
   return ast_custom_function_unregister(&base64_encode_function) |
      ast_custom_function_unregister(&base64_decode_function);
}
Variable Documentation
struct ast_custom_function base64_decode_function [static]
Initial value:
 {
   .name = "BASE64_DECODE",
   .read = base64_decode,
}
Definition at line 100 of file func_base64.c.
struct ast_custom_function base64_encode_function [static]
Initial value:
 {
   .name = "BASE64_ENCODE",
   .read = base64_encode,
}
Definition at line 95 of file func_base64.c.