Wed May 5 15:22:21 2010
Asterisk developer's documentation
logger.h File Reference
Support for logging to various files, console and syslog Configuration in file logger.conf.
#include "asterisk/options.h"
Defines
#define __LOG_DEBUG 0
#define __LOG_DTMF 6
#define __LOG_ERROR 4
#define __LOG_EVENT 1
#define __LOG_NOTICE 2
#define __LOG_VERBOSE 5
#define __LOG_WARNING 3
#define _A_ __FILE__, __LINE__, __PRETTY_FUNCTION__
#define ast_debug(level,...)
Log a DEBUG message.
#define AST_LOG_DEBUG __LOG_DEBUG, _A_
#define AST_LOG_DTMF __LOG_DTMF, _A_
#define AST_LOG_ERROR __LOG_ERROR, _A_
#define AST_LOG_EVENT __LOG_EVENT, _A_
#define AST_LOG_NOTICE __LOG_NOTICE, _A_
#define AST_LOG_WARNING __LOG_WARNING, _A_
#define ast_verb(level,...)
#define ast_verbose(...) __ast_verbose(__FILE__, __LINE__, __PRETTY_FUNCTION__, __VA_ARGS__)
#define ast_verbose_ap(fmt, ap) __ast_verbose_ap(__FILE__, __LINE__, __PRETTY_FUNCTION__, fmt, ap)
#define DEBUG_M(a)
#define EVENTLOG "event_log"
#define LOG_DEBUG __LOG_DEBUG, _A_
#define LOG_DTMF __LOG_DTMF, _A_
#define LOG_ERROR __LOG_ERROR, _A_
#define LOG_EVENT __LOG_EVENT, _A_
#define LOG_NOTICE __LOG_NOTICE, _A_
#define LOG_VERBOSE __LOG_VERBOSE, _A_
#define LOG_VERBOSE __LOG_VERBOSE, _A_
#define LOG_WARNING __LOG_WARNING, _A_
#define NUMLOGLEVELS 6
#define QUEUELOG "queue_log"
#define VERBOSE_PREFIX_1 " "
#define VERBOSE_PREFIX_2 " == "
#define VERBOSE_PREFIX_3 " -- "
#define VERBOSE_PREFIX_4 " > "
#define VERBOSITY_ATLEAST(level) (option_verbose >= (level) || (ast_opt_verb_file && ast_verbose_get_by_file(__FILE__) >= (level)))
Functions
void __ast_verbose (const char *file, int line, const char *func, const char *fmt,...)
This works like ast_log, but prints verbose messages to the console depending on verbosity level set. ast_verbose(VERBOSE_PREFIX_3 "Whatever %s is happening\n", "nothing"); This will print the message to the console if the verbose level is set to a level >= 3 Note the abscence of a comma after the VERBOSE_PREFIX_3. This is important. VERBOSE_PREFIX_1 through VERBOSE_PREFIX_3 are defined.
void __ast_verbose_ap (const char *file, int line, const char *func, const char *fmt, va_list ap)
void ast_backtrace (void)
void ast_child_verbose (int level, const char *fmt,...)
void ast_console_puts (const char *string)
void ast_console_puts_mutable (const char *string, int level)
log the string to the console, and all attached console clients
void ast_console_toggle_loglevel (int fd, int level, int state)
void ast_console_toggle_mute (int fd, int silent)
mute or unmute a console from logging
unsigned int ast_debug_get_by_file (const char *file)
Get the debug level for a file.
void ast_log (int level, const char *file, int line, const char *function, const char *fmt,...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
void ast_queue_log (const char *queuename, const char *callid, const char *agent, const char *event, const char *fmt,...)
int ast_register_verbose (void(*verboser)(const char *string)) attribute_warn_unused_result
int ast_unregister_verbose (void(*verboser)(const char *string)) attribute_warn_unused_result
unsigned int ast_verbose_get_by_file (const char *file)
Get the debug level for a file.
int logger_reload (void)
Reload logger without rotating log files.
Detailed Description
Support for logging to various files, console and syslog Configuration in file logger.conf.
Definition in file logger.h.
Define Documentation
#define __LOG_DEBUG 0
Definition at line 118 of file logger.h.
Referenced by ast_log(), ast_log_vsyslog(), handle_logger_show_channels(), log_exec(), and make_components().
#define __LOG_DTMF 6
Definition at line 184 of file logger.h.
Referenced by ast_log_vsyslog(), handle_logger_show_channels(), log_exec(), and make_components().
#define __LOG_ERROR 4
Definition at line 162 of file logger.h.
Referenced by handle_logger_show_channels(), log_exec(), and make_components().
#define __LOG_EVENT 1
Definition at line 129 of file logger.h.
Referenced by handle_logger_show_channels(), log_exec(), logger_print_normal(), and make_components().
#define __LOG_NOTICE 2
Definition at line 140 of file logger.h.
Referenced by handle_logger_show_channels(), log_exec(), and make_components().
#define __LOG_VERBOSE 5
Definition at line 173 of file logger.h.
Referenced by __ast_verbose_ap(), ast_log(), ast_log_vsyslog(), handle_logger_show_channels(), log_exec(), logger_print_normal(), make_components(), and network_verboser().
#define __LOG_WARNING 3
Definition at line 151 of file logger.h.
Referenced by handle_logger_show_channels(), log_exec(), and make_components().
#define _A_ __FILE__, __LINE__, __PRETTY_FUNCTION__
Definition at line 113 of file logger.h.
#define ast_debug (level, ...)
Value:
do {       \
   if (option_debug >= (level) || (ast_opt_dbg_file && ast_debug_get_by_file(__FILE__) >= (level)) ) \
      ast_log(AST_LOG_DEBUG, __VA_ARGS__); \
} while (0)
Log a DEBUG message.
Parameters:
level The minimum value of option_debug for this message to get logged
Definition at line 213 of file logger.h.
Referenced by __adsi_transmit_messages(), __ast_answer(), __ast_check_signature_bin(), __ast_context_destroy(), __ast_dsp_call_progress(), __ast_pbx_run(), __ast_play_and_record(), __ast_read(), __dahdi_exception(), __expire_registry(), __find_callno(), __init_manager(), __oh323_destroy(), __oh323_rtp_create(), __oh323_update_info(), __schedule_action(), __send_lagrq(), __send_ping(), __sip_ack(), __sip_autodestruct(), __sip_destroy(), __sip_reliable_xmit(), __sip_semi_ack(), __sip_xmit(), __ssl_setup(), _ast_adsi_begin_download(), _ast_adsi_load_session(), _ast_adsi_transmit_message_full(), _ast_device_state(), _macro_exec(), _sip_tcp_helper_thread(), access_counter_file(), acf_curl_exec(), acf_curlopt_read(), acf_curlopt_write(), acf_odbc_read(), acf_rand_exec(), acf_version_exec(), action_waitevent(), add_email_attachment(), add_realm_authentication(), add_sdp(), add_sip_domain(), adsi_load_vmail(), agent_bridgedchannel(), agent_call(), agent_cont_sleep(), agent_hangup(), agent_read(), agent_request(), agent_write(), agi_exec_full(), aji_act_hook(), aji_handle_presence(), aji_recv(), aji_recv_loop(), aji_tls_handshake(), alarmreceiver_exec(), alloc_sub(), alsa_card_init(), alsa_write(), answer_call(), app_exec(), append_transaction(), append_var_and_value_to_filter(), array(), ast_add_extension2_lockopt(), ast_add_hint_nolock(), ast_append_ha(), ast_apply_ha(), ast_backtrace(), ast_bridge_call(), ast_bridge_destroy(), ast_bridge_features_enable(), ast_bridge_handle_trip(), ast_bridge_merge(), ast_bridge_new(), ast_cdr_detach(), ast_cdr_submit_batch(), ast_channel_bridge(), ast_channel_free(), ast_channel_inherit_variables(), ast_channel_masquerade(), ast_channel_register(), ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), ast_channel_unregister(), ast_codec_choose(), ast_config_text_file_save(), ast_context_find_or_create(), ast_control_streamfile(), ast_db_del(), ast_db_get(), ast_dial_run(), ast_do_masquerade(), ast_dsp_busydetect(), ast_dsp_process(), ast_dsp_set_busy_pattern(), ast_eivr_setvariable(), ast_find_ourip(), ast_generic_bridge(), ast_get_encoded_char(), ast_get_enum(), ast_get_txt(), ast_hangup(), ast_iax2_new(), ast_indicate_data(), ast_internal_timing_enabled(), ast_io_add(), ast_io_dump(), ast_io_wait(), ast_ivr_menu_run_internal(), AST_LIST_HEAD_NOLOCK(), ast_lock_path_flock(), ast_lock_path_lockfile(), ast_moh_files_next(), ast_monitor_change_fname(), ast_monitor_start(), ast_monitor_stop(), ast_ouraddrfor(), ast_parse_allow_disallow(), ast_parse_arg(), ast_pickup_call(), ast_prod(), ast_read_generator_actions(), ast_rtcp_read(), ast_rtp_bridge(), ast_rtp_early_bridge(), ast_rtp_make_compatible(), ast_rtp_raw_write(), ast_rtp_read(), ast_rtp_write(), ast_say_date_with_format_da(), ast_say_date_with_format_de(), ast_say_date_with_format_en(), ast_say_date_with_format_es(), ast_say_date_with_format_fr(), ast_say_date_with_format_gr(), ast_say_date_with_format_he(), ast_say_date_with_format_it(), ast_say_date_with_format_nl(), ast_say_date_with_format_pl(), ast_say_date_with_format_pt(), ast_say_date_with_format_zh(), ast_say_enumeration_full_da(), ast_say_enumeration_full_de(), ast_say_enumeration_full_en(), ast_say_number_full_da(), ast_say_number_full_de(), ast_say_number_full_en(), ast_say_number_full_en_GB(), ast_say_number_full_es(), ast_say_number_full_fr(), ast_say_number_full_gr(), ast_say_number_full_he(), ast_say_number_full_hu(), ast_say_number_full_it(), ast_say_number_full_nl(), ast_say_number_full_no(), ast_say_number_full_ru(), ast_say_number_full_se(), ast_say_number_full_zh(), ast_sched_add_variable(), ast_sched_del(), ast_sched_dump(), ast_sched_runq(), ast_sched_wait(), ast_sched_when(), ast_search_dns(), ast_senddigit_begin(), ast_set_default_eid(), ast_settimeout(), ast_sip_ouraddrfor(), ast_softhangup_nolock(), ast_streamfile(), ast_tcptls_client_create(), ast_tcptls_server_start(), ast_tcptls_server_stop(), ast_tone_detect_init(), ast_udptl_bridge(), ast_udptl_read(), ast_unlock_path_lockfile(), ast_wait_for_output(), ast_write(), ast_writestream(), attempt_transfer(), audiohook_inheritance_fixup(), audiohook_read_frame_both(), authenticate(), available(), background_detect_exec(), bridge_array_add(), bridge_array_remove(), bridge_channel_dtmf_stream(), bridge_channel_feature(), bridge_channel_join(), bridge_channel_join_multithreaded(), bridge_channel_join_singlethreaded(), bridge_check_dissolve(), bridge_exec(), bridge_make_compatible(), bridge_native_loop(), bridge_p2p_loop(), bridge_p2p_rtp_write(), bridge_thread(), build_peer(), build_reply_digest(), build_route(), build_transactions(), builtin_atxfer(), cache_get_callno_locked(), cache_lookup_internal(), cache_save_hint(), calc_rxstamp(), calc_timestamp(), callerid_feed_jp(), callerid_get_dtmf(), calltoken_required(), cdr_handler(), chan_ringing(), change_t38_state(), channel_find_locked(), channel_spy(), check_availability(), check_beep(), check_key(), check_match(), check_password(), check_peer_ok(), check_pendings(), check_provisioning(), check_srcaddr(), cleaned_basedn(), cleanup_connection(), cli_console_dial(), cli_odbc_read(), cli_odbc_write(), close_mailbox(), common_exec(), compare_weight(), conf_add(), conf_del(), conf_run(), config_handler(), config_ldap(), config_module(), config_pgsql(), config_text_file_load(), connection_made(), console_read(), controlplayback_exec(), create_addr(), create_dirpath(), create_followme_number(), create_vmaccount(), crypto_load(), custom_prepare(), dahdi_answer(), dahdi_bridge(), dahdi_call(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_disable_ec(), dahdi_enable_ec(), dahdi_fixup(), dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_link(), dahdi_new(), dahdi_read(), dahdi_request(), dahdi_restart(), dahdi_sendtext(), dahdi_setoption(), dahdi_train_ec(), dahdi_translate(), dahdi_unlink(), dahdi_write(), decode_frame(), del_exec(), deltree_exec(), destroy_bridge(), destroy_conference_bridge(), destroy_pgsql(), destroy_table_cache(), determine_firstline_parts(), devstate_event(), dial_exec_full(), dialog_needdestroy(), dialog_unlink_all(), disa_exec(), do_cdr(), do_directory(), do_magic_pickup(), do_monitor(), do_proxy_auth(), do_register(), do_register_expire(), do_say(), do_setnat(), do_state_change(), do_waiting(), dump_agents(), dundi_answer_entity(), dundi_answer_query(), dundi_decrypt(), dundi_encrypt(), dundi_lookup_internal(), dundi_lookup_thread(), dundi_precache_internal(), dundi_precache_thread(), dundi_prop_precache(), dundi_query_thread(), eivr_comm(), encrypt_frame(), expire_register(), external_rtp_create(), feature_interpret(), festival_exec(), filter(), find_account(), find_best_technology(), find_call(), find_call_cb(), find_conf(), find_conf_realtime(), find_peer(), find_queue_by_name_rt(), find_subchannel_and_lock(), find_table(), find_table_cb(), find_tpeer(), find_user(), findmeexec(), func_inheritance_write(), function_db_delete(), function_db_read(), g726_open(), generator_force(), generic_http_callback(), get_also_info(), get_destination(), get_input(), get_lock(), get_member_status(), get_refer_info(), get_sip_pvt_byid_locked(), getproviderstate(), gosub_exec(), gtalk_alloc(), gtalk_answer(), gtalk_hangup_farend(), gtalk_parser(), gtalk_rtp_read(), gtalk_update_stun(), handle_command_response(), handle_devstate_change(), handle_frame(), handle_getoption(), handle_gosub(), handle_incoming(), handle_input(), handle_invite_replaces(), handle_jack_audio(), handle_offhook_message(), handle_onhook_message(), handle_output(), handle_request(), handle_request_bye(), handle_request_cancel(), handle_request_do(), handle_request_info(), handle_request_invite(), handle_request_notify(), handle_request_refer(), handle_request_register(), handle_request_subscribe(), handle_response(), handle_response_invite(), handle_response_notify(), handle_response_refer(), handle_response_register(), handle_response_subscribe(), handle_soft_key_event_message(), handle_statechange(), handle_stimulus_message(), handle_streamfile(), handle_tcptls_connection(), handle_transfer_button(), handle_uri(), HandleCallOutgoing(), hangup_cause2sip(), hangup_connection(), http_post_callback(), iax2_answer(), iax2_call(), iax2_destroy(), iax2_devicestate(), iax2_do_register(), iax2_hangup(), iax2_indicate(), iax2_provision(), iax2_start_transfer(), iax2_transfer(), iax2_trunk_queue(), iax2_write(), iax_provision_version(), ices_exec(), icesencode(), iconv_read(), init_jack_data(), initialize_initreq(), invent_message(), io_grow(), is_our_turn(), isAnsweringMachine(), jb_put(), jingle_alloc(), jingle_answer(), jingle_hangup_farend(), jingle_is_answered(), jingle_parser(), jingle_rtp_read(), join_conference_bridge(), join_queue(), launch_netscript(), ldap_loadentry(), ldap_reconnect(), leave_queue(), leave_voicemail(), load_config(), load_module(), local_attended_transfer(), local_bridgedchannel(), local_devicestate(), local_hangup(), local_write(), log_events(), log_jitterstats(), log_match_char_tree(), login_exec(), lua_find_extension(), make_email_file(), make_trunk(), manage_parkinglot(), manager_show_dialplan_helper(), measurenoise(), meetme_cmd(), meetme_show_cmd(), message_template_build(), message_template_parse_filebody(), metermaidstate(), mgcp_answer(), mgcp_hangup(), mgcp_rtp_read(), mgcp_ss(), mgcpsock_read(), minivm_accmess_exec(), minivm_delete_exec(), minivm_greet_exec(), misdn_hangup(), misdn_write(), mkif(), moh_class_destructor(), moh_scan_files(), monmp3thread(), mp3_exec(), multiplexed_add_or_remove(), multiplexed_bridge_create(), multiplexed_bridge_destroy(), multiplexed_bridge_join(), multiplexed_bridge_leave(), multiplexed_bridge_suspend(), multiplexed_bridge_unsuspend(), multiplexed_thread_function(), my_dahdi_write(), nbs_call(), nbs_hangup(), nbs_xread(), NBScat_exec(), network_thread(), new_find_extension(), notify_metermaids(), notify_new_message(), obproxy_get(), odbc_load_module(), odbc_release_obj2(), odbc_txn_free(), ogg_vorbis_open(), oh323_answer(), oh323_call(), oh323_destroy(), oh323_destroy_alias(), oh323_destroy_peer(), oh323_destroy_user(), oh323_hangup(), oh323_indicate(), oh323_request(), oh323_rtp_read(), originate_exec(), osp_auth(), osp_check_destination(), osp_create_provider(), osp_create_transaction(), osp_finish(), osp_get_provider(), osp_load(), osp_lookup(), osp_next(), osp_validate_token(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), parse_config(), parse_minse(), parse_moved_contact(), parse_naptr(), parse_request(), parse_session_expires(), parse_sip_options(), parse_uri(), pbx_builtin_gotoif(), pbx_builtin_gotoiftime(), pbx_extension_helper(), pbx_substitute_variables_helper_full(), peer_set_srcaddr(), peercnt_add(), peercnt_modify(), peercnt_remove(), pgsql_log(), pgsql_reconnect(), phase_e_handler(), phone_answer(), phone_call(), phone_check_exception(), phone_digit_end(), phone_exception(), phone_hangup(), phone_indicate(), phoneprov_callback(), pickup_do(), pl_odtworz_plik(), play_message_callerid(), play_message_duration(), play_record_review(), play_sound_file(), pop_exec(), post_raw(), precache_transactions(), printdigest(), proc_session_timer(), process_ast_dsp(), process_cisco_dtmf(), process_clearcache(), process_collection(), process_message(), process_message_callback(), process_request(), process_rfc2833(), process_rfc3389(), process_sdp(), process_sdp_a_audio(), process_sdp_a_image(), process_sdp_o(), progress(), queue_exec(), queue_set_param(), queue_voice_frame(), quit_handler(), radius_log(), raw_hangup(), read_pipe(), readexten_exec(), realtime_destroy_handler(), realtime_handler(), realtime_ldap_base_ap(), realtime_ldap_entry_to_var(), realtime_ldap_result_to_vars(), realtime_multi_handler(), realtime_multi_pgsql(), realtime_peer(), realtime_pgsql(), realtime_store_handler(), realtime_update2_handler(), realtime_update_handler(), realtimefield_read(), rebuild_matrix(), receive_ademco_contact_id(), receive_dtmf_digits(), record_exec(), reg_source_db(), regex(), register_request(), registry_addref(), registry_unref(), release_transaction(), reload_agents(), reload_config(), reload_followme(), reload_queue_members(), remote_hold(), reqprep(), require_pgsql(), restart_session_timer(), restore_conference(), retrans_pkt(), ring_entry(), ring_one(), rqm_exec(), rt_extend_conf(), run_agi(), run_externnotify(), run_ras(), save_conference(), save_to_folder(), sayname(), sched_delay_remove(), schedule_delivery(), search_directory(), select_entry(), semicolon_count_var(), send_digit_to_chan(), send_dtmf(), send_eivr_event(), send_packet(), send_request(), send_trunk(), send_waveform_to_channel(), sendmail(), sendpage(), set_actual_rxgain(), set_actual_txgain(), set_dtmf_payload(), set_format(), set_local_capabilities(), set_member_paused(), set_peer_capabilities(), set_peercnt_limit(), set_peercnt_limit_all_cb(), setup_incoming_call(), setup_inheritable_audiohook(), setup_rtp_connection(), sip_addheader(), sip_alloc(), sip_alreadygone(), sip_answer(), sip_call(), sip_destroy(), sip_destroy_peer(), sip_devicestate(), sip_do_reload(), sip_dump_history(), sip_fixup(), sip_hangup(), sip_new(), sip_park(), sip_park_thread(), sip_prepare_socket(), sip_registry_destroy(), sip_request_call(), sip_rtp_read(), sip_sendhtml(), sip_set_rtp_peer(), sip_set_udptl_peer(), skinny_answer(), skinny_hangup(), skinny_indicate(), skinny_rtp_read(), skinny_session(), skinny_ss(), skinny_transfer(), sla_handle_dial_state_event(), sla_queue_event_conf(), sla_station_exec(), smart_bridge_operation(), smdi_toggle_mwi(), socket_process(), socket_read(), sqlite3_log(), ss_thread(), start_session_timer(), start_stream(), stop_session_timer(), store_next_lin(), store_next_rr(), store_pgsql(), stun_handle_packet(), substituted(), swap_subs(), tds_message_handler(), testclient_exec(), testserver_exec(), timerfd_timer_ack(), timing_read(), tone_detect(), transmit(), transmit_audio(), transmit_invite(), transmit_notify_custom(), transmit_refer(), transmit_register(), transmit_response_with_sdp(), transmit_t38(), transmit_trunk(), try_calling(), try_load_key(), udptl_build_packet(), unalloc_sub(), unistim_fixup(), unistim_hangup(), unistim_rtp_read(), unload_module(), unload_pgsql(), unlock_read(), unwrap_timestamp(), update2_ldap(), update2_pgsql(), update_call_counter(), update_conf(), update_ldap(), update_max_nontrunk(), update_max_trunk(), update_pgsql(), update_qe_rule(), update_realtime_members(), vm_authenticate(), vm_change_password(), vm_delete(), vm_execmain(), vm_newuser(), vm_options(), wait_for_answer(), wait_for_winner(), write_metadata(), WriteMemoryCallback(), and xml_translate().
#define AST_LOG_DEBUG __LOG_DEBUG, _A_
Definition at line 124 of file logger.h.
Referenced by check_password(), and load_config().
#define AST_LOG_DTMF __LOG_DTMF, _A_
Definition at line 190 of file logger.h.
#define AST_LOG_ERROR __LOG_ERROR, _A_
Definition at line 168 of file logger.h.
Referenced by copy_message(), forward_message(), leave_voicemail(), load_config(), open_mailbox(), run_externnotify(), vm_box_exists(), vm_exec(), and vm_execmain().
#define AST_LOG_EVENT __LOG_EVENT, _A_
Definition at line 135 of file logger.h.
#define AST_LOG_NOTICE __LOG_NOTICE, _A_
Definition at line 146 of file logger.h.
Referenced by check_password(), copy_message(), leave_voicemail(), save_to_folder(), substitute_escapes(), vm_newuser(), and vm_options().
#define AST_LOG_WARNING __LOG_WARNING, _A_
Definition at line 157 of file logger.h.
Referenced by adsi_begin(), advanced_options(), apply_option(), base_encode(), check_password(), close_mailbox(), copy(), create_dirpath(), forward_message(), invent_message(), is_valid_dtmf(), leave_voicemail(), load_config(), load_module(), make_email_file(), notify_new_message(), play_message(), play_message_category(), play_message_datetime(), play_record_review(), run_externnotify(), sendmail(), sendpage(), vm_authenticate(), vm_box_exists(), vm_change_password(), vm_exec(), vm_execmain(), and wait_file2().
#define ast_verb (level, ...)
Definition at line 220 of file logger.h.
Referenced by __ast_context_destroy(), __ast_custom_function_register(), __ast_format_register(), __ast_mm_init(), __ast_pbx_run(), __ast_play_and_record(), __ast_register_translator(), __ast_rtp_reload(), __ast_udptl_reload(), __dahdi_exception(), __ssl_setup(), _macro_exec(), _while_exec(), accept_thread(), acf_odbc_read(), action_login(), add_realm_authentication(), adsi_exec(), adsi_prog(), advanced_options(), agent_call(), agent_read(), agent_thread(), alarmreceiver_exec(), alloc_sub(), append_mapping(), ast_add_extension2_lockopt(), ast_agi_register(), ast_agi_unregister(), ast_aji_disconnect(), ast_app_has_voicemail(), ast_app_inboxcount(), ast_app_inboxcount2(), ast_app_messagecount(), ast_bridge_call(), ast_cdr_unregister(), ast_channel_bridge(), ast_channel_register(), ast_channel_unregister(), ast_config_text_file_save(), ast_context_add_include2(), ast_context_add_switch2(), ast_context_find_or_create(), ast_context_remove_extension_callerid2(), ast_context_remove_include2(), ast_context_remove_switch2(), ast_control_streamfile(), ast_custom_function_unregister(), ast_dnsmgr_lookup(), ast_dnsmgr_release(), ast_format_unregister(), ast_get_enum(), ast_get_srv(), ast_image_register(), ast_image_unregister(), ast_jb_destroy(), ast_manager_register_struct(), ast_manager_unregister(), ast_merge_contexts_and_delete(), ast_module_reload(), ast_moh_destroy(), ast_moh_start(), ast_netsock_set_qos(), ast_odbc_find_table(), ast_pbx_outgoing_app(), ast_pbx_outgoing_exten(), ast_pbx_run_app(), ast_record_review(), ast_register_application2(), ast_register_feature(), ast_register_indication_country(), ast_rtp_bridge(), ast_set_indication_country(), ast_speech_register(), ast_speech_unregister(), ast_streamfile(), ast_udptl_read(), ast_udptl_write(), ast_unregister_application(), ast_unregister_translator(), async_wait(), attempt_thread(), attempt_transfer(), background_detect_exec(), begin_dial_channel(), blr_ebl(), blr_txt(), build_channels(), build_conf(), build_device(), build_gateway(), builtin_automixmonitor(), builtin_automonitor(), builtin_blindtransfer(), builtin_disconnect(), cb_extensionstate(), channel_spy(), check_for_conference(), check_send_queue(), cli_console_mute(), close_call(), close_client(), conf_exec(), conf_run(), config_device(), config_line(), config_load(), config_module(), config_odbc_prepare(), config_text_file_load(), console_answer(), console_call(), console_digit_begin(), console_digit_end(), console_hangup(), console_indicate(), console_text(), context_merge(), context_merge_incls_swits_igps_other_registrars(), cpeid_exec(), create_client(), create_jb(), dahdi_bridge(), dahdi_call(), dahdi_dnd(), dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_hangup(), dahdi_read(), dahdi_restart(), dahdiras_exec(), database_increment(), del_exec(), deltree_exec(), dial_exec_full(), dialout(), dnsmgr_refresh(), do_forward(), do_monitor(), do_timelimit(), do_waiting(), execute_cb(), exit_now(), feature_interpret(), feature_request_and_dial(), find_conf_realtime(), find_line_by_name(), find_subchannel_and_lock(), find_subchannel_by_name(), find_table(), findmeexec(), flash_exec(), generic_http_callback(), get_input(), handle_alarm_message(), handle_button_template_req_message(), handle_callforward_button(), handle_capabilities_res_message(), handle_cli_h323_hangup(), handle_command_response(), handle_enbloc_call_message(), handle_exec(), handle_frame(), handle_frame_ownerless(), handle_getoption(), handle_init_event(), handle_keypad_button_message(), handle_message(), handle_offhook_message(), handle_open_receive_channel_ack_message(), handle_register_message(), handle_request(), handle_response(), handle_skinny_reset(), handle_soft_key_event_message(), handle_stimulus_message(), handle_streamfile(), handle_tcptls_connection(), handle_verbose(), HandleCallIncoming(), HandleCallOutgoing(), iax2_ack_registry(), iax2_bridge(), iax2_exec(), iax2_hangup(), iax2_prov_app(), iax_provision_reload(), init_logger(), init_phone_step2(), isAnsweringMachine(), key_dial_page(), launch_script(), leave_voicemail(), listener(), load_config(), load_module(), load_modules(), load_pbx(), log_events(), logger_print_normal(), login_exec(), lua_pbx_exec(), manage_parkinglot(), mgcp_answer(), mgcp_call(), mgcp_hangup(), mgcp_indicate(), mgcp_new(), mgcp_request(), mgcp_ss(), misdn_bridge(), mixmonitor_ds_close_fs(), mixmonitor_thread(), moh_alloc(), moh_files_alloc(), moh_release(), mwi_event_cb(), netconsole(), odbc_load_module(), odbc_log(), oh323_call(), park_call_full(), park_exec_full(), parkandannounce_exec(), parse_config(), parse_register_contact(), ParseBookmark(), parsing(), pbx_builtin_goto(), pbx_builtin_pushvar_helper(), pbx_builtin_setvar_helper(), pbx_builtin_waitexten(), pbx_extension_helper(), pgsql_log(), phone_hangup(), play_message_callerid(), play_record_review(), privacy_exec(), process_ast_dsp(), process_dahdi(), process_request(), purge_sessions(), queue_exec(), rcv_mac_addr(), rcv_resume_connection_with_server(), read_exec(), realtime_exec(), receive_ademco_contact_id(), receive_dtmf_digits(), refresh_all_favorite(), refresh_list(), reg_source_db(), register_group(), register_group_feature(), RegisterExtension(), reload(), reload_config(), reload_firmware(), reload_logger(), ring_entry(), rna(), run_agi(), run_ras(), say_periodic_announcement(), say_position(), send_blink_cursor(), send_client(), send_cursor_pos(), send_cwcidspill(), send_date_time(), send_date_time2(), send_date_time3(), send_end_call(), send_favorite(), send_led_update(), send_no_ring(), send_ping(), send_raw_client(), send_retransmit(), send_ring(), send_select_output(), send_start_timer(), send_stop_timer(), send_text(), send_text_status(), send_texttitle(), send_tone(), send_tone_burst(), SendDialTone(), Sendicon(), session_do(), set_config(), setformat(), setup_dahdi(), setup_incoming_call(), setup_privacy_args(), skinny_answer(), skinny_call(), skinny_extensionstate_cb(), skinny_get_rtp_peer(), skinny_hangup(), skinny_hold(), skinny_indicate(), skinny_new(), skinny_register(), skinny_reload(), skinny_request(), skinny_session(), skinny_set_rtp_peer(), skinny_ss(), skinny_unhold(), smdi_load(), sms_debug(), sms_exec(), sms_handleincoming_proto2(), sms_process(), socket_process(), ss_thread(), ssl_read(), ssl_write(), start_network_thread(), start_resource(), start_rtp(), store_config(), swap_subs(), timeout_write(), TransferCallStep1(), transmit_callinfo(), transmit_connect_with_sdp(), transmit_connection_del(), transmit_connection_del_w_params(), transmit_displaymessage(), transmit_displaynotify(), transmit_displaypromptstatus(), transmit_modify_request(), transmit_notify_request(), transmit_notify_request_with_callerid(), transmit_response(), transmit_ringer_mode(), try_load_key(), unistim_answer(), unistim_call(), unistim_do_senddigit(), unistim_get_rtp_peer(), unistim_hangup(), unistim_indicate(), unistim_new(), unistim_reload(), unistim_request(), unistim_senddigit_end(), unistim_sendtext(), unistim_set_rtp_peer(), unistim_ss(), unistimsock_read(), unload_module(), UnregisterExtension(), update_registry(), vm_authenticate(), vm_execmain(), wait_for_answer(), wait_for_winner(), waitfor_exec(), waitforring_exec(), and write_metadata().
#define ast_verbose (...) __ast_verbose(__FILE__, __LINE__, __PRETTY_FUNCTION__, __VA_ARGS__)
Definition at line 79 of file logger.h.
Referenced by __agent_start_monitoring(), __ast_bridge_technology_register(), __ast_str_helper(), __sip_destroy(), add_codec_to_sdp(), add_noncodec_to_sdp(), add_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), aji_handle_presence(), aji_handle_subscribe(), aji_log_hook(), aji_test(), alsa_answer(), alsa_call(), alsa_digit(), alsa_hangup(), alsa_indicate(), alsa_text(), ast_agi_send(), ast_bridge_technology_unregister(), ast_frame_dump(), ast_module_reload(), ast_readconfig(), ast_remotecontrol(), ast_rtcp_read(), ast_rtcp_write_rr(), ast_rtcp_write_sr(), ast_rtp_destroy(), ast_rtp_raw_write(), ast_rtp_read(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_continuation(), ast_rtp_senddigit_end(), ast_say_enumeration_full_he(), ast_say_number_full_he(), ast_set_priority(), astman_append(), attempt_reconnect(), auth_headers(), bridge_p2p_rtp_write(), check_peer_ok(), check_via(), conf_run(), dahdi_request(), dahdi_softhangup_all(), destroy_all_channels(), dialout(), do_register_auth(), dumpchan_exec(), dundi_debug_output(), find_command(), find_gtalk(), find_transcoders(), get_also_info(), get_destination(), get_rdnis(), get_refer_info(), gtalk_do_reload(), gtalk_handle_dtmf(), h323_reload(), handle_cli_misdn_send_facility(), handle_frame(), handle_incoming(), handle_offhook_message(), handle_request(), handle_request_do(), handle_request_info(), handle_request_invite(), handle_request_message(), handle_request_refer(), handle_request_subscribe(), handle_response(), handle_transfer_button(), iax_debug_output(), init_files_class(), initialize_initreq(), ivr_demo_func(), jb_debug_output(), jingle_handle_dtmf(), leave_voicemail(), list_route(), load_config(), load_module(), load_rpt_vars(), main(), mdc1200_notify(), mgcp_reload(), mgcpsock_read(), moh_files_release(), oss_answer(), oss_call(), oss_digit_end(), oss_hangup(), oss_indicate(), oss_text(), parse(), parse_register_contact(), phone_check_exception(), phone_exception(), play_record_review(), process_sdp(), process_sdp_a_audio(), process_sdp_a_text(), process_sdp_a_video(), quit_handler(), receive_message(), resend_response(), retrans_pkt(), rpt(), rpt_exec(), run_agi(), send_request(), send_response(), set_destination(), setformat(), sip_read(), sip_reload(), sip_rtp_read(), sip_scheddestroy(), sip_sendtext(), start_resource(), stun_handle_packet(), stun_process_attr(), timeout_write(), timing_read(), transmit_register(), usbradio_digit_end(), usbradio_indicate(), usbradio_text(), and verbose_exec().
#define ast_verbose_ap (fmt, ap) __ast_verbose_ap(__FILE__, __LINE__, __PRETTY_FUNCTION__, fmt, ap)
Definition at line 83 of file logger.h.
#define DEBUG_M (a)
Value:
{ \
   a; \
}
Definition at line 37 of file logger.h.
#define EVENTLOG "event_log"
Definition at line 34 of file logger.h.
Referenced by init_logger(), and reload_logger().
#define LOG_DEBUG __LOG_DEBUG, _A_
Definition at line 119 of file logger.h.
Referenced by __sip_destroy(), _get_mohbyname(), add_exten_to_pattern_tree(), add_publish_event(), announce_thread(), ast_audiohook_write_frame(), ast_backtrace(), ast_channel_audiohook_count_by_source(), ast_channel_audiohook_count_by_source_running(), ast_event_cb(), ast_rtcp_read(), ast_rtp_codec_setpref(), ast_rtp_get_qosvalue(), ast_say_date_with_format_th(), ast_say_enumeration_full_he(), ast_say_number_full_zh(), ast_unlock_path_flock(), audiohook_read_frame_both(), build_parkinglot(), builtin_blindtransfer(), create_match_char_tree(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_read(), dahdi_request(), do_dtmf_local(), do_monitor(), find_parkinglot(), gtalk_is_accepted(), gtalk_is_answered(), handle_cli_agi_add_cmd(), handle_incoming(), http_post_callback(), ilbctolin_framein(), launch_asyncagi(), load_config(), load_module(), manager_modulecheck(), mgcp_senddigit_begin(), mgcp_senddigit_end(), moh_class_destructor(), odbc_obj_disconnect(), park_space_reserve(), parkinglot_addref(), parkinglot_unref(), parse_cookies(), pbx_find_extension(), prep_email_sub_vars(), process_dahdi(), process_request_queue(), process_rfc2833(), process_sdp(), process_sdp_a_audio(), realtime_ldap_base_ap(), rpt(), scan_service(), scheduled_destroy(), sip_removeheader(), sip_rtp_read(), skinny_transfer(), smdi_read(), span_message(), ss_thread(), tps_taskprocessor_destroy(), and xmldoc_build_field().
#define LOG_DTMF __LOG_DTMF, _A_
Definition at line 185 of file logger.h.
Referenced by __ast_read(), __oh323_update_info(), oh323_digit_begin(), oh323_digit_end(), oh323_rtp_read(), and receive_digit().
#define LOG_ERROR __LOG_ERROR, _A_
Definition at line 163 of file logger.h.
Referenced by __agent_start_monitoring(), __ao2_ref(), __ast_custom_function_register(), __ast_mm_init(), __ast_read(), __oh323_rtp_create(), __sip_reliable_xmit(), _macro_exec(), _sip_tcp_helper_thread(), access_counter_file(), acf_channel_read(), acf_curl_exec(), acf_curlopt_read(), acf_curlopt_write(), acf_cut_exec(), acf_iaxvar_write(), acf_jabberstatus_read(), acf_mailbox_exists(), acf_meetme_info(), acf_odbc_read(), acf_odbc_write(), acf_sort_exec(), acf_sprintf(), acf_strptime(), acf_transaction_write(), action_getvar(), add_exten_to_pattern_tree(), add_pri_lockopt(), add_rt_multi_cfg_entry(), add_subscribe_event(), add_to_agi(), ael2_print(), agent_get_base_channel(), agent_set_base_channel(), aji_act_hook(), aji_client_connect(), aji_client_info_handler(), aji_create_client(), aji_dinfo_handler(), aji_ditems_handler(), aji_find_version(), aji_handle_presence(), aji_handle_subscribe(), aji_initialize(), aji_pruneregister(), aji_recv_loop(), aji_register_approve_handler(), aji_register_query_handler(), aji_reload(), aji_send_exec(), aji_set_presence(), aji_start_sasl(), aji_status_exec(), alloc_expr_node(), alloc_resampler(), alsa_card_init(), alsa_read(), alsa_write(), answer_call(), anti_injection(), app_exec(), aqm_exec(), ast_add_extension2_lockopt(), ast_agi_send(), ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_ais_evt_load_module(), ast_ais_evt_unload_module(), ast_aji_create_chat(), ast_aji_invite_chat(), ast_aji_join_chat(), ast_aji_send_chat(), ast_careful_fwrite(), ast_carefulwrite(), ast_cdr_alloc(), ast_cdr_engine_init(), ast_cdr_serialize_variables(), ast_cdr_setvar(), ast_channel_queryoption(), ast_channel_setoption(), ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), ast_context_find_or_create(), ast_context_remove_extension_callerid2(), ast_device_state_engine_init(), ast_el_read_char(), ast_enable_distributed_devstate(), ast_event_cb(), ast_event_check_subscriber(), ast_event_get_cached(), ast_event_get_ie_pltype(), ast_event_get_ie_type_name(), ast_event_get_type_name(), ast_event_subscribe_new(), ast_func_read(), ast_func_write(), ast_get_encoded_char(), ast_get_group(), ast_hangup(), ast_heap_create(), ast_iax2_new(), ast_jb_put(), ast_lock_path_lockfile(), ast_manager_register_struct(), ast_manager_unregister(), ast_monitor_change_fname(), ast_netsock_bindaddr(), ast_odbc_find_table(), ast_ouraddrfor(), ast_pbx_outgoing_exten(), ast_playtones_start(), ast_readconfig(), ast_remotecontrol(), ast_rtcp_write_rr(), ast_rtcp_write_sr(), ast_rtp_new_with_bindaddr(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_continuation(), ast_rtp_senddigit_end(), ast_sched_runq(), ast_sched_thread_create(), ast_taskprocessor_get(), ast_taskprocessor_name(), ast_taskprocessor_push(), ast_tcptls_client_create(), ast_tcptls_client_start(), ast_tcptls_server_read(), ast_tcptls_server_start(), ast_tcptls_server_write(), ast_tps_init(), ast_unlock_path_lockfile(), ast_wait_for_output(), ast_xmldoc_load_documentation(), async_wait(), authenticate_reply(), bridge_array_add(), build_callno_limits(), build_channels(), build_device(), build_event_channel(), build_parkinglot(), build_peer(), build_route(), build_user(), builtin_automixmonitor(), builtin_automonitor(), callerid_feed(), callerid_feed_jp(), callerid_read(), callerid_write(), canmatch(), cb_events(), cdr_handler(), chan_ringing(), chanspy_exec(), check_break(), check_continue(), check_goto(), check_label(), check_pval_item(), check_srcaddr(), check_vars(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_include(), conf_exec(), config_curl(), config_device(), config_function_read(), config_handler(), config_ldap(), config_load(), config_module(), config_text_file_load(), connection_made(), console_request(), context_merge(), copy_rules(), create_jb(), create_match_char_tree(), create_vmaccount(), csv_log(), csv_quote(), custom_log(), dahdi_call(), dahdi_decoder_framein(), dahdi_decoder_frameout(), dahdi_encoder_framein(), dahdi_encoder_frameout(), dahdi_sendtext(), dahdi_test_timer(), dahdi_timer_set_rate(), dahdi_translate(), dahdi_write_frame(), destroy_curl(), device_state_cb(), devstate_cache_cb(), devstate_change_collector_cb(), devstate_write(), dial_exec_full(), dialgroup_write(), dialog_ref(), directory_exec(), dispatch_thread_handler(), dnsmgr_init(), do_magic_pickup(), do_monitor(), do_reload(), donodelog(), dundi_query_read(), dundi_result_read(), duplicate_pseudo(), eagi_exec(), enable_jack_hook(), encode_open_type(), enum_query_read(), enum_result_read(), event_channel_destroy(), evt_event_deliver_cb(), exec(), execif_exec(), exists(), extension_matches(), extenspy_exec(), external_rtp_create(), festival_exec(), filter(), find_conf(), find_matching_endwhile(), find_pval_goto_item(), find_table(), find_transaction(), find_transcoders(), findmeexec(), func_channel_write(), function_autopatchup(), get_agi_cmd(), get_lock(), get_member_penalty(), gosub_exec(), gtalk_alloc(), gtalk_create_candidates(), gtalk_create_member(), gtalk_digit(), gtalk_invite(), gtalk_invite_response(), gtalk_load_config(), gtalk_newcall(), gtalk_request(), handle_call_token(), handle_cli_h323_cycle_gk(), handle_devstate_change(), handle_gosub(), handle_incoming(), handle_input(), handle_invite_replaces(), handle_jack_audio(), handle_open_receive_channel_ack_message(), handle_options(), handle_register_message(), handle_request_do(), handle_request_invite(), handle_tcptls_connection(), hidthread(), http_post_callback(), iax2_dup_variable_datastore(), iax2_hangup(), iax_frame_wrap(), iconv_read(), init_acf_query(), init_jack_data(), init_logger(), init_timing_thread(), INTERNAL_OBJ(), isexten_function_read(), jack_hook_callback(), jack_hook_write(), jb_error_output(), jb_get_and_deliver(), jingle_alloc(), jingle_create_candidates(), jingle_create_member(), jingle_digit(), jingle_newcall(), jingle_request(), join_conference_bridge(), kickptt(), launch_asyncagi(), ldap_loadentry(), ldap_reconnect(), leave_voicemail(), lintoulaw(), listener(), listfilter(), load_column_config(), load_config(), load_config_meetme(), load_indications(), load_module(), load_odbc_config(), load_or_reload_lua_stuff(), load_pbx(), load_realtime_queue(), load_values_config(), local_alloc(), local_write(), log_exec(), lookup_iface(), lua_find_extension(), lua_get_state(), main(), manage_parkinglot(), matchmore(), message_template_build(), message_template_parse_filebody(), mgcp_senddigit_begin(), mgcp_senddigit_end(), minivm_accmess_exec(), minivm_account_func_read(), minivm_counter_func_read(), minivm_counter_func_write(), minivm_delete_exec(), minivm_greet_exec(), minivm_mwi_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_new(), misdn_request(), mixmonitor_thread(), mkintf(), mssql_connect(), multiplexed_nudge(), mute_fragment(), mwi_sub_event_cb(), netconsole(), odbc_load_module(), odbc_log(), ogg_vorbis_open(), ogg_vorbis_rewrite(), ogg_vorbis_write(), oh323_alloc(), oh323_digit_begin(), oh323_digit_end(), oh323_read(), oh323_set_rtp_peer(), op_func(), open_stream(), originate_exec(), osp_create_provider(), osp_load(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), page_exec(), park_call_full(), parse_config(), parse_gain_value(), pbx_builtin_serialize_variables(), pbx_load_config(), pbx_load_module(), pbx_load_users(), pbx_substitute_variables_helper_full(), peek_read(), peercnt_add(), pgsql_log(), pgsql_reconnect(), phone_request(), prep_email_sub_vars(), proc_session_timer(), process_dahdi(), process_message_callback(), process_sdp(), process_text_line(), progress(), pthread_timer_set_rate(), pvalCheckType(), pvalGlobalsAddStatement(), pvalTopLevAddObject(), queue_function_memberpenalty_read(), queue_function_memberpenalty_write(), queue_function_qac(), queue_function_qac_dep(), queue_function_queuememberlist(), queue_function_queuewaitingcount(), queue_function_var(), queue_reload_request(), queue_voice_frame(), quote(), radio_tune(), radius_log(), rcvfax_exec(), read_agent_config(), read_pipe(), readfile_exec(), realtime_curl(), realtime_directory(), realtime_multi_curl(), realtime_multi_ldap(), realtime_multi_pgsql(), realtime_odbc(), realtime_pgsql(), realtime_update2_handler(), receive_digit(), regex(), register_verify(), reload(), reload_config(), reload_followme(), reload_logger(), reload_queue_members(), reload_queue_rules(), reload_queues(), remove_by_peercallno(), remove_by_transfercallno(), replace_callno(), require_curl(), require_pgsql(), resample_frame(), restart_monitor(), retrydial_exec(), return_exec(), rpt(), rpt_do_lstats(), rpt_exec(), rpt_master(), rpt_tele_thread(), say_init_mode(), set_active(), set_config(), set_member_penalty(), setrem(), setup_dahdi(), setup_incoming_call(), setup_rtp_connection(), sha1(), shared_read(), shared_write(), sip_indicate(), sip_park_thread(), sip_queryoption(), sip_register(), sip_request_call(), sip_sipredirect(), sip_st_alloc(), sip_tcptls_write(), sip_threadinfo_create(), skinny_call(), skinny_req_parse(), sla_add_trunk_to_station(), sla_build_station(), sla_build_trunk(), sla_load_config(), sla_queue_event_conf(), sla_state(), sla_trunk_exec(), smdi_load(), smdi_msg_read(), smdi_msg_retrieve_read(), smdi_read(), smdi_toggle_mwi(), sms_exec(), sndfax_exec(), socket_process(), soundcard_init(), span_message(), speex_read(), speex_write(), sqlite3_log(), sqlite_log(), ssl_lock(), start_monitor_exec(), start_session_timer(), start_stream(), statpost(), store_by_peercallno(), store_by_transfercallno(), store_config(), store_curl(), subscribe_event_destroy(), sysinfo_helper(), tdd_feed(), tds_error_handler(), tds_load_module(), tds_log(), timeout_read(), timeout_write(), timerfd_timer_ack(), timerfd_timer_close(), timerfd_timer_disable_continuous(), timerfd_timer_enable_continuous(), timerfd_timer_get_event(), timerfd_timer_open(), timerfd_timer_set_rate(), tps_processing_function(), tps_taskprocessor_destroy(), tps_taskprocessor_pop(), transmit(), transmit_audio(), transmit_response_using_temp(), transmit_response_with_sdp(), transmit_response_with_t38_sdp(), transmit_t38(), try_calling(), unistim_call(), unload_module(), update2_curl(), update2_ldap(), update2_pgsql(), update2_prepare(), update_call_counter(), update_curl(), update_ldap(), update_pgsql(), usbradio_read(), usbradio_text(), usbradio_write(), write_byte(), writefile(), xmldoc_build_field(), xmldoc_string_cleanup(), xpmr_config(), and yyerror().
#define LOG_EVENT __LOG_EVENT, _A_
Definition at line 130 of file logger.h.
Referenced by action_login(), attempt_thread(), generic_http_callback(), init_logger(), logger_print_normal(), reload_logger(), scan_service(), session_do(), sms_readfile(), and sms_writefile().
#define LOG_NOTICE __LOG_NOTICE, _A_
Definition at line 141 of file logger.h.
Referenced by __ast_decrypt_bin(), __ast_encrypt_bin(), __ast_read(), __ast_request_and_dial(), __ast_udptl_reload(), __auto_congest(), __iax2_poke_noanswer(), __init_manager(), _extension_match_core(), accept_thread(), acf_jabberstatus_read(), acf_meetme_info(), add_in_calls(), add_out_calls(), admin_exec(), adsi_prog(), agent_call(), agent_hangup(), agent_read(), agent_request(), aji_client_info_handler(), aji_dinfo_handler(), aji_handle_presence(), aji_status_exec(), alsa_request(), alsa_write(), answer_call(), app_exec(), apply_outgoing(), aqm_exec(), ast_alaw_init(), ast_app_dtget(), ast_call_forward(), ast_cli_perms_init(), ast_config_engine_register(), ast_context_remove_extension_callerid2(), ast_db_get(), ast_io_remove(), ast_module_reload(), ast_process_pending_reloads(), ast_register_feature(), ast_rtp_read(), ast_sip_ouraddrfor(), ast_udptl_write(), ast_ulaw_init(), attempt_thread(), attempt_transfer(), authenticate(), authenticate_reply(), authenticate_verify(), birdbath(), bridge_p2p_loop(), build_peer(), builtin_atxfer(), builtin_automixmonitor(), builtin_automonitor(), callerid_feed(), callerid_feed_jp(), cb_events(), cdr_merge_vars(), channel_admin_exec(), channel_revert(), channel_steer(), chanspy_exec(), check_auth(), check_freq_ic706(), check_key(), check_post(), check_rtp_timeout(), check_tx_freq(), check_user_full(), cleanup_connection(), collect_function_digits(), compose_func_args(), config_device(), config_line(), config_load(), config_odbc(), connect_link(), console_request(), console_video_start(), convertcap(), copy_header(), copy_via_headers(), crypto_load(), dahdi_bridge(), dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_request(), dahdi_setoption(), destroy_trans(), dial_exec_full(), dnsmgr_refresh(), do_autokill(), do_dtmf_local(), do_forward(), do_register(), do_reload(), do_scheduler(), dump_queue(), dundi_encrypt(), dundi_exec(), dundi_helper(), dundi_precache_full(), dundi_precache_internal(), dundi_prop_precache(), dundi_rexmit(), dundi_send(), eivr_comm(), extenspy_exec(), feature_exec_app(), feature_request_and_dial(), ffmpeg_decode(), find_account(), find_subchannel_and_lock(), find_subchannel_by_name(), finish_bookmark(), flush_telem(), forward_message(), function_cop(), function_ilink(), function_remote(), get_canmatch_exten(), get_mem_set(), group_count_function_read(), gtalk_create_candidates(), gtalk_handle_dtmf(), gtalk_hangup_farend(), gtalk_indicate(), gtalk_is_accepted(), gtalk_is_answered(), gtalk_newcall(), gtalk_parser(), gtalk_sendhtml(), handle_cli_indication_add(), handle_command_response(), handle_incoming(), handle_init_event(), handle_invite_replaces(), handle_link_data(), handle_playtones(), handle_remote_dtmf_digit(), handle_request(), handle_request_bye(), handle_request_invite(), handle_request_notify(), handle_request_register(), handle_request_subscribe(), handle_response(), handle_response_invite(), handle_response_notify(), handle_response_peerpoke(), handle_response_refer(), handle_response_register(), handle_response_subscribe(), HandleCallIncoming(), HandleCallOutgoing(), hidthread(), iax2_canmatch(), iax2_exec(), iax2_exists(), iax2_matchmore(), iax2_poke_peer(), iax2_prov_app(), iax2_read(), iax2_send(), iax_park_thread(), iax_provision_reload(), ic706_pltocode(), import_ch(), ivr_dispatch(), jingle_create_candidates(), jingle_handle_dtmf(), jingle_hangup_farend(), jingle_indicate(), jingle_is_answered(), jingle_newcall(), jingle_parser(), jingle_sendhtml(), ldap_loadentry(), linkcount(), load_config(), load_config_meetme(), load_module(), load_modules(), load_odbc_config(), load_rpt_vars(), local_alloc(), local_ast_moh_start(), local_call(), log_jack_status(), login_exec(), manager_isdn_handler(), measurenoise(), meetmemute(), message_template_parse_emailbody(), mgcp_call(), mgcp_fixup(), mgcp_request(), mgcp_rtp_read(), mgcpsock_read(), misdn_bridge(), misdn_hangup(), mixmonitor_exec(), mkintf(), monmp3thread(), mpeg4_decode(), mssql_connect(), mwi_thread(), nbs_request(), new_find_extension(), odbc_obj_connect(), oh323_call(), oh323_request(), oh323_rtp_read(), openserial(), oss_request(), parse_config(), parse_register_contact(), ParseBookmark(), parsing(), pbx_extension_helper(), pbx_find_extension(), pbx_load_module(), phone_request(), pickup_exec(), pickupchan_exec(), process_ast_dsp(), process_dahdi(), process_rfc3389(), process_sdp(), purge_old_messages(), queue_function_qac_dep(), read_agent_config(), realtime_exec(), register_group(), register_group_feature(), register_verify(), registry_rerequest(), reload(), reload_agents(), reload_config(), reload_queue_members(), reload_queue_rules(), reload_queues(), retreive_memory(), rpt(), rpt_call(), rpt_do_stats(), rpt_exec(), rpt_manager_do_stats(), rpt_master(), rpt_push_alt_macro(), rpt_tele_thread(), rpt_telemetry(), rqm_exec(), send_usb_txt(), sendkenwood(), serial_remote_io(), set_config(), set_ctcss_mode_ic706(), set_freq_ic706(), set_ic706(), set_mode_ic706(), set_offset_ic706(), set_ulimit(), setup_dahdi(), setup_incoming_call(), setup_privacy_args(), setup_rtp_connection(), sip_dump_history(), sip_parse_host(), sip_poke_noanswer(), sip_poke_peer(), sip_read(), sip_reg_timeout(), sip_register(), sip_request_call(), sip_reregister(), sipsock_read(), skinny_fixup(), skinny_indicate(), skinny_request(), sla_station_exec(), smdi_load(), smoother_frame_feed(), sms_messagerx2(), sms_process(), socket_process(), ss_thread(), start_spying(), store_config(), stub_ast_key_get(), tdd_feed(), tds_load_module(), tds_log(), tds_message_handler(), testclient_exec(), testserver_exec(), timed_read(), transmit_refer(), transmit_register(), try_calling(), try_load_key(), try_suggested_sip_codec(), unistim_request(), unistimsock_read(), update2_pgsql(), update2_prepare(), update_call_counter(), update_common_options(), update_key(), update_registry(), update_scoreboard(), usbradio_read(), usbradio_request(), usbradio_text(), wait_for_answer(), wait_for_winner(), wait_interval(), and waituntil_exec().
#define LOG_VERBOSE __LOG_VERBOSE, _A_
Definition at line 179 of file logger.h.
#define LOG_VERBOSE __LOG_VERBOSE, _A_
Definition at line 179 of file logger.h.
Referenced by bridge_call_thread(), and unload_module().
#define LOG_WARNING __LOG_WARNING, _A_
Definition at line 152 of file logger.h.
Referenced by __adsi_transmit_messages(), __ao2_callback(), __ast_answer(), __ast_bridge_technology_register(), __ast_channel_alloc_ap(), __ast_check_signature(), __ast_check_signature_bin(), __ast_cli_register(), __ast_cli_unregister(), __ast_decrypt_bin(), __ast_dsp_call_progress(), __ast_encrypt_bin(), __ast_format_register(), __ast_http_load(), __ast_pbx_run(), __ast_play_and_record(), __ast_queue_frame(), __ast_read(), __ast_register_translator(), __ast_rtp_reload(), __ast_sign_bin(), __ast_smoother_feed(), __ast_string_field_init(), __ast_udptl_reload(), __attempt_transmit(), __dahdi_exception(), __find_callno(), __init_manager(), __mgcp_xmit(), __oh323_destroy(), __oh323_new(), __oh323_rtp_create(), __set_address_from_contact(), __sip_autodestruct(), __sip_pretend_ack(), __sip_xmit(), __transmit_response(), __unload_module(), _ast_adsi_get_cpeid(), _ast_adsi_get_cpeinfo(), _ast_adsi_load_session(), _ast_adsi_transmit_message_full(), _dsp_init(), _enum_array_map(), _extension_match_core(), _macro_exec(), _moh_register(), _sip_tcp_helper_thread(), _while_exec(), accept_thread(), acf_channel_read(), acf_curl_exec(), acf_if(), acf_isexten_exec(), acf_jabberstatus_read(), acf_odbc_read(), acf_odbc_write(), acf_strftime(), acf_strptime(), acf_transaction_write(), ack_trans(), action_bridge(), action_command(), add_agent(), add_agi_cmd(), add_calltoken_ignore(), add_cfg_entry(), add_codec_to_answer(), add_email_attachment(), add_exten_to_pattern_tree(), add_extensions(), add_features_datastores(), add_header(), add_line(), add_pri_lockopt(), add_publish_event(), add_realm_authentication(), add_redirect(), add_rt_multi_cfg_entry(), add_sdp(), add_sip_domain(), add_subscribe_event(), add_user_extension(), admin_exec(), adsi_careful_send(), adsi_process(), adsi_prog(), aes_helper(), agent_answer(), agent_call(), agent_fixup(), agent_new(), agent_request(), agentmonitoroutgoing_exec(), agi_exec_full(), aji_act_hook(), aji_create_buddy(), aji_create_client(), aji_dinfo_handler(), aji_load_config(), aji_recv(), aji_recv_loop(), aji_send_exec(), aji_status_exec(), alarmreceiver_exec(), alloc_sub(), alsa_card_init(), alsa_indicate(), alsa_new(), alsa_request(), alsa_write(), app_exec(), apply_general_options(), apply_outgoing(), aqm_exec(), ast_agi_register(), ast_agi_unregister(), ast_aji_send_chat(), ast_alaw_init(), ast_app_parse_options(), ast_app_parse_options64(), ast_append_ha(), ast_async_goto(), ast_autoservice_start(), ast_backtrace(), ast_best_codec(), ast_bridge_call(), ast_cdr_end(), ast_cdr_merge(), ast_cdr_noanswer(), ast_cdr_register(), ast_cdr_submit_batch(), ast_channel_bridge(), ast_channel_free(), ast_channel_make_compatible_helper(), ast_channel_masquerade(), ast_channel_register(), ast_check_timing(), ast_cli_perms_init(), ast_codec_get_len(), ast_codec_get_samples(), ast_config_internal_load(), ast_context_remove_extension_callerid2(), ast_context_verify_includes(), ast_db_gettree(), ast_db_put(), ast_do_masquerade(), ast_dsp_call_progress(), ast_dsp_noise(), ast_dsp_process(), ast_dsp_silence(), ast_dtmf_stream(), ast_enable_packet_fragmentation(), ast_event_get_cached(), ast_event_new(), ast_event_queue(), ast_event_queue_and_cache(), ast_extension_close(), ast_filehelper(), ast_find_ourip(), ast_format_str_reduce(), ast_format_unregister(), ast_get_enum(), ast_get_group(), ast_get_ip_or_srv(), ast_hangup(), ast_http_uri_link(), ast_iax2_new(), ast_include_new(), ast_indicate_data(), ast_io_remove(), ast_ivr_menu_run_internal(), ast_jb_put(), ast_linear_stream(), ast_lock_path_flock(), ast_lock_path_lockfile(), ast_makesocket(), ast_manager_register_struct(), ast_merge_contexts_and_delete(), ast_moh_files_next(), ast_monitor_change_fname(), ast_monitor_start(), ast_monitor_stop(), ast_netsock_bindaddr(), ast_netsock_set_qos(), ast_odbc_direct_execute(), ast_odbc_find_table(), ast_odbc_prepare_and_execute(), ast_odbc_request_obj2(), ast_odbc_sanity_check(), ast_odbc_smart_execute(), ast_openstream_full(), ast_openvstream(), ast_ouraddrfor(), ast_parse_allow_disallow(), ast_pbx_outgoing_app(), ast_pbx_outgoing_exten(), ast_pbx_run_app(), ast_pbx_start(), ast_pickup_call(), ast_prod(), ast_pthread_create_detached_stack(), ast_pthread_create_stack(), ast_read_image(), ast_read_textfile(), ast_readaudio_callback(), ast_readconfig(), ast_readfile(), ast_readvideo_callback(), ast_record_review(), ast_register_application2(), ast_register_switch(), ast_remotecontrol(), ast_request(), ast_rtcp_read(), ast_rtp_bridge(), ast_rtp_codec_setpref(), ast_rtp_early_bridge(), ast_rtp_make_compatible(), ast_rtp_proto_register(), ast_rtp_read(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_end(), ast_rtp_write(), ast_safe_fork(), ast_safe_system(), ast_say_date_with_format_da(), ast_say_date_with_format_de(), ast_say_date_with_format_en(), ast_say_date_with_format_es(), ast_say_date_with_format_fr(), ast_say_date_with_format_gr(), ast_say_date_with_format_he(), ast_say_date_with_format_it(), ast_say_date_with_format_nl(), ast_say_date_with_format_pl(), ast_say_date_with_format_pt(), ast_say_date_with_format_th(), ast_say_date_with_format_zh(), ast_say_number_full_pt(), ast_sched_del(), ast_search_dns(), ast_set_priority(), ast_sip_ouraddrfor(), ast_slinfactory_feed(), ast_smoother_read(), ast_speech_register(), ast_stopstream(), ast_streamfile(), ast_stun_request(), ast_taskprocessor_get(), ast_tcptls_client_create(), ast_tcptls_server_root(), ast_translate_path_steps(), ast_translator_build_path(), ast_tryconnect(), ast_udptl_bridge(), ast_udptl_new_with_bindaddr(), ast_udptl_proto_register(), ast_udptl_read(), ast_udptl_write(), ast_ulaw_init(), ast_unload_resource(), ast_waitfor_nandfds(), ast_waitfordigit_full(), ast_write(), ast_writefile(), ast_writestream(), ast_xmldoc_load_documentation(), ast_yyerror(), async_wait(), asyncgoto_exec(), attempt_reconnect(), attempt_transfer(), auth_exec(), authenticate_verify(), autoservice_run(), available(), background_detect_exec(), base64_decode(), base64_encode(), base_encode(), blr_ebl(), blr_txt(), bridge_call_thread(), bridge_exec(), bridge_make_compatible(), bridge_native_loop(), build_alias(), build_channels(), build_conf(), build_device(), build_event_channel(), build_filename(), build_gateway(), build_mapping(), build_parkinglot(), build_peer(), build_rpid(), build_user(), builtin_atxfer(), builtin_automixmonitor(), builtin_blindtransfer(), bump_gains(), cache_get_callno_locked(), calc_cost(), calc_metric(), calculate_far_max_ifp(), calculate_local_max_datagram(), callerid_feed(), callerid_feed_jp(), callerid_get_dtmf(), callerpres_write(), canary_thread(), careful_write(), cb_events(), cb_extensionstate(), cdr_handler(), chan_misdn_log(), chanavail_exec(), channel_admin_exec(), channel_spy(), channel_to_session(), chanspy_exec(), check_abstract_reference(), check_access(), check_app_args(), check_auth(), check_compat(), check_context_names(), check_day(), check_dow(), check_expr2_input(), check_for_conference(), check_goto(), check_header(), check_includes(), check_macro_returns(), check_month(), check_pval_item(), check_switch_expr(), check_timerange(), check_tx_freq(), check_via(), clear_caller(), clearcbone(), cleardisplay(), clearflag(), cleartimer(), close_call(), close_client(), commit_exec(), compile_script(), complete_dialplan_add_extension(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_transfer(), compress_subclass(), conf_add(), conf_del(), conf_exec(), conf_flush(), conf_queue_dtmf(), conf_run(), confbridge_exec(), config_handler(), config_ldap(), config_load(), config_module(), config_odbc(), config_parse_variables(), config_pgsql(), config_text_file_load(), connect_link(), console_autoanswer(), console_cmd(), console_indicate(), console_request(), controlplayback_exec(), copy(), count_exec(), create_addr(), create_dirpath(), create_jb(), create_queue_member(), create_video_frame(), crypto_load(), csv_log(), csv_quote(), custom_prepare(), cut_internal(), dahdi_answer(), dahdi_bridge(), dahdi_call(), dahdi_callwait(), dahdi_confmute(), dahdi_digit_begin(), dahdi_disable_ec(), dahdi_enable_ec(), dahdi_fake_event(), dahdi_get_index(), dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_link(), dahdi_new(), dahdi_open(), dahdi_read(), dahdi_request(), dahdi_restart(), dahdi_ring_phone(), dahdi_sendtext(), dahdi_set_hook(), dahdi_setoption(), dahdi_show_channel(), dahdi_train_ec(), dahdi_translate(), dahdi_write(), dahdiras_exec(), dbinit(), deadagi_exec(), dec_init(), del_exec(), destroy_odbc(), destroy_pgsql(), destroy_pval_item(), destroy_session(), destroy_trans(), devstate_write(), dial_exec_full(), dialgroup_read(), dialgroup_write(), dictate_exec(), digitcollect(), digitdirect(), disa_exec(), disable_jack_hook(), diskavail(), display_last_error(), dns_parse_answer(), do_monitor(), do_reload(), do_say(), do_scheduler(), do_timelimit(), do_waiting(), dump_agents(), dump_queue_members(), dundi_answer_entity(), dundi_answer_query(), dundi_discover(), dundi_error_output(), dundi_exec(), dundi_helper(), dundi_lookup_internal(), dundi_precache_internal(), dundi_prop_precache(), dundi_query(), dundi_query_read(), dundi_result_read(), dundi_xmit(), dundifunc_read(), duplicate_pseudo(), eagi_exec(), ebl_callback(), eivr_comm(), enum_callback(), enum_query_read(), enum_result_read(), exec_exec(), execif_exec(), ext_cmp1(), extension_matches(), extenspy_exec(), extstate_read(), fax_generator_generate(), fbuf_append(), feature_exec_app(), festival_exec(), ffmpeg_encode(), file_read(), filter(), find_cache(), find_call_locked(), find_conf(), find_conf_realtime(), find_desc(), find_desc_usb(), find_engine(), find_line_by_instance(), find_or_create(), find_queue_by_name_rt(), find_sdp(), find_speeddial_by_instance(), find_subchannel_by_instance_reference(), find_subchannel_by_name(), find_subchannel_by_reference(), find_table(), findmeexec(), flash_exec(), fn_wrapper(), forkcdr_exec(), framein(), func_args(), func_channel_read(), func_channel_write(), func_channels_read(), func_check_sipdomain(), func_header_read(), func_inheritance_write(), function_agent(), function_db_delete(), function_db_exists(), function_db_read(), function_db_write(), function_enum(), function_eval(), function_realtime_read(), function_realtime_readdestroy(), function_realtime_store(), function_realtime_write(), function_remote(), function_sipchaninfo_read(), function_sippeer(), function_txtcidname(), g723_len(), g723_read(), g723_write(), g726_read(), g726_write(), g729_read(), g729_write(), gen_generate(), gen_nextfile(), generic_execute(), generic_prepare(), get_alarms(), get_also_info(), get_button_template(), get_destination(), get_in_brackets(), get_input(), get_ip_and_port_from_sdp(), get_params(), get_range(), get_rdnis(), get_refer_info(), get_timerange(), get_to_address(), get_token(), get_unused_callno(), getdisplaybyname(), getflagbyname(), getkeybyname(), getstatebyname(), getsubbyname(), gosub_exec(), gosubif_exec(), goto_exten(), goto_line(), goto_line_rel(), group_function_write(), gsm_read(), gsm_seek(), gsm_write(), gsmtolin_framein(), gtalk_alloc(), gtalk_call(), gtalk_create_candidates(), gtalk_create_member(), gtalk_free_pvt(), gtalk_is_answered(), gtalk_load_config(), gtalk_new(), gtalk_newcall(), gtalk_request(), gtalk_show_channels(), gtalk_write(), h261_decap(), h263_decap(), h263_encap(), h263_open(), h263_read(), h263_write(), h263p_decap(), h263p_encap(), h264_decap(), h264_encap(), h264_open(), h264_read(), h264_write(), handle_alarms(), handle_call_token(), handle_callforward_button(), handle_capabilities_res_message(), handle_cli_agi_add_cmd(), handle_cli_indication_add(), handle_cli_indication_remove(), handle_command_response(), handle_common_options(), handle_enbloc_call_message(), handle_error(), handle_exec(), handle_getoption(), handle_gosub(), handle_hd_hf(), handle_incoming(), handle_init_event(), handle_invite_replaces(), handle_keypad_button_message(), handle_link_data(), handle_message(), handle_offhook_message(), handle_onhook_message(), handle_orig(), handle_recordfile(), handle_register_message(), handle_remote_data(), handle_request(), handle_request_bye(), handle_request_info(), handle_request_invite(), handle_request_notify(), handle_request_subscribe(), handle_response(), handle_response_invite(), handle_response_notify(), handle_response_refer(), handle_response_register(), handle_response_subscribe(), handle_soft_key_event_message(), handle_stimulus_message(), handle_t38_options(), handle_tcptls_connection(), handle_transfer_button(), handle_updates(), HandleCallIncoming(), HandleCallOutgoing(), hidthread(), hint_read(), httpd_helper_thread(), iax2_ack_registry(), iax2_bridge(), iax2_call(), iax2_canmatch(), iax2_devicestate(), iax2_do_register(), iax2_exec(), iax2_exists(), iax2_fixup(), iax2_hangup(), iax2_matchmore(), iax2_poke_peer(), iax2_register(), iax2_request(), iax2_send(), iax2_trunk_queue(), iax_error_output(), iax_park(), iax_process_template(), iax_template_parse(), ices_exec(), icesencode(), iconv_read(), iftime(), ilbc_read(), ilbc_write(), ilbctolin_framein(), in_band_indication(), increase_call_count(), init_acf_query(), init_app_class(), init_req(), init_resp(), insert_penaltychange(), inspect_module(), isAnsweringMachine(), jack_hook_callback(), jb_get_and_deliver(), jb_warning_output(), jingle_alloc(), jingle_call(), jingle_create_candidates(), jingle_create_member(), jingle_free_pvt(), jingle_load_config(), jingle_new(), jingle_newcall(), jingle_request(), jingle_show_channels(), jingle_write(), jpeg_read_image(), jpeg_write_image(), key_call(), Keyfavorite(), launch_asyncagi(), launch_monitor_thread(), launch_netscript(), launch_script(), launch_service(), ldap_loadentry(), ldap_reconnect(), leave_voicemail(), linear_alloc(), linear_generator(), linear_release(), linkcount(), lintogsm_framein(), lintolpc10_framein(), listener(), load_column_config(), load_config(), load_config_meetme(), load_dynamic_module(), load_indications(), load_module(), load_modules(), load_moh_classes(), load_odbc_config(), load_pbx(), load_resource(), load_rpt_vars(), load_values_config(), local_answer(), local_ast_moh_start(), local_devicestate(), local_dtmf_helper(), local_fixup(), local_new(), login_exec(), lookup_iface(), lpc10tolin_framein(), lua_read_extensions_file(), macroif_exec(), main(), make_number(), make_str(), make_trunk(), manage_parkinglot(), manager_show_dialplan_helper(), map_video_codec(), masq_park_call(), math(), md5(), memcpy_decrypt(), memcpy_encrypt(), mgcp_call(), mgcp_fixup(), mgcp_indicate(), mgcp_new(), mgcp_reload(), mgcp_request(), mgcp_ss(), mgcp_write(), mgcpsock_read(), milliwatt_generate(), minivm_accmess_exec(), minivm_counter_func_read(), minivm_counter_func_write(), minivm_notify_exec(), minivm_record_exec(), misdn_answer(), misdn_call(), misdn_cfg_get(), misdn_cfg_get_config_string(), misdn_cfg_init(), misdn_cfg_is_msn_valid(), misdn_cfg_update_ptp(), misdn_check_l2l1(), misdn_digit_end(), misdn_facility_exec(), misdn_hangup(), misdn_indication(), misdn_request(), misdn_send_text(), misdn_set_opt_exec(), misdn_write(), mixmonitor_exec(), mkif(), mkintf(), moh_alloc(), moh_class_destructor(), moh_files_generator(), moh_files_release(), moh_generate(), moh_release(), moh_scan_files(), mohalloc(), monmp3thread(), morsecode_exec(), mp3_exec(), mp3play(), multiplexed_bridge_create(), multiplexed_thread_function(), mwi_send_init(), mwi_send_process_buffer(), mwi_send_process_event(), mwi_thread(), nbs_alloc(), nbs_call(), nbs_hangup(), nbs_new(), nbs_xwrite(), NBScat_exec(), NBScatplay(), netconsole(), notify_new_message(), odbc_load_module(), odbc_log(), odbc_obj_connect(), odbc_obj_disconnect(), odbc_register_class(), odbc_release_obj2(), ogg_vorbis_read(), ogg_vorbis_rewrite(), ogg_vorbis_seek(), ogg_vorbis_tell(), ogg_vorbis_trunc(), ogg_vorbis_write(), oh323_call(), oh323_fixup(), oh323_hangup(), oh323_indicate(), oh323_request(), oh323_write(), old_milliwatt_exec(), onevent(), op_colon(), op_div(), op_eq(), op_eqtilde(), op_func(), op_minus(), op_negate(), op_plus(), op_rem(), op_times(), OpenHistory(), openserial(), originate_exec(), osp_check_destination(), osp_create_provider(), osp_load(), osplookup_exec(), ospnext_exec(), oss_indicate(), oss_new(), oss_request(), page_exec(), park_call_exec(), park_exec_full(), park_space_reserve(), parkandannounce_exec(), parse(), parse_args(), parse_config(), parse_empty_options(), parse_ie(), parse_minse(), parse_naptr(), parse_register_contact(), parse_request(), parse_session_expires(), parse_srv(), parse_tone_zone(), ParseBookmark(), parsing(), pbx_builtin_background(), pbx_builtin_execiftime(), pbx_builtin_gotoif(), pbx_builtin_gotoiftime(), pbx_builtin_hangup(), pbx_builtin_importvar(), pbx_builtin_pushvar_helper(), pbx_builtin_saynumber(), pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), pbx_builtin_waitexten(), pbx_exec(), pbx_extension_helper(), pbx_find_extension(), pbx_load_config(), pbx_parseable_goto(), pbx_substitute_variables_helper_full(), pcm_read(), pcm_seek(), pcm_write(), peer_set_srcaddr(), phase_e_handler(), phone_call(), phone_digit_end(), phone_exception(), phone_hangup(), phone_indicate(), phone_mini_packet(), phone_new(), phone_read(), phone_setup(), phone_write(), phone_write_buf(), phoneprov_callback(), pickup_do(), pickupchan_exec(), play_message(), play_message_in_bridged_call(), play_moh_exec(), play_record_review(), playback_exec(), playtones_alloc(), playtones_generator(), pop_exec(), post_raw(), powerof(), pp_each_extension_exec(), pqm_exec(), precache_trans(), precache_transactions(), privacy_exec(), private_enum_init(), proc_422_rsp(), proc_session_timer(), process_ast_dsp(), process_dahdi(), process_echocancel(), process_message_callback(), process_opcode(), process_request(), process_returncode(), process_sdp(), process_sdp_a_audio(), process_sdp_c(), process_sdp_o(), process_text_line(), profile_set_param(), proxy_update(), pw_cb(), ql_exec(), queue_exec(), queue_function_qac(), queue_function_qac_dep(), queue_function_queuememberlist(), queue_function_queuewaitingcount(), queue_function_var(), queue_set_param(), queue_transfer_fixup(), quote(), radio_tune(), rbi_out(), rcv_mac_addr(), read_config(), read_config_maps(), read_exec(), read_samples(), readexten_exec(), readfile_exec(), readmimefile(), realtime_destroy_handler(), realtime_directory(), realtime_exec(), realtime_handler(), realtime_ldap_base_ap(), realtime_multi_handler(), realtime_multi_odbc(), realtime_multi_pgsql(), realtime_odbc(), realtime_peer(), realtime_pgsql(), realtime_require_handler(), realtime_store_handler(), realtime_update2_handler(), realtime_update_handler(), realtime_user(), realtimefield_read(), receive_message(), record_exec(), refresh_list(), regex(), register_exten(), register_peer_exten(), register_verify(), registry_rerequest(), reload(), reload_config(), reload_firmware(), reload_followme(), reload_queue_members(), reload_queue_rules(), reload_single_member(), reload_single_queue(), remove_from_queue(), reply_digest(), require_odbc(), require_pgsql(), reset_conf(), restart_monitor(), restart_session_timer(), restore_conference(), restore_gains(), retrans_pkt(), retrydial_exec(), rollback_exec(), rotate_file(), rpt(), rpt_call(), rpt_exec(), rpt_master(), rpt_push_alt_macro(), rpt_tele_thread(), rpt_telemetry(), rqm_exec(), rt_handle_member_record(), rtp_socket(), run_agi(), run_ras(), s_streamwait3(), safe_append(), save_conference(), say_date(), say_date_with_format(), say_datetime(), say_datetime_from_now(), say_init_mode(), say_number_full(), say_time(), saycharstr(), sayfile(), saynum(), scan_service(), scan_thread(), schedule(), select_entry(), send_callerid(), send_client(), send_delay(), send_dtmf(), send_request(), send_retransmit(), send_select_output(), send_tone_burst(), send_waveform_to_channel(), send_waveform_to_fd(), senddtmf_exec(), sendimage_exec(), sendmail(), sendtext_exec(), sendurl_exec(), set(), set_bridge_features_on_config(), set_config(), set_destination(), set_format(), set_full_cmd(), set_insecure_flags(), set_member_paused(), set_moh_exec(), set_state(), set_ulimit(), set_var(), setcallerid_pres_exec(), setdtr(), setflag(), setformat(), setup_dahdi(), setup_privacy_args(), setup_transfer_datastore(), sha1(), shared_read(), shared_write(), shell_helper(), show_dialplan_helper(), showdisplay(), showkeys(), sip_addheader(), sip_alloc(), sip_call(), sip_cli_notify(), sip_dtmfmode(), sip_fixup(), sip_hangup(), sip_indicate(), sip_new(), sip_park(), sip_park_thread(), sip_register(), sip_request_call(), sip_scheddestroy(), sip_sendhtml(), sip_subscribe_mwi(), sip_write(), sipsock_read(), siren14read(), siren14write(), siren7read(), siren7write(), skel_exec(), skinny_call(), skinny_fixup(), skinny_indicate(), skinny_new(), skinny_newcall(), skinny_register(), skinny_request(), skinny_ss(), skinny_transfer(), skinny_write(), sla_add_trunk_to_station(), sla_build_station(), sla_build_trunk(), sla_load_config(), sla_station_exec(), slinear_read(), slinear_write(), smdi_msg_read(), smdi_msg_retrieve_read(), sms_generate(), sms_handleincoming(), sms_log(), sms_readfile(), socket_process(), socket_process_meta(), socket_read(), softhangup_exec(), soundcard_writeframe(), span_message(), spawn_dp_lookup(), spawn_mp3(), speex_get_wb_sz_at(), speex_samples(), speex_write(), speextolin_framein(), spy_generate(), ss_thread(), start_moh_exec(), start_monitor_exec(), start_network_thread(), start_rtp(), start_session_timer(), start_stream(), starttimer(), static_callback(), stop_session_timer(), store_boost(), store_config(), store_config_core(), store_digit(), store_mixer(), store_odbc(), store_pgsql(), store_rxcdtype(), store_rxdemod(), store_rxsdtype(), store_tone_zone_ring_cadence(), store_txmixa(), store_txmixb(), store_txtoctype(), subscript(), swap_subs(), sysinfo_helper(), system_exec_helper(), t38_tx_packet_handler(), tdd_feed(), tdd_new(), telem_lookup(), testclient_exec(), timezone_add(), to_number(), to_string(), tonepair_alloc(), tonepair_generator(), tps_processing_function(), transfer_exec(), TransferCallStep1(), transmit(), transmit_audio(), transmit_invite(), transmit_register(), transmit_request_with_auth(), transmit_response(), transmit_response_with_auth(), transmit_response_with_sdp(), transmit_response_with_t38_sdp(), transmit_state_notify(), transmit_t38(), try_calling(), try_firmware(), try_load_key(), try_transfer(), tryexec_exec(), tvfix(), txt_callback(), unalloc_sub(), unistim_answer(), unistim_call(), unistim_do_senddigit(), unistim_fixup(), unistim_hangup(), unistim_indicate(), unistim_new(), unistim_request(), unistim_rtp_read(), unistim_senddigit_end(), unistim_sendtext(), unistim_ss(), unistim_write(), unistimsock_read(), unload_module(), unlock_read(), unregister_exten(), update2_ldap(), update2_odbc(), update2_pgsql(), update2_prepare(), update_common_options(), update_config(), update_header(), update_ldap(), update_odbc(), update_pgsql(), update_registry(), upqm_exec(), uridecode(), uriencode(), usbradio_fixup(), usbradio_indicate(), usbradio_new(), usbradio_read(), usbradio_request(), used_blocks(), userevent_exec(), verbose_exec(), vm_check_password_shell(), vm_intro(), vox_read(), vox_write(), wait_file(), wait_for_answer(), wait_for_winner(), wait_moh_exec(), waitfor_exec(), waitforring_exec(), waitstream_core(), waituntil_exec(), wav_close(), wav_read(), wav_seek(), wav_write(), write_header(), write_history(), write_stream(), writefile(), xmldoc_build_field(), xmldoc_get_syntax_fun(), xmldoc_string_wrap(), and yyparse().
#define NUMLOGLEVELS 6
Definition at line 192 of file logger.h.
Referenced by handle_logger_set_level().
#define QUEUELOG "queue_log"
Definition at line 35 of file logger.h.
#define VERBOSE_PREFIX_1 " "
Definition at line 41 of file logger.h.
Referenced by console_verboser(), and verbose_exec().
#define VERBOSE_PREFIX_2 " == "
Definition at line 42 of file logger.h.
Referenced by __ast_bridge_technology_register(), ast_bridge_technology_unregister(), console_verboser(), destroy_all_channels(), find_transcoders(), load_config(), setformat(), sip_read(), and verbose_exec().
#define VERBOSE_PREFIX_3 " -- "
Definition at line 43 of file logger.h.
Referenced by aji_handle_subscribe(), ast_say_enumeration_full_he(), ast_say_number_full_he(), attempt_reconnect(), console_verboser(), dialout(), handle_frame(), handle_offhook_message(), init_files_class(), leave_voicemail(), load_rpt_vars(), moh_files_release(), parse_register_contact(), play_record_review(), rpt(), rpt_exec(), and verbose_exec().
#define VERBOSE_PREFIX_4 " > "
Definition at line 44 of file logger.h.
Referenced by console_verboser(), socket_process(), and verbose_exec().
#define VERBOSITY_ATLEAST (level) (option_verbose >= (level) || (ast_opt_verb_file && ast_verbose_get_by_file(__FILE__) >= (level)))
Definition at line 218 of file logger.h.
Referenced by parse_register_contact(), pbx_extension_helper(), purge_sessions(), and timeout_write().
Function Documentation
void __ast_verbose (const char * file, int line, const char * func, const char * fmt, ...)
This works like ast_log, but prints verbose messages to the console depending on verbosity level set. ast_verbose(VERBOSE_PREFIX_3 "Whatever %s is happening\n", "nothing"); This will print the message to the console if the verbose level is set to a level >= 3 Note the abscence of a comma after the VERBOSE_PREFIX_3. This is important. VERBOSE_PREFIX_1 through VERBOSE_PREFIX_3 are defined.
Send a verbose message (based on verbose level)
Definition at line 1295 of file logger.c.
References __ast_verbose_ap().
{
   va_list ap;
   va_start(ap, fmt);
   __ast_verbose_ap(file, line, func, fmt, ap);
   va_end(ap);
}
void __ast_verbose_ap (const char * file, int line, const char * func, const char * fmt, va_list ap)
Definition at line 1239 of file logger.c.
References __LOG_VERBOSE, ast_calloc, ast_cond_signal(), AST_DYNSTR_BUILD_FAILED, ast_free, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_localtime(), ast_log(), ast_opt_timestamp, AST_PTHREADT_NULL, ast_str_buffer(), ast_str_set_va(), ast_str_thread_get(), ast_strftime(), ast_tvnow(), buf, logchannel::list, logcond, logger_print_verbose(), LOGMSG_VERBOSE, logthread, logmsg::str, logmsg::type, verbose_buf, and VERBOSE_BUF_INIT_SIZE.
Referenced by __ast_verbose(), and ast_verbose().
{
   struct logmsg *logmsg = NULL;
   struct ast_str *buf = NULL;
   int res = 0;
   if (!(buf = ast_str_thread_get(&verbose_buf, VERBOSE_BUF_INIT_SIZE)))
      return;
   if (ast_opt_timestamp) {
      struct timeval now;
      struct ast_tm tm;
      char date[40];
      char *datefmt;
      now = ast_tvnow();
      ast_localtime(&now, &tm, NULL);
      ast_strftime(date, sizeof(date), dateformat, &tm);
      datefmt = alloca(strlen(date) + 3 + strlen(fmt) + 1);
      sprintf(datefmt, "%c[%s] %s", 127, date, fmt);
      fmt = datefmt;
   } else {
      char *tmp = alloca(strlen(fmt) + 2);
      sprintf(tmp, "%c%s", 127, fmt);
      fmt = tmp;
   }
   /* Build string */
   res = ast_str_set_va(&buf, 0, fmt, ap);
   /* If the build failed then we can drop this allocated message */
   if (res == AST_DYNSTR_BUILD_FAILED)
      return;
   if (!(logmsg = ast_calloc(1, sizeof(*logmsg) + res + 1)))
      return;
   strcpy(logmsg->str, ast_str_buffer(buf));
   ast_log(__LOG_VERBOSE, file, line, func, "%s", logmsg->str + 1);
   /* Set type */
   logmsg->type = LOGMSG_VERBOSE;
   /* Add to the list and poke the thread if possible */
   if (logthread != AST_PTHREADT_NULL) {
      AST_LIST_LOCK(&logmsgs);
      AST_LIST_INSERT_TAIL(&logmsgs, logmsg, list);
      ast_cond_signal(&logcond);
      AST_LIST_UNLOCK(&logmsgs);
   } else {
      logger_print_verbose(logmsg);
      ast_free(logmsg);
   }
}
void ast_backtrace (void)
Definition at line 1212 of file logger.c.
References ast_debug, ast_log(), free, LOG_DEBUG, and LOG_WARNING.
{
#ifdef HAVE_BKTR
   struct ast_bt *bt;
   int i = 0;
   char **strings;
   if (!(bt = ast_bt_create())) {
      ast_log(LOG_WARNING, "Unable to allocate space for backtrace structure\n");
      return;
   }
   if ((strings = backtrace_symbols(bt->addresses, bt->num_frames))) {
      ast_debug(1, "Got %d backtrace record%c\n", bt->num_frames, bt->num_frames != 1 ? 's' : ' ');
      for (i = 0; i < bt->num_frames; i++) {
         ast_log(LOG_DEBUG, "#%d: [%p] %s\n", i, bt->addresses[i], strings[i]);
      }
      free(strings);
   } else {
      ast_debug(1, "Could not allocate memory for backtrace\n");
   }
   ast_bt_destroy(bt);
#else
   ast_log(LOG_WARNING, "Must run configure with '--with-execinfo' for stack backtraces.\n");
#endif
}
void ast_child_verbose (int level, const char * fmt, ...)
Definition at line 416 of file logger.c.
References ast_free, ast_malloc, msg, and option_verbose.
Referenced by launch_script().
{
   char *msg = NULL, *emsg = NULL, *sptr, *eptr;
   va_list ap, aq;
   int size;
   /* Don't bother, if the level isn't that high */
   if (option_verbose < level) {
      return;
   }
   va_start(ap, fmt);
   va_copy(aq, ap);
   if ((size = vsnprintf(msg, 0, fmt, ap)) < 0) {
      va_end(ap);
      va_end(aq);
      return;
   }
   va_end(ap);
   if (!(msg = ast_malloc(size + 1))) {
      va_end(aq);
      return;
   }
   vsnprintf(msg, size + 1, fmt, aq);
   va_end(aq);
   if (!(emsg = ast_malloc(size * 2 + 1))) {
      ast_free(msg);
      return;
   }
   for (sptr = msg, eptr = emsg; ; sptr++) {
      if (*sptr == '"') {
         *eptr++ = '\\';
      }
      *eptr++ = *sptr;
      if (*sptr == '\0') {
         break;
      }
   }
   ast_free(msg);
   fprintf(stdout, "verbose \"%s\" %d\n", emsg, level);
   fflush(stdout);
   ast_free(emsg);
}
void ast_console_puts (const char * string)
write the string to the console, and all attached console clients
Definition at line 1133 of file asterisk.c.
References ast_network_puts().
Referenced by chan_misdn_log().
{
   fputs(string, stdout);
   fflush(stdout);
   ast_network_puts(string);
}
void ast_console_puts_mutable (const char * string, int level)
log the string to the console, and all attached console clients
Version:
1.6.1 added level parameter
Definition at line 1110 of file asterisk.c.
References ast_network_puts_mutable().
Referenced by logger_print_normal().
{
   fputs(string, stdout);
   fflush(stdout);
   ast_network_puts_mutable(string, level);
}
void ast_console_toggle_loglevel (int fd, int level, int state)
Since:
1.6.1
Definition at line 1057 of file asterisk.c.
References AST_MAX_CONNECTS, consoles, and console::levels.
Referenced by handle_logger_set_level().
{
   int x;
   for (x = 0;x < AST_MAX_CONNECTS; x++) {
      if (fd == consoles[x].fd) {
         consoles[x].levels[level] = state;
         return;
      }
   }
}
void ast_console_toggle_mute (int fd, int silent)
mute or unmute a console from logging
Definition at line 1071 of file asterisk.c.
References ast_cli(), AST_MAX_CONNECTS, consoles, and console::mute.
Referenced by handle_logger_mute().
{
   int x;
   for (x = 0;x < AST_MAX_CONNECTS; x++) {
      if (fd == consoles[x].fd) {
         if (consoles[x].mute) {
            consoles[x].mute = 0;
            if (!silent)
               ast_cli(fd, "Console is not muted anymore.\n");
         } else {
            consoles[x].mute = 1;
            if (!silent)
               ast_cli(fd, "Console is muted.\n");
         }
         return;
      }
   }
   ast_cli(fd, "Couldn't find remote console.\n");
}
unsigned int ast_debug_get_by_file (const char * file)
Get the debug level for a file.
Parameters:
file the filename
Returns:
the debug level
Definition at line 118 of file cli.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_debug_file::filename, and ast_debug_file::level.
{
   struct ast_debug_file *adf;
   unsigned int res = 0;
   AST_RWLIST_RDLOCK(&debug_files);
   AST_LIST_TRAVERSE(&debug_files, adf, entry) {
      if (!strncasecmp(adf->filename, file, strlen(adf->filename))) {
         res = adf->level;
         break;
      }
   }
   AST_RWLIST_UNLOCK(&debug_files);
   return res;
}
void ast_log (int level, const char * file, int line, const char * function, const char * fmt, ...)
Used for sending a log message This is the standard logger function. Probably the only way you will invoke it would be something like this: ast_log(AST_LOG_WHATEVER, "Problem with the %s Captain. We should get some more. Will %d be enough?\n", "flux capacitor", 10); where WHATEVER is one of ERROR, DEBUG, EVENT, NOTICE, or WARNING depending on which log you wish to output to. These are implemented as macros, that will provide the function with the needed arguments.
Parameters:
level Type of log event
file Will be provided by the AST_LOG_* macro
line Will be provided by the AST_LOG_* macro
function Will be provided by the AST_LOG_* macro
fmt This is what is important. The format is the same as your favorite breed of printf. You know how that works, right? :-)
Definition at line 1090 of file logger.c.
References __LOG_DEBUG, __LOG_VERBOSE, ast_calloc, ast_cond_signal(), ast_copy_string(), AST_DYNSTR_BUILD_FAILED, ast_free, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_localtime(), AST_PTHREADT_NULL, AST_RWLIST_EMPTY, ast_str_buffer(), ast_str_set_va(), ast_str_thread_get(), ast_strftime(), ast_tvnow(), buf, logmsg::date, logmsg::file, logmsg::function, GETTID, logmsg::level, logmsg::line, logchannel::list, log_buf, LOG_BUF_INIT_SIZE, logcond, logger_print_normal(), LOGMSG_NORMAL, logthread, option_debug, option_verbose, logmsg::process_id, logmsg::str, term_filter_escapes(), and logmsg::type.
Referenced by __adsi_transmit_messages(), __agent_start_monitoring(), __ao2_callback(), __ao2_ref(), __ast_answer(), __ast_bridge_technology_register(), __ast_channel_alloc_ap(), __ast_check_signature(), __ast_check_signature_bin(), __ast_cli_register(), __ast_cli_unregister(), __ast_custom_function_register(), __ast_decrypt_bin(), __ast_dsp_call_progress(), __ast_encrypt_bin(), __ast_format_register(), __ast_http_load(), __ast_mm_init(), __ast_pbx_run(), __ast_play_and_record(), __ast_queue_frame(), __ast_read(), __ast_register_translator(), __ast_request_and_dial(), __ast_rtp_reload(), __ast_sign_bin(), __ast_smoother_feed(), __ast_string_field_init(), __ast_udptl_reload(), __ast_verbose_ap(), __attempt_transmit(), __auto_congest(), __dahdi_exception(), __find_callno(), __iax2_poke_noanswer(), __init_manager(), __mgcp_xmit(), __oh323_destroy(), __oh323_new(), __oh323_rtp_create(), __oh323_update_info(), __set_address_from_contact(), __sip_autodestruct(), __sip_destroy(), __sip_pretend_ack(), __sip_reliable_xmit(), __sip_xmit(), __transmit_response(), __unload_module(), _ast_adsi_get_cpeid(), _ast_adsi_get_cpeinfo(), _ast_adsi_load_session(), _ast_adsi_transmit_message_full(), _dsp_init(), _enum_array_map(), _extension_match_core(), _get_mohbyname(), _macro_exec(), _moh_register(), _sip_tcp_helper_thread(), _while_exec(), accept_thread(), access_counter_file(), acf_channel_read(), acf_curl_exec(), acf_curlopt_read(), acf_curlopt_write(), acf_cut_exec(), acf_iaxvar_write(), acf_if(), acf_isexten_exec(), acf_jabberstatus_read(), acf_mailbox_exists(), acf_meetme_info(), acf_odbc_read(), acf_odbc_write(), acf_sort_exec(), acf_sprintf(), acf_strftime(), acf_strptime(), acf_transaction_write(), ack_trans(), action_bridge(), action_command(), action_getvar(), action_login(), add_agent(), add_agi_cmd(), add_calltoken_ignore(), add_cfg_entry(), add_codec_to_answer(), add_email_attachment(), add_exten_to_pattern_tree(), add_extensions(), add_features_datastores(), add_header(), add_in_calls(), add_line(), add_out_calls(), add_pri_lockopt(), add_publish_event(), add_realm_authentication(), add_redirect(), add_rt_multi_cfg_entry(), add_sdp(), add_sip_domain(), add_subscribe_event(), add_to_agi(), add_user_extension(), admin_exec(), adsi_begin(), adsi_careful_send(), adsi_process(), adsi_prog(), advanced_options(), ael2_print(), aes_helper(), agent_answer(), agent_call(), agent_fixup(), agent_get_base_channel(), agent_hangup(), agent_new(), agent_read(), agent_request(), agent_set_base_channel(), agentmonitoroutgoing_exec(), agi_exec_full(), aji_act_hook(), aji_client_connect(), aji_client_info_handler(), aji_create_buddy(), aji_create_client(), aji_dinfo_handler(), aji_ditems_handler(), aji_find_version(), aji_handle_presence(), aji_handle_subscribe(), aji_initialize(), aji_load_config(), aji_pruneregister(), aji_recv(), aji_recv_loop(), aji_register_approve_handler(), aji_register_query_handler(), aji_reload(), aji_send_exec(), aji_set_presence(), aji_start_sasl(), aji_status_exec(), alarmreceiver_exec(), alloc_expr_node(), alloc_resampler(), alloc_sub(), alsa_card_init(), alsa_indicate(), alsa_new(), alsa_read(), alsa_request(), alsa_write(), announce_thread(), answer_call(), anti_injection(), app_exec(), apply_general_options(), apply_option(), apply_outgoing(), aqm_exec(), ast_add_extension2_lockopt(), ast_agi_register(), ast_agi_send(), ast_agi_unregister(), ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_ais_evt_load_module(), ast_ais_evt_unload_module(), ast_aji_create_chat(), ast_aji_invite_chat(), ast_aji_join_chat(), ast_aji_send_chat(), ast_alaw_init(), ast_app_dtget(), ast_app_parse_options(), ast_app_parse_options64(), ast_append_ha(), ast_async_goto(), ast_audiohook_write_frame(), ast_autoservice_start(), ast_backtrace(), ast_best_codec(), ast_bridge_call(), ast_call_forward(), ast_careful_fwrite(), ast_carefulwrite(), ast_cdr_alloc(), ast_cdr_end(), ast_cdr_engine_init(), ast_cdr_merge(), ast_cdr_noanswer(), ast_cdr_register(), ast_cdr_serialize_variables(), ast_cdr_setvar(), ast_cdr_submit_batch(), ast_channel_audiohook_count_by_source(), ast_channel_audiohook_count_by_source_running(), ast_channel_bridge(), ast_channel_free(), ast_channel_make_compatible_helper(), ast_channel_masquerade(), ast_channel_queryoption(), ast_channel_register(), ast_channel_setoption(), ast_channel_start_silence_generator(), ast_channel_stop_silence_generator(), ast_check_timing(), ast_cli_perms_init(), ast_codec_get_len(), ast_codec_get_samples(), ast_config_engine_register(), ast_config_internal_load(), ast_context_find_or_create(), ast_context_remove_extension_callerid2(), ast_context_verify_includes(), ast_db_get(), ast_db_gettree(), ast_db_put(), ast_device_state_engine_init(), ast_do_masquerade(), ast_dsp_call_progress(), ast_dsp_noise(), ast_dsp_process(), ast_dsp_silence(), ast_dtmf_stream(), ast_el_read_char(), ast_enable_distributed_devstate(), ast_enable_packet_fragmentation(), ast_event_cb(), ast_event_check_subscriber(), ast_event_get_cached(), ast_event_get_ie_pltype(), ast_event_get_ie_type_name(), ast_event_get_type_name(), ast_event_new(), ast_event_queue(), ast_event_queue_and_cache(), ast_event_subscribe_new(), ast_extension_close(), ast_filehelper(), ast_find_ourip(), ast_format_str_reduce(), ast_format_unregister(), ast_func_read(), ast_func_write(), ast_get_encoded_char(), ast_get_enum(), ast_get_group(), ast_get_ip_or_srv(), ast_hangup(), ast_heap_create(), ast_http_uri_link(), ast_iax2_new(), ast_include_new(), ast_indicate_data(), ast_io_remove(), ast_ivr_menu_run_internal(), ast_jb_put(), ast_linear_stream(), ast_lock_path_flock(), ast_lock_path_lockfile(), ast_makesocket(), ast_manager_register_struct(), ast_manager_unregister(), ast_merge_contexts_and_delete(), ast_module_reload(), ast_moh_files_next(), ast_monitor_change_fname(), ast_monitor_start(), ast_monitor_stop(), ast_netsock_bindaddr(), ast_netsock_set_qos(), ast_odbc_direct_execute(), ast_odbc_find_table(), ast_odbc_prepare_and_execute(), ast_odbc_request_obj2(), ast_odbc_sanity_check(), ast_odbc_smart_execute(), ast_openstream_full(), ast_openvstream(), ast_ouraddrfor(), ast_parse_allow_disallow(), ast_pbx_outgoing_app(), ast_pbx_outgoing_exten(), ast_pbx_run_app(), ast_pbx_start(), ast_pickup_call(), ast_playtones_start(), ast_process_pending_reloads(), ast_prod(), ast_pthread_create_detached_stack(), ast_pthread_create_stack(), ast_read_image(), ast_read_textfile(), ast_readaudio_callback(), ast_readconfig(), ast_readfile(), ast_readvideo_callback(), ast_record_review(), ast_register_application2(), ast_register_feature(), ast_register_switch(), ast_remotecontrol(), ast_request(), ast_rtcp_read(), ast_rtcp_write_rr(), ast_rtcp_write_sr(), ast_rtp_bridge(), ast_rtp_codec_setpref(), ast_rtp_early_bridge(), ast_rtp_get_qosvalue(), ast_rtp_make_compatible(), ast_rtp_new_with_bindaddr(), ast_rtp_proto_register(), ast_rtp_read(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_continuation(), ast_rtp_senddigit_end(), ast_rtp_write(), ast_safe_fork(), ast_safe_system(), ast_say_date_with_format_da(), ast_say_date_with_format_de(), ast_say_date_with_format_en(), ast_say_date_with_format_es(), ast_say_date_with_format_fr(), ast_say_date_with_format_gr(), ast_say_date_with_format_he(), ast_say_date_with_format_it(), ast_say_date_with_format_nl(), ast_say_date_with_format_pl(), ast_say_date_with_format_pt(), ast_say_date_with_format_th(), ast_say_date_with_format_zh(), ast_say_enumeration_full_he(), ast_say_number_full_pt(), ast_say_number_full_zh(), ast_sched_del(), ast_sched_runq(), ast_sched_thread_create(), ast_search_dns(), ast_set_priority(), ast_sip_ouraddrfor(), ast_slinfactory_feed(), ast_smoother_read(), ast_speech_register(), ast_stopstream(), ast_streamfile(), ast_stun_request(), ast_taskprocessor_get(), ast_taskprocessor_name(), ast_taskprocessor_push(), ast_tcptls_client_create(), ast_tcptls_client_start(), ast_tcptls_server_read(), ast_tcptls_server_root(), ast_tcptls_server_start(), ast_tcptls_server_write(), ast_tps_init(), ast_translate_path_steps(), ast_translator_build_path(), ast_tryconnect(), ast_udptl_bridge(), ast_udptl_new_with_bindaddr(), ast_udptl_proto_register(), ast_udptl_read(), ast_udptl_write(), ast_ulaw_init(), ast_unload_resource(), ast_unlock_path_flock(), ast_unlock_path_lockfile(), ast_wait_for_output(), ast_waitfor_nandfds(), ast_waitfordigit_full(), ast_write(), ast_writefile(), ast_writestream(), ast_xmldoc_load_documentation(), ast_yyerror(), async_wait(), asyncgoto_exec(), attempt_reconnect(), attempt_thread(), attempt_transfer(), audiohook_read_frame_both(), auth_exec(), authenticate(), authenticate_reply(), authenticate_verify(), autoservice_run(), available(), background_detect_exec(), base64_decode(), base64_encode(), base_encode(), birdbath(), blr_ebl(), blr_txt(), bridge_array_add(), bridge_call_thread(), bridge_exec(), bridge_make_compatible(), bridge_native_loop(), bridge_p2p_loop(), build_alias(), build_callno_limits(), build_channels(), build_conf(), build_device(), build_event_channel(), build_filename(), build_gateway(), build_mapping(), build_parkinglot(), build_peer(), build_route(), build_rpid(), build_user(), builtin_atxfer(), builtin_automixmonitor(), builtin_automonitor(), builtin_blindtransfer(), bump_gains(), cache_get_callno_locked(), calc_cost(), calc_metric(), calculate_far_max_ifp(), calculate_local_max_datagram(), callerid_feed(), callerid_feed_jp(), callerid_get_dtmf(), callerid_read(), callerid_write(), callerpres_write(), canary_thread(), canmatch(), careful_write(), cb_events(), cb_extensionstate(), cdr_handler(), cdr_merge_vars(), chan_misdn_log(), chan_ringing(), chanavail_exec(), channel_admin_exec(), channel_revert(), channel_spy(), channel_steer(), channel_to_session(), chanspy_exec(), check_abstract_reference(), check_access(), check_app_args(), check_auth(), check_break(), check_compat(), check_context_names(), check_continue(), check_day(), check_dow(), check_expr2_input(), check_for_conference(), check_freq_ic706(), check_goto(), check_header(), check_includes(), check_key(), check_label(), check_macro_returns(), check_month(), check_password(), check_post(), check_pval_item(), check_rtp_timeout(), check_srcaddr(), check_switch_expr(), check_timerange(), check_tx_freq(), check_user_full(), check_vars(), check_via(), cleanup_connection(), clear_caller(), clearcbone(), cleardisplay(), clearflag(), cleartimer(), close_call(), close_client(), close_mailbox(), collect_function_digits(), commit_exec(), compile_script(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_transfer(), compose_func_args(), compress_subclass(), conf_add(), conf_del(), conf_exec(), conf_flush(), conf_queue_dtmf(), conf_run(), confbridge_exec(), config_curl(), config_device(), config_function_read(), config_handler(), config_ldap(), config_line(), config_load(), config_module(), config_odbc(), config_parse_variables(), config_pgsql(), config_text_file_load(), connect_link(), connection_made(), console_autoanswer(), console_cmd(), console_indicate(), console_request(), console_video_start(), context_merge(), controlplayback_exec(), convertcap(), copy(), copy_header(), copy_message(), copy_rules(), copy_via_headers(), count_exec(), create_addr(), create_dirpath(), create_jb(), create_match_char_tree(), create_queue_member(), create_video_frame(), create_vmaccount(), crypto_load(), csv_log(), csv_quote(), custom_log(), custom_prepare(), cut_internal(), dahdi_answer(), dahdi_bridge(), dahdi_call(), dahdi_callwait(), dahdi_confmute(), dahdi_decoder_framein(), dahdi_decoder_frameout(), dahdi_digit_begin(), dahdi_disable_ec(), dahdi_enable_ec(), dahdi_encoder_framein(), dahdi_encoder_frameout(), dahdi_fake_event(), dahdi_get_index(), dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_link(), dahdi_new(), dahdi_open(), dahdi_read(), dahdi_request(), dahdi_restart(), dahdi_ring_phone(), dahdi_sendtext(), dahdi_set_hook(), dahdi_setoption(), dahdi_show_channel(), dahdi_test_timer(), dahdi_timer_set_rate(), dahdi_train_ec(), dahdi_translate(), dahdi_write(), dahdi_write_frame(), dahdiras_exec(), dbinit(), deadagi_exec(), dec_init(), del_exec(), destroy_curl(), destroy_odbc(), destroy_pgsql(), destroy_pval_item(), destroy_session(), destroy_trans(), device_state_cb(), devstate_cache_cb(), devstate_change_collector_cb(), devstate_write(), dial_exec_full(), dialgroup_read(), dialgroup_write(), dialog_ref(), dictate_exec(), digitcollect(), digitdirect(), directory_exec(), disa_exec(), disable_jack_hook(), diskavail(), dispatch_thread_handler(), display_last_error(), dns_parse_answer(), dnsmgr_init(), dnsmgr_refresh(), do_autokill(), do_dtmf_local(), do_forward(), do_magic_pickup(), do_monitor(), do_register(), do_reload(), do_say(), do_scheduler(), do_timelimit(), do_waiting(), donodelog(), dump_agents(), dump_queue(), dump_queue_members(), dundi_answer_entity(), dundi_answer_query(), dundi_discover(), dundi_encrypt(), dundi_error_output(), dundi_exec(), dundi_helper(), dundi_lookup_internal(), dundi_precache_full(), dundi_precache_internal(), dundi_prop_precache(), dundi_query(), dundi_query_read(), dundi_result_read(), dundi_rexmit(), dundi_send(), dundi_xmit(), dundifunc_read(), duplicate_pseudo(), eagi_exec(), ebl_callback(), enable_jack_hook(), encode_open_type(), enum_callback(), enum_query_read(), enum_result_read(), event_channel_destroy(), evt_event_deliver_cb(), exec(), exec_exec(), execif_exec(), exists(), ext_cmp1(), extension_matches(), extenspy_exec(), external_rtp_create(), extstate_read(), fax_generator_generate(), fbuf_append(), feature_exec_app(), feature_request_and_dial(), festival_exec(), ffmpeg_decode(), ffmpeg_encode(), file_read(), filter(), find_account(), find_cache(), find_call_locked(), find_conf(), find_conf_realtime(), find_desc(), find_desc_usb(), find_engine(), find_line_by_instance(), find_matching_endwhile(), find_or_create(), find_parkinglot(), find_pval_goto_item(), find_queue_by_name_rt(), find_sdp(), find_speeddial_by_instance(), find_subchannel_and_lock(), find_subchannel_by_instance_reference(), find_subchannel_by_name(), find_subchannel_by_reference(), find_table(), find_transaction(), find_transcoders(), findmeexec(), finish_bookmark(), flash_exec(), flush_telem(), fn_wrapper(), forkcdr_exec(), forward_message(), framein(), func_args(), func_channel_read(), func_channel_write(), func_channels_read(), func_check_sipdomain(), func_header_read(), func_inheritance_write(), function_agent(), function_autopatchup(), function_cop(), function_db_delete(), function_db_exists(), function_db_read(), function_db_write(), function_enum(), function_eval(), function_ilink(), function_realtime_read(), function_realtime_readdestroy(), function_realtime_store(), function_realtime_write(), function_remote(), function_sipchaninfo_read(), function_sippeer(), function_txtcidname(), g723_len(), g723_read(), g723_write(), g726_read(), g726_write(), g729_read(), g729_write(), generic_execute(), generic_http_callback(), generic_prepare(), get_agi_cmd(), get_alarms(), get_also_info(), get_button_template(), get_canmatch_exten(), get_destination(), get_in_brackets(), get_input(), get_ip_and_port_from_sdp(), get_lock(), get_mem_set(), get_member_penalty(), get_params(), get_range(), get_rdnis(), get_refer_info(), get_timerange(), get_to_address(), get_token(), get_unused_callno(), getdisplaybyname(), getflagbyname(), getkeybyname(), getstatebyname(), getsubbyname(), gosub_exec(), gosubif_exec(), goto_exten(), goto_line(), goto_line_rel(), group_count_function_read(), group_function_write(), gsm_read(), gsm_seek(), gsm_write(), gsmtolin_framein(), gtalk_alloc(), gtalk_call(), gtalk_create_candidates(), gtalk_create_member(), gtalk_digit(), gtalk_free_pvt(), gtalk_handle_dtmf(), gtalk_hangup_farend(), gtalk_indicate(), gtalk_invite(), gtalk_invite_response(), gtalk_is_accepted(), gtalk_is_answered(), gtalk_load_config(), gtalk_new(), gtalk_newcall(), gtalk_parser(), gtalk_request(), gtalk_sendhtml(), gtalk_show_channels(), gtalk_write(), h261_decap(), h263_decap(), h263_encap(), h263_open(), h263_read(), h263_write(), h263p_decap(), h263p_encap(), h264_decap(), h264_encap(), h264_open(), h264_read(), h264_write(), handle_alarms(), handle_call_token(), handle_callforward_button(), handle_capabilities_res_message(), handle_cli_agi_add_cmd(), handle_cli_h323_cycle_gk(), handle_cli_indication_add(), handle_cli_indication_remove(), handle_command_response(), handle_common_options(), handle_devstate_change(), handle_enbloc_call_message(), handle_error(), handle_exec(), handle_getoption(), handle_gosub(), handle_hd_hf(), handle_incoming(), handle_init_event(), handle_input(), handle_invite_replaces(), handle_jack_audio(), handle_keypad_button_message(), handle_link_data(), handle_message(), handle_offhook_message(), handle_onhook_message(), handle_open_receive_channel_ack_message(), handle_options(), handle_orig(), handle_playtones(), handle_recordfile(), handle_register_message(), handle_remote_data(), handle_remote_dtmf_digit(), handle_request(), handle_request_bye(), handle_request_do(), handle_request_info(), handle_request_invite(), handle_request_notify(), handle_request_register(), handle_request_subscribe(), handle_response(), handle_response_invite(), handle_response_notify(), handle_response_peerpoke(), handle_response_refer(), handle_response_register(), handle_response_subscribe(), handle_soft_key_event_message(), handle_stimulus_message(), handle_t38_options(), handle_tcptls_connection(), handle_transfer_button(), handle_updates(), HandleCallIncoming(), HandleCallOutgoing(), hidthread(), hint_read(), http_post_callback(), httpd_helper_thread(), iax2_ack_registry(), iax2_bridge(), iax2_call(), iax2_canmatch(), iax2_devicestate(), iax2_do_register(), iax2_dup_variable_datastore(), iax2_exec(), iax2_exists(), iax2_fixup(), iax2_hangup(), iax2_matchmore(), iax2_poke_peer(), iax2_prov_app(), iax2_read(), iax2_register(), iax2_request(), iax2_send(), iax2_trunk_queue(), iax_error_output(), iax_frame_wrap(), iax_park(), iax_park_thread(), iax_process_template(), iax_provision_reload(), iax_template_parse(), ic706_pltocode(), ices_exec(), icesencode(), iconv_read(), iftime(), ilbc_read(), ilbc_write(), ilbctolin_framein(), import_ch(), in_band_indication(), increase_call_count(), init_acf_query(), init_app_class(), init_jack_data(), init_logger(), init_req(), init_resp(), init_timing_thread(), insert_penaltychange(), inspect_module(), INTERNAL_OBJ(), invent_message(), is_valid_dtmf(), isAnsweringMachine(), isexten_function_read(), ivr_dispatch(), jack_hook_callback(), jack_hook_write(), jb_error_output(), jb_get_and_deliver(), jb_warning_output(), jingle_alloc(), jingle_call(), jingle_create_candidates(), jingle_create_member(), jingle_digit(), jingle_free_pvt(), jingle_handle_dtmf(), jingle_hangup_farend(), jingle_indicate(), jingle_is_answered(), jingle_load_config(), jingle_new(), jingle_newcall(), jingle_parser(), jingle_request(), jingle_sendhtml(), jingle_show_channels(), jingle_write(), join_conference_bridge(), jpeg_read_image(), jpeg_write_image(), key_call(), Keyfavorite(), kickptt(), launch_asyncagi(), launch_monitor_thread(), launch_netscript(), launch_script(), launch_service(), ldap_loadentry(), ldap_reconnect(), leave_voicemail(), linear_alloc(), linear_generator(), linear_release(), linkcount(), lintogsm_framein(), lintolpc10_framein(), lintoulaw(), listener(), listfilter(), load_column_config(), load_config(), load_config_meetme(), load_dynamic_module(), load_indications(), load_module(), load_modules(), load_moh_classes(), load_odbc_config(), load_or_reload_lua_stuff(), load_pbx(), load_realtime_queue(), load_resource(), load_rpt_vars(), load_values_config(), local_alloc(), local_answer(), local_ast_moh_start(), local_call(), local_devicestate(), local_dtmf_helper(), local_fixup(), local_new(), local_write(), log_exec(), log_jack_status(), logger_print_normal(), login_exec(), lookup_iface(), lpc10tolin_framein(), lua_find_extension(), lua_get_state(), lua_read_extensions_file(), macroif_exec(), main(), make_email_file(), make_number(), make_str(), make_trunk(), manage_parkinglot(), manager_modulecheck(), manager_show_dialplan_helper(), map_video_codec(), masq_park_call(), matchmore(), math(), md5(), measurenoise(), meetmemute(), memcpy_decrypt(), memcpy_encrypt(), message_template_build(), message_template_parse_emailbody(), message_template_parse_filebody(), mgcp_call(), mgcp_fixup(), mgcp_indicate(), mgcp_new(), mgcp_reload(), mgcp_request(), mgcp_rtp_read(), mgcp_senddigit_begin(), mgcp_senddigit_end(), mgcp_ss(), mgcp_write(), mgcpsock_read(), milliwatt_generate(), minivm_accmess_exec(), minivm_account_func_read(), minivm_counter_func_read(), minivm_counter_func_write(), minivm_delete_exec(), minivm_greet_exec(), minivm_mwi_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_answer(), misdn_bridge(), misdn_call(), misdn_cfg_get(), misdn_cfg_get_config_string(), misdn_cfg_init(), misdn_cfg_is_msn_valid(), misdn_cfg_update_ptp(), misdn_check_l2l1(), misdn_digit_end(), misdn_facility_exec(), misdn_hangup(), misdn_indication(), misdn_new(), misdn_request(), misdn_send_text(), misdn_set_opt_exec(), misdn_write(), mixmonitor_exec(), mixmonitor_thread(), mkif(), mkintf(), moh_alloc(), moh_class_destructor(), moh_files_generator(), moh_files_release(), moh_generate(), moh_release(), moh_scan_files(), mohalloc(), monmp3thread(), morsecode_exec(), mp3_exec(), mp3play(), mpeg4_decode(), mssql_connect(), multiplexed_bridge_create(), multiplexed_nudge(), multiplexed_thread_function(), mute_fragment(), mwi_send_init(), mwi_send_process_buffer(), mwi_send_process_event(), mwi_sub_event_cb(), mwi_thread(), nbs_alloc(), nbs_call(), nbs_hangup(), nbs_new(), nbs_request(), nbs_xwrite(), NBScat_exec(), NBScatplay(), netconsole(), new_find_extension(), notify_new_message(), odbc_load_module(), odbc_log(), odbc_obj_connect(), odbc_obj_disconnect(), odbc_register_class(), odbc_release_obj2(), ogg_vorbis_open(), ogg_vorbis_read(), ogg_vorbis_rewrite(), ogg_vorbis_seek(), ogg_vorbis_tell(), ogg_vorbis_trunc(), ogg_vorbis_write(), oh323_alloc(), oh323_call(), oh323_digit_begin(), oh323_digit_end(), oh323_fixup(), oh323_hangup(), oh323_indicate(), oh323_read(), oh323_request(), oh323_rtp_read(), oh323_set_rtp_peer(), oh323_write(), old_milliwatt_exec(), onevent(), op_colon(), op_div(), op_eq(), op_eqtilde(), op_func(), op_minus(), op_negate(), op_plus(), op_rem(), op_times(), open_mailbox(), open_stream(), OpenHistory(), openserial(), originate_exec(), osp_check_destination(), osp_create_provider(), osp_load(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), oss_indicate(), oss_new(), oss_request(), page_exec(), park_call_exec(), park_call_full(), park_exec_full(), park_space_reserve(), parkandannounce_exec(), parkinglot_addref(), parkinglot_unref(), parse(), parse_args(), parse_config(), parse_cookies(), parse_empty_options(), parse_gain_value(), parse_ie(), parse_minse(), parse_naptr(), parse_register_contact(), parse_request(), parse_session_expires(), parse_srv(), parse_tone_zone(), ParseBookmark(), parsing(), pbx_builtin_background(), pbx_builtin_execiftime(), pbx_builtin_gotoif(), pbx_builtin_gotoiftime(), pbx_builtin_hangup(), pbx_builtin_importvar(), pbx_builtin_pushvar_helper(), pbx_builtin_saynumber(), pbx_builtin_serialize_variables(), pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), pbx_builtin_waitexten(), pbx_exec(), pbx_extension_helper(), pbx_find_extension(), pbx_load_config(), pbx_load_module(), pbx_load_users(), pbx_parseable_goto(), pbx_substitute_variables_helper_full(), pcm_read(), pcm_seek(), pcm_write(), peek_read(), peer_set_srcaddr(), peercnt_add(), pgsql_log(), pgsql_reconnect(), phase_e_handler(), phone_call(), phone_digit_end(), phone_exception(), phone_hangup(), phone_indicate(), phone_mini_packet(), phone_new(), phone_read(), phone_request(), phone_setup(), phone_write(), phone_write_buf(), phoneprov_callback(), pickup_do(), pickup_exec(), pickupchan_exec(), play_message(), play_message_category(), play_message_datetime(), play_message_in_bridged_call(), play_moh_exec(), play_record_review(), playback_exec(), playtones_alloc(), playtones_generator(), pop_exec(), post_raw(), powerof(), pp_each_extension_exec(), pqm_exec(), precache_trans(), precache_transactions(), prep_email_sub_vars(), privacy_exec(), private_enum_init(), proc_422_rsp(), proc_session_timer(), process_ast_dsp(), process_dahdi(), process_echocancel(), process_message_callback(), process_opcode(), process_request(), process_request_queue(), process_returncode(), process_rfc2833(), process_rfc3389(), process_sdp(), process_sdp_a_audio(), process_sdp_c(), process_sdp_o(), process_text_line(), profile_set_param(), progress(), proxy_update(), pthread_timer_set_rate(), purge_old_messages(), pvalCheckType(), pvalGlobalsAddStatement(), pvalTopLevAddObject(), pw_cb(), ql_exec(), queue_exec(), queue_function_memberpenalty_read(), queue_function_memberpenalty_write(), queue_function_qac(), queue_function_qac_dep(), queue_function_queuememberlist(), queue_function_queuewaitingcount(), queue_function_var(), queue_reload_request(), queue_set_param(), queue_transfer_fixup(), queue_voice_frame(), quote(), radio_tune(), radius_log(), rbi_out(), rcv_mac_addr(), rcvfax_exec(), read_agent_config(), read_config(), read_config_maps(), read_exec(), read_pipe(), read_samples(), readexten_exec(), readfile_exec(), readmimefile(), realtime_curl(), realtime_destroy_handler(), realtime_directory(), realtime_exec(), realtime_handler(), realtime_ldap_base_ap(), realtime_multi_curl(), realtime_multi_handler(), realtime_multi_ldap(), realtime_multi_odbc(), realtime_multi_pgsql(), realtime_odbc(), realtime_peer(), realtime_pgsql(), realtime_require_handler(), realtime_store_handler(), realtime_update2_handler(), realtime_update_handler(), realtime_user(), realtimefield_read(), receive_digit(), receive_message(), record_exec(), refresh_list(), regex(), register_exten(), register_group(), register_group_feature(), register_peer_exten(), register_verify(), registry_rerequest(), reload(), reload_agents(), reload_config(), reload_firmware(), reload_followme(), reload_logger(), reload_queue_members(), reload_queue_rules(), reload_queues(), reload_single_member(), reload_single_queue(), remove_by_peercallno(), remove_by_transfercallno(), remove_from_queue(), replace_callno(), reply_digest(), require_curl(), require_odbc(), require_pgsql(), resample_frame(), reset_conf(), restart_monitor(), restart_session_timer(), restore_conference(), restore_gains(), retrans_pkt(), retreive_memory(), retrydial_exec(), return_exec(), rollback_exec(), rotate_file(), rpt(), rpt_call(), rpt_do_lstats(), rpt_do_stats(), rpt_exec(), rpt_manager_do_stats(), rpt_master(), rpt_push_alt_macro(), rpt_tele_thread(), rpt_telemetry(), rqm_exec(), rt_handle_member_record(), rtp_socket(), run_agi(), run_externnotify(), run_ras(), s_streamwait3(), safe_append(), save_conference(), save_to_folder(), say_date(), say_date_with_format(), say_datetime(), say_datetime_from_now(), say_init_mode(), say_number_full(), say_time(), saycharstr(), sayfile(), saynum(), scan_service(), scan_thread(), schedule(), scheduled_destroy(), select_entry(), send_callerid(), send_client(), send_delay(), send_dtmf(), send_request(), send_retransmit(), send_select_output(), send_tone_burst(), send_usb_txt(), send_waveform_to_channel(), send_waveform_to_fd(), senddtmf_exec(), sendimage_exec(), sendkenwood(), sendmail(), sendpage(), sendtext_exec(), sendurl_exec(), serial_remote_io(), session_do(), set(), set_active(), set_bridge_features_on_config(), set_config(), set_ctcss_mode_ic706(), set_destination(), set_format(), set_freq_ic706(), set_full_cmd(), set_ic706(), set_insecure_flags(), set_member_paused(), set_member_penalty(), set_mode_ic706(), set_moh_exec(), set_offset_ic706(), set_state(), set_ulimit(), set_var(), setcallerid_pres_exec(), setdtr(), setflag(), setformat(), setrem(), setup_dahdi(), setup_incoming_call(), setup_privacy_args(), setup_rtp_connection(), setup_transfer_datastore(), sha1(), shared_read(), shared_write(), shell_helper(), show_dialplan_helper(), showdisplay(), showkeys(), sip_addheader(), sip_alloc(), sip_call(), sip_cli_notify(), sip_dtmfmode(), sip_dump_history(), sip_fixup(), sip_hangup(), sip_indicate(), sip_new(), sip_park(), sip_park_thread(), sip_parse_host(), sip_poke_noanswer(), sip_poke_peer(), sip_queryoption(), sip_read(), sip_reg_timeout(), sip_register(), sip_removeheader(), sip_request_call(), sip_reregister(), sip_rtp_read(), sip_scheddestroy(), sip_sendhtml(), sip_sipredirect(), sip_st_alloc(), sip_subscribe_mwi(), sip_tcptls_write(), sip_threadinfo_create(), sip_write(), sipsock_read(), siren14read(), siren14write(), siren7read(), siren7write(), skel_exec(), skinny_call(), skinny_fixup(), skinny_indicate(), skinny_new(), skinny_newcall(), skinny_register(), skinny_req_parse(), skinny_request(), skinny_ss(), skinny_transfer(), skinny_write(), sla_add_trunk_to_station(), sla_build_station(), sla_build_trunk(), sla_load_config(), sla_queue_event_conf(), sla_state(), sla_station_exec(), sla_trunk_exec(), slinear_read(), slinear_write(), smdi_load(), smdi_msg_read(), smdi_msg_retrieve_read(), smdi_read(), smdi_toggle_mwi(), smoother_frame_feed(), sms_exec(), sms_generate(), sms_handleincoming(), sms_log(), sms_messagerx2(), sms_process(), sms_readfile(), sms_writefile(), sndfax_exec(), socket_process(), socket_process_meta(), socket_read(), softhangup_exec(), soundcard_init(), soundcard_writeframe(), span_message(), spawn_dp_lookup(), spawn_mp3(), speex_get_wb_sz_at(), speex_read(), speex_samples(), speex_write(), speextolin_framein(), spy_generate(), sqlite3_log(), sqlite_log(), ss_thread(), ssl_lock(), start_moh_exec(), start_monitor_exec(), start_network_thread(), start_rtp(), start_session_timer(), start_spying(), start_stream(), starttimer(), static_callback(), statpost(), stop_session_timer(), store_boost(), store_by_peercallno(), store_by_transfercallno(), store_config(), store_config_core(), store_curl(), store_digit(), store_mixer(), store_odbc(), store_pgsql(), store_rxcdtype(), store_rxdemod(), store_rxsdtype(), store_tone_zone_ring_cadence(), store_txmixa(), store_txmixb(), store_txtoctype(), stub_ast_key_get(), subscribe_event_destroy(), subscript(), substitute_escapes(), swap_subs(), sysinfo_helper(), system_exec_helper(), t38_tx_packet_handler(), tdd_feed(), tdd_new(), tds_error_handler(), tds_load_module(), tds_log(), tds_message_handler(), telem_lookup(), testclient_exec(), testserver_exec(), timed_read(), timeout_read(), timeout_write(), timerfd_timer_ack(), timerfd_timer_close(), timerfd_timer_disable_continuous(), timerfd_timer_enable_continuous(), timerfd_timer_get_event(), timerfd_timer_open(), timerfd_timer_set_rate(), timezone_add(), to_number(), to_string(), tonepair_alloc(), tonepair_generator(), tps_processing_function(), tps_taskprocessor_destroy(), tps_taskprocessor_pop(), transfer_exec(), TransferCallStep1(), transmit(), transmit_audio(), transmit_invite(), transmit_refer(), transmit_register(), transmit_request_with_auth(), transmit_response(), transmit_response_using_temp(), transmit_response_with_auth(), transmit_response_with_sdp(), transmit_response_with_t38_sdp(), transmit_state_notify(), transmit_t38(), try_calling(), try_firmware(), try_load_key(), try_suggested_sip_codec(), try_transfer(), tryexec_exec(), tvfix(), txt_callback(), unalloc_sub(), unistim_answer(), unistim_call(), unistim_do_senddigit(), unistim_fixup(), unistim_hangup(), unistim_indicate(), unistim_new(), unistim_request(), unistim_rtp_read(), unistim_senddigit_end(), unistim_sendtext(), unistim_ss(), unistim_write(), unistimsock_read(), unload_module(), unlock_read(), unregister_exten(), update2_curl(), update2_ldap(), update2_odbc(), update2_pgsql(), update2_prepare(), update_call_counter(), update_common_options(), update_config(), update_curl(), update_header(), update_key(), update_ldap(), update_odbc(), update_pgsql(), update_registry(), update_scoreboard(), upqm_exec(), uridecode(), uriencode(), usbradio_fixup(), usbradio_indicate(), usbradio_new(), usbradio_read(), usbradio_request(), usbradio_text(), usbradio_write(), used_blocks(), userevent_exec(), verbose_exec(), vm_authenticate(), vm_box_exists(), vm_change_password(), vm_check_password_shell(), vm_exec(), vm_execmain(), vm_intro(), vm_newuser(), vm_options(), vox_read(), vox_write(), wait_file(), wait_file2(), wait_for_answer(), wait_for_winner(), wait_interval(), wait_moh_exec(), waitfor_exec(), waitforring_exec(), waitstream_core(), waituntil_exec(), wav_close(), wav_read(), wav_seek(), wav_write(), write_byte(), write_header(), write_history(), write_stream(), writefile(), xmldoc_build_field(), xmldoc_get_syntax_fun(), xmldoc_string_cleanup(), xmldoc_string_wrap(), xpmr_config(), yyerror(), and yyparse().
{
   struct logmsg *logmsg = NULL;
   struct ast_str *buf = NULL;
   struct ast_tm tm;
   struct timeval now = ast_tvnow();
   int res = 0;
   va_list ap;
   if (!(buf = ast_str_thread_get(&log_buf, LOG_BUF_INIT_SIZE)))
      return;
   if (AST_RWLIST_EMPTY(&logchannels)) {
      /*
       * we don't have the logger chain configured yet,
       * so just log to stdout
       */
      if (level != __LOG_VERBOSE) {
         int result;
         va_start(ap, fmt);
         result = ast_str_set_va(&buf, BUFSIZ, fmt, ap); /* XXX BUFSIZ ? */
         va_end(ap);
         if (result != AST_DYNSTR_BUILD_FAILED) {
            term_filter_escapes(ast_str_buffer(buf));
            fputs(ast_str_buffer(buf), stdout);
         }
      }
      return;
   }
   /* don't display LOG_DEBUG messages unless option_verbose _or_ option_debug
      are non-zero; LOG_DEBUG messages can still be displayed if option_debug
      is zero, if option_verbose is non-zero (this allows for 'level zero'
      LOG_DEBUG messages to be displayed, if the logmask on any channel
      allows it)
   */
   if (!option_verbose && !option_debug && (level == __LOG_DEBUG))
      return;
   /* Ignore anything that never gets logged anywhere */
   if (!(global_logmask & (1 << level)))
      return;
   /* Build string */
   va_start(ap, fmt);
   res = ast_str_set_va(&buf, BUFSIZ, fmt, ap);
   va_end(ap);
   /* If the build failed, then abort and free this structure */
   if (res == AST_DYNSTR_BUILD_FAILED)
      return;
   /* Create a new logging message */
   if (!(logmsg = ast_calloc(1, sizeof(*logmsg) + res + 1)))
      return;
   /* Copy string over */
   strcpy(logmsg->str, ast_str_buffer(buf));
   /* Set type to be normal */
   logmsg->type = LOGMSG_NORMAL;
   /* Create our date/time */
   ast_localtime(&now, &tm, NULL);
   ast_strftime(logmsg->date, sizeof(logmsg->date), dateformat, &tm);
   /* Copy over data */
   logmsg->level = level;
   logmsg->line = line;
   ast_copy_string(logmsg->file, file, sizeof(logmsg->file));
   ast_copy_string(logmsg->function, function, sizeof(logmsg->function));
   logmsg->process_id = (long) GETTID();
   /* If the logger thread is active, append it to the tail end of the list - otherwise skip that step */
   if (logthread != AST_PTHREADT_NULL) {
      AST_LIST_LOCK(&logmsgs);
      AST_LIST_INSERT_TAIL(&logmsgs, logmsg, list);
      ast_cond_signal(&logcond);
      AST_LIST_UNLOCK(&logmsgs);
   } else {
      logger_print_normal(logmsg);
      ast_free(logmsg);
   }
   return;
}
void ast_queue_log (const char * queuename, const char * callid, const char * agent, const char * event, const char * fmt, ...)
Definition at line 465 of file logger.c.
References ast_check_realtime(), AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_store_realtime(), qlog, and SENTINEL.
Referenced by agent_logoff_maintenance(), aqm_exec(), find_queue_by_name_rt(), handle_queue_add_member(), handle_queue_remove_member(), init_logger(), login_exec(), manager_add_queue_member(), manager_queue_log_custom(), manager_remove_queue_member(), ql_exec(), queue_exec(), queue_transfer_fixup(), reload_logger(), rna(), rqm_exec(), rt_handle_member_record(), set_member_paused(), set_member_penalty(), try_calling(), update_realtime_members(), and wait_our_turn().
{
   va_list ap;
   char qlog_msg[8192];
   int qlog_len;
   char time_str[16];
   if (ast_check_realtime("queue_log")) {
      va_start(ap, fmt);
      vsnprintf(qlog_msg, sizeof(qlog_msg), fmt, ap);
      va_end(ap);
      snprintf(time_str, sizeof(time_str), "%ld", (long)time(NULL));
      ast_store_realtime("queue_log", "time", time_str,
                  "callid", callid,
                  "queuename", queuename,
                  "agent", agent,
                  "event", event,
                  "data", qlog_msg,
                  SENTINEL);
   } else {
      if (qlog) {
         va_start(ap, fmt);
         qlog_len = snprintf(qlog_msg, sizeof(qlog_msg), "%ld|%s|%s|%s|%s|", (long)time(NULL), callid, queuename, agent, event);
         vsnprintf(qlog_msg + qlog_len, sizeof(qlog_msg) - qlog_len, fmt, ap);
         va_end(ap);
      }
      AST_RWLIST_RDLOCK(&logchannels);
      if (qlog) {
         fprintf(qlog, "%s\n", qlog_msg);
         fflush(qlog);
      }
      AST_RWLIST_UNLOCK(&logchannels);
   }
}
int ast_register_verbose (void(*)(const char *string) verboser)
Definition at line 1314 of file logger.c.
References ast_malloc, AST_RWLIST_INSERT_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, logchannel::list, and verb::verboser.
Referenced by ast_makesocket(), main(), and show_console().
{
   struct verb *verb;
   if (!(verb = ast_malloc(sizeof(*verb))))
      return -1;
   verb->verboser = v;
   AST_RWLIST_WRLOCK(&verbosers);
   AST_RWLIST_INSERT_HEAD(&verbosers, verb, list);
   AST_RWLIST_UNLOCK(&verbosers);
   return 0;
}
int ast_unregister_verbose (void(*)(const char *string) verboser)
Definition at line 1330 of file logger.c.
References ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, logchannel::list, and verb::verboser.
Referenced by exit_now().
{
   struct verb *cur;
   AST_RWLIST_WRLOCK(&verbosers);
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&verbosers, cur, list) {
      if (cur->verboser == v) {
         AST_RWLIST_REMOVE_CURRENT(list);
         ast_free(cur);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   AST_RWLIST_UNLOCK(&verbosers);
   return cur ? 0 : -1;
}
unsigned int ast_verbose_get_by_file (const char * file)
Get the debug level for a file.
Parameters:
file the filename
Returns:
the debug level
Definition at line 135 of file cli.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_debug_file::filename, and ast_debug_file::level.
{
   struct ast_debug_file *adf;
   unsigned int res = 0;
   AST_RWLIST_RDLOCK(&verbose_files);
   AST_LIST_TRAVERSE(&verbose_files, adf, entry) {
      if (!strncasecmp(adf->filename, file, strlen(file))) {
         res = adf->level;
         break;
      }
   }
   AST_RWLIST_UNLOCK(&verbose_files);
   return res;
}
int logger_reload (void)
Reload logger without rotating log files.
Definition at line 687 of file logger.c.
References reload_logger(), RESULT_FAILURE, and RESULT_SUCCESS.
{
   if(reload_logger(0))
      return RESULT_FAILURE;
   return RESULT_SUCCESS;
}