Wed May 5 15:22:23 2010
Asterisk developer's documentation
module.h File Reference
Asterisk module definitions.
#include "asterisk/utils.h"
Data Structures
struct ast_module_info
Defines
#define __MODULE_INFO_GLOBALS
#define __MODULE_INFO_SECTION
#define AST_MODULE_CONFIG "modules.conf"
Module configuration file.
#define AST_MODULE_INFO(keystr, flags_to_set, desc, fields...)
#define AST_MODULE_INFO_STANDARD(keystr, desc)
#define ast_module_user_add(chan) __ast_module_user_add(ast_module_info->self, chan)
#define ast_module_user_hangup_all() __ast_module_user_hangup_all(ast_module_info->self)
#define ast_module_user_remove(user) __ast_module_user_remove(ast_module_info->self, user)
#define ast_register_application(app, execute, synopsis, description) ast_register_application2(app, execute, synopsis, description, ast_module_info->self)
Register an application.
#define ast_register_application_xml(app, execute) ast_register_application(app, execute, NULL, NULL)
Register an application using XML documentation.
#define ASTERISK_GPL_KEY "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n"
The text the key() function should return.
Enumerations
enum ast_module_flags { AST_MODFLAG_DEFAULT = 0, AST_MODFLAG_GLOBAL_SYMBOLS = (1 << 0), AST_MODFLAG_LOAD_ORDER = (1 << 1) }
enum ast_module_load_result {
AST_MODULE_LOAD_SUCCESS = 0, AST_MODULE_LOAD_DECLINE = 1, AST_MODULE_LOAD_SKIP = 2, AST_MODULE_LOAD_PRIORITY = 3,
AST_MODULE_LOAD_FAILURE = -1
}
enum ast_module_unload_mode { AST_FORCE_SOFT = 0, AST_FORCE_FIRM = 1, AST_FORCE_HARD = 2 }
Functions
struct ast_module_user * __ast_module_user_add (struct ast_module *, struct ast_channel *)
void __ast_module_user_hangup_all (struct ast_module *)
void __ast_module_user_remove (struct ast_module *, struct ast_module_user *)
enum ast_module_load_result ast_load_resource (const char *resource_name)
Load a module.
int ast_loader_register (int(*updater)(void))
Add a procedure to be run when modules have been updated.
int ast_loader_unregister (int(*updater)(void))
Remove a procedure to be run when modules are updated.
int ast_module_check (const char *name)
Check if module with the name given is loaded.
char * ast_module_helper (const char *line, const char *word, int pos, int state, int rpos, int needsreload)
Match modules names for the Asterisk cli.
struct ast_module * ast_module_ref (struct ast_module *)
void ast_module_register (const struct ast_module_info *)
void ast_module_shutdown (void)
Run the unload() callback for all loaded modules.
void ast_module_unref (struct ast_module *)
void ast_module_unregister (const struct ast_module_info *)
int ast_register_application2 (const char *app, int(*execute)(struct ast_channel *, void *), const char *synopsis, const char *description, void *mod)
Register an application.
int ast_unload_resource (const char *resource_name, enum ast_module_unload_mode)
Unload a module.
int ast_unregister_application (const char *app)
Unregister an application.
int ast_update_module_list (int(*modentry)(const char *module, const char *description, int usecnt, const char *like), const char *like)
Ask for a list of modules, descriptions, and use counts.
void ast_update_use_count (void)
Notify when usecount has been changed.
Variables
static struct ast_module_info * ast_module_info
Detailed Description
Asterisk module definitions.
This file contains the definitons for functions Asterisk modules should provide and some other module related functions.
Definition in file module.h.
Define Documentation
#define __MODULE_INFO_GLOBALS
Definition at line 287 of file module.h.
#define __MODULE_INFO_SECTION
Definition at line 286 of file module.h.
#define AST_MODULE_CONFIG "modules.conf"
Module configuration file.
Definition at line 51 of file module.h.
Referenced by load_modules().
#define AST_MODULE_INFO (keystr, flags_to_set, desc, fields...)
Definition at line 344 of file module.h.
#define AST_MODULE_INFO_STANDARD (keystr, desc)
Value:
AST_MODULE_INFO(keystr, AST_MODFLAG_DEFAULT, desc, \
         .load = load_module,       \
         .unload = unload_module,      \
             )
Definition at line 366 of file module.h.
#define ast_module_user_add (chan) __ast_module_user_add(ast_module_info->self, chan)
Definition at line 240 of file module.h.
Referenced by canmatch(), dundi_query_read(), dundi_result_read(), dundifunc_read(), exec(), exists(), local_new(), login_exec(), matchmore(), nbs_new(), smdi_msg_read(), and smdi_msg_retrieve_read().
#define ast_module_user_hangup_all () __ast_module_user_hangup_all(ast_module_info->self)
Definition at line 242 of file module.h.
Referenced by unload_module().
#define ast_module_user_remove (user) __ast_module_user_remove(ast_module_info->self, user)
Definition at line 241 of file module.h.
Referenced by canmatch(), dundi_query_read(), dundi_result_read(), dundifunc_read(), exec(), exists(), local_hangup(), login_exec(), matchmore(), nbs_destroy(), smdi_msg_read(), and smdi_msg_retrieve_read().
#define ast_register_application (app, execute, synopsis, description) ast_register_application2(app, execute, synopsis, description, ast_module_info->self)
Register an application.
Parameters:
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
synopsis a short description (one line synopsis) of the application
description long description with all of the details about the use of the application
This registers an application with Asterisk's internal application list.
Note:
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values:
0 success
-1 failure.
Definition at line 390 of file module.h.
Referenced by load_module().
#define ast_register_application_xml (app, execute) ast_register_application(app, execute, NULL, NULL)
Register an application using XML documentation.
Parameters:
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
This registers an application with Asterisk's internal application list.
Note:
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values:
0 success
-1 failure.
Definition at line 406 of file module.h.
Referenced by load_module().
#define ASTERISK_GPL_KEY "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n"
The text the key() function should return.
Definition at line 38 of file module.h.
Enumeration Type Documentation
enum ast_module_flags
Enumerator:
AST_MODFLAG_DEFAULT
AST_MODFLAG_GLOBAL_SYMBOLS
AST_MODFLAG_LOAD_ORDER
Definition at line 190 of file module.h.
                      {
   AST_MODFLAG_DEFAULT = 0,
   AST_MODFLAG_GLOBAL_SYMBOLS = (1 << 0),
   AST_MODFLAG_LOAD_ORDER = (1 << 1),
};
enum ast_module_load_result
Enumerator:
AST_MODULE_LOAD_SUCCESS
Module loaded and configured
AST_MODULE_LOAD_DECLINE
Module is not configured
AST_MODULE_LOAD_SKIP
Module was skipped for some reason
AST_MODULE_LOAD_PRIORITY
Module is not loaded yet, but is added to prioity heap
AST_MODULE_LOAD_FAILURE
Module could not be loaded properly
Definition at line 60 of file module.h.
{
   AST_MODULE_LOAD_SUCCESS = 0,    /*!< Module loaded and configured */
   AST_MODULE_LOAD_DECLINE = 1,    /*!< Module is not configured */
   AST_MODULE_LOAD_SKIP = 2,       /*!< Module was skipped for some reason */
   AST_MODULE_LOAD_PRIORITY = 3,   /*!< Module is not loaded yet, but is added to prioity heap */
   AST_MODULE_LOAD_FAILURE = -1,   /*!< Module could not be loaded properly */
};
enum ast_module_unload_mode
Enumerator:
AST_FORCE_SOFT
Softly unload a module, only if not in use
AST_FORCE_FIRM
Firmly unload a module, even if in use
AST_FORCE_HARD
as FIRM, plus dlclose() on the module. Not recommended as it may cause crashes
Definition at line 53 of file module.h.
{
   AST_FORCE_SOFT = 0, /*!< Softly unload a module, only if not in use */
   AST_FORCE_FIRM = 1, /*!< Firmly unload a module, even if in use */
   AST_FORCE_HARD = 2, /*!< as FIRM, plus dlclose() on the module. Not recommended
            as it may cause crashes */
};
Function Documentation
struct ast_module_user* __ast_module_user_add (struct ast_module * , struct ast_channel *) [read]
Definition at line 195 of file loader.c.
References ast_atomic_fetchadd_int(), ast_calloc, AST_LIST_INSERT_HEAD, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_update_use_count(), ast_module_user::chan, ast_module::usecount, and ast_module::users.
Referenced by ast_func_read(), ast_func_write(), and pbx_exec().
{
   struct ast_module_user *u = ast_calloc(1, sizeof(*u));
   if (!u)
      return NULL;
   u->chan = chan;
   AST_LIST_LOCK(&mod->users);
   AST_LIST_INSERT_HEAD(&mod->users, u, entry);
   AST_LIST_UNLOCK(&mod->users);
   ast_atomic_fetchadd_int(&mod->usecount, +1);
   ast_update_use_count();
   return u;
}
void __ast_module_user_hangup_all (struct ast_module *)
Definition at line 227 of file loader.c.
References ast_atomic_fetchadd_int(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE_HEAD, AST_LIST_UNLOCK, ast_softhangup(), AST_SOFTHANGUP_APPUNLOAD, ast_update_use_count(), ast_module_user::chan, ast_module::usecount, and ast_module::users.
Referenced by ast_unload_resource().
{
   struct ast_module_user *u;
   AST_LIST_LOCK(&mod->users);
   while ((u = AST_LIST_REMOVE_HEAD(&mod->users, entry))) {
      ast_softhangup(u->chan, AST_SOFTHANGUP_APPUNLOAD);
      ast_atomic_fetchadd_int(&mod->usecount, -1);
      ast_free(u);
   }
   AST_LIST_UNLOCK(&mod->users);
   ast_update_use_count();
}
void __ast_module_user_remove (struct ast_module * , struct ast_module_user *)
Definition at line 216 of file loader.c.
References ast_atomic_fetchadd_int(), ast_free, AST_LIST_LOCK, AST_LIST_REMOVE, AST_LIST_UNLOCK, ast_update_use_count(), ast_module::usecount, and ast_module::users.
Referenced by ast_func_read(), ast_func_write(), and pbx_exec().
{
   AST_LIST_LOCK(&mod->users);
   AST_LIST_REMOVE(&mod->users, u, entry);
   AST_LIST_UNLOCK(&mod->users);
   ast_atomic_fetchadd_int(&mod->usecount, -1);
   ast_free(u);
   ast_update_use_count();
}
enum ast_module_load_result ast_load_resource (const char * resource_name)
Load a module.
Parameters:
resource_name The name of the module to load.
This function is run by the PBX to load the modules. It performs all loading and initialization tasks. Basically, to load a module, just give it the name of the module and it will do the rest.
Returns:
See possible enum values for ast_module_load_result.
Definition at line 831 of file loader.c.
References AST_LIST_LOCK, AST_LIST_UNLOCK, and load_resource().
Referenced by file_ok_sel(), handle_load(), load_module(), manager_moduleload(), and reload().
{
   int res;
   AST_LIST_LOCK(&module_list);
   res = load_resource(resource_name, 0, NULL);
   AST_LIST_UNLOCK(&module_list);
   return res;
}
int ast_loader_register (int(*)(void) updater)
Add a procedure to be run when modules have been updated.
Parameters:
updater The function to run when modules have been updated.
This function adds the given function to a linked list of functions to be run when the modules are updated.
Return values:
0 on success
-1 on failure.
Definition at line 1131 of file loader.c.
References AST_LIST_INSERT_HEAD, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_malloc, and loadupdate::updater.
Referenced by show_console().
{
   struct loadupdate *tmp;
   if (!(tmp = ast_malloc(sizeof(*tmp))))
      return -1;
   tmp->updater = v;
   AST_LIST_LOCK(&updaters);
   AST_LIST_INSERT_HEAD(&updaters, tmp, entry);
   AST_LIST_UNLOCK(&updaters);
   return 0;
}
int ast_loader_unregister (int(*)(void) updater)
Remove a procedure to be run when modules are updated.
Parameters:
updater The updater function to unregister.
This removes the given function from the updater list.
Return values:
0 on success
-1 on failure.
Definition at line 1146 of file loader.c.
References AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, and loadupdate::updater.
Referenced by exit_now().
{
   struct loadupdate *cur;
   AST_LIST_LOCK(&updaters);
   AST_LIST_TRAVERSE_SAFE_BEGIN(&updaters, cur, entry) {
      if (cur->updater == v)  {
         AST_LIST_REMOVE_CURRENT(entry);
         break;
      }
   }
   AST_LIST_TRAVERSE_SAFE_END;
   AST_LIST_UNLOCK(&updaters);
   return cur ? 0 : -1;
}
int ast_module_check (const char * name)
Check if module with the name given is loaded.
Parameters:
name Module name, like "chan_sip.so"
Return values:
1 if true
0 if false
Definition at line 1118 of file loader.c.
References ast_strlen_zero(), and find_resource().
Referenced by ifmodule_read(), load_module(), manager_modulecheck(), and unload_module().
{
   struct ast_module *cur;
   if (ast_strlen_zero(name))
      return 0;       /* FALSE */
   cur = find_resource(name, 1);
   return (cur != NULL);
}
char* ast_module_helper (const char * line, const char * word, int pos, int state, int rpos, int needsreload)
Match modules names for the Asterisk cli.
Parameters:
line Unused by this function, but this should be the line we are matching.
word The partial name to match.
pos The position the word we are completing is in.
state The possible match to return.
rpos The position we should be matching. This should be the same as pos.
needsreload This should be 1 if we need to reload this module and 0 otherwise. This function will only return modules that are reloadble if this is 1.
Return values:
A possible completion of the partial match.
NULL if no matches were found.
Definition at line 542 of file loader.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, ast_strdup, ast_module::info, name, ast_module_info::reload, and ast_module::resource.
Referenced by handle_modlist(), handle_reload(), handle_unload(), and load_module().
{
   struct ast_module *cur;
   int i, which=0, l = strlen(word);
   char *ret = NULL;
   if (pos != rpos)
      return NULL;
   AST_LIST_LOCK(&module_list);
   AST_LIST_TRAVERSE(&module_list, cur, entry) {
      if (!strncasecmp(word, cur->resource, l) &&
          (cur->info->reload || !needsreload) &&
          ++which > state) {
         ret = ast_strdup(cur->resource);
         break;
      }
   }
   AST_LIST_UNLOCK(&module_list);
   if (!ret) {
      for (i=0; !ret && reload_classes[i].name; i++) {
         if (!strncasecmp(word, reload_classes[i].name, l) && ++which > state)
            ret = ast_strdup(reload_classes[i].name);
      }
   }
   return ret;
}
struct ast_module* ast_module_ref (struct ast_module *) [read]
Definition at line 1163 of file loader.c.
References ast_atomic_fetchadd_int(), ast_update_use_count(), and ast_module::usecount.
Referenced by __oh323_new(), agi_handle_command(), alsa_new(), ast_agi_register(), ast_iax2_new(), ast_timer_open(), dahdi_new(), find_best_technology(), fn_wrapper(), gtalk_new(), handle_cli_file_convert(), handle_orig(), load_module(), mgcp_new(), moh_alloc(), moh_files_alloc(), newpvt(), oss_new(), phone_check_exception(), phone_new(), sip_new(), skinny_new(), smdi_load(), and usbradio_new().
{
   ast_atomic_fetchadd_int(&mod->usecount, +1);
   ast_update_use_count();
   return mod;
}
void ast_module_register (const struct ast_module_info *)
Definition at line 133 of file loader.c.
References ast_calloc, AST_LIST_HEAD_INIT, AST_LIST_INSERT_TAIL, AST_LIST_LOCK, AST_LIST_UNLOCK, embedding, ast_module::info, ast_module::resource, and ast_module::users.
{
   struct ast_module *mod;
   if (embedding) {
      if (!(mod = ast_calloc(1, sizeof(*mod) + strlen(info->name) + 1)))
         return;
      strcpy(mod->resource, info->name);
   } else {
      mod = resource_being_loaded;
   }
   mod->info = info;
   AST_LIST_HEAD_INIT(&mod->users);
   /* during startup, before the loader has been initialized,
      there are no threads, so there is no need to take the lock
      on this list to manipulate it. it is also possible that it
      might be unsafe to use the list lock at that point... so
      let's avoid it altogether
   */
   if (embedding) {
      AST_LIST_INSERT_TAIL(&embedded_module_list, mod, entry);
   } else {
      AST_LIST_LOCK(&module_list);
      /* it is paramount that the new entry be placed at the tail of
         the list, otherwise the code that uses dlopen() to load
         dynamic modules won't be able to find out if the module it
         just opened was registered or failed to load
      */
      AST_LIST_INSERT_TAIL(&module_list, mod, entry);
      AST_LIST_UNLOCK(&module_list);
   }
   /* give the module a copy of its own handle, for later use in registrations and the like */
   *((struct ast_module **) &(info->self)) = mod;
}
void ast_module_shutdown (void)
Run the unload() callback for all loaded modules.
This function should be called when Asterisk is shutting down gracefully.
Note:
Some resources, like timers, are started up dynamically, and thus may be still in use, even if all channels are dead. We must therefore check the usecount before asking modules to unload.
If we go through the entire list without changing anything, ignore the usecounts and unload, then exit.
Definition at line 444 of file loader.c.
References AST_LIST_HEAD_DESTROY, AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, free, ast_module::info, ast_module_info::unload, ast_module::usecount, and ast_module::users.
Referenced by quit_handler().
{
   struct ast_module *mod;
   int somethingchanged = 1, final = 0;
   AST_LIST_LOCK(&module_list);
   /*!\note Some resources, like timers, are started up dynamically, and thus
    * may be still in use, even if all channels are dead.  We must therefore
    * check the usecount before asking modules to unload. */
   do {
      if (!somethingchanged) {
         /*!\note If we go through the entire list without changing
          * anything, ignore the usecounts and unload, then exit. */
         final = 1;
      }
      /* Reset flag before traversing the list */
      somethingchanged = 0;
      AST_LIST_TRAVERSE_SAFE_BEGIN(&module_list, mod, entry) {
         if (!final && mod->usecount) {
            continue;
         }
         AST_LIST_REMOVE_CURRENT(entry);
         if (mod->info->unload) {
            mod->info->unload();
         }
         AST_LIST_HEAD_DESTROY(&mod->users);
         free(mod);
         somethingchanged = 1;
      }
      AST_LIST_TRAVERSE_SAFE_END;
   } while (somethingchanged && !final);
   AST_LIST_UNLOCK(&module_list);
}
void ast_module_unref (struct ast_module *)
Definition at line 1171 of file loader.c.
References ast_atomic_fetchadd_int(), ast_update_use_count(), and ast_module::usecount.
Referenced by agi_handle_command(), alsa_hangup(), ast_agi_unregister(), ast_bridge_check(), ast_smdi_interface_destroy(), ast_timer_close(), dahdi_destroy_channel_bynum(), dahdi_hangup(), destroy(), destroy_bridge(), filestream_destructor(), gtalk_hangup(), handle_cli_file_convert(), handle_orig(), iax2_predestroy(), local_ast_moh_cleanup(), mgcp_hangup(), oh323_hangup(), oss_hangup(), phone_check_exception(), phone_hangup(), sip_hangup(), skinny_hangup(), smart_bridge_operation(), and usbradio_hangup().
{
   ast_atomic_fetchadd_int(&mod->usecount, -1);
   ast_update_use_count();
}
void ast_module_unregister (const struct ast_module_info *)
Definition at line 171 of file loader.c.
References ast_free, AST_LIST_HEAD_DESTROY, AST_LIST_LOCK, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_LIST_UNLOCK, ast_module::info, and ast_module::users.
{
   struct ast_module *mod = NULL;
   /* it is assumed that the users list in the module structure
      will already be empty, or we cannot have gotten to this
      point
   */
   AST_LIST_LOCK(&module_list);
   AST_LIST_TRAVERSE_SAFE_BEGIN(&module_list, mod, entry) {
      if (mod->info == info) {
         AST_LIST_REMOVE_CURRENT(entry);
         break;
      }
   }
   AST_LIST_TRAVERSE_SAFE_END;
   AST_LIST_UNLOCK(&module_list);
   if (mod) {
      AST_LIST_HEAD_DESTROY(&mod->users);
      ast_free(mod);
   }
}
int ast_register_application2 (const char * app, int(*)(struct ast_channel *, void *) execute, const char * synopsis, const char * description, void * mod)
Register an application.
Parameters:
app Short name of the application
execute a function callback to execute the application. It should return non-zero if the channel needs to be hung up.
synopsis a short description (one line synopsis) of the application
description long description with all of the details about the use of the application
mod module this application belongs to
This registers an application with Asterisk's internal application list.
Note:
The individual applications themselves are responsible for registering and unregistering and unregistering their own CLI commands.
Return values:
0 success
-1 failure.
Definition at line 5062 of file pbx.c.
References ast_app::arguments, ast_calloc, ast_free, ast_log(), AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, AST_STATIC_DOC, ast_string_field_init, ast_string_field_set, ast_strlen_zero(), ast_verb, AST_XML_DOC, ast_xmldoc_build_arguments(), ast_xmldoc_build_description(), ast_xmldoc_build_seealso(), ast_xmldoc_build_synopsis(), ast_xmldoc_build_syntax(), COLOR_BRCYAN, ast_app::docsrc, ast_app::execute, LOG_WARNING, ast_app::module, ast_app::name, ast_app::seealso, ast_app::syntax, and term_color().
Referenced by ast_features_init(), and load_pbx().
{
   struct ast_app *tmp, *cur = NULL;
   char tmps[80];
   int length, res;
#ifdef AST_XML_DOCS
   char *tmpxml;
#endif
   AST_RWLIST_WRLOCK(&apps);
   AST_RWLIST_TRAVERSE(&apps, tmp, list) {
      if (!(res = strcasecmp(app, tmp->name))) {
         ast_log(LOG_WARNING, "Already have an application '%s'\n", app);
         AST_RWLIST_UNLOCK(&apps);
         return -1;
      } else if (res < 0)
         break;
   }
   length = sizeof(*tmp) + strlen(app) + 1;
   if (!(tmp = ast_calloc(1, length))) {
      AST_RWLIST_UNLOCK(&apps);
      return -1;
   }
   if (ast_string_field_init(tmp, 128)) {
      AST_RWLIST_UNLOCK(&apps);
      ast_free(tmp);
      return -1;
   }
#ifdef AST_XML_DOCS
   /* Try to lookup the docs in our XML documentation database */
   if (ast_strlen_zero(synopsis) && ast_strlen_zero(description)) {
      /* load synopsis */
      tmpxml = ast_xmldoc_build_synopsis("application", app);
      ast_string_field_set(tmp, synopsis, tmpxml);
      ast_free(tmpxml);
      /* load description */
      tmpxml = ast_xmldoc_build_description("application", app);
      ast_string_field_set(tmp, description, tmpxml);
      ast_free(tmpxml);
      /* load syntax */
      tmpxml = ast_xmldoc_build_syntax("application", app);
      ast_string_field_set(tmp, syntax, tmpxml);
      ast_free(tmpxml);
      /* load arguments */
      tmpxml = ast_xmldoc_build_arguments("application", app);
      ast_string_field_set(tmp, arguments, tmpxml);
      ast_free(tmpxml);
      /* load seealso */
      tmpxml = ast_xmldoc_build_seealso("application", app);
      ast_string_field_set(tmp, seealso, tmpxml);
      ast_free(tmpxml);
      tmp->docsrc = AST_XML_DOC;
   } else {
#endif
      ast_string_field_set(tmp, synopsis, synopsis);
      ast_string_field_set(tmp, description, description);
      tmp->docsrc = AST_STATIC_DOC;
#ifdef AST_XML_DOCS
   }
#endif
   strcpy(tmp->name, app);
   tmp->execute = execute;
   tmp->module = mod;
   /* Store in alphabetical order */
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, cur, list) {
      if (strcasecmp(tmp->name, cur->name) < 0) {
         AST_RWLIST_INSERT_BEFORE_CURRENT(tmp, list);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   if (!cur)
      AST_RWLIST_INSERT_TAIL(&apps, tmp, list);
   ast_verb(2, "Registered application '%s'\n", term_color(tmps, tmp->name, COLOR_BRCYAN, 0, sizeof(tmps)));
   AST_RWLIST_UNLOCK(&apps);
   return 0;
}
int ast_unload_resource (const char * resource_name, enum ast_module_unload_mode)
Unload a module.
Parameters:
resource_name The name of the module to unload.
ast_module_unload_mode The force flag. This should be set using one of the AST_FORCE flags.
This function unloads a module. It will only unload modules that are not in use (usecount not zero), unless AST_FORCE_FIRM or AST_FORCE_HARD is specified. Setting AST_FORCE_FIRM or AST_FORCE_HARD will unload the module regardless of consequences (NOT RECOMMENDED).
Return values:
0 on success.
-1 on error.
Definition at line 482 of file loader.c.
References __ast_module_user_hangup_all(), AST_FORCE_FIRM, AST_LIST_LOCK, AST_LIST_UNLOCK, ast_log(), ast_update_use_count(), ast_module::declined, find_resource(), ast_module::flags, ast_module::info, ast_module::lib, LOG_WARNING, ast_module_info::restore_globals, ast_module::running, ast_module_info::unload, unload_dynamic_module(), and ast_module::usecount.
Referenced by exit_now(), handle_unload(), manager_moduleload(), reload(), and remove_module().
{
   struct ast_module *mod;
   int res = -1;
   int error = 0;
   AST_LIST_LOCK(&module_list);
   if (!(mod = find_resource(resource_name, 0))) {
      AST_LIST_UNLOCK(&module_list);
      ast_log(LOG_WARNING, "Unload failed, '%s' could not be found\n", resource_name);
      return 0;
   }
   if (!(mod->flags.running || mod->flags.declined))
      error = 1;
   if (!error && (mod->usecount > 0)) {
      if (force)
         ast_log(LOG_WARNING, "Warning:  Forcing removal of module '%s' with use count %d\n",
            resource_name, mod->usecount);
      else {
         ast_log(LOG_WARNING, "Soft unload failed, '%s' has use count %d\n", resource_name,
            mod->usecount);
         error = 1;
      }
   }
   if (!error) {
      __ast_module_user_hangup_all(mod);
      res = mod->info->unload();
      if (res) {
         ast_log(LOG_WARNING, "Firm unload failed for %s\n", resource_name);
         if (force <= AST_FORCE_FIRM)
            error = 1;
         else
            ast_log(LOG_WARNING, "** Dangerous **: Unloading resource anyway, at user request\n");
      }
   }
   if (!error)
      mod->flags.running = mod->flags.declined = 0;
   AST_LIST_UNLOCK(&module_list);
   if (!error && !mod->lib && mod->info && mod->info->restore_globals)
      mod->info->restore_globals();
#ifdef LOADABLE_MODULES
   if (!error)
      unload_dynamic_module(mod);
#endif
   if (!error)
      ast_update_use_count();
   return res;
}
int ast_unregister_application (const char * app)
Unregister an application.
Parameters:
app name of the application (does not have to be the same string as the one that was registered)
This unregisters an application from Asterisk's internal application list.
Return values:
0 success
-1 failure
Definition at line 6403 of file pbx.c.
References ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_string_field_free_memory, ast_verb, ast_app::name, and unreference_cached_app().
Referenced by __unload_module(), load_module(), and unload_module().
{
   struct ast_app *tmp;
   AST_RWLIST_WRLOCK(&apps);
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, tmp, list) {
      if (!strcasecmp(app, tmp->name)) {
         unreference_cached_app(tmp);
         AST_RWLIST_REMOVE_CURRENT(list);
         ast_verb(2, "Unregistered application '%s'\n", tmp->name);
         ast_string_field_free_memory(tmp);
         ast_free(tmp);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   AST_RWLIST_UNLOCK(&apps);
   return tmp ? 0 : -1;
}
int ast_update_module_list (int(*)(const char *module, const char *description, int usecnt, const char *like) modentry, const char * like)
Ask for a list of modules, descriptions, and use counts.
Parameters:
modentry A callback to an updater function.
like For each of the modules loaded, modentry will be executed with the resource, description, and usecount values of each particular module.
Returns:
the number of modules loaded
Definition at line 1097 of file loader.c.
References AST_LIST_TRAVERSE, AST_LIST_TRYLOCK, AST_LIST_UNLOCK, ast_module_info::description, ast_module::info, ast_module::resource, and ast_module::usecount.
Referenced by ast_var_Modules(), handle_modlist(), and mod_update().
{
   struct ast_module *cur;
   int unlock = -1;
   int total_mod_loaded = 0;
   if (AST_LIST_TRYLOCK(&module_list))
      unlock = 0;
   AST_LIST_TRAVERSE(&module_list, cur, entry) {
      total_mod_loaded += modentry(cur->resource, cur->info->description, cur->usecount, like);
   }
   if (unlock)
      AST_LIST_UNLOCK(&module_list);
   return total_mod_loaded;
}
void ast_update_use_count (void)
Notify when usecount has been changed.
This function calulates use counts and notifies anyone trying to keep track of them. It should be called whenever your module's usecount changes.
Note:
The ast_module_user_* functions take care of calling this function for you.
Definition at line 1085 of file loader.c.
References AST_LIST_LOCK, AST_LIST_TRAVERSE, AST_LIST_UNLOCK, and loadupdate::updater.
Referenced by __ast_module_user_add(), __ast_module_user_hangup_all(), __ast_module_user_remove(), ast_module_ref(), ast_module_unref(), ast_unload_resource(), exit_now(), handle_request_do(), load_module(), oh323_request(), scheduler_process_request_queue(), sip_request_call(), start_resource(), and unistim_new().
{
   /* Notify any module monitors that the use count for a
      resource has changed */
   struct loadupdate *m;
   AST_LIST_LOCK(&updaters);
   AST_LIST_TRAVERSE(&updaters, m, entry)
      m->updater();
   AST_LIST_UNLOCK(&updaters);
}
Variable Documentation
struct ast_module_info* ast_module_info [static]
Definition at line 283 of file module.h.