Wed May 5 15:22:24 2010
Asterisk developer's documentation
netsock.c File Reference
Network socket handling.
#include "asterisk.h"
#include <ifaddrs.h>
#include "asterisk/netsock.h"
#include "asterisk/utils.h"
#include "asterisk/astobj.h"
Data Structures
struct ast_netsock
struct ast_netsock_list
Functions
int ast_eid_cmp (const struct ast_eid *eid1, const struct ast_eid *eid2)
Compare two EIDs.
char * ast_eid_to_str (char *s, int maxlen, struct ast_eid *eid)
struct ast_netsock * ast_netsock_bind (struct ast_netsock_list *list, struct io_context *ioc, const char *bindinfo, int defaultport, int tos, int cos, ast_io_cb callback, void *data)
struct ast_netsock * ast_netsock_bindaddr (struct ast_netsock_list *list, struct io_context *ioc, struct sockaddr_in *bindaddr, int tos, int cos, ast_io_cb callback, void *data)
struct sockaddr_in * ast_netsock_boundaddr (const struct ast_netsock *ns)
void * ast_netsock_data (const struct ast_netsock *ns)
static void ast_netsock_destroy (struct ast_netsock *netsock)
struct ast_netsock * ast_netsock_find (struct ast_netsock_list *list, struct sockaddr_in *sa)
int ast_netsock_init (struct ast_netsock_list *list)
struct ast_netsock_list * ast_netsock_list_alloc (void)
int ast_netsock_release (struct ast_netsock_list *list)
int ast_netsock_set_qos (int netsocket, int tos, int cos, const char *desc)
int ast_netsock_sockfd (const struct ast_netsock *ns)
void ast_netsock_unref (struct ast_netsock *ns)
void ast_set_default_eid (struct ast_eid *eid)
Fill in an ast_eid with the default eid of this machine.
int ast_str_to_eid (struct ast_eid *eid, const char *s)
Convert a string into an EID.
Detailed Description
Network socket handling.
Author:
Kevin P. Fleming <kpfleming@digium.com>
Mark Spencer <markster@digium.com>
Definition in file netsock.c.
Function Documentation
int ast_eid_cmp (const struct ast_eid * eid1, const struct ast_eid * eid2)
Compare two EIDs.
Returns:
0 if the two are the same, non-zero otherwise
Since:
1.6.1
Definition at line 294 of file netsock.c.
Referenced by ast_event_cb(), build_peer(), build_transactions(), destroy_trans(), dundi_answer_entity(), dundi_answer_query(), dundi_ie_append_eid_appropriately(), dundi_lookup_internal(), dundi_prop_precache(), dundi_query_thread(), evt_event_deliver_cb(), find_peer(), handle_command_response(), optimize_transactions(), and register_request().
{
   return memcmp(eid1, eid2, sizeof(*eid1));
}
char* ast_eid_to_str (char * s, int maxlen, struct ast_eid * eid)
/brief Convert an EID to a string
Since:
1.6.1
Definition at line 218 of file netsock.c.
References ast_eid::eid.
Referenced by append_transaction(), ast_set_default_eid(), build_peer(), build_transactions(), cache_lookup(), cache_lookup_internal(), check_key(), complete_peer_helper(), destroy_trans(), do_autokill(), do_register(), do_register_expire(), dump_answer(), dump_eid(), dundi_answer_entity(), dundi_lookup_internal(), dundi_lookup_local(), dundi_lookup_thread(), dundi_precache_thread(), dundi_prop_precache(), dundi_query_thread(), dundi_send(), dundi_show_entityid(), dundi_show_peer(), dundi_show_peers(), dundi_show_requests(), handle_command_response(), handle_show_settings(), pbx_retrieve_variable(), populate_addr(), register_request(), and update_key().
{
   int x;
   char *os = s;
   if (maxlen < 18) {
      if (s && (maxlen > 0))
         *s = '\0';
   } else {
      for (x = 0; x < 5; x++) {
         sprintf(s, "%02x:", eid->eid[x]);
         s += 3;
      }
      sprintf(s, "%02x", eid->eid[5]);
   }
   return os;
}
struct ast_netsock* ast_netsock_bind (struct ast_netsock_list * list, struct io_context * ioc, const char * bindinfo, int defaultport, int tos, int cos, ast_io_cb callback, void * data) [read]
Definition at line 174 of file netsock.c.
References ast_netsock_bindaddr(), ast_strdupa, and strsep().
Referenced by peer_set_srcaddr(), and set_config().
{
   struct sockaddr_in sin;
   char *tmp;
   char *host;
   char *port;
   int portno;
   memset(&sin, 0, sizeof(sin));
   sin.sin_family = AF_INET;
   sin.sin_port = htons(defaultport);
   tmp = ast_strdupa(bindinfo);
   host = strsep(&tmp, ":");
   port = tmp;
   if (port && ((portno = atoi(port)) > 0))
      sin.sin_port = htons(portno);
   inet_aton(host, &sin.sin_addr);
   return ast_netsock_bindaddr(list, ioc, &sin, tos, cos, callback, data);
}
struct ast_netsock* ast_netsock_bindaddr (struct ast_netsock_list * list, struct io_context * ioc, struct sockaddr_in * bindaddr, int tos, int cos, ast_io_cb callback, void * data) [read]
Definition at line 104 of file netsock.c.
References ast_calloc, ast_enable_packet_fragmentation(), ast_free, ast_inet_ntoa(), ast_io_add(), AST_IO_IN, ast_log(), ast_netsock_set_qos(), ASTOBJ_CONTAINER_LINK, ASTOBJ_INIT, ast_netsock::bindaddr, ast_netsock::data, errno, ast_netsock::ioc, ast_netsock::ioref, LOG_ERROR, LOG_WARNING, netsocket, and ast_netsock::sockfd.
Referenced by ast_netsock_bind().
{
   int netsocket = -1;
   int *ioref;
   struct ast_netsock *ns;
   const int reuseFlag = 1;
   /* Make a UDP socket */
   netsocket = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP);
   if (netsocket < 0) {
      ast_log(LOG_ERROR, "Unable to create network socket: %s\n", strerror(errno));
      return NULL;
   }
   if (setsockopt(netsocket, SOL_SOCKET, SO_REUSEADDR, (char *)&reuseFlag, sizeof reuseFlag) < 0) {
         ast_log(LOG_WARNING, "Error setting SO_REUSEADDR on sockfd '%d'\n", netsocket);
   }
   if (bind(netsocket,(struct sockaddr *)bindaddr, sizeof(struct sockaddr_in))) {
      ast_log(LOG_ERROR, "Unable to bind to %s port %d: %s\n", ast_inet_ntoa(bindaddr->sin_addr), ntohs(bindaddr->sin_port), strerror(errno));
      close(netsocket);
      return NULL;
   }
   ast_netsock_set_qos(netsocket, tos, cos, "IAX2");
   ast_enable_packet_fragmentation(netsocket);
   if (!(ns = ast_calloc(1, sizeof(*ns)))) {
      close(netsocket);
      return NULL;
   }
   /* Establish I/O callback for socket read */
   if (!(ioref = ast_io_add(ioc, netsocket, callback, AST_IO_IN, ns))) {
      close(netsocket);
      ast_free(ns);
      return NULL;
   }
   ASTOBJ_INIT(ns);
   ns->ioref = ioref;
   ns->ioc = ioc;
   ns->sockfd = netsocket;
   ns->data = data;
   memcpy(&ns->bindaddr, bindaddr, sizeof(ns->bindaddr));
   ASTOBJ_CONTAINER_LINK(list, ns);
   return ns;
}
struct sockaddr_in* ast_netsock_boundaddr (const struct ast_netsock * ns) [read]
Definition at line 203 of file netsock.c.
References ast_netsock::bindaddr.
{
   return &(ns->bindaddr);
}
void* ast_netsock_data (const struct ast_netsock * ns)
Definition at line 208 of file netsock.c.
References ast_netsock::data.
{
   return ns->data;
}
static void ast_netsock_destroy (struct ast_netsock * netsock) [static]
Definition at line 60 of file netsock.c.
References ast_free, ast_io_remove(), ast_netsock::ioc, ast_netsock::ioref, and ast_netsock::sockfd.
Referenced by ast_netsock_release(), and ast_netsock_unref().
{
   ast_io_remove(netsock->ioc, netsock->ioref);
   close(netsock->sockfd);
   ast_free(netsock);
}
struct ast_netsock* ast_netsock_find (struct ast_netsock_list * list, struct sockaddr_in * sa) [read]
Definition at line 89 of file netsock.c.
References ASTOBJ_CONTAINER_TRAVERSE, ASTOBJ_RDLOCK, ASTOBJ_UNLOCK, and inaddrcmp().
Referenced by peer_set_srcaddr().
{
   struct ast_netsock *sock = NULL;
   ASTOBJ_CONTAINER_TRAVERSE(list, !sock, {
      ASTOBJ_RDLOCK(iterator);
      if (!inaddrcmp(&iterator->bindaddr, sa))
         sock = iterator;
      ASTOBJ_UNLOCK(iterator);
   });
   return sock;
}
int ast_netsock_init (struct ast_netsock_list * list)
Definition at line 72 of file netsock.c.
References ASTOBJ_CONTAINER_INIT.
Referenced by load_module(), and set_config().
{
   memset(list, 0, sizeof(*list));
   ASTOBJ_CONTAINER_INIT(list);
   return 0;
}
struct ast_netsock_list* ast_netsock_list_alloc (void) [read]
Definition at line 67 of file netsock.c.
References ast_calloc.
Referenced by load_module(), and set_config().
{
   return ast_calloc(1, sizeof(struct ast_netsock_list));
}
int ast_netsock_release (struct ast_netsock_list * list)
Definition at line 80 of file netsock.c.
References ast_free, ast_netsock_destroy(), ASTOBJ_CONTAINER_DESTROY, and ASTOBJ_CONTAINER_DESTROYALL.
Referenced by __unload_module(), and set_config().
{
   ASTOBJ_CONTAINER_DESTROYALL(list, ast_netsock_destroy);
   ASTOBJ_CONTAINER_DESTROY(list);
   ast_free(list);
   return 0;
}
int ast_netsock_set_qos (int netsocket, int tos, int cos, const char * desc)
Definition at line 154 of file netsock.c.
References ast_log(), ast_verb, and LOG_WARNING.
Referenced by ast_netsock_bindaddr(), ast_rtp_setqos(), ast_udptl_setqos(), config_load(), load_module(), and reload_config().
{
   int res;
   if ((res = setsockopt(netsocket, IPPROTO_IP, IP_TOS, &tos, sizeof(tos))))
      ast_log(LOG_WARNING, "Unable to set %s TOS to %d, may be you have no root privileges\n", desc, tos);
   else if (tos)
      ast_verb(2, "Using %s TOS bits %d\n", desc, tos);
#if defined(linux)
   if (setsockopt(netsocket, SOL_SOCKET, SO_PRIORITY, &cos, sizeof(cos)))
      ast_log(LOG_WARNING, "Unable to set %s CoS to %d\n", desc, cos);
   else if (cos)
      ast_verb(2, "Using %s CoS mark %d\n", desc, cos);
#endif
   return res;
}
int ast_netsock_sockfd (const struct ast_netsock * ns)
Definition at line 198 of file netsock.c.
Referenced by peer_set_srcaddr(), and set_config().
{
   return ns ? ns-> sockfd : -1;
}
void ast_netsock_unref (struct ast_netsock * ns)
Definition at line 213 of file netsock.c.
References ast_netsock_destroy(), and ASTOBJ_UNREF.
Referenced by peer_set_srcaddr(), and set_config().
{
   ASTOBJ_UNREF(ns, ast_netsock_destroy);
}
void ast_set_default_eid (struct ast_eid * eid)
Fill in an ast_eid with the default eid of this machine.
Since:
1.6.1
Definition at line 235 of file netsock.c.
References ast_debug, ast_eid_to_str(), ast_eid::eid, and s.
Referenced by ast_readconfig().
{
#if defined(SIOCGIFHWADDR)
   int s, x = 0;
   char eid_str[20];
   struct ifreq ifr;
   s = socket(AF_INET, SOCK_STREAM, 0);
   if (s < 0)
      return;
   for (x = 0; x < 10; x++) {
      memset(&ifr, 0, sizeof(ifr));
      snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "eth%d", x);
      if (ioctl(s, SIOCGIFHWADDR, &ifr))
         continue;
      memcpy(eid, ((unsigned char *)&ifr.ifr_hwaddr) + 2, sizeof(*eid));
      ast_debug(1, "Seeding global EID '%s' from '%s' using 'siocgifhwaddr'\n", ast_eid_to_str(eid_str, sizeof(eid_str), eid), ifr.ifr_name);
      close(s);
      return;
   }
   close(s);
#else
#if defined(ifa_broadaddr) && !defined(SOLARIS)
   char eid_str[20];
   struct ifaddrs *ifap;
   if (getifaddrs(&ifap) == 0) {
      struct ifaddrs *p;
      for (p = ifap; p; p = p->ifa_next) {
         if ((p->ifa_addr->sa_family == AF_LINK) && !(p->ifa_flags & IFF_LOOPBACK) && (p->ifa_flags & IFF_RUNNING)) {
            struct sockaddr_dl* sdp = (struct sockaddr_dl*) p->ifa_addr;
            memcpy(&(eid->eid), sdp->sdl_data + sdp->sdl_nlen, 6);
            ast_debug(1, "Seeding global EID '%s' from '%s' using 'getifaddrs'\n", ast_eid_to_str(eid_str, sizeof(eid_str), eid), p->ifa_name);
            freeifaddrs(ifap);
            return;
         }
      }
      freeifaddrs(ifap);
   }
#endif
#endif
   ast_debug(1, "No ethernet interface found for seeding global EID. You will have to set it manually.\n");
}
int ast_str_to_eid (struct ast_eid * eid, const char * s)
Convert a string into an EID.
This function expects an EID in the format: 00:11:22:33:44:55
Returns:
0 success, non-zero failure
Since:
1.6.1
Definition at line 279 of file netsock.c.
References ast_eid::eid.
Referenced by ast_readconfig(), build_peer(), dundi_do_query(), and set_config().
{
   unsigned int eid_int[6];
   int x;
   if (sscanf(s, "%2x:%2x:%2x:%2x:%2x:%2x", &eid_int[0], &eid_int[1], &eid_int[2],
       &eid_int[3], &eid_int[4], &eid_int[5]) != 6)
         return -1;
   for (x = 0; x < 6; x++)
      eid->eid[x] = eid_int[x];
   return 0;
}