Wed May 5 15:22:24 2010
Asterisk developer's documentation
pbx.c File Reference
Core PBX routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/paths.h"
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include "asterisk/lock.h"
#include "asterisk/cli.h"
#include "asterisk/pbx.h"
#include "asterisk/channel.h"
#include "asterisk/file.h"
#include "asterisk/callerid.h"
#include "asterisk/cdr.h"
#include "asterisk/config.h"
#include "asterisk/term.h"
#include "asterisk/manager.h"
#include "asterisk/ast_expr.h"
#include "asterisk/linkedlists.h"
#include "asterisk/say.h"
#include "asterisk/utils.h"
#include "asterisk/causes.h"
#include "asterisk/musiconhold.h"
#include "asterisk/app.h"
#include "asterisk/devicestate.h"
#include "asterisk/event.h"
#include "asterisk/hashtab.h"
#include "asterisk/module.h"
#include "asterisk/indications.h"
#include "asterisk/taskprocessor.h"
#include "asterisk/xmldoc.h"
Data Structures
struct acf_root
struct app_tmp
struct apps
struct ast_app
ast_app: A registered application
struct ast_context
ast_context: An extension context
struct ast_exten
ast_exten: An extension The dialplan is saved as a linked list with each context having it's own linked list of extensions - one item per priority.
struct ast_hint
Structure for dial plan hints.
struct ast_ignorepat
ast_ignorepat: Ignore patterns in dial plan
struct ast_include
ast_include: include= support in extensions.conf
struct ast_state_cb
ast_state_cb: An extension state notify register item
struct ast_sw
ast_sw: Switch statement in extensions.conf
struct async_stat
struct cfextension_states
struct dialplan_counters
Counters for the show dialplan manager command.
struct fake_context
struct hints
struct match_char
match_char: forms a syntax tree for quick matching of extension patterns
struct pbx_builtin
Declaration of builtin applications.
struct pbx_exception
struct scoreboard
struct statecbs
struct statechange
struct store_hint
struct store_hints
struct switches
Defines
#define AST_PBX_MAX_STACK 128
#define BACKGROUND_MATCHEXTEN (1 << 2)
#define BACKGROUND_NOANSWER (1 << 1)
#define BACKGROUND_PLAYBACK (1 << 3)
#define BACKGROUND_SKIP (1 << 0)
#define EXT_DATA_SIZE 8192
#define NEW_MATCHER_CHK_MATCH
#define NEW_MATCHER_RECURSE
#define SAY_STUBS
#define STATUS_NO_CONTEXT 1
#define STATUS_NO_EXTENSION 2
#define STATUS_NO_LABEL 4
#define STATUS_NO_PRIORITY 3
#define STATUS_SUCCESS 5
#define SWITCH_DATA_LENGTH 256
#define VAR_BUF_SIZE 4096
#define VAR_HARDTRAN 3
#define VAR_NORMAL 1
#define VAR_SOFTTRAN 2
#define WAITEXTEN_DIALTONE (1 << 1)
#define WAITEXTEN_MOH (1 << 0)
Functions
void __ast_context_destroy (struct ast_context *list, struct ast_hashtab *contexttab, struct ast_context *con, const char *registrar)
int __ast_custom_function_register (struct ast_custom_function *acf, struct ast_module *mod)
Register a custom function.
static int __ast_goto_if_exists (struct ast_channel *chan, const char *context, const char *exten, int priority, int async)
static void __ast_internal_context_destroy (struct ast_context *con)
static enum ast_pbx_result __ast_pbx_run (struct ast_channel *c, struct ast_pbx_args *args)
static void __init_extensionstate_buf (void)
static void __init_switch_data (void)
static int _extension_match_core (const char *pattern, const char *data, enum ext_match_t mode)
static int acf_exception_read (struct ast_channel *chan, const char *name, char *data, char *buf, size_t buflen)
static int acf_retrieve_docs (struct ast_custom_function *acf)
static struct match_char * add_exten_to_pattern_tree (struct ast_context *con, struct ast_exten *e1, int findonly)
static struct match_char * add_pattern_node (struct ast_context *con, struct match_char *current, char *pattern, int is_pattern, int already, int specificity, struct match_char **parent)
static int add_pri (struct ast_context *con, struct ast_exten *tmp, struct ast_exten *el, struct ast_exten *e, int replace)
add the extension in the priority chain.
static int add_pri_lockopt (struct ast_context *con, struct ast_exten *tmp, struct ast_exten *el, struct ast_exten *e, int replace, int lockhints)
add the extension in the priority chain.
static struct match_char * already_in_tree (struct match_char *current, char *pat)
int ast_active_calls (void)
Retrieve the number of active calls.
int ast_add_extension (const char *context, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar)
Add and extension to an extension context.
int ast_add_extension2 (struct ast_context *con, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar)
Main interface to add extensions to the list for out context.
static int ast_add_extension2_lockopt (struct ast_context *con, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar, int lockconts, int lockhints)
Does all the work of ast_add_extension2, but adds two args, to determine if context and hint locking should be done. In merge_and_delete, we need to do this without locking, as the locks are already held.
static int ast_add_extension_nolock (const char *context, int replace, const char *extension, int priority, const char *label, const char *callerid, const char *application, void *data, void(*datad)(void *), const char *registrar)
static int ast_add_hint (struct ast_exten *e)
Add hint to hint list, check initial extension state.
static int ast_add_hint_nolock (struct ast_exten *e)
Add hint to hint list, check initial extension state; the hints had better be WRLOCKED already!
int ast_async_goto (struct ast_channel *chan, const char *context, const char *exten, int priority)
Set the channel to next execute the specified dialplan location.
int ast_async_goto_by_name (const char *channame, const char *context, const char *exten, int priority)
Set the channel to next execute the specified dialplan location.
int ast_async_goto_if_exists (struct ast_channel *chan, const char *context, const char *exten, int priority)
int ast_async_parseable_goto (struct ast_channel *chan, const char *goto_string)
int ast_build_timing (struct ast_timing *i, const char *info_in)
Construct a timing bitmap, for use in time-based conditionals.
int ast_canmatch_extension (struct ast_channel *c, const char *context, const char *exten, int priority, const char *callerid)
Looks for a valid matching extension.
static int ast_change_hint (struct ast_exten *oe, struct ast_exten *ne)
Change hint for an extension.
int ast_check_timing (const struct ast_timing *i)
Evaluate a pre-constructed bitmap as to whether the current time falls within the range specified.
int ast_context_add_ignorepat (const char *context, const char *value, const char *registrar)
Add an ignorepat.
int ast_context_add_ignorepat2 (struct ast_context *con, const char *value, const char *registrar)
int ast_context_add_include (const char *context, const char *include, const char *registrar)
Add a context include.
int ast_context_add_include2 (struct ast_context *con, const char *value, const char *registrar)
Add a context include.
int ast_context_add_switch (const char *context, const char *sw, const char *data, int eval, const char *registrar)
Add a switch.
int ast_context_add_switch2 (struct ast_context *con, const char *value, const char *data, int eval, const char *registrar)
Adds a switch (first param is a ast_context).
void ast_context_destroy (struct ast_context *con, const char *registrar)
Destroy a context (matches the specified context (or ANY context if NULL).
struct ast_context * ast_context_find (const char *name)
Find a context.
struct ast_context * ast_context_find_or_create (struct ast_context **extcontexts, struct ast_hashtab *exttable, const char *name, const char *registrar)
Register a new context or find an existing one.
int ast_context_lockmacro (const char *context)
locks the macrolock in the given given context
int ast_context_remove_extension (const char *context, const char *extension, int priority, const char *registrar)
Simply remove extension from context.
int ast_context_remove_extension2 (struct ast_context *con, const char *extension, int priority, const char *registrar, int already_locked)
This functionc locks given context, search for the right extension and fires out all peer in this extensions with given priority. If priority is set to 0, all peers are removed. After that, unlock context and return.
int ast_context_remove_extension_callerid (const char *context, const char *extension, int priority, const char *callerid, int matchcallerid, const char *registrar)
int ast_context_remove_extension_callerid2 (struct ast_context *con, const char *extension, int priority, const char *callerid, int matchcallerid, const char *registrar, int already_locked)
int ast_context_remove_ignorepat (const char *context, const char *ignorepat, const char *registrar)
int ast_context_remove_ignorepat2 (struct ast_context *con, const char *ignorepat, const char *registrar)
int ast_context_remove_include (const char *context, const char *include, const char *registrar)
Remove included contexts. This function locks contexts list by &conlist, search for the right context structure, leave context list locked and call ast_context_remove_include2 which removes include, unlock contexts list and return ...
int ast_context_remove_include2 (struct ast_context *con, const char *include, const char *registrar)
Locks context, remove included contexts, unlocks context. When we call this function, &conlock lock must be locked, because when we giving *con argument, some process can remove/change this context and after that there can be segfault.
int ast_context_remove_switch (const char *context, const char *sw, const char *data, const char *registrar)
Remove a switch.
int ast_context_remove_switch2 (struct ast_context *con, const char *sw, const char *data, const char *registrar)
This function locks given context, removes switch, unlock context and return.
int ast_context_unlockmacro (const char *context)
Unlocks the macrolock in the given context.
int ast_context_verify_includes (struct ast_context *con)
Verifies includes in an ast_contect structure.
struct ast_custom_function * ast_custom_function_find (const char *name)
int ast_custom_function_unregister (struct ast_custom_function *acf)
Unregister a custom function.
int ast_destroy_timing (struct ast_timing *i)
Deallocates memory structures associated with a timing bitmap.
enum ast_extension_states ast_devstate_to_extenstate (enum ast_device_state devstate)
Map devstate to an extension state.
int ast_exists_extension (struct ast_channel *c, const char *context, const char *exten, int priority, const char *callerid)
Determine whether an extension exists.
int ast_explicit_goto (struct ast_channel *chan, const char *context, const char *exten, int priority)
int ast_extension_close (const char *pattern, const char *data, int needmore)
int ast_extension_cmp (const char *a, const char *b)
Determine if one extension should match before another.
int ast_extension_match (const char *pattern, const char *data)
Determine if a given extension matches a given pattern (in NXX format).
int ast_extension_state (struct ast_channel *c, const char *context, const char *exten)
Check extension state for an extension by using hint.
static int ast_extension_state2 (struct ast_exten *e)
Check state of extension by using hints.
const char * ast_extension_state2str (int extension_state)
Return extension_state as string.
int ast_extension_state_add (const char *context, const char *exten, ast_state_cb_type callback, void *data)
Add watcher for extension states.
int ast_extension_state_del (int id, ast_state_cb_type callback)
Remove a watcher from the callback list.
int ast_findlabel_extension (struct ast_channel *c, const char *context, const char *exten, const char *label, const char *callerid)
Find the priority of an extension that has the specified label.
int ast_findlabel_extension2 (struct ast_channel *c, struct ast_context *con, const char *exten, const char *label, const char *callerid)
Find the priority of an extension that has the specified label.
int ast_func_read (struct ast_channel *chan, const char *function, char *workspace, size_t len)
executes a read operation on a function
int ast_func_write (struct ast_channel *chan, const char *function, const char *value)
executes a write operation on a function
const char * ast_get_context_name (struct ast_context *con)
const char * ast_get_context_registrar (struct ast_context *c)
const char * ast_get_extension_app (struct ast_exten *e)
void * ast_get_extension_app_data (struct ast_exten *e)
const char * ast_get_extension_cidmatch (struct ast_exten *e)
struct ast_context * ast_get_extension_context (struct ast_exten *exten)
const char * ast_get_extension_label (struct ast_exten *exten)
int ast_get_extension_matchcid (struct ast_exten *e)
const char * ast_get_extension_name (struct ast_exten *exten)
int ast_get_extension_priority (struct ast_exten *exten)
const char * ast_get_extension_registrar (struct ast_exten *e)
int ast_get_hint (char *hint, int hintsize, char *name, int namesize, struct ast_channel *c, const char *context, const char *exten)
Get hint for channel.
const char * ast_get_ignorepat_name (struct ast_ignorepat *ip)
const char * ast_get_ignorepat_registrar (struct ast_ignorepat *ip)
const char * ast_get_include_name (struct ast_include *inc)
const char * ast_get_include_registrar (struct ast_include *i)
const char * ast_get_switch_data (struct ast_sw *sw)
int ast_get_switch_eval (struct ast_sw *sw)
const char * ast_get_switch_name (struct ast_sw *sw)
const char * ast_get_switch_registrar (struct ast_sw *sw)
int ast_goto_if_exists (struct ast_channel *chan, const char *context, const char *exten, int priority)
int ast_hashtab_compare_contexts (const void *ah_a, const void *ah_b)
hashtable functions for contexts
unsigned int ast_hashtab_hash_contexts (const void *obj)
static struct ast_exten * ast_hint_extension (struct ast_channel *c, const char *context, const char *exten)
static struct ast_exten * ast_hint_extension_nolock (struct ast_channel *c, const char *context, const char *exten)
Find hint for given extension in context.
int ast_ignore_pattern (const char *context, const char *pattern)
Checks to see if a number should be ignored.
int ast_matchmore_extension (struct ast_channel *c, const char *context, const char *exten, int priority, const char *callerid)
Looks to see if adding anything to this extension might match something. (exists ^ canmatch).
void ast_merge_contexts_and_delete (struct ast_context **extcontexts, struct ast_hashtab *exttable, const char *registrar)
Merge the temporary contexts into a global contexts list and delete from the global list the ones that are being added.
int ast_parseable_goto (struct ast_channel *chan, const char *goto_string)
int ast_pbx_outgoing_app (const char *type, int format, void *data, int timeout, const char *app, const char *appdata, int *reason, int synchronous, const char *cid_num, const char *cid_name, struct ast_variable *vars, const char *account, struct ast_channel **locked_channel)
static int ast_pbx_outgoing_cdr_failed (void)
Function to post an empty cdr after a spool call fails.
int ast_pbx_outgoing_exten (const char *type, int format, void *data, int timeout, const char *context, const char *exten, int priority, int *reason, int synchronous, const char *cid_num, const char *cid_name, struct ast_variable *vars, const char *account, struct ast_channel **channel)
enum ast_pbx_result ast_pbx_run (struct ast_channel *c)
Execute the PBX in the current thread.
static void * ast_pbx_run_app (void *data)
run the application and free the descriptor once done
enum ast_pbx_result ast_pbx_run_args (struct ast_channel *c, struct ast_pbx_args *args)
Execute the PBX in the current thread.
enum ast_pbx_result ast_pbx_start (struct ast_channel *c)
Create a new thread and start the PBX.
int ast_processed_calls (void)
Retrieve the total number of calls processed through the PBX since last restart.
int ast_rdlock_context (struct ast_context *con)
Read locks a given context.
int ast_rdlock_contexts ()
Read locks the context list.
int ast_register_application2 (const char *app, int(*execute)(struct ast_channel *, void *), const char *synopsis, const char *description, void *mod)
Dynamically register a new dial plan application.
int ast_register_switch (struct ast_switch *sw)
Register an alternative dialplan switch.
static int ast_remove_hint (struct ast_exten *e)
Remove hint from extension.
int ast_spawn_extension (struct ast_channel *c, const char *context, const char *exten, int priority, const char *callerid, int *found, int combined_find_spawn)
Launch a new extension (i.e. new stack).
int ast_unlock_context (struct ast_context *con)
int ast_unlock_contexts ()
Unlocks contexts.
int ast_unregister_application (const char *app)
Unregister an application.
void ast_unregister_switch (struct ast_switch *sw)
Unregister an alternative switch.
struct ast_exten * ast_walk_context_extensions (struct ast_context *con, struct ast_exten *exten)
struct ast_ignorepat * ast_walk_context_ignorepats (struct ast_context *con, struct ast_ignorepat *ip)
struct ast_include * ast_walk_context_includes (struct ast_context *con, struct ast_include *inc)
struct ast_sw * ast_walk_context_switches (struct ast_context *con, struct ast_sw *sw)
struct ast_context * ast_walk_contexts (struct ast_context *con)
struct ast_exten * ast_walk_extension_priorities (struct ast_exten *exten, struct ast_exten *priority)
int ast_wrlock_context (struct ast_context *con)
Write locks a given context.
int ast_wrlock_contexts ()
Write locks the context list.
int ast_wrlock_contexts_version (void)
static void * async_wait (void *data)
static void cli_match_char_tree (struct match_char *node, char *prefix, int fd)
static int collect_digits (struct ast_channel *c, int waittime, char *buf, int buflen, int pos)
collect digits from the channel into the buffer.
static int compare_char (const void *a, const void *b)
static char * complete_core_show_hint (const char *line, const char *word, int pos, int state)
autocomplete for CLI command 'core show hint'
static char * complete_show_dialplan_context (const char *line, const char *word, int pos, int state)
static void context_merge (struct ast_context **extcontexts, struct ast_hashtab *exttable, struct ast_context *context, const char *registrar)
static void context_merge_incls_swits_igps_other_registrars (struct ast_context *new, struct ast_context *old, const char *registrar)
static void create_match_char_tree (struct ast_context *con)
static void decrease_call_count (void)
static void destroy_exten (struct ast_exten *e)
static void destroy_pattern_tree (struct match_char *pattern_tree)
static void device_state_cb (const struct ast_event *event, void *unused)
static void exception_store_free (void *data)
static int ext_cmp (const char *a, const char *b)
the full routine to compare extensions in rules.
static int ext_cmp1 (const char **p, unsigned char *bitwise)
helper functions to sort extensions and patterns in the desired way, so that more specific patterns appear first.
static int ext_strncpy (char *dst, const char *src, int len)
copy a string skipping whitespace
static int extension_match_core (const char *pattern, const char *data, enum ext_match_t mode)
static struct ast_context * find_context (const char *context)
lookup for a context with a given name,
static struct ast_context * find_context_locked (const char *context)
lookup for a context with a given name,
static char * func_args (char *function)
return a pointer to the arguments of the function, and terminates the function name with '\0'
static struct ast_exten * get_canmatch_exten (struct match_char *node)
static unsigned get_range (char *src, int max, char *const names[], const char *msg)
helper function to return a range up to max (7, 12, 31 respectively). names, if supplied, is an array of names that should be mapped to numbers.
static void get_timerange (struct ast_timing *i, char *times)
store a bitmask of valid times, one bit each 1 minute
static char * handle_debug_dialplan (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
Send ack once.
static char * handle_set_chanvar (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_set_extenpatternmatchnew (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_set_global (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_application (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_applications (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_chanvar (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI support for listing chanvar's variables in a parseable way.
static char * handle_show_dialplan (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_function (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_functions (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_show_globals (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
CLI support for listing global variables in a parseable way.
static char * handle_show_hint (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handle_show_hint: CLI support for listing registered dial plan hint
static char * handle_show_hints (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handle_show_hints: CLI support for listing registered dial plan hints
static char * handle_show_switches (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handle_show_switches: CLI support for listing registered dial plan switches
static int handle_statechange (void *datap)
static char * handle_unset_extenpatternmatchnew (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int hashtab_compare_exten_labels (const void *ah_a, const void *ah_b)
static int hashtab_compare_exten_numbers (const void *ah_a, const void *ah_b)
static int hashtab_compare_extens (const void *ha_a, const void *ah_b)
static unsigned int hashtab_hash_extens (const void *obj)
static unsigned int hashtab_hash_labels (const void *obj)
static unsigned int hashtab_hash_priority (const void *obj)
static int include_valid (struct ast_include *i)
static int increase_call_count (const struct ast_channel *c)
Increase call count for channel.
static void insert_in_next_chars_alt_char_list (struct match_char **parent_ptr, struct match_char *node)
int load_pbx (void)
void log_match_char_tree (struct match_char *node, char *prefix)
static int lookup_name (const char *s, char *const names[], int max)
Helper for get_range. return the index of the matching entry, starting from 1. If names is not supplied, try numeric values.
static void manager_dpsendack (struct mansession *s, const struct message *m)
Send ack once.
static int manager_show_dialplan (struct mansession *s, const struct message *m)
Manager listing of dial plan.
static int manager_show_dialplan_helper (struct mansession *s, const struct message *m, const char *actionidtext, const char *context, const char *exten, struct dialplan_counters *dpc, struct ast_include *rinclude)
Show dialplan extensions XXX this function is similar but not exactly the same as the CLI's show dialplan. Must check whether the difference is intentional or not.
static int matchcid (const char *cidpattern, const char *callerid)
static void new_find_extension (const char *str, struct scoreboard *score, struct match_char *tree, int length, int spec, const char *callerid, const char *label, enum ext_match_t action)
static int parse_variable_name (char *var, int *offset, int *length, int *isfunc)
extract offset:length from variable name.
static int pbx_builtin_answer (struct ast_channel *, void *)
static int pbx_builtin_background (struct ast_channel *, void *)
static int pbx_builtin_busy (struct ast_channel *, void *)
void pbx_builtin_clear_globals (void)
static int pbx_builtin_congestion (struct ast_channel *, void *)
static int pbx_builtin_execiftime (struct ast_channel *, void *)
const char * pbx_builtin_getvar_helper (struct ast_channel *chan, const char *name)
Return a pointer to the value of the corresponding channel variable.
static int pbx_builtin_goto (struct ast_channel *, void *)
static int pbx_builtin_gotoif (struct ast_channel *, void *)
static int pbx_builtin_gotoiftime (struct ast_channel *, void *)
static int pbx_builtin_hangup (struct ast_channel *, void *)
static int pbx_builtin_importvar (struct ast_channel *, void *)
static int pbx_builtin_incomplete (struct ast_channel *, void *)
static int pbx_builtin_noop (struct ast_channel *, void *)
static int pbx_builtin_proceeding (struct ast_channel *, void *)
static int pbx_builtin_progress (struct ast_channel *, void *)
void pbx_builtin_pushvar_helper (struct ast_channel *chan, const char *name, const char *value)
Add a variable to the channel variable stack, without removing any previously set value.
int pbx_builtin_raise_exception (struct ast_channel *chan, void *vreason)
static int pbx_builtin_resetcdr (struct ast_channel *, void *)
static int pbx_builtin_ringing (struct ast_channel *, void *)
static int pbx_builtin_saycharacters (struct ast_channel *, void *)
static int pbx_builtin_saydigits (struct ast_channel *, void *)
static int pbx_builtin_saynumber (struct ast_channel *, void *)
static int pbx_builtin_sayphonetic (struct ast_channel *, void *)
int pbx_builtin_serialize_variables (struct ast_channel *chan, struct ast_str **buf)
Create a human-readable string, specifying all variables and their corresponding values.
static int pbx_builtin_setamaflags (struct ast_channel *, void *)
int pbx_builtin_setvar (struct ast_channel *, void *)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
void pbx_builtin_setvar_helper (struct ast_channel *chan, const char *name, const char *value)
Add a variable to the channel variable stack, removing the most recently set value for the same name.
int pbx_builtin_setvar_multiple (struct ast_channel *, void *)
Parse and set multiple channel variables, where the pairs are separated by the ',' character, and name and value are separated with an '=' character.
static int pbx_builtin_wait (struct ast_channel *, void *)
static int pbx_builtin_waitexten (struct ast_channel *, void *)
int pbx_checkcondition (const char *condition)
Evaluate a condition.
static void pbx_destroy (struct ast_pbx *p)
int pbx_exec (struct ast_channel *c, struct ast_app *app, void *data)
Execute an application.
static int pbx_extension_helper (struct ast_channel *c, struct ast_context *con, const char *context, const char *exten, int priority, const char *label, const char *callerid, enum ext_match_t action, int *found, int combined_find_spawn)
The return value depends on the action:.
struct ast_exten * pbx_find_extension (struct ast_channel *chan, struct ast_context *bypass, struct pbx_find_info *q, const char *context, const char *exten, int priority, const char *label, const char *callerid, enum ext_match_t action)
struct ast_app * pbx_findapp (const char *app)
Find application handle in linked list.
static struct ast_switch * pbx_findswitch (const char *sw)
static int pbx_parseable_goto (struct ast_channel *chan, const char *goto_string, int async)
void pbx_retrieve_variable (struct ast_channel *c, const char *var, char **ret, char *workspace, int workspacelen, struct varshead *headp)
Support for Asterisk built-in variables in the dialplan.
int pbx_set_autofallthrough (int newval)
int pbx_set_extenpatternmatchnew (int newval)
void pbx_set_overrideswitch (const char *newval)
static void pbx_substitute_variables (char *passdata, int datalen, struct ast_channel *c, struct ast_exten *e)
void pbx_substitute_variables_helper (struct ast_channel *c, const char *cp1, char *cp2, int count)
void pbx_substitute_variables_helper_full (struct ast_channel *c, struct varshead *headp, const char *cp1, char *cp2, int count, size_t *used)
void pbx_substitute_variables_varshead (struct varshead *headp, const char *cp1, char *cp2, int count)
static void * pbx_thread (void *data)
static void print_app_docs (struct ast_app *aa, int fd)
static void print_ext (struct ast_exten *e, char *buf, int buflen)
helper function to print an extension
static void set_ext_pri (struct ast_channel *c, const char *exten, int pri)
static int show_debug_helper (int fd, const char *context, const char *exten, struct dialplan_counters *dpc, struct ast_include *rinclude, int includecount, const char *includes[])
static int show_dialplan_helper (int fd, const char *context, const char *exten, struct dialplan_counters *dpc, struct ast_include *rinclude, int includecount, const char *includes[])
static char * substring (const char *value, int offset, int length, char *workspace, size_t workspace_len)
takes a substring. It is ok to call with value == workspace.
static struct ast_exten * trie_find_next_match (struct match_char *node)
static void unreference_cached_app (struct ast_app *app)
static void update_scoreboard (struct scoreboard *board, int length, int spec, struct ast_exten *exten, char last, const char *callerid, int deleted, struct match_char *node)
static void wait_for_hangup (struct ast_channel *chan, void *data)
Variables
static int autofallthrough = 1
static struct ast_app_option background_opts [128] = { [ 's' ] = { .flag = (1 << 0) }, [ 'n' ] = { .flag = (1 << 1) }, [ 'm' ] = { .flag = (1 << 2) }, [ 'p' ] = { .flag = (1 << 3) },}
static struct pbx_builtin builtins []
Declaration of builtin applications.
static ast_rwlock_t conlock = PTHREAD_RWLOCK_INITIALIZER
static int conlock_wrlock_version = 0
static struct ast_context * contexts
static struct ast_hashtab * contexts_table = NULL
static int countcalls
static char * days []
static struct ast_event_sub * device_state_sub
Subscription for device state change events.
static struct ast_taskprocessor * device_state_tps
static struct ast_custom_function exception_function
static struct ast_datastore_info exception_store_info
static int extenpatternmatchnew = 0
static struct cfextension_states extension_states []
static struct ast_threadstorage extensionstate_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_extensionstate_buf , .custom_init = NULL , }
static struct varshead globals = AST_LIST_HEAD_NOLOCK_INIT_VALUE
static ast_rwlock_t globalslock = PTHREAD_RWLOCK_INITIALIZER
static char mandescr_show_dialplan []
static ast_mutex_t maxcalllock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER)
static char * months []
static char * overrideswitch = NULL
static struct ast_cli_entry pbx_cli []
static struct ast_app_option resetcdr_opts [128] = { [ 'w' ] = { .flag = (1 << 1) }, [ 'a' ] = { .flag = (1 << 2) }, [ 'v' ] = { .flag = (1 << 0) }, [ 'e' ] = { .flag = (1 << 10) },}
static int stateid = 1
static struct ast_threadstorage switch_data = { .once = PTHREAD_ONCE_INIT , .key_init = __init_switch_data , .custom_init = NULL , }
static int totalcalls
static struct ast_app_option waitexten_opts [128] = { [ 'm' ] = { .flag = (1 << 0) , .arg_index = 0 + 1 }, [ 'd' ] = { .flag = (1 << 1) , .arg_index = 0 + 1 },}
Detailed Description
Core PBX routines.
Author:
Mark Spencer <markster@digium.com>
Definition in file pbx.c.
Define Documentation
#define AST_PBX_MAX_STACK 128
Go no deeper than this through includes (not counting loops)
Definition at line 1359 of file pbx.c.
#define BACKGROUND_MATCHEXTEN (1 << 2)
Definition at line 737 of file pbx.c.
Referenced by pbx_builtin_background().
#define BACKGROUND_NOANSWER (1 << 1)
Definition at line 736 of file pbx.c.
Referenced by pbx_builtin_background().
#define BACKGROUND_PLAYBACK (1 << 3)
Definition at line 738 of file pbx.c.
Referenced by pbx_builtin_background().
#define BACKGROUND_SKIP (1 << 0)
Definition at line 735 of file pbx.c.
Referenced by pbx_builtin_background().
#define EXT_DATA_SIZE 8192
Note:
I M P O R T A N T :
The speed of extension handling will likely be among the most important aspects of this PBX. The switching scheme as it exists right now isn't terribly bad (it's O(N+M), where N is the # of extensions and M is the avg # of priorities, but a constant search time here would be great ;-)
A new algorithm to do searching based on a 'compiled' pattern tree is introduced here, and shows a fairly flat (constant) search time, even for over 10000 patterns.
Also, using a hash table for context/priority name lookup can help prevent the find_extension routines from absorbing exponential cpu cycles as the number of contexts/priorities grow. I've previously tested find_extension with red-black trees, which have O(log2(n)) speed. Right now, I'm using hash tables, which do searches (ideally) in O(1) time. While these techniques do not yield much speed in small dialplans, they are worth the trouble in large dialplans.
Definition at line 724 of file pbx.c.
Referenced by pbx_extension_helper(), and realtime_exec().
#define NEW_MATCHER_CHK_MATCH
Referenced by new_find_extension().
#define NEW_MATCHER_RECURSE
Referenced by new_find_extension().
#define SAY_STUBS
Definition at line 54 of file pbx.c.
#define STATUS_NO_CONTEXT 1
Definition at line 2451 of file pbx.c.
#define STATUS_NO_EXTENSION 2
Definition at line 2452 of file pbx.c.
#define STATUS_NO_LABEL 4
Definition at line 2454 of file pbx.c.
#define STATUS_NO_PRIORITY 3
Definition at line 2453 of file pbx.c.
#define STATUS_SUCCESS 5
Definition at line 2455 of file pbx.c.
#define SWITCH_DATA_LENGTH 256
Definition at line 727 of file pbx.c.
#define VAR_BUF_SIZE 4096
Definition at line 729 of file pbx.c.
Referenced by add_user_extension(), ast_add_extension2_lockopt(), build_user_routes(), pbx_builtin_importvar(), pbx_substitute_variables_helper_full(), phoneprov_callback(), pp_each_extension_exec(), and pp_each_user_exec().
#define VAR_HARDTRAN 3
Definition at line 733 of file pbx.c.
#define VAR_NORMAL 1
Definition at line 731 of file pbx.c.
#define VAR_SOFTTRAN 2
Definition at line 732 of file pbx.c.
#define WAITEXTEN_DIALTONE (1 << 1)
Definition at line 748 of file pbx.c.
Referenced by pbx_builtin_waitexten().
#define WAITEXTEN_MOH (1 << 0)
Definition at line 747 of file pbx.c.
Referenced by pbx_builtin_waitexten().
Function Documentation
void __ast_context_destroy (struct ast_context * list, struct ast_hashtab * contexttab, struct ast_context * con, const char * registrar)
Definition at line 8276 of file pbx.c.
References __ast_internal_context_destroy(), ast_context::alts, ast_context_remove_extension_callerid2(), ast_debug, ast_free, ast_hashtab_end_traversal(), ast_hashtab_next(), ast_hashtab_remove_this_object(), ast_hashtab_start_traversal(), AST_LIST_EMPTY, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_exten::cidmatch, contexts, ast_exten::exten, ast_context::ignorepats, ast_context::includes, ast_context::name, ast_include::next, ast_ignorepat::next, ast_context::next, ast_sw::next, ast_exten::peer_table, ast_exten::priority, ast_context::refcount, ast_exten::registrar, ast_sw::registrar, ast_include::registrar, ast_ignorepat::registrar, ast_context::registrar, ast_context::root, and ast_context::root_table.
Referenced by ast_context_destroy().
{
   struct ast_context *tmp, *tmpl=NULL;
   struct ast_exten *exten_item, *prio_item;
   for (tmp = list; tmp; ) {
      struct ast_context *next = NULL; /* next starting point */
         /* The following code used to skip forward to the next
            context with matching registrar, but this didn't
            make sense; individual priorities registrar'd to
            the matching registrar could occur in any context! */
      ast_debug(1, "Investigate ctx %s %s\n", tmp->name, tmp->registrar);
      if (con) {
         for (; tmp; tmpl = tmp, tmp = tmp->next) { /* skip to the matching context */
            ast_debug(1, "check ctx %s %s\n", tmp->name, tmp->registrar);
            if ( !strcasecmp(tmp->name, con->name) ) {
               break;   /* found it */
            }
         }
      }
      if (!tmp)   /* not found, we are done */
         break;
      ast_wrlock_context(tmp);
      if (registrar) {
         /* then search thru and remove any extens that match registrar. */
         struct ast_hashtab_iter *exten_iter;
         struct ast_hashtab_iter *prio_iter;
         struct ast_ignorepat *ip, *ipl = NULL, *ipn = NULL;
         struct ast_include *i, *pi = NULL, *ni = NULL;
         struct ast_sw *sw = NULL;
         /* remove any ignorepats whose registrar matches */
         for (ip = tmp->ignorepats; ip; ip = ipn) {
            ipn = ip->next;
            if (!strcmp(ip->registrar, registrar)) {
               if (ipl) {
                  ipl->next = ip->next;
                  ast_free(ip);
                  continue; /* don't change ipl */
               } else {
                  tmp->ignorepats = ip->next;
                  ast_free(ip);
                  continue; /* don't change ipl */
               }
            }
            ipl = ip;
         }
         /* remove any includes whose registrar matches */
         for (i = tmp->includes; i; i = ni) {
            ni = i->next;
            if (strcmp(i->registrar, registrar) == 0) {
               /* remove from list */
               if (pi) {
                  pi->next = i->next;
                  /* free include */
                  ast_free(i);
                  continue; /* don't change pi */
               } else {
                  tmp->includes = i->next;
                  /* free include */
                  ast_free(i);
                  continue; /* don't change pi */
               }
            }
            pi = i;
         }
         /* remove any switches whose registrar matches */
         AST_LIST_TRAVERSE_SAFE_BEGIN(&tmp->alts, sw, list) {
            if (strcmp(sw->registrar,registrar) == 0) {
               AST_LIST_REMOVE_CURRENT(list);
               ast_free(sw);
            }
         }
         AST_LIST_TRAVERSE_SAFE_END;
         if (tmp->root_table) { /* it is entirely possible that the context is EMPTY */
            exten_iter = ast_hashtab_start_traversal(tmp->root_table);
            while ((exten_item=ast_hashtab_next(exten_iter))) {
               prio_iter = ast_hashtab_start_traversal(exten_item->peer_table);
               while ((prio_item=ast_hashtab_next(prio_iter))) {
                  if (!prio_item->registrar || strcmp(prio_item->registrar, registrar) != 0) {
                     continue;
                  }
                  ast_verb(3, "Remove %s/%s/%d, registrar=%s; con=%s(%p); con->root=%p\n",
                         tmp->name, prio_item->exten, prio_item->priority, registrar, con? con->name : "<nil>", con, con? con->root_table: NULL);
                  /* set matchcid to 1 to insure we get a direct match, and NULL registrar to make sure no wildcarding is done */
                  ast_context_remove_extension_callerid2(tmp, prio_item->exten, prio_item->priority, prio_item->cidmatch, 1, NULL, 1);
               }
               ast_hashtab_end_traversal(prio_iter);
            }
            ast_hashtab_end_traversal(exten_iter);
         }
         /* delete the context if it's registrar matches, is empty, has refcount of 1, */
         /* it's not empty, if it has includes, ignorepats, or switches that are registered from
            another registrar. It's not empty if there are any extensions */
         if (strcmp(tmp->registrar, registrar) == 0 && tmp->refcount < 2 && !tmp->root && !tmp->ignorepats && !tmp->includes && AST_LIST_EMPTY(&tmp->alts)) {
            ast_debug(1, "delete ctx %s %s\n", tmp->name, tmp->registrar);
            ast_hashtab_remove_this_object(contexttab, tmp);
            next = tmp->next;
            if (tmpl)
               tmpl->next = next;
            else
               contexts = next;
            /* Okay, now we're safe to let it go -- in a sense, we were
               ready to let it go as soon as we locked it. */
            ast_unlock_context(tmp);
            __ast_internal_context_destroy(tmp);
         } else {
            ast_debug(1,"Couldn't delete ctx %s/%s; refc=%d; tmp.root=%p\n", tmp->name, tmp->registrar,
                    tmp->refcount, tmp->root);
            ast_unlock_context(tmp);
            next = tmp->next;
            tmpl = tmp;
         }
      } else if (con) {
         ast_verb(3, "Deleting context %s registrar=%s\n", tmp->name, tmp->registrar);
         ast_debug(1, "delete ctx %s %s\n", tmp->name, tmp->registrar);
         ast_hashtab_remove_this_object(contexttab, tmp);
         next = tmp->next;
         if (tmpl)
            tmpl->next = next;
         else
            contexts = next;
         /* Okay, now we're safe to let it go -- in a sense, we were
            ready to let it go as soon as we locked it. */
         ast_unlock_context(tmp);
         __ast_internal_context_destroy(tmp);
      }
      /* if we have a specific match, we are done, otherwise continue */
      tmp = con ? NULL : next;
   }
}
int __ast_custom_function_register (struct ast_custom_function * acf, struct ast_module * mod)
Register a custom function.
Definition at line 3289 of file pbx.c.
References acf_retrieve_docs(), ast_custom_function::acflist, ast_log(), AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, AST_STATIC_DOC, ast_verb, COLOR_BRCYAN, ast_custom_function::docsrc, LOG_ERROR, ast_custom_function::mod, ast_custom_function::name, and term_color().
Referenced by load_pbx().
{
   struct ast_custom_function *cur;
   char tmps[80];
   if (!acf) {
      return -1;
   }
   acf->mod = mod;
   acf->docsrc = AST_STATIC_DOC;
   if (acf_retrieve_docs(acf)) {
      return -1;
   }
   AST_RWLIST_WRLOCK(&acf_root);
   AST_RWLIST_TRAVERSE(&acf_root, cur, acflist) {
      if (!strcmp(acf->name, cur->name)) {
         ast_log(LOG_ERROR, "Function %s already registered.\n", acf->name);
         AST_RWLIST_UNLOCK(&acf_root);
         return -1;
      }
   }
   /* Store in alphabetical order */
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&acf_root, cur, acflist) {
      if (strcasecmp(acf->name, cur->name) < 0) {
         AST_RWLIST_INSERT_BEFORE_CURRENT(acf, acflist);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   if (!cur) {
      AST_RWLIST_INSERT_TAIL(&acf_root, acf, acflist);
   }
   AST_RWLIST_UNLOCK(&acf_root);
   ast_verb(2, "Registered custom function '%s'\n", term_color(tmps, acf->name, COLOR_BRCYAN, 0, sizeof(tmps)));
   return 0;
}
static int __ast_goto_if_exists (struct ast_channel * chan, const char * context, const char * exten, int priority, int async) [static]
Definition at line 9551 of file pbx.c.
References ast_async_goto(), ast_exists_extension(), ast_explicit_goto(), ast_channel::cid, ast_callerid::cid_num, ast_channel::context, and ast_channel::exten.
Referenced by ast_async_goto_if_exists(), and ast_goto_if_exists().
{
   int (*goto_func)(struct ast_channel *chan, const char *context, const char *exten, int priority);
   if (!chan)
      return -2;
   if (context == NULL)
      context = chan->context;
   if (exten == NULL)
      exten = chan->exten;
   goto_func = (async) ? ast_async_goto : ast_explicit_goto;
   if (ast_exists_extension(chan, context, exten, priority, chan->cid.cid_num))
      return goto_func(chan, context, exten, priority);
   else
      return -3;
}
static void __ast_internal_context_destroy (struct ast_context * con) [static]
Definition at line 8229 of file pbx.c.
References ast_context::alts, ast_free, ast_hashtab_destroy(), AST_LIST_REMOVE_HEAD, ast_rwlock_destroy(), destroy_exten(), destroy_pattern_tree(), el, ast_context::ignorepats, ast_context::includes, ast_context::lock, ast_exten::next, ast_ignorepat::next, ast_include::next, ast_context::pattern_tree, ast_exten::peer, ast_context::registrar, ast_context::root, and ast_context::root_table.
Referenced by __ast_context_destroy(), and ast_merge_contexts_and_delete().
{
   struct ast_include *tmpi;
   struct ast_sw *sw;
   struct ast_exten *e, *el, *en;
   struct ast_ignorepat *ipi;
   struct ast_context *tmp = con;
   for (tmpi = tmp->includes; tmpi; ) { /* Free includes */
      struct ast_include *tmpil = tmpi;
      tmpi = tmpi->next;
      ast_free(tmpil);
   }
   for (ipi = tmp->ignorepats; ipi; ) { /* Free ignorepats */
      struct ast_ignorepat *ipl = ipi;
      ipi = ipi->next;
      ast_free(ipl);
   }
   if (tmp->registrar)
      ast_free(tmp->registrar);
   /* destroy the hash tabs */
   if (tmp->root_table) {
      ast_hashtab_destroy(tmp->root_table, 0);
   }
   /* and destroy the pattern tree */
   if (tmp->pattern_tree)
      destroy_pattern_tree(tmp->pattern_tree);
   while ((sw = AST_LIST_REMOVE_HEAD(&tmp->alts, list)))
      ast_free(sw);
   for (e = tmp->root; e;) {
      for (en = e->peer; en;) {
         el = en;
         en = en->peer;
         destroy_exten(el);
      }
      el = e;
      e = e->next;
      destroy_exten(el);
   }
   tmp->root = NULL;
   ast_rwlock_destroy(&tmp->lock);
   ast_free(tmp);
}
static enum ast_pbx_result __ast_pbx_run (struct ast_channel * c, struct ast_pbx_args * args) [static]
Note:
We get here on a failure of some kind: non-existing extension or hangup. We have options, here. We can either catch the failure and continue, or we can drop out entirely.
If there is no match at priority 1, it is not a valid extension anymore. Try to continue at "i" (for invalid) or "e" (for exception) or exit if neither exist.
Definition at line 4214 of file pbx.c.
References ast_channel::_softhangup, ast_calloc, ast_cdr_end(), ast_cdr_update(), ast_check_hangup(), ast_clear_flag, ast_copy_string(), ast_debug, ast_exists_extension(), AST_FLAG_BRIDGE_HANGUP_RUN, AST_FLAG_IN_AUTOLOOP, ast_free, ast_hangup(), ast_log(), ast_matchmore_extension(), ast_opt_end_cdr_before_h_exten, AST_PBX_ERROR, AST_PBX_INCOMPLETE, ast_set2_flag, ast_set_flag, ast_softhangup(), AST_SOFTHANGUP_APPUNLOAD, AST_SOFTHANGUP_ASYNCGOTO, AST_SOFTHANGUP_TIMEOUT, ast_spawn_extension(), ast_strlen_zero(), ast_test_flag, ast_verb, autofallthrough, ast_channel::cdr, ast_channel::cid, ast_callerid::cid_num, collect_digits(), ast_channel::context, ast_pbx::dtimeoutms, ast_channel::exten, LOG_WARNING, ast_pbx_args::no_hangup_chan, ast_channel::pbx, pbx_builtin_busy(), pbx_builtin_congestion(), pbx_builtin_getvar_helper(), pbx_builtin_raise_exception(), pbx_builtin_setvar_helper(), pbx_destroy(), ast_channel::priority, ast_pbx::rtimeoutms, set_ext_pri(), status, and ast_channel::whentohangup.
Referenced by ast_pbx_run_args(), and pbx_thread().
{
   int found = 0; /* set if we find at least one match */
   int res = 0;
   int autoloopflag;
   int error = 0;    /* set an error conditions */
   /* A little initial setup here */
   if (c->pbx) {
      ast_log(LOG_WARNING, "%s already has PBX structure??\n", c->name);
      /* XXX and now what ? */
      ast_free(c->pbx);
   }
   if (!(c->pbx = ast_calloc(1, sizeof(*c->pbx))))
      return -1;
   /* Set reasonable defaults */
   c->pbx->rtimeoutms = 10000;
   c->pbx->dtimeoutms = 5000;
   autoloopflag = ast_test_flag(c, AST_FLAG_IN_AUTOLOOP);   /* save value to restore at the end */
   ast_set_flag(c, AST_FLAG_IN_AUTOLOOP);
   /* Start by trying whatever the channel is set to */
   if (!ast_exists_extension(c, c->context, c->exten, c->priority, c->cid.cid_num)) {
      /* If not successful fall back to 's' */
      ast_verb(2, "Starting %s at %s,%s,%d failed so falling back to exten 's'\n", c->name, c->context, c->exten, c->priority);
      /* XXX the original code used the existing priority in the call to
       * ast_exists_extension(), and reset it to 1 afterwards.
       * I believe the correct thing is to set it to 1 immediately.
       */
      set_ext_pri(c, "s", 1);
      if (!ast_exists_extension(c, c->context, c->exten, c->priority, c->cid.cid_num)) {
         /* JK02: And finally back to default if everything else failed */
         ast_verb(2, "Starting %s at %s,%s,%d still failed so falling back to context 'default'\n", c->name, c->context, c->exten, c->priority);
         ast_copy_string(c->context, "default", sizeof(c->context));
      }
   }
   if (c->cdr) {
      /* allow CDR variables that have been collected after channel was created to be visible during call */
      ast_cdr_update(c);
   }
   for (;;) {
      char dst_exten[256]; /* buffer to accumulate digits */
      int pos = 0;      /* XXX should check bounds */
      int digit = 0;
      int invalid = 0;
      int timeout = 0;
      /* loop on priorities in this context/exten */
      while ( !(res = ast_spawn_extension(c, c->context, c->exten, c->priority, c->cid.cid_num, &found,1))) {
         if (c->_softhangup == AST_SOFTHANGUP_TIMEOUT && ast_exists_extension(c, c->context, "T", 1, c->cid.cid_num)) {
            set_ext_pri(c, "T", 0); /* 0 will become 1 with the c->priority++; at the end */
            /* If the AbsoluteTimeout is not reset to 0, we'll get an infinite loop */
            memset(&c->whentohangup, 0, sizeof(c->whentohangup));
            c->_softhangup &= ~AST_SOFTHANGUP_TIMEOUT;
         } else if (c->_softhangup == AST_SOFTHANGUP_TIMEOUT && ast_exists_extension(c, c->context, "e", 1, c->cid.cid_num)) {
            pbx_builtin_raise_exception(c, "ABSOLUTETIMEOUT");
            /* If the AbsoluteTimeout is not reset to 0, we'll get an infinite loop */
            memset(&c->whentohangup, 0, sizeof(c->whentohangup));
            c->_softhangup &= ~AST_SOFTHANGUP_TIMEOUT;
         } else if (c->_softhangup == AST_SOFTHANGUP_ASYNCGOTO) {
            c->_softhangup = 0;
            continue;
         } else if (ast_check_hangup(c)) {
            ast_debug(1, "Extension %s, priority %d returned normally even though call was hung up\n",
               c->exten, c->priority);
            error = 1;
            break;
         }
         c->priority++;
      } /* end while  - from here on we can use 'break' to go out */
      if (found && res) {
         /* Something bad happened, or a hangup has been requested. */
         if (strchr("0123456789ABCDEF*#", res)) {
            ast_debug(1, "Oooh, got something to jump out with ('%c')!\n", res);
            pos = 0;
            dst_exten[pos++] = digit = res;
            dst_exten[pos] = '\0';
         } else if (res == AST_PBX_INCOMPLETE) {
            ast_debug(1, "Spawn extension (%s,%s,%d) exited INCOMPLETE on '%s'\n", c->context, c->exten, c->priority, c->name);
            ast_verb(2, "Spawn extension (%s, %s, %d) exited INCOMPLETE on '%s'\n", c->context, c->exten, c->priority, c->name);
            /* Don't cycle on incomplete - this will happen if the only extension that matches is our "incomplete" extension */
            if (!ast_matchmore_extension(c, c->context, c->exten, 1, c->cid.cid_num)) {
               invalid = 1;
            } else {
               ast_copy_string(dst_exten, c->exten, sizeof(dst_exten));
               digit = 1;
               pos = strlen(dst_exten);
            }
         } else {
            ast_debug(1, "Spawn extension (%s,%s,%d) exited non-zero on '%s'\n", c->context, c->exten, c->priority, c->name);
            ast_verb(2, "Spawn extension (%s, %s, %d) exited non-zero on '%s'\n", c->context, c->exten, c->priority, c->name);
            if ((res == AST_PBX_ERROR) && ast_exists_extension(c, c->context, "e", 1, c->cid.cid_num)) {
               /* if we are already on the 'e' exten, don't jump to it again */
               if (!strcmp(c->exten, "e")) {
                  ast_verb(2, "Spawn extension (%s, %s, %d) exited ERROR while already on 'e' exten on '%s'\n", c->context, c->exten, c->priority, c->name);
                  error = 1;
               } else {
                  pbx_builtin_raise_exception(c, "ERROR");
                  continue;
               }
            }
            if (c->_softhangup == AST_SOFTHANGUP_ASYNCGOTO) {
               c->_softhangup = 0;
               continue;
            } else if (c->_softhangup == AST_SOFTHANGUP_TIMEOUT && ast_exists_extension(c, c->context, "T", 1, c->cid.cid_num)) {
               set_ext_pri(c, "T", 1);
               /* If the AbsoluteTimeout is not reset to 0, we'll get an infinite loop */
               memset(&c->whentohangup, 0, sizeof(c->whentohangup));
               c->_softhangup &= ~AST_SOFTHANGUP_TIMEOUT;
               continue;
            } else {
               if (c->cdr)
                  ast_cdr_update(c);
               error = 1;
               break;
            }
         }
      }
      if (error)
         break;
      /*!\note
       * We get here on a failure of some kind:  non-existing extension or
       * hangup.  We have options, here.  We can either catch the failure
       * and continue, or we can drop out entirely. */
      if (invalid || !ast_exists_extension(c, c->context, c->exten, 1, c->cid.cid_num)) {
         /*!\note
          * If there is no match at priority 1, it is not a valid extension anymore.
          * Try to continue at "i" (for invalid) or "e" (for exception) or exit if
          * neither exist.
          */
         if (ast_exists_extension(c, c->context, "i", 1, c->cid.cid_num)) {
            ast_verb(3, "Sent into invalid extension '%s' in context '%s' on %s\n", c->exten, c->context, c->name);
            pbx_builtin_setvar_helper(c, "INVALID_EXTEN", c->exten);
            set_ext_pri(c, "i", 1);
         } else if (ast_exists_extension(c, c->context, "e", 1, c->cid.cid_num)) {
            pbx_builtin_raise_exception(c, "INVALID");
         } else {
            ast_log(LOG_WARNING, "Channel '%s' sent into invalid extension '%s' in context '%s', but no invalid handler\n",
               c->name, c->exten, c->context);
            error = 1; /* we know what to do with it */
            break;
         }
      } else if (c->_softhangup == AST_SOFTHANGUP_TIMEOUT) {
         /* If we get this far with AST_SOFTHANGUP_TIMEOUT, then we know that the "T" extension is next. */
         c->_softhangup = 0;
      } else { /* keypress received, get more digits for a full extension */
         int waittime = 0;
         if (digit)
            waittime = c->pbx->dtimeoutms;
         else if (!autofallthrough)
            waittime = c->pbx->rtimeoutms;
         if (!waittime) {
            const char *status = pbx_builtin_getvar_helper(c, "DIALSTATUS");
            if (!status)
               status = "UNKNOWN";
            ast_verb(3, "Auto fallthrough, channel '%s' status is '%s'\n", c->name, status);
            if (!strcasecmp(status, "CONGESTION"))
               res = pbx_builtin_congestion(c, "10");
            else if (!strcasecmp(status, "CHANUNAVAIL"))
               res = pbx_builtin_congestion(c, "10");
            else if (!strcasecmp(status, "BUSY"))
               res = pbx_builtin_busy(c, "10");
            error = 1; /* XXX disable message */
            break;   /* exit from the 'for' loop */
         }
         if (collect_digits(c, waittime, dst_exten, sizeof(dst_exten), pos))
            break;
         if (res == AST_PBX_INCOMPLETE && ast_strlen_zero(&dst_exten[pos]))
            timeout = 1;
         if (!timeout && ast_exists_extension(c, c->context, dst_exten, 1, c->cid.cid_num)) /* Prepare the next cycle */
            set_ext_pri(c, dst_exten, 1);
         else {
            /* No such extension */
            if (!timeout && !ast_strlen_zero(dst_exten)) {
               /* An invalid extension */
               if (ast_exists_extension(c, c->context, "i", 1, c->cid.cid_num)) {
                  ast_verb(3, "Invalid extension '%s' in context '%s' on %s\n", dst_exten, c->context, c->name);
                  pbx_builtin_setvar_helper(c, "INVALID_EXTEN", dst_exten);
                  set_ext_pri(c, "i", 1);
               } else if (ast_exists_extension(c, c->context, "e", 1, c->cid.cid_num)) {
                  pbx_builtin_raise_exception(c, "INVALID");
               } else {
                  ast_log(LOG_WARNING, "Invalid extension '%s', but no rule 'i' in context '%s'\n", dst_exten, c->context);
                  found = 1; /* XXX disable message */
                  break;
               }
            } else {
               /* A simple timeout */
               if (ast_exists_extension(c, c->context, "t", 1, c->cid.cid_num)) {
                  ast_verb(3, "Timeout on %s\n", c->name);
                  set_ext_pri(c, "t", 1);
               } else if (ast_exists_extension(c, c->context, "e", 1, c->cid.cid_num)) {
                  pbx_builtin_raise_exception(c, "RESPONSETIMEOUT");
               } else {
                  ast_log(LOG_WARNING, "Timeout, but no rule 't' in context '%s'\n", c->context);
                  found = 1; /* XXX disable message */
                  break;
               }
            }
         }
         if (c->cdr) {
            ast_verb(2, "CDR updated on %s\n",c->name);
            ast_cdr_update(c);
         }
      }
   }
   if (!found && !error) {
      ast_log(LOG_WARNING, "Don't know what to do with '%s'\n", c->name);
   }
   if (!args || !args->no_hangup_chan) {
      ast_softhangup(c, AST_SOFTHANGUP_APPUNLOAD);
   }
   if ((!args || !args->no_hangup_chan) &&
         !ast_test_flag(c, AST_FLAG_BRIDGE_HANGUP_RUN) &&
         ast_exists_extension(c, c->context, "h", 1, c->cid.cid_num)) {
      set_ext_pri(c, "h", 1);
      if (c->cdr && ast_opt_end_cdr_before_h_exten) {
         ast_cdr_end(c->cdr);
      }
      while ((res = ast_spawn_extension(c, c->context, c->exten, c->priority, c->cid.cid_num, &found, 1)) == 0) {
         c->priority++;
      }
      if (found && res) {
         /* Something bad happened, or a hangup has been requested. */
         ast_debug(1, "Spawn extension (%s,%s,%d) exited non-zero on '%s'\n", c->context, c->exten, c->priority, c->name);
         ast_verb(2, "Spawn extension (%s, %s, %d) exited non-zero on '%s'\n", c->context, c->exten, c->priority, c->name);
      }
   }
   ast_set2_flag(c, autoloopflag, AST_FLAG_IN_AUTOLOOP);
   ast_clear_flag(c, AST_FLAG_BRIDGE_HANGUP_RUN); /* from one round to the next, make sure this gets cleared */
   pbx_destroy(c->pbx);
   c->pbx = NULL;
   if (!args || !args->no_hangup_chan) {
      ast_hangup(c);
   }
   return 0;
}
static void __init_extensionstate_buf (void) [static]
Definition at line 761 of file pbx.c.
: An extension
static void __init_switch_data (void) [static]
Definition at line 760 of file pbx.c.
: An extension
static int _extension_match_core (const char * pattern, const char * data, enum ext_match_t mode) [static]
Definition at line 2226 of file pbx.c.
References ast_log(), E_MATCH, E_MATCH_MASK, E_MATCHMORE, LOG_NOTICE, and LOG_WARNING.
Referenced by extension_match_core().
{
   mode &= E_MATCH_MASK;   /* only consider the relevant bits */
#ifdef NEED_DEBUG_HERE
   ast_log(LOG_NOTICE,"match core: pat: '%s', dat: '%s', mode=%d\n", pattern, data, (int)mode);
#endif
   if ( (mode == E_MATCH) && (pattern[0] == '_') && (!strcasecmp(pattern,data)) ) { /* note: if this test is left out, then _x. will not match _x. !!! */
#ifdef NEED_DEBUG_HERE
      ast_log(LOG_NOTICE,"return (1) - pattern matches pattern\n");
#endif
      return 1;
   }
   if (pattern[0] != '_') { /* not a pattern, try exact or partial match */
      int ld = strlen(data), lp = strlen(pattern);
      if (lp < ld) {    /* pattern too short, cannot match */
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"return (0) - pattern too short, cannot match\n");
#endif
         return 0;
      }
      /* depending on the mode, accept full or partial match or both */
      if (mode == E_MATCH) {
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"return (!strcmp(%s,%s) when mode== E_MATCH)\n", pattern, data);
#endif
         return !strcmp(pattern, data); /* 1 on match, 0 on fail */
      }
      if (ld == 0 || !strncasecmp(pattern, data, ld)) { /* partial or full match */
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"return (mode(%d) == E_MATCHMORE ? lp(%d) > ld(%d) : 1)\n", mode, lp, ld);
#endif
         return (mode == E_MATCHMORE) ? lp > ld : 1; /* XXX should consider '!' and '/' ? */
      } else {
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"return (0) when ld(%d) > 0 && pattern(%s) != data(%s)\n", ld, pattern, data);
#endif
         return 0;
      }
   }
   pattern++; /* skip leading _ */
   /*
    * XXX below we stop at '/' which is a separator for the CID info. However we should
    * not store '/' in the pattern at all. When we insure it, we can remove the checks.
    */
   while (*data && *pattern && *pattern != '/') {
      const char *end;
      if (*data == '-') { /* skip '-' in data (just a separator) */
         data++;
         continue;
      }
      switch (toupper(*pattern)) {
      case '[':   /* a range */
         end = strchr(pattern+1, ']'); /* XXX should deal with escapes ? */
         if (end == NULL) {
            ast_log(LOG_WARNING, "Wrong usage of [] in the extension\n");
            return 0;   /* unconditional failure */
         }
         for (pattern++; pattern != end; pattern++) {
            if (pattern+2 < end && pattern[1] == '-') { /* this is a range */
               if (*data >= pattern[0] && *data <= pattern[2])
                  break;   /* match found */
               else {
                  pattern += 2; /* skip a total of 3 chars */
                  continue;
               }
            } else if (*data == pattern[0])
               break;   /* match found */
         }
         if (pattern == end) {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"return (0) when pattern==end\n");
#endif
            return 0;
         }
         pattern = end; /* skip and continue */
         break;
      case 'N':
         if (*data < '2' || *data > '9') {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"return (0) N is matched\n");
#endif
            return 0;
         }
         break;
      case 'X':
         if (*data < '0' || *data > '9') {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"return (0) X is matched\n");
#endif
            return 0;
         }
         break;
      case 'Z':
         if (*data < '1' || *data > '9') {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"return (0) Z is matched\n");
#endif
            return 0;
         }
         break;
      case '.':   /* Must match, even with more digits */
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE, "return (1) when '.' is matched\n");
#endif
         return 1;
      case '!':   /* Early match */
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE, "return (2) when '!' is matched\n");
#endif
         return 2;
      case ' ':
      case '-':   /* Ignore these in patterns */
         data--; /* compensate the final data++ */
         break;
      default:
         if (*data != *pattern) {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE, "return (0) when *data(%c) != *pattern(%c)\n", *data, *pattern);
#endif
            return 0;
         }
      }
      data++;
      pattern++;
   }
   if (*data)        /* data longer than pattern, no match */ {
#ifdef NEED_DEBUG_HERE
      ast_log(LOG_NOTICE, "return (0) when data longer than pattern\n");
#endif
      return 0;
   }
   /*
    * match so far, but ran off the end of the data.
    * Depending on what is next, determine match or not.
    */
   if (*pattern == '\0' || *pattern == '/') {   /* exact match */
#ifdef NEED_DEBUG_HERE
      ast_log(LOG_NOTICE, "at end, return (%d) in 'exact match'\n", (mode==E_MATCHMORE) ? 0 : 1);
#endif
      return (mode == E_MATCHMORE) ? 0 : 1;  /* this is a failure for E_MATCHMORE */
   } else if (*pattern == '!')   {     /* early match */
#ifdef NEED_DEBUG_HERE
      ast_log(LOG_NOTICE, "at end, return (2) when '!' is matched\n");
#endif
      return 2;
   } else {                /* partial match */
#ifdef NEED_DEBUG_HERE
      ast_log(LOG_NOTICE, "at end, return (%d) which deps on E_MATCH\n", (mode == E_MATCH) ? 0 : 1);
#endif
      return (mode == E_MATCH) ? 0 : 1;   /* this is a failure for E_MATCH */
   }
}
static int acf_exception_read (struct ast_channel * chan, const char * name, char * data, char * buf, size_t buflen) [static]
Definition at line 3028 of file pbx.c.
References ast_channel_datastore_find(), ast_copy_string(), pbx_exception::context, ast_datastore::data, exception_store_info, pbx_exception::exten, pbx_exception::priority, and pbx_exception::reason.
{
   struct ast_datastore *ds = ast_channel_datastore_find(chan, &exception_store_info, NULL);
   struct pbx_exception *exception = NULL;
   if (!ds || !ds->data)
      return -1;
   exception = ds->data;
   if (!strcasecmp(data, "REASON"))
      ast_copy_string(buf, exception->reason, buflen);
   else if (!strcasecmp(data, "CONTEXT"))
      ast_copy_string(buf, exception->context, buflen);
   else if (!strncasecmp(data, "EXTEN", 5))
      ast_copy_string(buf, exception->exten, buflen);
   else if (!strcasecmp(data, "PRIORITY"))
      snprintf(buf, buflen, "%d", exception->priority);
   else
      return -1;
   return 0;
}
static int acf_retrieve_docs (struct ast_custom_function * acf) [static]
Definition at line 3244 of file pbx.c.
References ast_free, ast_string_field_init, ast_string_field_set, ast_strlen_zero(), AST_XML_DOC, ast_xmldoc_build_arguments(), ast_xmldoc_build_description(), ast_xmldoc_build_seealso(), ast_xmldoc_build_synopsis(), ast_xmldoc_build_syntax(), desc, ast_custom_function::docsrc, ast_custom_function::name, and synopsis.
Referenced by __ast_custom_function_register().
{
#ifdef AST_XML_DOCS
   char *tmpxml;
   /* Let's try to find it in the Documentation XML */
   if (!ast_strlen_zero(acf->desc) || !ast_strlen_zero(acf->synopsis)) {
      return 0;
   }
   if (ast_string_field_init(acf, 128)) {
      return -1;
   }
   /* load synopsis */
   tmpxml = ast_xmldoc_build_synopsis("function", acf->name);
   ast_string_field_set(acf, synopsis, tmpxml);
   ast_free(tmpxml);
   /* load description */
   tmpxml = ast_xmldoc_build_description("function", acf->name);
   ast_string_field_set(acf, desc, tmpxml);
   ast_free(tmpxml);
   /* load syntax */
   tmpxml = ast_xmldoc_build_syntax("function", acf->name);
   ast_string_field_set(acf, syntax, tmpxml);
   ast_free(tmpxml);
   /* load arguments */
   tmpxml = ast_xmldoc_build_arguments("function", acf->name);
   ast_string_field_set(acf, arguments, tmpxml);
   ast_free(tmpxml);
   /* load seealso */
   tmpxml = ast_xmldoc_build_seealso("function", acf->name);
   ast_string_field_set(acf, seealso, tmpxml);
   ast_free(tmpxml);
   acf->docsrc = AST_XML_DOC;
#endif
   return 0;
}
static struct match_char * add_exten_to_pattern_tree (struct ast_context * con, struct ast_exten * e1, int findonly) [static, read]
Definition at line 1873 of file pbx.c.
References add_pattern_node(), already_in_tree(), ast_copy_string(), ast_log(), buf, ast_exten::cidmatch, compare_char(), match_char::deleted, match_char::exten, ast_exten::exten, LOG_DEBUG, LOG_ERROR, LOG_WARNING, m1, m2, ast_exten::matchcid, match_char::next_char, and ast_context::pattern_tree.
Referenced by add_pri_lockopt(), ast_add_extension2_lockopt(), ast_context_remove_extension_callerid2(), and create_match_char_tree().
{
   struct match_char *m1 = NULL, *m2 = NULL, **m0;
   int specif;
   int already;
   int pattern = 0;
   char buf[256];
   char extenbuf[512];
   char *s1 = extenbuf;
   int l1 = strlen(e1->exten) + strlen(e1->cidmatch) + 2;
   ast_copy_string(extenbuf, e1->exten, sizeof(extenbuf));
   if (e1->matchcid &&  l1 <= sizeof(extenbuf)) {
      strcat(extenbuf, "/");
      strcat(extenbuf, e1->cidmatch);
   } else if (l1 > sizeof(extenbuf)) {
      ast_log(LOG_ERROR, "The pattern %s/%s is too big to deal with: it will be ignored! Disaster!\n", e1->exten, e1->cidmatch);
      return 0;
   }
#ifdef NEED_DEBUG
   ast_log(LOG_DEBUG, "Adding exten %s%c%s to tree\n", s1, e1->matchcid ? '/' : ' ', e1->matchcid ? e1->cidmatch : "");
#endif
   m1 = con->pattern_tree; /* each pattern starts over at the root of the pattern tree */
   m0 = &con->pattern_tree;
   already = 1;
   if ( *s1 == '_') {
      pattern = 1;
      s1++;
   }
   while( *s1 ) {
      if (pattern && *s1 == '[' && *(s1-1) != '\\') {
         char *s2 = buf;
         buf[0] = 0;
         s1++; /* get past the '[' */
         while (*s1 != ']' && *(s1 - 1) != '\\' ) {
            if (*s1 == '\\') {
               if (*(s1 + 1) == ']') {
                  *s2++ = ']';
                  s1++; s1++;
               } else if (*(s1 + 1) == '\\') {
                  *s2++ = '\\';
                  s1++; s1++;
               } else if (*(s1 + 1) == '-') {
                  *s2++ = '-';
                  s1++; s1++;
               } else if (*(s1 + 1) == '[') {
                  *s2++ = '[';
                  s1++; s1++;
               }
            } else if (*s1 == '-') { /* remember to add some error checking to all this! */
               char s3 = *(s1 - 1);
               char s4 = *(s1 + 1);
               for (s3++; s3 <= s4; s3++) {
                  *s2++ = s3;
               }
               s1++; s1++;
            } else if (*s1 == '\0') {
               ast_log(LOG_WARNING, "A matching ']' was not found for '[' in pattern string '%s'\n", extenbuf);
               break;
            } else {
               *s2++ = *s1++;
            }
         }
         *s2 = 0; /* null terminate the exploded range */
         /* sort the characters */
         specif = strlen(buf);
         qsort(buf, specif, 1, compare_char);
         specif <<= 8;
         specif += buf[0];
      } else {
         if (*s1 == '\\') {
            s1++;
            buf[0] = *s1;
         } else {
            if (pattern) {
               if (*s1 == 'n') /* make sure n,x,z patterns are canonicalized to N,X,Z */
                  *s1 = 'N';
               else if (*s1 == 'x')
                  *s1 = 'X';
               else if (*s1 == 'z')
                  *s1 = 'Z';
            }
            buf[0] = *s1;
         }
         buf[1] = 0;
         specif = 1;
      }
      m2 = 0;
      if (already && (m2 = already_in_tree(m1,buf)) && m2->next_char) {
         if (!(*(s1 + 1))) {  /* if this is the end of the pattern, but not the end of the tree, then mark this node with the exten...
                          * a shorter pattern might win if the longer one doesn't match */
            m2->exten = e1;
            m2->deleted = 0;
         }
         m1 = m2->next_char; /* m1 points to the node to compare against */
         m0 = &m2->next_char; /* m0 points to the ptr that points to m1 */
      } else { /* not already OR not m2 OR nor m2->next_char */
         if (m2) {
            if (findonly) {
               return m2;
            }
            m1 = m2; /* while m0 stays the same */
         } else {
            if (findonly) {
               return m1;
            }
            m1 = add_pattern_node(con, m1, buf, pattern, already,specif, m0); /* m1 is the node just added */
            m0 = &m1->next_char;
         }
         if (!(*(s1 + 1))) {
            m1->deleted = 0;
            m1->exten = e1;
         }
         already = 0;
      }
      s1++; /* advance to next char */
   }
   return m1;
}
static struct match_char * add_pattern_node (struct ast_context * con, struct match_char * current, char * pattern, int is_pattern, int already, int specificity, struct match_char ** parent) [static, read]
Definition at line 1831 of file pbx.c.
References ast_calloc, ast_free, ast_strdup, insert_in_next_chars_alt_char_list(), match_char::is_pattern, match_char::next_char, ast_context::pattern_tree, match_char::specificity, and match_char::x.
Referenced by add_exten_to_pattern_tree().
{
   struct match_char *m;
   if (!(m = ast_calloc(1, sizeof(*m)))) {
      return NULL;
   }
   if (!(m->x = ast_strdup(pattern))) {
      ast_free(m);
      return NULL;
   }
   /* the specificity scores are the same as used in the old
      pattern matcher. */
   m->is_pattern = is_pattern;
   if (specificity == 1 && is_pattern && pattern[0] == 'N')
      m->specificity = 0x0802;
   else if (specificity == 1 && is_pattern && pattern[0] == 'Z')
      m->specificity = 0x0901;
   else if (specificity == 1 && is_pattern && pattern[0] == 'X')
      m->specificity = 0x0a00;
   else if (specificity == 1 && is_pattern && pattern[0] == '.')
      m->specificity = 0x10000;
   else if (specificity == 1 && is_pattern && pattern[0] == '!')
      m->specificity = 0x20000;
   else
      m->specificity = specificity;
   if (!con->pattern_tree) {
      insert_in_next_chars_alt_char_list(&con->pattern_tree, m);
   } else {
      if (already) { /* switch to the new regime (traversing vs appending)*/
         insert_in_next_chars_alt_char_list(nextcharptr, m);
      } else {
         insert_in_next_chars_alt_char_list(&current->next_char, m);
      }
   }
   return m;
}
static int add_pri (struct ast_context * con, struct ast_exten * tmp, struct ast_exten * el, struct ast_exten * e, int replace) [static]
add the extension in the priority chain.
Return values:
0 on success.
-1 on failure.
Definition at line 7440 of file pbx.c.
References add_pri_lockopt().
Referenced by ast_add_extension2_lockopt().
{
   return add_pri_lockopt(con, tmp, el, e, replace, 1);
}
static int add_pri_lockopt (struct ast_context * con, struct ast_exten * tmp, struct ast_exten * el, struct ast_exten * e, int replace, int lockhints) [static]
add the extension in the priority chain.
Return values:
0 on success.
-1 on failure.
Definition at line 7451 of file pbx.c.
References add_exten_to_pattern_tree(), ast_add_hint(), ast_add_hint_nolock(), ast_change_hint(), ast_free, ast_hashtab_insert_safe(), ast_hashtab_remove_object_via_lookup(), ast_log(), ast_exten::data, ast_exten::datad, match_char::exten, ast_exten::exten, ast_exten::label, LOG_ERROR, LOG_WARNING, ast_context::name, ast_exten::next, ast_exten::peer, ast_exten::peer_label_table, ast_exten::peer_table, ast_exten::priority, PRIORITY_HINT, ast_context::root, ast_context::root_table, and match_char::x.
Referenced by add_pri().
{
   struct ast_exten *ep;
   struct ast_exten *eh=e;
   for (ep = NULL; e ; ep = e, e = e->peer) {
      if (e->priority >= tmp->priority)
         break;
   }
   if (!e) {   /* go at the end, and ep is surely set because the list is not empty */
      ast_hashtab_insert_safe(eh->peer_table, tmp);
      if (tmp->label) {
         ast_hashtab_insert_safe(eh->peer_label_table, tmp);
      }
      ep->peer = tmp;
      return 0;   /* success */
   }
   if (e->priority == tmp->priority) {
      /* Can't have something exactly the same.  Is this a
         replacement?  If so, replace, otherwise, bonk. */
      if (!replace) {
         ast_log(LOG_WARNING, "Unable to register extension '%s', priority %d in '%s', already in use\n", tmp->exten, tmp->priority, con->name);
         if (tmp->datad) {
            tmp->datad(tmp->data);
            /* if you free this, null it out */
            tmp->data = NULL;
         }
         ast_free(tmp);
         return -1;
      }
      /* we are replacing e, so copy the link fields and then update
       * whoever pointed to e to point to us
       */
      tmp->next = e->next; /* not meaningful if we are not first in the peer list */
      tmp->peer = e->peer; /* always meaningful */
      if (ep)  {     /* We're in the peer list, just insert ourselves */
         ast_hashtab_remove_object_via_lookup(eh->peer_table,e);
         if (e->label) {
            ast_hashtab_remove_object_via_lookup(eh->peer_label_table,e);
         }
         ast_hashtab_insert_safe(eh->peer_table,tmp);
         if (tmp->label) {
            ast_hashtab_insert_safe(eh->peer_label_table,tmp);
         }
         ep->peer = tmp;
      } else if (el) {     /* We're the first extension. Take over e's functions */
         struct match_char *x = add_exten_to_pattern_tree(con, e, 1);
         tmp->peer_table = e->peer_table;
         tmp->peer_label_table = e->peer_label_table;
         ast_hashtab_remove_object_via_lookup(tmp->peer_table,e);
         ast_hashtab_insert_safe(tmp->peer_table,tmp);
         if (e->label) {
            ast_hashtab_remove_object_via_lookup(tmp->peer_label_table, e);
         }
         if (tmp->label) {
            ast_hashtab_insert_safe(tmp->peer_label_table, tmp);
         }
         ast_hashtab_remove_object_via_lookup(con->root_table, e);
         ast_hashtab_insert_safe(con->root_table, tmp);
         el->next = tmp;
         /* The pattern trie points to this exten; replace the pointer,
            and all will be well */
         if (x) { /* if the trie isn't formed yet, don't sweat this */
            if (x->exten) { /* this test for safety purposes */
               x->exten = tmp; /* replace what would become a bad pointer */
            } else {
               ast_log(LOG_ERROR,"Trying to delete an exten from a context, but the pattern tree node returned isn't an extension\n");
            }
         }
      } else {       /* We're the very first extension.  */
         struct match_char *x = add_exten_to_pattern_tree(con, e, 1);
         ast_hashtab_remove_object_via_lookup(con->root_table, e);
         ast_hashtab_insert_safe(con->root_table, tmp);
         tmp->peer_table = e->peer_table;
         tmp->peer_label_table = e->peer_label_table;
         ast_hashtab_remove_object_via_lookup(tmp->peer_table, e);
         ast_hashtab_insert_safe(tmp->peer_table, tmp);
         if (e->label) {
            ast_hashtab_remove_object_via_lookup(tmp->peer_label_table, e);
         }
         if (tmp->label) {
            ast_hashtab_insert_safe(tmp->peer_label_table, tmp);
         }
         ast_hashtab_remove_object_via_lookup(con->root_table, e);
         ast_hashtab_insert_safe(con->root_table, tmp);
         con->root = tmp;
         /* The pattern trie points to this exten; replace the pointer,
            and all will be well */
         if (x) { /* if the trie isn't formed yet; no problem */
            if (x->exten) { /* this test for safety purposes */
               x->exten = tmp; /* replace what would become a bad pointer */
            } else {
               ast_log(LOG_ERROR,"Trying to delete an exten from a context, but the pattern tree node returned isn't an extension\n");
            }
         }
      }
      if (tmp->priority == PRIORITY_HINT)
         ast_change_hint(e,tmp);
      /* Destroy the old one */
      if (e->datad)
         e->datad(e->data);
      ast_free(e);
   } else { /* Slip ourselves in just before e */
      tmp->peer = e;
      tmp->next = e->next; /* extension chain, or NULL if e is not the first extension */
      if (ep) {         /* Easy enough, we're just in the peer list */
         if (tmp->label) {
            ast_hashtab_insert_safe(eh->peer_label_table, tmp);
         }
         ast_hashtab_insert_safe(eh->peer_table, tmp);
         ep->peer = tmp;
      } else {       /* we are the first in some peer list, so link in the ext list */
         tmp->peer_table = e->peer_table;
         tmp->peer_label_table = e->peer_label_table;
         e->peer_table = 0;
         e->peer_label_table = 0;
         ast_hashtab_insert_safe(tmp->peer_table, tmp);
         if (tmp->label) {
            ast_hashtab_insert_safe(tmp->peer_label_table, tmp);
         }
         ast_hashtab_remove_object_via_lookup(con->root_table, e);
         ast_hashtab_insert_safe(con->root_table, tmp);
         if (el)
            el->next = tmp;   /* in the middle... */
         else
            con->root = tmp; /* ... or at the head */
         e->next = NULL;   /* e is no more at the head, so e->next must be reset */
      }
      /* And immediately return success. */
      if (tmp->priority == PRIORITY_HINT) {
         if (lockhints) {
            ast_add_hint(tmp);
         } else {
            ast_add_hint_nolock(tmp);
         }
      }
   }
   return 0;
}
static struct match_char * already_in_tree (struct match_char * current, char * pat) [static, read]
Definition at line 1778 of file pbx.c.
References match_char::alt_char, and match_char::x.
Referenced by add_exten_to_pattern_tree().
{
   struct match_char *t;
   if (!current) {
      return 0;
   }
   for (t = current; t; t = t->alt_char) {
      if (!strcmp(pat, t->x)) { /* uh, we may want to sort exploded [] contents to make matching easy */
         return t;
      }
   }
   return 0;
}
int ast_active_calls (void)
Retrieve the number of active calls.
Definition at line 4601 of file pbx.c.
References countcalls.
Referenced by ast_var_Config(), handle_chanlist(), handle_showcalls(), and sysinfo_helper().
{
   return countcalls;
}
int ast_add_extension (const char * context, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar)
Add and extension to an extension context.
Parameters:
context context to add the extension to
replace
extension extension to add
priority priority level of extension addition
label extension label
callerid pattern to match CallerID, or NULL to match any CallerID
application application to run on the extension with that priority level
data data to pass to the application
datad
registrar who registered the extension
Return values:
0 success
-1 failure
Definition at line 7305 of file pbx.c.
References ast_add_extension2(), ast_unlock_contexts(), and find_context_locked().
Referenced by ast_extension_state_add(), handle_cli_dialplan_add_extension(), park_add_hints(), register_exten(), register_peer_exten(), and RegisterExtension().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) {
      ret = ast_add_extension2(c, replace, extension, priority, label, callerid,
         application, data, datad, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_add_extension2 (struct ast_context * con, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar)
Main interface to add extensions to the list for out context.
Add an extension to an extension context, this time with an ast_context *.
We sort extensions in order of matching preference, so that we can stop the search as soon as we find a suitable match. This ordering also takes care of wildcards such as '.' (meaning "one or more of any character") and '!' (which is 'earlymatch', meaning "zero or more of any character" but also impacts the return value from CANMATCH and EARLYMATCH.
The extension match rules defined in the devmeeting 2006.05.05 are quite simple: WE SELECT THE LONGEST MATCH. In detail, "longest" means the number of matched characters in the extension. In case of ties (e.g. _XXX and 333) in the length of a pattern, we give priority to entries with the smallest cardinality (e.g, [5-9] comes before [2-8] before the former has only 5 elements, while the latter has 7, etc. In case of same cardinality, the first element in the range counts. If we still have a tie, any final '!' will make this as a possibly less specific pattern.
EBUSY - can't lock EEXIST - extension with the same priority exist and no replace is set
Definition at line 7624 of file pbx.c.
References ast_add_extension2_lockopt().
Referenced by add_extensions(), ast_add_extension(), build_parkinglot(), context_merge(), load_config(), load_module(), manage_parkinglot(), park_call_full(), pbx_load_config(), pbx_load_users(), sla_build_station(), and sla_build_trunk().
{
   return ast_add_extension2_lockopt(con, replace, extension, priority, label, callerid, application, data, datad, registrar, 1, 1);
}
static int ast_add_extension2_lockopt (struct ast_context * con, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar, int lockconts, int lockhints) [static]
Does all the work of ast_add_extension2, but adds two args, to determine if context and hint locking should be done. In merge_and_delete, we need to do this without locking, as the locks are already held.
Definition at line 7637 of file pbx.c.
References add_exten_to_pattern_tree(), add_pri(), ast_exten::app, ast_add_hint(), ast_add_hint_nolock(), ast_calloc, ast_copy_string(), ast_debug, ast_hashtab_create(), ast_hashtab_insert_safe(), ast_hashtab_lookup(), ast_hashtab_newsize_java(), ast_hashtab_resize_java(), ast_log(), ast_strlen_zero(), ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_exten::cidmatch, ast_channel::context, ast_exten::data, ast_exten::datad, el, errno, ext_cmp(), ext_strncpy(), ast_exten::exten, ast_channel::exten, hashtab_compare_exten_labels(), hashtab_compare_exten_numbers(), hashtab_compare_extens(), hashtab_hash_extens(), hashtab_hash_labels(), hashtab_hash_priority(), ast_exten::label, LOG_ERROR, ast_exten::matchcid, ast_context::name, ast_exten::next, option_debug, ast_exten::parent, ast_context::pattern_tree, pbx_substitute_variables_helper(), ast_exten::peer_label_table, ast_exten::peer_table, ast_exten::priority, PRIORITY_HINT, ast_exten::registrar, ast_context::root, ast_context::root_table, ast_exten::stuff, and VAR_BUF_SIZE.
Referenced by ast_add_extension2(), and ast_add_extension_nolock().
{
   /*
    * Sort extensions (or patterns) according to the rules indicated above.
    * These are implemented by the function ext_cmp()).
    * All priorities for the same ext/pattern/cid are kept in a list,
    * using the 'peer' field  as a link field..
    */
   struct ast_exten *tmp, *tmp2, *e, *el = NULL;
   int res;
   int length;
   char *p;
   char expand_buf[VAR_BUF_SIZE];
   struct ast_exten dummy_exten = {0};
   char dummy_name[1024];
   if (ast_strlen_zero(extension)) {
      ast_log(LOG_ERROR,"You have to be kidding-- add exten '' to context %s? Figure out a name and call me back. Action ignored.\n",
            con->name);
      return -1;
   }
   /* If we are adding a hint evalulate in variables and global variables */
   if (priority == PRIORITY_HINT && strstr(application, "${") && !strstr(extension, "_")) {
      struct ast_channel c = {0, };
      ast_copy_string(c.exten, extension, sizeof(c.exten));
      ast_copy_string(c.context, con->name, sizeof(c.context));
      pbx_substitute_variables_helper(&c, application, expand_buf, sizeof(expand_buf));
      application = expand_buf;
   }
   length = sizeof(struct ast_exten);
   length += strlen(extension) + 1;
   length += strlen(application) + 1;
   if (label)
      length += strlen(label) + 1;
   if (callerid)
      length += strlen(callerid) + 1;
   else
      length ++;  /* just the '\0' */
   /* Be optimistic:  Build the extension structure first */
   if (!(tmp = ast_calloc(1, length)))
      return -1;
   if (ast_strlen_zero(label)) /* let's turn empty labels to a null ptr */
      label = 0;
   /* use p as dst in assignments, as the fields are const char * */
   p = tmp->stuff;
   if (label) {
      tmp->label = p;
      strcpy(p, label);
      p += strlen(label) + 1;
   }
   tmp->exten = p;
   p += ext_strncpy(p, extension, strlen(extension) + 1) + 1;
   tmp->priority = priority;
   tmp->cidmatch = p;   /* but use p for assignments below */
   /* Blank callerid and NULL callerid are two SEPARATE things.  Do NOT confuse the two!!! */
   if (callerid) {
      p += ext_strncpy(p, callerid, strlen(callerid) + 1) + 1;
      tmp->matchcid = 1;
   } else {
      *p++ = '\0';
      tmp->matchcid = 0;
   }
   tmp->app = p;
   strcpy(p, application);
   tmp->parent = con;
   tmp->data = data;
   tmp->datad = datad;
   tmp->registrar = registrar;
   if (lockconts) {
      ast_wrlock_context(con);
   }
   if (con->pattern_tree) { /* usually, on initial load, the pattern_tree isn't formed until the first find_exten; so if we are adding
                        an extension, and the trie exists, then we need to incrementally add this pattern to it. */
      ast_copy_string(dummy_name, extension, sizeof(dummy_name));
      dummy_exten.exten = dummy_name;
      dummy_exten.matchcid = 0;
      dummy_exten.cidmatch = 0;
      tmp2 = ast_hashtab_lookup(con->root_table, &dummy_exten);
      if (!tmp2) {
         /* hmmm, not in the trie; */
         add_exten_to_pattern_tree(con, tmp, 0);
         ast_hashtab_insert_safe(con->root_table, tmp); /* for the sake of completeness */
      }
   }
   res = 0; /* some compilers will think it is uninitialized otherwise */
   for (e = con->root; e; el = e, e = e->next) {   /* scan the extension list */
      res = ext_cmp(e->exten, tmp->exten);
      if (res == 0) { /* extension match, now look at cidmatch */
         if (!e->matchcid && !tmp->matchcid)
            res = 0;
         else if (tmp->matchcid && !e->matchcid)
            res = 1;
         else if (e->matchcid && !tmp->matchcid)
            res = -1;
         else
            res = ext_cmp(e->cidmatch, tmp->cidmatch);
      }
      if (res >= 0)
         break;
   }
   if (e && res == 0) { /* exact match, insert in the pri chain */
      res = add_pri(con, tmp, el, e, replace);
      if (lockconts) {
         ast_unlock_context(con);
      }
      if (res < 0) {
         errno = EEXIST;   /* XXX do we care ? */
         return 0; /* XXX should we return -1 maybe ? */
      }
   } else {
      /*
       * not an exact match, this is the first entry with this pattern,
       * so insert in the main list right before 'e' (if any)
       */
      tmp->next = e;
      if (el) {  /* there is another exten already in this context */
         el->next = tmp;
         tmp->peer_table = ast_hashtab_create(13,
                     hashtab_compare_exten_numbers,
                     ast_hashtab_resize_java,
                     ast_hashtab_newsize_java,
                     hashtab_hash_priority,
                     0);
         tmp->peer_label_table = ast_hashtab_create(7,
                        hashtab_compare_exten_labels,
                        ast_hashtab_resize_java,
                        ast_hashtab_newsize_java,
                        hashtab_hash_labels,
                        0);
         if (label) {
            ast_hashtab_insert_safe(tmp->peer_label_table, tmp);
         }
         ast_hashtab_insert_safe(tmp->peer_table, tmp);
      } else {  /* this is the first exten in this context */
         if (!con->root_table)
            con->root_table = ast_hashtab_create(27,
                                       hashtab_compare_extens,
                                       ast_hashtab_resize_java,
                                       ast_hashtab_newsize_java,
                                       hashtab_hash_extens,
                                       0);
         con->root = tmp;
         con->root->peer_table = ast_hashtab_create(13,
                        hashtab_compare_exten_numbers,
                        ast_hashtab_resize_java,
                        ast_hashtab_newsize_java,
                        hashtab_hash_priority,
                        0);
         con->root->peer_label_table = ast_hashtab_create(7,
                           hashtab_compare_exten_labels,
                           ast_hashtab_resize_java,
                           ast_hashtab_newsize_java,
                           hashtab_hash_labels,
                           0);
         if (label) {
            ast_hashtab_insert_safe(con->root->peer_label_table, tmp);
         }
         ast_hashtab_insert_safe(con->root->peer_table, tmp);
      }
      ast_hashtab_insert_safe(con->root_table, tmp);
      if (lockconts) {
         ast_unlock_context(con);
      }
      if (tmp->priority == PRIORITY_HINT) {
         if (lockhints) {
            ast_add_hint(tmp);
         } else {
            ast_add_hint_nolock(tmp);
         }
      }
   }
   if (option_debug) {
      if (tmp->matchcid) {
         ast_debug(1, "Added extension '%s' priority %d (CID match '%s') to %s (%p)\n",
                 tmp->exten, tmp->priority, tmp->cidmatch, con->name, con);
      } else {
         ast_debug(1, "Added extension '%s' priority %d to %s (%p)\n",
                 tmp->exten, tmp->priority, con->name, con);
      }
   }
   if (tmp->matchcid) {
      ast_verb(3, "Added extension '%s' priority %d (CID match '%s') to %s (%p)\n",
             tmp->exten, tmp->priority, tmp->cidmatch, con->name, con);
   } else {
      ast_verb(3, "Added extension '%s' priority %d to %s (%p)\n",
             tmp->exten, tmp->priority, con->name, con);
   }
   return 0;
}
static int ast_add_extension_nolock (const char * context, int replace, const char * extension, int priority, const char * label, const char * callerid, const char * application, void * data, void(*)(void *) datad, const char * registrar) [static]
Definition at line 7286 of file pbx.c.
References ast_add_extension2_lockopt(), and find_context().
Referenced by ast_merge_contexts_and_delete().
{
   int ret = -1;
   struct ast_context *c = find_context(context);
   if (c) {
      ret = ast_add_extension2_lockopt(c, replace, extension, priority, label, callerid,
         application, data, datad, registrar, 0, 0);
   }
   return ret;
}
static int ast_add_hint (struct ast_exten * e) [static]
Add hint to hint list, check initial extension state.
Definition at line 4060 of file pbx.c.
References ast_add_hint_nolock(), AST_RWLIST_UNLOCK, and AST_RWLIST_WRLOCK.
Referenced by add_pri_lockopt(), and ast_add_extension2_lockopt().
{
   int ret;
   AST_RWLIST_WRLOCK(&hints);
   ret = ast_add_hint_nolock(e);
   AST_RWLIST_UNLOCK(&hints);
   return ret;
}
static int ast_add_hint_nolock (struct ast_exten * e) [static]
Add hint to hint list, check initial extension state; the hints had better be WRLOCKED already!
Definition at line 4031 of file pbx.c.
References ast_calloc, ast_debug, ast_extension_state2(), ast_get_extension_app(), ast_get_extension_name(), AST_RWLIST_INSERT_HEAD, AST_RWLIST_TRAVERSE, ast_hint::exten, and ast_hint::laststate.
Referenced by add_pri_lockopt(), ast_add_extension2_lockopt(), and ast_add_hint().
{
   struct ast_hint *hint;
   if (!e)
      return -1;
   /* Search if hint exists, do nothing */
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (hint->exten == e) {
         ast_debug(2, "HINTS: Not re-adding existing hint %s: %s\n", ast_get_extension_name(e), ast_get_extension_app(e));
         return -1;
      }
   }
   ast_debug(2, "HINTS: Adding hint %s: %s\n", ast_get_extension_name(e), ast_get_extension_app(e));
   if (!(hint = ast_calloc(1, sizeof(*hint)))) {
      return -1;
   }
   /* Initialize and insert new item at the top */
   hint->exten = e;
   hint->laststate = ast_extension_state2(e);
   AST_RWLIST_INSERT_HEAD(&hints, hint, list);
   return 0;
}
int ast_async_goto (struct ast_channel * chan, const char * context, const char * exten, int priority)
Set the channel to next execute the specified dialplan location.
See also:
ast_async_parseable_goto, ast_async_goto_if_exists
Definition at line 7344 of file pbx.c.
References ast_channel::_state, ast_channel::amaflags, ast_cdr_discard(), ast_cdr_dup(), ast_channel_alloc, ast_channel_lock, ast_channel_masquerade(), ast_channel_unlock, ast_do_masquerade(), ast_explicit_goto(), ast_hangup(), ast_log(), ast_pbx_start(), AST_SOFTHANGUP_ASYNCGOTO, ast_softhangup_nolock(), ast_channel::cdr, ast_channel::context, ast_channel::exten, LOG_WARNING, ast_channel::pbx, ast_channel::readformat, S_OR, and ast_channel::writeformat.
Referenced by __ast_goto_if_exists(), action_redirect(), ast_async_goto_by_name(), builtin_blindtransfer(), console_transfer(), dahdi_handle_dtmfup(), handle_request_bye(), handle_request_refer(), pbx_parseable_goto(), process_ast_dsp(), sip_read(), and socket_process().
{
   int res = 0;
   ast_channel_lock(chan);
   if (chan->pbx) { /* This channel is currently in the PBX */
      ast_explicit_goto(chan, context, exten, priority + 1);
      ast_softhangup_nolock(chan, AST_SOFTHANGUP_ASYNCGOTO);
   } else {
      /* In order to do it when the channel doesn't really exist within
         the PBX, we have to make a new channel, masquerade, and start the PBX
         at the new location */
      struct ast_channel *tmpchan = ast_channel_alloc(0, chan->_state, 0, 0, chan->accountcode, chan->exten, chan->context, chan->amaflags, "AsyncGoto/%s", chan->name);
      if (!tmpchan) {
         res = -1;
      } else {
         if (chan->cdr) {
            ast_cdr_discard(tmpchan->cdr);
            tmpchan->cdr = ast_cdr_dup(chan->cdr);  /* share the love */
         }
         /* Make formats okay */
         tmpchan->readformat = chan->readformat;
         tmpchan->writeformat = chan->writeformat;
         /* Setup proper location */
         ast_explicit_goto(tmpchan,
            S_OR(context, chan->context), S_OR(exten, chan->exten), priority);
         /* Masquerade into temp channel */
         if (ast_channel_masquerade(tmpchan, chan)) {
            /* Failed to set up the masquerade.  It's probably chan_local
             * in the middle of optimizing itself out.  Sad. :( */
            ast_hangup(tmpchan);
            tmpchan = NULL;
            res = -1;
         } else {
            /* Grab the locks and get going */
            ast_channel_lock(tmpchan);
            ast_do_masquerade(tmpchan);
            ast_channel_unlock(tmpchan);
            /* Start the PBX going on our stolen channel */
            if (ast_pbx_start(tmpchan)) {
               ast_log(LOG_WARNING, "Unable to start PBX on %s\n", tmpchan->name);
               ast_hangup(tmpchan);
               res = -1;
            }
         }
      }
   }
   ast_channel_unlock(chan);
   return res;
}
int ast_async_goto_by_name (const char * channame, const char * context, const char * exten, int priority)
Set the channel to next execute the specified dialplan location.
Definition at line 7397 of file pbx.c.
References ast_async_goto(), ast_channel_unlock, and ast_get_channel_by_name_locked().
{
   struct ast_channel *chan;
   int res = -1;
   chan = ast_get_channel_by_name_locked(channame);
   if (chan) {
      res = ast_async_goto(chan, context, exten, priority);
      ast_channel_unlock(chan);
   }
   return res;
}
int ast_async_goto_if_exists (struct ast_channel * chan, const char * context, const char * exten, int priority)
Note:
This function will handle locking the channel as needed.
Definition at line 9575 of file pbx.c.
References __ast_goto_if_exists().
{
   return __ast_goto_if_exists(chan, context, exten, priority, 1);
}
int ast_async_parseable_goto (struct ast_channel * chan, const char * goto_string)
Note:
This function will handle locking the channel as needed.
Definition at line 9638 of file pbx.c.
References pbx_parseable_goto().
Referenced by asyncgoto_exec(), and handle_redirect().
{
   return pbx_parseable_goto(chan, goto_string, 1);
}
int ast_build_timing (struct ast_timing * i, const char * info)
Construct a timing bitmap, for use in time-based conditionals.
Parameters:
i Pointer to an ast_timing structure.
info Standard string containing a timerange, weekday range, monthday range, and month range, as well as an optional timezone.
Return values:
Returns 1 on success or 0 on failure.
Definition at line 6939 of file pbx.c.
References ast_strdup, ast_strdupa, ast_strlen_zero(), ast_timing::daymask, days, ast_timing::dowmask, get_range(), get_timerange(), ast_timing::monthmask, months, strsep(), and ast_timing::timezone.
Referenced by ast_context_add_include2(), iftime(), pbx_builtin_execiftime(), and pbx_builtin_gotoiftime().
{
   char *info_save, *info;
   int j, num_fields, last_sep = -1;
   /* Check for empty just in case */
   if (ast_strlen_zero(info_in)) {
      return 0;
   }
   /* make a copy just in case we were passed a static string */
   info_save = info = ast_strdupa(info_in);
   /* count the number of fields in the timespec */
   for (j = 0, num_fields = 1; info[j] != '\0'; j++) {
      if (info[j] == ',') {
         last_sep = j;
         num_fields++;
      }
   }
   /* save the timezone, if it is specified */
   if (num_fields == 5) {
      i->timezone = ast_strdup(info + last_sep + 1);
   } else {
      i->timezone = NULL;
   }
   /* Assume everything except time */
   i->monthmask = 0xfff;   /* 12 bits */
   i->daymask = 0x7fffffffU; /* 31 bits */
   i->dowmask = 0x7f; /* 7 bits */
   /* on each call, use strsep() to move info to the next argument */
   get_timerange(i, strsep(&info, "|,"));
   if (info)
      i->dowmask = get_range(strsep(&info, "|,"), 7, days, "day of week");
   if (info)
      i->daymask = get_range(strsep(&info, "|,"), 31, NULL, "day");
   if (info)
      i->monthmask = get_range(strsep(&info, "|,"), 12, months, "month");
   return 1;
}
int ast_canmatch_extension (struct ast_channel * c, const char * context, const char * exten, int priority, const char * callerid)
Looks for a valid matching extension.
Parameters:
c not really important
context context to serach within
exten extension to check
priority priority of extension path
callerid callerid of extension being searched for
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
Returns:
If "exten" *could be* a valid extension in this context with or without some more digits, return non-zero. Basically, when this returns 0, no matter what you add to exten, it's not going to be a valid extension anymore
Definition at line 4158 of file pbx.c.
References E_CANMATCH, and pbx_extension_helper().
Referenced by background_detect_exec(), cb_events(), do_immediate_setup(), dp_lookup(), dundi_lookup_local(), get_also_info(), get_destination(), handle_link_data(), handle_link_phone_dtmf(), leave_voicemail(), local_dtmf_helper(), loopback_canmatch(), mgcp_ss(), pbx_builtin_background(), phone_check_exception(), skinny_ss(), ss_thread(), and valid_exit().
{
   return pbx_extension_helper(c, NULL, context, exten, priority, NULL, callerid, E_CANMATCH, 0, 0);
}
static int ast_change_hint (struct ast_exten * oe, struct ast_exten * ne) [static]
Change hint for an extension.
Definition at line 4072 of file pbx.c.
References AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, and ast_hint::exten.
Referenced by add_pri_lockopt().
{
   struct ast_hint *hint;
   int res = -1;
   AST_RWLIST_WRLOCK(&hints);
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (hint->exten == oe) {
         hint->exten = ne;
         res = 0;
         break;
      }
   }
   AST_RWLIST_UNLOCK(&hints);
   return res;
}
int ast_check_timing (const struct ast_timing * i)
Evaluate a pre-constructed bitmap as to whether the current time falls within the range specified.
Parameters:
i Pointer to an ast_timing structure.
Return values:
Returns 1, if the time matches or 0, if the current time falls outside of the specified range.
Definition at line 6982 of file pbx.c.
References ast_localtime(), ast_log(), ast_tvnow(), ast_timing::daymask, ast_timing::dowmask, LOG_WARNING, ast_timing::minmask, ast_timing::monthmask, ast_timing::timezone, ast_tm::tm_hour, ast_tm::tm_mday, ast_tm::tm_min, ast_tm::tm_mon, and ast_tm::tm_wday.
Referenced by iftime(), include_valid(), pbx_builtin_execiftime(), and pbx_builtin_gotoiftime().
{
   struct ast_tm tm;
   struct timeval now = ast_tvnow();
   ast_localtime(&now, &tm, i->timezone);
   /* If it's not the right month, return */
   if (!(i->monthmask & (1 << tm.tm_mon)))
      return 0;
   /* If it's not that time of the month.... */
   /* Warning, tm_mday has range 1..31! */
   if (!(i->daymask & (1 << (tm.tm_mday-1))))
      return 0;
   /* If it's not the right day of the week */
   if (!(i->dowmask & (1 << tm.tm_wday)))
      return 0;
   /* Sanity check the hour just to be safe */
   if ((tm.tm_hour < 0) || (tm.tm_hour > 23)) {
      ast_log(LOG_WARNING, "Insane time...\n");
      return 0;
   }
   /* Now the tough part, we calculate if it fits
      in the right time based on min/hour */
   if (!(i->minmask[tm.tm_hour * 2 + (tm.tm_min >= 30 ? 1 : 0)] & (1 << (tm.tm_min >= 30 ? tm.tm_min - 30 : tm.tm_min))))
      return 0;
   /* If we got this far, then we're good */
   return 1;
}
int ast_context_add_ignorepat (const char * context, const char * ignorepat, const char * registrar)
Add an ignorepat.
Parameters:
context which context to add the ignorpattern to
ignorepat ignorepattern to set up for the extension
registrar registrar of the ignore pattern
Adds an ignore pattern to a particular context.
Return values:
0 on success
-1 on failure
Definition at line 7217 of file pbx.c.
References ast_context_add_ignorepat2(), ast_unlock_contexts(), and find_context_locked().
Referenced by handle_cli_dialplan_add_ignorepat().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) {
      ret = ast_context_add_ignorepat2(c, value, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_add_ignorepat2 (struct ast_context * con, const char * value, const char * registrar)
Definition at line 7229 of file pbx.c.
References ast_calloc, ast_unlock_context(), ast_wrlock_context(), errno, ast_context::ignorepats, ast_ignorepat::next, ast_ignorepat::pattern, and ast_ignorepat::registrar.
Referenced by ast_compile_ael2(), ast_context_add_ignorepat(), context_merge_incls_swits_igps_other_registrars(), and pbx_load_config().
{
   struct ast_ignorepat *ignorepat, *ignorepatc, *ignorepatl = NULL;
   int length;
   char *pattern;
   length = sizeof(struct ast_ignorepat);
   length += strlen(value) + 1;
   if (!(ignorepat = ast_calloc(1, length)))
      return -1;
   /* The cast to char * is because we need to write the initial value.
    * The field is not supposed to be modified otherwise.  Also, gcc 4.2
    * sees the cast as dereferencing a type-punned pointer and warns about
    * it.  This is the workaround (we're telling gcc, yes, that's really
    * what we wanted to do).
    */
   pattern = (char *) ignorepat->pattern;
   strcpy(pattern, value);
   ignorepat->next = NULL;
   ignorepat->registrar = registrar;
   ast_wrlock_context(con);
   for (ignorepatc = con->ignorepats; ignorepatc; ignorepatc = ignorepatc->next) {
      ignorepatl = ignorepatc;
      if (!strcasecmp(ignorepatc->pattern, value)) {
         /* Already there */
         ast_unlock_context(con);
         errno = EEXIST;
         return -1;
      }
   }
   if (ignorepatl)
      ignorepatl->next = ignorepat;
   else
      con->ignorepats = ignorepat;
   ast_unlock_context(con);
   return 0;
}
int ast_context_add_include (const char * context, const char * include, const char * registrar)
Add a context include.
Parameters:
context context to add include to
include new include to add
registrar who's registering it
Adds an include taking a char * string as the context parameter
Return values:
0 on success
-1 on error
Definition at line 6768 of file pbx.c.
References ast_context_add_include2(), ast_unlock_contexts(), and find_context_locked().
Referenced by handle_cli_dialplan_add_include().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) {
      ret = ast_context_add_include2(c, include, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_add_include2 (struct ast_context * con, const char * include, const char * registrar)
Add a context include.
Parameters:
con context to add the include to
include include to add
registrar who registered the context
Adds an include taking a struct ast_context as the first parameter
Return values:
0 on success
-1 on failure
Definition at line 7032 of file pbx.c.
References ast_build_timing(), ast_calloc, ast_destroy_timing(), ast_free, ast_get_context_name(), ast_unlock_context(), ast_verb, ast_wrlock_context(), errno, ast_include::hastime, ast_context::includes, ast_include::name, ast_include::next, ast_include::registrar, ast_include::rname, ast_include::stuff, and ast_include::timing.
Referenced by ast_compile_ael2(), ast_context_add_include(), context_merge_incls_swits_igps_other_registrars(), and pbx_load_config().
{
   struct ast_include *new_include;
   char *c;
   struct ast_include *i, *il = NULL; /* include, include_last */
   int length;
   char *p;
   length = sizeof(struct ast_include);
   length += 2 * (strlen(value) + 1);
   /* allocate new include structure ... */
   if (!(new_include = ast_calloc(1, length)))
      return -1;
   /* Fill in this structure. Use 'p' for assignments, as the fields
    * in the structure are 'const char *'
    */
   p = new_include->stuff;
   new_include->name = p;
   strcpy(p, value);
   p += strlen(value) + 1;
   new_include->rname = p;
   strcpy(p, value);
   /* Strip off timing info, and process if it is there */
   if ( (c = strchr(p, ',')) ) {
      *c++ = '\0';
      new_include->hastime = ast_build_timing(&(new_include->timing), c);
   }
   new_include->next      = NULL;
   new_include->registrar = registrar;
   ast_wrlock_context(con);
   /* ... go to last include and check if context is already included too... */
   for (i = con->includes; i; i = i->next) {
      if (!strcasecmp(i->name, new_include->name)) {
         ast_destroy_timing(&(new_include->timing));
         ast_free(new_include);
         ast_unlock_context(con);
         errno = EEXIST;
         return -1;
      }
      il = i;
   }
   /* ... include new context into context list, unlock, return */
   if (il)
      il->next = new_include;
   else
      con->includes = new_include;
   ast_verb(3, "Including context '%s' in context '%s'\n", new_include->name, ast_get_context_name(con));
   ast_unlock_context(con);
   return 0;
}
int ast_context_add_switch (const char * context, const char * sw, const char * data, int eval, const char * registrar)
Add a switch.
Parameters:
context context to which to add the switch
sw switch to add
data data to pass to switch
eval whether to evaluate variables when running switch
registrar whoever registered the switch
This function registers a switch with the asterisk switch architecture
Return values:
0 on success
-1 on failure
Definition at line 7095 of file pbx.c.
References ast_context_add_switch2(), ast_unlock_contexts(), and find_context_locked().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) { /* found, add switch to this context */
      ret = ast_context_add_switch2(c, sw, data, eval, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_add_switch2 (struct ast_context * con, const char * sw, const char * data, int eval, const char * registrar)
Adds a switch (first param is a ast_context).
Note:
See ast_context_add_switch() for argument information, with the exception of the first argument. In this case, it's a pointer to an ast_context structure as opposed to the name.
Definition at line 7114 of file pbx.c.
References ast_context::alts, ast_calloc, ast_free, ast_get_context_name(), AST_LIST_INSERT_TAIL, AST_LIST_TRAVERSE, ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_sw::data, errno, ast_sw::eval, ast_sw::name, ast_sw::registrar, and ast_sw::stuff.
Referenced by ast_compile_ael2(), ast_context_add_switch(), context_merge_incls_swits_igps_other_registrars(), lua_register_switches(), and pbx_load_config().
{
   struct ast_sw *new_sw;
   struct ast_sw *i;
   int length;
   char *p;
   length = sizeof(struct ast_sw);
   length += strlen(value) + 1;
   if (data)
      length += strlen(data);
   length++;
   /* allocate new sw structure ... */
   if (!(new_sw = ast_calloc(1, length)))
      return -1;
   /* ... fill in this structure ... */
   p = new_sw->stuff;
   new_sw->name = p;
   strcpy(new_sw->name, value);
   p += strlen(value) + 1;
   new_sw->data = p;
   if (data) {
      strcpy(new_sw->data, data);
      p += strlen(data) + 1;
   } else {
      strcpy(new_sw->data, "");
      p++;
   }
   new_sw->eval     = eval;
   new_sw->registrar = registrar;
   /* ... try to lock this context ... */
   ast_wrlock_context(con);
   /* ... go to last sw and check if context is already swd too... */
   AST_LIST_TRAVERSE(&con->alts, i, list) {
      if (!strcasecmp(i->name, new_sw->name) && !strcasecmp(i->data, new_sw->data)) {
         ast_free(new_sw);
         ast_unlock_context(con);
         errno = EEXIST;
         return -1;
      }
   }
   /* ... sw new context into context list, unlock, return */
   AST_LIST_INSERT_TAIL(&con->alts, new_sw, list);
   ast_verb(3, "Including switch '%s/%s' in context '%s'\n", new_sw->name, new_sw->data, ast_get_context_name(con));
   ast_unlock_context(con);
   return 0;
}
void ast_context_destroy (struct ast_context * con, const char * registrar)
Destroy a context (matches the specified context (or ANY context if NULL).
Parameters:
con context to destroy
registrar who registered it
You can optionally leave out either parameter. It will find it based on either the ast_context or the registrar name.
Returns:
nothing
Definition at line 8415 of file pbx.c.
References __ast_context_destroy(), ast_unlock_contexts(), ast_wrlock_contexts(), contexts, and contexts_table.
Referenced by __unload_module(), cleanup_stale_contexts(), parkinglot_destroy(), sla_destroy(), and unload_module().
{
   ast_wrlock_contexts();
   __ast_context_destroy(contexts, contexts_table, con,registrar);
   ast_unlock_contexts();
}
struct ast_context* ast_context_find (const char * name) [read]
Find a context.
Parameters:
name name of the context to find
Will search for the context with the given name.
Returns:
the ast_context on success, NULL on failure.
Definition at line 2430 of file pbx.c.
References ast_copy_string(), ast_hashtab_lookup(), ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_contexts(), contexts_table, ast_context::name, and fake_context::name.
Referenced by __unload_module(), _macro_exec(), ast_context_verify_includes(), ast_ignore_pattern(), cleanup_stale_contexts(), isexten_function_read(), load_config(), manage_parkinglot(), park_exec_full(), parkinglot_destroy(), register_exten(), register_peer_exten(), unload_module(), and unregister_exten().
{
   struct ast_context *tmp = NULL;
   struct fake_context item;
   ast_copy_string(item.name, name, sizeof(item.name));
   ast_rdlock_contexts();
   if( contexts_table ) {
      tmp = ast_hashtab_lookup(contexts_table,&item);
   } else {
      while ( (tmp = ast_walk_contexts(tmp)) ) {
         if (!name || !strcasecmp(name, tmp->name)) {
            break;
         }
      }
   }
   ast_unlock_contexts();
   return tmp;
}
struct ast_context* ast_context_find_or_create (struct ast_context ** extcontexts, struct ast_hashtab * exttable, const char * name, const char * registrar) [read]
Register a new context or find an existing one.
Parameters:
extcontexts pointer to the ast_context structure pointer
exttable pointer to the hashtable that contains all the elements in extcontexts
name name of the new context
registrar registrar of the context
This function allows you to play in two environments: the global contexts (active dialplan) or an external context set of your choosing. To act on the external set, make sure extcontexts and exttable are set; for the globals, make sure both extcontexts and exttable are NULL.
This will first search for a context with your name. If it exists already, it will not create a new one. If it does not exist, it will create a new one with the given name and registrar.
Returns:
NULL on failure, and an ast_context structure on success
Definition at line 6424 of file pbx.c.
References ast_calloc, ast_copy_string(), ast_debug, ast_hashtab_compare_contexts(), ast_hashtab_create(), ast_hashtab_hash_contexts(), ast_hashtab_insert_immediate(), ast_hashtab_insert_safe(), ast_hashtab_lookup(), ast_hashtab_newsize_java(), ast_hashtab_resize_java(), ast_log(), ast_mutex_init(), ast_rdlock_contexts(), ast_rwlock_init(), ast_strdup, ast_unlock_contexts(), ast_verb, ast_wrlock_contexts(), contexts, contexts_table, ast_context::ignorepats, ast_context::includes, local_contexts, ast_context::lock, LOG_ERROR, ast_context::macrolock, ast_context::name, fake_context::name, ast_context::next, ast_context::refcount, ast_context::registrar, ast_context::root, and ast_context::root_table.
Referenced by ast_compile_ael2(), build_parkinglot(), config_parse_variables(), context_merge(), load_config(), load_module(), lua_register_switches(), manage_parkinglot(), park_call_full(), pbx_load_config(), pbx_load_users(), reload_config(), set_config(), sla_build_station(), and sla_build_trunk().
{
   struct ast_context *tmp, **local_contexts;
   struct fake_context search;
   int length = sizeof(struct ast_context) + strlen(name) + 1;
   if (!contexts_table) {
      contexts_table = ast_hashtab_create(17,
                                 ast_hashtab_compare_contexts,
                                 ast_hashtab_resize_java,
                                 ast_hashtab_newsize_java,
                                 ast_hashtab_hash_contexts,
                                 0);
   }
   ast_copy_string(search.name, name, sizeof(search.name));
   if (!extcontexts) {
      ast_rdlock_contexts();
      local_contexts = &contexts;
      tmp = ast_hashtab_lookup(contexts_table, &search);
      ast_unlock_contexts();
      if (tmp) {
         tmp->refcount++;
         return tmp;
      }
   } else { /* local contexts just in a linked list; search there for the new context; slow, linear search, but not frequent */
      local_contexts = extcontexts;
      tmp = ast_hashtab_lookup(exttable, &search);
      if (tmp) {
         tmp->refcount++;
         return tmp;
      }
   }
   if ((tmp = ast_calloc(1, length))) {
      ast_rwlock_init(&tmp->lock);
      ast_mutex_init(&tmp->macrolock);
      strcpy(tmp->name, name);
      tmp->root = NULL;
      tmp->root_table = NULL;
      tmp->registrar = ast_strdup(registrar);
      tmp->includes = NULL;
      tmp->ignorepats = NULL;
      tmp->refcount = 1;
   } else {
      ast_log(LOG_ERROR, "Danger! We failed to allocate a context for %s!\n", name);
      return NULL;
   }
   if (!extcontexts) {
      ast_wrlock_contexts();
      tmp->next = *local_contexts;
      *local_contexts = tmp;
      ast_hashtab_insert_safe(contexts_table, tmp); /*put this context into the tree */
      ast_unlock_contexts();
      ast_debug(1, "Registered context '%s'(%p) in table %p registrar: %s\n", tmp->name, tmp, contexts_table, registrar);
      ast_verb(3, "Registered extension context '%s' (%p) in table %p; registrar: %s\n", tmp->name, tmp, contexts_table, registrar);
   } else {
      tmp->next = *local_contexts;
      if (exttable)
         ast_hashtab_insert_immediate(exttable, tmp); /*put this context into the tree */
      *local_contexts = tmp;
      ast_debug(1, "Registered context '%s'(%p) in local table %p; registrar: %s\n", tmp->name, tmp, exttable, registrar);
      ast_verb(3, "Registered extension context '%s' (%p) in local table %p; registrar: %s\n", tmp->name, tmp, exttable, registrar);
   }
   return tmp;
}
int ast_context_lockmacro (const char * context)
locks the macrolock in the given given context
Note:
This function locks contexts list by &conlist, searches for the right context structure, and locks the macrolock mutex in that context. macrolock is used to limit a macro to be executed by one call at a time.
Definition at line 4988 of file pbx.c.
References ast_copy_string(), ast_get_context_name(), ast_hashtab_lookup(), ast_mutex_lock(), ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_contexts(), contexts_table, ast_context::macrolock, and fake_context::name.
Referenced by _macro_exec().
{
   struct ast_context *c = NULL;
   int ret = -1;
   struct fake_context item;
   ast_rdlock_contexts();
   ast_copy_string(item.name, context, sizeof(item.name));
   c = ast_hashtab_lookup(contexts_table,&item);
   if (c)
      ret = 0;
#ifdef NOTNOW
   while ((c = ast_walk_contexts(c))) {
      if (!strcmp(ast_get_context_name(c), context)) {
         ret = 0;
         break;
      }
   }
#endif
   ast_unlock_contexts();
   /* if we found context, lock macrolock */
   if (ret == 0) {
      ret = ast_mutex_lock(&c->macrolock);
   }
   return ret;
}
int ast_context_remove_extension (const char * context, const char * extension, int priority, const char * registrar)
Simply remove extension from context.
Parameters:
context context to remove extension from
extension which extension to remove
priority priority of extension to remove (0 to remove all)
callerid NULL to remove all; non-NULL to match a single record per priority
matchcid non-zero to match callerid element (if non-NULL); 0 to match default case
registrar registrar of the extension
This function removes an extension from a given context.
Return values:
0 on success
-1 on failure
Definition at line 4796 of file pbx.c.
References ast_context_remove_extension_callerid().
Referenced by destroy_station(), destroy_trunk(), register_peer_exten(), unregister_exten(), and UnregisterExtension().
{
   return ast_context_remove_extension_callerid(context, extension, priority, NULL, 0, registrar);
}
int ast_context_remove_extension2 (struct ast_context * con, const char * extension, int priority, const char * registrar, int already_locked)
This functionc locks given context, search for the right extension and fires out all peer in this extensions with given priority. If priority is set to 0, all peers are removed. After that, unlock context and return.
Note:
When do you want to call this function, make sure that &conlock is locked, because some process can handle with your *con context before you lock it.
Definition at line 4823 of file pbx.c.
References ast_context_remove_extension_callerid2().
Referenced by load_config(), manage_parkinglot(), park_exec_full(), and unload_module().
{
   return ast_context_remove_extension_callerid2(con, extension, priority, NULL, 0, registrar, already_locked);
}
int ast_context_remove_extension_callerid (const char * context, const char * extension, int priority, const char * callerid, int matchcallerid, const char * registrar)
Definition at line 4801 of file pbx.c.
References ast_context_remove_extension_callerid2(), ast_unlock_contexts(), and find_context_locked().
Referenced by ast_context_remove_extension(), and handle_cli_dialplan_remove_extension().
{
   int ret = -1; /* default error return */
   struct ast_context *c = find_context_locked(context);
   if (c) { /* ... remove extension ... */
      ret = ast_context_remove_extension_callerid2(c, extension, priority, callerid, matchcallerid, registrar, 1);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_remove_extension_callerid2 (struct ast_context * con, const char * extension, int priority, const char * callerid, int matchcallerid, const char * registrar, int already_locked)
Definition at line 4828 of file pbx.c.
References add_exten_to_pattern_tree(), ast_copy_string(), ast_hashtab_insert_immediate(), ast_hashtab_lookup(), ast_hashtab_remove_this_object(), ast_hashtab_size(), ast_log(), ast_strlen_zero(), ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_exten::cidmatch, match_char::deleted, destroy_exten(), match_char::exten, ast_exten::exten, ast_exten::label, LOG_ERROR, log_match_char_tree(), LOG_NOTICE, LOG_WARNING, ast_exten::matchcid, ast_context::name, ast_exten::next, ast_context::pattern_tree, ast_exten::peer, ast_exten::peer_label_table, ast_exten::peer_table, ast_exten::priority, ast_exten::registrar, ast_context::root, ast_context::root_table, and match_char::x.
Referenced by __ast_context_destroy(), ast_context_remove_extension2(), and ast_context_remove_extension_callerid().
{
   struct ast_exten *exten, *prev_exten = NULL;
   struct ast_exten *peer;
   struct ast_exten ex, *exten2, *exten3;
   char dummy_name[1024];
   struct ast_exten *previous_peer = NULL;
   struct ast_exten *next_peer = NULL;
   int found = 0;
   if (!already_locked)
      ast_wrlock_context(con);
   /* Handle this is in the new world */
   /* FIXME For backwards compatibility, if callerid==NULL, then remove ALL
    * peers, not just those matching the callerid. */
#ifdef NEED_DEBUG
   ast_verb(3,"Removing %s/%s/%d%s%s from trees, registrar=%s\n", con->name, extension, priority, matchcallerid ? "/" : "", matchcallerid ? callerid : "", registrar);
#endif
#ifdef CONTEXT_DEBUG
   check_contexts(__FILE__, __LINE__);
#endif
   /* find this particular extension */
   ex.exten = dummy_name;
   ex.matchcid = matchcallerid && !ast_strlen_zero(callerid); /* don't say match if there's no callerid */
   ex.cidmatch = callerid;
   ast_copy_string(dummy_name, extension, sizeof(dummy_name));
   exten = ast_hashtab_lookup(con->root_table, &ex);
   if (exten) {
      if (priority == 0) {
         exten2 = ast_hashtab_remove_this_object(con->root_table, exten);
         if (!exten2)
            ast_log(LOG_ERROR,"Trying to delete the exten %s from context %s, but could not remove from the root_table\n", extension, con->name);
         if (con->pattern_tree) {
            struct match_char *x = add_exten_to_pattern_tree(con, exten, 1);
            if (x->exten) { /* this test for safety purposes */
               x->deleted = 1; /* with this marked as deleted, it will never show up in the scoreboard, and therefore never be found */
               x->exten = 0; /* get rid of what will become a bad pointer */
            } else {
               ast_log(LOG_WARNING,"Trying to delete an exten from a context, but the pattern tree node returned isn't a full extension\n");
            }
         }
      } else {
         ex.priority = priority;
         exten2 = ast_hashtab_lookup(exten->peer_table, &ex);
         if (exten2) {
            if (exten2->label) { /* if this exten has a label, remove that, too */
               exten3 = ast_hashtab_remove_this_object(exten->peer_label_table,exten2);
               if (!exten3)
                  ast_log(LOG_ERROR,"Did not remove this priority label (%d/%s) from the peer_label_table of context %s, extension %s!\n", priority, exten2->label, con->name, exten2->exten);
            }
            exten3 = ast_hashtab_remove_this_object(exten->peer_table, exten2);
            if (!exten3)
               ast_log(LOG_ERROR,"Did not remove this priority (%d) from the peer_table of context %s, extension %s!\n", priority, con->name, exten2->exten);
            if (exten2 == exten && exten2->peer) {
               exten2 = ast_hashtab_remove_this_object(con->root_table, exten);
               ast_hashtab_insert_immediate(con->root_table, exten2->peer);
            }
            if (ast_hashtab_size(exten->peer_table) == 0) {
               /* well, if the last priority of an exten is to be removed,
                  then, the extension is removed, too! */
               exten3 = ast_hashtab_remove_this_object(con->root_table, exten);
               if (!exten3)
                  ast_log(LOG_ERROR,"Did not remove this exten (%s) from the context root_table (%s) (priority %d)\n", exten->exten, con->name, priority);
               if (con->pattern_tree) {
                  struct match_char *x = add_exten_to_pattern_tree(con, exten, 1);
                  if (x->exten) { /* this test for safety purposes */
                     x->deleted = 1; /* with this marked as deleted, it will never show up in the scoreboard, and therefore never be found */
                     x->exten = 0; /* get rid of what will become a bad pointer */
                  }
               }
            }
         } else {
            ast_log(LOG_ERROR,"Could not find priority %d of exten %s in context %s!\n",
                  priority, exten->exten, con->name);
         }
      }
   } else {
      /* hmmm? this exten is not in this pattern tree? */
      ast_log(LOG_WARNING,"Cannot find extension %s in root_table in context %s\n",
            extension, con->name);
   }
#ifdef NEED_DEBUG
   if (con->pattern_tree) {
      ast_log(LOG_NOTICE,"match char tree after exten removal:\n");
      log_match_char_tree(con->pattern_tree, " ");
   }
#endif
   /* scan the extension list to find first matching extension-registrar */
   for (exten = con->root; exten; prev_exten = exten, exten = exten->next) {
      if (!strcmp(exten->exten, extension) &&
         (!registrar || !strcmp(exten->registrar, registrar)) &&
         (!matchcallerid || (!ast_strlen_zero(callerid) && !ast_strlen_zero(exten->cidmatch) && !strcmp(exten->cidmatch, callerid)) || (ast_strlen_zero(callerid) && ast_strlen_zero(exten->cidmatch))))
         break;
   }
   if (!exten) {
      /* we can't find right extension */
      if (!already_locked)
         ast_unlock_context(con);
      return -1;
   }
   /* scan the priority list to remove extension with exten->priority == priority */
   for (peer = exten, next_peer = exten->peer ? exten->peer : exten->next;
       peer && !strcmp(peer->exten, extension) && (!matchcallerid || (!ast_strlen_zero(callerid) && !ast_strlen_zero(peer->cidmatch) && !strcmp(peer->cidmatch,callerid)) || (ast_strlen_zero(callerid) && ast_strlen_zero(peer->cidmatch)));
         peer = next_peer, next_peer = next_peer ? (next_peer->peer ? next_peer->peer : next_peer->next) : NULL) {
      if ((priority == 0 || peer->priority == priority) &&
            (!callerid || !matchcallerid || (matchcallerid && !strcmp(peer->cidmatch, callerid))) &&
            (!registrar || !strcmp(peer->registrar, registrar) )) {
         found = 1;
         /* we are first priority extension? */
         if (!previous_peer) {
            /*
             * We are first in the priority chain, so must update the extension chain.
             * The next node is either the next priority or the next extension
             */
            struct ast_exten *next_node = peer->peer ? peer->peer : peer->next;
            if (peer->peer) {
               /* move the peer_table and peer_label_table down to the next peer, if
                  it is there */
               peer->peer->peer_table = peer->peer_table;
               peer->peer->peer_label_table = peer->peer_label_table;
               peer->peer_table = NULL;
               peer->peer_label_table = NULL;
            }
            if (!prev_exten) {   /* change the root... */
               con->root = next_node;
            } else {
               prev_exten->next = next_node; /* unlink */
            }
            if (peer->peer)   { /* update the new head of the pri list */
               peer->peer->next = peer->next;
            }
         } else { /* easy, we are not first priority in extension */
            previous_peer->peer = peer->peer;
         }
         /* now, free whole priority extension */
         destroy_exten(peer);
      } else {
         previous_peer = peer;
      }
   }
   if (!already_locked)
      ast_unlock_context(con);
   return found ? 0 : -1;
}
int ast_context_remove_ignorepat (const char * context, const char * ignorepat, const char * registrar)
Definition at line 7174 of file pbx.c.
References ast_context_remove_ignorepat2(), ast_unlock_contexts(), and find_context_locked().
Referenced by handle_cli_dialplan_remove_ignorepat().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) {
      ret = ast_context_remove_ignorepat2(c, ignorepat, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_remove_ignorepat2 (struct ast_context * con, const char * ignorepat, const char * registrar)
Definition at line 7186 of file pbx.c.
References ast_free, ast_unlock_context(), ast_wrlock_context(), errno, ast_context::ignorepats, ast_ignorepat::next, ast_ignorepat::pattern, and ast_ignorepat::registrar.
Referenced by ast_context_remove_ignorepat().
{
   struct ast_ignorepat *ip, *ipl = NULL;
   ast_wrlock_context(con);
   for (ip = con->ignorepats; ip; ip = ip->next) {
      if (!strcmp(ip->pattern, ignorepat) &&
         (!registrar || (registrar == ip->registrar))) {
         if (ipl) {
            ipl->next = ip->next;
            ast_free(ip);
         } else {
            con->ignorepats = ip->next;
            ast_free(ip);
         }
         ast_unlock_context(con);
         return 0;
      }
      ipl = ip;
   }
   ast_unlock_context(con);
   errno = EINVAL;
   return -1;
}
int ast_context_remove_include (const char * context, const char * include, const char * registrar)
Remove included contexts. This function locks contexts list by &conlist, search for the right context structure, leave context list locked and call ast_context_remove_include2 which removes include, unlock contexts list and return ...
Remove a context include.
Definition at line 4687 of file pbx.c.
References ast_context_remove_include2(), ast_unlock_contexts(), and find_context_locked().
Referenced by handle_cli_dialplan_remove_include().
{
   int ret = -1;
   struct ast_context *c = find_context_locked(context);
   if (c) {
      /* found, remove include from this context ... */
      ret = ast_context_remove_include2(c, include, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_remove_include2 (struct ast_context * con, const char * include, const char * registrar)
Locks context, remove included contexts, unlocks context. When we call this function, &conlock lock must be locked, because when we giving *con argument, some process can remove/change this context and after that there can be segfault.
Removes an include by an ast_context structure.
Return values:
0 on success.
-1 on failure.
Definition at line 4709 of file pbx.c.
References ast_destroy_timing(), ast_free, ast_get_context_name(), ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_context::includes, ast_include::name, ast_include::next, ast_include::registrar, and ast_include::timing.
Referenced by ast_context_remove_include().
{
   struct ast_include *i, *pi = NULL;
   int ret = -1;
   ast_wrlock_context(con);
   /* find our include */
   for (i = con->includes; i; pi = i, i = i->next) {
      if (!strcmp(i->name, include) &&
            (!registrar || !strcmp(i->registrar, registrar))) {
         /* remove from list */
         ast_verb(3, "Removing inclusion of context '%s' in context '%s; registrar=%s'\n", include, ast_get_context_name(con), registrar);
         if (pi)
            pi->next = i->next;
         else
            con->includes = i->next;
         /* free include and return */
         ast_destroy_timing(&(i->timing));
         ast_free(i);
         ret = 0;
         break;
      }
   }
   ast_unlock_context(con);
   return ret;
}
int ast_context_remove_switch (const char * context, const char * sw, const char * data, const char * registrar)
Remove a switch.
Note:
This function locks contexts list by &conlist, search for the rigt context structure, leave context list locked and call ast_context_remove_switch2 which removes switch, unlock contexts list and return ...
Definition at line 4744 of file pbx.c.
References ast_context_remove_switch2(), ast_unlock_contexts(), and find_context_locked().
{
   int ret = -1; /* default error return */
   struct ast_context *c = find_context_locked(context);
   if (c) {
      /* remove switch from this context ... */
      ret = ast_context_remove_switch2(c, sw, data, registrar);
      ast_unlock_contexts();
   }
   return ret;
}
int ast_context_remove_switch2 (struct ast_context * con, const char * sw, const char * data, const char * registrar)
This function locks given context, removes switch, unlock context and return.
Note:
When we call this function, &conlock lock must be locked, because when we giving *con argument, some process can remove/change this context and after that there can be segfault.
Definition at line 4765 of file pbx.c.
References ast_context::alts, ast_free, ast_get_context_name(), AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_unlock_context(), ast_verb, ast_wrlock_context(), ast_sw::data, ast_sw::name, and ast_sw::registrar.
Referenced by ast_context_remove_switch().
{
   struct ast_sw *i;
   int ret = -1;
   ast_wrlock_context(con);
   /* walk switches */
   AST_LIST_TRAVERSE_SAFE_BEGIN(&con->alts, i, list) {
      if (!strcmp(i->name, sw) && !strcmp(i->data, data) &&
         (!registrar || !strcmp(i->registrar, registrar))) {
         /* found, remove from list */
         ast_verb(3, "Removing switch '%s' from context '%s; registrar=%s'\n", sw, ast_get_context_name(con), registrar);
         AST_LIST_REMOVE_CURRENT(list);
         ast_free(i); /* free switch and return */
         ret = 0;
         break;
      }
   }
   AST_LIST_TRAVERSE_SAFE_END;
   ast_unlock_context(con);
   return ret;
}
int ast_context_unlockmacro (const char * context)
Unlocks the macrolock in the given context.
Note:
This function locks contexts list by &conlist, searches for the right context structure, and unlocks the macrolock mutex in that context. macrolock is used to limit a macro to be executed by one call at a time.
Definition at line 5028 of file pbx.c.
References ast_copy_string(), ast_get_context_name(), ast_hashtab_lookup(), ast_mutex_unlock(), ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_contexts(), contexts_table, ast_context::macrolock, and fake_context::name.
Referenced by _macro_exec().
{
   struct ast_context *c = NULL;
   int ret = -1;
   struct fake_context item;
   ast_rdlock_contexts();
   ast_copy_string(item.name, context, sizeof(item.name));
   c = ast_hashtab_lookup(contexts_table,&item);
   if (c)
      ret = 0;
#ifdef NOTNOW
   while ((c = ast_walk_contexts(c))) {
      if (!strcmp(ast_get_context_name(c), context)) {
         ret = 0;
         break;
      }
   }
#endif
   ast_unlock_contexts();
   /* if we found context, unlock macrolock */
   if (ret == 0) {
      ret = ast_mutex_unlock(&c->macrolock);
   }
   return ret;
}
int ast_context_verify_includes (struct ast_context * con)
Verifies includes in an ast_contect structure.
Parameters:
con context in which to verify the includes
Return values:
0 if no problems found
-1 if there were any missing context
Definition at line 9532 of file pbx.c.
References ast_context_find(), ast_get_context_name(), ast_log(), ast_walk_context_includes(), LOG_WARNING, and ast_include::rname.
Referenced by pbx_load_module().
{
   struct ast_include *inc = NULL;
   int res = 0;
   while ( (inc = ast_walk_context_includes(con, inc)) ) {
      if (ast_context_find(inc->rname))
         continue;
      res = -1;
      ast_log(LOG_WARNING, "Context '%s' tries to include nonexistent context '%s'\n",
         ast_get_context_name(con), inc->rname);
      break;
   }
   return res;
}
struct ast_custom_function* ast_custom_function_find (const char * name) [read]
Definition at line 3202 of file pbx.c.
References ast_custom_function::acflist, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, and ast_custom_function::name.
Referenced by ast_func_read(), ast_func_write(), config_curl(), destroy_curl(), handle_show_function(), op_func(), realtime_curl(), realtime_multi_curl(), require_curl(), store_curl(), update2_curl(), and update_curl().
{
   struct ast_custom_function *acf = NULL;
   AST_RWLIST_RDLOCK(&acf_root);
   AST_RWLIST_TRAVERSE(&acf_root, acf, acflist) {
      if (!strcmp(name, acf->name))
         break;
   }
   AST_RWLIST_UNLOCK(&acf_root);
   return acf;
}
int ast_custom_function_unregister (struct ast_custom_function * acf)
Unregister a custom function.
Definition at line 3216 of file pbx.c.
References ast_custom_function::acflist, AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_string_field_free_memory, ast_verb, AST_XML_DOC, ast_custom_function::docsrc, and ast_custom_function::name.
Referenced by load_module(), reload(), and unload_module().
{
   struct ast_custom_function *cur;
   if (!acf) {
      return -1;
   }
   AST_RWLIST_WRLOCK(&acf_root);
   if ((cur = AST_RWLIST_REMOVE(&acf_root, acf, acflist))) {
      if (cur->docsrc == AST_XML_DOC) {
         ast_string_field_free_memory(acf);
      }
      ast_verb(2, "Unregistered custom function %s\n", cur->name);
   }
   AST_RWLIST_UNLOCK(&acf_root);
   return cur ? 0 : -1;
}
int ast_destroy_timing (struct ast_timing * i)
Deallocates memory structures associated with a timing bitmap.
Parameters:
i Pointer to an ast_timing structure.
Return values:
0 success
non-zero failure (number suitable to pass to
See also:
strerror)
Definition at line 7017 of file pbx.c.
References ast_free, and ast_timing::timezone.
Referenced by ast_context_add_include2(), ast_context_remove_include2(), iftime(), pbx_builtin_execiftime(), and pbx_builtin_gotoiftime().
{
   if (i->timezone) {
      ast_free(i->timezone);
      i->timezone = NULL;
   }
   return 0;
}
enum ast_extension_states ast_devstate_to_extenstate (enum ast_device_state devstate)
Map devstate to an extension state.
Parameters:
[in] device state
Returns:
the extension state mapping.
Definition at line 3770 of file pbx.c.
References AST_DEVICE_BUSY, AST_DEVICE_INUSE, AST_DEVICE_INVALID, AST_DEVICE_NOT_INUSE, AST_DEVICE_ONHOLD, AST_DEVICE_RINGING, AST_DEVICE_RINGINUSE, AST_DEVICE_TOTAL, AST_DEVICE_UNAVAILABLE, AST_DEVICE_UNKNOWN, AST_EXTENSION_BUSY, AST_EXTENSION_INUSE, AST_EXTENSION_NOT_INUSE, AST_EXTENSION_ONHOLD, AST_EXTENSION_RINGING, and AST_EXTENSION_UNAVAILABLE.
Referenced by ast_extension_state2().
{
   switch (devstate) {
   case AST_DEVICE_ONHOLD:
      return AST_EXTENSION_ONHOLD;
   case AST_DEVICE_BUSY:
      return AST_EXTENSION_BUSY;
   case AST_DEVICE_UNAVAILABLE:
   case AST_DEVICE_UNKNOWN:
   case AST_DEVICE_INVALID:
      return AST_EXTENSION_UNAVAILABLE;
   case AST_DEVICE_RINGINUSE:
      return (AST_EXTENSION_INUSE | AST_EXTENSION_RINGING);
   case AST_DEVICE_RINGING:
      return AST_EXTENSION_RINGING;
   case AST_DEVICE_INUSE:
      return AST_EXTENSION_INUSE;
   case AST_DEVICE_NOT_INUSE:
      return AST_EXTENSION_NOT_INUSE;
   case AST_DEVICE_TOTAL: /* not a device state, included for completeness */
      break;
   }
   return AST_EXTENSION_NOT_INUSE;
}
int ast_exists_extension (struct ast_channel * c, const char * context, const char * exten, int priority, const char * callerid)
Determine whether an extension exists.
Parameters:
c this is not important
context which context to look in
exten which extension to search for
priority priority of the action within the extension
callerid callerid to search for
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
Returns:
If an extension within the given context(or callerid) with the given priority is found a non zero value will be returned. Otherwise, 0 is returned.
Definition at line 4143 of file pbx.c.
References E_MATCH, and pbx_extension_helper().
Referenced by __ast_goto_if_exists(), __ast_pbx_run(), _macro_exec(), acf_isexten_exec(), answer_call(), ast_app_dtget(), ast_bridge_call(), ast_pbx_outgoing_exten(), builtin_atxfer(), builtin_blindtransfer(), cb_events(), cli_console_dial(), conf_run(), console_dial(), console_transfer(), dahdi_handle_dtmfup(), dial_exec_full(), disa_exec(), dp_lookup(), dundi_lookup_local(), get_also_info(), get_destination(), get_refer_info(), gosub_exec(), handle_gosub(), handle_link_data(), handle_link_phone_dtmf(), handle_stimulus_message(), isexten_function_read(), leave_voicemail(), local_alloc(), local_call(), local_devicestate(), local_dtmf_helper(), loopback_exists(), metermaidstate(), mgcp_ss(), minivm_greet_exec(), misdn_overlap_dial_task(), park_space_reserve(), parkandannounce_exec(), pbx_builtin_waitexten(), phone_check_exception(), privacy_exec(), process_ast_dsp(), readexten_exec(), register_peer_exten(), rpt_exec(), show_debug_helper(), sip_read(), skinny_ss(), socket_process(), ss_thread(), and waitstream_core().
{
   return pbx_extension_helper(c, NULL, context, exten, priority, NULL, callerid, E_MATCH, 0, 0);
}
int ast_explicit_goto (struct ast_channel * chan, const char * context, const char * exten, int priority)
Note:
This function will handle locking the channel as needed.
Definition at line 7321 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, ast_copy_string(), AST_FLAG_IN_AUTOLOOP, ast_strlen_zero(), ast_test_flag, ast_channel::context, ast_channel::exten, and ast_channel::priority.
Referenced by __ast_goto_if_exists(), ast_async_goto(), builtin_atxfer(), disa_exec(), do_bridge_masquerade(), handle_setpriority(), pbx_parseable_goto(), and return_exec().
{
   if (!chan)
      return -1;
   ast_channel_lock(chan);
   if (!ast_strlen_zero(context))
      ast_copy_string(chan->context, context, sizeof(chan->context));
   if (!ast_strlen_zero(exten))
      ast_copy_string(chan->exten, exten, sizeof(chan->exten));
   if (priority > -1) {
      chan->priority = priority;
      /* see flag description in channel.h for explanation */
      if (ast_test_flag(chan, AST_FLAG_IN_AUTOLOOP))
         chan->priority--;
   }
   ast_channel_unlock(chan);
   return 0;
}
int ast_extension_close (const char * pattern, const char * data, int needmore)
Definition at line 2407 of file pbx.c.
References ast_log(), E_CANMATCH, E_MATCHMORE, extension_match_core(), and LOG_WARNING.
Referenced by lua_find_extension(), and realtime_switch_common().
{
   if (needmore != E_MATCHMORE && needmore != E_CANMATCH)
      ast_log(LOG_WARNING, "invalid argument %d\n", needmore);
   return extension_match_core(pattern, data, needmore);
}
int ast_extension_cmp (const char * a, const char * b)
Determine if one extension should match before another.
Parameters:
a extension to compare with b
b extension to compare with a
Checks whether or extension a should match before extension b
Return values:
0 if the two extensions have equal matching priority
1 on a > b
-1 on a < b
Definition at line 2209 of file pbx.c.
References ext_cmp().
Referenced by lua_extension_cmp().
{
   return ext_cmp(a, b);
}
int ast_extension_match (const char * pattern, const char * extension)
Determine if a given extension matches a given pattern (in NXX format).
Parameters:
pattern pattern to match
extension extension to check against the pattern.
Checks whether or not the given extension matches the given pattern.
Return values:
1 on match
0 on failure
Definition at line 2402 of file pbx.c.
References E_MATCH, and extension_match_core().
Referenced by ast_ignore_pattern(), do_say(), find_matching_priority(), load_module(), loopback_canmatch(), loopback_exists(), loopback_matchmore(), lua_find_extension(), manager_show_dialplan_helper(), matchcid(), misdn_cfg_is_msn_valid(), realtime_switch_common(), reload(), and show_dialplan_helper().
{
   return extension_match_core(pattern, data, E_MATCH);
}
int ast_extension_state (struct ast_channel * c, const char * context, const char * exten)
Check extension state for an extension by using hint.
Uses hint and devicestate callback to get the state of an extension.
Definition at line 3832 of file pbx.c.
References ast_extension_state2(), and ast_hint_extension().
Referenced by action_extensionstate(), extstate_read(), and handle_request_subscribe().
{
   struct ast_exten *e;
   if (!(e = ast_hint_extension(c, context, exten))) {  /* Do we have a hint for this extension ? */
      return -1;                   /* No hint, return -1 */
   }
   return ast_extension_state2(e);  /* Check all devices in the hint */
}
static int ast_extension_state2 (struct ast_exten * e) [static]
Check state of extension by using hints.
Definition at line 3797 of file pbx.c.
References ast_devstate_aggregate_add(), ast_devstate_aggregate_init(), ast_devstate_aggregate_result(), ast_devstate_to_extenstate(), ast_get_extension_app(), ast_str_buffer(), ast_str_set(), ast_str_thread_get(), extensionstate_buf, and strsep().
Referenced by ast_add_hint_nolock(), ast_extension_state(), and handle_statechange().
{
   struct ast_str *hint = ast_str_thread_get(&extensionstate_buf, 16);
   char *cur, *rest;
   struct ast_devstate_aggregate agg;
   if (!e)
      return -1;
   ast_devstate_aggregate_init(&agg);
   ast_str_set(&hint, 0, "%s", ast_get_extension_app(e));
   rest = ast_str_buffer(hint);  /* One or more devices separated with a & character */
   while ( (cur = strsep(&rest, "&")) ) {
      ast_devstate_aggregate_add(&agg, ast_device_state(cur));
   }
   return ast_devstate_to_extenstate(ast_devstate_aggregate_result(&agg));
}
const char* ast_extension_state2str (int extension_state)
Return extension_state as string.
Return string representation of the state of an extension.
Definition at line 3820 of file pbx.c.
References ARRAY_LEN, extension_states, and cfextension_states::text.
Referenced by cb_extensionstate(), handle_request_subscribe(), handle_show_hint(), handle_show_hints(), and show_channels_cb().
{
   int i;
   for (i = 0; (i < ARRAY_LEN(extension_states)); i++) {
      if (extension_states[i].extension_state == extension_state)
         return extension_states[i].text;
   }
   return "Unknown";
}
int ast_extension_state_add (const char * context, const char * exten, ast_state_cb_type callback, void * data)
Add watcher for extension states.
Registers a state change callback.
Definition at line 3896 of file pbx.c.
References ast_exten::app, ast_add_extension(), ast_calloc, ast_free_ptr(), ast_hint_extension(), AST_LIST_INSERT_HEAD, AST_LIST_TRAVERSE, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strdup, ast_state_cb::callback, ast_hint::callbacks, ast_exten::cidmatch, ast_exten::data, ast_state_cb::data, ast_hint::exten, ast_exten::exten, ast_state_cb::id, ast_exten::label, ast_exten::matchcid, ast_context::name, ast_exten::parent, ast_exten::priority, ast_exten::registrar, and stateid.
Referenced by __init_manager(), handle_request_subscribe(), and skinny_register().
{
   struct ast_hint *hint;
   struct ast_state_cb *cblist;
   struct ast_exten *e;
   /* If there's no context and extension:  add callback to statecbs list */
   if (!context && !exten) {
      AST_RWLIST_WRLOCK(&hints);
      AST_LIST_TRAVERSE(&statecbs, cblist, entry) {
         if (cblist->callback == callback) {
            cblist->data = data;
            AST_RWLIST_UNLOCK(&hints);
            return 0;
         }
      }
      /* Now insert the callback */
      if (!(cblist = ast_calloc(1, sizeof(*cblist)))) {
         AST_RWLIST_UNLOCK(&hints);
         return -1;
      }
      cblist->id = 0;
      cblist->callback = callback;
      cblist->data = data;
      AST_LIST_INSERT_HEAD(&statecbs, cblist, entry);
      AST_RWLIST_UNLOCK(&hints);
      return 0;
   }
   if (!context || !exten)
      return -1;
   /* This callback type is for only one hint, so get the hint */
   e = ast_hint_extension(NULL, context, exten);
   if (!e) {
      return -1;
   }
   /* If this is a pattern, dynamically create a new extension for this
    * particular match.  Note that this will only happen once for each
    * individual extension, because the pattern will no longer match first.
    */
   if (e->exten[0] == '_') {
      ast_add_extension(e->parent->name, 0, exten, e->priority, e->label,
         e->matchcid ? e->cidmatch : NULL, e->app, ast_strdup(e->data), ast_free_ptr,
         e->registrar);
      e = ast_hint_extension(NULL, context, exten);
      if (!e || e->exten[0] == '_') {
         return -1;
      }
   }
   /* Find the hint in the list of hints */
   AST_RWLIST_WRLOCK(&hints);
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (hint->exten == e)
         break;
   }
   if (!hint) {
      /* We have no hint, sorry */
      AST_RWLIST_UNLOCK(&hints);
      return -1;
   }
   /* Now insert the callback in the callback list  */
   if (!(cblist = ast_calloc(1, sizeof(*cblist)))) {
      AST_RWLIST_UNLOCK(&hints);
      return -1;
   }
   cblist->id = stateid++;    /* Unique ID for this callback */
   cblist->callback = callback;  /* Pointer to callback routine */
   cblist->data = data;    /* Data for the callback */
   AST_LIST_INSERT_HEAD(&hint->callbacks, cblist, entry);
   AST_RWLIST_UNLOCK(&hints);
   return cblist->id;
}
int ast_extension_state_del (int id, ast_state_cb_type callback)
Remove a watcher from the callback list.
Deletes a registered state change callback by ID.
Definition at line 3986 of file pbx.c.
References ast_free, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_state_cb::callback, ast_hint::callbacks, and ast_state_cb::id.
Referenced by dialog_unlink_all(), handle_request_subscribe(), and skinny_unregister().
{
   struct ast_state_cb *p_cur = NULL;
   int ret = -1;
   if (!id && !callback)
      return -1;
   AST_RWLIST_WRLOCK(&hints);
   if (!id) {  /* id == 0 is a callback without extension */
      AST_LIST_TRAVERSE_SAFE_BEGIN(&statecbs, p_cur, entry) {
         if (p_cur->callback == callback) {
            AST_LIST_REMOVE_CURRENT(entry);
            break;
         }
      }
      AST_LIST_TRAVERSE_SAFE_END;
   } else { /* callback with extension, find the callback based on ID */
      struct ast_hint *hint;
      AST_RWLIST_TRAVERSE(&hints, hint, list) {
         AST_LIST_TRAVERSE_SAFE_BEGIN(&hint->callbacks, p_cur, entry) {
            if (p_cur->id == id) {
               AST_LIST_REMOVE_CURRENT(entry);
               break;
            }
         }
         AST_LIST_TRAVERSE_SAFE_END;
         if (p_cur)
            break;
      }
   }
   if (p_cur) {
      ast_free(p_cur);
   }
   AST_RWLIST_UNLOCK(&hints);
   return ret;
}
int ast_findlabel_extension (struct ast_channel * c, const char * context, const char * exten, const char * label, const char * callerid)
Find the priority of an extension that has the specified label.
Parameters:
c this is not important
context which context to look in
exten which extension to search for
label label of the action within the extension to match to priority
callerid callerid to search for
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
Return values:
the priority which matches the given label in the extension
-1 if not found.
Definition at line 4148 of file pbx.c.
References E_FINDLABEL, and pbx_extension_helper().
Referenced by action_originate(), action_redirect(), handle_gosub(), handle_setpriority(), isexten_function_read(), and pbx_parseable_goto().
{
   return pbx_extension_helper(c, NULL, context, exten, 0, label, callerid, E_FINDLABEL, 0, 0);
}
int ast_findlabel_extension2 (struct ast_channel * c, struct ast_context * con, const char * exten, const char * label, const char * callerid)
Find the priority of an extension that has the specified label.
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
This function is the same as ast_findlabel_extension, except that it accepts a pointer to an ast_context structure to specify the context instead of the name of the context. Otherwise, the functions behave the same.
Definition at line 4153 of file pbx.c.
References E_FINDLABEL, and pbx_extension_helper().
Referenced by pbx_load_config().
{
   return pbx_extension_helper(c, con, NULL, exten, 0, label, callerid, E_FINDLABEL, 0, 0);
}
int ast_func_read (struct ast_channel * chan, const char * function, char * workspace, size_t len)
executes a read operation on a function
Parameters:
chan Channel to execute on
function Data containing the function call string (will be modified)
workspace A pointer to safe memory to use for a return value
len the number of bytes in workspace
This application executes a function in read mode on a given channel.
Return values:
0 success
non-zero failure
Definition at line 3356 of file pbx.c.
References __ast_module_user_add(), __ast_module_user_remove(), ast_custom_function_find(), ast_log(), ast_strdupa, copy(), func_args(), LOG_ERROR, ast_custom_function::mod, and ast_custom_function::read.
Referenced by action_getvar(), action_status(), handle_getvariable(), lua_get_variable_value(), and pbx_substitute_variables_helper_full().
{
   char *copy = ast_strdupa(function);
   char *args = func_args(copy);
   struct ast_custom_function *acfptr = ast_custom_function_find(copy);
   if (acfptr == NULL)
      ast_log(LOG_ERROR, "Function %s not registered\n", copy);
   else if (!acfptr->read)
      ast_log(LOG_ERROR, "Function %s cannot be read\n", copy);
   else {
      int res;
      struct ast_module_user *u = NULL;
      if (acfptr->mod)
         u = __ast_module_user_add(acfptr->mod, chan);
      res = acfptr->read(chan, copy, args, workspace, len);
      if (acfptr->mod && u)
         __ast_module_user_remove(acfptr->mod, u);
      return res;
   }
   return -1;
}
int ast_func_write (struct ast_channel * chan, const char * function, const char * value)
executes a write operation on a function
Parameters:
chan Channel to execute on
function Data containing the function call string (will be modified)
value A value parameter to pass for writing
This application executes a function in write mode on a given channel.
Return values:
0 success
non-zero failure
Definition at line 3379 of file pbx.c.
References __ast_module_user_add(), __ast_module_user_remove(), ast_custom_function_find(), ast_log(), ast_strdupa, copy(), func_args(), LOG_ERROR, ast_custom_function::mod, and ast_custom_function::write.
Referenced by action_setvar(), pbx_builtin_pushvar_helper(), and pbx_builtin_setvar_helper().
{
   char *copy = ast_strdupa(function);
   char *args = func_args(copy);
   struct ast_custom_function *acfptr = ast_custom_function_find(copy);
   if (acfptr == NULL)
      ast_log(LOG_ERROR, "Function %s not registered\n", copy);
   else if (!acfptr->write)
      ast_log(LOG_ERROR, "Function %s cannot be written to\n", copy);
   else {
      int res;
      struct ast_module_user *u = NULL;
      if (acfptr->mod)
         u = __ast_module_user_add(acfptr->mod, chan);
      res = acfptr->write(chan, copy, args, value);
      if (acfptr->mod && u)
         __ast_module_user_remove(acfptr->mod, u);
      return res;
   }
   return -1;
}
const char* ast_get_context_name (struct ast_context * con)
Definition at line 9384 of file pbx.c.
References ast_context::name.
Referenced by _macro_exec(), ast_context_add_include2(), ast_context_add_switch2(), ast_context_lockmacro(), ast_context_remove_include2(), ast_context_remove_switch2(), ast_context_unlockmacro(), ast_context_verify_includes(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_show_dialplan_context(), context_merge_incls_swits_igps_other_registrars(), dundi_precache_full(), find_context_locked(), find_matching_endwhile(), find_matching_priority(), handle_cli_dialplan_save(), handle_show_hint(), handle_show_hints(), manager_show_dialplan_helper(), show_debug_helper(), and show_dialplan_helper().
{
   return con ? con->name : NULL;
}
const char* ast_get_context_registrar (struct ast_context * c)
Definition at line 9422 of file pbx.c.
References ast_context::registrar.
Referenced by handle_cli_dialplan_save(), show_debug_helper(), and show_dialplan_helper().
{
   return c ? c->registrar : NULL;
}
const char* ast_get_extension_app (struct ast_exten * e)
Definition at line 9452 of file pbx.c.
References ast_exten::app.
Referenced by _macro_exec(), ast_add_hint_nolock(), ast_extension_state2(), ast_get_hint(), find_matching_endwhile(), handle_cli_dialplan_save(), handle_show_hint(), handle_show_hints(), handle_statechange(), manager_show_dialplan_helper(), and print_ext().
{
   return e ? e->app : NULL;
}
void* ast_get_extension_app_data (struct ast_exten * e)
Definition at line 9457 of file pbx.c.
References ast_exten::data.
Referenced by _macro_exec(), ast_get_hint(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and print_ext().
{
   return e ? e->data : NULL;
}
const char* ast_get_extension_cidmatch (struct ast_exten * e)
Definition at line 9447 of file pbx.c.
References ast_exten::cidmatch.
Referenced by complete_dialplan_remove_extension(), find_matching_priority(), and handle_cli_dialplan_save().
{
   return e ? e->cidmatch : NULL;
}
struct ast_context* ast_get_extension_context (struct ast_exten * exten) [read]
Definition at line 9389 of file pbx.c.
References ast_exten::parent.
Referenced by handle_show_hint(), and handle_show_hints().
{
   return exten ? exten->parent : NULL;
}
const char* ast_get_extension_label (struct ast_exten * exten)
Definition at line 9399 of file pbx.c.
References ast_exten::label.
Referenced by handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return exten ? exten->label : NULL;
}
int ast_get_extension_matchcid (struct ast_exten * e)
Definition at line 9442 of file pbx.c.
References ast_exten::matchcid.
Referenced by complete_dialplan_remove_extension(), find_matching_priority(), and handle_cli_dialplan_save().
{
   return e ? e->matchcid : 0;
}
const char* ast_get_extension_name (struct ast_exten * exten)
Definition at line 9394 of file pbx.c.
References ast_exten::exten.
Referenced by ast_add_hint_nolock(), complete_core_show_hint(), complete_dialplan_remove_extension(), dundi_precache_full(), find_matching_priority(), handle_cli_dialplan_save(), handle_show_hint(), handle_show_hints(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return exten ? exten->exten : NULL;
}
int ast_get_extension_priority (struct ast_exten * exten)
Definition at line 9414 of file pbx.c.
References ast_exten::priority.
Referenced by complete_dialplan_remove_extension(), find_matching_priority(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and print_ext().
{
   return exten ? exten->priority : -1;
}
const char* ast_get_extension_registrar (struct ast_exten * e)
Definition at line 9427 of file pbx.c.
References ast_exten::registrar.
Referenced by handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return e ? e->registrar : NULL;
}
int ast_get_hint (char * hint, int hintsize, char * name, int namesize, struct ast_channel * c, const char * context, const char * exten)
Get hint for channel.
If an extension hint exists, return non-zero.
Definition at line 4126 of file pbx.c.
References ast_copy_string(), ast_get_extension_app(), ast_get_extension_app_data(), and ast_hint_extension().
Referenced by action_extensionstate(), get_cid_name(), get_destination(), hint_read(), manager_state_cb(), pbx_retrieve_variable(), skinny_extensionstate_cb(), and transmit_state_notify().
{
   struct ast_exten *e = ast_hint_extension(c, context, exten);
   if (e) {
      if (hint)
         ast_copy_string(hint, ast_get_extension_app(e), hintsize);
      if (name) {
         const char *tmp = ast_get_extension_app_data(e);
         if (tmp)
            ast_copy_string(name, tmp, namesize);
      }
      return -1;
   }
   return 0;
}
const char* ast_get_ignorepat_name (struct ast_ignorepat * ip)
Definition at line 9409 of file pbx.c.
References ast_ignorepat::pattern.
Referenced by complete_dialplan_remove_ignorepat(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), lookup_c_ip(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return ip ? ip->pattern : NULL;
}
const char* ast_get_ignorepat_registrar (struct ast_ignorepat * ip)
Definition at line 9437 of file pbx.c.
References ast_ignorepat::registrar.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return ip ? ip->registrar : NULL;
}
const char* ast_get_include_name (struct ast_include * inc)
Definition at line 9404 of file pbx.c.
References ast_include::name.
Referenced by complete_dialplan_remove_include(), context_merge_incls_swits_igps_other_registrars(), find_matching_priority(), handle_cli_dialplan_save(), lookup_ci(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return inc ? inc->name : NULL;
}
const char* ast_get_include_registrar (struct ast_include * i)
Definition at line 9432 of file pbx.c.
References ast_include::registrar.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return i ? i->registrar : NULL;
}
const char* ast_get_switch_data (struct ast_sw * sw)
Definition at line 9467 of file pbx.c.
References ast_sw::data.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return sw ? sw->data : NULL;
}
int ast_get_switch_eval (struct ast_sw * sw)
Definition at line 9472 of file pbx.c.
References ast_sw::eval.
Referenced by context_merge_incls_swits_igps_other_registrars().
{
   return sw->eval;
}
const char* ast_get_switch_name (struct ast_sw * sw)
Definition at line 9462 of file pbx.c.
References ast_sw::name.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return sw ? sw->name : NULL;
}
const char* ast_get_switch_registrar (struct ast_sw * sw)
Definition at line 9477 of file pbx.c.
References ast_sw::registrar.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   return sw ? sw->registrar : NULL;
}
int ast_goto_if_exists (struct ast_channel * chan, const char * context, const char * exten, int priority)
Note:
This function will handle locking the channel as needed.
Definition at line 9570 of file pbx.c.
References __ast_goto_if_exists().
Referenced by background_detect_exec(), channel_spy(), common_exec(), conf_run(), goto_exten(), onedigit_goto(), priority_jump(), select_entry(), and valid_exit().
{
   return __ast_goto_if_exists(chan, context, exten, priority, 0);
}
int ast_hashtab_compare_contexts (const void * ah_a, const void * ah_b)
hashtable functions for contexts
Definition at line 994 of file pbx.c.
References ast_context::name.
Referenced by ast_context_find_or_create(), lua_register_switches(), and pbx_load_module().
{
   const struct ast_context *ac = ah_a;
   const struct ast_context *bc = ah_b;
   if (!ac || !bc) /* safety valve, but it might prevent a crash you'd rather have happen */
      return 1;
   /* assume context names are registered in a string table! */
   return strcmp(ac->name, bc->name);
}
unsigned int ast_hashtab_hash_contexts (const void * obj)
Definition at line 1037 of file pbx.c.
References ast_hashtab_hash_string(), and ast_context::name.
Referenced by ast_context_find_or_create(), lua_register_switches(), and pbx_load_module().
{
   const struct ast_context *ac = obj;
   return ast_hashtab_hash_string(ac->name);
}
static struct ast_exten* ast_hint_extension (struct ast_channel * c, const char * context, const char * exten) [static, read]
Definition at line 3761 of file pbx.c.
References ast_hint_extension_nolock(), ast_rdlock_contexts(), and ast_unlock_contexts().
Referenced by ast_extension_state(), ast_extension_state_add(), and ast_get_hint().
{
   struct ast_exten *e;
   ast_rdlock_contexts();
   e = ast_hint_extension_nolock(c, context, exten);
   ast_unlock_contexts();
   return e;
}
static struct ast_exten* ast_hint_extension_nolock (struct ast_channel * c, const char * context, const char * exten) [static, read]
Find hint for given extension in context.
Definition at line 3755 of file pbx.c.
References E_MATCH, pbx_find_extension(), PRIORITY_HINT, and pbx_find_info::stacklen.
Referenced by ast_hint_extension(), and ast_merge_contexts_and_delete().
{
   struct pbx_find_info q = { .stacklen = 0 }; /* the rest is set in pbx_find_context */
   return pbx_find_extension(c, NULL, &q, context, exten, PRIORITY_HINT, NULL, "", E_MATCH);
}
int ast_ignore_pattern (const char * context, const char * pattern)
Checks to see if a number should be ignored.
Parameters:
context context to search within
pattern to check whether it should be ignored or not
Check if a number should be ignored with respect to dialtone cancellation.
Return values:
0 if the pattern should not be ignored
non-zero if the pattern should be ignored
Definition at line 7267 of file pbx.c.
References ast_context_find(), ast_extension_match(), ast_context::ignorepats, ast_ignorepat::next, and ast_ignorepat::pattern.
Referenced by ast_app_dtget(), disa_exec(), dp_lookup(), dundi_lookup_local(), handle_enbloc_call_message(), handle_soft_key_event_message(), handle_stimulus_message(), mgcp_ss(), skinny_ss(), and ss_thread().
{
   struct ast_context *con = ast_context_find(context);
   if (con) {
      struct ast_ignorepat *pat;
      for (pat = con->ignorepats; pat; pat = pat->next) {
         if (ast_extension_match(pat->pattern, pattern))
            return 1;
      }
   }
   return 0;
}
int ast_matchmore_extension (struct ast_channel * c, const char * context, const char * exten, int priority, const char * callerid)
Looks to see if adding anything to this extension might match something. (exists ^ canmatch).
Parameters:
c not really important XXX
context context to serach within
exten extension to check
priority priority of extension path
callerid callerid of extension being searched for
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
Returns:
If "exten" *could match* a valid extension in this context with some more digits, return non-zero. Does NOT return non-zero if this is an exact-match only. Basically, when this returns 0, no matter what you add to exten, it's not going to be a valid extension anymore
Definition at line 4163 of file pbx.c.
References E_MATCHMORE, and pbx_extension_helper().
Referenced by __ast_pbx_run(), ast_app_dtget(), collect_digits(), disa_exec(), dp_lookup(), dundi_lookup_local(), handle_link_data(), handle_link_phone_dtmf(), local_dtmf_helper(), loopback_matchmore(), mgcp_ss(), pbx_builtin_background(), readexten_exec(), skinny_ss(), and ss_thread().
{
   return pbx_extension_helper(c, NULL, context, exten, priority, NULL, callerid, E_MATCHMORE, 0, 0);
}
void ast_merge_contexts_and_delete (struct ast_context ** extcontexts, struct ast_hashtab * exttable, const char * registrar)
Merge the temporary contexts into a global contexts list and delete from the global list the ones that are being added.
Parameters:
extcontexts pointer to the ast_context structure
exttable pointer to the ast_hashtab structure that contains all the elements in extcontexts
registrar of the context; if it's set the routine will delete all contexts that belong to that registrar; if NULL only the contexts that are specified in extcontexts
Definition at line 6623 of file pbx.c.
References __ast_internal_context_destroy(), ast_exten::app, ast_add_extension_nolock(), ast_calloc, AST_EXTENSION_REMOVED, ast_free, ast_free_ptr(), ast_hashtab_destroy(), ast_hashtab_end_traversal(), ast_hashtab_next(), ast_hashtab_start_traversal(), ast_hint_extension_nolock(), AST_LIST_APPEND_LIST, AST_LIST_EMPTY, AST_LIST_HEAD_INIT_VALUE, AST_LIST_INSERT_HEAD, AST_LIST_REMOVE_HEAD, ast_log(), ast_rdlock_contexts(), AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strdup, ast_tvdiff_us(), ast_tvnow(), ast_unlock_contexts(), ast_verb, ast_wrlock_contexts(), ast_wrlock_contexts_version(), ast_state_cb::callback, ast_hint::callbacks, context_merge(), contexts, contexts_table, ast_state_cb::data, ast_exten::data, E_MATCH, ast_exten::exten, ast_hint::exten, ast_hint::laststate, LOG_WARNING, ast_context::name, ast_context::next, ast_sw::next, ast_exten::parent, pbx_find_extension(), PRIORITY_HINT, ast_exten::registrar, and pbx_find_info::stacklen.
Referenced by lua_reload_extensions(), and pbx_load_module().
{
   double ft;
   struct ast_context *tmp, *oldcontextslist;
   struct ast_hashtab *oldtable;
   struct store_hints store = AST_LIST_HEAD_INIT_VALUE;
   struct store_hint *this;
   struct ast_hint *hint;
   struct ast_exten *exten;
   int length;
   struct ast_state_cb *thiscb;
   struct ast_hashtab_iter *iter;
   /* it is very important that this function hold the hint list lock _and_ the conlock
      during its operation; not only do we need to ensure that the list of contexts
      and extensions does not change, but also that no hint callbacks (watchers) are
      added or removed during the merge/delete process
      in addition, the locks _must_ be taken in this order, because there are already
      other code paths that use this order
   */
   struct timeval begintime, writelocktime, endlocktime, enddeltime;
   int wrlock_ver;
   begintime = ast_tvnow();
   ast_rdlock_contexts();
   iter = ast_hashtab_start_traversal(contexts_table);
   while ((tmp = ast_hashtab_next(iter))) {
      context_merge(extcontexts, exttable, tmp, registrar);
   }
   ast_hashtab_end_traversal(iter);
   wrlock_ver = ast_wrlock_contexts_version();
   ast_unlock_contexts(); /* this feels real retarded, but you must do
                       what you must do If this isn't done, the following
                        wrlock is a guraranteed deadlock */
   ast_wrlock_contexts();
   if (ast_wrlock_contexts_version() > wrlock_ver+1) {
      ast_log(LOG_WARNING,"==================!!!!!!!!!!!!!!!Something changed the contexts in the middle of merging contexts!\n");
   }
   AST_RWLIST_WRLOCK(&hints);
   writelocktime = ast_tvnow();
   /* preserve all watchers for hints */
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (!AST_LIST_EMPTY(&hint->callbacks)) {
         length = strlen(hint->exten->exten) + strlen(hint->exten->parent->name) + 2 + sizeof(*this);
         if (!(this = ast_calloc(1, length)))
            continue;
         /* this removes all the callbacks from the hint into this. */
         AST_LIST_APPEND_LIST(&this->callbacks, &hint->callbacks, entry);
         this->laststate = hint->laststate;
         this->context = this->data;
         strcpy(this->data, hint->exten->parent->name);
         this->exten = this->data + strlen(this->context) + 1;
         strcpy(this->exten, hint->exten->exten);
         AST_LIST_INSERT_HEAD(&store, this, list);
      }
   }
   /* save the old table and list */
   oldtable = contexts_table;
   oldcontextslist = contexts;
   /* move in the new table and list */
   contexts_table = exttable;
   contexts = *extcontexts;
   /* restore the watchers for hints that can be found; notify those that
      cannot be restored
   */
   while ((this = AST_LIST_REMOVE_HEAD(&store, list))) {
      struct pbx_find_info q = { .stacklen = 0 };
      exten = pbx_find_extension(NULL, NULL, &q, this->context, this->exten, PRIORITY_HINT, NULL, "", E_MATCH);
      /* If this is a pattern, dynamically create a new extension for this
       * particular match.  Note that this will only happen once for each
       * individual extension, because the pattern will no longer match first.
       */
      if (exten && exten->exten[0] == '_') {
         ast_add_extension_nolock(exten->parent->name, 0, this->exten, PRIORITY_HINT, NULL,
            0, exten->app, ast_strdup(exten->data), ast_free_ptr, exten->registrar);
         /* rwlocks are not recursive locks */
         exten = ast_hint_extension_nolock(NULL, this->context, this->exten);
      }
      /* Find the hint in the list of hints */
      AST_RWLIST_TRAVERSE(&hints, hint, list) {
         if (hint->exten == exten)
            break;
      }
      if (!exten || !hint) {
         /* this hint has been removed, notify the watchers */
         while ((thiscb = AST_LIST_REMOVE_HEAD(&this->callbacks, entry))) {
            thiscb->callback(this->context, this->exten, AST_EXTENSION_REMOVED, thiscb->data);
            ast_free(thiscb);
         }
      } else {
         AST_LIST_APPEND_LIST(&hint->callbacks, &this->callbacks, entry);
         hint->laststate = this->laststate;
      }
      ast_free(this);
   }
   AST_RWLIST_UNLOCK(&hints);
   ast_unlock_contexts();
   endlocktime = ast_tvnow();
   /* the old list and hashtab no longer are relevant, delete them while the rest of asterisk
      is now freely using the new stuff instead */
   ast_hashtab_destroy(oldtable, NULL);
   for (tmp = oldcontextslist; tmp; ) {
      struct ast_context *next;  /* next starting point */
      next = tmp->next;
      __ast_internal_context_destroy(tmp);
      tmp = next;
   }
   enddeltime = ast_tvnow();
   ft = ast_tvdiff_us(writelocktime, begintime);
   ft /= 1000000.0;
   ast_verb(3,"Time to scan old dialplan and merge leftovers back into the new: %8.6f sec\n", ft);
   ft = ast_tvdiff_us(endlocktime, writelocktime);
   ft /= 1000000.0;
   ast_verb(3,"Time to restore hints and swap in new dialplan: %8.6f sec\n", ft);
   ft = ast_tvdiff_us(enddeltime, endlocktime);
   ft /= 1000000.0;
   ast_verb(3,"Time to delete the old dialplan: %8.6f sec\n", ft);
   ft = ast_tvdiff_us(enddeltime, begintime);
   ft /= 1000000.0;
   ast_verb(3,"Total time merge_contexts_delete: %8.6f sec\n", ft);
   return;
}
int ast_parseable_goto (struct ast_channel * chan, const char * goto_string)
Note:
This function will handle locking the channel as needed.
Definition at line 9633 of file pbx.c.
References pbx_parseable_goto().
Referenced by _while_exec(), check_goto_on_transfer(), dial_exec_full(), gosub_exec(), ivr_dispatch(), parkandannounce_exec(), pbx_builtin_goto(), and while_continue_exec().
{
   return pbx_parseable_goto(chan, goto_string, 0);
}
int ast_pbx_outgoing_app (const char * type, int format, void * data, int timeout, const char * app, const char * appdata, int * reason, int sync, const char * cid_num, const char * cid_name, struct ast_variable * vars, const char * account, struct ast_channel ** locked_channel)
Synchronously or asynchronously make an outbound call and send it to a particular application with given extension
Definition at line 8106 of file pbx.c.
References __ast_request_and_dial(), ast_channel::_state, outgoing_helper::account, async_stat::app, app_tmp::app, async_stat::appdata, ast_calloc, ast_cdr_disposition(), ast_cdr_failed(), ast_cdr_setaccount(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_free, ast_hangup(), ast_log(), ast_pbx_outgoing_cdr_failed(), ast_pbx_run_app(), ast_pthread_create_detached, ast_set_variables(), AST_STATE_UP, ast_strlen_zero(), ast_variables_destroy(), ast_verb, async_wait(), ast_channel::cdr, async_stat::chan, app_tmp::chan, app_tmp::data, errno, ast_channel::hangupcause, LOG_WARNING, async_stat::p, app_tmp::t, async_stat::timeout, and outgoing_helper::vars.
Referenced by action_originate(), attempt_thread(), fast_originate(), orig_app(), and originate_exec().
{
   struct ast_channel *chan;
   struct app_tmp *tmp;
   int res = -1, cdr_res = -1;
   struct outgoing_helper oh;
   memset(&oh, 0, sizeof(oh));
   oh.vars = vars;
   oh.account = account;
   if (locked_channel)
      *locked_channel = NULL;
   if (ast_strlen_zero(app)) {
      res = -1;
      goto outgoing_app_cleanup;
   }
   if (synchronous) {
      chan = __ast_request_and_dial(type, format, data, timeout, reason, cid_num, cid_name, &oh);
      if (chan) {
         ast_set_variables(chan, vars);
         if (account)
            ast_cdr_setaccount(chan, account);
         if (chan->_state == AST_STATE_UP) {
            res = 0;
            ast_verb(4, "Channel %s was answered.\n", chan->name);
            tmp = ast_calloc(1, sizeof(*tmp));
            if (!tmp)
               res = -1;
            else {
               ast_copy_string(tmp->app, app, sizeof(tmp->app));
               if (appdata)
                  ast_copy_string(tmp->data, appdata, sizeof(tmp->data));
               tmp->chan = chan;
               if (synchronous > 1) {
                  if (locked_channel)
                     ast_channel_unlock(chan);
                  ast_pbx_run_app(tmp);
               } else {
                  if (locked_channel)
                     ast_channel_lock(chan);
                  if (ast_pthread_create_detached(&tmp->t, NULL, ast_pbx_run_app, tmp)) {
                     ast_log(LOG_WARNING, "Unable to spawn execute thread on %s: %s\n", chan->name, strerror(errno));
                     ast_free(tmp);
                     if (locked_channel)
                        ast_channel_unlock(chan);
                     ast_hangup(chan);
                     res = -1;
                  } else {
                     if (locked_channel)
                        *locked_channel = chan;
                  }
               }
            }
         } else {
            ast_verb(4, "Channel %s was never answered.\n", chan->name);
            if (chan->cdr) { /* update the cdr */
               /* here we update the status of the call, which sould be busy.
                * if that fails then we set the status to failed */
               if (ast_cdr_disposition(chan->cdr, chan->hangupcause))
                  ast_cdr_failed(chan->cdr);
            }
            ast_hangup(chan);
         }
      }
      if (res < 0) { /* the call failed for some reason */
         if (*reason == 0) { /* if the call failed (not busy or no answer)
                        * update the cdr with the failed message */
            cdr_res = ast_pbx_outgoing_cdr_failed();
            if (cdr_res != 0) {
               res = cdr_res;
               goto outgoing_app_cleanup;
            }
         }
      }
   } else {
      struct async_stat *as;
      if (!(as = ast_calloc(1, sizeof(*as)))) {
         res = -1;
         goto outgoing_app_cleanup;
      }
      chan = __ast_request_and_dial(type, format, data, timeout, reason, cid_num, cid_name, &oh);
      if (!chan) {
         ast_free(as);
         res = -1;
         goto outgoing_app_cleanup;
      }
      as->chan = chan;
      ast_copy_string(as->app, app, sizeof(as->app));
      if (appdata)
         ast_copy_string(as->appdata,  appdata, sizeof(as->appdata));
      as->timeout = timeout;
      ast_set_variables(chan, vars);
      if (account)
         ast_cdr_setaccount(chan, account);
      /* Start a new thread, and get something handling this channel. */
      if (locked_channel)
         ast_channel_lock(chan);
      if (ast_pthread_create_detached(&as->p, NULL, async_wait, as)) {
         ast_log(LOG_WARNING, "Failed to start async wait\n");
         ast_free(as);
         if (locked_channel)
            ast_channel_unlock(chan);
         ast_hangup(chan);
         res = -1;
         goto outgoing_app_cleanup;
      } else {
         if (locked_channel)
            *locked_channel = chan;
      }
      res = 0;
   }
outgoing_app_cleanup:
   ast_variables_destroy(vars);
   return res;
}
static int ast_pbx_outgoing_cdr_failed (void) [static]
Function to post an empty cdr after a spool call fails.
Note:
This function posts an empty cdr for a failed spool call
Definition at line 7914 of file pbx.c.
References ast_cdr_detach(), ast_cdr_end(), ast_cdr_failed(), ast_cdr_init(), ast_cdr_start(), ast_channel_alloc, ast_channel_free(), AST_STATE_DOWN, and ast_channel::cdr.
Referenced by ast_pbx_outgoing_app(), and ast_pbx_outgoing_exten().
{
   /* allocate a channel */
   struct ast_channel *chan = ast_channel_alloc(0, AST_STATE_DOWN, 0, 0, "", "", "", 0, "%s", "");
   if (!chan)
      return -1;  /* failure */
   if (!chan->cdr) {
      /* allocation of the cdr failed */
      ast_channel_free(chan);   /* free the channel */
      return -1;                /* return failure */
   }
   /* allocation of the cdr was successful */
   ast_cdr_init(chan->cdr, chan);  /* initialize our channel's cdr */
   ast_cdr_start(chan->cdr);       /* record the start and stop time */
   ast_cdr_end(chan->cdr);
   ast_cdr_failed(chan->cdr);      /* set the status to failed */
   ast_cdr_detach(chan->cdr);      /* post and free the record */
   chan->cdr = NULL;
   ast_channel_free(chan);         /* free the channel */
   return 0;  /* success */
}
int ast_pbx_outgoing_exten (const char * type, int format, void * data, int timeout, const char * context, const char * exten, int priority, int * reason, int sync, const char * cid_num, const char * cid_name, struct ast_variable * vars, const char * account, struct ast_channel ** locked_channel)
Synchronously or asynchronously make an outbound call and send it to a particular extension
Definition at line 7940 of file pbx.c.
References __ast_request_and_dial(), ast_channel::_state, outgoing_helper::account, ast_calloc, ast_cdr_disposition(), ast_cdr_failed(), ast_cdr_setaccount(), ast_channel_alloc, ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_exists_extension(), ast_free, ast_hangup(), ast_log(), ast_pbx_outgoing_cdr_failed(), ast_pbx_run(), ast_pbx_start(), ast_pthread_create_detached, ast_request_and_dial(), ast_set_variables(), AST_STATE_DOWN, AST_STATE_UP, ast_strlen_zero(), ast_variables_destroy(), ast_verb, async_wait(), ast_channel::cdr, async_stat::chan, outgoing_helper::cid_name, outgoing_helper::cid_num, async_stat::context, ast_channel::context, outgoing_helper::context, outgoing_helper::exten, ast_channel::hangupcause, LOG_ERROR, LOG_WARNING, async_stat::p, outgoing_helper::parent_channel, pbx_builtin_setvar_helper(), outgoing_helper::priority, set_ext_pri(), async_stat::timeout, and outgoing_helper::vars.
Referenced by action_originate(), attempt_thread(), fast_originate(), orig_exten(), and originate_exec().
{
   struct ast_channel *chan;
   struct async_stat *as;
   int res = -1, cdr_res = -1;
   struct outgoing_helper oh;
   if (synchronous) {
      oh.context = context;
      oh.exten = exten;
      oh.priority = priority;
      oh.cid_num = cid_num;
      oh.cid_name = cid_name;
      oh.account = account;
      oh.vars = vars;
      oh.parent_channel = NULL;
      chan = __ast_request_and_dial(type, format, data, timeout, reason, cid_num, cid_name, &oh);
      if (channel) {
         *channel = chan;
         if (chan)
            ast_channel_lock(chan);
      }
      if (chan) {
         if (chan->_state == AST_STATE_UP) {
               res = 0;
            ast_verb(4, "Channel %s was answered.\n", chan->name);
            if (synchronous > 1) {
               if (channel)
                  ast_channel_unlock(chan);
               if (ast_pbx_run(chan)) {
                  ast_log(LOG_ERROR, "Unable to run PBX on %s\n", chan->name);
                  if (channel)
                     *channel = NULL;
                  ast_hangup(chan);
                  chan = NULL;
                  res = -1;
               }
            } else {
               if (ast_pbx_start(chan)) {
                  ast_log(LOG_ERROR, "Unable to start PBX on %s\n", chan->name);
                  if (channel) {
                     *channel = NULL;
                     ast_channel_unlock(chan);
                  }
                  ast_hangup(chan);
                  res = -1;
               }
               chan = NULL;
            }
         } else {
            ast_verb(4, "Channel %s was never answered.\n", chan->name);
            if (chan->cdr) { /* update the cdr */
               /* here we update the status of the call, which sould be busy.
                * if that fails then we set the status to failed */
               if (ast_cdr_disposition(chan->cdr, chan->hangupcause))
                  ast_cdr_failed(chan->cdr);
            }
            if (channel) {
               *channel = NULL;
               ast_channel_unlock(chan);
            }
            ast_hangup(chan);
            chan = NULL;
         }
      }
      if (res < 0) { /* the call failed for some reason */
         if (*reason == 0) { /* if the call failed (not busy or no answer)
                        * update the cdr with the failed message */
            cdr_res = ast_pbx_outgoing_cdr_failed();
            if (cdr_res != 0) {
               res = cdr_res;
               goto outgoing_exten_cleanup;
            }
         }
         /* create a fake channel and execute the "failed" extension (if it exists) within the requested context */
         /* check if "failed" exists */
         if (ast_exists_extension(chan, context, "failed", 1, NULL)) {
            chan = ast_channel_alloc(0, AST_STATE_DOWN, 0, 0, "", "", "", 0, "OutgoingSpoolFailed");
            if (chan) {
               char failed_reason[4] = "";
               if (!ast_strlen_zero(context))
                  ast_copy_string(chan->context, context, sizeof(chan->context));
               set_ext_pri(chan, "failed", 1);
               ast_set_variables(chan, vars);
               snprintf(failed_reason, sizeof(failed_reason), "%d", *reason);
               pbx_builtin_setvar_helper(chan, "REASON", failed_reason);
               if (account)
                  ast_cdr_setaccount(chan, account);
               if (ast_pbx_run(chan)) {
                  ast_log(LOG_ERROR, "Unable to run PBX on %s\n", chan->name);
                  ast_hangup(chan);
               }
               chan = NULL;
            }
         }
      }
   } else {
      if (!(as = ast_calloc(1, sizeof(*as)))) {
         res = -1;
         goto outgoing_exten_cleanup;
      }
      chan = ast_request_and_dial(type, format, data, timeout, reason, cid_num, cid_name);
      if (channel) {
         *channel = chan;
         if (chan)
            ast_channel_lock(chan);
      }
      if (!chan) {
         ast_free(as);
         res = -1;
         goto outgoing_exten_cleanup;
      }
      as->chan = chan;
      ast_copy_string(as->context, context, sizeof(as->context));
      set_ext_pri(as->chan,  exten, priority);
      as->timeout = timeout;
      ast_set_variables(chan, vars);
      if (account)
         ast_cdr_setaccount(chan, account);
      if (ast_pthread_create_detached(&as->p, NULL, async_wait, as)) {
         ast_log(LOG_WARNING, "Failed to start async wait\n");
         ast_free(as);
         if (channel) {
            *channel = NULL;
            ast_channel_unlock(chan);
         }
         ast_hangup(chan);
         res = -1;
         goto outgoing_exten_cleanup;
      }
      res = 0;
   }
outgoing_exten_cleanup:
   ast_variables_destroy(vars);
   return res;
}
enum ast_pbx_result ast_pbx_run (struct ast_channel * c)
Execute the PBX in the current thread.
Parameters:
c channel to run the pbx on
This executes the PBX on a given channel. It allocates a new PBX structure for the channel, and provides all PBX functionality. See ast_pbx_start for an asynchronous function to run the PBX in a new thread as opposed to the current one.
Return values:
Zero on success
non-zero on failure
Definition at line 4596 of file pbx.c.
References ast_pbx_run_args().
Referenced by ast_pbx_outgoing_exten(), async_wait(), mgcp_ss(), skinny_newcall(), ss_thread(), and unistim_ss().
{
   return ast_pbx_run_args(c, NULL);
}
static void* ast_pbx_run_app (void * data) [static]
run the application and free the descriptor once done
Definition at line 8091 of file pbx.c.
References app_tmp::app, ast_free, ast_hangup(), ast_log(), ast_verb, app_tmp::chan, app_tmp::data, LOG_WARNING, pbx_exec(), and pbx_findapp().
Referenced by ast_pbx_outgoing_app().
{
   struct app_tmp *tmp = data;
   struct ast_app *app;
   app = pbx_findapp(tmp->app);
   if (app) {
      ast_verb(4, "Launching %s(%s) on %s\n", tmp->app, tmp->data, tmp->chan->name);
      pbx_exec(tmp->chan, app, tmp->data);
   } else
      ast_log(LOG_WARNING, "No such application '%s'\n", tmp->app);
   ast_hangup(tmp->chan);
   ast_free(tmp);
   return NULL;
}
enum ast_pbx_result ast_pbx_run_args (struct ast_channel * c, struct ast_pbx_args * args)
Execute the PBX in the current thread.
Parameters:
c channel to run the pbx on
args options for the pbx
This executes the PBX on a given channel. It allocates a new PBX structure for the channel, and provides all PBX functionality. See ast_pbx_start for an asynchronous function to run the PBX in a new thread as opposed to the current one.
Return values:
Zero on success
non-zero on failure
Definition at line 4581 of file pbx.c.
References __ast_pbx_run(), AST_PBX_CALL_LIMIT, AST_PBX_SUCCESS, decrease_call_count(), and increase_call_count().
Referenced by ast_pbx_run(), dial_exec_full(), handle_gosub(), and try_calling().
{
   enum ast_pbx_result res = AST_PBX_SUCCESS;
   if (increase_call_count(c)) {
      return AST_PBX_CALL_LIMIT;
   }
   res = __ast_pbx_run(c, args);
   decrease_call_count();
   return res;
}
enum ast_pbx_result ast_pbx_start (struct ast_channel * c)
Create a new thread and start the PBX.
Parameters:
c channel to start the pbx on
See also:
ast_pbx_run for a synchronous function to run the PBX in the current thread, as opposed to starting a new one.
Return values:
Zero on success
non-zero on failure
Definition at line 4559 of file pbx.c.
References ast_log(), AST_PBX_CALL_LIMIT, AST_PBX_FAILED, AST_PBX_SUCCESS, ast_pthread_create_detached, decrease_call_count(), increase_call_count(), LOG_WARNING, and pbx_thread().
Referenced by __oh323_new(), alsa_new(), ast_async_goto(), ast_iax2_new(), ast_pbx_outgoing_exten(), bridge_call_thread(), bridge_exec(), check_goto_on_transfer(), console_new(), dahdi_new(), dial_exec_full(), gtalk_new(), gtalk_newcall(), handle_request_invite(), jingle_new(), jingle_newcall(), local_call(), manage_parkinglot(), mgcp_new(), nbs_new(), oss_new(), pbx_start_chan(), phone_new(), rpt_call(), sip_new(), skinny_new(), unistim_new(), and usbradio_new().
{
   pthread_t t;
   if (!c) {
      ast_log(LOG_WARNING, "Asked to start thread on NULL channel?\n");
      return AST_PBX_FAILED;
   }
   if (increase_call_count(c))
      return AST_PBX_CALL_LIMIT;
   /* Start a new thread, and get something handling this channel. */
   if (ast_pthread_create_detached(&t, NULL, pbx_thread, c)) {
      ast_log(LOG_WARNING, "Failed to create new channel thread\n");
      decrease_call_count();
      return AST_PBX_FAILED;
   }
   return AST_PBX_SUCCESS;
}
int ast_processed_calls (void)
Retrieve the total number of calls processed through the PBX since last restart.
Definition at line 4606 of file pbx.c.
References totalcalls.
Referenced by ast_var_Config(), handle_chanlist(), and handle_showcalls().
{
   return totalcalls;
}
int ast_rdlock_context (struct ast_context * con)
Read locks a given context.
Parameters:
con context to lock
Return values:
0 on success
-1 on failure
Definition at line 9371 of file pbx.c.
References ast_rwlock_rdlock(), and ast_context::lock.
Referenced by _macro_exec(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), dundi_precache_full(), find_matching_endwhile(), handle_cli_dialplan_save(), lookup_c_ip(), lookup_ci(), manager_show_dialplan_helper(), show_debug_helper(), and show_dialplan_helper().
{
   return ast_rwlock_rdlock(&con->lock);
}
int ast_rdlock_contexts (void)
Read locks the context list.
Return values:
0 on success
-1 on error
Definition at line 9353 of file pbx.c.
References ast_rwlock_rdlock(), and conlock.
Referenced by _macro_exec(), ast_context_find(), ast_context_find_or_create(), ast_context_lockmacro(), ast_context_unlockmacro(), ast_hint_extension(), ast_merge_contexts_and_delete(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_show_dialplan_context(), dundi_precache_full(), find_context_locked(), find_matching_endwhile(), handle_cli_dialplan_save(), handle_statechange(), manager_show_dialplan_helper(), pbx_extension_helper(), show_debug_helper(), show_dialplan_helper(), and unreference_cached_app().
{
   return ast_rwlock_rdlock(&conlock);
}
int ast_register_application2 (const char * app, int(*)(struct ast_channel *, void *) execute, const char * synopsis, const char * description, void * mod)
Dynamically register a new dial plan application.
Register an application.
Definition at line 5062 of file pbx.c.
References ast_app::arguments, ast_calloc, ast_free, ast_log(), AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, AST_STATIC_DOC, ast_string_field_init, ast_string_field_set, ast_strlen_zero(), ast_verb, AST_XML_DOC, ast_xmldoc_build_arguments(), ast_xmldoc_build_description(), ast_xmldoc_build_seealso(), ast_xmldoc_build_synopsis(), ast_xmldoc_build_syntax(), COLOR_BRCYAN, ast_app::docsrc, ast_app::execute, LOG_WARNING, ast_app::module, ast_app::name, ast_app::seealso, ast_app::syntax, and term_color().
Referenced by ast_features_init(), and load_pbx().
{
   struct ast_app *tmp, *cur = NULL;
   char tmps[80];
   int length, res;
#ifdef AST_XML_DOCS
   char *tmpxml;
#endif
   AST_RWLIST_WRLOCK(&apps);
   AST_RWLIST_TRAVERSE(&apps, tmp, list) {
      if (!(res = strcasecmp(app, tmp->name))) {
         ast_log(LOG_WARNING, "Already have an application '%s'\n", app);
         AST_RWLIST_UNLOCK(&apps);
         return -1;
      } else if (res < 0)
         break;
   }
   length = sizeof(*tmp) + strlen(app) + 1;
   if (!(tmp = ast_calloc(1, length))) {
      AST_RWLIST_UNLOCK(&apps);
      return -1;
   }
   if (ast_string_field_init(tmp, 128)) {
      AST_RWLIST_UNLOCK(&apps);
      ast_free(tmp);
      return -1;
   }
#ifdef AST_XML_DOCS
   /* Try to lookup the docs in our XML documentation database */
   if (ast_strlen_zero(synopsis) && ast_strlen_zero(description)) {
      /* load synopsis */
      tmpxml = ast_xmldoc_build_synopsis("application", app);
      ast_string_field_set(tmp, synopsis, tmpxml);
      ast_free(tmpxml);
      /* load description */
      tmpxml = ast_xmldoc_build_description("application", app);
      ast_string_field_set(tmp, description, tmpxml);
      ast_free(tmpxml);
      /* load syntax */
      tmpxml = ast_xmldoc_build_syntax("application", app);
      ast_string_field_set(tmp, syntax, tmpxml);
      ast_free(tmpxml);
      /* load arguments */
      tmpxml = ast_xmldoc_build_arguments("application", app);
      ast_string_field_set(tmp, arguments, tmpxml);
      ast_free(tmpxml);
      /* load seealso */
      tmpxml = ast_xmldoc_build_seealso("application", app);
      ast_string_field_set(tmp, seealso, tmpxml);
      ast_free(tmpxml);
      tmp->docsrc = AST_XML_DOC;
   } else {
#endif
      ast_string_field_set(tmp, synopsis, synopsis);
      ast_string_field_set(tmp, description, description);
      tmp->docsrc = AST_STATIC_DOC;
#ifdef AST_XML_DOCS
   }
#endif
   strcpy(tmp->name, app);
   tmp->execute = execute;
   tmp->module = mod;
   /* Store in alphabetical order */
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, cur, list) {
      if (strcasecmp(tmp->name, cur->name) < 0) {
         AST_RWLIST_INSERT_BEFORE_CURRENT(tmp, list);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   if (!cur)
      AST_RWLIST_INSERT_TAIL(&apps, tmp, list);
   ast_verb(2, "Registered application '%s'\n", term_color(tmps, tmp->name, COLOR_BRCYAN, 0, sizeof(tmps)));
   AST_RWLIST_UNLOCK(&apps);
   return 0;
}
int ast_register_switch (struct ast_switch * sw)
Register an alternative dialplan switch.
Parameters:
sw switch to register
This function registers a populated ast_switch structure with the asterisk switching architecture.
Return values:
0 success
non-zero failure
Definition at line 5157 of file pbx.c.
References ast_log(), AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, LOG_WARNING, and ast_switch::name.
Referenced by load_module().
{
   struct ast_switch *tmp;
   AST_RWLIST_WRLOCK(&switches);
   AST_RWLIST_TRAVERSE(&switches, tmp, list) {
      if (!strcasecmp(tmp->name, sw->name)) {
         AST_RWLIST_UNLOCK(&switches);
         ast_log(LOG_WARNING, "Switch '%s' already found\n", sw->name);
         return -1;
      }
   }
   AST_RWLIST_INSERT_TAIL(&switches, sw, list);
   AST_RWLIST_UNLOCK(&switches);
   return 0;
}
static int ast_remove_hint (struct ast_exten * e) [static]
Remove hint from extension.
Definition at line 4091 of file pbx.c.
References AST_EXTENSION_DEACTIVATED, ast_free, AST_LIST_REMOVE_HEAD, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, ast_state_cb::callback, ast_hint::callbacks, ast_state_cb::data, ast_exten::exten, ast_hint::exten, ast_context::name, and ast_exten::parent.
Referenced by destroy_exten().
{
   /* Cleanup the Notifys if hint is removed */
   struct ast_hint *hint;
   struct ast_state_cb *cblist;
   int res = -1;
   if (!e)
      return -1;
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&hints, hint, list) {
      if (hint->exten != e)
         continue;
      while ((cblist = AST_LIST_REMOVE_HEAD(&hint->callbacks, entry))) {
         /* Notify with -1 and remove all callbacks */
         cblist->callback(hint->exten->parent->name, hint->exten->exten,
            AST_EXTENSION_DEACTIVATED, cblist->data);
         ast_free(cblist);
      }
      AST_RWLIST_REMOVE_CURRENT(list);
      ast_free(hint);
      res = 0;
      break;
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   return res;
}
int ast_spawn_extension (struct ast_channel * c, const char * context, const char * exten, int priority, const char * callerid, int * found, int combined_find_spawn)
Launch a new extension (i.e. new stack).
Parameters:
c not important
context which context to generate the extension within
exten new extension to add
priority priority of new extension
callerid callerid of extension
found
combined_find_spawn
This adds a new extension to the asterisk extension list.
Note:
It is possible for autoservice to be started and stopped on c during this function call, it is important that c is not locked prior to calling this. Otherwise a deadlock may occur
Return values:
0 on success
-1 on failure.
Definition at line 4168 of file pbx.c.
References E_SPAWN, and pbx_extension_helper().
Referenced by __ast_pbx_run(), _macro_exec(), ast_bridge_call(), dial_exec_full(), and loopback_exec().
{
   return pbx_extension_helper(c, NULL, context, exten, priority, NULL, callerid, E_SPAWN, found, combined_find_spawn);
}
int ast_unlock_context (struct ast_context * con)
Return values:
Unlocks the given context
Parameters:
con context to unlock
Return values:
0 on success
-1 on failure
Definition at line 9376 of file pbx.c.
References ast_rwlock_unlock(), and ast_context::lock.
Referenced by __ast_context_destroy(), _macro_exec(), ast_add_extension2_lockopt(), ast_context_add_ignorepat2(), ast_context_add_include2(), ast_context_add_switch2(), ast_context_remove_extension_callerid2(), ast_context_remove_ignorepat2(), ast_context_remove_include2(), ast_context_remove_switch2(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), dundi_precache_full(), find_matching_endwhile(), handle_cli_dialplan_save(), lookup_c_ip(), lookup_ci(), manager_show_dialplan_helper(), show_debug_helper(), and show_dialplan_helper().
{
   return ast_rwlock_unlock(&con->lock);
}
int ast_unlock_contexts (void)
Unlocks contexts.
Return values:
0 on success
-1 on failure
Definition at line 9358 of file pbx.c.
References ast_rwlock_unlock(), and conlock.
Referenced by _macro_exec(), ast_add_extension(), ast_context_add_ignorepat(), ast_context_add_include(), ast_context_add_switch(), ast_context_destroy(), ast_context_find(), ast_context_find_or_create(), ast_context_lockmacro(), ast_context_remove_extension_callerid(), ast_context_remove_ignorepat(), ast_context_remove_include(), ast_context_remove_switch(), ast_context_unlockmacro(), ast_hint_extension(), ast_merge_contexts_and_delete(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_show_dialplan_context(), dundi_precache_full(), find_context_locked(), find_matching_endwhile(), handle_cli_dialplan_save(), handle_statechange(), manager_show_dialplan_helper(), pbx_extension_helper(), show_debug_helper(), show_dialplan_helper(), and unreference_cached_app().
{
   return ast_rwlock_unlock(&conlock);
}
int ast_unregister_application (const char * app)
Unregister an application.
Parameters:
app name of the application (does not have to be the same string as the one that was registered)
This unregisters an application from Asterisk's internal application list.
Return values:
0 success
-1 failure
Definition at line 6403 of file pbx.c.
References ast_free, AST_RWLIST_REMOVE_CURRENT, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_string_field_free_memory, ast_verb, ast_app::name, and unreference_cached_app().
Referenced by __unload_module(), load_module(), and unload_module().
{
   struct ast_app *tmp;
   AST_RWLIST_WRLOCK(&apps);
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&apps, tmp, list) {
      if (!strcasecmp(app, tmp->name)) {
         unreference_cached_app(tmp);
         AST_RWLIST_REMOVE_CURRENT(list);
         ast_verb(2, "Unregistered application '%s'\n", tmp->name);
         ast_string_field_free_memory(tmp);
         ast_free(tmp);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   AST_RWLIST_UNLOCK(&apps);
   return tmp ? 0 : -1;
}
void ast_unregister_switch (struct ast_switch * sw)
Unregister an alternative switch.
Parameters:
sw switch to unregister
Unregisters a switch from asterisk.
Returns:
nothing
Definition at line 5175 of file pbx.c.
References AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, and AST_RWLIST_WRLOCK.
Referenced by __unload_module(), and unload_module().
{
   AST_RWLIST_WRLOCK(&switches);
   AST_RWLIST_REMOVE(&switches, sw, list);
   AST_RWLIST_UNLOCK(&switches);
}
struct ast_exten* ast_walk_context_extensions (struct ast_context * con, struct ast_exten * exten) [read]
Definition at line 9490 of file pbx.c.
References ast_exten::next, and ast_context::root.
Referenced by complete_dialplan_remove_extension(), dundi_precache_full(), find_matching_priority(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), pbx_find_extension(), show_dialplan_helper(), and unreference_cached_app().
{
   if (!exten)
      return con ? con->root : NULL;
   else
      return exten->next;
}
struct ast_ignorepat* ast_walk_context_ignorepats (struct ast_context * con, struct ast_ignorepat * ip) [read]
Definition at line 9523 of file pbx.c.
References ast_context::ignorepats, and ast_ignorepat::next.
Referenced by complete_dialplan_remove_ignorepat(), context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), lookup_c_ip(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   if (!ip)
      return con ? con->ignorepats : NULL;
   else
      return ip->next;
}
struct ast_include* ast_walk_context_includes (struct ast_context * con, struct ast_include * inc) [read]
Definition at line 9514 of file pbx.c.
References ast_context::includes, and ast_include::next.
Referenced by ast_context_verify_includes(), complete_dialplan_remove_include(), context_merge_incls_swits_igps_other_registrars(), find_matching_priority(), handle_cli_dialplan_save(), lookup_ci(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   if (!inc)
      return con ? con->includes : NULL;
   else
      return inc->next;
}
struct ast_sw* ast_walk_context_switches (struct ast_context * con, struct ast_sw * sw) [read]
Definition at line 9499 of file pbx.c.
References ast_context::alts, AST_LIST_FIRST, and AST_LIST_NEXT.
Referenced by context_merge_incls_swits_igps_other_registrars(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), and show_dialplan_helper().
{
   if (!sw)
      return con ? AST_LIST_FIRST(&con->alts) : NULL;
   else
      return AST_LIST_NEXT(sw, list);
}
struct ast_context* ast_walk_contexts (struct ast_context * con) [read]
Definition at line 9485 of file pbx.c.
References contexts, and ast_context::next.
Referenced by _macro_exec(), ast_context_find(), ast_context_lockmacro(), ast_context_unlockmacro(), complete_dialplan_add_extension(), complete_dialplan_add_ignorepat(), complete_dialplan_add_include(), complete_dialplan_remove_extension(), complete_dialplan_remove_ignorepat(), complete_dialplan_remove_include(), complete_show_dialplan_context(), dundi_precache_full(), find_context_locked(), find_matching_endwhile(), find_matching_priority(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), pbx_find_extension(), pbx_load_module(), show_debug_helper(), show_dialplan_helper(), and unreference_cached_app().
{
   return con ? con->next : contexts;
}
struct ast_exten* ast_walk_extension_priorities (struct ast_exten * exten, struct ast_exten * priority) [read]
Definition at line 9508 of file pbx.c.
References ast_exten::peer.
Referenced by complete_dialplan_remove_extension(), find_matching_priority(), handle_cli_dialplan_save(), manager_show_dialplan_helper(), pbx_find_extension(), show_dialplan_helper(), and unreference_cached_app().
{
   return priority ? priority->peer : exten;
}
int ast_wrlock_context (struct ast_context * con)
Write locks a given context.
Parameters:
con context to lock
Return values:
0 on success
-1 on failure
Definition at line 9366 of file pbx.c.
References ast_rwlock_wrlock(), and ast_context::lock.
Referenced by __ast_context_destroy(), ast_add_extension2_lockopt(), ast_context_add_ignorepat2(), ast_context_add_include2(), ast_context_add_switch2(), ast_context_remove_extension_callerid2(), ast_context_remove_ignorepat2(), ast_context_remove_include2(), and ast_context_remove_switch2().
{
   return ast_rwlock_wrlock(&con->lock);
}
int ast_wrlock_contexts (void)
Write locks the context list.
Return values:
0 on success
-1 on error
Definition at line 9345 of file pbx.c.
References ast_atomic_fetchadd_int(), ast_rwlock_wrlock(), conlock, and conlock_wrlock_version.
Referenced by ast_context_destroy(), ast_context_find_or_create(), ast_merge_contexts_and_delete(), and complete_dialplan_remove_include().
{
   int res = ast_rwlock_wrlock(&conlock);
   if (!res)
      ast_atomic_fetchadd_int(&conlock_wrlock_version, 1);
   return res;
}
int ast_wrlock_contexts_version (void)
Definition at line 9337 of file pbx.c.
References conlock_wrlock_version.
Referenced by ast_merge_contexts_and_delete().
{
   return conlock_wrlock_version;
}
static void* async_wait (void * data) [static]
Definition at line 7853 of file pbx.c.
References ast_channel::_state, async_stat::app, async_stat::appdata, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, ast_copy_string(), AST_FRAME_CONTROL, ast_free, ast_frfree, ast_hangup(), ast_log(), ast_pbx_run(), ast_read(), AST_STATE_UP, ast_strlen_zero(), ast_verb, ast_waitfor(), async_stat::chan, ast_channel::context, async_stat::context, ast_channel::exten, async_stat::exten, f, ast_frame::frametype, LOG_ERROR, LOG_WARNING, pbx_exec(), pbx_findapp(), ast_channel::priority, async_stat::priority, ast_frame::subclass, and async_stat::timeout.
Referenced by ast_pbx_outgoing_app(), and ast_pbx_outgoing_exten().
{
   struct async_stat *as = data;
   struct ast_channel *chan = as->chan;
   int timeout = as->timeout;
   int res;
   struct ast_frame *f;
   struct ast_app *app;
   while (timeout && (chan->_state != AST_STATE_UP)) {
      res = ast_waitfor(chan, timeout);
      if (res < 1)
         break;
      if (timeout > -1)
         timeout = res;
      f = ast_read(chan);
      if (!f)
         break;
      if (f->frametype == AST_FRAME_CONTROL) {
         if ((f->subclass == AST_CONTROL_BUSY)  ||
             (f->subclass == AST_CONTROL_CONGESTION) ) {
            ast_frfree(f);
            break;
         }
      }
      ast_frfree(f);
   }
   if (chan->_state == AST_STATE_UP) {
      if (!ast_strlen_zero(as->app)) {
         app = pbx_findapp(as->app);
         if (app) {
            ast_verb(3, "Launching %s(%s) on %s\n", as->app, as->appdata, chan->name);
            pbx_exec(chan, app, as->appdata);
         } else
            ast_log(LOG_WARNING, "No such application '%s'\n", as->app);
      } else {
         if (!ast_strlen_zero(as->context))
            ast_copy_string(chan->context, as->context, sizeof(chan->context));
         if (!ast_strlen_zero(as->exten))
            ast_copy_string(chan->exten, as->exten, sizeof(chan->exten));
         if (as->priority > 0)
            chan->priority = as->priority;
         /* Run the PBX */
         if (ast_pbx_run(chan)) {
            ast_log(LOG_ERROR, "Failed to start PBX on %s\n", chan->name);
         } else {
            /* PBX will have taken care of this */
            chan = NULL;
         }
      }
   }
   ast_free(as);
   if (chan)
      ast_hangup(chan);
   return NULL;
}
static void cli_match_char_tree (struct match_char * node, char * prefix, int fd) [static]
Definition at line 1523 of file pbx.c.
References match_char::alt_char, ast_cli(), ast_str_alloca, ast_str_buffer(), ast_str_set(), match_char::deleted, ast_exten::exten, match_char::exten, match_char::is_pattern, match_char::next_char, match_char::specificity, and match_char::x.
Referenced by show_debug_helper().
{
   char extenstr[40];
   struct ast_str *my_prefix = ast_str_alloca(1024);
   extenstr[0] = '\0';
   if (node && node->exten && node->exten)
      snprintf(extenstr, sizeof(extenstr), "(%p)", node->exten);
   if (strlen(node->x) > 1) {
      ast_cli(fd, "%s[%s]:%c:%c:%d:%s%s%s\n", prefix, node->x, node->is_pattern ? 'Y' : 'N',
         node->deleted ? 'D' : '-', node->specificity, node->exten? "EXTEN:" : "",
         node->exten ? node->exten->exten : "", extenstr);
   } else {
      ast_cli(fd, "%s%s:%c:%c:%d:%s%s%s\n", prefix, node->x, node->is_pattern ? 'Y' : 'N',
         node->deleted ? 'D' : '-', node->specificity, node->exten? "EXTEN:" : "",
         node->exten ? node->exten->exten : "", extenstr);
   }
   ast_str_set(&my_prefix, 0, "%s+       ", prefix);
   if (node->next_char)
      cli_match_char_tree(node->next_char, ast_str_buffer(my_prefix), fd);
   if (node->alt_char)
      cli_match_char_tree(node->alt_char, prefix, fd);
}
static int collect_digits (struct ast_channel * c, int waittime, char * buf, int buflen, int pos) [static]
collect digits from the channel into the buffer.
Parameters:
waittime is in milliseconds
Return values:
0 on timeout or done.
-1 on error.
Definition at line 4188 of file pbx.c.
References ast_channel::_softhangup, ast_matchmore_extension(), AST_SOFTHANGUP_ASYNCGOTO, ast_waitfordigit(), ast_channel::cid, ast_callerid::cid_num, ast_channel::context, ast_pbx::dtimeoutms, and ast_channel::pbx.
Referenced by __ast_pbx_run().
{
   int digit;
   buf[pos] = '\0';  /* make sure it is properly terminated */
   while (ast_matchmore_extension(c, c->context, buf, 1, c->cid.cid_num)) {
      /* As long as we're willing to wait, and as long as it's not defined,
         keep reading digits until we can't possibly get a right answer anymore.  */
      digit = ast_waitfordigit(c, waittime);
      if (c->_softhangup == AST_SOFTHANGUP_ASYNCGOTO) {
         c->_softhangup = 0;
      } else {
         if (!digit) /* No entry */
            break;
         if (digit < 0) /* Error, maybe a  hangup */
            return -1;
         if (pos < buflen - 1) { /* XXX maybe error otherwise ? */
            buf[pos++] = digit;
            buf[pos] = '\0';
         }
         waittime = c->pbx->dtimeoutms;
      }
   }
   return 0;
}
static int compare_char (const void * a, const void * b) [static]
Definition at line 981 of file pbx.c.
Referenced by add_exten_to_pattern_tree().
{
   const char *ac = a;
   const char *bc = b;
   if ((*ac) < (*bc))
      return -1;
   else if ((*ac) == (*bc))
      return 0;
   else
      return 1;
}
static char* complete_core_show_hint (const char * line, const char * word, int pos, int state) [static]
autocomplete for CLI command 'core show hint'
Definition at line 5371 of file pbx.c.
References ast_get_extension_name(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, and ast_hint::exten.
Referenced by handle_show_hint().
{
   struct ast_hint *hint;
   char *ret = NULL;
   int which = 0;
   int wordlen;
   if (pos != 3)
      return NULL;
   wordlen = strlen(word);
   AST_RWLIST_RDLOCK(&hints);
   /* walk through all hints */
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (!strncasecmp(word, ast_get_extension_name(hint->exten), wordlen) && ++which > state) {
         ret = ast_strdup(ast_get_extension_name(hint->exten));
         break;
      }
   }
   AST_RWLIST_UNLOCK(&hints);
   return ret;
}
static char* complete_show_dialplan_context (const char * line, const char * word, int pos, int state) [static]
Definition at line 5567 of file pbx.c.
References ast_get_context_name(), ast_rdlock_contexts(), ast_strdup, ast_unlock_contexts(), and ast_walk_contexts().
Referenced by handle_debug_dialplan(), and handle_show_dialplan().
{
   struct ast_context *c = NULL;
   char *ret = NULL;
   int which = 0;
   int wordlen;
   /* we are do completion of [exten@]context on second position only */
   if (pos != 2)
      return NULL;
   ast_rdlock_contexts();
   wordlen = strlen(word);
   /* walk through all contexts and return the n-th match */
   while ( (c = ast_walk_contexts(c)) ) {
      if (!strncasecmp(word, ast_get_context_name(c), wordlen) && ++which > state) {
         ret = ast_strdup(ast_get_context_name(c));
         break;
      }
   }
   ast_unlock_contexts();
   return ret;
}
static void context_merge (struct ast_context ** extcontexts, struct ast_hashtab * exttable, struct ast_context * context, const char * registrar) [static]
Definition at line 6539 of file pbx.c.
References ast_exten::app, ast_add_extension2(), ast_context_find_or_create(), ast_hashtab_end_traversal(), ast_hashtab_lookup(), ast_hashtab_next(), ast_hashtab_start_traversal(), ast_log(), ast_strdup, ast_verb, ast_exten::cidmatch, context_merge_incls_swits_igps_other_registrars(), ast_exten::data, ast_exten::datad, ast_exten::exten, first, ast_exten::label, LOG_ERROR, ast_exten::matchcid, ast_context::name, ast_exten::peer_table, ast_exten::priority, ast_context::refcount, ast_context::registrar, ast_exten::registrar, and ast_context::root_table.
Referenced by ast_merge_contexts_and_delete().
{
   struct ast_context *new = ast_hashtab_lookup(exttable, context); /* is there a match in the new set? */
   struct ast_exten *exten_item, *prio_item, *new_exten_item, *new_prio_item;
   struct ast_hashtab_iter *exten_iter;
   struct ast_hashtab_iter *prio_iter;
   int insert_count = 0;
   int first = 1;
   /* We'll traverse all the extensions/prios, and see which are not registrar'd with
      the current registrar, and copy them to the new context. If the new context does not
      exist, we'll create it "on demand". If no items are in this context to copy, then we'll
      only create the empty matching context if the old one meets the criteria */
   if (context->root_table) {
      exten_iter = ast_hashtab_start_traversal(context->root_table);
      while ((exten_item=ast_hashtab_next(exten_iter))) {
         if (new) {
            new_exten_item = ast_hashtab_lookup(new->root_table, exten_item);
         } else {
            new_exten_item = NULL;
         }
         prio_iter = ast_hashtab_start_traversal(exten_item->peer_table);
         while ((prio_item=ast_hashtab_next(prio_iter))) {
            int res1;
            char *dupdstr;
            if (new_exten_item) {
               new_prio_item = ast_hashtab_lookup(new_exten_item->peer_table, prio_item);
            } else {
               new_prio_item = NULL;
            }
            if (strcmp(prio_item->registrar,registrar) == 0) {
               continue;
            }
            /* make sure the new context exists, so we have somewhere to stick this exten/prio */
            if (!new) {
               new = ast_context_find_or_create(extcontexts, exttable, context->name, prio_item->registrar); /* a new context created via priority from a different context in the old dialplan, gets its registrar from the prio's registrar */
            }
            /* copy in the includes, switches, and ignorepats */
            if (first) { /* but, only need to do this once */
               context_merge_incls_swits_igps_other_registrars(new, context, registrar);
               first = 0;
            }
            if (!new) {
               ast_log(LOG_ERROR,"Could not allocate a new context for %s in merge_and_delete! Danger!\n", context->name);
               return; /* no sense continuing. */
            }
            /* we will not replace existing entries in the new context with stuff from the old context.
               but, if this is because of some sort of registrar conflict, we ought to say something... */
            dupdstr = ast_strdup(prio_item->data);
            res1 = ast_add_extension2(new, 0, prio_item->exten, prio_item->priority, prio_item->label,
                                prio_item->matchcid ? prio_item->cidmatch : NULL, prio_item->app, dupdstr, prio_item->datad, prio_item->registrar);
            if (!res1 && new_exten_item && new_prio_item){
               ast_verb(3,"Dropping old dialplan item %s/%s/%d [%s(%s)] (registrar=%s) due to conflict with new dialplan\n",
                     context->name, prio_item->exten, prio_item->priority, prio_item->app, (char*)prio_item->data, prio_item->registrar);
            } else {
               /* we do NOT pass the priority data from the old to the new -- we pass a copy of it, so no changes to the current dialplan take place,
                and no double frees take place, either! */
               insert_count++;
            }
         }
         ast_hashtab_end_traversal(prio_iter);
      }
      ast_hashtab_end_traversal(exten_iter);
   }
   if (!insert_count && !new && (strcmp(context->registrar, registrar) != 0 ||
        (strcmp(context->registrar, registrar) == 0 && context->refcount > 1))) {
      /* we could have given it the registrar of the other module who incremented the refcount,
         but that's not available, so we give it the registrar we know about */
      new = ast_context_find_or_create(extcontexts, exttable, context->name, context->registrar);
      /* copy in the includes, switches, and ignorepats */
      context_merge_incls_swits_igps_other_registrars(new, context, registrar);
   }
}
static void context_merge_incls_swits_igps_other_registrars (struct ast_context * new, struct ast_context * old, const char * registrar) [static]
Definition at line 6506 of file pbx.c.
References ast_context_add_ignorepat2(), ast_context_add_include2(), ast_context_add_switch2(), ast_get_context_name(), ast_get_ignorepat_name(), ast_get_ignorepat_registrar(), ast_get_include_name(), ast_get_include_registrar(), ast_get_switch_data(), ast_get_switch_eval(), ast_get_switch_name(), ast_get_switch_registrar(), ast_verb, ast_walk_context_ignorepats(), ast_walk_context_includes(), and ast_walk_context_switches().
Referenced by context_merge().
{
   struct ast_include *i;
   struct ast_ignorepat *ip;
   struct ast_sw *sw;
   ast_verb(3, "merging incls/swits/igpats from old(%s) to new(%s) context, registrar = %s\n", ast_get_context_name(old), ast_get_context_name(new), registrar);
   /* copy in the includes, switches, and ignorepats */
   /* walk through includes */
   for (i = NULL; (i = ast_walk_context_includes(old, i)) ; ) {
      if (strcmp(ast_get_include_registrar(i), registrar) == 0)
         continue; /* not mine */
      ast_context_add_include2(new, ast_get_include_name(i), ast_get_include_registrar(i));
   }
   /* walk through switches */
   for (sw = NULL; (sw = ast_walk_context_switches(old, sw)) ; ) {
      if (strcmp(ast_get_switch_registrar(sw), registrar) == 0)
         continue; /* not mine */
      ast_context_add_switch2(new, ast_get_switch_name(sw), ast_get_switch_data(sw), ast_get_switch_eval(sw), ast_get_switch_registrar(sw));
   }
   /* walk thru ignorepats ... */
   for (ip = NULL; (ip = ast_walk_context_ignorepats(old, ip)); ) {
      if (strcmp(ast_get_ignorepat_registrar(ip), registrar) == 0)
         continue; /* not mine */
      ast_context_add_ignorepat2(new, ast_get_ignorepat_name(ip), ast_get_ignorepat_registrar(ip));
   }
}
static void create_match_char_tree (struct ast_context * con) [static]
Definition at line 2000 of file pbx.c.
References add_exten_to_pattern_tree(), ast_hashtab_end_traversal(), ast_hashtab_get_stats(), ast_hashtab_next(), ast_hashtab_start_traversal(), ast_log(), ast_exten::exten, LOG_DEBUG, LOG_ERROR, ast_context::name, and ast_context::root_table.
Referenced by pbx_find_extension().
{
   struct ast_hashtab_iter *t1;
   struct ast_exten *e1;
#ifdef NEED_DEBUG
   int biggest_bucket, resizes, numobjs, numbucks;
   ast_log(LOG_DEBUG,"Creating Extension Trie for context %s\n", con->name);
   ast_hashtab_get_stats(con->root_table, &biggest_bucket, &resizes, &numobjs, &numbucks);
   ast_log(LOG_DEBUG,"This tree has %d objects in %d bucket lists, longest list=%d objects, and has resized %d times\n",
         numobjs, numbucks, biggest_bucket, resizes);
#endif
   t1 = ast_hashtab_start_traversal(con->root_table);
   while ((e1 = ast_hashtab_next(t1))) {
      if (e1->exten) {
         add_exten_to_pattern_tree(con, e1, 0);
      } else {
         ast_log(LOG_ERROR, "Attempt to create extension with no extension name.\n");
      }
   }
   ast_hashtab_end_traversal(t1);
}
static void decrease_call_count (void) [static]
Definition at line 4517 of file pbx.c.
References ast_mutex_lock(), ast_mutex_unlock(), countcalls, and maxcalllock.
Referenced by ast_pbx_run_args(), ast_pbx_start(), and pbx_thread().
{
   ast_mutex_lock(&maxcalllock);
   if (countcalls > 0)
      countcalls--;
   ast_mutex_unlock(&maxcalllock);
}
static void destroy_exten (struct ast_exten * e) [static]
Definition at line 4525 of file pbx.c.
References ast_free, ast_hashtab_destroy(), ast_remove_hint(), ast_exten::data, ast_exten::datad, ast_exten::peer_label_table, ast_exten::peer_table, ast_exten::priority, and PRIORITY_HINT.
Referenced by __ast_internal_context_destroy(), and ast_context_remove_extension_callerid2().
{
   if (e->priority == PRIORITY_HINT)
      ast_remove_hint(e);
   if (e->peer_table)
      ast_hashtab_destroy(e->peer_table,0);
   if (e->peer_label_table)
      ast_hashtab_destroy(e->peer_label_table, 0);
   if (e->datad)
      e->datad(e->data);
   ast_free(e);
}
static void destroy_pattern_tree (struct match_char * pattern_tree) [static]
Definition at line 2023 of file pbx.c.
References match_char::alt_char, match_char::exten, free, match_char::next_char, and match_char::x.
Referenced by __ast_internal_context_destroy().
{
   /* destroy all the alternates */
   if (pattern_tree->alt_char) {
      destroy_pattern_tree(pattern_tree->alt_char);
      pattern_tree->alt_char = 0;
   }
   /* destroy all the nexts */
   if (pattern_tree->next_char) {
      destroy_pattern_tree(pattern_tree->next_char);
      pattern_tree->next_char = 0;
   }
   pattern_tree->exten = 0; /* never hurts to make sure there's no pointers laying around */
   if (pattern_tree->x) {
      free(pattern_tree->x);
   }
   free(pattern_tree);
}
static void device_state_cb (const struct ast_event * event, void * unused) [static]
Definition at line 9283 of file pbx.c.
References ast_calloc, ast_event_get_ie_str(), AST_EVENT_IE_DEVICE, ast_free, ast_log(), ast_strlen_zero(), ast_taskprocessor_push(), statechange::dev, handle_statechange(), and LOG_ERROR.
Referenced by load_pbx().
{
   const char *device;
   struct statechange *sc;
   device = ast_event_get_ie_str(event, AST_EVENT_IE_DEVICE);
   if (ast_strlen_zero(device)) {
      ast_log(LOG_ERROR, "Received invalid event that had no device IE\n");
      return;
   }
   if (!(sc = ast_calloc(1, sizeof(*sc) + strlen(device) + 1)))
      return;
   strcpy(sc->dev, device);
   if (ast_taskprocessor_push(device_state_tps, handle_statechange, sc) < 0) {
      ast_free(sc);
   }
}
static void exception_store_free (void * data) [static]
Definition at line 2983 of file pbx.c.
References ast_free, and ast_string_field_free_memory.
{
   struct pbx_exception *exception = data;
   ast_string_field_free_memory(exception);
   ast_free(exception);
}
static int ext_cmp (const char * a, const char * b) [static]
the full routine to compare extensions in rules.
Definition at line 2176 of file pbx.c.
References ext_cmp1().
Referenced by ast_add_extension2_lockopt(), and ast_extension_cmp().
{
   /* make sure non-patterns come first.
    * If a is not a pattern, it either comes first or
    * we do a more complex pattern comparison.
    */
   int ret = 0;
   if (a[0] != '_')
      return (b[0] == '_') ? -1 : strcmp(a, b);
   /* Now we know a is a pattern; if b is not, a comes first */
   if (b[0] != '_')
      return 1;
   /* ok we need full pattern sorting routine.
    * skip past the underscores */
   ++a; ++b;
   do {
      unsigned char bitwise[2][32] = { { 0, } };
      ret = ext_cmp1(&a, bitwise[0]) - ext_cmp1(&b, bitwise[1]);
      if (ret == 0) {
         /* Are the classes different, even though they score the same? */
         ret = memcmp(bitwise[0], bitwise[1], 32);
      }
   } while (!ret && a && b);
   if (ret == 0) {
      return 0;
   } else {
      return (ret > 0) ? 1 : -1;
   }
}
static int ext_cmp1 (const char ** p, unsigned char * bitwise) [static]
helper functions to sort extensions and patterns in the desired way, so that more specific patterns appear first.
ext_cmp1 compares individual characters (or sets of), returning an int where bits 0-7 are the ASCII code of the first char in the set, while bit 8-15 are the cardinality of the set minus 1. This way more specific patterns (smaller cardinality) appear first. Wildcards have a special value, so that we can directly compare them to sets by subtracting the two values. In particular: 0x000xx one character, xx 0x0yyxx yy character set starting with xx 0x10000 '.' (one or more of anything) 0x20000 '!' (zero or more of anything) 0x30000 NUL (end of string) 0x40000 error in set. The pointer to the string is advanced according to needs. NOTES: 1. the empty set is equivalent to NUL. 2. given that a full set has always 0 as the first element, we could encode the special cases as 0xffXX where XX is 1, 2, 3, 4 as used above.
Note:
If two patterns score the same, the one with the lowest ascii values will compare as coming first.
Definition at line 2096 of file pbx.c.
References ast_log(), and LOG_WARNING.
Referenced by ext_cmp().
{
   int c, cmin = 0xff, count = 0;
   const char *end;
   /* load value and advance pointer */
   c = *(*p)++;
   /* always return unless we have a set of chars */
   switch (toupper(c)) {
   default: /* ordinary character */
      bitwise[c / 8] = 1 << (c % 8);
      return 0x0100 | (c & 0xff);
   case 'N':   /* 2..9 */
      bitwise[6] = 0xfc;
      bitwise[7] = 0x03;
      return 0x0800 | '2';
   case 'X':   /* 0..9 */
      bitwise[6] = 0xff;
      bitwise[7] = 0x03;
      return 0x0A00 | '0';
   case 'Z':   /* 1..9 */
      bitwise[6] = 0xfe;
      bitwise[7] = 0x03;
      return 0x0900 | '1';
   case '.':   /* wildcard */
      return 0x10000;
   case '!':   /* earlymatch */
      return 0x20000;   /* less specific than NULL */
   case '\0':  /* empty string */
      *p = NULL;
      return 0x30000;
   case '[':   /* pattern */
      break;
   }
   /* locate end of set */
   end = strchr(*p, ']');
   if (end == NULL) {
      ast_log(LOG_WARNING, "Wrong usage of [] in the extension\n");
      return 0x40000;   /* XXX make this entry go last... */
   }
   for (; *p < end  ; (*p)++) {
      unsigned char c1, c2;   /* first-last char in range */
      c1 = (unsigned char)((*p)[0]);
      if (*p + 2 < end && (*p)[1] == '-') { /* this is a range */
         c2 = (unsigned char)((*p)[2]);
         *p += 2;    /* skip a total of 3 chars */
      } else {        /* individual character */
         c2 = c1;
      }
      if (c1 < cmin) {
         cmin = c1;
      }
      for (; c1 <= c2; c1++) {
         unsigned char mask = 1 << (c1 % 8);
         /*!\note If two patterns score the same, the one with the lowest
          * ascii values will compare as coming first. */
         /* Flag the character as included (used) and count it. */
         if (!(bitwise[ c1 / 8 ] & mask)) {
            bitwise[ c1 / 8 ] |= mask;
            count += 0x100;
         }
      }
   }
   (*p)++;
   return count == 0 ? 0x30000 : (count | cmin);
}
static int ext_strncpy (char * dst, const char * src, int len) [static]
copy a string skipping whitespace
Definition at line 7411 of file pbx.c.
Referenced by ast_add_extension2_lockopt().
{
   int count = 0;
   int insquares = 0;
   while (*src && (count < len - 1)) {
      if (*src == '[') {
         insquares = 1;
      } else if (*src == ']') {
         insquares = 0;
      } else if (*src == ' ' && !insquares) {
         src++;
         continue;
      }
      *dst = *src;
      dst++;
      src++;
      count++;
   }
   *dst = '\0';
   return count;
}
static int extension_match_core (const char * pattern, const char * data, enum ext_match_t mode) [static]
Definition at line 2389 of file pbx.c.
References _extension_match_core(), ast_add_profile(), and ast_mark().
Referenced by ast_extension_close(), ast_extension_match(), and pbx_find_extension().
{
   int i;
   static int prof_id = -2;   /* marker for 'unallocated' id */
   if (prof_id == -2) {
      prof_id = ast_add_profile("ext_match", 0);
   }
   ast_mark(prof_id, 1);
   i = _extension_match_core(pattern, data, mode);
   ast_mark(prof_id, 0);
   return i;
}
static struct ast_context* find_context (const char * context) [static, read]
lookup for a context with a given name,
Return values:
found context or NULL if not found.
Definition at line 4641 of file pbx.c.
References ast_copy_string(), ast_hashtab_lookup(), contexts_table, and fake_context::name.
{
   struct ast_context *c = NULL;
   struct fake_context item;
   ast_copy_string(item.name, context, sizeof(item.name));
   c = ast_hashtab_lookup(contexts_table,&item);
   return c;
}
static struct ast_context* find_context_locked (const char * context) [static, read]
lookup for a context with a given name,
Return values:
with conlock held if found.
NULL if not found.
Definition at line 4658 of file pbx.c.
References ast_copy_string(), ast_get_context_name(), ast_hashtab_lookup(), ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_contexts(), contexts_table, and fake_context::name.
Referenced by ast_add_extension(), ast_context_add_ignorepat(), ast_context_add_include(), ast_context_add_switch(), ast_context_remove_extension_callerid(), ast_context_remove_ignorepat(), ast_context_remove_include(), and ast_context_remove_switch().
{
   struct ast_context *c = NULL;
   struct fake_context item;
   ast_copy_string(item.name, context, sizeof(item.name));
   ast_rdlock_contexts();
   c = ast_hashtab_lookup(contexts_table,&item);
#ifdef NOTNOW
   while ( (c = ast_walk_contexts(c)) ) {
      if (!strcmp(ast_get_context_name(c), context))
         return c;
   }
#endif
   if (!c)
      ast_unlock_contexts();
   return c;
}
static char* func_args (char * function) [static]
return a pointer to the arguments of the function, and terminates the function name with '\0'
Definition at line 3338 of file pbx.c.
References ast_log(), and LOG_WARNING.
Referenced by ast_func_read(), and ast_func_write().
{
   char *args = strchr(function, '(');
   if (!args) {
      ast_log(LOG_WARNING, "Function '%s' doesn't contain parentheses.  Assuming null argument.\n", function);
   } else {
      char *p;
      *args++ = '\0';
      if ((p = strrchr(args, ')'))) {
         *p = '\0';
      } else {
         ast_log(LOG_WARNING, "Can't find trailing parenthesis for function '%s(%s'?\n", function, args);
      }
   }
   return args;
}
static struct ast_exten * get_canmatch_exten (struct match_char * node) [static, read]
Definition at line 1552 of file pbx.c.
References ast_log(), ast_exten::exten, match_char::exten, LOG_NOTICE, match_char::next_char, and match_char::x.
{
   /* find the exten at the end of the rope */
   struct match_char *node2 = node;
   for (node2 = node; node2; node2 = node2->next_char) {
      if (node2->exten) {
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"CanMatch_exten returns exten %s(%p)\n", node2->exten->exten, node2->exten);
#endif
         return node2->exten;
      }
   }
#ifdef NEED_DEBUG_HERE
   ast_log(LOG_NOTICE,"CanMatch_exten returns NULL, match_char=%s\n", node->x);
#endif
   return 0;
}
static unsigned get_range (char * src, int max, char *const names[], const char * msg) [static]
helper function to return a range up to max (7, 12, 31 respectively). names, if supplied, is an array of names that should be mapped to numbers.
Definition at line 6807 of file pbx.c.
References ast_log(), ast_strlen_zero(), LOG_WARNING, lookup_name(), and strsep().
Referenced by ast_build_timing().
{
   int start, end; /* start and ending position */
   unsigned int mask = 0;
   char *part;
   /* Check for whole range */
   if (ast_strlen_zero(src) || !strcmp(src, "*")) {
      return (1 << max) - 1;
   }
   while ((part = strsep(&src, "&"))) {
      /* Get start and ending position */
      char *endpart = strchr(part, '-');
      if (endpart) {
         *endpart++ = '\0';
      }
      /* Find the start */
      if ((start = lookup_name(part, names, max)) < 0) {
         ast_log(LOG_WARNING, "Invalid %s '%s', skipping element\n", msg, part);
         continue;
      }
      if (endpart) { /* find end of range */
         if ((end = lookup_name(endpart, names, max)) < 0) {
            ast_log(LOG_WARNING, "Invalid end %s '%s', skipping element\n", msg, endpart);
            continue;
         }
      } else {
         end = start;
      }
      /* Fill the mask. Remember that ranges are cyclic */
      mask |= (1 << end);   /* initialize with last element */
      while (start != end) {
         mask |= (1 << start);
         if (++start >= max) {
            start = 0;
         }
      }
   }
   return mask;
}
static void get_timerange (struct ast_timing * i, char * times) [static]
store a bitmask of valid times, one bit each 1 minute
Definition at line 6850 of file pbx.c.
References ast_log(), ast_strlen_zero(), LOG_WARNING, ast_timing::minmask, and strsep().
Referenced by ast_build_timing().
{
   char *endpart, *part;
   int x;
   int st_h, st_m;
   int endh, endm;
   int minute_start, minute_end;
   /* start disabling all times, fill the fields with 0's, as they may contain garbage */
   memset(i->minmask, 0, sizeof(i->minmask));
   /* 1-minute per bit */
   /* Star is all times */
   if (ast_strlen_zero(times) || !strcmp(times, "*")) {
      /* 48, because each hour takes 2 integers; 30 bits each */
      for (x = 0; x < 48; x++) {
         i->minmask[x] = 0x3fffffff; /* 30 bits */
      }
      return;
   }
   /* Otherwise expect a range */
   while ((part = strsep(&times, "&"))) {
      if (!(endpart = strchr(part, '-'))) {
         if (sscanf(part, "%2d:%2d", &st_h, &st_m) != 2 || st_h < 0 || st_h > 23 || st_m < 0 || st_m > 59) {
            ast_log(LOG_WARNING, "%s isn't a valid time.\n", part);
            continue;
         }
         i->minmask[st_h * 2 + (st_m >= 30 ? 1 : 0)] |= (1 << (st_m % 30));
         continue;
      }
      *endpart++ = '\0';
      /* why skip non digits? Mostly to skip spaces */
      while (*endpart && !isdigit(*endpart)) {
         endpart++;
      }
      if (!*endpart) {
         ast_log(LOG_WARNING, "Invalid time range starting with '%s-'.\n", part);
         continue;
      }
      if (sscanf(part, "%2d:%2d", &st_h, &st_m) != 2 || st_h < 0 || st_h > 23 || st_m < 0 || st_m > 59) {
         ast_log(LOG_WARNING, "'%s' isn't a valid start time.\n", part);
         continue;
      }
      if (sscanf(endpart, "%2d:%2d", &endh, &endm) != 2 || endh < 0 || endh > 23 || endm < 0 || endm > 59) {
         ast_log(LOG_WARNING, "'%s' isn't a valid end time.\n", endpart);
         continue;
      }
      minute_start = st_h * 60 + st_m;
      minute_end = endh * 60 + endm;
      /* Go through the time and enable each appropriate bit */
      for (x = minute_start; x != minute_end; x = (x + 1) % (24 * 60)) {
         i->minmask[x / 30] |= (1 << (x % 30));
      }
      /* Do the last one */
      i->minmask[x / 30] |= (1 << (x % 30));
   }
   /* All done */
   return;
}
static char* handle_debug_dialplan (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Send ack once.
Definition at line 5892 of file pbx.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_PBX_MAX_STACK, ast_strdupa, ast_strlen_zero(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_show_dialplan_context(), dialplan_counters::context_existence, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, show_debug_helper(), strsep(), dialplan_counters::total_context, ast_cli_entry::usage, and ast_cli_args::word.
{
   char *exten = NULL, *context = NULL;
   /* Variables used for different counters */
   struct dialplan_counters counters;
   const char *incstack[AST_PBX_MAX_STACK];
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan debug";
      e->usage =
         "Usage: dialplan debug [context]\n"
         "       Show dialplan context Trie(s). Usually only useful to folks debugging the deep internals of the fast pattern matcher\n";
      return NULL;
   case CLI_GENERATE:
      return complete_show_dialplan_context(a->line, a->word, a->pos, a->n);
   }
   memset(&counters, 0, sizeof(counters));
   if (a->argc != 2 && a->argc != 3)
      return CLI_SHOWUSAGE;
   /* we obtain [exten@]context? if yes, split them ... */
   /* note: we ignore the exten totally here .... */
   if (a->argc == 3) {
      if (strchr(a->argv[2], '@')) {   /* split into exten & context */
         context = ast_strdupa(a->argv[2]);
         exten = strsep(&context, "@");
         /* change empty strings to NULL */
         if (ast_strlen_zero(exten))
            exten = NULL;
      } else { /* no '@' char, only context given */
         context = a->argv[2];
      }
      if (ast_strlen_zero(context))
         context = NULL;
   }
   /* else Show complete dial plan, context and exten are NULL */
   show_debug_helper(a->fd, context, exten, &counters, NULL, 0, incstack);
   /* check for input failure and throw some error messages */
   if (context && !counters.context_existence) {
      ast_cli(a->fd, "There is no existence of '%s' context\n", context);
      return CLI_FAILURE;
   }
   ast_cli(a->fd,"-= %d %s. =-\n",
         counters.total_context, counters.total_context == 1 ? "context" : "contexts");
   /* everything ok */
   return CLI_SUCCESS;
}
static char* handle_set_chanvar (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 6269 of file pbx.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_unlock, ast_cli(), ast_complete_channels(), ast_get_channel_by_name_locked(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, pbx_builtin_setvar_helper(), ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_channel *chan;
   const char *chan_name, *var_name, *var_value;
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan set chanvar";
      e->usage =
         "Usage: dialplan set chanvar <channel> <varname> <value>\n"
         "       Set channel variable <varname> to <value>\n";
      return NULL;
   case CLI_GENERATE:
      return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
   }
   if (a->argc != e->args + 3)
      return CLI_SHOWUSAGE;
   chan_name = a->argv[e->args];
   var_name = a->argv[e->args + 1];
   var_value = a->argv[e->args + 2];
   if (!(chan = ast_get_channel_by_name_locked(chan_name))) {
      ast_cli(a->fd, "Channel '%s' not found\n", chan_name);
      return CLI_FAILURE;
   }
   pbx_builtin_setvar_helper(chan, var_name, var_value);
   ast_channel_unlock(chan);
   ast_cli(a->fd, "\n    -- Channel variable '%s' set to '%s' for '%s'\n",  var_name, var_value, chan_name);
   return CLI_SUCCESS;
}
static char* handle_set_extenpatternmatchnew (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 6304 of file pbx.c.
References ast_cli_args::argc, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, pbx_set_extenpatternmatchnew(), and ast_cli_entry::usage.
{
   int oldval = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan set extenpatternmatchnew true";
      e->usage =
         "Usage: dialplan set extenpatternmatchnew true|false\n"
         "       Use the NEW extension pattern matching algorithm, true or false.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   oldval =  pbx_set_extenpatternmatchnew(1);
   if (oldval)
      ast_cli(a->fd, "\n    -- Still using the NEW pattern match algorithm for extension names in the dialplan.\n");
   else
      ast_cli(a->fd, "\n    -- Switched to using the NEW pattern match algorithm for extension names in the dialplan.\n");
   return CLI_SUCCESS;
}
static char* handle_set_global (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 6247 of file pbx.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, pbx_builtin_setvar_helper(), and ast_cli_entry::usage.
{
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan set global";
      e->usage =
         "Usage: dialplan set global <name> <value>\n"
         "       Set global dialplan variable <name> to <value>\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != e->args + 2)
      return CLI_SHOWUSAGE;
   pbx_builtin_setvar_helper(NULL, a->argv[3], a->argv[4]);
   ast_cli(a->fd, "\n    -- Global variable '%s' set to '%s'\n", a->argv[3], a->argv[4]);
   return CLI_SUCCESS;
}
static char* handle_show_application (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 5261 of file pbx.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::n, ast_app::name, print_app_docs(), ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_app *aa;
   int app, no_registered_app = 1;
   char *ret = NULL;
   int which = 0;
   int wordlen;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show application";
      e->usage =
         "Usage: core show application <application> [<application> [<application> [...]]]\n"
         "       Describes a particular application.\n";
      return NULL;
   case CLI_GENERATE:
      /*
       * There is a possibility to show informations about more than one
       * application at one time. You can type 'show application Dial Echo' and
       * you will see informations about these two applications ...
       */
      wordlen = strlen(a->word);
      /* return the n-th [partial] matching entry */
      AST_RWLIST_RDLOCK(&apps);
      AST_RWLIST_TRAVERSE(&apps, aa, list) {
         if (!strncasecmp(a->word, aa->name, wordlen) && ++which > a->n) {
            ret = ast_strdup(aa->name);
            break;
         }
      }
      AST_RWLIST_UNLOCK(&apps);
      return ret;
   }
   if (a->argc < 4) {
      return CLI_SHOWUSAGE;
   }
   AST_RWLIST_RDLOCK(&apps);
   AST_RWLIST_TRAVERSE(&apps, aa, list) {
      /* Check for each app that was supplied as an argument */
      for (app = 3; app < a->argc; app++) {
         if (strcasecmp(aa->name, a->argv[app])) {
            continue;
         }
         /* We found it! */
         no_registered_app = 0;
         print_app_docs(aa, a->fd);
      }
   }
   AST_RWLIST_UNLOCK(&apps);
   /* we found at least one app? no? */
   if (no_registered_app) {
      ast_cli(a->fd, "Your application(s) is (are) not registered\n");
      return CLI_FAILURE;
   }
   return CLI_SUCCESS;
}
static char* handle_show_applications (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 5481 of file pbx.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_complete(), AST_RWLIST_EMPTY, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_app::description, ast_cli_args::fd, ast_cli_args::n, ast_app::name, ast_cli_args::pos, strcasestr(), ast_app::synopsis, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_app *aa;
   int like = 0, describing = 0;
   int total_match = 0;    /* Number of matches in like clause */
   int total_apps = 0;     /* Number of apps registered */
   static char* choices[] = { "like", "describing", NULL };
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show applications [like|describing]";
      e->usage =
         "Usage: core show applications [{like|describing} <text>]\n"
         "       List applications which are currently available.\n"
         "       If 'like', <text> will be a substring of the app name\n"
         "       If 'describing', <text> will be a substring of the description\n";
      return NULL;
   case CLI_GENERATE:
      return (a->pos != 3) ? NULL : ast_cli_complete(a->word, choices, a->n);
   }
   AST_RWLIST_RDLOCK(&apps);
   if (AST_RWLIST_EMPTY(&apps)) {
      ast_cli(a->fd, "There are no registered applications\n");
      AST_RWLIST_UNLOCK(&apps);
      return CLI_SUCCESS;
   }
   /* core list applications like <keyword> */
   if ((a->argc == 5) && (!strcmp(a->argv[3], "like"))) {
      like = 1;
   } else if ((a->argc > 4) && (!strcmp(a->argv[3], "describing"))) {
      describing = 1;
   }
   /* core list applications describing <keyword1> [<keyword2>] [...] */
   if ((!like) && (!describing)) {
      ast_cli(a->fd, "    -= Registered Asterisk Applications =-\n");
   } else {
      ast_cli(a->fd, "    -= Matching Asterisk Applications =-\n");
   }
   AST_RWLIST_TRAVERSE(&apps, aa, list) {
      int printapp = 0;
      total_apps++;
      if (like) {
         if (strcasestr(aa->name, a->argv[4])) {
            printapp = 1;
            total_match++;
         }
      } else if (describing) {
         if (aa->description) {
            /* Match all words on command line */
            int i;
            printapp = 1;
            for (i = 4; i < a->argc; i++) {
               if (!strcasestr(aa->description, a->argv[i])) {
                  printapp = 0;
               } else {
                  total_match++;
               }
            }
         }
      } else {
         printapp = 1;
      }
      if (printapp) {
         ast_cli(a->fd,"  %20s: %s\n", aa->name, aa->synopsis ? aa->synopsis : "<Synopsis not available>");
      }
   }
   if ((!like) && (!describing)) {
      ast_cli(a->fd, "    -= %d Applications Registered =-\n",total_apps);
   } else {
      ast_cli(a->fd, "    -= %d Applications Matching =-\n",total_match);
   }
   AST_RWLIST_UNLOCK(&apps);
   return CLI_SUCCESS;
}
static char* handle_show_chanvar (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
CLI support for listing chanvar's variables in a parseable way.
Definition at line 6215 of file pbx.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_unlock, ast_cli(), ast_complete_channels(), ast_get_channel_by_name_locked(), ast_str_alloca, ast_str_buffer(), ast_str_strlen(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, pbx_builtin_serialize_variables(), ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_channel *chan = NULL;
   struct ast_str *vars = ast_str_alloca(BUFSIZ * 4); /* XXX large because we might have lots of channel vars */
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan show chanvar";
      e->usage =
         "Usage: dialplan show chanvar <channel>\n"
         "       List current channel variables and their values\n";
      return NULL;
   case CLI_GENERATE:
      return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
   }
   if (a->argc != e->args + 1)
      return CLI_SHOWUSAGE;
   if (!(chan = ast_get_channel_by_name_locked(a->argv[e->args]))) {
      ast_cli(a->fd, "Channel '%s' not found\n", a->argv[e->args]);
      return CLI_FAILURE;
   }
   pbx_builtin_serialize_variables(chan, &vars);
   if (ast_str_strlen(vars)) {
      ast_cli(a->fd, "\nVariables for channel %s:\n%s\n", a->argv[e->args], ast_str_buffer(vars));
   }
   ast_channel_unlock(chan);
   return CLI_SUCCESS;
}
static char* handle_show_dialplan (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 5825 of file pbx.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_PBX_MAX_STACK, ast_strdupa, ast_strlen_zero(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_show_dialplan_context(), dialplan_counters::context_existence, dialplan_counters::extension_existence, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, show_dialplan_helper(), strsep(), dialplan_counters::total_context, dialplan_counters::total_exten, dialplan_counters::total_prio, ast_cli_entry::usage, and ast_cli_args::word.
{
   char *exten = NULL, *context = NULL;
   /* Variables used for different counters */
   struct dialplan_counters counters;
   const char *incstack[AST_PBX_MAX_STACK];
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan show";
      e->usage =
         "Usage: dialplan show [[exten@]context]\n"
         "       Show dialplan\n";
      return NULL;
   case CLI_GENERATE:
      return complete_show_dialplan_context(a->line, a->word, a->pos, a->n);
   }
   memset(&counters, 0, sizeof(counters));
   if (a->argc != 2 && a->argc != 3)
      return CLI_SHOWUSAGE;
   /* we obtain [exten@]context? if yes, split them ... */
   if (a->argc == 3) {
      if (strchr(a->argv[2], '@')) {   /* split into exten & context */
         context = ast_strdupa(a->argv[2]);
         exten = strsep(&context, "@");
         /* change empty strings to NULL */
         if (ast_strlen_zero(exten))
            exten = NULL;
      } else { /* no '@' char, only context given */
         context = a->argv[2];
      }
      if (ast_strlen_zero(context))
         context = NULL;
   }
   /* else Show complete dial plan, context and exten are NULL */
   show_dialplan_helper(a->fd, context, exten, &counters, NULL, 0, incstack);
   /* check for input failure and throw some error messages */
   if (context && !counters.context_existence) {
      ast_cli(a->fd, "There is no existence of '%s' context\n", context);
      return CLI_FAILURE;
   }
   if (exten && !counters.extension_existence) {
      if (context)
         ast_cli(a->fd, "There is no existence of %s@%s extension\n",
            exten, context);
      else
         ast_cli(a->fd,
            "There is no existence of '%s' extension in all contexts\n",
            exten);
      return CLI_FAILURE;
   }
   ast_cli(a->fd,"-= %d %s (%d %s) in %d %s. =-\n",
            counters.total_exten, counters.total_exten == 1 ? "extension" : "extensions",
            counters.total_prio, counters.total_prio == 1 ? "priority" : "priorities",
            counters.total_context, counters.total_context == 1 ? "context" : "contexts");
   /* everything ok */
   return CLI_SUCCESS;
}
static char* handle_show_function (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 3095 of file pbx.c.
References ast_custom_function::acflist, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_custom_function_find(), ast_free, ast_malloc, AST_MAX_APP, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_strdup, AST_TERM_MAX_ESCAPE_CHARS, AST_XML_DOC, ast_xmldoc_printable(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, COLOR_CYAN, COLOR_MAGENTA, ast_cli_entry::command, description, ast_custom_function::docsrc, ast_cli_args::fd, ast_cli_args::n, ast_custom_function::name, S_OR, synopsis, term_color(), ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_custom_function *acf;
   /* Maximum number of characters added by terminal coloring is 22 */
   char infotitle[64 + AST_MAX_APP + 22], syntitle[40], destitle[40], argtitle[40], seealsotitle[40];
   char info[64 + AST_MAX_APP], *synopsis = NULL, *description = NULL, *seealso = NULL;
   char stxtitle[40], *syntax = NULL, *arguments = NULL;
   int syntax_size, description_size, synopsis_size, arguments_size, seealso_size;
   char *ret = NULL;
   int which = 0;
   int wordlen;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show function";
      e->usage =
         "Usage: core show function <function>\n"
         "       Describe a particular dialplan function.\n";
      return NULL;
   case CLI_GENERATE:
      wordlen = strlen(a->word);
      /* case-insensitive for convenience in this 'complete' function */
      AST_RWLIST_RDLOCK(&acf_root);
      AST_RWLIST_TRAVERSE(&acf_root, acf, acflist) {
         if (!strncasecmp(a->word, acf->name, wordlen) && ++which > a->n) {
            ret = ast_strdup(acf->name);
            break;
         }
      }
      AST_RWLIST_UNLOCK(&acf_root);
      return ret;
   }
   if (a->argc < 4) {
      return CLI_SHOWUSAGE;
   }
   if (!(acf = ast_custom_function_find(a->argv[3]))) {
      ast_cli(a->fd, "No function by that name registered.\n");
      return CLI_FAILURE;
   }
   syntax_size = strlen(S_OR(acf->syntax, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
   if (!(syntax = ast_malloc(syntax_size))) {
      ast_cli(a->fd, "Memory allocation failure!\n");
      return CLI_FAILURE;
   }
   snprintf(info, sizeof(info), "\n  -= Info about function '%s' =- \n\n", acf->name);
   term_color(infotitle, info, COLOR_MAGENTA, 0, sizeof(infotitle));
   term_color(syntitle, "[Synopsis]\n", COLOR_MAGENTA, 0, 40);
   term_color(destitle, "[Description]\n", COLOR_MAGENTA, 0, 40);
   term_color(stxtitle, "[Syntax]\n", COLOR_MAGENTA, 0, 40);
   term_color(argtitle, "[Arguments]\n", COLOR_MAGENTA, 0, 40);
   term_color(seealsotitle, "[See Also]\n", COLOR_MAGENTA, 0, 40);
   term_color(syntax, S_OR(acf->syntax, "Not available"), COLOR_CYAN, 0, syntax_size);
#ifdef AST_XML_DOCS
   if (acf->docsrc == AST_XML_DOC) {
      arguments = ast_xmldoc_printable(S_OR(acf->arguments, "Not available"), 1);
      synopsis = ast_xmldoc_printable(S_OR(acf->synopsis, "Not available"), 1);
      description = ast_xmldoc_printable(S_OR(acf->desc, "Not available"), 1);
      seealso = ast_xmldoc_printable(S_OR(acf->seealso, "Not available"), 1);
   } else
#endif
   {
      synopsis_size = strlen(S_OR(acf->synopsis, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      synopsis = ast_malloc(synopsis_size);
      description_size = strlen(S_OR(acf->desc, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      description = ast_malloc(description_size);
      arguments_size = strlen(S_OR(acf->arguments, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      arguments = ast_malloc(arguments_size);
      seealso_size = strlen(S_OR(acf->seealso, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      seealso = ast_malloc(seealso_size);
      /* check allocated memory. */
      if (!synopsis || !description || !arguments || !seealso) {
         ast_free(synopsis);
         ast_free(description);
         ast_free(arguments);
         ast_free(seealso);
         ast_free(syntax);
         return CLI_FAILURE;
      }
      term_color(arguments, S_OR(acf->arguments, "Not available"), COLOR_CYAN, 0, arguments_size);
      term_color(synopsis, S_OR(acf->synopsis, "Not available"), COLOR_CYAN, 0, synopsis_size);
      term_color(description, S_OR(acf->desc, "Not available"), COLOR_CYAN, 0, description_size);
      term_color(seealso, S_OR(acf->seealso, "Not available"), COLOR_CYAN, 0, seealso_size);
   }
   ast_cli(a->fd, "%s%s%s\n\n%s%s\n\n%s%s\n\n%s%s\n\n%s%s\n",
         infotitle, syntitle, synopsis, destitle, description,
         stxtitle, syntax, argtitle, arguments, seealsotitle, seealso);
   ast_free(arguments);
   ast_free(synopsis);
   ast_free(description);
   ast_free(seealso);
   ast_free(syntax);
   return CLI_SUCCESS;
}
static char* handle_show_functions (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 3053 of file pbx.c.
References ast_custom_function::acflist, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_custom_function::name, S_OR, and ast_cli_entry::usage.
{
   struct ast_custom_function *acf;
   int count_acf = 0;
   int like = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show functions [like]";
      e->usage =
         "Usage: core show functions [like <text>]\n"
         "       List builtin functions, optionally only those matching a given string\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc == 5 && (!strcmp(a->argv[3], "like")) ) {
      like = 1;
   } else if (a->argc != 3) {
      return CLI_SHOWUSAGE;
   }
   ast_cli(a->fd, "%s Custom Functions:\n--------------------------------------------------------------------------------\n", like ? "Matching" : "Installed");
   AST_RWLIST_RDLOCK(&acf_root);
   AST_RWLIST_TRAVERSE(&acf_root, acf, acflist) {
      if (!like || strstr(acf->name, a->argv[4])) {
         count_acf++;
         ast_cli(a->fd, "%-20.20s  %-35.35s  %s\n",
            S_OR(acf->name, ""),
            S_OR(acf->syntax, ""),
            S_OR(acf->synopsis, ""));
      }
   }
   AST_RWLIST_UNLOCK(&acf_root);
   ast_cli(a->fd, "%d %scustom functions installed.\n", count_acf, like ? "matching " : "");
   return CLI_SUCCESS;
}
static char* handle_show_globals (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
CLI support for listing global variables in a parseable way.
Definition at line 6157 of file pbx.c.
References ast_cli(), AST_LIST_TRAVERSE, ast_rwlock_rdlock(), ast_rwlock_unlock(), ast_var_name(), ast_var_value(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, globals, globalslock, and ast_cli_entry::usage.
{
   int i = 0;
   struct ast_var_t *newvariable;
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan show globals";
      e->usage =
         "Usage: dialplan show globals\n"
         "       List current global dialplan variables and their values\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   ast_rwlock_rdlock(&globalslock);
   AST_LIST_TRAVERSE (&globals, newvariable, entries) {
      i++;
      ast_cli(a->fd, "   %s=%s\n", ast_var_name(newvariable), ast_var_value(newvariable));
   }
   ast_rwlock_unlock(&globalslock);
   ast_cli(a->fd, "\n    -- %d variable(s)\n", i);
   return CLI_SUCCESS;
}
static char* handle_show_hint (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handle_show_hint: CLI support for listing registered dial plan hint
Definition at line 5397 of file pbx.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_extension_state2str(), ast_get_context_name(), ast_get_extension_app(), ast_get_extension_context(), ast_get_extension_name(), AST_LIST_TRAVERSE, AST_RWLIST_EMPTY, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_hint::callbacks, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_core_show_hint(), ast_hint::exten, ast_cli_args::fd, ast_hint::laststate, ast_cli_args::line, ast_cli_args::n, num, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_hint *hint;
   int watchers;
   int num = 0, extenlen;
   struct ast_state_cb *watcher;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show hint";
      e->usage =
         "Usage: core show hint <exten>\n"
         "       List registered hint\n";
      return NULL;
   case CLI_GENERATE:
      return complete_core_show_hint(a->line, a->word, a->pos, a->n);
   }
   if (a->argc < 4)
      return CLI_SHOWUSAGE;
   AST_RWLIST_RDLOCK(&hints);
   if (AST_RWLIST_EMPTY(&hints)) {
      ast_cli(a->fd, "There are no registered dialplan hints\n");
      AST_RWLIST_UNLOCK(&hints);
      return CLI_SUCCESS;
   }
   extenlen = strlen(a->argv[3]);
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      if (!strncasecmp(ast_get_extension_name(hint->exten), a->argv[3], extenlen)) {
         watchers = 0;
         AST_LIST_TRAVERSE(&hint->callbacks, watcher, entry) {
            watchers++;
         }
         ast_cli(a->fd, "   %20s@%-20.20s: %-20.20s  State:%-15.15s Watchers %2d\n",
            ast_get_extension_name(hint->exten),
            ast_get_context_name(ast_get_extension_context(hint->exten)),
            ast_get_extension_app(hint->exten),
            ast_extension_state2str(hint->laststate), watchers);
         num++;
      }
   }
   AST_RWLIST_UNLOCK(&hints);
   if (!num)
      ast_cli(a->fd, "No hints matching extension %s\n", a->argv[3]);
   else
      ast_cli(a->fd, "%d hint%s matching extension %s\n", num, (num!=1 ? "s":""), a->argv[3]);
   return CLI_SUCCESS;
}
static char* handle_show_hints (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handle_show_hints: CLI support for listing registered dial plan hints
Definition at line 5326 of file pbx.c.
References ast_cli(), ast_extension_state2str(), ast_get_context_name(), ast_get_extension_app(), ast_get_extension_context(), ast_get_extension_name(), AST_LIST_TRAVERSE, AST_RWLIST_EMPTY, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_hint::callbacks, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_hint::exten, ast_cli_args::fd, ast_hint::laststate, num, and ast_cli_entry::usage.
{
   struct ast_hint *hint;
   int num = 0;
   int watchers;
   struct ast_state_cb *watcher;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show hints";
      e->usage =
         "Usage: core show hints\n"
         "       List registered hints\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   AST_RWLIST_RDLOCK(&hints);
   if (AST_RWLIST_EMPTY(&hints)) {
      ast_cli(a->fd, "There are no registered dialplan hints\n");
      AST_RWLIST_UNLOCK(&hints);
      return CLI_SUCCESS;
   }
   /* ... we have hints ... */
   ast_cli(a->fd, "\n    -= Registered Asterisk Dial Plan Hints =-\n");
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      watchers = 0;
      AST_LIST_TRAVERSE(&hint->callbacks, watcher, entry) {
         watchers++;
      }
      ast_cli(a->fd, "   %20s@%-20.20s: %-20.20s  State:%-15.15s Watchers %2d\n",
         ast_get_extension_name(hint->exten),
         ast_get_context_name(ast_get_extension_context(hint->exten)),
         ast_get_extension_app(hint->exten),
         ast_extension_state2str(hint->laststate), watchers);
      num++;
   }
   ast_cli(a->fd, "----------------\n");
   ast_cli(a->fd, "- %d hints registered\n", num);
   AST_RWLIST_UNLOCK(&hints);
   return CLI_SUCCESS;
}
static char* handle_show_switches (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handle_show_switches: CLI support for listing registered dial plan switches
Definition at line 5449 of file pbx.c.
References ast_cli(), AST_RWLIST_EMPTY, AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_switch::description, ast_cli_args::fd, ast_switch::name, and ast_cli_entry::usage.
{
   struct ast_switch *sw;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show switches";
      e->usage =
         "Usage: core show switches\n"
         "       List registered switches\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   AST_RWLIST_RDLOCK(&switches);
   if (AST_RWLIST_EMPTY(&switches)) {
      AST_RWLIST_UNLOCK(&switches);
      ast_cli(a->fd, "There are no registered alternative switches\n");
      return CLI_SUCCESS;
   }
   ast_cli(a->fd, "\n    -= Registered Asterisk Alternative Switches =-\n");
   AST_RWLIST_TRAVERSE(&switches, sw, list)
      ast_cli(a->fd, "%s: %s\n", sw->name, sw->description);
   AST_RWLIST_UNLOCK(&switches);
   return CLI_SUCCESS;
}
static int handle_statechange (void * datap) [static]
Definition at line 3843 of file pbx.c.
References ast_copy_string(), ast_extension_state2(), ast_free, ast_get_extension_app(), AST_LIST_TRAVERSE, AST_MAX_EXTENSION, ast_rdlock_contexts(), AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, ast_unlock_contexts(), buf, ast_state_cb::callback, ast_hint::callbacks, ast_state_cb::data, statechange::dev, ast_exten::exten, ast_hint::exten, ast_hint::laststate, ast_context::name, ast_exten::parent, parse(), and strsep().
Referenced by device_state_cb().
{
   struct ast_hint *hint;
   struct statechange *sc = datap;
   ast_rdlock_contexts();
   AST_RWLIST_RDLOCK(&hints);
   AST_RWLIST_TRAVERSE(&hints, hint, list) {
      struct ast_state_cb *cblist;
      char buf[AST_MAX_EXTENSION];
      char *parse = buf;
      char *cur;
      int state;
      ast_copy_string(buf, ast_get_extension_app(hint->exten), sizeof(buf));
      while ( (cur = strsep(&parse, "&")) ) {
         if (!strcasecmp(cur, sc->dev)) {
            break;
         }
      }
      if (!cur) {
         continue;
      }
      /* Get device state for this hint */
      state = ast_extension_state2(hint->exten);
      if ((state == -1) || (state == hint->laststate)) {
         continue;
      }
      /* Device state changed since last check - notify the watchers */
      /* For general callbacks */
      AST_LIST_TRAVERSE(&statecbs, cblist, entry) {
         cblist->callback(hint->exten->parent->name, hint->exten->exten, state, cblist->data);
      }
      /* For extension callbacks */
      AST_LIST_TRAVERSE(&hint->callbacks, cblist, entry) {
         cblist->callback(hint->exten->parent->name, hint->exten->exten, state, cblist->data);
      }
      hint->laststate = state;   /* record we saw the change */
   }
   AST_RWLIST_UNLOCK(&hints);
   ast_unlock_contexts();
   ast_free(sc);
   return 0;
}
static char* handle_unset_extenpatternmatchnew (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 6332 of file pbx.c.
References ast_cli_args::argc, ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, pbx_set_extenpatternmatchnew(), and ast_cli_entry::usage.
{
   int oldval = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "dialplan set extenpatternmatchnew false";
      e->usage =
         "Usage: dialplan set extenpatternmatchnew true|false\n"
         "       Use the NEW extension pattern matching algorithm, true or false.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   oldval =  pbx_set_extenpatternmatchnew(0);
   if (!oldval)
      ast_cli(a->fd, "\n    -- Still using the OLD pattern match algorithm for extension names in the dialplan.\n");
   else
      ast_cli(a->fd, "\n    -- Switched to using the OLD pattern match algorithm for extension names in the dialplan.\n");
   return CLI_SUCCESS;
}
static int hashtab_compare_exten_labels (const void * ah_a, const void * ah_b) [static]
Definition at line 1030 of file pbx.c.
References ast_exten::label, and S_OR.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = ah_a;
   const struct ast_exten *bc = ah_b;
   return strcmp(S_OR(ac->label, ""), S_OR(bc->label, ""));
}
static int hashtab_compare_exten_numbers (const void * ah_a, const void * ah_b) [static]
Definition at line 1023 of file pbx.c.
References ast_exten::priority.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = ah_a;
   const struct ast_exten *bc = ah_b;
   return ac->priority != bc->priority;
}
static int hashtab_compare_extens (const void * ha_a, const void * ah_b) [static]
Definition at line 1004 of file pbx.c.
References ast_exten::cidmatch, ast_exten::exten, and ast_exten::matchcid.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = ah_a;
   const struct ast_exten *bc = ah_b;
   int x = strcmp(ac->exten, bc->exten);
   if (x) { /* if exten names are diff, then return */
      return x;
   }
   /* but if they are the same, do the cidmatch values match? */
   if (ac->matchcid && bc->matchcid) {
      return strcmp(ac->cidmatch,bc->cidmatch);
   } else if (!ac->matchcid && !bc->matchcid) {
      return 0; /* if there's no matchcid on either side, then this is a match */
   } else {
      return 1; /* if there's matchcid on one but not the other, they are different */
   }
}
static unsigned int hashtab_hash_extens (const void * obj) [static]
Definition at line 1043 of file pbx.c.
References ast_hashtab_hash_string(), ast_exten::cidmatch, ast_exten::exten, and ast_exten::matchcid.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = obj;
   unsigned int x = ast_hashtab_hash_string(ac->exten);
   unsigned int y = 0;
   if (ac->matchcid)
      y = ast_hashtab_hash_string(ac->cidmatch);
   return x+y;
}
static unsigned int hashtab_hash_labels (const void * obj) [static]
Definition at line 1059 of file pbx.c.
References ast_hashtab_hash_string(), ast_exten::label, and S_OR.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = obj;
   return ast_hashtab_hash_string(S_OR(ac->label, ""));
}
static unsigned int hashtab_hash_priority (const void * obj) [static]
Definition at line 1053 of file pbx.c.
References ast_hashtab_hash_int(), and ast_exten::priority.
Referenced by ast_add_extension2_lockopt().
{
   const struct ast_exten *ac = obj;
   return ast_hashtab_hash_int(ac->priority);
}
static int include_valid (struct ast_include * i) [inline, static]
Definition at line 1391 of file pbx.c.
References ast_check_timing(), ast_include::hastime, and ast_include::timing.
Referenced by pbx_find_extension().
{
   if (!i->hastime)
      return 1;
   return ast_check_timing(&(i->timing));
}
static int increase_call_count (const struct ast_channel * c) [static]
Increase call count for channel.
Return values:
0 on success
non-zero if a configured limit (maxcalls, maxload, minmemfree) was reached
Definition at line 4470 of file pbx.c.
References ast_log(), ast_mutex_lock(), ast_mutex_unlock(), countcalls, getloadavg(), LOG_WARNING, maxcalllock, option_maxcalls, option_maxload, and totalcalls.
Referenced by ast_pbx_run_args(), and ast_pbx_start().
{
   int failed = 0;
   double curloadavg;
#if defined(HAVE_SYSINFO)
   long curfreemem;
   struct sysinfo sys_info;
#endif
   ast_mutex_lock(&maxcalllock);
   if (option_maxcalls) {
      if (countcalls >= option_maxcalls) {
         ast_log(LOG_WARNING, "Maximum call limit of %d calls exceeded by '%s'!\n", option_maxcalls, c->name);
         failed = -1;
      }
   }
   if (option_maxload) {
      getloadavg(&curloadavg, 1);
      if (curloadavg >= option_maxload) {
         ast_log(LOG_WARNING, "Maximum loadavg limit of %f load exceeded by '%s' (currently %f)!\n", option_maxload, c->name, curloadavg);
         failed = -1;
      }
   }
#if defined(HAVE_SYSINFO)
   if (option_minmemfree) {
      if (!sysinfo(&sys_info)) {
         /* make sure that the free system memory is above the configured low watermark
          * convert the amount of freeram from mem_units to MB */
         curfreemem = sys_info.freeram / sys_info.mem_unit;
         curfreemem /= 1024 * 1024;
         if (curfreemem < option_minmemfree) {
            ast_log(LOG_WARNING, "Available system memory (~%ldMB) is below the configured low watermark (%ldMB)\n", curfreemem, option_minmemfree);
            failed = -1;
         }
      }
   }
#endif
   if (!failed) {
      countcalls++;
      totalcalls++;
   }
   ast_mutex_unlock(&maxcalllock);
   return failed;
}
static void insert_in_next_chars_alt_char_list (struct match_char ** parent_ptr, struct match_char * node) [static]
Definition at line 1799 of file pbx.c.
References match_char::alt_char, and match_char::specificity.
Referenced by add_pattern_node().
{
   struct match_char *curr, *lcurr;
   /* insert node into the tree at "current", so the alt_char list from current is
      sorted in increasing value as you go to the leaves */
   if (!(*parent_ptr)) {
      *parent_ptr = node;
   } else {
      if ((*parent_ptr)->specificity > node->specificity) {
         /* insert at head */
         node->alt_char = (*parent_ptr);
         *parent_ptr = node;
      } else {
         lcurr = *parent_ptr;
         for (curr = (*parent_ptr)->alt_char; curr; curr = curr->alt_char) {
            if (curr->specificity > node->specificity) {
               node->alt_char = curr;
               lcurr->alt_char = node;
               break;
            }
            lcurr = curr;
         }
         if (!curr) {
            lcurr->alt_char = node;
         }
      }
   }
}
int load_pbx (void)
Provided by pbx.c
Definition at line 9302 of file pbx.c.
References __ast_custom_function_register(), ARRAY_LEN, ast_cli_register_multiple(), AST_EVENT_DEVICE_STATE, AST_EVENT_IE_END, ast_event_subscribe(), ast_log(), ast_manager_register2(), ast_register_application2(), ast_taskprocessor_get(), ast_verb, builtins, device_state_cb(), device_state_sub, EVENT_FLAG_CONFIG, EVENT_FLAG_REPORTING, exception_function, LOG_ERROR, LOG_WARNING, manager_show_dialplan(), mandescr_show_dialplan, and pbx_cli.
Referenced by main().
{
   int x;
   /* Initialize the PBX */
   ast_verb(1, "Asterisk PBX Core Initializing\n");
   if (!(device_state_tps = ast_taskprocessor_get("pbx-core", 0))) {
      ast_log(LOG_WARNING, "failed to create pbx-core taskprocessor\n");
   }
   ast_verb(1, "Registering builtin applications:\n");
   ast_cli_register_multiple(pbx_cli, ARRAY_LEN(pbx_cli));
   __ast_custom_function_register(&exception_function, NULL);
   /* Register builtin applications */
   for (x = 0; x < ARRAY_LEN(builtins); x++) {
      ast_verb(1, "[%s]\n", builtins[x].name);
      if (ast_register_application2(builtins[x].name, builtins[x].execute, NULL, NULL, NULL)) {
         ast_log(LOG_ERROR, "Unable to register builtin application '%s'\n", builtins[x].name);
         return -1;
      }
   }
   /* Register manager application */
   ast_manager_register2("ShowDialPlan", EVENT_FLAG_CONFIG | EVENT_FLAG_REPORTING, manager_show_dialplan, "List dialplan", mandescr_show_dialplan);
   if (!(device_state_sub = ast_event_subscribe(AST_EVENT_DEVICE_STATE, device_state_cb, NULL,
         AST_EVENT_IE_END))) {
      return -1;
   }
   return 0;
}
void log_match_char_tree (struct match_char * node, char * prefix)
Definition at line 1494 of file pbx.c.
References match_char::alt_char, ast_debug, ast_str_alloca, ast_str_buffer(), ast_str_set(), match_char::deleted, ast_exten::exten, match_char::exten, match_char::is_pattern, match_char::next_char, match_char::specificity, and match_char::x.
Referenced by ast_context_remove_extension_callerid2(), and pbx_find_extension().
{
   char extenstr[40];
   struct ast_str *my_prefix = ast_str_alloca(1024);
   extenstr[0] = '\0';
   if (node && node->exten && node->exten)
      snprintf(extenstr, sizeof(extenstr), "(%p)", node->exten);
   if (strlen(node->x) > 1) {
      ast_debug(1, "%s[%s]:%c:%c:%d:%s%s%s\n", prefix, node->x, node->is_pattern ? 'Y':'N',
         node->deleted? 'D':'-', node->specificity, node->exten? "EXTEN:":"",
         node->exten ? node->exten->exten : "", extenstr);
   } else {
      ast_debug(1, "%s%s:%c:%c:%d:%s%s%s\n", prefix, node->x, node->is_pattern ? 'Y':'N',
         node->deleted? 'D':'-', node->specificity, node->exten? "EXTEN:":"",
         node->exten ? node->exten->exten : "", extenstr);
   }
   ast_str_set(&my_prefix, 0, "%s+       ", prefix);
   if (node->next_char)
      log_match_char_tree(node->next_char, ast_str_buffer(my_prefix));
   if (node->alt_char)
      log_match_char_tree(node->alt_char, prefix);
}
static int lookup_name (const char * s, char *const names[], int max) [static]
Helper for get_range. return the index of the matching entry, starting from 1. If names is not supplied, try numeric values.
Definition at line 6784 of file pbx.c.
Referenced by get_range().
{
   int i;
   if (names && *s > '9') {
      for (i = 0; names[i]; i++) {
         if (!strcasecmp(s, names[i])) {
            return i;
         }
      }
   }
   /* Allow months and weekdays to be specified as numbers, as well */
   if (sscanf(s, "%2d", &i) == 1 && i >= 1 && i <= max) {
      /* What the array offset would have been: "1" would be at offset 0 */
      return i - 1;
   }
   return -1; /* error return */
}
static void manager_dpsendack (struct mansession * s, const struct message * m) [static]
Send ack once.
Definition at line 5948 of file pbx.c.
References astman_send_listack().
Referenced by manager_show_dialplan_helper().
{
   astman_send_listack(s, m, "DialPlan list will follow", "start");
}
static int manager_show_dialplan (struct mansession * s, const struct message * m) [static]
Manager listing of dial plan.
Definition at line 6094 of file pbx.c.
References ast_strlen_zero(), astman_get_header(), astman_send_error(), dialplan_counters::context_existence, EVENT_FLAG_CONFIG, dialplan_counters::extension_existence, manager_event, manager_show_dialplan_helper(), dialplan_counters::total_context, dialplan_counters::total_exten, dialplan_counters::total_items, and dialplan_counters::total_prio.
Referenced by load_pbx().
{
   const char *exten, *context;
   const char *id = astman_get_header(m, "ActionID");
   char idtext[256];
   int res;
   /* Variables used for different counters */
   struct dialplan_counters counters;
   if (!ast_strlen_zero(id))
      snprintf(idtext, sizeof(idtext), "ActionID: %s\r\n", id);
   else
      idtext[0] = '\0';
   memset(&counters, 0, sizeof(counters));
   exten = astman_get_header(m, "Extension");
   context = astman_get_header(m, "Context");
   res = manager_show_dialplan_helper(s, m, idtext, context, exten, &counters, NULL);
   if (context && !counters.context_existence) {
      char errorbuf[BUFSIZ];
      snprintf(errorbuf, sizeof(errorbuf), "Did not find context %s", context);
      astman_send_error(s, m, errorbuf);
      return 0;
   }
   if (exten && !counters.extension_existence) {
      char errorbuf[BUFSIZ];
      if (context)
         snprintf(errorbuf, sizeof(errorbuf), "Did not find extension %s@%s", exten, context);
      else
         snprintf(errorbuf, sizeof(errorbuf), "Did not find extension %s in any context", exten);
      astman_send_error(s, m, errorbuf);
      return 0;
   }
   manager_event(EVENT_FLAG_CONFIG, "ShowDialPlanComplete",
      "EventList: Complete\r\n"
      "ListItems: %d\r\n"
      "ListExtensions: %d\r\n"
      "ListPriorities: %d\r\n"
      "ListContexts: %d\r\n"
      "%s"
      "\r\n", counters.total_items, counters.total_exten, counters.total_prio, counters.total_context, idtext);
   /* everything ok */
   return 0;
}
static int manager_show_dialplan_helper (struct mansession * s, const struct message * m, const char * actionidtext, const char * context, const char * exten, struct dialplan_counters * dpc, struct ast_include * rinclude) [static]
Show dialplan extensions XXX this function is similar but not exactly the same as the CLI's show dialplan. Must check whether the difference is intentional or not.
Definition at line 5957 of file pbx.c.
References ast_debug, ast_extension_match(), ast_get_context_name(), ast_get_extension_app(), ast_get_extension_app_data(), ast_get_extension_label(), ast_get_extension_name(), ast_get_extension_priority(), ast_get_extension_registrar(), ast_get_ignorepat_name(), ast_get_ignorepat_registrar(), ast_get_include_name(), ast_get_include_registrar(), ast_get_switch_data(), ast_get_switch_name(), ast_get_switch_registrar(), ast_log(), AST_MAX_EXTENSION, ast_rdlock_context(), ast_rdlock_contexts(), ast_strlen_zero(), ast_unlock_context(), ast_unlock_contexts(), ast_walk_context_extensions(), ast_walk_context_ignorepats(), ast_walk_context_includes(), ast_walk_context_switches(), ast_walk_contexts(), ast_walk_extension_priorities(), astman_append(), astman_send_error(), dialplan_counters::context_existence, dialplan_counters::extension_existence, LOG_WARNING, manager_dpsendack(), PRIORITY_HINT, dialplan_counters::total_context, dialplan_counters::total_exten, dialplan_counters::total_items, and dialplan_counters::total_prio.
Referenced by manager_show_dialplan().
{
   struct ast_context *c;
   int res = 0, old_total_exten = dpc->total_exten;
   if (ast_strlen_zero(exten))
      exten = NULL;
   if (ast_strlen_zero(context))
      context = NULL;
   ast_debug(3, "manager_show_dialplan: Context: -%s- Extension: -%s-\n", context, exten);
   /* try to lock contexts */
   if (ast_rdlock_contexts()) {
      astman_send_error(s, m, "Failed to lock contexts");
      ast_log(LOG_WARNING, "Failed to lock contexts list for manager: listdialplan\n");
      return -1;
   }
   c = NULL;      /* walk all contexts ... */
   while ( (c = ast_walk_contexts(c)) ) {
      struct ast_exten *e;
      struct ast_include *i;
      struct ast_ignorepat *ip;
      if (context && strcmp(ast_get_context_name(c), context) != 0)
         continue;   /* not the name we want */
      dpc->context_existence = 1;
      ast_debug(3, "manager_show_dialplan: Found Context: %s \n", ast_get_context_name(c));
      if (ast_rdlock_context(c)) {  /* failed to lock */
         ast_debug(3, "manager_show_dialplan: Failed to lock context\n");
         continue;
      }
      /* XXX note- an empty context is not printed */
      e = NULL;      /* walk extensions in context  */
      while ( (e = ast_walk_context_extensions(c, e)) ) {
         struct ast_exten *p;
         /* looking for extension? is this our extension? */
         if (exten && !ast_extension_match(ast_get_extension_name(e), exten)) {
            /* not the one we are looking for, continue */
            ast_debug(3, "manager_show_dialplan: Skipping extension %s\n", ast_get_extension_name(e));
            continue;
         }
         ast_debug(3, "manager_show_dialplan: Found Extension: %s \n", ast_get_extension_name(e));
         dpc->extension_existence = 1;
         /* may we print context info? */
         dpc->total_context++;
         dpc->total_exten++;
         p = NULL;      /* walk next extension peers */
         while ( (p = ast_walk_extension_priorities(e, p)) ) {
            int prio = ast_get_extension_priority(p);
            dpc->total_prio++;
            if (!dpc->total_items++)
               manager_dpsendack(s, m);
            astman_append(s, "Event: ListDialplan\r\n%s", actionidtext);
            astman_append(s, "Context: %s\r\nExtension: %s\r\n", ast_get_context_name(c), ast_get_extension_name(e) );
            /* XXX maybe make this conditional, if p != e ? */
            if (ast_get_extension_label(p))
               astman_append(s, "ExtensionLabel: %s\r\n", ast_get_extension_label(p));
            if (prio == PRIORITY_HINT) {
               astman_append(s, "Priority: hint\r\nApplication: %s\r\n", ast_get_extension_app(p));
            } else {
               astman_append(s, "Priority: %d\r\nApplication: %s\r\nAppData: %s\r\n", prio, ast_get_extension_app(p), (char *) ast_get_extension_app_data(p));
            }
            astman_append(s, "Registrar: %s\r\n\r\n", ast_get_extension_registrar(e));
         }
      }
      i = NULL;      /* walk included and write info ... */
      while ( (i = ast_walk_context_includes(c, i)) ) {
         if (exten) {
            /* Check all includes for the requested extension */
            manager_show_dialplan_helper(s, m, actionidtext, ast_get_include_name(i), exten, dpc, i);
         } else {
            if (!dpc->total_items++)
               manager_dpsendack(s, m);
            astman_append(s, "Event: ListDialplan\r\n%s", actionidtext);
            astman_append(s, "Context: %s\r\nIncludeContext: %s\r\nRegistrar: %s\r\n", ast_get_context_name(c), ast_get_include_name(i), ast_get_include_registrar(i));
            astman_append(s, "\r\n");
            ast_debug(3, "manager_show_dialplan: Found Included context: %s \n", ast_get_include_name(i));
         }
      }
      ip = NULL;  /* walk ignore patterns and write info ... */
      while ( (ip = ast_walk_context_ignorepats(c, ip)) ) {
         const char *ipname = ast_get_ignorepat_name(ip);
         char ignorepat[AST_MAX_EXTENSION];
         snprintf(ignorepat, sizeof(ignorepat), "_%s.", ipname);
         if (!exten || ast_extension_match(ignorepat, exten)) {
            if (!dpc->total_items++)
               manager_dpsendack(s, m);
            astman_append(s, "Event: ListDialplan\r\n%s", actionidtext);
            astman_append(s, "Context: %s\r\nIgnorePattern: %s\r\nRegistrar: %s\r\n", ast_get_context_name(c), ipname, ast_get_ignorepat_registrar(ip));
            astman_append(s, "\r\n");
         }
      }
      if (!rinclude) {
         struct ast_sw *sw = NULL;
         while ( (sw = ast_walk_context_switches(c, sw)) ) {
            if (!dpc->total_items++)
               manager_dpsendack(s, m);
            astman_append(s, "Event: ListDialplan\r\n%s", actionidtext);
            astman_append(s, "Context: %s\r\nSwitch: %s/%s\r\nRegistrar: %s\r\n", ast_get_context_name(c), ast_get_switch_name(sw), ast_get_switch_data(sw), ast_get_switch_registrar(sw));
            astman_append(s, "\r\n");
            ast_debug(3, "manager_show_dialplan: Found Switch : %s \n", ast_get_switch_name(sw));
         }
      }
      ast_unlock_context(c);
   }
   ast_unlock_contexts();
   if (dpc->total_exten == old_total_exten) {
      ast_debug(3, "manager_show_dialplan: Found nothing new\n");
      /* Nothing new under the sun */
      return -1;
   } else {
      return res;
   }
}
static int matchcid (const char * cidpattern, const char * callerid) [static]
Definition at line 2457 of file pbx.c.
References ast_extension_match(), and ast_strlen_zero().
Referenced by pbx_find_extension().
{
   /* If the Caller*ID pattern is empty, then we're matching NO Caller*ID, so
      failing to get a number should count as a match, otherwise not */
   if (ast_strlen_zero(callerid)) {
      return ast_strlen_zero(cidpattern) ? 1 : 0;
   }
   return ast_extension_match(cidpattern, callerid);
}
static void new_find_extension (const char * str, struct scoreboard * score, struct match_char * tree, int length, int spec, const char * callerid, const char * label, enum ext_match_t action) [static]
Definition at line 1629 of file pbx.c.
References match_char::alt_char, ast_debug, ast_log(), scoreboard::canmatch, match_char::deleted, E_CANMATCH, E_MATCHMORE, ast_exten::exten, scoreboard::exten, match_char::exten, ast_exten::label, LOG_NOTICE, NEW_MATCHER_CHK_MATCH, NEW_MATCHER_RECURSE, match_char::next_char, match_char::specificity, update_scoreboard(), and match_char::x.
Referenced by pbx_find_extension().
{
   struct match_char *p; /* note minimal stack storage requirements */
   struct ast_exten pattern = { .label = label };
#ifdef DEBUG_THIS
   if (tree)
      ast_log(LOG_NOTICE,"new_find_extension called with %s on (sub)tree %s action=%s\n", str, tree->x, action2str(action));
   else
      ast_log(LOG_NOTICE,"new_find_extension called with %s on (sub)tree NULL action=%s\n", str, action2str(action));
#endif
   for (p = tree; p; p = p->alt_char) {
      if (p->x[0] == 'N') {
         if (p->x[1] == 0 && *str >= '2' && *str <= '9' ) {
#define NEW_MATCHER_CHK_MATCH        \
            if (p->exten && !(*(str + 1))) { /* if a shorter pattern matches along the way, might as well report it */           \
               if (action == E_MATCH || action == E_SPAWN || action == E_FINDLABEL) { /* if in CANMATCH/MATCHMORE, don't let matches get in the way */   \
                  update_scoreboard(score, length + 1, spec + p->specificity, p->exten, 0, callerid, p->deleted, p);           \
                  if (!p->deleted) {                                                                                           \
                     if (action == E_FINDLABEL) {                                                                             \
                        if (ast_hashtab_lookup(score->exten->peer_label_table, &pattern)) {                                  \
                           ast_debug(4, "Found label in preferred extension\n");                                            \
                           return;                                                                                          \
                        }                                                                                                    \
                     } else {                                                                                                 \
                        ast_debug(4,"returning an exact match-- first found-- %s\n", p->exten->exten);                       \
                        return; /* the first match, by definition, will be the best, because of the sorted tree */           \
                     }                                                                                                        \
                  }                                                                                                            \
               }                                                                                                                \
            }
#define NEW_MATCHER_RECURSE              \
            if (p->next_char && ( *(str + 1) || (p->next_char->x[0] == '/' && p->next_char->x[1] == 0)               \
                                                 || p->next_char->x[0] == '!')) {                                        \
               if (*(str + 1) || p->next_char->x[0] == '!') {                                                       \
                  new_find_extension(str + 1, score, p->next_char, length + 1, spec+p->specificity, callerid, label, action); \
                  if (score->exten)  {                                                                             \
                       ast_debug(4, "returning an exact match-- %s\n", score->exten->exten);                        \
                     return; /* the first match is all we need */                                                 \
                  }                                                                                    \
               } else {                                                                                             \
                  new_find_extension("/", score, p->next_char, length + 1, spec+p->specificity, callerid, label, action);   \
                  if (score->exten || ((action == E_CANMATCH || action == E_MATCHMORE) && score->canmatch)) {      \
                       ast_debug(4,"returning a (can/more) match--- %s\n", score->exten ? score->exten->exten :     \
                                       "NULL");                                                                          \
                     return; /* the first match is all we need */                                                 \
                  }                                                                                    \
               }                                                                                                    \
            } else if (p->next_char && !*(str + 1)) {                                                                \
               score->canmatch = 1;                                                                                 \
               score->canmatch_exten = get_canmatch_exten(p);                                                       \
               if (action == E_CANMATCH || action == E_MATCHMORE) {                                                 \
                    ast_debug(4, "returning a canmatch/matchmore--- str=%s\n", str);                                 \
                  return;                                                                                          \
               }                                                                                        \
            }
            NEW_MATCHER_CHK_MATCH;
            NEW_MATCHER_RECURSE;
         }
      } else if (p->x[0] == 'Z') {
         if (p->x[1] == 0 && *str >= '1' && *str <= '9' ) {
            NEW_MATCHER_CHK_MATCH;
            NEW_MATCHER_RECURSE;
         }
      } else if (p->x[0] == 'X') {
         if (p->x[1] == 0 && *str >= '0' && *str <= '9' ) {
            NEW_MATCHER_CHK_MATCH;
            NEW_MATCHER_RECURSE;
         }
      } else if (p->x[0] == '.' && p->x[1] == 0) {
         /* how many chars will the . match against? */
         int i = 0;
         const char *str2 = str;
         while (*str2 && *str2 != '/') {
            str2++;
            i++;
         }
         if (p->exten && *str2 != '/') {
            update_scoreboard(score, length+i, spec+(i*p->specificity), p->exten, '.', callerid, p->deleted, p);
            if (score->exten) {
               ast_debug(4,"return because scoreboard has a match with '/'--- %s\n", score->exten->exten);
               return; /* the first match is all we need */
            }
         }
         if (p->next_char && p->next_char->x[0] == '/' && p->next_char->x[1] == 0) {
            new_find_extension("/", score, p->next_char, length+i, spec+(p->specificity*i), callerid, label, action);
            if (score->exten || ((action == E_CANMATCH || action == E_MATCHMORE) && score->canmatch)) {
               ast_debug(4, "return because scoreboard has exact match OR CANMATCH/MATCHMORE & canmatch set--- %s\n", score->exten ? score->exten->exten : "NULL");
               return; /* the first match is all we need */
            }
         }
      } else if (p->x[0] == '!' && p->x[1] == 0) {
         /* how many chars will the . match against? */
         int i = 1;
         const char *str2 = str;
         while (*str2 && *str2 != '/') {
            str2++;
            i++;
         }
         if (p->exten && *str2 != '/') {
            update_scoreboard(score, length + 1, spec+(p->specificity * i), p->exten, '!', callerid, p->deleted, p);
            if (score->exten) {
               ast_debug(4, "return because scoreboard has a '!' match--- %s\n", score->exten->exten);
               return; /* the first match is all we need */
            }
         }
         if (p->next_char && p->next_char->x[0] == '/' && p->next_char->x[1] == 0) {
            new_find_extension("/", score, p->next_char, length + i, spec + (p->specificity * i), callerid, label, action);
            if (score->exten || ((action == E_CANMATCH || action == E_MATCHMORE) && score->canmatch)) {
               ast_debug(4,"return because scoreboard has exact match OR CANMATCH/MATCHMORE & canmatch set with '/' and '!'--- %s\n", score->exten ? score->exten->exten : "NULL");
               return; /* the first match is all we need */
            }
         }
      } else if (p->x[0] == '/' && p->x[1] == 0) {
         /* the pattern in the tree includes the cid match! */
         if (p->next_char && callerid && *callerid) {
            new_find_extension(callerid, score, p->next_char, length+1, spec, callerid, label, action);
            if (score->exten || ((action == E_CANMATCH || action == E_MATCHMORE) && score->canmatch)) {
               ast_debug(4, "return because scoreboard has exact match OR CANMATCH/MATCHMORE & canmatch set with '/'--- %s\n", score->exten ? score->exten->exten : "NULL");
               return; /* the first match is all we need */
            }
         }
      } else if (strchr(p->x, *str)) {
         ast_debug(4, "Nothing strange about this match\n");
         NEW_MATCHER_CHK_MATCH;
         NEW_MATCHER_RECURSE;
      }
   }
   ast_debug(4, "return at end of func\n");
}
static int parse_variable_name (char * var, int * offset, int * length, int * isfunc) [static]
extract offset:length from variable name.
Returns:
1 if there is a offset:length part, which is trimmed off (values go into variables)
Definition at line 2792 of file pbx.c.
Referenced by pbx_retrieve_variable(), and pbx_substitute_variables_helper_full().
{
   int parens = 0;
   *offset = 0;
   *length = INT_MAX;
   *isfunc = 0;
   for (; *var; var++) {
      if (*var == '(') {
         (*isfunc)++;
         parens++;
      } else if (*var == ')') {
         parens--;
      } else if (*var == ':' && parens == 0) {
         *var++ = '\0';
         sscanf(var, "%30d:%30d", offset, length);
         return 1; /* offset:length valid */
      }
   }
   return 0;
}
void pbx_builtin_clear_globals (void)
Definition at line 9182 of file pbx.c.
References AST_LIST_REMOVE_HEAD, ast_rwlock_unlock(), ast_rwlock_wrlock(), ast_var_delete(), globals, and globalslock.
Referenced by handle_cli_dialplan_reload(), and reload().
{
   struct ast_var_t *vardata;
   ast_rwlock_wrlock(&globalslock);
   while ((vardata = AST_LIST_REMOVE_HEAD(&globals, entries)))
      ast_var_delete(vardata);
   ast_rwlock_unlock(&globalslock);
}
const char* pbx_builtin_getvar_helper (struct ast_channel * chan, const char * name)
Return a pointer to the value of the corresponding channel variable.
Note:
Will lock the channel.
This function will return a pointer to the buffer inside the channel variable. This value should only be accessed with the channel locked. If the value needs to be kept around, it should be done by using the following thread-safe code:
      const char *var;
      ast_channel_lock(chan);
      if ((var = pbx_builtin_getvar_helper(chan, "MYVAR"))) {
         var = ast_strdupa(var);
      }
      ast_channel_unlock(chan);
Definition at line 8951 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, AST_LIST_TRAVERSE, ast_rwlock_rdlock(), ast_rwlock_unlock(), ast_var_name(), ast_var_value(), globals, globalslock, and ast_channel::varshead.
Referenced by __ast_pbx_run(), _macro_exec(), _while_exec(), agent_hangup(), agent_read(), agentmonitoroutgoing_exec(), array(), ast_bridge_call(), ast_call_forward(), ast_eivr_getvariable(), ast_monitor_stop(), bridge_play_sounds(), builtin_atxfer(), builtin_automixmonitor(), builtin_automonitor(), check_goto_on_transfer(), common_exec(), conf_exec(), conf_run(), confbridge_exec(), dahdi_call(), dahdi_hangup(), dial_exec_full(), do_forward(), do_timelimit(), dundi_exec(), dundi_helper(), feature_interpret(), find_by_mark(), find_conf_realtime(), findparkinglotname(), get_also_info(), get_index(), get_refer_info(), global_read(), hash_read(), iax2_call(), iax2_exec(), import_ch(), leave_voicemail(), listfilter(), local_attended_transfer(), local_hangup(), local_read(), login_exec(), macro_fixup(), minivm_delete_exec(), minivm_notify_exec(), misdn_answer(), misdn_hangup(), morsecode_exec(), notify_new_message(), oh323_call(), oh323_hangup(), park_call_full(), park_space_reserve(), pbx_builtin_background(), queue_exec(), real_ctx(), retrydial_exec(), ring_entry(), run_agi(), set_config_flags(), set_local_info(), sip_addheader(), sla_trunk_exec(), speech_background(), try_calling(), try_suggested_sip_codec(), update_bridge_vars(), and wait_for_answer().
{
   struct ast_var_t *variables;
   const char *ret = NULL;
   int i;
   struct varshead *places[2] = { NULL, &globals };
   if (!name)
      return NULL;
   if (chan) {
      ast_channel_lock(chan);
      places[0] = &chan->varshead;
   }
   for (i = 0; i < 2; i++) {
      if (!places[i])
         continue;
      if (places[i] == &globals)
         ast_rwlock_rdlock(&globalslock);
      AST_LIST_TRAVERSE(places[i], variables, entries) {
         if (!strcmp(name, ast_var_name(variables))) {
            ret = ast_var_value(variables);
            break;
         }
      }
      if (places[i] == &globals)
         ast_rwlock_unlock(&globalslock);
      if (ret)
         break;
   }
   if (chan)
      ast_channel_unlock(chan);
   return ret;
}
static int pbx_builtin_gotoif (struct ast_channel * chan, void * data) [static]
Definition at line 9204 of file pbx.c.
References ast_debug, ast_log(), ast_strdupa, ast_strlen_zero(), LOG_WARNING, pbx_builtin_goto(), pbx_checkcondition(), and strsep().
{
   char *condition, *branch1, *branch2, *branch;
   char *stringp;
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Ignoring, since there is no variable to check\n");
      return 0;
   }
   stringp = ast_strdupa(data);
   condition = strsep(&stringp,"?");
   branch1 = strsep(&stringp,":");
   branch2 = strsep(&stringp,"");
   branch = pbx_checkcondition(condition) ? branch1 : branch2;
   if (ast_strlen_zero(branch)) {
      ast_debug(1, "Not taking any branch\n");
      return 0;
   }
   return pbx_builtin_goto(chan, branch);
}
int pbx_builtin_importvar (struct ast_channel * chan, void * data) [static]
Todo:
XXX should do !ast_strlen_zero(..) of the args ?
Definition at line 9140 of file pbx.c.
References ast_channel_unlock, ast_get_channel_by_name_locked(), ast_log(), ast_strdupa, ast_strlen_zero(), LOG_WARNING, pbx_builtin_setvar_helper(), pbx_substitute_variables_helper(), s, strsep(), and VAR_BUF_SIZE.
{
   char *name;
   char *value;
   char *channel;
   char tmp[VAR_BUF_SIZE];
   static int deprecation_warning = 0;
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Ignoring, since there is no variable to set\n");
      return 0;
   }
   tmp[0] = 0;
   if (!deprecation_warning) {
      ast_log(LOG_WARNING, "ImportVar is deprecated.  Please use Set(varname=${IMPORT(channel,variable)}) instead.\n");
      deprecation_warning = 1;
   }
   value = ast_strdupa(data);
   name = strsep(&value,"=");
   channel = strsep(&value,",");
   if (channel && value && name) { /*! \todo XXX should do !ast_strlen_zero(..) of the args ? */
      struct ast_channel *chan2 = ast_get_channel_by_name_locked(channel);
      if (chan2) {
         char *s = alloca(strlen(value) + 4);
         if (s) {
            sprintf(s, "${%s}", value);
            pbx_substitute_variables_helper(chan2, s, tmp, sizeof(tmp) - 1);
         }
         ast_channel_unlock(chan2);
      }
      pbx_builtin_setvar_helper(chan, name, tmp);
   }
   return(0);
}
static int pbx_builtin_incomplete (struct ast_channel * chan, void * data) [static]
Definition at line 8536 of file pbx.c.
References __ast_answer(), ast_channel::_state, ast_check_hangup(), AST_PBX_INCOMPLETE, AST_STATE_UP, and ast_strlen_zero().
{
   char *options = data;
   int answer = 1;
   /* Some channels can receive DTMF in unanswered state; some cannot */
   if (!ast_strlen_zero(options) && strchr(options, 'n')) {
      answer = 0;
   }
   /* If the channel is hungup, stop waiting */
   if (ast_check_hangup(chan)) {
      return -1;
   } else if (chan->_state != AST_STATE_UP && answer) {
      __ast_answer(chan, 0, 1);
   }
   return AST_PBX_INCOMPLETE;
}
static int pbx_builtin_noop (struct ast_channel * chan, void * data) [static]
Definition at line 9177 of file pbx.c.
{
   return 0;
}
void pbx_builtin_pushvar_helper (struct ast_channel * chan, const char * name, const char * value)
Add a variable to the channel variable stack, without removing any previously set value.
Note:
Will lock the channel.
Definition at line 8989 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, ast_func_write(), AST_LIST_INSERT_HEAD, ast_log(), ast_rwlock_unlock(), ast_rwlock_wrlock(), ast_strdupa, ast_var_assign(), ast_verb, globals, globalslock, LOG_WARNING, and ast_channel::varshead.
Referenced by acf_odbc_read(), acf_odbc_write(), cli_odbc_read(), cli_odbc_write(), and frame_set_var().
{
   struct ast_var_t *newvariable;
   struct varshead *headp;
   if (name[strlen(name)-1] == ')') {
      char *function = ast_strdupa(name);
      ast_log(LOG_WARNING, "Cannot push a value onto a function\n");
      ast_func_write(chan, function, value);
      return;
   }
   if (chan) {
      ast_channel_lock(chan);
      headp = &chan->varshead;
   } else {
      ast_rwlock_wrlock(&globalslock);
      headp = &globals;
   }
   if (value) {
      if (headp == &globals)
         ast_verb(2, "Setting global variable '%s' to '%s'\n", name, value);
      newvariable = ast_var_assign(name, value);
      AST_LIST_INSERT_HEAD(headp, newvariable, entries);
   }
   if (chan)
      ast_channel_unlock(chan);
   else
      ast_rwlock_unlock(&globalslock);
}
int pbx_builtin_raise_exception (struct ast_channel * chan, void * vreason)
Definition at line 2995 of file pbx.c.
References ast_calloc, ast_channel_datastore_add(), ast_channel_datastore_find(), ast_datastore_alloc, ast_datastore_free(), ast_free, ast_string_field_init, ast_string_field_set, ast_channel::context, ast_datastore::data, exception_store_info, ast_channel::exten, ast_channel::priority, pbx_exception::priority, and set_ext_pri().
Referenced by __ast_pbx_run().
{
   const char *reason = vreason;
   struct ast_datastore *ds = ast_channel_datastore_find(chan, &exception_store_info, NULL);
   struct pbx_exception *exception = NULL;
   if (!ds) {
      ds = ast_datastore_alloc(&exception_store_info, NULL);
      if (!ds)
         return -1;
      exception = ast_calloc(1, sizeof(struct pbx_exception));
      if (!exception) {
         ast_datastore_free(ds);
         return -1;
      }
      if (ast_string_field_init(exception, 128)) {
         ast_free(exception);
         ast_datastore_free(ds);
         return -1;
      }
      ds->data = exception;
      ast_channel_datastore_add(chan, ds);
   } else
      exception = ds->data;
   ast_string_field_set(exception, reason, reason);
   ast_string_field_set(exception, context, chan->context);
   ast_string_field_set(exception, exten, chan->exten);
   exception->priority = chan->priority;
   set_ext_pri(chan, "e", 0);
   return 0;
}
static int pbx_builtin_saycharacters (struct ast_channel * chan, void * data) [static]
Definition at line 9265 of file pbx.c.
References ast_say_character_str().
{
   int res = 0;
   if (data)
      res = ast_say_character_str(chan, data, "", chan->language);
   return res;
}
static int pbx_builtin_saydigits (struct ast_channel * chan, void * data) [static]
Definition at line 9256 of file pbx.c.
References ast_say_digit_str().
{
   int res = 0;
   if (data)
      res = ast_say_digit_str(chan, data, "", chan->language);
   return res;
}
static int pbx_builtin_saynumber (struct ast_channel * chan, void * data) [static]
Definition at line 9228 of file pbx.c.
References ast_copy_string(), ast_log(), ast_say_number(), ast_strlen_zero(), LOG_WARNING, and strsep().
{
   char tmp[256];
   char *number = tmp;
   char *options;
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "SayNumber requires an argument (number)\n");
      return -1;
   }
   ast_copy_string(tmp, data, sizeof(tmp));
   strsep(&number, ",");
   options = strsep(&number, ",");
   if (options) {
      if ( strcasecmp(options, "f") && strcasecmp(options, "m") &&
         strcasecmp(options, "c") && strcasecmp(options, "n") ) {
         ast_log(LOG_WARNING, "SayNumber gender option is either 'f', 'm', 'c' or 'n'\n");
         return -1;
      }
   }
   if (ast_say_number(chan, atoi(tmp), "", chan->language, options)) {
      ast_log(LOG_WARNING, "We were unable to say the number %s, is it too large?\n", tmp);
   }
   return 0;
}
static int pbx_builtin_sayphonetic (struct ast_channel * chan, void * data) [static]
Definition at line 9274 of file pbx.c.
References ast_say_phonetic_str().
{
   int res = 0;
   if (data)
      res = ast_say_phonetic_str(chan, data, "", chan->language);
   return res;
}
int pbx_builtin_serialize_variables (struct ast_channel * chan, struct ast_str ** buf)
Create a human-readable string, specifying all variables and their corresponding values.
Parameters:
chan Channel from which to read variables
buf Dynamic string in which to place the result (should be allocated with
See also:
ast_str_create).
Note:
Will lock the channel.
Definition at line 8920 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, AST_LIST_TRAVERSE, ast_log(), ast_str_append(), ast_str_reset(), ast_var_name(), ast_var_value(), LOG_ERROR, total, var, and ast_channel::varshead.
Referenced by ast_var_channels_table(), dumpchan_exec(), handle_show_chanvar(), handle_showchan(), and vars2manager().
{
   struct ast_var_t *variables;
   const char *var, *val;
   int total = 0;
   if (!chan)
      return 0;
   ast_str_reset(*buf);
   ast_channel_lock(chan);
   AST_LIST_TRAVERSE(&chan->varshead, variables, entries) {
      if ((var = ast_var_name(variables)) && (val = ast_var_value(variables))
         /* && !ast_strlen_zero(var) && !ast_strlen_zero(val) */
         ) {
         if (ast_str_append(buf, 0, "%s=%s\n", var, val) < 0) {
            ast_log(LOG_ERROR, "Data Buffer Size Exceeded!\n");
            break;
         } else
            total++;
      } else
         break;
   }
   ast_channel_unlock(chan);
   return total;
}
int pbx_builtin_setvar (struct ast_channel * chan, void * data)
Parse and set a single channel variable, where the name and value are separated with an '=' character.
Note:
Will lock the channel.
Definition at line 9081 of file pbx.c.
References ast_compat_app_set, ast_log(), ast_strdupa, ast_strlen_zero(), LOG_WARNING, pbx_builtin_setvar_helper(), pbx_builtin_setvar_multiple(), and strsep().
Referenced by ast_compile_ael2(), and rpt_exec().
{
   char *name, *value, *mydata;
   if (ast_compat_app_set) {
      return pbx_builtin_setvar_multiple(chan, data);
   }
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Set requires one variable name/value pair.\n");
      return 0;
   }
   mydata = ast_strdupa(data);
   name = strsep(&mydata, "=");
   value = mydata;
   if (strchr(name, ' '))
      ast_log(LOG_WARNING, "Please avoid unnecessary spaces on variables as it may lead to unexpected results ('%s' set to '%s').\n", name, mydata);
   pbx_builtin_setvar_helper(chan, name, value);
   return(0);
}
void pbx_builtin_setvar_helper (struct ast_channel * chan, const char * name, const char * value)
Add a variable to the channel variable stack, removing the most recently set value for the same name.
Note:
Will lock the channel. May also be used to set a channel dialplan function to a particular value.
See also:
ast_func_write
Definition at line 9023 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, ast_func_write(), AST_LIST_INSERT_HEAD, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, ast_rwlock_unlock(), ast_rwlock_wrlock(), ast_strdupa, ast_var_assign(), ast_var_delete(), ast_var_name(), ast_verb, EVENT_FLAG_DIALPLAN, globals, globalslock, manager_event, and ast_channel::varshead.
Referenced by __ast_pbx_run(), __oh323_new(), _macro_exec(), _while_exec(), acf_curl_exec(), acf_fetch(), acf_odbc_read(), acf_odbc_write(), acf_transaction_write(), action_atxfer(), action_setvar(), admin_exec(), agi_exec_full(), aji_status_exec(), aqm_exec(), array(), ast_bridge_call(), ast_eivr_setvariable(), ast_iax2_new(), ast_monitor_start(), ast_pbx_outgoing_exten(), ast_rtp_set_vars(), ast_set_variables(), asyncgoto_exec(), background_detect_exec(), bridge_exec(), bridge_play_sounds(), builtin_atxfer(), builtin_automixmonitor(), builtin_automonitor(), builtin_blindtransfer(), cb_events(), chanavail_exec(), channel_spy(), commit_exec(), conf_run(), controlplayback_exec(), count_exec(), dahdi_handle_dtmfup(), dahdi_new(), dial_exec_full(), disa_exec(), do_waiting(), end_bridge_callback(), export_aoc_vars(), export_ch(), feature_request_and_dial(), frame_set_var(), function_db_delete(), function_db_exists(), function_db_read(), function_realtime_store(), get_rdnis(), get_refer_info(), global_write(), gosub_release_frame(), handle_request_bye(), handle_request_refer(), handle_set_chanvar(), handle_set_global(), handle_setvariable(), hash_read(), hash_write(), isAnsweringMachine(), leave_voicemail(), local_hangup(), lua_set_variable(), lua_set_variable_value(), macro_fixup(), manage_parkinglot(), minivm_accmess_exec(), minivm_delete_exec(), minivm_greet_exec(), minivm_notify_exec(), minivm_record_exec(), misdn_call(), mixmonitor_exec(), originate_exec(), ospauth_exec(), ospfinished_exec(), osplookup_exec(), ospnext_exec(), park_exec_full(), parse_moved_contact(), pbx_builtin_background(), pbx_builtin_importvar(), pbx_builtin_setvar(), pbx_builtin_setvar_multiple(), pbx_load_config(), phase_e_handler(), play_message_datetime(), playback_exec(), pqm_exec(), prep_email_sub_vars(), privacy_exec(), process_ast_dsp(), read_exec(), readexten_exec(), readfile_exec(), realtimefield_read(), record_exec(), return_exec(), rollback_exec(), rotate_file(), rpt_exec(), rqm_exec(), sendimage_exec(), sendtext_exec(), sendurl_exec(), set(), set_agentbycallerid(), set_queue_result(), sip_addheader(), sip_hangup(), sip_new(), sip_read(), skinny_new(), sla_calc_trunk_timeouts(), sla_station_exec(), sla_trunk_exec(), socket_process(), speech_create(), ss_thread(), start_monitor_exec(), system_exec_helper(), transfer_exec(), transmit(), tryexec_exec(), update_bridge_vars(), update_qe_rule(), upqm_exec(), vm_box_exists(), vm_exec(), vmauthenticate(), waituntil_exec(), and zapateller_exec().
{
   struct ast_var_t *newvariable;
   struct varshead *headp;
   const char *nametail = name;
   if (name[strlen(name) - 1] == ')') {
      char *function = ast_strdupa(name);
      ast_func_write(chan, function, value);
      return;
   }
   if (chan) {
      ast_channel_lock(chan);
      headp = &chan->varshead;
   } else {
      ast_rwlock_wrlock(&globalslock);
      headp = &globals;
   }
   /* For comparison purposes, we have to strip leading underscores */
   if (*nametail == '_') {
      nametail++;
      if (*nametail == '_')
         nametail++;
   }
   AST_LIST_TRAVERSE_SAFE_BEGIN(headp, newvariable, entries) {
      if (strcasecmp(ast_var_name(newvariable), nametail) == 0) {
         /* there is already such a variable, delete it */
         AST_LIST_REMOVE_CURRENT(entries);
         ast_var_delete(newvariable);
         break;
      }
   }
   AST_LIST_TRAVERSE_SAFE_END;
   if (value) {
      if (headp == &globals)
         ast_verb(2, "Setting global variable '%s' to '%s'\n", name, value);
      newvariable = ast_var_assign(name, value);
      AST_LIST_INSERT_HEAD(headp, newvariable, entries);
      manager_event(EVENT_FLAG_DIALPLAN, "VarSet",
         "Channel: %s\r\n"
         "Variable: %s\r\n"
         "Value: %s\r\n"
         "Uniqueid: %s\r\n",
         chan ? chan->name : "none", name, value,
         chan ? chan->uniqueid : "none");
   }
   if (chan)
      ast_channel_unlock(chan);
   else
      ast_rwlock_unlock(&globalslock);
}
int pbx_builtin_setvar_multiple (struct ast_channel * chan, void * vdata)
Parse and set multiple channel variables, where the pairs are separated by the ',' character, and name and value are separated with an '=' character.
Note:
Will lock the channel.
Definition at line 9104 of file pbx.c.
References AST_APP_ARG, AST_DECLARE_APP_ARGS, ast_log(), AST_NONSTANDARD_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strdupa, ast_strlen_zero(), ast_channel::context, ast_channel::exten, LOG_WARNING, pbx_builtin_setvar_helper(), and ast_channel::priority.
Referenced by pbx_builtin_setvar(), queue_function_var(), set_queue_variables(), and try_calling().
{
   char *data;
   int x;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(pair)[24];
   );
   AST_DECLARE_APP_ARGS(pair,
      AST_APP_ARG(name);
      AST_APP_ARG(value);
   );
   if (ast_strlen_zero(vdata)) {
      ast_log(LOG_WARNING, "MSet requires at least one variable name/value pair.\n");
      return 0;
   }
   data = ast_strdupa(vdata);
   AST_STANDARD_APP_ARGS(args, data);
   for (x = 0; x < args.argc; x++) {
      AST_NONSTANDARD_APP_ARGS(pair, args.pair[x], '=');
      if (pair.argc == 2) {
         pbx_builtin_setvar_helper(chan, pair.name, pair.value);
         if (strchr(pair.name, ' '))
            ast_log(LOG_WARNING, "Please avoid unnecessary spaces on variables as it may lead to unexpected results ('%s' set to '%s').\n", pair.name, pair.value);
      } else if (!chan) {
         ast_log(LOG_WARNING, "MSet: ignoring entry '%s' with no '='\n", pair.name);
      } else {
         ast_log(LOG_WARNING, "MSet: ignoring entry '%s' with no '=' (in %s@%s:%d\n", pair.name, chan->exten, chan->context, chan->priority);
      }
   }
   return 0;
}
int pbx_checkcondition (const char * condition)
Evaluate a condition.
Return values:
0 if the condition is NULL or of zero length
int If the string is an integer, the integer representation of the integer is returned
1 Any other non-empty string
Definition at line 9192 of file pbx.c.
References ast_strlen_zero().
Referenced by _macro_exec(), _while_exec(), acf_if(), execif_exec(), gosubif_exec(), macroif_exec(), and pbx_builtin_gotoif().
{
   int res;
   if (ast_strlen_zero(condition)) {                /* NULL or empty strings are false */
      return 0;
   } else if (sscanf(condition, "%30d", &res) == 1) { /* Numbers are evaluated for truth */
      return res;
   } else {                                         /* Strings are true */
      return 1;
   }
}
static void pbx_destroy (struct ast_pbx * p) [static]
Definition at line 1399 of file pbx.c.
References ast_free.
Referenced by __ast_pbx_run().
{
   ast_free(p);
}
int pbx_exec (struct ast_channel * c, struct ast_app * app, void * data)
Execute an application.
Parameters:
c channel to execute on
app which app to execute
data the data passed into the app
This application executes an application on a given channel. It saves the stack and executes the given application passing in the given data.
Return values:
0 success
-1 failure
Parameters:
c Channel
app Application
data Data for execution
Definition at line 1322 of file pbx.c.
References __ast_module_user_add(), __ast_module_user_remove(), ast_channel::appl, ast_cdr_setapp(), ast_check_hangup(), ast_log(), ast_opt_dont_warn, ast_strlen_zero(), ast_channel::cdr, ast_channel::data, ast_app::execute, LOG_WARNING, ast_app::module, ast_app::name, and S_OR.
Referenced by answer_exec_run(), ast_bridge_call(), ast_pbx_run_app(), async_wait(), builtin_automixmonitor(), builtin_automonitor(), conf_run(), dial_exec_full(), do_magic_pickup(), dundi_exec(), exec_exec(), execif_exec(), feature_exec_app(), forward_message(), handle_exec(), handle_gosub(), iax2_exec(), lua_pbx_exec(), page_exec(), pbx_builtin_execiftime(), pbx_extension_helper(), realtime_exec(), try_calling(), and tryexec_exec().
{
   int res;
   struct ast_module_user *u = NULL;
   const char *saved_c_appl;
   const char *saved_c_data;
   if (c->cdr && !ast_check_hangup(c))
      ast_cdr_setapp(c->cdr, app->name, data);
   /* save channel values */
   saved_c_appl= c->appl;
   saved_c_data= c->data;
   c->appl = app->name;
   c->data = data;
   if (app->module)
      u = __ast_module_user_add(app->module, c);
   if (strcasecmp(app->name, "system") && !ast_strlen_zero(data) &&
         strchr(data, '|') && !strchr(data, ',') && !ast_opt_dont_warn) {
      ast_log(LOG_WARNING, "The application delimiter is now the comma, not "
         "the pipe.  Did you forget to convert your dialplan?  (%s(%s))\n",
         app->name, (char *) data);
   }
   res = app->execute(c, S_OR((char *) data, ""));
   if (app->module && u)
      __ast_module_user_remove(app->module, u);
   /* restore channel values */
   c->appl = saved_c_appl;
   c->data = saved_c_data;
   return res;
}
static int pbx_extension_helper (struct ast_channel * c, struct ast_context * con, const char * context, const char * exten, int priority, const char * label, const char * callerid, enum ext_match_t action, int * found, int combined_find_spawn) [static]
The return value depends on the action:.
E_MATCH, E_CANMATCH, E_MATCHMORE require a real match, and return 0 on failure, -1 on match; E_FINDLABEL maps the label to a priority, and returns the priority on success, ... XXX E_SPAWN, spawn an application,
Return values:
0 on success.
-1 on failure.
Note:
The channel is auto-serviced in this function, because doing an extension match may block for a long time. For example, if the lookup has to use a network dialplan switch, such as DUNDi or IAX2, it may take a while. However, the channel auto-service code will queue up any important signalling frames to be processed after this is done.
Definition at line 3647 of file pbx.c.
References ast_exten::app, app, ast_copy_string(), ast_debug, ast_log(), ast_rdlock_contexts(), ast_unlock_contexts(), ast_verb, ast_exten::cached_app, COLOR_BRCYAN, COLOR_BRMAGENTA, ast_channel::context, pbx_find_info::data, E_CANMATCH, E_FINDLABEL, E_MATCH, E_MATCHMORE, EVENT_FLAG_DIALPLAN, ast_switch::exec, EXT_DATA_SIZE, ast_channel::exten, pbx_find_info::foundcontext, LOG_NOTICE, LOG_WARNING, manager_event, ast_switch::name, ast_app::name, pbx_exec(), pbx_find_extension(), pbx_findapp(), pbx_substitute_variables(), ast_channel::priority, ast_exten::priority, S_OR, pbx_find_info::stacklen, pbx_find_info::status, STATUS_NO_CONTEXT, STATUS_NO_EXTENSION, STATUS_NO_LABEL, STATUS_NO_PRIORITY, pbx_find_info::swo, term_color(), and VERBOSITY_ATLEAST.
Referenced by ast_canmatch_extension(), ast_exists_extension(), ast_findlabel_extension(), ast_findlabel_extension2(), ast_matchmore_extension(), and ast_spawn_extension().
{
   struct ast_exten *e;
   struct ast_app *app;
   int res;
   struct pbx_find_info q = { .stacklen = 0 }; /* the rest is reset in pbx_find_extension */
   char passdata[EXT_DATA_SIZE];
   int matching_action = (action == E_MATCH || action == E_CANMATCH || action == E_MATCHMORE);
   ast_rdlock_contexts();
   if (found)
      *found = 0;
   e = pbx_find_extension(c, con, &q, context, exten, priority, label, callerid, action);
   if (e) {
      if (found)
         *found = 1;
      if (matching_action) {
         ast_unlock_contexts();
         return -1;  /* success, we found it */
      } else if (action == E_FINDLABEL) { /* map the label to a priority */
         res = e->priority;
         ast_unlock_contexts();
         return res; /* the priority we were looking for */
      } else { /* spawn */
         if (!e->cached_app)
            e->cached_app = pbx_findapp(e->app);
         app = e->cached_app;
         ast_unlock_contexts();
         if (!app) {
            ast_log(LOG_WARNING, "No application '%s' for extension (%s, %s, %d)\n", e->app, context, exten, priority);
            return -1;
         }
         if (c->context != context)
            ast_copy_string(c->context, context, sizeof(c->context));
         if (c->exten != exten)
            ast_copy_string(c->exten, exten, sizeof(c->exten));
         c->priority = priority;
         pbx_substitute_variables(passdata, sizeof(passdata), c, e);
#ifdef CHANNEL_TRACE
         ast_channel_trace_update(c);
#endif
         ast_debug(1, "Launching '%s'\n", app->name);
         if (VERBOSITY_ATLEAST(3)) {
            char tmp[80], tmp2[80], tmp3[EXT_DATA_SIZE];
            ast_verb(3, "Executing [%s@%s:%d] %s(\"%s\", \"%s\") %s\n",
               exten, context, priority,
               term_color(tmp, app->name, COLOR_BRCYAN, 0, sizeof(tmp)),
               term_color(tmp2, c->name, COLOR_BRMAGENTA, 0, sizeof(tmp2)),
               term_color(tmp3, passdata, COLOR_BRMAGENTA, 0, sizeof(tmp3)),
               "in new stack");
         }
         manager_event(EVENT_FLAG_DIALPLAN, "Newexten",
               "Channel: %s\r\n"
               "Context: %s\r\n"
               "Extension: %s\r\n"
               "Priority: %d\r\n"
               "Application: %s\r\n"
               "AppData: %s\r\n"
               "Uniqueid: %s\r\n",
               c->name, c->context, c->exten, c->priority, app->name, passdata, c->uniqueid);
         return pbx_exec(c, app, passdata);  /* 0 on success, -1 on failure */
      }
   } else if (q.swo) {  /* not found here, but in another switch */
      if (found)
         *found = 1;
      ast_unlock_contexts();
      if (matching_action) {
         return -1;
      } else {
         if (!q.swo->exec) {
            ast_log(LOG_WARNING, "No execution engine for switch %s\n", q.swo->name);
            res = -1;
         }
         return q.swo->exec(c, q.foundcontext ? q.foundcontext : context, exten, priority, callerid, q.data);
      }
   } else { /* not found anywhere, see what happened */
      ast_unlock_contexts();
      /* Using S_OR here because Solaris doesn't like NULL being passed to ast_log */
      switch (q.status) {
      case STATUS_NO_CONTEXT:
         if (!matching_action && !combined_find_spawn)
            ast_log(LOG_NOTICE, "Cannot find extension context '%s'\n", S_OR(context, ""));
         break;
      case STATUS_NO_EXTENSION:
         if (!matching_action && !combined_find_spawn)
            ast_log(LOG_NOTICE, "Cannot find extension '%s' in context '%s'\n", exten, S_OR(context, ""));
         break;
      case STATUS_NO_PRIORITY:
         if (!matching_action && !combined_find_spawn)
            ast_log(LOG_NOTICE, "No such priority %d in extension '%s' in context '%s'\n", priority, exten, S_OR(context, ""));
         break;
      case STATUS_NO_LABEL:
         if (context && !combined_find_spawn)
            ast_log(LOG_NOTICE, "No such label '%s' in extension '%s' in context '%s'\n", label, exten, S_OR(context, ""));
         break;
      default:
         ast_debug(1, "Shouldn't happen!\n");
      }
      return (matching_action) ? 0 : -1;
   }
}
struct ast_exten* pbx_find_extension (struct ast_channel * chan, struct ast_context * bypass, struct pbx_find_info * q, const char * context, const char * exten, int priority, const char * label, const char * callerid, enum ext_match_t action) [read]
Definition at line 2469 of file pbx.c.
References ast_context::alts, ast_autoservice_start(), ast_autoservice_stop(), ast_copy_string(), ast_hashtab_lookup(), AST_LIST_TRAVERSE, ast_log(), AST_PBX_MAX_STACK, ast_str_buffer(), ast_str_size(), ast_str_thread_get(), ast_strdupa, ast_strlen_zero(), ast_walk_context_extensions(), ast_walk_contexts(), ast_walk_extension_priorities(), ast_switch::canmatch, scoreboard::canmatch_exten, contexts_table, create_match_char_tree(), ast_sw::data, pbx_find_info::data, E_CANMATCH, E_FINDLABEL, E_MATCHMORE, ast_sw::eval, ast_switch::exists, ast_exten::exten, scoreboard::exten, extenpatternmatchnew, extension_match_core(), pbx_find_info::foundcontext, include_valid(), ast_context::includes, pbx_find_info::incstack, ast_exten::label, scoreboard::last_char, LOG_DEBUG, log_match_char_tree(), LOG_NOTICE, LOG_WARNING, match(), matchcid(), ast_switch::matchmore, ast_sw::name, ast_context::name, fake_context::name, new_find_extension(), ast_include::next, scoreboard::node, overrideswitch, ast_context::pattern_tree, pbx_find_extension(), pbx_findswitch(), pbx_substitute_variables_helper(), ast_exten::priority, ast_include::rname, ast_context::root_table, pbx_find_info::stacklen, pbx_find_info::status, STATUS_NO_CONTEXT, STATUS_NO_EXTENSION, STATUS_NO_LABEL, STATUS_NO_PRIORITY, STATUS_SUCCESS, strsep(), switch_data, pbx_find_info::swo, scoreboard::total_length, scoreboard::total_specificity, and trie_find_next_match().
Referenced by ast_hint_extension_nolock(), ast_merge_contexts_and_delete(), check_goto(), check_pval_item(), pbx_extension_helper(), pbx_find_extension(), and register_peer_exten().
{
   int x, res;
   struct ast_context *tmp = NULL;
   struct ast_exten *e = NULL, *eroot = NULL;
   struct ast_include *i = NULL;
   struct ast_sw *sw = NULL;
   struct ast_exten pattern = {NULL, };
   struct scoreboard score = {0, };
   struct ast_str *tmpdata = NULL;
   pattern.label = label;
   pattern.priority = priority;
#ifdef NEED_DEBUG_HERE
   ast_log(LOG_NOTICE, "Looking for cont/ext/prio/label/action = %s/%s/%d/%s/%d\n", context, exten, priority, label, (int) action);
#endif
   /* Initialize status if appropriate */
   if (q->stacklen == 0) {
      q->status = STATUS_NO_CONTEXT;
      q->swo = NULL;
      q->data = NULL;
      q->foundcontext = NULL;
   } else if (q->stacklen >= AST_PBX_MAX_STACK) {
      ast_log(LOG_WARNING, "Maximum PBX stack exceeded\n");
      return NULL;
   }
   /* Check first to see if we've already been checked */
   for (x = 0; x < q->stacklen; x++) {
      if (!strcasecmp(q->incstack[x], context))
         return NULL;
   }
   if (bypass) { /* bypass means we only look there */
      tmp = bypass;
   } else {      /* look in contexts */
      struct fake_context item;
      ast_copy_string(item.name, context, sizeof(item.name));
      tmp = ast_hashtab_lookup(contexts_table, &item);
#ifdef NOTNOW
      tmp = NULL;
      while ((tmp = ast_walk_contexts(tmp)) ) {
         if (!strcmp(tmp->name, context)) {
            break;
         }
      }
#endif
      if (!tmp) {
         return NULL;
      }
   }
   if (q->status < STATUS_NO_EXTENSION)
      q->status = STATUS_NO_EXTENSION;
   /* Do a search for matching extension */
   eroot = NULL;
   score.total_specificity = 0;
   score.exten = 0;
   score.total_length = 0;
   if (!tmp->pattern_tree && tmp->root_table) {
      create_match_char_tree(tmp);
#ifdef NEED_DEBUG
      ast_log(LOG_DEBUG, "Tree Created in context %s:\n", context);
      log_match_char_tree(tmp->pattern_tree," ");
#endif
   }
#ifdef NEED_DEBUG
   ast_log(LOG_NOTICE, "The Trie we are searching in:\n");
   log_match_char_tree(tmp->pattern_tree, "::  ");
#endif
   do {
      if (!ast_strlen_zero(overrideswitch)) {
         char *osw = ast_strdupa(overrideswitch), *name;
         struct ast_switch *asw;
         ast_switch_f *aswf = NULL;
         char *datap;
         int eval = 0;
         name = strsep(&osw, "/");
         asw = pbx_findswitch(name);
         if (!asw) {
            ast_log(LOG_WARNING, "No such switch '%s'\n", name);
            break;
         }
         if (osw && strchr(osw, '$')) {
            eval = 1;
         }
         if (eval && !(tmpdata = ast_str_thread_get(&switch_data, 512))) {
            ast_log(LOG_WARNING, "Can't evaluate overrideswitch?!");
            break;
         } else if (eval) {
            /* Substitute variables now */
            pbx_substitute_variables_helper(chan, osw, ast_str_buffer(tmpdata), ast_str_size(tmpdata));
            datap = ast_str_buffer(tmpdata);
         } else {
            datap = osw;
         }
         /* equivalent of extension_match_core() at the switch level */
         if (action == E_CANMATCH)
            aswf = asw->canmatch;
         else if (action == E_MATCHMORE)
            aswf = asw->matchmore;
         else /* action == E_MATCH */
            aswf = asw->exists;
         if (!aswf) {
            res = 0;
         } else {
            if (chan) {
               ast_autoservice_start(chan);
            }
            res = aswf(chan, context, exten, priority, callerid, datap);
            if (chan) {
               ast_autoservice_stop(chan);
            }
         }
         if (res) {  /* Got a match */
            q->swo = asw;
            q->data = datap;
            q->foundcontext = context;
            /* XXX keep status = STATUS_NO_CONTEXT ? */
            return NULL;
         }
      }
   } while (0);
   if (extenpatternmatchnew) {
      new_find_extension(exten, &score, tmp->pattern_tree, 0, 0, callerid, label, action);
      eroot = score.exten;
      if (score.last_char == '!' && action == E_MATCHMORE) {
         /* We match an extension ending in '!'.
          * The decision in this case is final and is NULL (no match).
          */
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"Returning MATCHMORE NULL with exclamation point.\n");
#endif
         return NULL;
      }
      if (!eroot && (action == E_CANMATCH || action == E_MATCHMORE) && score.canmatch_exten) {
         q->status = STATUS_SUCCESS;
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE,"Returning CANMATCH exten %s\n", score.canmatch_exten->exten);
#endif
         return score.canmatch_exten;
      }
      if ((action == E_MATCHMORE || action == E_CANMATCH)  && eroot) {
         if (score.node) {
            struct ast_exten *z = trie_find_next_match(score.node);
            if (z) {
#ifdef NEED_DEBUG_HERE
               ast_log(LOG_NOTICE,"Returning CANMATCH/MATCHMORE next_match exten %s\n", z->exten);
#endif
            } else {
               if (score.canmatch_exten) {
#ifdef NEED_DEBUG_HERE
                  ast_log(LOG_NOTICE,"Returning CANMATCH/MATCHMORE canmatchmatch exten %s(%p)\n", score.canmatch_exten->exten, score.canmatch_exten);
#endif
                  return score.canmatch_exten;
               } else {
#ifdef NEED_DEBUG_HERE
                  ast_log(LOG_NOTICE,"Returning CANMATCH/MATCHMORE next_match exten NULL\n");
#endif
               }
            }
            return z;
         }
#ifdef NEED_DEBUG_HERE
         ast_log(LOG_NOTICE, "Returning CANMATCH/MATCHMORE NULL (no next_match)\n");
#endif
         return NULL;  /* according to the code, complete matches are null matches in MATCHMORE mode */
      }
      if (eroot) {
         /* found entry, now look for the right priority */
         if (q->status < STATUS_NO_PRIORITY)
            q->status = STATUS_NO_PRIORITY;
         e = NULL;
         if (action == E_FINDLABEL && label ) {
            if (q->status < STATUS_NO_LABEL)
               q->status = STATUS_NO_LABEL;
            e = ast_hashtab_lookup(eroot->peer_label_table, &pattern);
         } else {
            e = ast_hashtab_lookup(eroot->peer_table, &pattern);
         }
         if (e) { /* found a valid match */
            q->status = STATUS_SUCCESS;
            q->foundcontext = context;
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"Returning complete match of exten %s\n", e->exten);
#endif
            return e;
         }
      }
   } else {   /* the old/current default exten pattern match algorithm */
      /* scan the list trying to match extension and CID */
      eroot = NULL;
      while ( (eroot = ast_walk_context_extensions(tmp, eroot)) ) {
         int match = extension_match_core(eroot->exten, exten, action);
         /* 0 on fail, 1 on match, 2 on earlymatch */
         if (!match || (eroot->matchcid && !matchcid(eroot->cidmatch, callerid)))
            continue;   /* keep trying */
         if (match == 2 && action == E_MATCHMORE) {
            /* We match an extension ending in '!'.
             * The decision in this case is final and is NULL (no match).
             */
            return NULL;
         }
         /* found entry, now look for the right priority */
         if (q->status < STATUS_NO_PRIORITY)
            q->status = STATUS_NO_PRIORITY;
         e = NULL;
         if (action == E_FINDLABEL && label ) {
            if (q->status < STATUS_NO_LABEL)
               q->status = STATUS_NO_LABEL;
            e = ast_hashtab_lookup(eroot->peer_label_table, &pattern);
         } else {
            e = ast_hashtab_lookup(eroot->peer_table, &pattern);
         }
#ifdef NOTNOW
         while ( (e = ast_walk_extension_priorities(eroot, e)) ) {
            /* Match label or priority */
            if (action == E_FINDLABEL) {
               if (q->status < STATUS_NO_LABEL)
                  q->status = STATUS_NO_LABEL;
               if (label && e->label && !strcmp(label, e->label))
                  break;   /* found it */
            } else if (e->priority == priority) {
               break;   /* found it */
            } /* else keep searching */
         }
#endif
         if (e) { /* found a valid match */
            q->status = STATUS_SUCCESS;
            q->foundcontext = context;
            return e;
         }
      }
   }
   /* Check alternative switches */
   AST_LIST_TRAVERSE(&tmp->alts, sw, list) {
      struct ast_switch *asw = pbx_findswitch(sw->name);
      ast_switch_f *aswf = NULL;
      char *datap;
      if (!asw) {
         ast_log(LOG_WARNING, "No such switch '%s'\n", sw->name);
         continue;
      }
      /* Substitute variables now */
      if (sw->eval) {
         if (!(tmpdata = ast_str_thread_get(&switch_data, 512))) {
            ast_log(LOG_WARNING, "Can't evaluate switch?!");
            continue;
         }
         pbx_substitute_variables_helper(chan, sw->data, ast_str_buffer(tmpdata), ast_str_size(tmpdata));
      }
      /* equivalent of extension_match_core() at the switch level */
      if (action == E_CANMATCH)
         aswf = asw->canmatch;
      else if (action == E_MATCHMORE)
         aswf = asw->matchmore;
      else /* action == E_MATCH */
         aswf = asw->exists;
      datap = sw->eval ? ast_str_buffer(tmpdata) : sw->data;
      if (!aswf)
         res = 0;
      else {
         if (chan)
            ast_autoservice_start(chan);
         res = aswf(chan, context, exten, priority, callerid, datap);
         if (chan)
            ast_autoservice_stop(chan);
      }
      if (res) {  /* Got a match */
         q->swo = asw;
         q->data = datap;
         q->foundcontext = context;
         /* XXX keep status = STATUS_NO_CONTEXT ? */
         return NULL;
      }
   }
   q->incstack[q->stacklen++] = tmp->name;   /* Setup the stack */
   /* Now try any includes we have in this context */
   for (i = tmp->includes; i; i = i->next) {
      if (include_valid(i)) {
         if ((e = pbx_find_extension(chan, bypass, q, i->rname, exten, priority, label, callerid, action))) {
#ifdef NEED_DEBUG_HERE
            ast_log(LOG_NOTICE,"Returning recursive match of %s\n", e->exten);
#endif
            return e;
         }
         if (q->swo)
            return NULL;
      }
   }
   return NULL;
}
struct ast_app* pbx_findapp (const char * app) [read]
Find application handle in linked list.
Look up an application.
Definition at line 1363 of file pbx.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, and ast_app::name.
Referenced by answer_exec_run(), ast_bridge_call(), ast_pbx_run_app(), async_wait(), builtin_automixmonitor(), builtin_automonitor(), conf_run(), dial_exec_full(), do_magic_pickup(), dundi_exec(), exec_exec(), execif_exec(), feature_exec_app(), forward_message(), handle_exec(), handle_gosub(), iax2_exec(), lua_pbx_exec(), page_exec(), pbx_builtin_execiftime(), pbx_extension_helper(), realtime_exec(), try_calling(), and tryexec_exec().
{
   struct ast_app *tmp;
   AST_RWLIST_RDLOCK(&apps);
   AST_RWLIST_TRAVERSE(&apps, tmp, list) {
      if (!strcasecmp(tmp->name, app))
         break;
   }
   AST_RWLIST_UNLOCK(&apps);
   return tmp;
}
static struct ast_switch* pbx_findswitch (const char * sw) [static, read]
Definition at line 1377 of file pbx.c.
References AST_RWLIST_RDLOCK, AST_RWLIST_TRAVERSE, AST_RWLIST_UNLOCK, and ast_switch::name.
Referenced by pbx_find_extension().
{
   struct ast_switch *asw;
   AST_RWLIST_RDLOCK(&switches);
   AST_RWLIST_TRAVERSE(&switches, asw, list) {
      if (!strcasecmp(asw->name, sw))
         break;
   }
   AST_RWLIST_UNLOCK(&switches);
   return asw;
}
static int pbx_parseable_goto (struct ast_channel * chan, const char * goto_string, int async) [static]
Definition at line 9580 of file pbx.c.
References ast_async_goto(), ast_explicit_goto(), ast_findlabel_extension(), ast_log(), ast_strdupa, ast_strlen_zero(), ast_channel::cid, ast_callerid::cid_num, ast_channel::context, ast_channel::exten, LOG_WARNING, ast_channel::priority, and strsep().
Referenced by ast_async_parseable_goto(), and ast_parseable_goto().
{
   char *exten, *pri, *context;
   char *stringp;
   int ipri;
   int mode = 0;
   if (ast_strlen_zero(goto_string)) {
      ast_log(LOG_WARNING, "Goto requires an argument ([[context,]extension,]priority)\n");
      return -1;
   }
   stringp = ast_strdupa(goto_string);
   context = strsep(&stringp, ","); /* guaranteed non-null */
   exten = strsep(&stringp, ",");
   pri = strsep(&stringp, ",");
   if (!exten) {  /* Only a priority in this one */
      pri = context;
      exten = NULL;
      context = NULL;
   } else if (!pri) {   /* Only an extension and priority in this one */
      pri = exten;
      exten = context;
      context = NULL;
   }
   if (*pri == '+') {
      mode = 1;
      pri++;
   } else if (*pri == '-') {
      mode = -1;
      pri++;
   }
   if (sscanf(pri, "%30d", &ipri) != 1) {
      if ((ipri = ast_findlabel_extension(chan, context ? context : chan->context, exten ? exten : chan->exten,
         pri, chan->cid.cid_num)) < 1) {
         ast_log(LOG_WARNING, "Priority '%s' must be a number > 0, or valid label\n", pri);
         return -1;
      } else
         mode = 0;
   }
   /* At this point we have a priority and maybe an extension and a context */
   if (mode)
      ipri = chan->priority + (ipri * mode);
   if (async)
      ast_async_goto(chan, context, exten, ipri);
   else
      ast_explicit_goto(chan, context, exten, ipri);
   return 0;
}
void pbx_retrieve_variable (struct ast_channel * c, const char * var, char ** ret, char * workspace, int workspacelen, struct varshead * headp)
Support for Asterisk built-in variables in the dialplan.
Retrieve the value of a builtin variable or variable from the channel variable stack.
Note:
See also
Globally predefined channel variables Channel variables
Hangup Causes for Asterisk The HANGUPCAUSE variable
Definition at line 2867 of file pbx.c.
References ARRAY_LEN, ast_channel_lock, ast_channel_unlock, ast_config_AST_SYSTEM_NAME, ast_copy_string(), ast_eid_default, ast_eid_to_str(), ast_get_hint(), AST_LIST_TRAVERSE, ast_rwlock_rdlock(), ast_rwlock_unlock(), ast_strdupa, ast_var_name(), ast_var_value(), ast_channel::cid, ast_callerid::cid_ani2, ast_callerid::cid_pres, ast_callerid::cid_tns, ast_callerid::cid_ton, ast_channel::context, ast_channel::exten, globals, globalslock, ast_channel::hangupcause, parse_variable_name(), ast_channel::priority, s, substring(), and ast_channel::varshead.
Referenced by action_getvar(), action_status(), handle_getvariable(), lua_get_variable(), lua_get_variable_value(), and pbx_substitute_variables_helper_full().
{
   const char not_found = '\0';
   char *tmpvar;
   const char *s; /* the result */
   int offset, length;
   int i, need_substring;
   struct varshead *places[2] = { headp, &globals };  /* list of places where we may look */
   if (c) {
      ast_channel_lock(c);
      places[0] = &c->varshead;
   }
   /*
    * Make a copy of var because parse_variable_name() modifies the string.
    * Then if called directly, we might need to run substring() on the result;
    * remember this for later in 'need_substring', 'offset' and 'length'
    */
   tmpvar = ast_strdupa(var); /* parse_variable_name modifies the string */
   need_substring = parse_variable_name(tmpvar, &offset, &length, &i /* ignored */);
   /*
    * Look first into predefined variables, then into variable lists.
    * Variable 's' points to the result, according to the following rules:
    * s == &not_found (set at the beginning) means that we did not find a
    * matching variable and need to look into more places.
    * If s != &not_found, s is a valid result string as follows:
    * s = NULL if the variable does not have a value;
    * you typically do this when looking for an unset predefined variable.
    * s = workspace if the result has been assembled there;
    * typically done when the result is built e.g. with an snprintf(),
    * so we don't need to do an additional copy.
    * s != workspace in case we have a string, that needs to be copied
    * (the ast_copy_string is done once for all at the end).
    * Typically done when the result is already available in some string.
    */
   s = &not_found;   /* default value */
   if (c) { /* This group requires a valid channel */
      /* Names with common parts are looked up a piece at a time using strncmp. */
      if (!strncmp(var, "CALL", 4)) {
         if (!strncmp(var + 4, "ING", 3)) {
            if (!strcmp(var + 7, "PRES")) {        /* CALLINGPRES */
               snprintf(workspace, workspacelen, "%d", c->cid.cid_pres);
               s = workspace;
            } else if (!strcmp(var + 7, "ANI2")) {    /* CALLINGANI2 */
               snprintf(workspace, workspacelen, "%d", c->cid.cid_ani2);
               s = workspace;
            } else if (!strcmp(var + 7, "TON")) {     /* CALLINGTON */
               snprintf(workspace, workspacelen, "%d", c->cid.cid_ton);
               s = workspace;
            } else if (!strcmp(var + 7, "TNS")) {     /* CALLINGTNS */
               snprintf(workspace, workspacelen, "%d", c->cid.cid_tns);
               s = workspace;
            }
         }
      } else if (!strcmp(var, "HINT")) {
         s = ast_get_hint(workspace, workspacelen, NULL, 0, c, c->context, c->exten) ? workspace : NULL;
      } else if (!strcmp(var, "HINTNAME")) {
         s = ast_get_hint(NULL, 0, workspace, workspacelen, c, c->context, c->exten) ? workspace : NULL;
      } else if (!strcmp(var, "EXTEN")) {
         s = c->exten;
      } else if (!strcmp(var, "CONTEXT")) {
         s = c->context;
      } else if (!strcmp(var, "PRIORITY")) {
         snprintf(workspace, workspacelen, "%d", c->priority);
         s = workspace;
      } else if (!strcmp(var, "CHANNEL")) {
         s = c->name;
      } else if (!strcmp(var, "UNIQUEID")) {
         s = c->uniqueid;
      } else if (!strcmp(var, "HANGUPCAUSE")) {
         snprintf(workspace, workspacelen, "%d", c->hangupcause);
         s = workspace;
      }
   }
   if (s == &not_found) { /* look for more */
      if (!strcmp(var, "EPOCH")) {
         snprintf(workspace, workspacelen, "%u",(int)time(NULL));
         s = workspace;
      } else if (!strcmp(var, "SYSTEMNAME")) {
         s = ast_config_AST_SYSTEM_NAME;
      } else if (!strcmp(var, "ENTITYID")) {
         ast_eid_to_str(workspace, workspacelen, &ast_eid_default);
         s = workspace;
      }
   }
   /* if not found, look into chanvars or global vars */
   for (i = 0; s == &not_found && i < ARRAY_LEN(places); i++) {
      struct ast_var_t *variables;
      if (!places[i])
         continue;
      if (places[i] == &globals)
         ast_rwlock_rdlock(&globalslock);
      AST_LIST_TRAVERSE(places[i], variables, entries) {
         if (!strcasecmp(ast_var_name(variables), var)) {
            s = ast_var_value(variables);
            break;
         }
      }
      if (places[i] == &globals)
         ast_rwlock_unlock(&globalslock);
   }
   if (s == &not_found || s == NULL)
      *ret = NULL;
   else {
      if (s != workspace)
         ast_copy_string(workspace, s, workspacelen);
      *ret = workspace;
      if (need_substring)
         *ret = substring(*ret, offset, length, workspace, workspacelen);
   }
   if (c)
      ast_channel_unlock(c);
}
int pbx_set_autofallthrough (int newval)
Set "autofallthrough" flag, if newval is <0, does not actually set. If set to 1, sets to auto fall through. If newval set to 0, sets to no auto fall through (reads extension instead). Returns previous value.
Definition at line 4611 of file pbx.c.
References autofallthrough.
Referenced by pbx_load_module().
{
   int oldval = autofallthrough;
   autofallthrough = newval;
   return oldval;
}
int pbx_set_extenpatternmatchnew (int newval)
Set "extenpatternmatchnew" flag, if newval is <0, does not actually set. If set to 1, sets to use the new Trie-based pattern matcher. If newval set to 0, sets to use the old linear-search algorithm. Returns previous value.
Definition at line 4618 of file pbx.c.
References extenpatternmatchnew.
Referenced by handle_set_extenpatternmatchnew(), handle_unset_extenpatternmatchnew(), and pbx_load_module().
{
   int oldval = extenpatternmatchnew;
   extenpatternmatchnew = newval;
   return oldval;
}
void pbx_set_overrideswitch (const char * newval)
Set "overrideswitch" field. If set and of nonzero length, all contexts will be tried directly through the named switch prior to any other matching within that context.
Since:
1.6.1
Definition at line 4625 of file pbx.c.
References ast_free, ast_strdup, ast_strlen_zero(), and overrideswitch.
Referenced by pbx_load_module().
{
   if (overrideswitch) {
      ast_free(overrideswitch);
   }
   if (!ast_strlen_zero(newval)) {
      overrideswitch = ast_strdup(newval);
   } else {
      overrideswitch = NULL;
   }
}
static void pbx_substitute_variables (char * passdata, int datalen, struct ast_channel * c, struct ast_exten * e) [static]
Definition at line 3610 of file pbx.c.
References ast_copy_string(), ast_exten::data, and pbx_substitute_variables_helper().
Referenced by pbx_extension_helper().
{
   const char *tmp;
   /* Nothing more to do */
   if (!e->data) {
      *passdata = '\0';
      return;
   }
   /* No variables or expressions in e->data, so why scan it? */
   if ((!(tmp = strchr(e->data, '$'))) || (!strstr(tmp, "${") && !strstr(tmp, "$["))) {
      ast_copy_string(passdata, e->data, datalen);
      return;
   }
   pbx_substitute_variables_helper(c, e->data, passdata, datalen - 1);
}
void pbx_substitute_variables_helper (struct ast_channel * c, const char * cp1, char * cp2, int count)
Definition at line 3598 of file pbx.c.
References pbx_substitute_variables_helper_full(), and ast_channel::varshead.
Referenced by _macro_exec(), acf_import(), add_extensions(), ast_add_extension2_lockopt(), config_curl(), custom_log(), cut_internal(), destroy_curl(), exec_exec(), function_eval(), function_fieldqty(), get_mapping_weight(), handle_getvariablefull(), launch_monitor_thread(), make_email_file(), manager_log(), pbx_builtin_importvar(), pbx_find_extension(), pbx_load_config(), pbx_substitute_variables(), realtime_curl(), realtime_exec(), realtime_multi_curl(), require_curl(), rotate_file(), rpt_do_lstats(), rpt_exec(), sendmail(), sendpage(), sqlite3_log(), store_curl(), substituted(), try_calling(), tryexec_exec(), update2_curl(), and update_curl().
{
   size_t used;
   pbx_substitute_variables_helper_full(c, (c) ? &c->varshead : NULL, cp1, cp2, count, &used);
}
void pbx_substitute_variables_helper_full (struct ast_channel * c, struct varshead * headp, const char * cp1, char * cp2, int count, size_t * used)
Definition at line 3403 of file pbx.c.
References ast_channel_alloc, ast_channel_free(), ast_copy_string(), ast_debug, ast_expr(), ast_func_read(), ast_log(), ast_strlen_zero(), len(), LOG_ERROR, LOG_WARNING, parse_variable_name(), pbx_retrieve_variable(), pbx_substitute_variables_helper_full(), substring(), var, VAR_BUF_SIZE, and ast_channel::varshead.
Referenced by ast_str_substitute_variables(), pbx_substitute_variables_helper(), pbx_substitute_variables_helper_full(), and pbx_substitute_variables_varshead().
{
   /* Substitutes variables into cp2, based on string cp1, cp2 NO LONGER NEEDS TO BE ZEROED OUT!!!!  */
   char *cp4;
   const char *tmp, *whereweare, *orig_cp2 = cp2;
   int length, offset, offset2, isfunction;
   char *workspace = NULL;
   char *ltmp = NULL, *var = NULL;
   char *nextvar, *nextexp, *nextthing;
   char *vars, *vare;
   int pos, brackets, needsub, len;
   *cp2 = 0; /* just in case nothing ends up there */
   whereweare=tmp=cp1;
   while (!ast_strlen_zero(whereweare) && count) {
      /* Assume we're copying the whole remaining string */
      pos = strlen(whereweare);
      nextvar = NULL;
      nextexp = NULL;
      nextthing = strchr(whereweare, '$');
      if (nextthing) {
         switch (nextthing[1]) {
         case '{':
            nextvar = nextthing;
            pos = nextvar - whereweare;
            break;
         case '[':
            nextexp = nextthing;
            pos = nextexp - whereweare;
            break;
         default:
            pos = 1;
         }
      }
      if (pos) {
         /* Can't copy more than 'count' bytes */
         if (pos > count)
            pos = count;
         /* Copy that many bytes */
         memcpy(cp2, whereweare, pos);
         count -= pos;
         cp2 += pos;
         whereweare += pos;
         *cp2 = 0;
      }
      if (nextvar) {
         /* We have a variable.  Find the start and end, and determine
            if we are going to have to recursively call ourselves on the
            contents */
         vars = vare = nextvar + 2;
         brackets = 1;
         needsub = 0;
         /* Find the end of it */
         while (brackets && *vare) {
            if ((vare[0] == '$') && (vare[1] == '{')) {
               needsub++;
            } else if (vare[0] == '{') {
               brackets++;
            } else if (vare[0] == '}') {
               brackets--;
            } else if ((vare[0] == '$') && (vare[1] == '['))
               needsub++;
            vare++;
         }
         if (brackets)
            ast_log(LOG_WARNING, "Error in extension logic (missing '}')\n");
         len = vare - vars - 1;
         /* Skip totally over variable string */
         whereweare += (len + 3);
         if (!var)
            var = alloca(VAR_BUF_SIZE);
         /* Store variable name (and truncate) */
         ast_copy_string(var, vars, len + 1);
         /* Substitute if necessary */
         if (needsub) {
            size_t used;
            if (!ltmp)
               ltmp = alloca(VAR_BUF_SIZE);
            pbx_substitute_variables_helper_full(c, headp, var, ltmp, VAR_BUF_SIZE - 1, &used);
            vars = ltmp;
         } else {
            vars = var;
         }
         if (!workspace)
            workspace = alloca(VAR_BUF_SIZE);
         workspace[0] = '\0';
         parse_variable_name(vars, &offset, &offset2, &isfunction);
         if (isfunction) {
            /* Evaluate function */
            if (c || !headp)
               cp4 = ast_func_read(c, vars, workspace, VAR_BUF_SIZE) ? NULL : workspace;
            else {
               struct varshead old;
               struct ast_channel *bogus = ast_channel_alloc(0, 0, "", "", "", "", "", 0, "Bogus/%p", vars);
               if (bogus) {
                  memcpy(&old, &bogus->varshead, sizeof(old));
                  memcpy(&bogus->varshead, headp, sizeof(bogus->varshead));
                  cp4 = ast_func_read(bogus, vars, workspace, VAR_BUF_SIZE) ? NULL : workspace;
                  /* Don't deallocate the varshead that was passed in */
                  memcpy(&bogus->varshead, &old, sizeof(bogus->varshead));
                  ast_channel_free(bogus);
               } else
                  ast_log(LOG_ERROR, "Unable to allocate bogus channel for variable substitution.  Function results may be blank.\n");
            }
            ast_debug(2, "Function result is '%s'\n", cp4 ? cp4 : "(null)");
         } else {
            /* Retrieve variable value */
            pbx_retrieve_variable(c, vars, &cp4, workspace, VAR_BUF_SIZE, headp);
         }
         if (cp4) {
            cp4 = substring(cp4, offset, offset2, workspace, VAR_BUF_SIZE);
            length = strlen(cp4);
            if (length > count)
               length = count;
            memcpy(cp2, cp4, length);
            count -= length;
            cp2 += length;
            *cp2 = 0;
         }
      } else if (nextexp) {
         /* We have an expression.  Find the start and end, and determine
            if we are going to have to recursively call ourselves on the
            contents */
         vars = vare = nextexp + 2;
         brackets = 1;
         needsub = 0;
         /* Find the end of it */
         while (brackets && *vare) {
            if ((vare[0] == '$') && (vare[1] == '[')) {
               needsub++;
               brackets++;
               vare++;
            } else if (vare[0] == '[') {
               brackets++;
            } else if (vare[0] == ']') {
               brackets--;
            } else if ((vare[0] == '$') && (vare[1] == '{')) {
               needsub++;
               vare++;
            }
            vare++;
         }
         if (brackets)
            ast_log(LOG_WARNING, "Error in extension logic (missing ']')\n");
         len = vare - vars - 1;
         /* Skip totally over expression */
         whereweare += (len + 3);
         if (!var)
            var = alloca(VAR_BUF_SIZE);
         /* Store variable name (and truncate) */
         ast_copy_string(var, vars, len + 1);
         /* Substitute if necessary */
         if (needsub) {
            size_t used;
            if (!ltmp)
               ltmp = alloca(VAR_BUF_SIZE);
            pbx_substitute_variables_helper_full(c, headp, var, ltmp, VAR_BUF_SIZE - 1, &used);
            vars = ltmp;
         } else {
            vars = var;
         }
         length = ast_expr(vars, cp2, count, c);
         if (length) {
            ast_debug(1, "Expression result is '%s'\n", cp2);
            count -= length;
            cp2 += length;
            *cp2 = 0;
         }
      }
   }
   *used = cp2 - orig_cp2;
}
void pbx_substitute_variables_varshead (struct varshead * headp, const char * cp1, char * cp2, int count)
Definition at line 3604 of file pbx.c.
References pbx_substitute_variables_helper_full().
Referenced by add_user_extension(), build_user_routes(), do_say(), dundi_lookup_local(), loopback_subst(), phoneprov_callback(), pp_each_extension_exec(), and pp_each_user_exec().
{
   size_t used;
   pbx_substitute_variables_helper_full(NULL, headp, cp1, cp2, count, &used);
}
static void* pbx_thread (void * data) [static]
Definition at line 4539 of file pbx.c.
References __ast_pbx_run(), and decrease_call_count().
Referenced by ast_pbx_start().
{
   /* Oh joyeous kernel, we're a new thread, with nothing to do but
      answer this channel and get it going.
   */
   /* NOTE:
      The launcher of this function _MUST_ increment 'countcalls'
      before invoking the function; it will be decremented when the
      PBX has finished running on the channel
    */
   struct ast_channel *c = data;
   __ast_pbx_run(c, NULL);
   decrease_call_count();
   pthread_exit(NULL);
   return NULL;
}
static void print_app_docs (struct ast_app * aa, int fd) [static]
Definition at line 5186 of file pbx.c.
References ast_app::arguments, ast_cli(), ast_free, ast_malloc, AST_MAX_APP, AST_TERM_MAX_ESCAPE_CHARS, AST_XML_DOC, ast_xmldoc_printable(), COLOR_CYAN, COLOR_MAGENTA, ast_app::description, description, ast_app::docsrc, ast_app::name, S_OR, ast_app::seealso, ast_app::synopsis, synopsis, ast_app::syntax, and term_color().
Referenced by handle_show_application().
{
   /* Maximum number of characters added by terminal coloring is 22 */
   char infotitle[64 + AST_MAX_APP + 22], syntitle[40], destitle[40], stxtitle[40], argtitle[40];
   char seealsotitle[40];
   char info[64 + AST_MAX_APP], *synopsis = NULL, *description = NULL, *syntax = NULL, *arguments = NULL;
   char *seealso = NULL;
   int syntax_size, synopsis_size, description_size, arguments_size, seealso_size;
   snprintf(info, sizeof(info), "\n  -= Info about application '%s' =- \n\n", aa->name);
   term_color(infotitle, info, COLOR_MAGENTA, 0, sizeof(infotitle));
   term_color(syntitle, "[Synopsis]\n", COLOR_MAGENTA, 0, 40);
   term_color(destitle, "[Description]\n", COLOR_MAGENTA, 0, 40);
   term_color(stxtitle, "[Syntax]\n", COLOR_MAGENTA, 0, 40);
   term_color(argtitle, "[Arguments]\n", COLOR_MAGENTA, 0, 40);
   term_color(seealsotitle, "[See Also]\n", COLOR_MAGENTA, 0, 40);
#ifdef AST_XML_DOCS
   if (aa->docsrc == AST_XML_DOC) {
      description = ast_xmldoc_printable(S_OR(aa->description, "Not available"), 1);
      arguments = ast_xmldoc_printable(S_OR(aa->arguments, "Not available"), 1);
      synopsis = ast_xmldoc_printable(S_OR(aa->synopsis, "Not available"), 1);
      seealso = ast_xmldoc_printable(S_OR(aa->seealso, "Not available"), 1);
      if (!synopsis || !description || !arguments || !seealso) {
         goto return_cleanup;
      }
   } else
#endif
   {
      synopsis_size = strlen(S_OR(aa->synopsis, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      synopsis = ast_malloc(synopsis_size);
      description_size = strlen(S_OR(aa->description, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      description = ast_malloc(description_size);
      arguments_size = strlen(S_OR(aa->arguments, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      arguments = ast_malloc(arguments_size);
      seealso_size = strlen(S_OR(aa->seealso, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
      seealso = ast_malloc(seealso_size);
      if (!synopsis || !description || !arguments || !seealso) {
         goto return_cleanup;
      }
      term_color(synopsis, S_OR(aa->synopsis, "Not available"), COLOR_CYAN, 0, synopsis_size);
      term_color(description, S_OR(aa->description, "Not available"),   COLOR_CYAN, 0, description_size);
      term_color(arguments, S_OR(aa->arguments, "Not available"), COLOR_CYAN, 0, arguments_size);
      term_color(seealso, S_OR(aa->seealso, "Not available"), COLOR_CYAN, 0, seealso_size);
   }
   /* Handle the syntax the same for both XML and raw docs */
   syntax_size = strlen(S_OR(aa->syntax, "Not Available")) + AST_TERM_MAX_ESCAPE_CHARS;
   if (!(syntax = ast_malloc(syntax_size))) {
      goto return_cleanup;
   }
   term_color(syntax, S_OR(aa->syntax, "Not available"), COLOR_CYAN, 0, syntax_size);
   ast_cli(fd, "%s%s%s\n\n%s%s\n\n%s%s\n\n%s%s\n\n%s%s\n",
         infotitle, syntitle, synopsis, destitle, description,
         stxtitle, syntax, argtitle, arguments, seealsotitle, seealso);
return_cleanup:
   ast_free(description);
   ast_free(arguments);
   ast_free(synopsis);
   ast_free(seealso);
   ast_free(syntax);
}
static void print_ext (struct ast_exten * e, char * buf, int buflen) [static]
helper function to print an extension
Definition at line 5607 of file pbx.c.
References ast_get_extension_app(), ast_get_extension_app_data(), ast_get_extension_priority(), ast_strlen_zero(), and PRIORITY_HINT.
Referenced by show_dialplan_helper().
{
   int prio = ast_get_extension_priority(e);
   if (prio == PRIORITY_HINT) {
      snprintf(buf, buflen, "hint: %s",
         ast_get_extension_app(e));
   } else {
      snprintf(buf, buflen, "%d. %s(%s)",
         prio, ast_get_extension_app(e),
         (!ast_strlen_zero(ast_get_extension_app_data(e)) ? (char *)ast_get_extension_app_data(e) : ""));
   }
}
static void set_ext_pri (struct ast_channel * c, const char * exten, int pri) [static]
helper function to set extension and priority
Definition at line 4174 of file pbx.c.
References ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_channel::exten, and ast_channel::priority.
Referenced by __ast_pbx_run(), ast_pbx_outgoing_exten(), pbx_builtin_raise_exception(), and pbx_builtin_waitexten().
{
   ast_channel_lock(c);
   ast_copy_string(c->exten, exten, sizeof(c->exten));
   c->priority = pri;
   ast_channel_unlock(c);
}
static int show_debug_helper (int fd, const char * context, const char * exten, struct dialplan_counters * dpc, struct ast_include * rinclude, int includecount, const char * includes[]) [static]
Definition at line 5772 of file pbx.c.
References ast_cli(), ast_exists_extension(), ast_get_context_name(), ast_get_context_registrar(), ast_rdlock_context(), ast_rdlock_contexts(), ast_unlock_context(), ast_unlock_contexts(), ast_walk_contexts(), cli_match_char_tree(), dialplan_counters::context_existence, ast_context::name, ast_context::pattern_tree, dialplan_counters::total_context, and dialplan_counters::total_exten.
Referenced by handle_debug_dialplan().
{
   struct ast_context *c = NULL;
   int res = 0, old_total_exten = dpc->total_exten;
   ast_cli(fd,"\n     In-mem exten Trie for Fast Extension Pattern Matching:\n\n");
   ast_cli(fd,"\n           Explanation: Node Contents Format = <char(s) to match>:<pattern?>:<specif>:[matched extension]\n");
   ast_cli(fd,    "                        Where <char(s) to match> is a set of chars, any one of which should match the current character\n");
   ast_cli(fd,    "                              <pattern?>: Y if this a pattern match (eg. _XZN[5-7]), N otherwise\n");
   ast_cli(fd,    "                              <specif>: an assigned 'exactness' number for this matching char. The lower the number, the more exact the match\n");
   ast_cli(fd,    "                              [matched exten]: If all chars matched to this point, which extension this matches. In form: EXTEN:<exten string>\n");
   ast_cli(fd,    "                        In general, you match a trie node to a string character, from left to right. All possible matching chars\n");
   ast_cli(fd,    "                        are in a string vertically, separated by an unbroken string of '+' characters.\n\n");
   ast_rdlock_contexts();
   /* walk all contexts ... */
   while ( (c = ast_walk_contexts(c)) ) {
      int context_info_printed = 0;
      if (context && strcmp(ast_get_context_name(c), context))
         continue;   /* skip this one, name doesn't match */
      dpc->context_existence = 1;
      if (!c->pattern_tree)
         ast_exists_extension(NULL, c->name, "s", 1, ""); /* do this to force the trie to built, if it is not already */
      ast_rdlock_context(c);
      dpc->total_context++;
      ast_cli(fd, "[ Context '%s' created by '%s' ]\n",
         ast_get_context_name(c), ast_get_context_registrar(c));
      context_info_printed = 1;
      if (c->pattern_tree)
      {
         cli_match_char_tree(c->pattern_tree, " ", fd);
      } else {
         ast_cli(fd,"\n     No Pattern Trie present. Perhaps the context is empty...or there is trouble...\n\n");
      }
      ast_unlock_context(c);
      /* if we print something in context, make an empty line */
      if (context_info_printed)
         ast_cli(fd, "\n");
   }
   ast_unlock_contexts();
   return (dpc->total_exten == old_total_exten) ? -1 : res;
}
static int show_dialplan_helper (int fd, const char * context, const char * exten, struct dialplan_counters * dpc, struct ast_include * rinclude, int includecount, const char * includes[]) [static]
Definition at line 5621 of file pbx.c.
References ast_cli(), ast_extension_match(), ast_get_context_name(), ast_get_context_registrar(), ast_get_extension_label(), ast_get_extension_name(), ast_get_extension_registrar(), ast_get_ignorepat_name(), ast_get_ignorepat_registrar(), ast_get_include_name(), ast_get_include_registrar(), ast_get_switch_data(), ast_get_switch_name(), ast_get_switch_registrar(), ast_log(), AST_MAX_EXTENSION, AST_PBX_MAX_STACK, ast_rdlock_context(), ast_rdlock_contexts(), ast_unlock_context(), ast_unlock_contexts(), ast_walk_context_extensions(), ast_walk_context_ignorepats(), ast_walk_context_includes(), ast_walk_context_switches(), ast_walk_contexts(), ast_walk_extension_priorities(), buf, ast_exten::cidmatch, dialplan_counters::context_existence, el, dialplan_counters::extension_existence, LOG_WARNING, ast_exten::matchcid, print_ext(), dialplan_counters::total_context, dialplan_counters::total_exten, and dialplan_counters::total_prio.
Referenced by handle_show_dialplan().
{
   struct ast_context *c = NULL;
   int res = 0, old_total_exten = dpc->total_exten;
   ast_rdlock_contexts();
   /* walk all contexts ... */
   while ( (c = ast_walk_contexts(c)) ) {
      struct ast_exten *e;
      struct ast_include *i;
      struct ast_ignorepat *ip;
      char buf[256], buf2[256];
      int context_info_printed = 0;
      if (context && strcmp(ast_get_context_name(c), context))
         continue;   /* skip this one, name doesn't match */
      dpc->context_existence = 1;
      ast_rdlock_context(c);
      /* are we looking for exten too? if yes, we print context
       * only if we find our extension.
       * Otherwise print context even if empty ?
       * XXX i am not sure how the rinclude is handled.
       * I think it ought to go inside.
       */
      if (!exten) {
         dpc->total_context++;
         ast_cli(fd, "[ Context '%s' created by '%s' ]\n",
            ast_get_context_name(c), ast_get_context_registrar(c));
         context_info_printed = 1;
      }
      /* walk extensions ... */
      e = NULL;
      while ( (e = ast_walk_context_extensions(c, e)) ) {
         struct ast_exten *p;
         if (exten && !ast_extension_match(ast_get_extension_name(e), exten))
            continue;   /* skip, extension match failed */
         dpc->extension_existence = 1;
         /* may we print context info? */
         if (!context_info_printed) {
            dpc->total_context++;
            if (rinclude) { /* TODO Print more info about rinclude */
               ast_cli(fd, "[ Included context '%s' created by '%s' ]\n",
                  ast_get_context_name(c), ast_get_context_registrar(c));
            } else {
               ast_cli(fd, "[ Context '%s' created by '%s' ]\n",
                  ast_get_context_name(c), ast_get_context_registrar(c));
            }
            context_info_printed = 1;
         }
         dpc->total_prio++;
         /* write extension name and first peer */
         if (e->matchcid)
            snprintf(buf, sizeof(buf), "'%s' (CID match '%s') => ", ast_get_extension_name(e), e->cidmatch);
         else
            snprintf(buf, sizeof(buf), "'%s' =>", ast_get_extension_name(e));
         print_ext(e, buf2, sizeof(buf2));
         ast_cli(fd, "  %-17s %-45s [%s]\n", buf, buf2,
            ast_get_extension_registrar(e));
         dpc->total_exten++;
         /* walk next extension peers */
         p = e;   /* skip the first one, we already got it */
         while ( (p = ast_walk_extension_priorities(e, p)) ) {
            const char *el = ast_get_extension_label(p);
            dpc->total_prio++;
            if (el)
               snprintf(buf, sizeof(buf), "   [%s]", el);
            else
               buf[0] = '\0';
            print_ext(p, buf2, sizeof(buf2));
            ast_cli(fd,"  %-17s %-45s [%s]\n", buf, buf2,
               ast_get_extension_registrar(p));
         }
      }
      /* walk included and write info ... */
      i = NULL;
      while ( (i = ast_walk_context_includes(c, i)) ) {
         snprintf(buf, sizeof(buf), "'%s'", ast_get_include_name(i));
         if (exten) {
            /* Check all includes for the requested extension */
            if (includecount >= AST_PBX_MAX_STACK) {
               ast_log(LOG_WARNING, "Maximum include depth exceeded!\n");
            } else {
               int dupe = 0;
               int x;
               for (x = 0; x < includecount; x++) {
                  if (!strcasecmp(includes[x], ast_get_include_name(i))) {
                     dupe++;
                     break;
                  }
               }
               if (!dupe) {
                  includes[includecount] = ast_get_include_name(i);
                  show_dialplan_helper(fd, ast_get_include_name(i), exten, dpc, i, includecount + 1, includes);
               } else {
                  ast_log(LOG_WARNING, "Avoiding circular include of %s within %s\n", ast_get_include_name(i), context);
               }
            }
         } else {
            ast_cli(fd, "  Include =>        %-45s [%s]\n",
               buf, ast_get_include_registrar(i));
         }
      }
      /* walk ignore patterns and write info ... */
      ip = NULL;
      while ( (ip = ast_walk_context_ignorepats(c, ip)) ) {
         const char *ipname = ast_get_ignorepat_name(ip);
         char ignorepat[AST_MAX_EXTENSION];
         snprintf(buf, sizeof(buf), "'%s'", ipname);
         snprintf(ignorepat, sizeof(ignorepat), "_%s.", ipname);
         if (!exten || ast_extension_match(ignorepat, exten)) {
            ast_cli(fd, "  Ignore pattern => %-45s [%s]\n",
               buf, ast_get_ignorepat_registrar(ip));
         }
      }
      if (!rinclude) {
         struct ast_sw *sw = NULL;
         while ( (sw = ast_walk_context_switches(c, sw)) ) {
            snprintf(buf, sizeof(buf), "'%s/%s'",
               ast_get_switch_name(sw),
               ast_get_switch_data(sw));
            ast_cli(fd, "  Alt. Switch =>    %-45s [%s]\n",
               buf, ast_get_switch_registrar(sw));
         }
      }
      ast_unlock_context(c);
      /* if we print something in context, make an empty line */
      if (context_info_printed)
         ast_cli(fd, "\n");
   }
   ast_unlock_contexts();
   return (dpc->total_exten == old_total_exten) ? -1 : res;
}
static char* substring (const char * value, int offset, int length, char * workspace, size_t workspace_len) [static]
takes a substring. It is ok to call with value == workspace.
Parameters:
value
offset < 0 means start from the end of the string and set the beginning to be that many characters back.
length is the length of the substring, a value less than 0 means to leave that many off the end.
workspace
workspace_len Always return a copy in workspace.
Definition at line 2825 of file pbx.c.
References ast_copy_string().
Referenced by pbx_retrieve_variable(), and pbx_substitute_variables_helper_full().
{
   char *ret = workspace;
   int lr;  /* length of the input string after the copy */
   ast_copy_string(workspace, value, workspace_len); /* always make a copy */
   lr = strlen(ret); /* compute length after copy, so we never go out of the workspace */
   /* Quick check if no need to do anything */
   if (offset == 0 && length >= lr) /* take the whole string */
      return ret;
   if (offset < 0)   {  /* translate negative offset into positive ones */
      offset = lr + offset;
      if (offset < 0) /* If the negative offset was greater than the length of the string, just start at the beginning */
         offset = 0;
   }
   /* too large offset result in empty string so we know what to return */
   if (offset >= lr)
      return ret + lr;  /* the final '\0' */
   ret += offset;    /* move to the start position */
   if (length >= 0 && length < lr - offset)  /* truncate if necessary */
      ret[length] = '\0';
   else if (length < 0) {
      if (lr > offset - length) /* After we remove from the front and from the rear, is there anything left? */
         ret[lr + length - offset] = '\0';
      else
         ret[0] = '\0';
   }
   return ret;
}
static struct ast_exten* trie_find_next_match (struct match_char * node) [static, read]
Definition at line 1571 of file pbx.c.
References match_char::alt_char, match_char::exten, match_char::next_char, and match_char::x.
Referenced by pbx_find_extension().
{
   struct match_char *m3;
   struct match_char *m4;
   struct ast_exten *e3;
   if (node && node->x[0] == '.' && !node->x[1]) { /* dot and ! will ALWAYS be next match in a matchmore */
      return node->exten;
   }
   if (node && node->x[0] == '!' && !node->x[1]) {
      return node->exten;
   }
   if (!node || !node->next_char) {
      return NULL;
   }
   m3 = node->next_char;
   if (m3->exten) {
      return m3->exten;
   }
   for (m4 = m3->alt_char; m4; m4 = m4->alt_char) {
      if (m4->exten) {
         return m4->exten;
      }
   }
   for (m4 = m3; m4; m4 = m4->alt_char) {
      e3 = trie_find_next_match(m3);
      if (e3) {
         return e3;
      }
   }
   return NULL;
}
static void unreference_cached_app (struct ast_app * app) [static]
Definition at line 6384 of file pbx.c.
References ast_rdlock_contexts(), ast_unlock_contexts(), ast_walk_context_extensions(), ast_walk_contexts(), and ast_walk_extension_priorities().
Referenced by ast_unregister_application().
{
   struct ast_context *context = NULL;
   struct ast_exten *eroot = NULL, *e = NULL;
   ast_rdlock_contexts();
   while ((context = ast_walk_contexts(context))) {
      while ((eroot = ast_walk_context_extensions(context, eroot))) {
         while ((e = ast_walk_extension_priorities(eroot, e))) {
            if (e->cached_app == app)
               e->cached_app = NULL;
         }
      }
   }
   ast_unlock_contexts();
   return;
}
static void update_scoreboard (struct scoreboard * board, int length, int spec, struct ast_exten * exten, char last, const char * callerid, int deleted, struct match_char * node) [static]
Definition at line 1478 of file pbx.c.
References ast_log(), ast_exten::exten, scoreboard::exten, scoreboard::last_char, LOG_NOTICE, scoreboard::node, scoreboard::total_length, and scoreboard::total_specificity.
Referenced by new_find_extension().
{
   /* if this extension is marked as deleted, then skip this -- if it never shows
      on the scoreboard, it will never be found, nor will halt the traversal. */
   if (deleted)
      return;
   board->total_specificity = spec;
   board->total_length = length;
   board->exten = exten;
   board->last_char = last;
   board->node = node;
#ifdef NEED_DEBUG_HERE
   ast_log(LOG_NOTICE,"Scoreboarding (LONGER) %s, len=%d, score=%d\n", exten->exten, length, spec);
#endif
}
static void wait_for_hangup (struct ast_channel * chan, void * data) [static]
Definition at line 8422 of file pbx.c.
References ast_frfree, ast_read(), ast_safe_sleep(), ast_strlen_zero(), ast_waitfor(), and f.
Referenced by pbx_builtin_busy(), and pbx_builtin_congestion().
{
   int res;
   struct ast_frame *f;
   double waitsec;
   int waittime;
   if (ast_strlen_zero(data) || (sscanf(data, "%30lg", &waitsec) != 1) || (waitsec < 0))
      waitsec = -1;
   if (waitsec > -1) {
      waittime = waitsec * 1000.0;
      ast_safe_sleep(chan, waittime);
   } else do {
      res = ast_waitfor(chan, -1);
      if (res < 0)
         return;
      f = ast_read(chan);
      if (f)
         ast_frfree(f);
   } while(f);
}
Variable Documentation
int autofallthrough = 1 [static]
Definition at line 1069 of file pbx.c.
Referenced by __ast_pbx_run(), and pbx_set_autofallthrough().
struct ast_app_option background_opts[128] = { [ 's' ] = { .flag = (1 << 0) }, [ 'n' ] = { .flag = (1 << 1) }, [ 'm' ] = { .flag = (1 << 2) }, [ 'p' ] = { .flag = (1 << 3) },} [static]
Definition at line 745 of file pbx.c.
Referenced by pbx_builtin_background().
struct pbx_builtin builtins[] [static]
Declaration of builtin applications.
Referenced by load_pbx().
ast_rwlock_t conlock = PTHREAD_RWLOCK_INITIALIZER [static]
Lock for the ast_context list
Definition at line 1122 of file pbx.c.
Referenced by ast_rdlock_contexts(), ast_unlock_contexts(), and ast_wrlock_contexts().
int conlock_wrlock_version = 0 [static]
Definition at line 9335 of file pbx.c.
Referenced by ast_wrlock_contexts(), and ast_wrlock_contexts_version().
struct ast_context* contexts [static]
Definition at line 1119 of file pbx.c.
Referenced by __ast_context_destroy(), ast_context_destroy(), ast_context_find_or_create(), ast_merge_contexts_and_delete(), and ast_walk_contexts().
struct ast_hashtab* contexts_table = NULL [static]
Definition at line 1120 of file pbx.c.
Referenced by ast_context_destroy(), ast_context_find(), ast_context_find_or_create(), ast_context_lockmacro(), ast_context_unlockmacro(), ast_merge_contexts_and_delete(), find_context(), find_context_locked(), and pbx_find_extension().
int countcalls [static]
Definition at line 1077 of file pbx.c.
Referenced by ast_active_calls(), decrease_call_count(), and increase_call_count().
char* days[] [static]
Definition at line 6910 of file pbx.c.
Referenced by ast_build_timing().
struct ast_event_sub* device_state_sub [static]
Subscription for device state change events.
Definition at line 1074 of file pbx.c.
Referenced by load_pbx().
struct ast_taskprocessor* device_state_tps [static]
Definition at line 758 of file pbx.c.
struct ast_custom_function exception_function [static]
Initial value:
 {
   .name = "EXCEPTION",
   .read = acf_exception_read,
}
Definition at line 3048 of file pbx.c.
Referenced by load_pbx().
struct ast_datastore_info exception_store_info [static]
Initial value:
 {
   .type = "EXCEPTION",
   .destroy = exception_store_free,
}
Definition at line 2990 of file pbx.c.
Referenced by acf_exception_read(), and pbx_builtin_raise_exception().
int extenpatternmatchnew = 0 [static]
Definition at line 1070 of file pbx.c.
Referenced by pbx_find_extension(), and pbx_set_extenpatternmatchnew().
struct cfextension_states extension_states[] [static]
Referenced by ast_extension_state2str().
struct ast_threadstorage extensionstate_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_extensionstate_buf , .custom_init = NULL , } [static]
Definition at line 761 of file pbx.c.
Referenced by ast_extension_state2().
struct varshead globals = AST_LIST_HEAD_NOLOCK_INIT_VALUE [static]
Definition at line 1067 of file pbx.c.
Referenced by handle_show_globals(), pbx_builtin_clear_globals(), pbx_builtin_getvar_helper(), pbx_builtin_pushvar_helper(), pbx_builtin_setvar_helper(), and pbx_retrieve_variable().
ast_rwlock_t globalslock = PTHREAD_RWLOCK_INITIALIZER [static]
Definition at line 1066 of file pbx.c.
Referenced by handle_show_globals(), pbx_builtin_clear_globals(), pbx_builtin_getvar_helper(), pbx_builtin_pushvar_helper(), pbx_builtin_setvar_helper(), and pbx_retrieve_variable().
char mandescr_show_dialplan[] [static]
Definition at line 6147 of file pbx.c.
Referenced by load_pbx().
ast_mutex_t maxcalllock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER) [static]
Definition at line 1076 of file pbx.c.
Referenced by decrease_call_count(), and increase_call_count().
char* months[] [static]
Definition at line 6922 of file pbx.c.
Referenced by ast_build_timing().
char* overrideswitch = NULL [static]
Definition at line 1071 of file pbx.c.
Referenced by handle_cli_dialplan_save(), pbx_find_extension(), and pbx_set_overrideswitch().
struct ast_cli_entry pbx_cli[] [static]
Definition at line 6363 of file pbx.c.
Referenced by load_pbx().
struct ast_app_option resetcdr_opts[128] = { [ 'w' ] = { .flag = (1 << 1) }, [ 'a' ] = { .flag = (1 << 2) }, [ 'v' ] = { .flag = (1 << 0) }, [ 'e' ] = { .flag = (1 << 10) },} [static]
Definition at line 8561 of file pbx.c.
Referenced by pbx_builtin_resetcdr().
int stateid = 1 [static]
Definition at line 1128 of file pbx.c.
Referenced by ast_extension_state_add().
struct ast_threadstorage switch_data = { .once = PTHREAD_ONCE_INIT , .key_init = __init_switch_data , .custom_init = NULL , } [static]
Definition at line 760 of file pbx.c.
Referenced by pbx_find_extension().
int totalcalls [static]
Definition at line 1078 of file pbx.c.
Referenced by ast_processed_calls(), increase_call_count(), and timing_read().
struct ast_app_option waitexten_opts[128] = { [ 'm' ] = { .flag = (1 << 0) , .arg_index = 0 + 1 }, [ 'd' ] = { .flag = (1 << 1) , .arg_index = 0 + 1 },} [static]
Definition at line 753 of file pbx.c.
Referenced by pbx_builtin_waitexten().