Wed May 5 15:23:09 2010
Asterisk developer's documentation
res_ais.c File Reference
Usage of the SAForum AIS (Application Interface Specification).
#include "asterisk.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include "ais/ais.h"
#include "asterisk/module.h"
#include "asterisk/options.h"
#include "asterisk/logger.h"
#include "asterisk/channel.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
Data Structures
struct ais_error
Functions
static void __reg_module (void)
static void __unreg_module (void)
const char * ais_err2str (SaAisErrorT error)
ASTERISK_FILE_VERSION (__FILE__,"$Revision: 179164 $")
static void * dispatch_thread_handler (void *data)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "SAForum AIS" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "aefddfaffd51bc118c14a748e96eb9a0" , .load = load_module, .unload = unload_module, }
static struct ais_error ais_errors []
SaVersionT ais_version = { 'B', 1, 1 }
static struct ast_module_info * ast_module_info = &__mod_info
struct {
pthread_t id
unsigned int stop:1
} dispatch_thread
Detailed Description
Usage of the SAForum AIS (Application Interface Specification).
Author:
Russell Bryant <russell@digium.com>
http://www.openais.org/
This file contains the common code between the uses of the different AIS services.
Note:
This module is still considered experimental, as it exposes the internal binary format of events between Asterisk servers over a network. However, this format is still subject to change between 1.6.X releases.
Definition in file res_ais.c.
Function Documentation
static void __reg_module (void) [static]
Definition at line 196 of file res_ais.c.
static void __unreg_module (void) [static]
Definition at line 196 of file res_ais.c.
const char* ais_err2str (SaAisErrorT error)
Definition at line 102 of file res_ais.c.
References ais_errors, ARRAY_LEN, and ais_error::desc.
Referenced by add_subscribe_event(), ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_ais_evt_load_module(), ast_ais_evt_unload_module(), ast_event_cb(), build_event_channel(), event_channel_destroy(), evt_event_deliver_cb(), and subscribe_event_destroy().
{
   int x;
   for (x = 0; x < ARRAY_LEN(ais_errors); x++) {
      if (ais_errors[x].error == error)
         return ais_errors[x].desc;
   }
   return "Unknown";
}
ASTERISK_FILE_VERSION (__FILE__ , "$Revision: 179164 $")
static void* dispatch_thread_handler (void * data) [static]
Definition at line 114 of file res_ais.c.
References ast_log(), ast_select(), clm_handle, dispatch_thread, errno, evt_handle, and LOG_ERROR.
Referenced by load_module().
{
   SaSelectionObjectT clm_fd, evt_fd, max_fd;
   int res;
   fd_set read_fds;
   SaAisErrorT ais_res;
   ais_res = saClmSelectionObjectGet(clm_handle, &clm_fd);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Failed to retrieve select fd for CLM service.  "
         "This module will not operate.\n");
      return NULL;
   }
   ais_res = saEvtSelectionObjectGet(evt_handle, &evt_fd);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Failed to retrieve select fd for EVT service.  "
         "This module will not operate.\n");
      return NULL;
   }
   max_fd = clm_fd > evt_fd ? clm_fd : evt_fd;
   while (!dispatch_thread.stop) {
      FD_ZERO(&read_fds);
      FD_SET(clm_fd,  &read_fds);
      FD_SET(evt_fd,  &read_fds);
      res = ast_select(max_fd + 1, &read_fds, NULL, NULL, NULL);
      if (res == -1 && errno != EINTR && errno != EAGAIN) {
         ast_log(LOG_ERROR, "Select error (%s) dispatch thread going away now, "
            "and the module will no longer operate.\n", strerror(errno));
         break;
      }
      if (FD_ISSET(clm_fd,  &read_fds))
         saClmDispatch(clm_handle,   SA_DISPATCH_ALL);
      if (FD_ISSET(evt_fd,  &read_fds))
         saEvtDispatch(evt_handle,   SA_DISPATCH_ALL);
   }
   return NULL;
}
static int load_module (void) [static]
Definition at line 158 of file res_ais.c.
References ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_ais_evt_load_module(), ast_ais_evt_unload_module(), ast_log(), AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, ast_pthread_create_background, dispatch_thread, dispatch_thread_handler(), and LOG_ERROR.
{
   if (ast_ais_clm_load_module())
      goto return_error;
   if (ast_ais_evt_load_module())
      goto evt_failed;
   if (ast_pthread_create_background(&dispatch_thread.id, NULL,
      dispatch_thread_handler, NULL)) {
      ast_log(LOG_ERROR, "Error starting AIS dispatch thread.\n");
      goto dispatch_failed;
   }
   return AST_MODULE_LOAD_SUCCESS;
dispatch_failed:
   ast_ais_evt_unload_module();
evt_failed:
   ast_ais_clm_unload_module();
return_error:
   return AST_MODULE_LOAD_DECLINE;
}
static int unload_module (void) [static]
Definition at line 182 of file res_ais.c.
References ast_ais_clm_unload_module(), ast_ais_evt_unload_module(), AST_PTHREADT_NULL, and dispatch_thread.
{
   ast_ais_clm_unload_module();
   ast_ais_evt_unload_module();
   if (dispatch_thread.id != AST_PTHREADT_NULL) {
      dispatch_thread.stop = 1;
      pthread_kill(dispatch_thread.id, SIGURG); /* poke! */
      pthread_join(dispatch_thread.id, NULL);
   }
   return 0;
}
Variable Documentation
struct ast_module_info __mod_info = { .name = AST_MODULE, .flags = AST_MODFLAG_DEFAULT , .description = "SAForum AIS" , .key = "This paragraph is copyright (c) 2006 by Digium, Inc. \In order for your module to load, it must return this \key via a function called \"key\". Any code which \includes this paragraph must be licensed under the GNU \General Public License version 2 or later (at your \option). In addition to Digium's general reservations \of rights, Digium expressly reserves the right to \allow other parties to license this paragraph under \different terms. Any use of Digium, Inc. trademarks or \logos (including \"Asterisk\" or \"Digium\") without \express written permission of Digium, Inc. is prohibited.\n" , .buildopt_sum = "aefddfaffd51bc118c14a748e96eb9a0" , .load = load_module, .unload = unload_module, } [static]
Definition at line 196 of file res_ais.c.
struct ais_error ais_errors[] [static]
Referenced by ais_err2str().
SaVersionT ais_version = { 'B', 1, 1 }
Definition at line 67 of file res_ais.c.
Referenced by ast_ais_clm_load_module(), and ast_ais_evt_load_module().
struct ast_module_info* ast_module_info = &__mod_info [static]
Definition at line 196 of file res_ais.c.
struct { ... } dispatch_thread [static]
Referenced by dispatch_thread_handler(), load_module(), and unload_module().
pthread_t id
Definition at line 61 of file res_ais.c.
unsigned int stop
Definition at line 62 of file res_ais.c.
Referenced by controlplayback_exec(), handle_controlstreamfile(), and queue_exec().