Wed May 5 15:23:41 2010
Asterisk developer's documentation
ast_module_info Struct Reference
#include <module.h>
Data Fields
int(* backup_globals)(void)
const char buildopt_sum [33]
const char * description
unsigned int flags
const char * key
enum ast_module_load_result(* load)(void)
unsigned char load_pri
const char * name
int(* reload)(void)
void(* restore_globals)(void)
struct ast_module * self
int(* unload)(void)
Detailed Description
Definition at line 196 of file module.h.
Field Documentation
int(* backup_globals)(void)
for embedded modules, backup global data
Referenced by load_resource().
const char buildopt_sum[33]
The value of AST_BUILDOPT_SUM when this module was compiled
Definition at line 223 of file module.h.
Referenced by inspect_module().
const char* description
user friendly description of the module.
Definition at line 211 of file module.h.
Referenced by ast_module_reload(), ast_update_module_list(), inspect_module(), and start_resource().
unsigned int flags
Definition at line 220 of file module.h.
const char* key
This holds the ASTERISK_GPL_KEY, signifiying that you agree to the terms of the Asterisk license as stated in the ASTERISK_GPL_KEY. Your module will not load if it does not return the EXACT key string.
Definition at line 219 of file module.h.
Referenced by inspect_module().
enum ast_module_load_result(* load)(void)
register stuff etc. Optional.
Referenced by start_resource().
unsigned char load_pri
This value represents the order in which a module's load() function is initialized. The lower this value, the higher the priority. The value is only checked if the AST_MODFLAG_LOAD_ORDER flag is set. If the AST_MODFLAG_LOAD_ORDER flag is not set, this value will never be read and the module will be given the lowest possible priority on load.
Definition at line 230 of file module.h.
Referenced by mod_load_cmp().
const char* name
name of the module for loader reference and CLI commands
Definition at line 210 of file module.h.
int(* reload)(void)
config etc. Optional.
Referenced by ast_module_helper(), and ast_module_reload().
void(* restore_globals)(void)
for embedded modules, restore global data
Referenced by ast_unload_resource().
struct ast_module* self [read]
The 'self' pointer for a module; it will be set by the loader before it calls the module's load_module() entrypoint, and used by various other macros that need to identify the module.
Definition at line 204 of file module.h.
int(* unload)(void)
unload. called with the module locked
Referenced by ast_module_shutdown(), and ast_unload_resource().
The documentation for this struct was generated from the following file:
module.h