Wed May 5 15:23:45 2010
Asterisk developer's documentation
verb Struct Reference
Data Fields
struct {
struct verb * next
} list
void(* verboser)(const char *string)
Detailed Description
Definition at line 816 of file logger.c.
Field Documentation
struct { ... } list
struct verb* next [read]
Definition at line 818 of file logger.c.
void(* verboser)(const char *string)
Referenced by ast_register_verbose(), ast_unregister_verbose(), and logger_print_verbose().
The documentation for this struct was generated from the following file:
logger.c