Wed May 5 15:23:41 2010
Asterisk developer's documentation
ast_generator Struct Reference
#include <channel.h>
Data Fields
void *(* alloc)(struct ast_channel *chan, void *params)
void(* digit)(struct ast_channel *chan, char digit)
int(* generate)(struct ast_channel *chan, void *data, int len, int samples)
void(* release)(struct ast_channel *chan, void *data)
Detailed Description
Todo:
Add an explanation of an Asterisk generator
Definition at line 174 of file channel.h.
Field Documentation
void*(* alloc)(struct ast_channel *chan, void *params)
Referenced by ast_activate_generator().
void(* digit)(struct ast_channel *chan, char digit)
This gets called when DTMF_END frames are read from the channel
Referenced by __ast_read().
int(* generate)(struct ast_channel *chan, void *data, int len, int samples)
This function gets called with the channel unlocked, but is called in the context of the channel thread so we know the channel is not going to disappear. This callback is responsible for locking the channel as necessary.
Referenced by __ast_read(), ast_read_generator_actions(), cb_events(), and generator_force().
void(* release)(struct ast_channel *chan, void *data)
Referenced by ast_activate_generator(), ast_deactivate_generator(), and ast_hangup().
The documentation for this struct was generated from the following file:
channel.h