Wed May 5 15:23:45 2010
Asterisk developer's documentation
thr_arg Struct Reference
Data Fields
void * data
char * name
void *(* start_routine)(void *)
Detailed Description
Definition at line 920 of file utils.c.
Field Documentation
void* data
Definition at line 922 of file utils.c.
Referenced by ast_pthread_create_stack(), and dummy_start().
char* name
Definition at line 923 of file utils.c.
Referenced by ast_pthread_create_stack(), and dummy_start().
void*(* start_routine)(void *)
Referenced by ast_pthread_create_detached_stack(), ast_pthread_create_stack(), and dummy_start().
The documentation for this struct was generated from the following file:
utils.c