Wed May 5 15:23:31 2010
Asterisk developer's documentation
taskprocessor.h File Reference
An API for managing task processing threads that can be shared across modules.
#include "asterisk.h"
#include "asterisk/lock.h"
#include "asterisk/linkedlists.h"
#include "asterisk/utils.h"
#include "asterisk/options.h"
Enumerations
enum ast_tps_options { TPS_REF_DEFAULT = 0, TPS_REF_IF_EXISTS = (1 << 0) }
ast_tps_options for specification of taskprocessor options
Functions
struct ast_taskprocessor * ast_taskprocessor_get (char *name, enum ast_tps_options create)
Get a reference to a taskprocessor with the specified name and create the taskprocessor if necessary.
const char * ast_taskprocessor_name (struct ast_taskprocessor *tps)
Return the name of the taskprocessor singleton.
int ast_taskprocessor_push (struct ast_taskprocessor *tps, int(*task_exe)(void *datap), void *datap)
Push a task into the specified taskprocessor queue and signal the taskprocessor thread.
void * ast_taskprocessor_unreference (struct ast_taskprocessor *tps)
Unreference the specified taskprocessor and its reference count will decrement.
Detailed Description
An API for managing task processing threads that can be shared across modules.
Author:
Dwayne M. Hubbard <dhubbard@digium.com>
Note:
A taskprocessor is a named singleton containing a processing thread and a task queue that serializes tasks pushed into it by [a] module(s) that reference the taskprocessor. A taskprocessor is created the first time its name is requested via the ast_taskprocessor_get() function and destroyed when the taskprocessor reference count reaches zero.
Modules that obtain a reference to a taskprocessor can queue tasks into the taskprocessor to be processed by the singleton processing thread when the task is popped off the front of the queue. A task is a wrapper around a task-handling function pointer and a data pointer. It is the responsibility of the task handling function to free memory allocated for the task data pointer. A task is pushed into a taskprocessor queue using the ast_taskprocessor_push(taskprocessor, taskhandler, taskdata) function and freed by the taskprocessor after the task handling function returns. A module releases its reference to a taskprocessor using the ast_taskprocessor_unreference() function which may result in the destruction of the taskprocessor if the taskprocessor's reference count reaches zero. Tasks waiting to be processed in the taskprocessor queue when the taskprocessor reference count reaches zero will be purged and released from the taskprocessor queue without being processed.
Definition in file taskprocessor.h.
Enumeration Type Documentation
enum ast_tps_options
ast_tps_options for specification of taskprocessor options
Specify whether a taskprocessor should be created via ast_taskprocessor_get() if the taskprocessor does not already exist. The default behavior is to create a taskprocessor if it does not already exist and provide its reference to the calling function. To only return a reference to a taskprocessor if and only if it exists, use the TPS_REF_IF_EXISTS option in ast_taskprocessor_get().
Enumerator:
TPS_REF_DEFAULT
return a reference to a taskprocessor, create one if it does not exist
TPS_REF_IF_EXISTS
return a reference to a taskprocessor ONLY if it already exists
Definition at line 58 of file taskprocessor.h.
                     {
   /*! \brief return a reference to a taskprocessor, create one if it does not exist */
   TPS_REF_DEFAULT = 0,
   /*! \brief return a reference to a taskprocessor ONLY if it already exists */
   TPS_REF_IF_EXISTS = (1 << 0),
};
Function Documentation
struct ast_taskprocessor* ast_taskprocessor_get (char * name, enum ast_tps_options create) [read]
Get a reference to a taskprocessor with the specified name and create the taskprocessor if necessary.
The default behavior of instantiating a taskprocessor if one does not already exist can be disabled by specifying the TPS_REF_IF_EXISTS ast_tps_options as the second argument to ast_taskprocessor_get().
Parameters:
name The name of the taskprocessor
create Use 0 by default or specify TPS_REF_IF_EXISTS to return NULL if the taskprocessor does not already exist return A pointer to a reference counted taskprocessor under normal conditions, or NULL if the TPS_REF_IF_EXISTS reference type is specified and the taskprocessor does not exist
Since:
1.6.1
Definition at line 407 of file taskprocessor.c.
References ao2_alloc, ao2_find, ao2_link, ao2_lock(), ao2_ref, ao2_unlock(), ast_calloc, ast_cond_init(), ast_log(), ast_mutex_init(), ast_pthread_create, AST_PTHREADT_NULL, ast_strdup, ast_strlen_zero(), LOG_ERROR, LOG_WARNING, ast_taskprocessor::name, OBJ_POINTER, ast_taskprocessor::poll_cond, ast_taskprocessor::poll_thread, ast_taskprocessor::poll_thread_run, ast_taskprocessor::stats, ast_taskprocessor::taskprocessor_lock, tps_processing_function(), TPS_REF_IF_EXISTS, tps_singletons, and tps_taskprocessor_destroy().
Referenced by ast_event_init(), cli_tps_ping(), load_module(), and load_pbx().
{
   struct ast_taskprocessor *p, tmp_tps = {
      .name = name,
   };
   if (ast_strlen_zero(name)) {
      ast_log(LOG_ERROR, "requesting a nameless taskprocessor!!!\n");
      return NULL;
   }
   ao2_lock(tps_singletons);
   p = ao2_find(tps_singletons, &tmp_tps, OBJ_POINTER);
   if (p) {
      ao2_unlock(tps_singletons);
      return p;
   }
   if (create & TPS_REF_IF_EXISTS) {
      /* calling function does not want a new taskprocessor to be created if it doesn't already exist */
      ao2_unlock(tps_singletons);
      return NULL;
   }
   /* create a new taskprocessor */
   if (!(p = ao2_alloc(sizeof(*p), tps_taskprocessor_destroy))) {
      ao2_unlock(tps_singletons);
      ast_log(LOG_WARNING, "failed to create taskprocessor '%s'\n", name);
      return NULL;
   }
   ast_cond_init(&p->poll_cond, NULL);
   ast_mutex_init(&p->taskprocessor_lock);
   if (!(p->stats = ast_calloc(1, sizeof(*p->stats)))) {
      ao2_unlock(tps_singletons);
      ast_log(LOG_WARNING, "failed to create taskprocessor stats for '%s'\n", name);
      ao2_ref(p, -1);
      return NULL;
   }
   if (!(p->name = ast_strdup(name))) {
      ao2_unlock(tps_singletons);
      ao2_ref(p, -1);
      return NULL;
   }
   p->poll_thread_run = 1;
   p->poll_thread = AST_PTHREADT_NULL;
   if (ast_pthread_create(&p->poll_thread, NULL, tps_processing_function, p) < 0) {
      ao2_unlock(tps_singletons);
      ast_log(LOG_ERROR, "Taskprocessor '%s' failed to create the processing thread.\n", p->name);
      ao2_ref(p, -1);
      return NULL;
   }
   if (!(ao2_link(tps_singletons, p))) {
      ao2_unlock(tps_singletons);
      ast_log(LOG_ERROR, "Failed to add taskprocessor '%s' to container\n", p->name);
      ao2_ref(p, -1);
      return NULL;
   }
   ao2_unlock(tps_singletons);
   return p;
}
const char* ast_taskprocessor_name (struct ast_taskprocessor * tps)
Return the name of the taskprocessor singleton.
Since:
1.6.1
Definition at line 395 of file taskprocessor.c.
References ast_log(), LOG_ERROR, and ast_taskprocessor::name.
{
   if (!tps) {
      ast_log(LOG_ERROR, "no taskprocessor specified!\n");
      return NULL;
   }
   return tps->name;
}
int ast_taskprocessor_push (struct ast_taskprocessor * tps, int(*)(void *datap) task_exe, void * datap)
Push a task into the specified taskprocessor queue and signal the taskprocessor thread.
Parameters:
tps The taskprocessor structure
task_exe The task handling function to push into the taskprocessor queue
datap The data to be used by the task handling function
Returns:
zero on success, -1 on failure
Since:
1.6.1
Definition at line 482 of file taskprocessor.c.
References ast_cond_signal(), AST_LIST_INSERT_TAIL, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), LOG_ERROR, ast_taskprocessor::name, ast_taskprocessor::poll_cond, ast_taskprocessor::taskprocessor_lock, ast_taskprocessor::tps_queue, ast_taskprocessor::tps_queue_size, and tps_task_alloc().
Referenced by ast_event_queue(), cli_tps_ping(), device_state_cb(), mwi_sub_event_cb(), and mwi_unsub_event_cb().
{
   struct tps_task *t;
   if (!tps || !task_exe) {
      ast_log(LOG_ERROR, "%s is missing!!\n", (tps) ? "task callback" : "taskprocessor");
      return -1;
   }
   if (!(t = tps_task_alloc(task_exe, datap))) {
      ast_log(LOG_ERROR, "failed to allocate task!  Can't push to '%s'\n", tps->name);
      return -1;
   }
   ast_mutex_lock(&tps->taskprocessor_lock);
   AST_LIST_INSERT_TAIL(&tps->tps_queue, t, list);
   tps->tps_queue_size++;
   ast_cond_signal(&tps->poll_cond);
   ast_mutex_unlock(&tps->taskprocessor_lock);
   return 0;
}
void* ast_taskprocessor_unreference (struct ast_taskprocessor * tps)
Unreference the specified taskprocessor and its reference count will decrement.
Taskprocessors use astobj2 and will unlink from the taskprocessor singleton container and destroy themself when the taskprocessor reference count reaches zero.
Parameters:
tps taskprocessor to unreference
Returns:
NULL
Since:
1.6.1
Definition at line 468 of file taskprocessor.c.
References ao2_link, ao2_lock(), ao2_ref, ao2_unlink, ao2_unlock(), and tps_singletons.
Referenced by unload_module().
{
   if (tps) {
      ao2_lock(tps_singletons);
      ao2_unlink(tps_singletons, tps);
      if (ao2_ref(tps, -1) > 1) {
         ao2_link(tps_singletons, tps);
      }
      ao2_unlock(tps_singletons);
   }
   return NULL;
}