Wed May 5 15:18:52 2010
Asterisk developer's documentation
ais.h File Reference
Usage of the SAForum AIS (Application Interface Specification).
#include <saAis.h>
#include <saClm.h>
#include <saEvt.h>
Functions
const char * ais_err2str (SaAisErrorT error)
int ast_ais_clm_load_module (void)
int ast_ais_clm_unload_module (void)
int ast_ais_evt_load_module (void)
int ast_ais_evt_unload_module (void)
Variables
SaVersionT ais_version
SaClmHandleT clm_handle
SaEvtHandleT evt_handle
Detailed Description
Usage of the SAForum AIS (Application Interface Specification).
Author:
Russell Bryant <russell@digium.com>
http://www.openais.org/
Definition in file ais.h.
Function Documentation
const char* ais_err2str (SaAisErrorT error)
Definition at line 102 of file res_ais.c.
References ais_errors, ARRAY_LEN, and ais_error::desc.
Referenced by add_subscribe_event(), ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_ais_evt_load_module(), ast_ais_evt_unload_module(), ast_event_cb(), build_event_channel(), event_channel_destroy(), evt_event_deliver_cb(), and subscribe_event_destroy().
{
   int x;
   for (x = 0; x < ARRAY_LEN(ais_errors); x++) {
      if (ais_errors[x].error == error)
         return ais_errors[x].desc;
   }
   return "Unknown";
}
int ast_ais_clm_load_module (void)
Definition at line 135 of file clm.c.
References ais_err2str(), ais_version, ARRAY_LEN, ast_cli_register_multiple(), ast_log(), clm_callbacks, clm_handle, and LOG_ERROR.
Referenced by load_module().
{
   SaAisErrorT ais_res;
   ais_res = saClmInitialize(&clm_handle, &clm_callbacks, &ais_version);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Could not initialize cluster membership service: %s\n",
         ais_err2str(ais_res));
      return -1;
   }
   ast_cli_register_multiple(ais_cli, ARRAY_LEN(ais_cli));
   return 0;
}
int ast_ais_clm_unload_module (void)
Definition at line 151 of file clm.c.
References ais_err2str(), ARRAY_LEN, ast_cli_unregister_multiple(), ast_log(), clm_handle, and LOG_ERROR.
Referenced by load_module(), and unload_module().
{
   SaAisErrorT ais_res;
   ast_cli_unregister_multiple(ais_cli, ARRAY_LEN(ais_cli));
   ais_res = saClmFinalize(clm_handle);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Problem stopping cluster membership service: %s\n",
         ais_err2str(ais_res));
      return -1;
   }
   return 0;
}
int ast_ais_evt_load_module (void)
Definition at line 540 of file evt.c.
References ais_err2str(), ais_version, ARRAY_LEN, ast_cli_register_multiple(), ast_log(), evt_callbacks, evt_handle, load_config(), and LOG_ERROR.
Referenced by load_module().
{
   SaAisErrorT ais_res;
   ais_res = saEvtInitialize(&evt_handle, &evt_callbacks, &ais_version);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Could not initialize eventing service: %s\n",
         ais_err2str(ais_res));
      return -1;
   }
   load_config();
   ast_cli_register_multiple(ais_cli, ARRAY_LEN(ais_cli));
   return 0;
}
int ast_ais_evt_unload_module (void)
Definition at line 558 of file evt.c.
References ais_err2str(), ast_log(), destroy_event_channels(), evt_handle, and LOG_ERROR.
Referenced by load_module(), and unload_module().
{
   SaAisErrorT ais_res;
   destroy_event_channels();
   ais_res = saEvtFinalize(evt_handle);
   if (ais_res != SA_AIS_OK) {
      ast_log(LOG_ERROR, "Problem stopping eventing service: %s\n",
         ais_err2str(ais_res));
      return -1;
   }
   return 0;
}
Variable Documentation
SaVersionT ais_version
Definition at line 67 of file res_ais.c.
Referenced by ast_ais_clm_load_module(), and ast_ais_evt_load_module().
SaClmHandleT clm_handle
Definition at line 48 of file clm.c.
Referenced by ais_clm_show_members(), ast_ais_clm_load_module(), ast_ais_clm_unload_module(), ast_event_cb(), and dispatch_thread_handler().
SaEvtHandleT evt_handle
Definition at line 57 of file evt.c.
Referenced by ast_ais_evt_load_module(), ast_ais_evt_unload_module(), build_event_channel(), and dispatch_thread_handler().