Wed May 5 15:18:55 2010
Asterisk developer's documentation
app_echo.c File Reference
Echo application -- play back what you hear to evaluate latency.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/module.h"
#include "asterisk/channel.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Simple Echo Application")
static int echo_exec (struct ast_channel *chan, void *data)
static int load_module (void)
static int unload_module (void)
Variables
static char * app = "Echo"
Detailed Description
Echo application -- play back what you hear to evaluate latency.
Author:
Mark Spencer <markster@digium.com>
Definition in file app_echo.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Simple Echo Application")
static int echo_exec (struct ast_channel * chan, void * data) [static]
Definition at line 51 of file app_echo.c.
References ast_best_codec(), AST_FRAME_DTMF, ast_frfree, ast_read(), ast_set_read_format(), ast_set_write_format(), ast_waitfor(), ast_write(), ast_frame::delivery, f, format, ast_frame::frametype, ast_channel::nativeformats, and ast_frame::subclass.
Referenced by load_module().
{
   int res = -1;
   int format;
   format = ast_best_codec(chan->nativeformats);
   ast_set_write_format(chan, format);
   ast_set_read_format(chan, format);
   while (ast_waitfor(chan, -1) > -1) {
      struct ast_frame *f = ast_read(chan);
      if (!f) {
         break;
      }
      f->delivery.tv_sec = 0;
      f->delivery.tv_usec = 0;
      if (ast_write(chan, f)) {
         ast_frfree(f);
         goto end;
      }
      if ((f->frametype == AST_FRAME_DTMF) && (f->subclass == '#')) {
         res = 0;
         ast_frfree(f);
         goto end;
      }
      ast_frfree(f);
   }
end:
   return res;
}
static int load_module (void) [static]
Definition at line 87 of file app_echo.c.
References ast_register_application_xml, and echo_exec().
{
   return ast_register_application_xml(app, echo_exec);
}
static int unload_module (void) [static]
Definition at line 82 of file app_echo.c.
References ast_unregister_application().
{
   return ast_unregister_application(app);
}
Variable Documentation
char* app = "Echo" [static]
Definition at line 49 of file app_echo.c.