Wed May 5 15:18:56 2010
Asterisk developer's documentation
app_ivrdemo.c File Reference
IVR Demo application.
#include "asterisk.h"
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/app.h"
Functions
AST_IVR_DECLARE_MENU (ivr_demo,"IVR Demo Main Menu", 0,{{"s", AST_ACTION_BACKGROUND,"demo-congrats"},{"g", AST_ACTION_BACKGROUND,"demo-instruct"},{"g", AST_ACTION_WAITOPTION},{"1", AST_ACTION_PLAYBACK,"digits/1"},{"1", AST_ACTION_RESTART},{"2", AST_ACTION_MENU,&ivr_submenu},{"2", AST_ACTION_RESTART},{"i", AST_ACTION_PLAYBACK,"invalid"},{"i", AST_ACTION_REPEAT,(void *)(unsigned long) 2},{"#", AST_ACTION_EXIT},{NULL},})
AST_IVR_DECLARE_MENU (ivr_submenu,"IVR Demo Sub Menu", 0,{{"s", AST_ACTION_BACKGROUND,"demo-abouttotry"},{"s", AST_ACTION_WAITOPTION},{"1", AST_ACTION_PLAYBACK,"digits/1"},{"1", AST_ACTION_PLAYBACK,"digits/1"},{"1", AST_ACTION_RESTART},{"2", AST_ACTION_PLAYLIST,"digits/2;digits/3"},{"3", AST_ACTION_CALLBACK, ivr_demo_func},{"4", AST_ACTION_TRANSFER,"demo|s|1"},{"*", AST_ACTION_REPEAT},{"#", AST_ACTION_UPONE},{NULL}})
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"IVR Demo Application")
static int ivr_demo_func (struct ast_channel *chan, void *data)
static int load_module (void)
static int skel_exec (struct ast_channel *chan, void *data)
static int unload_module (void)
Variables
static char * app = "IVRDemo"
Detailed Description
IVR Demo application.
Author:
Mark Spencer <markster@digium.com>
Definition in file app_ivrdemo.c.
Function Documentation
AST_IVR_DECLARE_MENU (ivr_demo , "IVR Demo Main Menu" , 0)
AST_IVR_DECLARE_MENU (ivr_submenu , "IVR Demo Sub Menu" , 0)
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "IVR Demo Application")
static int ivr_demo_func (struct ast_channel * chan, void * data) [static]
Definition at line 60 of file app_ivrdemo.c.
References ast_verbose.
{
   ast_verbose("IVR Demo, data is %s!\n", (char *)data);
   return 0;
}
static int load_module (void) [static]
Definition at line 121 of file app_ivrdemo.c.
References ast_register_application_xml, and skel_exec().
{
   return ast_register_application_xml(app, skel_exec);
}
static int skel_exec (struct ast_channel * chan, void * data) [static]
Definition at line 97 of file app_ivrdemo.c.
References ast_channel::_state, ast_answer(), ast_ivr_menu_run(), ast_log(), AST_STATE_UP, ast_strlen_zero(), and LOG_WARNING.
Referenced by load_module().
{
   int res=0;
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "skel requires an argument (filename)\n");
      return -1;
   }
   /* Do our thing here */
   if (chan->_state != AST_STATE_UP)
      res = ast_answer(chan);
   if (!res)
      res = ast_ivr_menu_run(chan, &ivr_demo, data);
   return res;
}
static int unload_module (void) [static]
Definition at line 116 of file app_ivrdemo.c.
References ast_unregister_application().
{
   return ast_unregister_application(app);
}
Variable Documentation
char* app = "IVRDemo" [static]
Definition at line 58 of file app_ivrdemo.c.