Wed May 5 15:19:40 2010
Asterisk developer's documentation
bridge_simple.c File Reference
Simple two channel bridging module.
#include "asterisk.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "asterisk/module.h"
#include "asterisk/channel.h"
#include "asterisk/bridging.h"
#include "asterisk/bridging_technology.h"
#include "asterisk/frame.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Simple two channel bridging module")
static int load_module (void)
static int simple_bridge_join (struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
static enum ast_bridge_write_result simple_bridge_write (struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel, struct ast_frame *frame)
static int unload_module (void)
Variables
static struct ast_bridge_technology simple_bridge
Detailed Description
Simple two channel bridging module.
Author:
Joshua Colp <jcolp@digium.com>
Definition in file bridge_simple.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Simple two channel bridging module")
static int load_module (void) [static]
Definition at line 98 of file bridge_simple.c.
References ast_bridge_technology_register.
{
   return ast_bridge_technology_register(&simple_bridge);
}
static int simple_bridge_join (struct ast_bridge * bridge, struct ast_bridge_channel * bridge_channel) [static]
Definition at line 44 of file bridge_simple.c.
References ast_channel_make_compatible(), AST_LIST_FIRST, AST_LIST_LAST, ast_channel::nativeformats, ast_channel::readformat, and ast_channel::writeformat.
{
   struct ast_channel *c0 = AST_LIST_FIRST(&bridge->channels)->chan, *c1 = AST_LIST_LAST(&bridge->channels)->chan;
   /* If this is the first channel we can't make it compatible... unless we make it compatible with itself O.o */
   if (AST_LIST_FIRST(&bridge->channels) == AST_LIST_LAST(&bridge->channels)) {
      return 0;
   }
   /* See if we need to make these compatible */
   if (((c0->writeformat == c1->readformat) && (c0->readformat == c1->writeformat) && (c0->nativeformats == c1->nativeformats))) {
      return 0;
   }
   /* BOOM! We do. */
   return ast_channel_make_compatible(c0, c1);
}
static enum ast_bridge_write_result simple_bridge_write (struct ast_bridge * bridge, struct ast_bridge_channel * bridge_channel, struct ast_frame * frame) [static]
Definition at line 62 of file bridge_simple.c.
References AST_BRIDGE_CHANNEL_STATE_WAIT, AST_BRIDGE_WRITE_FAILED, AST_BRIDGE_WRITE_SUCCESS, AST_LIST_FIRST, AST_LIST_LAST, ast_write(), ast_bridge_channel::chan, and ast_bridge_channel::state.
{
   struct ast_bridge_channel *other = NULL;
   /* If this is the only channel in this bridge then immediately exit */
   if (AST_LIST_FIRST(&bridge->channels) == AST_LIST_LAST(&bridge->channels)) {
      return AST_BRIDGE_WRITE_FAILED;
   }
   /* Find the channel we actually want to write to */
   if (!(other = (AST_LIST_FIRST(&bridge->channels) == bridge_channel ? AST_LIST_LAST(&bridge->channels) : AST_LIST_FIRST(&bridge->channels)))) {
      return AST_BRIDGE_WRITE_FAILED;
   }
   /* Write the frame out if they are in the waiting state... don't worry about freeing it, the bridging core will take care of it */
   if (other->state == AST_BRIDGE_CHANNEL_STATE_WAIT) {
      ast_write(other->chan, frame);
   }
   return AST_BRIDGE_WRITE_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 93 of file bridge_simple.c.
References ast_bridge_technology_unregister().
{
   return ast_bridge_technology_unregister(&simple_bridge);
}
Variable Documentation
struct ast_bridge_technology simple_bridge [static]
Definition at line 84 of file bridge_simple.c.