Wed May 5 15:19:45 2010
Asterisk developer's documentation
chan_dahdi.c File Reference
DAHDI for Pseudo TDM.
#include "asterisk.h"
#include <sys/signal.h>
#include <sys/ioctl.h>
#include <math.h>
#include <ctype.h>
#include <dahdi/user.h>
#include <dahdi/tonezone.h>
#include "asterisk/lock.h"
#include "asterisk/channel.h"
#include "asterisk/config.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/file.h"
#include "asterisk/ulaw.h"
#include "asterisk/alaw.h"
#include "asterisk/callerid.h"
#include "asterisk/adsi.h"
#include "asterisk/cli.h"
#include "asterisk/cdr.h"
#include "asterisk/features.h"
#include "asterisk/musiconhold.h"
#include "asterisk/say.h"
#include "asterisk/tdd.h"
#include "asterisk/app.h"
#include "asterisk/dsp.h"
#include "asterisk/astdb.h"
#include "asterisk/manager.h"
#include "asterisk/causes.h"
#include "asterisk/term.h"
#include "asterisk/utils.h"
#include "asterisk/transcap.h"
#include "asterisk/stringfields.h"
#include "asterisk/abstract_jb.h"
#include "asterisk/smdi.h"
#include "asterisk/astobj.h"
#include "asterisk/event.h"
#include "asterisk/devicestate.h"
#include "asterisk/paths.h"
Data Structures
struct dahdi_chan_conf
Channel configuration from chan_dahdi.conf . This struct is used for parsing the [channels] section of chan_dahdi.conf. Generally there is a field here for every possible configuration item.
struct dahdi_distRings
struct dahdi_pvt
struct dahdi_subchannel
struct distRingData
struct mwi_thread_data
struct mwisend_info
struct ringContextData
Defines
#define ASCII_BYTES_PER_CHAR 80
#define AST_LAW(p) (((p)->law == DAHDI_LAW_ALAW) ? AST_FORMAT_ALAW : AST_FORMAT_ULAW)
#define CALLPROGRESS_FAX (CALLPROGRESS_FAX_INCOMING | CALLPROGRESS_FAX_OUTGOING)
#define CALLPROGRESS_FAX_INCOMING 4
#define CALLPROGRESS_FAX_OUTGOING 2
#define CALLPROGRESS_PROGRESS 1
#define CALLWAITING_REPEAT_SAMPLES ((10000 * 8) / READ_SIZE)
#define CALLWAITING_SILENT_SAMPLES ((300 * 8) / READ_SIZE)
#define CANBUSYDETECT(p) (ISTRUNK(p) || (p->sig & (SIG_EM | SIG_EM_E1 | SIG_SF)) /* || (p->sig & __DAHDI_SIG_FXO) */)
#define CANPROGRESSDETECT(p) (ISTRUNK(p) || (p->sig & (SIG_EM | SIG_EM_E1 | SIG_SF)) /* || (p->sig & __DAHDI_SIG_FXO) */)
#define CHAN_PSEUDO -2
#define CHANNEL_PSEUDO -12
#define CIDCW_EXPIRE_SAMPLES ((500 * 8) / READ_SIZE)
#define CONF_USER_REAL (1 << 0)
#define CONF_USER_THIRDCALL (1 << 1)
#define DAHDI_CHAN_MAPPING_LOGICAL 1
#define DAHDI_CHAN_MAPPING_PHYSICAL 0
#define DAHDI_OVERLAPDIAL_BOTH (DAHDI_OVERLAPDIAL_INCOMING|DAHDI_OVERLAPDIAL_OUTGOING)
#define DAHDI_OVERLAPDIAL_INCOMING 2
#define DAHDI_OVERLAPDIAL_NONE 0
#define DAHDI_OVERLAPDIAL_OUTGOING 1
#define DCHAN_AVAILABLE (DCHAN_PROVISIONED | DCHAN_NOTINALARM | DCHAN_UP)
#define DCHAN_NOTINALARM (1 << 1)
#define DCHAN_PROVISIONED (1 << 0)
#define DCHAN_UP (1 << 2)
#define DEFAULT_CIDRINGS 1
Typically, how many rings before we should send Caller*ID.
#define DEFAULT_RINGT ((8000 * 8) / READ_SIZE)
#define END_SILENCE_LEN 400
#define FORMAT "%-40.40s %-7.7s %-6d %-6d %-6d %-3.3s %-4.4s %-8.8s %s\n"
#define FORMAT "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
#define FORMAT2 "%-40.40s %-7.7s %-6.6s %-6.6s %-6.6s %-3.3s %-4.4s %-8.8s %s\n"
#define FORMAT2 "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
#define GET_CHANNEL(p) ((p)->channel)
#define HANGUP 1
#define HEADER_LEN ((HEADER_MS + TRAILER_MS) * 8)
#define HEADER_MS 50
#define ISTRUNK(p)
#define MASK_AVAIL (1 << 0)
#define MASK_INUSE (1 << 1)
#define MAX_CHANLIST_LEN 80
#define MAX_CHANNELS 672
#define MAX_SLAVES 4
#define MIN_MS_SINCE_FLASH ((2000))
#define NEED_MFDETECT(p) (((p)->sig == SIG_FEATDMF) || ((p)->sig == SIG_FEATDMF_TA) || ((p)->sig == SIG_E911) || ((p)->sig == SIG_FGC_CAMA) || ((p)->sig == SIG_FGC_CAMAMF) || ((p)->sig == SIG_FEATB))
Signaling types that need to use MF detection should be placed in this macro.
#define NUM_CADENCE_MAX 25
#define NUM_DCHANS 4
#define NUM_SPANS 32
#define POLARITY_IDLE 0
#define POLARITY_REV 1
#define PROC_DAHDI_OPT_NOCHAN (1 << 0)
#define PROC_DAHDI_OPT_NOWARN (1 << 1)
#define READ_SIZE 160
#define sig2str dahdi_sig2str
#define SIG_BRI (0x2000000 | DAHDI_SIG_CLEAR)
#define SIG_BRI_PTMP (0X4000000 | DAHDI_SIG_CLEAR)
#define SIG_E911 (0x1000000 | DAHDI_SIG_EM)
#define SIG_EM DAHDI_SIG_EM
#define SIG_EM_E1 DAHDI_SIG_EM_E1
#define SIG_EMWINK (0x0100000 | DAHDI_SIG_EM)
#define SIG_FEATB (0x0800000 | DAHDI_SIG_EM)
#define SIG_FEATD (0x0200000 | DAHDI_SIG_EM)
#define SIG_FEATDMF (0x0400000 | DAHDI_SIG_EM)
#define SIG_FEATDMF_TA (0x2000000 | DAHDI_SIG_EM)
#define SIG_FGC_CAMA (0x4000000 | DAHDI_SIG_EM)
#define SIG_FGC_CAMAMF (0x8000000 | DAHDI_SIG_EM)
#define SIG_FXOGS DAHDI_SIG_FXOGS
#define SIG_FXOKS DAHDI_SIG_FXOKS
#define SIG_FXOLS DAHDI_SIG_FXOLS
#define SIG_FXSGS DAHDI_SIG_FXSGS
#define SIG_FXSKS DAHDI_SIG_FXSKS
#define SIG_FXSLS DAHDI_SIG_FXSLS
#define SIG_GR303FXOKS (0x0100000 | DAHDI_SIG_FXOKS)
#define SIG_GR303FXSKS (0x0100000 | DAHDI_SIG_FXSKS)
#define SIG_MFCR2 DAHDI_SIG_CAS
#define SIG_PRI DAHDI_SIG_CLEAR
#define SIG_SF DAHDI_SIG_SF
#define SIG_SF_FEATB (0x0800000 | DAHDI_SIG_SF)
#define SIG_SF_FEATD (0x0200000 | DAHDI_SIG_SF)
#define SIG_SF_FEATDMF (0x0400000 | DAHDI_SIG_SF)
#define SIG_SFWINK (0x0100000 | DAHDI_SIG_SF)
#define SIG_SS7 (0x1000000 | DAHDI_SIG_CLEAR)
#define SMDI_MD_WAIT_TIMEOUT 1500
#define SUB_CALLWAIT 1
#define SUB_REAL 0
#define SUB_THREEWAY 2
#define TRAILER_MS 5
#define TRANSFER 0
Enumerations
enum mwisend_states {
MWI_SEND_NULL = 0, MWI_SEND_SA, MWI_SEND_SA_WAIT, MWI_SEND_PAUSE,
MWI_SEND_SPILL, MWI_SEND_CLEANUP, MWI_SEND_DONE
}
Functions
static struct ast_frame * __dahdi_exception (struct ast_channel *ast)
static int __unload_module (void)
static int action_dahdidialoffhook (struct mansession *s, const struct message *m)
static int action_dahdidndoff (struct mansession *s, const struct message *m)
static int action_dahdidndon (struct mansession *s, const struct message *m)
static int action_dahdirestart (struct mansession *s, const struct message *m)
static int action_dahdishowchannels (struct mansession *s, const struct message *m)
static int action_transfer (struct mansession *s, const struct message *m)
static int action_transferhangup (struct mansession *s, const struct message *m)
static char * alarm2str (int alm)
static int alloc_sub (struct dahdi_pvt *p, int x)
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_DEFAULT, tdesc,.load=load_module,.unload=unload_module,.reload=reload,)
AST_MUTEX_DEFINE_STATIC (restart_lock)
AST_MUTEX_DEFINE_STATIC (ss_thread_lock)
AST_MUTEX_DEFINE_STATIC (monlock)
Protect the monitoring thread, so only one process can kill or start it, and not when it's doing something critical.
AST_MUTEX_DEFINE_STATIC (iflock)
Protect the interface list (of dahdi_pvt's).
static int attempt_transfer (struct dahdi_pvt *p)
static int available (struct dahdi_pvt *p, int channelmatch, ast_group_t groupmatch, int *busy, int *channelmatched, int *groupmatched)
static int build_channels (struct dahdi_chan_conf *conf, int iscrv, const char *value, int reload, int lineno, int *found_pseudo)
static int bump_gains (struct dahdi_pvt *p)
static int calc_energy (const unsigned char *buf, int len, int law)
static int check_for_conference (struct dahdi_pvt *p)
static int conf_add (struct dahdi_pvt *p, struct dahdi_subchannel *c, int idx, int slavechannel)
static int conf_del (struct dahdi_pvt *p, struct dahdi_subchannel *c, int idx)
static int dahdi_answer (struct ast_channel *ast)
static enum ast_bridge_result dahdi_bridge (struct ast_channel *c0, struct ast_channel *c1, int flags, struct ast_frame **fo, struct ast_channel **rc, int timeoutms)
static int dahdi_call (struct ast_channel *ast, char *rdest, int timeout)
static int dahdi_callwait (struct ast_channel *ast)
static struct dahdi_chan_conf dahdi_chan_conf_default (void)
static void dahdi_close (int fd)
static void dahdi_close_sub (struct dahdi_pvt *chan_pvt, int sub_num)
static int dahdi_confmute (struct dahdi_pvt *p, int muted)
static char * dahdi_destroy_channel (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int dahdi_destroy_channel_bynum (int channel)
static int dahdi_digit_begin (struct ast_channel *ast, char digit)
static int dahdi_digit_end (struct ast_channel *ast, char digit, unsigned int duration)
static void dahdi_disable_ec (struct dahdi_pvt *p)
static void dahdi_dnd (struct dahdi_pvt *dahdichan, int on)
enable or disable the chan_dahdi Do-Not-Disturb mode for a DAHDI channel
static void dahdi_enable_ec (struct dahdi_pvt *p)
static struct ast_frame * dahdi_exception (struct ast_channel *ast)
static int dahdi_fake_event (struct dahdi_pvt *p, int mode)
static int dahdi_fixup (struct ast_channel *oldchan, struct ast_channel *newchan)
static int dahdi_func_read (struct ast_channel *chan, const char *function, char *data, char *buf, size_t len)
static int dahdi_get_event (int fd)
Avoid the silly dahdi_getevent which ignores a bunch of events.
static int dahdi_get_index (struct ast_channel *ast, struct dahdi_pvt *p, int nullok)
static void dahdi_handle_dtmfup (struct ast_channel *ast, int idx, struct ast_frame **dest)
static struct ast_frame * dahdi_handle_event (struct ast_channel *ast)
static int dahdi_hangup (struct ast_channel *ast)
static int dahdi_indicate (struct ast_channel *chan, int condition, const void *data, size_t datalen)
static void dahdi_link (struct dahdi_pvt *slave, struct dahdi_pvt *master)
static struct ast_channel * dahdi_new (struct dahdi_pvt *, int, int, int, int, int)
static int dahdi_open (char *fn)
static void dahdi_queue_frame (struct dahdi_pvt *p, struct ast_frame *f, void *data)
static struct ast_frame * dahdi_read (struct ast_channel *ast)
static struct ast_channel * dahdi_request (const char *type, int format, void *data, int *cause)
static int dahdi_restart (void)
static char * dahdi_restart_cmd (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int dahdi_ring_phone (struct dahdi_pvt *p)
static int dahdi_sendtext (struct ast_channel *c, const char *text)
static char * dahdi_set_dnd (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int dahdi_set_hook (int fd, int hs)
static char * dahdi_set_hwgain (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * dahdi_set_swgain (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int dahdi_setlinear (int dfd, int linear)
static int dahdi_setoption (struct ast_channel *chan, int option, void *data, int datalen)
static char * dahdi_show_channel (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * dahdi_show_channels (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * dahdi_show_status (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * dahdi_show_version (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * dahdi_sig2str (int sig)
static void dahdi_softhangup_all (void)
static void dahdi_train_ec (struct dahdi_pvt *p)
static void dahdi_unlink (struct dahdi_pvt *slave, struct dahdi_pvt *master, int needlock)
static int dahdi_wait_event (int fd)
Avoid the silly dahdi_waitevent which ignores a bunch of events.
static int dahdi_wink (struct dahdi_pvt *p, int idx)
static int dahdi_write (struct ast_channel *ast, struct ast_frame *frame)
static void destroy_all_channels (void)
static int destroy_channel (struct dahdi_pvt *prev, struct dahdi_pvt *cur, int now)
static void destroy_dahdi_pvt (struct dahdi_pvt **pvt)
static int digit_to_dtmfindex (char digit)
static void disable_dtmf_detect (struct dahdi_pvt *p)
static void * do_monitor (void *data)
static struct dahdi_pvt * duplicate_pseudo (struct dahdi_pvt *src)
static void enable_dtmf_detect (struct dahdi_pvt *p)
static char * event2str (int event)
static void fill_rxgain (struct dahdi_gains *g, float gain, int law)
static void fill_txgain (struct dahdi_gains *g, float gain, int law)
static struct dahdi_pvt * find_channel (int channel)
static int get_alarms (struct dahdi_pvt *p)
static void handle_alarms (struct dahdi_pvt *p, int alms)
static char * handle_dahdi_show_cadences (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static struct dahdi_pvt * handle_init_event (struct dahdi_pvt *i, int event)
static int has_voicemail (struct dahdi_pvt *p)
static int isourconf (struct dahdi_pvt *p, struct dahdi_subchannel *c)
static int isslavenative (struct dahdi_pvt *p, struct dahdi_pvt **out)
static int load_module (void)
static struct dahdi_pvt * mkintf (int channel, const struct dahdi_chan_conf *conf, struct dahdi_pri *pri, int reloading)
static void mwi_event_cb (const struct ast_event *event, void *userdata)
static int mwi_send_init (struct dahdi_pvt *pvt)
static int mwi_send_process_buffer (struct dahdi_pvt *pvt, int num_read)
static int mwi_send_process_event (struct dahdi_pvt *pvt, int event)
static void * mwi_thread (void *data)
static int my_dahdi_write (struct dahdi_pvt *p, unsigned char *buf, int len, int idx, int linear)
static int my_getsigstr (struct ast_channel *chan, char *str, const char *term, int ms)
static void notify_message (char *mailbox_full, int thereornot)
Send MWI state change.
static int process_dahdi (struct dahdi_chan_conf *confp, const char *cat, struct ast_variable *v, int reload, int options)
static void process_echocancel (struct dahdi_chan_conf *confp, const char *data, unsigned int line)
static int reload (void)
static int reset_conf (struct dahdi_pvt *p)
static int restart_monitor (void)
static int restore_conference (struct dahdi_pvt *p)
static int restore_gains (struct dahdi_pvt *p)
static int save_conference (struct dahdi_pvt *p)
static int send_callerid (struct dahdi_pvt *p)
static int send_cwcidspill (struct dahdi_pvt *p)
static int set_actual_gain (int fd, int chan, float rxgain, float txgain, int law)
static int set_actual_rxgain (int fd, int chan, float gain, int law)
static int set_actual_txgain (int fd, int chan, float gain, int law)
static int setup_dahdi (int reload)
static int sigtype_to_signalling (int sigtype)
static void * ss_thread (void *data)
static void swap_subs (struct dahdi_pvt *p, int a, int b)
static int unalloc_sub (struct dahdi_pvt *p, int x)
static int unload_module (void)
static int update_conf (struct dahdi_pvt *p)
static void wakeup_sub (struct dahdi_pvt *p, int a, struct dahdi_pri *pri)
Variables
struct {
int alarm
char * name
} alarms []
static struct dahdi_ring_cadence AS_RP_cadence = {{250, 10000}}
static struct dahdi_ring_cadence cadences [NUM_CADENCE_MAX]
static int cidrings [NUM_CADENCE_MAX]
cidrings says in which pause to transmit the cid information, where the first pause is 1, the second pause is 2 and so on.
static const char config [] = "chan_dahdi.conf"
static struct ast_cli_entry dahdi_cli []
static struct ast_channel_tech dahdi_tech
static struct ast_jb_conf default_jbconf
static char defaultcic [64] = ""
static char defaultozz [64] = ""
static int distinctiveringaftercid = 0
static char * events []
static int firstdigittimeout = 16000
Wait up to 16 seconds for first digit (FXO logic).
static int gendigittimeout = 8000
How long to wait for following digits (FXO logic).
static struct ast_jb_conf global_jbconf
static int ifcount = 0
static struct dahdi_pvt * ifend
static struct dahdi_pvt * iflist
static const char * lbostr []
static int matchdigittimeout = 3000
How long to wait for an extra digit, if there is an ambiguous match.
static pthread_t monitor_thread = AST_PTHREADT_NULL
This is the thread for the monitor which checks for input on the channels which are not currently in use.
static int mwilevel = 512
static char mwimonitornotify [PATH_MAX] = ""
static int mwisend_rpas = 0
static int num_cadence = 4
static int num_restart_pending = 0
static int numbufs = 4
static char parkinglot [AST_MAX_EXTENSION] = ""
static char progzone [10] = ""
static int ringt_base = DEFAULT_RINGT
Configured ring timeout base.
struct dahdi_pvt * round_robin [32]
static ast_cond_t ss_thread_complete
static int ss_thread_count = 0
static char * subnames []
static const char tdesc [] = "DAHDI Telephony Driver"
static int usedistinctiveringdetection = 0
static int user_has_defined_cadences = 0
Detailed Description
DAHDI for Pseudo TDM.
Author:
Mark Spencer <markster@digium.com>
Connects to the DAHDI telephony library as well as libpri. Libpri is optional and needed only if you are going to use ISDN connections.
You need to install libraries before you attempt to compile and install the DAHDI channel.
See also
DAHDI configuration
Todo:
Deprecate the "musiconhold" configuration option post 1.4
Definition in file chan_dahdi.c.
Define Documentation
#define ASCII_BYTES_PER_CHAR 80
Referenced by dahdi_sendtext().
#define AST_LAW (p) (((p)->law == DAHDI_LAW_ALAW) ? AST_FORMAT_ALAW : AST_FORMAT_ULAW)
Definition at line 209 of file chan_dahdi.c.
Referenced by dahdi_call(), dahdi_callwait(), dahdi_sendtext(), do_monitor(), mwi_send_init(), mwi_thread(), send_cwcidspill(), and ss_thread().
#define CALLPROGRESS_FAX (CALLPROGRESS_FAX_INCOMING | CALLPROGRESS_FAX_OUTGOING)
Definition at line 294 of file chan_dahdi.c.
Referenced by dahdi_handle_dtmfup(), and process_dahdi().
#define CALLPROGRESS_FAX_INCOMING 4
Definition at line 293 of file chan_dahdi.c.
Referenced by dahdi_new(), and process_dahdi().
#define CALLPROGRESS_FAX_OUTGOING 2
Definition at line 292 of file chan_dahdi.c.
Referenced by dahdi_new(), and process_dahdi().
#define CALLPROGRESS_PROGRESS 1
Definition at line 291 of file chan_dahdi.c.
Referenced by dahdi_handle_event(), dahdi_new(), and process_dahdi().
#define CALLWAITING_REPEAT_SAMPLES ((10000 * 8) / READ_SIZE)
10,000 ms
Definition at line 403 of file chan_dahdi.c.
Referenced by dahdi_callwait().
#define CALLWAITING_SILENT_SAMPLES ((300 * 8) / READ_SIZE)
300 ms
Definition at line 402 of file chan_dahdi.c.
#define CANBUSYDETECT (p) (ISTRUNK(p) || (p->sig & (SIG_EM | SIG_EM_E1 | SIG_SF)) /* || (p->sig & __DAHDI_SIG_FXO) */)
Definition at line 1500 of file chan_dahdi.c.
Referenced by dahdi_new().
#define CANPROGRESSDETECT (p) (ISTRUNK(p) || (p->sig & (SIG_EM | SIG_EM_E1 | SIG_SF)) /* || (p->sig & __DAHDI_SIG_FXO) */)
Definition at line 1501 of file chan_dahdi.c.
Referenced by dahdi_call(), dahdi_handle_event(), and dahdi_new().
#define CHAN_PSEUDO -2
Definition at line 277 of file chan_dahdi.c.
Referenced by build_channels(), dahdi_new(), dahdi_request(), enable_dtmf_detect(), mkintf(), and process_dahdi().
#define CHANNEL_PSEUDO -12
Definition at line 207 of file chan_dahdi.c.
#define CIDCW_EXPIRE_SAMPLES ((500 * 8) / READ_SIZE)
500 ms
Definition at line 404 of file chan_dahdi.c.
Referenced by send_callerid().
#define CONF_USER_REAL (1 << 0)
Definition at line 625 of file chan_dahdi.c.
#define CONF_USER_THIRDCALL (1 << 1)
Definition at line 626 of file chan_dahdi.c.
#define DAHDI_CHAN_MAPPING_LOGICAL 1
Definition at line 339 of file chan_dahdi.c.
Referenced by process_dahdi().
#define DAHDI_CHAN_MAPPING_PHYSICAL 0
Definition at line 338 of file chan_dahdi.c.
Referenced by dahdi_chan_conf_default(), and process_dahdi().
#define DAHDI_OVERLAPDIAL_BOTH (DAHDI_OVERLAPDIAL_INCOMING|DAHDI_OVERLAPDIAL_OUTGOING)
Definition at line 289 of file chan_dahdi.c.
Referenced by process_dahdi().
#define DAHDI_OVERLAPDIAL_INCOMING 2
Definition at line 288 of file chan_dahdi.c.
Referenced by dahdi_handle_event(), dahdi_read(), process_dahdi(), and ss_thread().
#define DAHDI_OVERLAPDIAL_NONE 0
Definition at line 286 of file chan_dahdi.c.
Referenced by process_dahdi().
#define DAHDI_OVERLAPDIAL_OUTGOING 1
Definition at line 287 of file chan_dahdi.c.
Referenced by dahdi_read(), and process_dahdi().
#define DCHAN_AVAILABLE (DCHAN_PROVISIONED | DCHAN_NOTINALARM | DCHAN_UP)
Definition at line 283 of file chan_dahdi.c.
#define DCHAN_NOTINALARM (1 << 1)
Definition at line 280 of file chan_dahdi.c.
#define DCHAN_PROVISIONED (1 << 0)
Definition at line 279 of file chan_dahdi.c.
#define DCHAN_UP (1 << 2)
Definition at line 281 of file chan_dahdi.c.
#define DEFAULT_CIDRINGS 1
Typically, how many rings before we should send Caller*ID.
Note:
Define ZHONE_HACK to cause us to go off hook and then back on hook when the user hangs up to reset the state machine so ring works properly. This is used to be able to support kewlstart by putting the zhone in groundstart mode since their forward disconnect supervision is entirely broken even though their documentation says it isn't and their support is entirely unwilling to provide any assistance with their channel banks even though their web site says they support their products for life.
Define if you want to check the hook state for an FXO (FXS signalled) interface before dialing on it. Certain FXO interfaces always think they're out of service with this method however.
Definition at line 205 of file chan_dahdi.c.
Referenced by dahdi_chan_conf_default().
#define DEFAULT_RINGT ((8000 * 8) / READ_SIZE)
8,000 ms
Definition at line 406 of file chan_dahdi.c.
#define END_SILENCE_LEN 400
Referenced by dahdi_sendtext().
#define FORMAT "%-40.40s %-7.7s %-6d %-6d %-6d %-3.3s %-4.4s %-8.8s %s\n"
#define FORMAT "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
Referenced by __iax2_show_peers(), _sip_show_peers(), alias_show(), dahdi_show_channels(), dahdi_show_status(), dundi_show_mappings(), dundi_show_peers(), dundi_show_precache(), dundi_show_requests(), dundi_show_trans(), gtalk_show_channels(), handle_cli_core_show_channeltypes(), handle_cli_core_show_file_formats(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_registry(), handle_cli_iax2_show_users(), handle_cli_keys_show(), handle_core_show_image_formats(), handle_show_routes(), handle_show_version_files(), jingle_show_channels(), show_channels_cb(), show_chanstats_cb(), sip_show_domains(), sip_show_inuse(), sip_show_mwi(), sip_show_registry(), sip_show_tcp(), and sip_show_users().
#define FORMAT2 "%-40.40s %-7.7s %-6.6s %-6.6s %-6.6s %-3.3s %-4.4s %-8.8s %s\n"
#define FORMAT2 "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
Referenced by __iax2_show_peers(), _sip_show_peers(), dahdi_show_channels(), dahdi_show_status(), dundi_show_mappings(), dundi_show_peers(), dundi_show_precache(), dundi_show_requests(), dundi_show_trans(), handle_cli_core_show_file_formats(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_registry(), handle_cli_iax2_show_users(), handle_core_show_image_formats(), sip_show_channels(), sip_show_channelstats(), sip_show_inuse(), sip_show_registry(), and sip_show_tcp().
#define GET_CHANNEL (p) ((p)->channel)
Definition at line 1425 of file chan_dahdi.c.
Referenced by update_conf().
#define HANGUP 1
Definition at line 15183 of file chan_dahdi.c.
Referenced by action_transferhangup(), and dahdi_fake_event().
#define HEADER_LEN ((HEADER_MS + TRAILER_MS) * 8)
Referenced by build_alerting(), build_connect(), build_connect_acknowledge(), build_disconnect(), build_facility(), build_hold(), build_hold_acknowledge(), build_hold_reject(), build_information(), build_notify(), build_proceeding(), build_progress(), build_release(), build_release_complete(), build_restart(), build_resume(), build_resume_acknowledge(), build_resume_reject(), build_retrieve(), build_retrieve_acknowledge(), build_retrieve_reject(), build_setup(), build_setup_acknowledge(), build_status(), build_status_enquiry(), build_suspend(), build_suspend_acknowledge(), build_suspend_reject(), build_timeout(), build_user_information(), dahdi_sendtext(), parse_alerting(), parse_connect(), parse_disconnect(), parse_facility(), parse_information(), parse_proceeding(), parse_progress(), parse_release(), parse_release_complete(), parse_restart(), parse_setup(), parse_setup_acknowledge(), and parse_status().
#define HEADER_MS 50
Referenced by dahdi_sendtext().
#define ISTRUNK (p)
Value:
((p->sig == SIG_FXSLS) || (p->sig == SIG_FXSKS) || \
         (p->sig == SIG_FXSGS) || (p->sig == SIG_PRI))
Definition at line 1497 of file chan_dahdi.c.
Referenced by dahdi_indicate(), and ss_thread().
#define MASK_AVAIL (1 << 0)
Channel available for PRI use
Definition at line 399 of file chan_dahdi.c.
#define MASK_INUSE (1 << 1)
Channel currently in use
Definition at line 400 of file chan_dahdi.c.
#define MAX_CHANLIST_LEN 80
The length of the parameters list of 'dahdichan'.
Todo:
Move definition of MAX_CHANLIST_LEN to a proper place.
Definition at line 16038 of file chan_dahdi.c.
Referenced by process_dahdi().
#define MAX_CHANNELS 672
No more than a DS3 per trunk group
Definition at line 275 of file chan_dahdi.c.
Referenced by mkintf().
#define MAX_SLAVES 4
Definition at line 628 of file chan_dahdi.c.
Referenced by dahdi_link(), dahdi_show_channel(), dahdi_unlink(), isslavenative(), and update_conf().
#define MIN_MS_SINCE_FLASH ((2000))
2000 ms
Definition at line 405 of file chan_dahdi.c.
Referenced by dahdi_handle_event().
#define NEED_MFDETECT (p) (((p)->sig == SIG_FEATDMF) || ((p)->sig == SIG_FEATDMF_TA) || ((p)->sig == SIG_E911) || ((p)->sig == SIG_FGC_CAMA) || ((p)->sig == SIG_FGC_CAMAMF) || ((p)->sig == SIG_FEATB))
Signaling types that need to use MF detection should be placed in this macro.
Definition at line 213 of file chan_dahdi.c.
Referenced by dahdi_new(), and ss_thread().
#define NUM_CADENCE_MAX 25
Definition at line 1472 of file chan_dahdi.c.
Referenced by process_dahdi().
#define NUM_DCHANS 4
No more than 4 d-channels
Definition at line 274 of file chan_dahdi.c.
#define NUM_SPANS 32
Definition at line 272 of file chan_dahdi.c.
#define POLARITY_IDLE 0
Definition at line 584 of file chan_dahdi.c.
Referenced by dahdi_handle_event(), dahdi_hangup(), ss_thread(), and unalloc_sub().
#define POLARITY_REV 1
Definition at line 585 of file chan_dahdi.c.
Referenced by dahdi_handle_event(), handle_init_event(), and ss_thread().
#define PROC_DAHDI_OPT_NOCHAN (1 << 0)
process_dahdi() - ignore keyword 'channel' and similar
Definition at line 16092 of file chan_dahdi.c.
Referenced by process_dahdi(), and setup_dahdi().
#define PROC_DAHDI_OPT_NOWARN (1 << 1)
process_dahdi() - No warnings on non-existing cofiguration keywords
Definition at line 16094 of file chan_dahdi.c.
Referenced by process_dahdi(), and setup_dahdi().
#define READ_SIZE 160
Chunk size to read -- we use 20ms chunks to make things happy.
Definition at line 397 of file chan_dahdi.c.
Referenced by dahdi_callwait(), dahdi_open(), dahdi_read(), dahdi_sendtext(), dahdi_setoption(), my_dahdi_write(), process_dahdi(), and send_cwcidspill().
#define sig2str dahdi_sig2str
Definition at line 2476 of file chan_dahdi.c.
Referenced by action_dahdishowchannels(), build_channels(), dahdi_handle_event(), dahdi_show_channel(), handle_init_event(), mkintf(), and ss_thread().
#define SIG_BRI (0x2000000 | DAHDI_SIG_CLEAR)
Definition at line 256 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_confmute(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_enable_ec(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_queue_frame(), dahdi_read(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_BRI_PTMP (0X4000000 | DAHDI_SIG_CLEAR)
Definition at line 257 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_confmute(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_enable_ec(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_queue_frame(), dahdi_read(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_E911 (0x1000000 | DAHDI_SIG_EM)
Definition at line 245 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_EM DAHDI_SIG_EM
Definition at line 240 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_EM_E1 DAHDI_SIG_EM_E1
Definition at line 265 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_EMWINK (0x0100000 | DAHDI_SIG_EM)
Definition at line 241 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FEATB (0x0800000 | DAHDI_SIG_EM)
Definition at line 244 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FEATD (0x0200000 | DAHDI_SIG_EM)
Definition at line 242 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FEATDMF (0x0400000 | DAHDI_SIG_EM)
Definition at line 243 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FEATDMF_TA (0x2000000 | DAHDI_SIG_EM)
Definition at line 246 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FGC_CAMA (0x4000000 | DAHDI_SIG_EM)
Definition at line 247 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FGC_CAMAMF (0x8000000 | DAHDI_SIG_EM)
Definition at line 248 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FXOGS DAHDI_SIG_FXOGS
Definition at line 253 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_new(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FXOKS DAHDI_SIG_FXOKS
Definition at line 254 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_new(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FXOLS DAHDI_SIG_FXOLS
Definition at line 252 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_new(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FXSGS DAHDI_SIG_FXSGS
Definition at line 250 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_sig2str(), handle_init_event(), process_dahdi(), and ss_thread().
#define SIG_FXSKS DAHDI_SIG_FXSKS
Definition at line 251 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_request(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_FXSLS DAHDI_SIG_FXSLS
Definition at line 249 of file chan_dahdi.c.
Referenced by available(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_GR303FXOKS (0x0100000 | DAHDI_SIG_FXOKS)
Definition at line 266 of file chan_dahdi.c.
Referenced by dahdi_sig2str(), handle_init_event(), mkintf(), and process_dahdi().
#define SIG_GR303FXSKS (0x0100000 | DAHDI_SIG_FXSKS)
Definition at line 267 of file chan_dahdi.c.
Referenced by dahdi_sig2str(), handle_init_event(), mkintf(), and process_dahdi().
#define SIG_MFCR2 DAHDI_SIG_CAS
Definition at line 259 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_hangup(), dahdi_sig2str(), do_monitor(), mkintf(), and process_dahdi().
#define SIG_PRI DAHDI_SIG_CLEAR
Definition at line 255 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_confmute(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_enable_ec(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_queue_frame(), dahdi_read(), dahdi_sig2str(), dahdi_write(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_SF DAHDI_SIG_SF
Definition at line 260 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_SF_FEATB (0x0800000 | DAHDI_SIG_SF)
Definition at line 264 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_SF_FEATD (0x0200000 | DAHDI_SIG_SF)
Definition at line 262 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), and ss_thread().
#define SIG_SF_FEATDMF (0x0400000 | DAHDI_SIG_SF)
Definition at line 263 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), and ss_thread().
#define SIG_SFWINK (0x0100000 | DAHDI_SIG_SF)
Definition at line 261 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_sig2str(), handle_init_event(), mkintf(), process_dahdi(), and ss_thread().
#define SIG_SS7 (0x1000000 | DAHDI_SIG_CLEAR)
Definition at line 258 of file chan_dahdi.c.
Referenced by dahdi_answer(), dahdi_call(), dahdi_confmute(), dahdi_enable_ec(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_queue_frame(), dahdi_sig2str(), handle_init_event(), mkintf(), and process_dahdi().
#define SMDI_MD_WAIT_TIMEOUT 1500
Definition at line 159 of file chan_dahdi.c.
Referenced by ss_thread().
#define SUB_CALLWAIT 1
Call-Waiting call on hold
Definition at line 580 of file chan_dahdi.c.
Referenced by available(), dahdi_bridge(), dahdi_call(), dahdi_get_index(), dahdi_handle_event(), dahdi_hangup(), dahdi_read(), dahdi_request(), dahdi_show_channel(), and ss_thread().
#define SUB_REAL 0
Active call
Definition at line 579 of file chan_dahdi.c.
Referenced by __dahdi_exception(), attempt_transfer(), available(), build_device(), bump_gains(), check_for_conference(), close_call(), close_client(), dahdi_answer(), dahdi_bridge(), dahdi_call(), dahdi_confmute(), dahdi_destroy_channel_bynum(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_disable_ec(), dahdi_enable_ec(), dahdi_get_index(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_new(), dahdi_read(), dahdi_request(), dahdi_ring_phone(), dahdi_setoption(), dahdi_train_ec(), dahdi_unlink(), destroy_dahdi_pvt(), disable_dtmf_detect(), do_monitor(), duplicate_pseudo(), enable_dtmf_detect(), find_subchannel_by_name(), get_alarms(), handle_init_event(), HandleCallIncoming(), HandleCallOutgoing(), key_call(), key_dial_page(), mkintf(), mwi_send_init(), mwi_send_process_buffer(), mwi_send_process_event(), mwi_thread(), process_request(), rcv_mac_addr(), reset_conf(), restore_conference(), restore_gains(), save_conference(), send_callerid(), ss_thread(), TransferCallStep1(), unistim_do_senddigit(), unistim_hangup(), unistim_senddigit_end(), and update_conf().
#define SUB_THREEWAY 2
Three-way call
Definition at line 581 of file chan_dahdi.c.
Referenced by attempt_transfer(), available(), close_call(), dahdi_answer(), dahdi_bridge(), dahdi_get_index(), dahdi_handle_event(), dahdi_hangup(), dahdi_show_channel(), HandleCallOutgoing(), ss_thread(), TransferCallStep1(), unistim_answer(), and unistim_hangup().
#define TRAILER_MS 5
Referenced by dahdi_sendtext().
#define TRANSFER 0
Definition at line 15182 of file chan_dahdi.c.
Referenced by action_transfer(), dahdi_fake_event(), send_agent_complete(), and try_calling().
Enumeration Type Documentation
enum mwisend_states
Enumerator:
MWI_SEND_NULL
MWI_SEND_SA
MWI_SEND_SA_WAIT
MWI_SEND_PAUSE
MWI_SEND_SPILL
MWI_SEND_CLEANUP
MWI_SEND_DONE
Definition at line 633 of file chan_dahdi.c.
             {
   MWI_SEND_NULL = 0,
   MWI_SEND_SA,
   MWI_SEND_SA_WAIT,
   MWI_SEND_PAUSE,
   MWI_SEND_SPILL,
   MWI_SEND_CLEANUP,
   MWI_SEND_DONE,
} mwisend_states;
Function Documentation
static struct ast_frame* __dahdi_exception (struct ast_channel * ast) [static, read]
Definition at line 6601 of file chan_dahdi.c.
References ast_channel::_state, ast_bridged_channel(), AST_CONTROL_UNHOLD, ast_debug, AST_FRAME_NULL, ast_log(), ast_queue_control(), ast_setstate(), AST_STATE_RINGING, AST_STATE_UP, ast_tv(), ast_tvnow(), ast_verb, dahdi_pvt::callwaitingrepeat, dahdi_pvt::channel, dahdi_pvt::cidcwexpire, dahdi_disable_ec(), dahdi_enable_ec(), dahdi_get_event(), dahdi_get_index(), dahdi_handle_event(), dahdi_ring_phone(), dahdi_set_hook(), ast_frame::data, ast_frame::datalen, ast_frame::delivery, dahdi_subchannel::dfd, dahdi_pvt::dialing, event2str(), dahdi_subchannel::f, dahdi_pvt::fake_event, ast_channel::fds, dahdi_pvt::flashtime, ast_frame::frametype, LOG_WARNING, ast_frame::mallocd, dahdi_subchannel::needanswer, dahdi_subchannel::needunhold, ast_frame::offset, dahdi_pvt::oprmode, dahdi_subchannel::owner, dahdi_pvt::owner, ast_frame::ptr, dahdi_pvt::radio, ast_frame::samples, ast_frame::src, SUB_REAL, ast_frame::subclass, dahdi_pvt::subs, ast_channel::tech_pvt, and update_conf().
Referenced by dahdi_exception(), and dahdi_read().
{
   struct dahdi_pvt *p = ast->tech_pvt;
   int res;
   int usedindex=-1;
   int idx;
   struct ast_frame *f;
   idx = dahdi_get_index(ast, p, 1);
   p->subs[idx].f.frametype = AST_FRAME_NULL;
   p->subs[idx].f.datalen = 0;
   p->subs[idx].f.samples = 0;
   p->subs[idx].f.mallocd = 0;
   p->subs[idx].f.offset = 0;
   p->subs[idx].f.subclass = 0;
   p->subs[idx].f.delivery = ast_tv(0,0);
   p->subs[idx].f.src = "dahdi_exception";
   p->subs[idx].f.data.ptr = NULL;
   if ((!p->owner) && (!(p->radio || (p->oprmode < 0)))) {
      /* If nobody owns us, absorb the event appropriately, otherwise
         we loop indefinitely.  This occurs when, during call waiting, the
         other end hangs up our channel so that it no longer exists, but we
         have neither FLASH'd nor ONHOOK'd to signify our desire to
         change to the other channel. */
      if (p->fake_event) {
         res = p->fake_event;
         p->fake_event = 0;
      } else
         res = dahdi_get_event(p->subs[SUB_REAL].dfd);
      /* Switch to real if there is one and this isn't something really silly... */
      if ((res != DAHDI_EVENT_RINGEROFF) && (res != DAHDI_EVENT_RINGERON) &&
         (res != DAHDI_EVENT_HOOKCOMPLETE)) {
         ast_debug(1, "Restoring owner of channel %d on event %d\n", p->channel, res);
         p->owner = p->subs[SUB_REAL].owner;
         if (p->owner && ast_bridged_channel(p->owner))
            ast_queue_control(p->owner, AST_CONTROL_UNHOLD);
         p->subs[SUB_REAL].needunhold = 1;
      }
      switch (res) {
      case DAHDI_EVENT_ONHOOK:
         dahdi_disable_ec(p);
         if (p->owner) {
            ast_verb(3, "Channel %s still has call, ringing phone\n", p->owner->name);
            dahdi_ring_phone(p);
            p->callwaitingrepeat = 0;
            p->cidcwexpire = 0;
         } else
            ast_log(LOG_WARNING, "Absorbed on hook, but nobody is left!?!?\n");
         update_conf(p);
         break;
      case DAHDI_EVENT_RINGOFFHOOK:
         dahdi_enable_ec(p);
         dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
         if (p->owner && (p->owner->_state == AST_STATE_RINGING)) {
            p->subs[SUB_REAL].needanswer = 1;
            p->dialing = 0;
         }
         break;
      case DAHDI_EVENT_HOOKCOMPLETE:
      case DAHDI_EVENT_RINGERON:
      case DAHDI_EVENT_RINGEROFF:
         /* Do nothing */
         break;
      case DAHDI_EVENT_WINKFLASH:
         p->flashtime = ast_tvnow();
         if (p->owner) {
            ast_verb(3, "Channel %d flashed to other channel %s\n", p->channel, p->owner->name);
            if (p->owner->_state != AST_STATE_UP) {
               /* Answer if necessary */
               usedindex = dahdi_get_index(p->owner, p, 0);
               if (usedindex > -1) {
                  p->subs[usedindex].needanswer = 1;
               }
               ast_setstate(p->owner, AST_STATE_UP);
            }
            p->callwaitingrepeat = 0;
            p->cidcwexpire = 0;
            if (ast_bridged_channel(p->owner))
               ast_queue_control(p->owner, AST_CONTROL_UNHOLD);
            p->subs[SUB_REAL].needunhold = 1;
         } else
            ast_log(LOG_WARNING, "Absorbed on hook, but nobody is left!?!?\n");
         update_conf(p);
         break;
      default:
         ast_log(LOG_WARNING, "Don't know how to absorb event %s\n", event2str(res));
      }
      f = &p->subs[idx].f;
      return f;
   }
   if (!(p->radio || (p->oprmode < 0)))
      ast_debug(1, "Exception on %d, channel %d\n", ast->fds[0],p->channel);
   /* If it's not us, return NULL immediately */
   if (ast != p->owner) {
      ast_log(LOG_WARNING, "We're %s, not %s\n", ast->name, p->owner->name);
      f = &p->subs[idx].f;
      return f;
   }
   f = dahdi_handle_event(ast);
   return f;
}
static int __unload_module (void) [static]
Definition at line 15849 of file chan_dahdi.c.
References ARRAY_LEN, ast_channel_unregister(), ast_cli_unregister_multiple(), ast_cond_destroy(), ast_manager_unregister(), ast_mutex_lock(), ast_mutex_unlock(), AST_PTHREADT_NULL, AST_PTHREADT_STOP, ast_softhangup(), AST_SOFTHANGUP_APPUNLOAD, ast_unregister_application(), destroy_all_channels(), iflist, master, dahdi_pvt::next, and dahdi_pvt::owner.
Referenced by load_module(), and unload_module().
15850 {
15851    struct dahdi_pvt *p;
15852 #if defined(HAVE_PRI) || defined(HAVE_SS7)
15853    int i, j;
15854 #endif
15855
15856 #ifdef HAVE_PRI
15857    for (i = 0; i < NUM_SPANS; i++) {
15858       if (pris[i].master != AST_PTHREADT_NULL)
15859          pthread_cancel(pris[i].master);
15860    }
15861    ast_cli_unregister_multiple(dahdi_pri_cli, ARRAY_LEN(dahdi_pri_cli));
15862    ast_unregister_application(dahdi_send_keypad_facility_app);
15863 #ifdef HAVE_PRI_PROG_W_CAUSE
15864    ast_unregister_application(dahdi_send_callrerouting_facility_app);
15865 #endif
15866 #endif
15867 #if defined(HAVE_SS7)
15868    for (i = 0; i < NUM_SPANS; i++) {
15869       if (linksets[i].master != AST_PTHREADT_NULL)
15870          pthread_cancel(linksets[i].master);
15871       }
15872    ast_cli_unregister_multiple(dahdi_ss7_cli, ARRAY_LEN(dahdi_ss7_cli));
15873 #endif
15874 #if defined(HAVE_OPENR2)
15875    dahdi_r2_destroy_links();
15876    ast_cli_unregister_multiple(dahdi_mfcr2_cli, ARRAY_LEN(dahdi_mfcr2_cli));
15877    ast_unregister_application(dahdi_accept_r2_call_app);
15878 #endif
15879
15880    ast_cli_unregister_multiple(dahdi_cli, ARRAY_LEN(dahdi_cli));
15881    ast_manager_unregister("DAHDIDialOffhook");
15882    ast_manager_unregister("DAHDIHangup");
15883    ast_manager_unregister("DAHDITransfer");
15884    ast_manager_unregister("DAHDIDNDoff");
15885    ast_manager_unregister("DAHDIDNDon");
15886    ast_manager_unregister("DAHDIShowChannels");
15887    ast_manager_unregister("DAHDIRestart");
15888    ast_channel_unregister(&dahdi_tech);
15889    ast_mutex_lock(&iflock);
15890    /* Hangup all interfaces if they have an owner */
15891    p = iflist;
15892    while (p) {
15893       if (p->owner)
15894          ast_softhangup(p->owner, AST_SOFTHANGUP_APPUNLOAD);
15895       p = p->next;
15896    }
15897    ast_mutex_unlock(&iflock);
15898    ast_mutex_lock(&monlock);
15899    if (monitor_thread && (monitor_thread != AST_PTHREADT_STOP) && (monitor_thread != AST_PTHREADT_NULL)) {
15900       pthread_cancel(monitor_thread);
15901       pthread_kill(monitor_thread, SIGURG);
15902       pthread_join(monitor_thread, NULL);
15903    }
15904    monitor_thread = AST_PTHREADT_STOP;
15905    ast_mutex_unlock(&monlock);
15906
15907    destroy_all_channels();
15908
15909 #if defined(HAVE_PRI)
15910    for (i = 0; i < NUM_SPANS; i++) {
15911       if (pris[i].master && (pris[i].master != AST_PTHREADT_NULL))
15912          pthread_join(pris[i].master, NULL);
15913       for (j = 0; j < NUM_DCHANS; j++) {
15914          dahdi_close_pri_fd(&(pris[i]), j);
15915       }
15916    }
15917 #endif
15918
15919 #if defined(HAVE_SS7)
15920    for (i = 0; i < NUM_SPANS; i++) {
15921       if (linksets[i].master && (linksets[i].master != AST_PTHREADT_NULL))
15922          pthread_join(linksets[i].master, NULL);
15923       for (j = 0; j < NUM_DCHANS; j++) {
15924          dahdi_close_ss7_fd(&(linksets[i]), j);
15925       }
15926    }
15927 #endif
15928    ast_cond_destroy(&ss_thread_complete);
15929    return 0;
15930 }
static int action_dahdidialoffhook (struct mansession * s, const struct message * m) [static]
Definition at line 15289 of file chan_dahdi.c.
References AST_FRAME_DTMF, ast_strlen_zero(), astman_get_header(), astman_send_ack(), astman_send_error(), dahdi_queue_frame(), find_channel(), and dahdi_pvt::owner.
Referenced by load_module().
15290 {
15291    struct dahdi_pvt *p = NULL;
15292    const char *channel = astman_get_header(m, "DAHDIChannel");
15293    const char *number = astman_get_header(m, "Number");
15294    int i;
15295
15296    if (ast_strlen_zero(channel)) {
15297       astman_send_error(s, m, "No channel specified");
15298       return 0;
15299    }
15300    if (ast_strlen_zero(number)) {
15301       astman_send_error(s, m, "No number specified");
15302       return 0;
15303    }
15304    p = find_channel(atoi(channel));
15305    if (!p) {
15306       astman_send_error(s, m, "No such channel");
15307       return 0;
15308    }
15309    if (!p->owner) {
15310       astman_send_error(s, m, "Channel does not have it's owner");
15311       return 0;
15312    }
15313    for (i = 0; i < strlen(number); i++) {
15314       struct ast_frame f = { AST_FRAME_DTMF, number[i] };
15315       dahdi_queue_frame(p, &f, NULL);
15316    }
15317    astman_send_ack(s, m, "DAHDIDialOffhook");
15318    return 0;
15319 }
static int action_dahdidndoff (struct mansession * s, const struct message * m) [static]
Definition at line 15232 of file chan_dahdi.c.
References ast_strlen_zero(), astman_get_header(), astman_send_ack(), astman_send_error(), dahdi_pvt::dnd, and find_channel().
Referenced by load_module().
15233 {
15234    struct dahdi_pvt *p = NULL;
15235    const char *channel = astman_get_header(m, "DAHDIChannel");
15236
15237    if (ast_strlen_zero(channel)) {
15238       astman_send_error(s, m, "No channel specified");
15239       return 0;
15240    }
15241    p = find_channel(atoi(channel));
15242    if (!p) {
15243       astman_send_error(s, m, "No such channel");
15244       return 0;
15245    }
15246    p->dnd = 0;
15247    astman_send_ack(s, m, "DND Disabled");
15248    return 0;
15249 }
static int action_dahdidndon (struct mansession * s, const struct message * m) [static]
Definition at line 15213 of file chan_dahdi.c.
References ast_strlen_zero(), astman_get_header(), astman_send_ack(), astman_send_error(), dahdi_pvt::dnd, and find_channel().
Referenced by load_module().
15214 {
15215    struct dahdi_pvt *p = NULL;
15216    const char *channel = astman_get_header(m, "DAHDIChannel");
15217
15218    if (ast_strlen_zero(channel)) {
15219       astman_send_error(s, m, "No channel specified");
15220       return 0;
15221    }
15222    p = find_channel(atoi(channel));
15223    if (!p) {
15224       astman_send_error(s, m, "No such channel");
15225       return 0;
15226    }
15227    p->dnd = 1;
15228    astman_send_ack(s, m, "DND Enabled");
15229    return 0;
15230 }
static int action_dahdirestart (struct mansession * s, const struct message * m) [static]
Definition at line 14475 of file chan_dahdi.c.
References astman_send_ack(), astman_send_error(), and dahdi_restart().
Referenced by load_module().
14476 {
14477    if (dahdi_restart() != 0) {
14478       astman_send_error(s, m, "Failed rereading DAHDI configuration");
14479       return 1;
14480    }
14481    astman_send_ack(s, m, "DAHDIRestart: Success");
14482    return 0;
14483 }
static int action_dahdishowchannels (struct mansession * s, const struct message * m) [static]
Definition at line 15321 of file chan_dahdi.c.
References alarm2str(), ast_mutex_lock(), ast_mutex_unlock(), ast_strlen_zero(), astman_append(), astman_get_header(), astman_send_ack(), dahdi_pvt::channel, dahdi_pvt::context, dahdi_pvt::dnd, get_alarms(), iflist, dahdi_pvt::next, dahdi_pvt::owner, dahdi_pvt::sig, and sig2str.
Referenced by load_module().
15322 {
15323    struct dahdi_pvt *tmp = NULL;
15324    const char *id = astman_get_header(m, "ActionID");
15325    const char *dahdichannel = astman_get_header(m, "DAHDIChannel");
15326    char idText[256] = "";
15327    int channels = 0;
15328    int dahdichanquery = -1;
15329    if (!ast_strlen_zero(dahdichannel)) {
15330       dahdichanquery = atoi(dahdichannel);
15331    }
15332
15333    astman_send_ack(s, m, "DAHDI channel status will follow");
15334    if (!ast_strlen_zero(id))
15335       snprintf(idText, sizeof(idText), "ActionID: %s\r\n", id);
15336
15337    ast_mutex_lock(&iflock);
15338
15339    tmp = iflist;
15340    while (tmp) {
15341       if (tmp->channel > 0) {
15342          int alm = get_alarms(tmp);
15343
15344          /* If a specific channel is queried for, only deliver status for that channel */
15345          if (dahdichanquery > 0 && tmp->channel != dahdichanquery)
15346             continue;
15347
15348          channels++;
15349          if (tmp->owner) {
15350             /* Add data if we have a current call */
15351             astman_append(s,
15352                "Event: DAHDIShowChannels\r\n"
15353                "DAHDIChannel: %d\r\n"
15354                "Channel: %s\r\n"
15355                "Uniqueid: %s\r\n"
15356                "AccountCode: %s\r\n"
15357                "Signalling: %s\r\n"
15358                "SignallingCode: %d\r\n"
15359                "Context: %s\r\n"
15360                "DND: %s\r\n"
15361                "Alarm: %s\r\n"
15362                "%s"
15363                "\r\n",
15364                tmp->channel,
15365                tmp->owner->name,
15366                tmp->owner->uniqueid,
15367                tmp->owner->accountcode,
15368                sig2str(tmp->sig),
15369                tmp->sig,
15370                tmp->context,
15371                tmp->dnd ? "Enabled" : "Disabled",
15372                alarm2str(alm), idText);
15373          } else {
15374             astman_append(s,
15375                "Event: DAHDIShowChannels\r\n"
15376                "DAHDIChannel: %d\r\n"
15377                "Signalling: %s\r\n"
15378                "SignallingCode: %d\r\n"
15379                "Context: %s\r\n"
15380                "DND: %s\r\n"
15381                "Alarm: %s\r\n"
15382                "%s"
15383                "\r\n",
15384                tmp->channel, sig2str(tmp->sig), tmp->sig,
15385                tmp->context,
15386                tmp->dnd ? "Enabled" : "Disabled",
15387                alarm2str(alm), idText);
15388          }
15389       }
15390
15391       tmp = tmp->next;
15392    }
15393
15394    ast_mutex_unlock(&iflock);
15395
15396    astman_append(s,
15397       "Event: DAHDIShowChannelsComplete\r\n"
15398       "%s"
15399       "Items: %d\r\n"
15400       "\r\n",
15401       idText,
15402       channels);
15403    return 0;
15404 }
static int action_transfer (struct mansession * s, const struct message * m) [static]
Definition at line 15251 of file chan_dahdi.c.
References ast_strlen_zero(), astman_get_header(), astman_send_ack(), astman_send_error(), dahdi_fake_event(), find_channel(), and TRANSFER.
Referenced by load_module().
15252 {
15253    struct dahdi_pvt *p = NULL;
15254    const char *channel = astman_get_header(m, "DAHDIChannel");
15255
15256    if (ast_strlen_zero(channel)) {
15257       astman_send_error(s, m, "No channel specified");
15258       return 0;
15259    }
15260    p = find_channel(atoi(channel));
15261    if (!p) {
15262       astman_send_error(s, m, "No such channel");
15263       return 0;
15264    }
15265    dahdi_fake_event(p,TRANSFER);
15266    astman_send_ack(s, m, "DAHDITransfer");
15267    return 0;
15268 }
static int action_transferhangup (struct mansession * s, const struct message * m) [static]
Definition at line 15270 of file chan_dahdi.c.
References ast_strlen_zero(), astman_get_header(), astman_send_ack(), astman_send_error(), dahdi_fake_event(), find_channel(), and HANGUP.
Referenced by load_module().
15271 {
15272    struct dahdi_pvt *p = NULL;
15273    const char *channel = astman_get_header(m, "DAHDIChannel");
15274
15275    if (ast_strlen_zero(channel)) {
15276       astman_send_error(s, m, "No channel specified");
15277       return 0;
15278    }
15279    p = find_channel(atoi(channel));
15280    if (!p) {
15281       astman_send_error(s, m, "No such channel");
15282       return 0;
15283    }
15284    dahdi_fake_event(p,HANGUP);
15285    astman_send_ack(s, m, "DAHDIHangup");
15286    return 0;
15287 }
static char* alarm2str (int alm) [static]
Definition at line 2379 of file chan_dahdi.c.
References alarms, and ARRAY_LEN.
Referenced by action_dahdishowchannels(), and handle_alarms().
{
   int x;
   for (x = 0; x < ARRAY_LEN(alarms); x++) {
      if (alarms[x].alarm & alm)
         return alarms[x].name;
   }
   return alm ? "Unknown Alarm" : "No Alarm";
}
static int alloc_sub (struct dahdi_pvt * p, int x) [static]
Definition at line 2175 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::buf_no, dahdi_pvt::buf_policy, dahdi_subchannel::chan, dahdi_pvt::channel, dahdi_close_sub(), dahdi_open(), dahdi_subchannel::dfd, errno, LOG_WARNING, and dahdi_pvt::subs.
Referenced by dahdi_handle_event(), dahdi_request(), and ss_thread().
{
   struct dahdi_bufferinfo bi;
   int res;
   if (p->subs[x].dfd >= 0) {
      ast_log(LOG_WARNING, "%s subchannel of %d already in use\n", subnames[x], p->channel);
      return -1;
   }
   p->subs[x].dfd = dahdi_open("/dev/dahdi/pseudo");
   if (p->subs[x].dfd <= -1) {
      ast_log(LOG_WARNING, "Unable to open pseudo channel: %s\n", strerror(errno));
      return -1;
   }
   res = ioctl(p->subs[x].dfd, DAHDI_GET_BUFINFO, &bi);
   if (!res) {
      bi.txbufpolicy = p->buf_policy;
      bi.rxbufpolicy = p->buf_policy;
      bi.numbufs = p->buf_no;
      res = ioctl(p->subs[x].dfd, DAHDI_SET_BUFINFO, &bi);
      if (res < 0) {
         ast_log(LOG_WARNING, "Unable to set buffer policy on channel %d: %s\n", x, strerror(errno));
      }
   } else
      ast_log(LOG_WARNING, "Unable to check buffer policy on channel %d: %s\n", x, strerror(errno));
   if (ioctl(p->subs[x].dfd, DAHDI_CHANNO, &p->subs[x].chan) == 1) {
      ast_log(LOG_WARNING, "Unable to get channel number for pseudo channel on FD %d: %s\n", p->subs[x].dfd, strerror(errno));
      dahdi_close_sub(p, x);
      p->subs[x].dfd = -1;
      return -1;
   }
   ast_debug(1, "Allocated %s subchannel on FD %d channel %d\n", subnames[x], p->subs[x].dfd, p->subs[x].chan);
   return 0;
}
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_DEFAULT , tdesc , . load = load_module, . unload = unload_module, . reload = reload)
AST_MUTEX_DEFINE_STATIC (restart_lock)
AST_MUTEX_DEFINE_STATIC (ss_thread_lock)
AST_MUTEX_DEFINE_STATIC (monlock)
Protect the monitoring thread, so only one process can kill or start it, and not when it's doing something critical.
AST_MUTEX_DEFINE_STATIC (iflock)
Protect the interface list (of dahdi_pvt's).
static int attempt_transfer (struct dahdi_pvt * p) [static]
Definition at line 5502 of file chan_dahdi.c.
References ast_channel::_softhangup, ast_channel::_state, ast_bridged_channel(), ast_channel_masquerade(), ast_channel_unlock, AST_CONTROL_RINGING, AST_CONTROL_UNHOLD, ast_debug, ast_indicate(), ast_log(), ast_queue_control(), AST_SOFTHANGUP_DEV, AST_STATE_RING, AST_STATE_RINGING, dahdi_subchannel::dfd, LOG_WARNING, dahdi_subchannel::owner, SUB_REAL, SUB_THREEWAY, dahdi_pvt::subs, swap_subs(), and unalloc_sub().
Referenced by dahdi_handle_event().
{
   /* In order to transfer, we need at least one of the channels to
      actually be in a call bridge.  We can't conference two applications
      together (but then, why would we want to?) */
   if (ast_bridged_channel(p->subs[SUB_REAL].owner)) {
      /* The three-way person we're about to transfer to could still be in MOH, so
         stop if now if appropriate */
      if (ast_bridged_channel(p->subs[SUB_THREEWAY].owner))
         ast_queue_control(p->subs[SUB_THREEWAY].owner, AST_CONTROL_UNHOLD);
      if (p->subs[SUB_REAL].owner->_state == AST_STATE_RINGING) {
         ast_indicate(ast_bridged_channel(p->subs[SUB_REAL].owner), AST_CONTROL_RINGING);
      }
      if (p->subs[SUB_THREEWAY].owner->_state == AST_STATE_RING) {
         tone_zone_play_tone(p->subs[SUB_THREEWAY].dfd, DAHDI_TONE_RINGTONE);
      }
       if (ast_channel_masquerade(p->subs[SUB_THREEWAY].owner, ast_bridged_channel(p->subs[SUB_REAL].owner))) {
         ast_log(LOG_WARNING, "Unable to masquerade %s as %s\n",
               ast_bridged_channel(p->subs[SUB_REAL].owner)->name, p->subs[SUB_THREEWAY].owner->name);
         return -1;
      }
      /* Orphan the channel after releasing the lock */
      ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
      unalloc_sub(p, SUB_THREEWAY);
   } else if (ast_bridged_channel(p->subs[SUB_THREEWAY].owner)) {
      ast_queue_control(p->subs[SUB_REAL].owner, AST_CONTROL_UNHOLD);
      if (p->subs[SUB_THREEWAY].owner->_state == AST_STATE_RINGING) {
         ast_indicate(ast_bridged_channel(p->subs[SUB_THREEWAY].owner), AST_CONTROL_RINGING);
      }
      if (p->subs[SUB_REAL].owner->_state == AST_STATE_RING) {
         tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_RINGTONE);
      }
      if (ast_channel_masquerade(p->subs[SUB_REAL].owner, ast_bridged_channel(p->subs[SUB_THREEWAY].owner))) {
         ast_log(LOG_WARNING, "Unable to masquerade %s as %s\n",
               ast_bridged_channel(p->subs[SUB_THREEWAY].owner)->name, p->subs[SUB_REAL].owner->name);
         return -1;
      }
      /* Three-way is now the REAL */
      swap_subs(p, SUB_THREEWAY, SUB_REAL);
      ast_channel_unlock(p->subs[SUB_REAL].owner);
      unalloc_sub(p, SUB_THREEWAY);
      /* Tell the caller not to hangup */
      return 1;
   } else {
      ast_debug(1, "Neither %s nor %s are in a bridge, nothing to transfer\n",
         p->subs[SUB_REAL].owner->name, p->subs[SUB_THREEWAY].owner->name);
      p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
      return -1;
   }
   return 0;
}
static int available (struct dahdi_pvt * p, int channelmatch, ast_group_t groupmatch, int * busy, int * channelmatched, int * groupmatched) [inline, static]
Definition at line 10640 of file chan_dahdi.c.
References ast_channel::_state, ast_debug, ast_log(), AST_STATE_RINGING, AST_STATE_UP, dahdi_pvt::callwaiting, dahdi_pvt::channel, dahdi_subchannel::dfd, dahdi_pvt::dnd, errno, dahdi_pvt::group, dahdi_pvt::guardtime, dahdi_subchannel::inthreeway, dahdi_pvt::locallyblocked, LOG_WARNING, dahdi_pvt::oprmode, dahdi_pvt::outgoing, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::radio, dahdi_pvt::remotelyblocked, dahdi_pvt::sig, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, and dahdi_pvt::subs.
Referenced by __ast_string_field_ptr_build_va(), and dahdi_request().
10641 {
10642    int res;
10643    struct dahdi_params par;
10644
10645    /* First, check group matching */
10646    if (groupmatch) {
10647       if ((p->group & groupmatch) != groupmatch)
10648          return 0;
10649       *groupmatched = 1;
10650    }
10651    /* Check to see if we have a channel match */
10652    if (channelmatch != -1) {
10653       if (p->channel != channelmatch)
10654          return 0;
10655       *channelmatched = 1;
10656    }
10657    /* We're at least busy at this point */
10658    if (busy) {
10659       if ((p->sig == SIG_FXOKS) || (p->sig == SIG_FXOLS) || (p->sig == SIG_FXOGS))
10660          *busy = 1;
10661    }
10662    /* If do not disturb, definitely not */
10663    if (p->dnd)
10664       return 0;
10665    /* If guard time, definitely not */
10666    if (p->guardtime && (time(NULL) < p->guardtime))
10667       return 0;
10668
10669    if (p->locallyblocked || p->remotelyblocked)
10670       return 0;
10671
10672    /* If no owner definitely available */
10673    if (!p->owner) {
10674 #ifdef HAVE_PRI
10675       /* Trust PRI */
10676       if (p->pri) {
10677          if (p->resetting || p->call)
10678             return 0;
10679          else
10680             return 1;
10681       }
10682 #endif
10683 #ifdef HAVE_SS7
10684       /* Trust SS7 */
10685       if (p->ss7) {
10686          if (p->ss7call)
10687             return 0;
10688          else
10689             return 1;
10690       }
10691 #endif
10692 #ifdef HAVE_OPENR2
10693       /* Trust MFC/R2 */
10694       if (p->mfcr2) {
10695          if (p->mfcr2call)
10696             return 0;
10697          else
10698             return 1;
10699       }
10700 #endif
10701       if (!(p->radio || (p->oprmode < 0)))
10702       {
10703          if (!p->sig || (p->sig == SIG_FXSLS))
10704             return 1;
10705          /* Check hook state */
10706          if (p->subs[SUB_REAL].dfd > -1) {
10707             memset(&par, 0, sizeof(par));
10708             res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &par);
10709          } else {
10710             /* Assume not off hook on CVRS */
10711             res = 0;
10712             par.rxisoffhook = 0;
10713          }
10714          if (res) {
10715             ast_log(LOG_WARNING, "Unable to check hook state on channel %d: %s\n", p->channel, strerror(errno));
10716          } else if ((p->sig == SIG_FXSKS) || (p->sig == SIG_FXSGS)) {
10717             /* When "onhook" that means no battery on the line, and thus
10718               it is out of service..., if it's on a TDM card... If it's a channel
10719               bank, there is no telling... */
10720             if (par.rxbits > -1)
10721                return 1;
10722             if (par.rxisoffhook)
10723                return 1;
10724             else
10725                return 0;
10726          } else if (par.rxisoffhook) {
10727             ast_debug(1, "Channel %d off hook, can't use\n", p->channel);
10728             /* Not available when the other end is off hook */
10729 #ifdef DAHDI_CHECK_HOOKSTATE
10730             return 0;
10731 #else
10732             return 1;
10733 #endif
10734          }
10735       }
10736       return 1;
10737    }
10738
10739    /* If it's not an FXO, forget about call wait */
10740    if ((p->sig != SIG_FXOKS) && (p->sig != SIG_FXOLS) && (p->sig != SIG_FXOGS))
10741       return 0;
10742
10743    if (!p->callwaiting) {
10744       /* If they don't have call waiting enabled, then for sure they're unavailable at this point */
10745       return 0;
10746    }
10747
10748    if (p->subs[SUB_CALLWAIT].dfd > -1) {
10749       /* If there is already a call waiting call, then we can't take a second one */
10750       return 0;
10751    }
10752
10753    if ((p->owner->_state != AST_STATE_UP) &&
10754       ((p->owner->_state != AST_STATE_RINGING) || p->outgoing)) {
10755       /* If the current call is not up, then don't allow the call */
10756       return 0;
10757    }
10758    if ((p->subs[SUB_THREEWAY].owner) && (!p->subs[SUB_THREEWAY].inthreeway)) {
10759       /* Can't take a call wait when the three way calling hasn't been merged yet. */
10760       return 0;
10761    }
10762    /* We're cool */
10763    return 1;
10764 }
static int build_channels (struct dahdi_chan_conf * conf, int iscrv, const char * value, int reload, int lineno, int * found_pseudo) [static]
Definition at line 15948 of file chan_dahdi.c.
References ast_log(), ast_strdupa, ast_verb, dahdi_chan_conf::chan, CHAN_PSEUDO, dahdi_chan_conf::is_sig_auto, LOG_ERROR, LOG_WARNING, mkintf(), dahdi_pvt::sig, sig2str, and strsep().
Referenced by process_dahdi().
15949 {
15950    char *c, *chan;
15951    int x, start, finish;
15952    struct dahdi_pvt *tmp;
15953 #ifdef HAVE_PRI
15954    struct dahdi_pri *pri;
15955    int trunkgroup, y;
15956 #endif
15957
15958    if ((reload == 0) && (conf->chan.sig < 0) && !conf->is_sig_auto) {
15959       ast_log(LOG_ERROR, "Signalling must be specified before any channels are.\n");
15960       return -1;
15961    }
15962
15963    c = ast_strdupa(value);
15964
15965 #ifdef HAVE_PRI
15966    pri = NULL;
15967    if (iscrv) {
15968       if (sscanf(c, "%30d:%n", &trunkgroup, &y) != 1) {
15969          ast_log(LOG_WARNING, "CRV must begin with trunkgroup followed by a colon at line %d.\n", lineno);
15970          return -1;
15971       }
15972       if (trunkgroup < 1) {
15973          ast_log(LOG_WARNING, "CRV trunk group must be a positive number at line %d.\n", lineno);
15974          return -1;
15975       }
15976       c += y;
15977       for (y = 0; y < NUM_SPANS; y++) {
15978          if (pris[y].trunkgroup == trunkgroup) {
15979             pri = pris + y;
15980             break;
15981          }
15982       }
15983       if (!pri) {
15984          ast_log(LOG_WARNING, "No such trunk group %d at CRV declaration at line %d.\n", trunkgroup, lineno);
15985          return -1;
15986       }
15987    }
15988 #endif
15989
15990    while ((chan = strsep(&c, ","))) {
15991       if (sscanf(chan, "%30d-%30d", &start, &finish) == 2) {
15992          /* Range */
15993       } else if (sscanf(chan, "%30d", &start)) {
15994          /* Just one */
15995          finish = start;
15996       } else if (!strcasecmp(chan, "pseudo")) {
15997          finish = start = CHAN_PSEUDO;
15998          if (found_pseudo)
15999             *found_pseudo = 1;
16000       } else {
16001          ast_log(LOG_ERROR, "Syntax error parsing '%s' at '%s'\n", value, chan);
16002          return -1;
16003       }
16004       if (finish < start) {
16005          ast_log(LOG_WARNING, "Sillyness: %d < %d\n", start, finish);
16006          x = finish;
16007          finish = start;
16008          start = x;
16009       }
16010
16011       for (x = start; x <= finish; x++) {
16012 #ifdef HAVE_PRI
16013          tmp = mkintf(x, conf, pri, reload);
16014 #else
16015          tmp = mkintf(x, conf, NULL, reload);
16016 #endif
16017
16018          if (tmp) {
16019 #ifdef HAVE_PRI
16020             if (pri)
16021                ast_verb(3, "%s CRV %d:%d, %s signalling\n", reload ? "Reconfigured" : "Registered", trunkgroup, x, sig2str(tmp->sig));
16022             else
16023 #endif
16024                ast_verb(3, "%s channel %d, %s signalling\n", reload ? "Reconfigured" : "Registered", x, sig2str(tmp->sig));
16025          } else {
16026             ast_log(LOG_ERROR, "Unable to %s channel '%s'\n",
16027                (reload == 1) ? "reconfigure" : "register", value);
16028             return -1;
16029          }
16030       }
16031    }
16032
16033    return 0;
16034 }
static int bump_gains (struct dahdi_pvt * p) [static]
Definition at line 2836 of file chan_dahdi.c.
References ast_log(), dahdi_pvt::cid_rxgain, dahdi_subchannel::dfd, errno, dahdi_pvt::law, LOG_WARNING, dahdi_pvt::rxgain, set_actual_gain(), SUB_REAL, dahdi_pvt::subs, and dahdi_pvt::txgain.
Referenced by mwi_thread(), and ss_thread().
{
   int res;
   /* Bump receive gain by value stored in cid_rxgain */
   res = set_actual_gain(p->subs[SUB_REAL].dfd, 0, p->rxgain + p->cid_rxgain, p->txgain, p->law);
   if (res) {
      ast_log(LOG_WARNING, "Unable to bump gain: %s\n", strerror(errno));
      return -1;
   }
   return 0;
}
static int calc_energy (const unsigned char * buf, int len, int law) [static]
Definition at line 8911 of file chan_dahdi.c.
References AST_ALAW, AST_FORMAT_ULAW, and AST_MULAW.
Referenced by do_monitor(), and mwi_thread().
{
   int x;
   int sum = 0;
   if (!len)
      return 0;
   for (x = 0; x < len; x++)
      sum += abs(law == AST_FORMAT_ULAW ? AST_MULAW(buf[x]) : AST_ALAW(buf[x]));
   return sum / len;
}
static int check_for_conference (struct dahdi_pvt * p) [static]
Definition at line 5554 of file chan_dahdi.c.
References ast_log(), ast_verb, dahdi_pvt::channel, dahdi_pvt::confno, dahdi_subchannel::curconf, dahdi_subchannel::dfd, errno, LOG_WARNING, dahdi_pvt::master, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_handle_event().
{
   struct dahdi_confinfo ci;
   /* Fine if we already have a master, etc */
   if (p->master || (p->confno > -1))
      return 0;
   memset(&ci, 0, sizeof(ci));
   if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_GETCONF, &ci)) {
      ast_log(LOG_WARNING, "Failed to get conference info on channel %d: %s\n", p->channel, strerror(errno));
      return 0;
   }
   /* If we have no master and don't have a confno, then
      if we're in a conference, it's probably a MeetMe room or
      some such, so don't let us 3-way out! */
   if ((p->subs[SUB_REAL].curconf.confno != ci.confno) || (p->subs[SUB_REAL].curconf.confmode != ci.confmode)) {
      ast_verb(3, "Avoiding 3-way call when in an external conference\n");
      return 1;
   }
   return 0;
}
static int conf_add (struct dahdi_pvt * p, struct dahdi_subchannel * c, int idx, int slavechannel) [static]
Definition at line 2478 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::confno, dahdi_subchannel::curconf, dahdi_subchannel::dfd, errno, and LOG_WARNING.
Referenced by update_conf().
{
   /* If the conference already exists, and we're already in it
      don't bother doing anything */
   struct dahdi_confinfo zi;
   memset(&zi, 0, sizeof(zi));
   zi.chan = 0;
   if (slavechannel > 0) {
      /* If we have only one slave, do a digital mon */
      zi.confmode = DAHDI_CONF_DIGITALMON;
      zi.confno = slavechannel;
   } else {
      if (!idx) {
         /* Real-side and pseudo-side both participate in conference */
         zi.confmode = DAHDI_CONF_REALANDPSEUDO | DAHDI_CONF_TALKER | DAHDI_CONF_LISTENER |
            DAHDI_CONF_PSEUDO_TALKER | DAHDI_CONF_PSEUDO_LISTENER;
      } else
         zi.confmode = DAHDI_CONF_CONF | DAHDI_CONF_TALKER | DAHDI_CONF_LISTENER;
      zi.confno = p->confno;
   }
   if ((zi.confno == c->curconf.confno) && (zi.confmode == c->curconf.confmode))
      return 0;
   if (c->dfd < 0)
      return 0;
   if (ioctl(c->dfd, DAHDI_SETCONF, &zi)) {
      ast_log(LOG_WARNING, "Failed to add %d to conference %d/%d: %s\n", c->dfd, zi.confmode, zi.confno, strerror(errno));
      return -1;
   }
   if (slavechannel < 1) {
      p->confno = zi.confno;
   }
   memcpy(&c->curconf, &zi, sizeof(c->curconf));
   ast_debug(1, "Added %d to conference %d/%d\n", c->dfd, c->curconf.confmode, c->curconf.confno);
   return 0;
}
static int conf_del (struct dahdi_pvt * p, struct dahdi_subchannel * c, int idx) [static]
Definition at line 2527 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_subchannel::curconf, dahdi_subchannel::dfd, errno, isourconf(), and LOG_WARNING.
Referenced by dahdi_unlink(), and update_conf().
{
   struct dahdi_confinfo zi;
   if (/* Can't delete if there's no dfd */
      (c->dfd < 0) ||
      /* Don't delete from the conference if it's not our conference */
      !isourconf(p, c)
      /* Don't delete if we don't think it's conferenced at all (implied) */
      ) return 0;
   memset(&zi, 0, sizeof(zi));
   if (ioctl(c->dfd, DAHDI_SETCONF, &zi)) {
      ast_log(LOG_WARNING, "Failed to drop %d from conference %d/%d: %s\n", c->dfd, c->curconf.confmode, c->curconf.confno, strerror(errno));
      return -1;
   }
   ast_debug(1, "Removed %d from conference %d/%d\n", c->dfd, c->curconf.confmode, c->curconf.confno);
   memcpy(&c->curconf, &zi, sizeof(c->curconf));
   return 0;
}
static int dahdi_answer (struct ast_channel * ast) [static]
Definition at line 4718 of file chan_dahdi.c.
References ast_channel::_state, ast_debug, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_setstate(), AST_STATE_RINGING, AST_STATE_UP, ast_tvnow(), dahdi_pvt::channel, dahdi_enable_ec(), dahdi_get_index(), dahdi_set_hook(), dahdi_train_ec(), dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::digital, dahdi_pvt::hanguponpolarityswitch, dahdi_subchannel::inthreeway, dahdi_pvt::lock, LOG_DEBUG, LOG_WARNING, dahdi_pvt::oprmode, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::polaritydelaytv, dahdi_pvt::radio, dahdi_pvt::ringt, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, SIG_SS7, dahdi_pvt::span, SUB_REAL, SUB_THREEWAY, dahdi_pvt::subs, swap_subs(), and ast_channel::tech_pvt.
{
   struct dahdi_pvt *p = ast->tech_pvt;
   int res = 0;
   int idx;
   int oldstate = ast->_state;
   ast_setstate(ast, AST_STATE_UP);
   ast_mutex_lock(&p->lock);
   idx = dahdi_get_index(ast, p, 0);
   if (idx < 0)
      idx = SUB_REAL;
   /* nothing to do if a radio channel */
   if ((p->radio || (p->oprmode < 0))) {
      ast_mutex_unlock(&p->lock);
      return 0;
   }
   switch (p->sig) {
   case SIG_FXSLS:
   case SIG_FXSGS:
   case SIG_FXSKS:
      p->ringt = 0;
      /* Fall through */
   case SIG_EM:
   case SIG_EM_E1:
   case SIG_EMWINK:
   case SIG_FEATD:
   case SIG_FEATDMF:
   case SIG_FEATDMF_TA:
   case SIG_E911:
   case SIG_FGC_CAMA:
   case SIG_FGC_CAMAMF:
   case SIG_FEATB:
   case SIG_SF:
   case SIG_SFWINK:
   case SIG_SF_FEATD:
   case SIG_SF_FEATDMF:
   case SIG_SF_FEATB:
   case SIG_FXOLS:
   case SIG_FXOGS:
   case SIG_FXOKS:
      /* Pick up the line */
      ast_debug(1, "Took %s off hook\n", ast->name);
      if (p->hanguponpolarityswitch) {
         p->polaritydelaytv = ast_tvnow();
      }
      res = dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
      tone_zone_play_tone(p->subs[idx].dfd, -1);
      p->dialing = 0;
      if ((idx == SUB_REAL) && p->subs[SUB_THREEWAY].inthreeway) {
         if (oldstate == AST_STATE_RINGING) {
            ast_debug(1, "Finally swapping real and threeway\n");
            tone_zone_play_tone(p->subs[SUB_THREEWAY].dfd, -1);
            swap_subs(p, SUB_THREEWAY, SUB_REAL);
            p->owner = p->subs[SUB_REAL].owner;
         }
      }
      if (p->sig & __DAHDI_SIG_FXS) {
         dahdi_enable_ec(p);
         dahdi_train_ec(p);
      }
      break;
#ifdef HAVE_PRI
   case SIG_BRI:
   case SIG_BRI_PTMP:
   case SIG_PRI:
      /* Send a pri acknowledge */
      if (!pri_grab(p, p->pri)) {
         p->proceeding = 1;
         p->dialing = 0;
         res = pri_answer(p->pri->pri, p->call, 0, !p->digital);
         pri_rel(p->pri);
      } else {
         ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
         res = -1;
      }
      break;
#endif
#ifdef HAVE_SS7
   case SIG_SS7:
      if (!ss7_grab(p, p->ss7)) {
         p->proceeding = 1;
         res = isup_anm(p->ss7->ss7, p->ss7call);
         ss7_rel(p->ss7);
      } else {
         ast_log(LOG_WARNING, "Unable to grab SS7 on span %d\n", p->span);
         res = -1;
      }
      break;
#endif
#ifdef HAVE_OPENR2
   case SIG_MFCR2:
      if (!p->mfcr2_call_accepted) {
         /* The call was not accepted on offer nor the user, so it must be accepted now before answering,
            openr2_chan_answer_call will be called when the callback on_call_accepted is executed */
         p->mfcr2_answer_pending = 1;
         if (p->mfcr2_charge_calls) {
            ast_log(LOG_DEBUG, "Accepting MFC/R2 call with charge before answering on chan %d\n", p->channel);
            openr2_chan_accept_call(p->r2chan, OR2_CALL_WITH_CHARGE);
         } else {
            ast_log(LOG_DEBUG, "Accepting MFC/R2 call with no charge before answering on chan %d\n", p->channel);
            openr2_chan_accept_call(p->r2chan, OR2_CALL_NO_CHARGE);
         }
      } else {
         ast_log(LOG_DEBUG, "Answering MFC/R2 call on chan %d\n", p->channel);
         dahdi_r2_answer(p);
      }
      break;
#endif
   case 0:
      ast_mutex_unlock(&p->lock);
      return 0;
   default:
      ast_log(LOG_WARNING, "Don't know how to answer signalling %d (channel %d)\n", p->sig, p->channel);
      res = -1;
   }
   ast_mutex_unlock(&p->lock);
   return res;
}
static enum ast_bridge_result dahdi_bridge (struct ast_channel * c0, struct ast_channel * c1, int flags, struct ast_frame ** fo, struct ast_channel ** rc, int timeoutms) [static]
Definition at line 5156 of file chan_dahdi.c.
References ast_channel::_state, AST_BRIDGE_COMPLETE, AST_BRIDGE_DTMF_CHANNEL_0, AST_BRIDGE_DTMF_CHANNEL_1, AST_BRIDGE_FAILED, AST_BRIDGE_FAILED_NOWARN, AST_BRIDGE_RETRY, ast_channel_lock, ast_channel_trylock, ast_channel_unlock, ast_debug, AST_FRAME_CONTROL, AST_FRAME_DTMF, ast_frfree, ast_log(), ast_mutex_trylock(), ast_mutex_unlock(), ast_read(), AST_STATE_RINGING, ast_verb, ast_waitfor_n(), ast_write(), dahdi_pvt::channel, CHANNEL_DEADLOCK_AVOIDANCE, dahdi_disable_ec(), dahdi_enable_ec(), dahdi_get_index(), dahdi_link(), dahdi_unlink(), dahdi_subchannel::dfd, disable_dtmf_detect(), dahdi_pvt::echocanbridged, enable_dtmf_detect(), ast_channel::fds, ast_frame::frametype, dahdi_pvt::inconference, dahdi_subchannel::inthreeway, dahdi_pvt::lock, LOG_NOTICE, LOG_WARNING, master, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::pulsedial, dahdi_pvt::sig, SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, dahdi_pvt::subs, ast_channel::tech_pvt, dahdi_pvt::transfer, and update_conf().
{
   struct ast_channel *who;
   struct dahdi_pvt *p0, *p1, *op0, *op1;
   struct dahdi_pvt *master = NULL, *slave = NULL;
   struct ast_frame *f;
   int inconf = 0;
   int nothingok = 1;
   int ofd0, ofd1;
   int oi0, oi1, i0 = -1, i1 = -1, t0, t1;
   int os0 = -1, os1 = -1;
   int priority = 0;
   struct ast_channel *oc0, *oc1;
   enum ast_bridge_result res;
#ifdef PRI_2BCT
   int triedtopribridge = 0;
   q931_call *q931c0 = NULL, *q931c1 = NULL;
#endif
   /* For now, don't attempt to native bridge if either channel needs DTMF detection.
      There is code below to handle it properly until DTMF is actually seen,
      but due to currently unresolved issues it's ignored...
   */
   if (flags & (AST_BRIDGE_DTMF_CHANNEL_0 | AST_BRIDGE_DTMF_CHANNEL_1))
      return AST_BRIDGE_FAILED_NOWARN;
   ast_channel_lock(c0);
   while (ast_channel_trylock(c1)) {
      CHANNEL_DEADLOCK_AVOIDANCE(c0);
   }
   p0 = c0->tech_pvt;
   p1 = c1->tech_pvt;
   /* cant do pseudo-channels here */
   if (!p0 || (!p0->sig) || !p1 || (!p1->sig)) {
      ast_channel_unlock(c0);
      ast_channel_unlock(c1);
      return AST_BRIDGE_FAILED_NOWARN;
   }
   oi0 = dahdi_get_index(c0, p0, 0);
   oi1 = dahdi_get_index(c1, p1, 0);
   if ((oi0 < 0) || (oi1 < 0)) {
      ast_channel_unlock(c0);
      ast_channel_unlock(c1);
      return AST_BRIDGE_FAILED;
   }
   op0 = p0 = c0->tech_pvt;
   op1 = p1 = c1->tech_pvt;
   ofd0 = c0->fds[0];
   ofd1 = c1->fds[0];
   oc0 = p0->owner;
   oc1 = p1->owner;
   if (ast_mutex_trylock(&p0->lock)) {
      /* Don't block, due to potential for deadlock */
      ast_channel_unlock(c0);
      ast_channel_unlock(c1);
      ast_log(LOG_NOTICE, "Avoiding deadlock...\n");
      return AST_BRIDGE_RETRY;
   }
   if (ast_mutex_trylock(&p1->lock)) {
      /* Don't block, due to potential for deadlock */
      ast_mutex_unlock(&p0->lock);
      ast_channel_unlock(c0);
      ast_channel_unlock(c1);
      ast_log(LOG_NOTICE, "Avoiding deadlock...\n");
      return AST_BRIDGE_RETRY;
   }
   if ((oi0 == SUB_REAL) && (oi1 == SUB_REAL)) {
      if (p0->owner && p1->owner) {
         /* If we don't have a call-wait in a 3-way, and we aren't in a 3-way, we can be master */
         if (!p0->subs[SUB_CALLWAIT].inthreeway && !p1->subs[SUB_REAL].inthreeway) {
            master = p0;
            slave = p1;
            inconf = 1;
         } else if (!p1->subs[SUB_CALLWAIT].inthreeway && !p0->subs[SUB_REAL].inthreeway) {
            master = p1;
            slave = p0;
            inconf = 1;
         } else {
            ast_log(LOG_WARNING, "Huh?  Both calls are callwaits or 3-ways?  That's clever...?\n");
            ast_log(LOG_WARNING, "p0: chan %d/%d/CW%d/3W%d, p1: chan %d/%d/CW%d/3W%d\n",
               p0->channel,
               oi0, (p0->subs[SUB_CALLWAIT].dfd > -1) ? 1 : 0,
               p0->subs[SUB_REAL].inthreeway, p0->channel,
               oi0, (p1->subs[SUB_CALLWAIT].dfd > -1) ? 1 : 0,
               p1->subs[SUB_REAL].inthreeway);
         }
         nothingok = 0;
      }
   } else if ((oi0 == SUB_REAL) && (oi1 == SUB_THREEWAY)) {
      if (p1->subs[SUB_THREEWAY].inthreeway) {
         master = p1;
         slave = p0;
         nothingok = 0;
      }
   } else if ((oi0 == SUB_THREEWAY) && (oi1 == SUB_REAL)) {
      if (p0->subs[SUB_THREEWAY].inthreeway) {
         master = p0;
         slave = p1;
         nothingok = 0;
      }
   } else if ((oi0 == SUB_REAL) && (oi1 == SUB_CALLWAIT)) {
      /* We have a real and a call wait.  If we're in a three way call, put us in it, otherwise,
         don't put us in anything */
      if (p1->subs[SUB_CALLWAIT].inthreeway) {
         master = p1;
         slave = p0;
         nothingok = 0;
      }
   } else if ((oi0 == SUB_CALLWAIT) && (oi1 == SUB_REAL)) {
      /* Same as previous */
      if (p0->subs[SUB_CALLWAIT].inthreeway) {
         master = p0;
         slave = p1;
         nothingok = 0;
      }
   }
   ast_debug(1, "master: %d, slave: %d, nothingok: %d\n",
      master ? master->channel : 0, slave ? slave->channel : 0, nothingok);
   if (master && slave) {
      /* Stop any tones, or play ringtone as appropriate.  If they're bridged
         in an active threeway call with a channel that is ringing, we should
         indicate ringing. */
      if ((oi1 == SUB_THREEWAY) &&
         p1->subs[SUB_THREEWAY].inthreeway &&
         p1->subs[SUB_REAL].owner &&
         p1->subs[SUB_REAL].inthreeway &&
         (p1->subs[SUB_REAL].owner->_state == AST_STATE_RINGING)) {
         ast_debug(1, "Playing ringback on %s since %s is in a ringing three-way\n", c0->name, c1->name);
         tone_zone_play_tone(p0->subs[oi0].dfd, DAHDI_TONE_RINGTONE);
         os1 = p1->subs[SUB_REAL].owner->_state;
      } else {
         ast_debug(1, "Stopping tones on %d/%d talking to %d/%d\n", p0->channel, oi0, p1->channel, oi1);
         tone_zone_play_tone(p0->subs[oi0].dfd, -1);
      }
      if ((oi0 == SUB_THREEWAY) &&
         p0->subs[SUB_THREEWAY].inthreeway &&
         p0->subs[SUB_REAL].owner &&
         p0->subs[SUB_REAL].inthreeway &&
         (p0->subs[SUB_REAL].owner->_state == AST_STATE_RINGING)) {
         ast_debug(1, "Playing ringback on %s since %s is in a ringing three-way\n", c1->name, c0->name);
         tone_zone_play_tone(p1->subs[oi1].dfd, DAHDI_TONE_RINGTONE);
         os0 = p0->subs[SUB_REAL].owner->_state;
      } else {
         ast_debug(1, "Stopping tones on %d/%d talking to %d/%d\n", p1->channel, oi1, p0->channel, oi0);
         tone_zone_play_tone(p1->subs[oi0].dfd, -1);
      }
      if ((oi0 == SUB_REAL) && (oi1 == SUB_REAL)) {
         if (!p0->echocanbridged || !p1->echocanbridged) {
            /* Disable echo cancellation if appropriate */
            dahdi_disable_ec(p0);
            dahdi_disable_ec(p1);
         }
      }
      dahdi_link(slave, master);
      master->inconference = inconf;
   } else if (!nothingok)
      ast_log(LOG_WARNING, "Can't link %d/%s with %d/%s\n", p0->channel, subnames[oi0], p1->channel, subnames[oi1]);
   update_conf(p0);
   update_conf(p1);
   t0 = p0->subs[SUB_REAL].inthreeway;
   t1 = p1->subs[SUB_REAL].inthreeway;
   ast_mutex_unlock(&p0->lock);
   ast_mutex_unlock(&p1->lock);
   ast_channel_unlock(c0);
   ast_channel_unlock(c1);
   /* Native bridge failed */
   if ((!master || !slave) && !nothingok) {
      dahdi_enable_ec(p0);
      dahdi_enable_ec(p1);
      return AST_BRIDGE_FAILED;
   }
   ast_verb(3, "Native bridging %s and %s\n", c0->name, c1->name);
   if (!(flags & AST_BRIDGE_DTMF_CHANNEL_0) && (oi0 == SUB_REAL))
      disable_dtmf_detect(op0);
   if (!(flags & AST_BRIDGE_DTMF_CHANNEL_1) && (oi1 == SUB_REAL))
      disable_dtmf_detect(op1);
   for (;;) {
      struct ast_channel *c0_priority[2] = {c0, c1};
      struct ast_channel *c1_priority[2] = {c1, c0};
      /* Here's our main loop...  Start by locking things, looking for private parts,
         and then balking if anything is wrong */
      ast_channel_lock(c0);
      while (ast_channel_trylock(c1)) {
         CHANNEL_DEADLOCK_AVOIDANCE(c0);
      }
      p0 = c0->tech_pvt;
      p1 = c1->tech_pvt;
      if (op0 == p0)
         i0 = dahdi_get_index(c0, p0, 1);
      if (op1 == p1)
         i1 = dahdi_get_index(c1, p1, 1);
      ast_channel_unlock(c0);
      ast_channel_unlock(c1);
      if (!timeoutms ||
         (op0 != p0) ||
         (op1 != p1) ||
         (ofd0 != c0->fds[0]) ||
         (ofd1 != c1->fds[0]) ||
         (p0->subs[SUB_REAL].owner && (os0 > -1) && (os0 != p0->subs[SUB_REAL].owner->_state)) ||
         (p1->subs[SUB_REAL].owner && (os1 > -1) && (os1 != p1->subs[SUB_REAL].owner->_state)) ||
         (oc0 != p0->owner) ||
         (oc1 != p1->owner) ||
         (t0 != p0->subs[SUB_REAL].inthreeway) ||
         (t1 != p1->subs[SUB_REAL].inthreeway) ||
         (oi0 != i0) ||
         (oi1 != i1)) {
         ast_debug(1, "Something changed out on %d/%d to %d/%d, returning -3 to restart\n",
            op0->channel, oi0, op1->channel, oi1);
         res = AST_BRIDGE_RETRY;
         goto return_from_bridge;
      }
#ifdef PRI_2BCT
      q931c0 = p0->call;
      q931c1 = p1->call;
      if (p0->transfer && p1->transfer
         && q931c0 && q931c1
         && !triedtopribridge) {
         pri_channel_bridge(q931c0, q931c1);
         triedtopribridge = 1;
      }
#endif
      who = ast_waitfor_n(priority ? c0_priority : c1_priority, 2, &timeoutms);
      if (!who) {
         ast_debug(1, "Ooh, empty read...\n");
         continue;
      }
      f = ast_read(who);
      if (!f || (f->frametype == AST_FRAME_CONTROL)) {
         *fo = f;
         *rc = who;
         res = AST_BRIDGE_COMPLETE;
         goto return_from_bridge;
      }
      if (f->frametype == AST_FRAME_DTMF) {
         if ((who == c0) && p0->pulsedial) {
            ast_write(c1, f);
         } else if ((who == c1) && p1->pulsedial) {
            ast_write(c0, f);
         } else {
            *fo = f;
            *rc = who;
            res = AST_BRIDGE_COMPLETE;
            goto return_from_bridge;
         }
      }
      ast_frfree(f);
      /* Swap who gets priority */
      priority = !priority;
   }
return_from_bridge:
   if (op0 == p0)
      dahdi_enable_ec(p0);
   if (op1 == p1)
      dahdi_enable_ec(p1);
   if (!(flags & AST_BRIDGE_DTMF_CHANNEL_0) && (oi0 == SUB_REAL))
      enable_dtmf_detect(op0);
   if (!(flags & AST_BRIDGE_DTMF_CHANNEL_1) && (oi1 == SUB_REAL))
      enable_dtmf_detect(op1);
   dahdi_unlink(slave, master, 1);
   return res;
}
static int dahdi_call (struct ast_channel * ast, char * rdest, int timeout) [static]
Definition at line 3101 of file chan_dahdi.c.
References ast_channel::_state, dahdi_pvt::answeronpolarityswitch, ast_callerid_generate(), ast_channel_lock, ast_channel_unlock, ast_copy_string(), ast_debug, ast_free, AST_LAW, ast_log(), ast_malloc, ast_mutex_lock(), ast_mutex_unlock(), ast_setstate(), AST_STATE_BUSY, AST_STATE_DIALING, AST_STATE_DOWN, AST_STATE_OFFHOOK, AST_STATE_RESERVED, AST_STATE_RINGING, AST_STATE_UP, ast_strlen_zero(), ast_transfercapability2str(), ast_tvnow(), ast_verb, dahdi_pvt::callwait_name, dahdi_pvt::callwait_num, dahdi_pvt::callwaitcas, dahdi_pvt::callwaitrings, CANPROGRESSDETECT, dahdi_pvt::channel, ast_channel::cid, ast_callerid::cid_ani2, ast_callerid::cid_name, ast_callerid::cid_num, ast_callerid::cid_pres, ast_callerid::cid_rdnis, dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidrings, dahdi_pvt::cidspill, dahdi_callwait(), dahdi_get_index(), dahdi_subchannel::dfd, dahdi_pvt::dialdest, dahdi_pvt::dialednone, dahdi_pvt::dialing, dahdi_pvt::digital, dahdi_pvt::distinctivering, dahdi_pvt::dop, dahdi_pvt::dsp, dahdi_pvt::echobreak, dahdi_pvt::echorest, dahdi_pvt::echotraining, errno, dahdi_pvt::finaldial, dahdi_pvt::hanguponpolarityswitch, dahdi_pvt::hidecallerid, dahdi_pvt::hidecalleridname, IS_DIGITAL, dahdi_pvt::lastcid_name, dahdi_pvt::lastcid_num, dahdi_pvt::law, dahdi_pvt::lock, LOG_DEBUG, LOG_ERROR, LOG_WARNING, MAX_CALLERID_SIZE, dahdi_subchannel::needbusy, dahdi_subchannel::needringing, dahdi_pvt::oprmode, dahdi_pvt::outgoing, dahdi_pvt::outsigmod, dahdi_pvt::owner, pbx_builtin_getvar_helper(), dahdi_pvt::polaritydelaytv, PRI_TRANS_CAP_DIGITAL, dahdi_pvt::priexclusive, dahdi_pvt::pulse, dahdi_pvt::radio, dahdi_pvt::rxgain, s, send_callerid(), dahdi_pvt::sendcalleridafter, set_actual_gain(), dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, SIG_SS7, dahdi_pvt::stripmsd, SUB_CALLWAIT, SUB_REAL, dahdi_pvt::subs, ast_channel::tech_pvt, ast_channel::transfercapability, dahdi_pvt::txgain, dahdi_pvt::use_callerid, dahdi_pvt::use_callingpres, dahdi_pvt::waitfordialtone, dahdi_pvt::waitingfordt, and dahdi_pvt::whichwink.
{
   struct dahdi_pvt *p = ast->tech_pvt;
   int x, res, idx,mysig;
   char *c, *n, *l;
#ifdef HAVE_PRI
   char *s = NULL;
#endif
   char dest[256]; /* must be same length as p->dialdest */
   ast_mutex_lock(&p->lock);
   ast_copy_string(dest, rdest, sizeof(dest));
   ast_copy_string(p->dialdest, rdest, sizeof(p->dialdest));
   if ((ast->_state == AST_STATE_BUSY)) {
      p->subs[SUB_REAL].needbusy = 1;
      ast_mutex_unlock(&p->lock);
      return 0;
   }
   if ((ast->_state != AST_STATE_DOWN) && (ast->_state != AST_STATE_RESERVED)) {
      ast_log(LOG_WARNING, "dahdi_call called on %s, neither down nor reserved\n", ast->name);
      ast_mutex_unlock(&p->lock);
      return -1;
   }
   p->waitingfordt.tv_sec = 0;
   p->dialednone = 0;
   if ((p->radio || (p->oprmode < 0)))  /* if a radio channel, up immediately */
   {
      /* Special pseudo -- automatically up */
      ast_setstate(ast, AST_STATE_UP);
      ast_mutex_unlock(&p->lock);
      return 0;
   }
   x = DAHDI_FLUSH_READ | DAHDI_FLUSH_WRITE;
   res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_FLUSH, &x);
   if (res)
      ast_log(LOG_WARNING, "Unable to flush input on channel %d: %s\n", p->channel, strerror(errno));
   p->outgoing = 1;
   if (IS_DIGITAL(ast->transfercapability)){
      set_actual_gain(p->subs[SUB_REAL].dfd, 0, 0, 0, p->law);
   } else {
      set_actual_gain(p->subs[SUB_REAL].dfd, 0, p->rxgain, p->txgain, p->law);
   }
   mysig = p->sig;
   if (p->outsigmod > -1)
      mysig = p->outsigmod;
   switch (mysig) {
   case SIG_FXOLS:
   case SIG_FXOGS:
   case SIG_FXOKS:
      if (p->owner == ast) {
         /* Normal ring, on hook */
         /* Don't send audio while on hook, until the call is answered */
         p->dialing = 1;
         if (p->use_callerid) {
            /* Generate the Caller-ID spill if desired */
            if (p->cidspill) {
               ast_log(LOG_WARNING, "cidspill already exists??\n");
               ast_free(p->cidspill);
            }
            p->callwaitcas = 0;
            if ((p->cidspill = ast_malloc(MAX_CALLERID_SIZE))) {
               p->cidlen = ast_callerid_generate(p->cidspill, ast->cid.cid_name, ast->cid.cid_num, AST_LAW(p));
               p->cidpos = 0;
               send_callerid(p);
            }
         }
         /* Choose proper cadence */
         if ((p->distinctivering > 0) && (p->distinctivering <= num_cadence)) {
            if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETCADENCE, &cadences[p->distinctivering - 1]))
               ast_log(LOG_WARNING, "Unable to set distinctive ring cadence %d on '%s': %s\n", p->distinctivering, ast->name, strerror(errno));
            p->cidrings = cidrings[p->distinctivering - 1];
         } else {
            if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETCADENCE, NULL))
               ast_log(LOG_WARNING, "Unable to reset default ring on '%s': %s\n", ast->name, strerror(errno));
            p->cidrings = p->sendcalleridafter;
         }
         /* nick@dccinc.com 4/3/03 mods to allow for deferred dialing */
         c = strchr(dest, '/');
         if (c)
            c++;
         if (c && (strlen(c) < p->stripmsd)) {
            ast_log(LOG_WARNING, "Number '%s' is shorter than stripmsd (%d)\n", c, p->stripmsd);
            c = NULL;
         }
         if (c) {
            p->dop.op = DAHDI_DIAL_OP_REPLACE;
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "Tw%s", c);
            ast_debug(1, "FXO: setup deferred dialstring: %s\n", c);
         } else {
            p->dop.dialstr[0] = '\0';
         }
         x = DAHDI_RING;
         if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x) && (errno != EINPROGRESS)) {
            ast_log(LOG_WARNING, "Unable to ring phone: %s\n", strerror(errno));
            ast_mutex_unlock(&p->lock);
            return -1;
         }
         p->dialing = 1;
      } else {
         /* Call waiting call */
         p->callwaitrings = 0;
         if (ast->cid.cid_num)
            ast_copy_string(p->callwait_num, ast->cid.cid_num, sizeof(p->callwait_num));
         else
            p->callwait_num[0] = '\0';
         if (ast->cid.cid_name)
            ast_copy_string(p->callwait_name, ast->cid.cid_name, sizeof(p->callwait_name));
         else
            p->callwait_name[0] = '\0';
         /* Call waiting tone instead */
         if (dahdi_callwait(ast)) {
            ast_mutex_unlock(&p->lock);
            return -1;
         }
         /* Make ring-back */
         if (tone_zone_play_tone(p->subs[SUB_CALLWAIT].dfd, DAHDI_TONE_RINGTONE))
            ast_log(LOG_WARNING, "Unable to generate call-wait ring-back on channel %s\n", ast->name);
      }
      n = ast->cid.cid_name;
      l = ast->cid.cid_num;
      if (l)
         ast_copy_string(p->lastcid_num, l, sizeof(p->lastcid_num));
      else
         p->lastcid_num[0] = '\0';
      if (n)
         ast_copy_string(p->lastcid_name, n, sizeof(p->lastcid_name));
      else
         p->lastcid_name[0] = '\0';
      ast_setstate(ast, AST_STATE_RINGING);
      idx = dahdi_get_index(ast, p, 0);
      if (idx > -1) {
         p->subs[idx].needringing = 1;
      }
      break;
   case SIG_FXSLS:
   case SIG_FXSGS:
   case SIG_FXSKS:
      if (p->answeronpolarityswitch || p->hanguponpolarityswitch) {
         ast_debug(1, "Ignore possible polarity reversal on line seizure\n");
         p->polaritydelaytv = ast_tvnow();
      }
      /* fall through */
   case SIG_EMWINK:
   case SIG_EM:
   case SIG_EM_E1:
   case SIG_FEATD:
   case SIG_FEATDMF:
   case SIG_E911:
   case SIG_FGC_CAMA:
   case SIG_FGC_CAMAMF:
   case SIG_FEATB:
   case SIG_SFWINK:
   case SIG_SF:
   case SIG_SF_FEATD:
   case SIG_SF_FEATDMF:
   case SIG_FEATDMF_TA:
   case SIG_SF_FEATB:
      c = strchr(dest, '/');
      if (c)
         c++;
      else
         c = "";
      if (strlen(c) < p->stripmsd) {
         ast_log(LOG_WARNING, "Number '%s' is shorter than stripmsd (%d)\n", c, p->stripmsd);
         ast_mutex_unlock(&p->lock);
         return -1;
      }
#ifdef HAVE_PRI
      /* Start the trunk, if not GR-303 */
      if (!p->pri) {
#endif
         x = DAHDI_START;
         res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x);
         if (res < 0) {
            if (errno != EINPROGRESS) {
               ast_log(LOG_WARNING, "Unable to start channel: %s\n", strerror(errno));
               ast_mutex_unlock(&p->lock);
               return -1;
            }
         }
#ifdef HAVE_PRI
      }
#endif
      ast_debug(1, "Dialing '%s'\n", c);
      p->dop.op = DAHDI_DIAL_OP_REPLACE;
      c += p->stripmsd;
      switch (mysig) {
      case SIG_FEATD:
         l = ast->cid.cid_num;
         if (l)
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "T*%s*%s*", l, c);
         else
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "T**%s*", c);
         break;
      case SIG_FEATDMF:
         l = ast->cid.cid_num;
         if (l)
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*00%s#*%s#", l, c);
         else
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*02#*%s#", c);
         break;
      case SIG_FEATDMF_TA:
      {
         const char *cic, *ozz;
         /* If you have to go through a Tandem Access point you need to use this */
         ozz = pbx_builtin_getvar_helper(p->owner, "FEATDMF_OZZ");
         if (!ozz)
            ozz = defaultozz;
         cic = pbx_builtin_getvar_helper(p->owner, "FEATDMF_CIC");
         if (!cic)
            cic = defaultcic;
         if (!ozz || !cic) {
            ast_log(LOG_WARNING, "Unable to dial channel of type feature group D MF tandem access without CIC or OZZ set\n");
            ast_mutex_unlock(&p->lock);
            return -1;
         }
         snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*%s%s#", ozz, cic);
         snprintf(p->finaldial, sizeof(p->finaldial), "M*%s#", c);
         p->whichwink = 0;
      }
         break;
      case SIG_E911:
         ast_copy_string(p->dop.dialstr, "M*911#", sizeof(p->dop.dialstr));
         break;
      case SIG_FGC_CAMA:
         snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "P%s", c);
         break;
      case SIG_FGC_CAMAMF:
      case SIG_FEATB:
         snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*%s#", c);
         break;
      default:
         if (p->pulse)
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "P%sw", c);
         else
            snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "T%sw", c);
         break;
      }
      if (p->echotraining && (strlen(p->dop.dialstr) > 4)) {
         memset(p->echorest, 'w', sizeof(p->echorest) - 1);
         strcpy(p->echorest + (p->echotraining / 400) + 1, p->dop.dialstr + strlen(p->dop.dialstr) - 2);
         p->echorest[sizeof(p->echorest) - 1] = '\0';
         p->echobreak = 1;
         p->dop.dialstr[strlen(p->dop.dialstr)-2] = '\0';
      } else
         p->echobreak = 0;
      /* waitfordialtone ? */
#ifdef HAVE_PRI
      if (!p->pri) {
#endif
         if( p->waitfordialtone && CANPROGRESSDETECT(p) && p->dsp ) {
            ast_log(LOG_DEBUG, "Defer dialling for %dms or dialtone\n", p->waitfordialtone);
            gettimeofday(&p->waitingfordt,NULL);
            ast_setstate(ast, AST_STATE_OFFHOOK);
            break;
         }
#ifdef HAVE_PRI
      }
#endif
      if (!res) {
         if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop)) {
            int saveerr = errno;
            x = DAHDI_ONHOOK;
            ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x);
            ast_log(LOG_WARNING, "Dialing failed on channel %d: %s\n", p->channel, strerror(saveerr));
            ast_mutex_unlock(&p->lock);
            return -1;
         }
      } else
         ast_debug(1, "Deferring dialing...\n");
      p->dialing = 1;
      if (ast_strlen_zero(c))
         p->dialednone = 1;
      ast_setstate(ast, AST_STATE_DIALING);
      break;
   case 0:
      /* Special pseudo -- automatically up*/
      ast_setstate(ast, AST_STATE_UP);
      break;
   case SIG_PRI:
   case SIG_BRI:
   case SIG_BRI_PTMP:
   case SIG_SS7:
   case SIG_MFCR2:
      /* We'll get it in a moment -- but use dialdest to store pre-setup_ack digits */
      p->dialdest[0] = '\0';
      p->dialing = 1;
      break;
   default:
      ast_debug(1, "not yet implemented\n");
      ast_mutex_unlock(&p->lock);
      return -1;
   }
#ifdef HAVE_SS7
   if (p->ss7) {
      char ss7_called_nai;
      int called_nai_strip;
      char ss7_calling_nai;
      int calling_nai_strip;
      const char *charge_str = NULL;
      const char *gen_address = NULL;
      const char *gen_digits = NULL;
      const char *gen_dig_type = NULL;
      const char *gen_dig_scheme = NULL;
      const char *gen_name = NULL;
      const char *jip_digits = NULL;
      const char *lspi_ident = NULL;
      const char *rlt_flag = NULL;
      const char *call_ref_id = NULL;
      const char *call_ref_pc = NULL;
      const char *send_far = NULL;
      c = strchr(dest, '/');
      if (c) {
         c++;
      } else {
         c = "";
      }
      if (strlen(c) < p->stripmsd) {
         ast_log(LOG_WARNING, "Number '%s' is shorter than stripmsd (%d)\n", c, p->stripmsd);
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      if (!p->hidecallerid) {
         l = ast->cid.cid_num;
      } else {
         l = NULL;
      }
      if (ss7_grab(p, p->ss7)) {
         ast_log(LOG_WARNING, "Failed to grab SS7!\n");
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      p->digital = IS_DIGITAL(ast->transfercapability);
      p->ss7call = isup_new_call(p->ss7->ss7);
      if (!p->ss7call) {
         ss7_rel(p->ss7);
         ast_mutex_unlock(&p->lock);
         ast_log(LOG_ERROR, "Unable to allocate new SS7 call!\n");
         return -1;
      }
      called_nai_strip = 0;
      ss7_called_nai = p->ss7->called_nai;
      if (ss7_called_nai == SS7_NAI_DYNAMIC) { /* compute dynamically */
         if (strncmp(c + p->stripmsd, p->ss7->internationalprefix, strlen(p->ss7->internationalprefix)) == 0) {
            called_nai_strip = strlen(p->ss7->internationalprefix);
            ss7_called_nai = SS7_NAI_INTERNATIONAL;
         } else if (strncmp(c + p->stripmsd, p->ss7->nationalprefix, strlen(p->ss7->nationalprefix)) == 0) {
            called_nai_strip = strlen(p->ss7->nationalprefix);
            ss7_called_nai = SS7_NAI_NATIONAL;
         } else {
            ss7_called_nai = SS7_NAI_SUBSCRIBER;
         }
      }
      isup_set_called(p->ss7call, c + p->stripmsd + called_nai_strip, ss7_called_nai, p->ss7->ss7);
      calling_nai_strip = 0;
      ss7_calling_nai = p->ss7->calling_nai;
      if ((l != NULL) && (ss7_calling_nai == SS7_NAI_DYNAMIC)) { /* compute dynamically */
         if (strncmp(l, p->ss7->internationalprefix, strlen(p->ss7->internationalprefix)) == 0) {
            calling_nai_strip = strlen(p->ss7->internationalprefix);
            ss7_calling_nai = SS7_NAI_INTERNATIONAL;
         } else if (strncmp(l, p->ss7->nationalprefix, strlen(p->ss7->nationalprefix)) == 0) {
            calling_nai_strip = strlen(p->ss7->nationalprefix);
            ss7_calling_nai = SS7_NAI_NATIONAL;
         } else {
            ss7_calling_nai = SS7_NAI_SUBSCRIBER;
         }
      }
      isup_set_calling(p->ss7call, l ? (l + calling_nai_strip) : NULL, ss7_calling_nai,
         p->use_callingpres ? cid_pres2ss7pres(ast->cid.cid_pres) : (l ? SS7_PRESENTATION_ALLOWED : SS7_PRESENTATION_RESTRICTED),
         p->use_callingpres ? cid_pres2ss7screen(ast->cid.cid_pres) : SS7_SCREENING_USER_PROVIDED );
      isup_set_oli(p->ss7call, ast->cid.cid_ani2);
      isup_init_call(p->ss7->ss7, p->ss7call, p->cic, p->dpc);
      ast_channel_lock(ast);
      /* Set the charge number if it is set */
      charge_str = pbx_builtin_getvar_helper(ast, "SS7_CHARGE_NUMBER");
      if (charge_str)
         isup_set_charge(p->ss7call, charge_str, SS7_ANI_CALLING_PARTY_SUB_NUMBER, 0x10);
      gen_address = pbx_builtin_getvar_helper(ast, "SS7_GENERIC_ADDRESS");
      if (gen_address)
         isup_set_gen_address(p->ss7call, gen_address, p->gen_add_nai,p->gen_add_pres_ind, p->gen_add_num_plan,p->gen_add_type); /* need to add some types here for NAI,PRES,TYPE */
      gen_digits = pbx_builtin_getvar_helper(ast, "SS7_GENERIC_DIGITS");
      gen_dig_type = pbx_builtin_getvar_helper(ast, "SS7_GENERIC_DIGTYPE");
      gen_dig_scheme = pbx_builtin_getvar_helper(ast, "SS7_GENERIC_DIGSCHEME");
      if (gen_digits)
         isup_set_gen_digits(p->ss7call, gen_digits, atoi(gen_dig_type), atoi(gen_dig_scheme));
      gen_name = pbx_builtin_getvar_helper(ast, "SS7_GENERIC_NAME");
      if (gen_name)
         isup_set_generic_name(p->ss7call, gen_name, GEN_NAME_TYPE_CALLING_NAME, GEN_NAME_AVAIL_AVAILABLE, GEN_NAME_PRES_ALLOWED);
      jip_digits = pbx_builtin_getvar_helper(ast, "SS7_JIP");
      if (jip_digits)
         isup_set_jip_digits(p->ss7call, jip_digits);
      lspi_ident = pbx_builtin_getvar_helper(ast, "SS7_LSPI_IDENT");
      if (lspi_ident)
         isup_set_lspi(p->ss7call, lspi_ident, 0x18, 0x7, 0x00);
      rlt_flag = pbx_builtin_getvar_helper(ast, "SS7_RLT_ON");
      if ((rlt_flag) && ((strncmp("NO", rlt_flag, strlen(rlt_flag))) != 0 )) {
         isup_set_lspi(p->ss7call, rlt_flag, 0x18, 0x7, 0x00); /* Setting for Nortel DMS-250/500 */
      }
      call_ref_id = pbx_builtin_getvar_helper(ast, "SS7_CALLREF_IDENT");
      call_ref_pc = pbx_builtin_getvar_helper(ast, "SS7_CALLREF_PC");
      if (call_ref_id && call_ref_pc) {
         isup_set_callref(p->ss7call, atoi(call_ref_id),
                call_ref_pc ? atoi(call_ref_pc) : 0);
      }
      send_far = pbx_builtin_getvar_helper(ast, "SS7_SEND_FAR");
      if ((send_far) && ((strncmp("NO", send_far, strlen(send_far))) != 0 ))
         (isup_far(p->ss7->ss7, p->ss7call));
      ast_channel_unlock(ast);
      isup_iam(p->ss7->ss7, p->ss7call);
      ast_setstate(ast, AST_STATE_DIALING);
      ss7_rel(p->ss7);
   }
#endif /* HAVE_SS7 */
#ifdef HAVE_OPENR2
   if (p->mfcr2) {
      openr2_calling_party_category_t chancat;
      int callres = 0;
      char *c, *l;
      c = strchr(dest, '/');
      if (c) {
         c++;
      } else {
         c = "";
      }
      if (!p->hidecallerid) {
         l = ast->cid.cid_num;
      } else {
         l = NULL;
      }
      if (strlen(c) < p->stripmsd) {
         ast_log(LOG_WARNING, "Number '%s' is shorter than stripmsd (%d)\n", c, p->stripmsd);
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      p->dialing = 1;
      ast_channel_lock(ast);
      chancat = dahdi_r2_get_channel_category(ast);
      ast_channel_unlock(ast);
      callres = openr2_chan_make_call(p->r2chan, l, (c + p->stripmsd), chancat);
      if (-1 == callres) {
         ast_mutex_unlock(&p->lock);
         ast_log(LOG_ERROR, "unable to make new MFC/R2 call!\n");
         return -1;
      }
      ast_setstate(ast, AST_STATE_DIALING);
   }
#endif /* HAVE_OPENR2 */
#ifdef HAVE_PRI
   if (p->pri) {
      struct pri_sr *sr;
#ifdef SUPPORT_USERUSER
      const char *useruser;
#endif
      int pridialplan;
      int dp_strip;
      int prilocaldialplan;
      int ldp_strip;
      int exclusive;
      const char *rr_str;
      int redirect_reason;
      c = strchr(dest, '/');
      if (c) {
         c++;
      } else {
         c = "";
      }
      l = NULL;
      n = NULL;
      if (!p->hidecallerid) {
         l = ast->cid.cid_num;
         if (!p->hidecalleridname) {
            n = ast->cid.cid_name;
         }
      }
      if (strlen(c) < p->stripmsd) {
         ast_log(LOG_WARNING, "Number '%s' is shorter than stripmsd (%d)\n", c, p->stripmsd);
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      if (mysig != SIG_FXSKS) {
         p->dop.op = DAHDI_DIAL_OP_REPLACE;
         s = strchr(c + p->stripmsd, 'w');
         if (s) {
            if (strlen(s) > 1)
               snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "T%s", s);
            else
               p->dop.dialstr[0] = '\0';
            *s = '\0';
         } else {
            p->dop.dialstr[0] = '\0';
         }
      }
      if (pri_grab(p, p->pri)) {
         ast_log(LOG_WARNING, "Failed to grab PRI!\n");
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      if (!(p->call = pri_new_call(p->pri->pri))) {
         ast_log(LOG_WARNING, "Unable to create call on channel %d\n", p->channel);
         pri_rel(p->pri);
         ast_mutex_unlock(&p->lock);
         return -1;
      }
      if (!(sr = pri_sr_new())) {
         ast_log(LOG_WARNING, "Failed to allocate setup request channel %d\n", p->channel);
         pri_rel(p->pri);
         ast_mutex_unlock(&p->lock);
      }
      if (p->bearer || (mysig == SIG_FXSKS)) {
         if (p->bearer) {
            ast_debug(1, "Oooh, I have a bearer on %d (%d:%d)\n", PVT_TO_CHANNEL(p->bearer), p->bearer->logicalspan, p->bearer->channel);
            p->bearer->call = p->call;
         } else
            ast_debug(1, "I'm being setup with no bearer right now...\n");
         pri_set_crv(p->pri->pri, p->call, p->channel, 0);
      }
      p->digital = IS_DIGITAL(ast->transfercapability);
      /* Should the picked channel be used exclusively? */
      if (p->priexclusive || p->pri->nodetype == PRI_NETWORK) {
         exclusive = 1;
      } else {
         exclusive = 0;
      }
      pri_sr_set_channel(sr, p->bearer ? PVT_TO_CHANNEL(p->bearer) : PVT_TO_CHANNEL(p), exclusive, 1);
      pri_sr_set_bearer(sr, p->digital ? PRI_TRANS_CAP_DIGITAL : ast->transfercapability,
         (p->digital ? -1 :
            ((p->law == DAHDI_LAW_ALAW) ? PRI_LAYER_1_ALAW : PRI_LAYER_1_ULAW)));
      if (p->pri->facilityenable)
         pri_facility_enable(p->pri->pri);
      ast_verb(3, "Requested transfer capability: 0x%.2x - %s\n", ast->transfercapability, ast_transfercapability2str(ast->transfercapability));
      dp_strip = 0;
      pridialplan = p->pri->dialplan - 1;
      if (pridialplan == -2 || pridialplan == -3) { /* compute dynamically */
         if (strncmp(c + p->stripmsd, p->pri->internationalprefix, strlen(p->pri->internationalprefix)) == 0) {
            if (pridialplan == -2) {
               dp_strip = strlen(p->pri->internationalprefix);
            }
            pridialplan = PRI_INTERNATIONAL_ISDN;
         } else if (strncmp(c + p->stripmsd, p->pri->nationalprefix, strlen(p->pri->nationalprefix)) == 0) {
            if (pridialplan == -2) {
               dp_strip = strlen(p->pri->nationalprefix);
            }
            pridialplan = PRI_NATIONAL_ISDN;
         } else {
            pridialplan = PRI_LOCAL_ISDN;
         }
      }
      while (c[p->stripmsd] > '9' && c[p->stripmsd] != '*' && c[p->stripmsd] != '#') {
         switch (c[p->stripmsd]) {
         case 'U':
            pridialplan = (PRI_TON_UNKNOWN << 4) | (pridialplan & 0xf);
            break;
         case 'I':
            pridialplan = (PRI_TON_INTERNATIONAL << 4) | (pridialplan & 0xf);
            break;
         case 'N':
            pridialplan = (PRI_TON_NATIONAL << 4) | (pridialplan & 0xf);
            break;
         case 'L':
            pridialplan = (PRI_TON_NET_SPECIFIC << 4) | (pridialplan & 0xf);
            break;
         case 'S':
            pridialplan = (PRI_TON_SUBSCRIBER << 4) | (pridialplan & 0xf);
            break;
         case 'V':
            pridialplan = (PRI_TON_ABBREVIATED << 4) | (pridialplan & 0xf);
            break;
         case 'R':
            pridialplan = (PRI_TON_RESERVED << 4) | (pridialplan & 0xf);
            break;
         case 'u':
            pridialplan = PRI_NPI_UNKNOWN | (pridialplan & 0xf0);
            break;
         case 'e':
            pridialplan = PRI_NPI_E163_E164 | (pridialplan & 0xf0);
            break;
         case 'x':
            pridialplan = PRI_NPI_X121 | (pridialplan & 0xf0);
            break;
         case 'f':
            pridialplan = PRI_NPI_F69 | (pridialplan & 0xf0);
            break;
         case 'n':
            pridialplan = PRI_NPI_NATIONAL | (pridialplan & 0xf0);
            break;
         case 'p':
            pridialplan = PRI_NPI_PRIVATE | (pridialplan & 0xf0);
            break;
         case 'r':
            pridialplan = PRI_NPI_RESERVED | (pridialplan & 0xf0);
            break;
         default:
            if (isalpha(c[p->stripmsd])) {
               ast_log(LOG_WARNING, "Unrecognized pridialplan %s modifier: %c\n",
                  c[p->stripmsd] > 'Z' ? "NPI" : "TON", c[p->stripmsd]);
            }
            break;
         }
         c++;
      }
      pri_sr_set_called(sr, c + p->stripmsd + dp_strip, pridialplan, s ? 1 : 0);
      ldp_strip = 0;
      prilocaldialplan = p->pri->localdialplan - 1;
      if ((l != NULL) && (prilocaldialplan == -2 || prilocaldialplan == -3)) { /* compute dynamically */
         if (strncmp(l, p->pri->internationalprefix, strlen(p->pri->internationalprefix)) == 0) {
            if (prilocaldialplan == -2) {
               ldp_strip = strlen(p->pri->internationalprefix);
            }
            prilocaldialplan = PRI_INTERNATIONAL_ISDN;
         } else if (strncmp(l, p->pri->nationalprefix, strlen(p->pri->nationalprefix)) == 0) {
            if (prilocaldialplan == -2) {
               ldp_strip = strlen(p->pri->nationalprefix);
            }
            prilocaldialplan = PRI_NATIONAL_ISDN;
         } else {
            prilocaldialplan = PRI_LOCAL_ISDN;
         }
      }
      if (l != NULL) {
         while (*l > '9' && *l != '*' && *l != '#') {
            switch (*l) {
            case 'U':
               prilocaldialplan = (PRI_TON_UNKNOWN << 4) | (prilocaldialplan & 0xf);
               break;
            case 'I':
               prilocaldialplan = (PRI_TON_INTERNATIONAL << 4) | (prilocaldialplan & 0xf);
               break;
            case 'N':
               prilocaldialplan = (PRI_TON_NATIONAL << 4) | (prilocaldialplan & 0xf);
               break;
            case 'L':
               prilocaldialplan = (PRI_TON_NET_SPECIFIC << 4) | (prilocaldialplan & 0xf);
               break;
            case 'S':
               prilocaldialplan = (PRI_TON_SUBSCRIBER << 4) | (prilocaldialplan & 0xf);
               break;
            case 'V':
               prilocaldialplan = (PRI_TON_ABBREVIATED << 4) | (prilocaldialplan & 0xf);
               break;
            case 'R':
               prilocaldialplan = (PRI_TON_RESERVED << 4) | (prilocaldialplan & 0xf);
               break;
            case 'u':
               prilocaldialplan = PRI_NPI_UNKNOWN | (prilocaldialplan & 0xf0);
               break;
            case 'e':
               prilocaldialplan = PRI_NPI_E163_E164 | (prilocaldialplan & 0xf0);
               break;
            case 'x':
               prilocaldialplan = PRI_NPI_X121 | (prilocaldialplan & 0xf0);
               break;
            case 'f':
               prilocaldialplan = PRI_NPI_F69 | (prilocaldialplan & 0xf0);
               break;
            case 'n':
               prilocaldialplan = PRI_NPI_NATIONAL | (prilocaldialplan & 0xf0);
               break;
            case 'p':
               prilocaldialplan = PRI_NPI_PRIVATE | (prilocaldialplan & 0xf0);
               break;
            case 'r':
               prilocaldialplan = PRI_NPI_RESERVED | (prilocaldialplan & 0xf0);
               break;
            default:
               if (isalpha(*l)) {
                  ast_log(LOG_WARNING,
                     "Unrecognized prilocaldialplan %s modifier: %c\n",
                     *l > 'Z' ? "NPI" : "TON", *l);
               }
               break;
            }
            l++;
         }
      }
      pri_sr_set_caller(sr, l ? (l + ldp_strip) : NULL, n, prilocaldialplan,
         p->use_callingpres ? ast->cid.cid_pres : (l ? PRES_ALLOWED_USER_NUMBER_PASSED_SCREEN : PRES_NUMBER_NOT_AVAILABLE));
      if ((rr_str = pbx_builtin_getvar_helper(ast, "PRIREDIRECTREASON"))) {
         if (!strcasecmp(rr_str, "UNKNOWN"))
            redirect_reason = 0;
         else if (!strcasecmp(rr_str, "BUSY"))
            redirect_reason = 1;
         else if (!strcasecmp(rr_str, "NO_REPLY") || !strcasecmp(rr_str, "NOANSWER"))
         /* the NOANSWER is to match diversion-reason from chan_sip, (which never reads PRIREDIRECTREASON) */
            redirect_reason = 2;
         else if (!strcasecmp(rr_str, "UNCONDITIONAL"))
            redirect_reason = 15;
         else
            redirect_reason = PRI_REDIR_UNCONDITIONAL;
      } else
         redirect_reason = PRI_REDIR_UNCONDITIONAL;
      pri_sr_set_redirecting(sr, ast->cid.cid_rdnis, p->pri->localdialplan - 1, PRES_ALLOWED_USER_NUMBER_PASSED_SCREEN, redirect_reason);
#ifdef SUPPORT_USERUSER
      /* User-user info */
      useruser = pbx_builtin_getvar_helper(p->owner, "USERUSERINFO");
      if (useruser)
         pri_sr_set_useruser(sr, useruser);
#endif
      if (pri_setup(p->pri->pri, p->call, sr)) {
         ast_log(LOG_WARNING, "Unable to setup call to %s (using %s)\n",
            c + p->stripmsd + dp_strip, dialplan2str(p->pri->dialplan));
         pri_rel(p->pri);
         ast_mutex_unlock(&p->lock);
         pri_sr_free(sr);
         return -1;
      }
      pri_sr_free(sr);
      ast_setstate(ast, AST_STATE_DIALING);
      pri_rel(p->pri);
   }
#endif
   ast_mutex_unlock(&p->lock);
   return 0;
}
static int dahdi_callwait (struct ast_channel * ast) [static]
Definition at line 3059 of file chan_dahdi.c.
References ast_free, ast_gen_cas(), AST_LAW, ast_log(), ast_malloc, dahdi_pvt::callwaitcas, CALLWAITING_REPEAT_SAMPLES, dahdi_pvt::callwaitingcallerid, dahdi_pvt::callwaitingrepeat, dahdi_pvt::callwaitrings, dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, LOG_WARNING, READ_SIZE, save_conference(), send_callerid(), and ast_channel::tech_pvt.
Referenced by dahdi_call(), and dahdi_read().
{
   struct dahdi_pvt *p = ast->tech_pvt;
   p->callwaitingrepeat = CALLWAITING_REPEAT_SAMPLES;
   if (p->cidspill) {
      ast_log(LOG_WARNING, "Spill already exists?!?\n");
      ast_free(p->cidspill);
   }
   if (!(p->cidspill = ast_malloc(2400 /* SAS */ + 680 /* CAS */ + READ_SIZE * 4)))
      return -1;
   save_conference(p);
   /* Silence */
   memset(p->cidspill, 0x7f, 2400 + 600 + READ_SIZE * 4);
   if (!p->callwaitrings && p->callwaitingcallerid) {
      ast_gen_cas(p->cidspill, 1, 2400 + 680, AST_LAW(p));
      p->callwaitcas = 1;
      p->cidlen = 2400 + 680 + READ_SIZE * 4;
   } else {
      ast_gen_cas(p->cidspill, 1, 2400, AST_LAW(p));
      p->callwaitcas = 0;
      p->cidlen = 2400 + READ_SIZE * 4;
   }
   p->cidpos = 0;
   send_callerid(p);
   return 0;
}
static struct dahdi_chan_conf dahdi_chan_conf_default (void) [static, read]
returns a new dahdi_chan_conf with default values (by-value)
Definition at line 1266 of file chan_dahdi.c.
References CID_SIG_BELL, CID_START_RING, DAHDI_CHAN_MAPPING_PHYSICAL, and DEFAULT_CIDRINGS.
Referenced by process_dahdi(), and setup_dahdi().
{
   /* recall that if a field is not included here it is initialized
    * to 0 or equivalent
    */
   struct dahdi_chan_conf conf = {
#ifdef HAVE_PRI
      .pri = {
         .nsf = PRI_NSF_NONE,
         .switchtype = PRI_SWITCH_NI2,
         .dialplan = PRI_UNKNOWN + 1,
         .localdialplan = PRI_NATIONAL_ISDN + 1,
         .nodetype = PRI_CPE,
         .qsigchannelmapping = DAHDI_CHAN_MAPPING_PHYSICAL,
         .minunused = 2,
         .idleext = "",
         .idledial = "",
         .internationalprefix = "",
         .nationalprefix = "",
         .localprefix = "",
         .privateprefix = "",
         .unknownprefix = "",
         .resetinterval = -1,
      },
#endif
#ifdef HAVE_SS7
      .ss7 = {
         .called_nai = SS7_NAI_NATIONAL,
         .calling_nai = SS7_NAI_NATIONAL,
         .internationalprefix = "",
         .nationalprefix = "",
         .subscriberprefix = "",
         .unknownprefix = ""
      },
#endif
#ifdef HAVE_OPENR2
      .mfcr2 = {
         .variant = OR2_VAR_ITU,
         .mfback_timeout = -1,
         .metering_pulse_timeout = -1,
         .max_ani = 10,
         .max_dnis = 4,
         .get_ani_first = -1,
#if defined(OR2_LIB_INTERFACE) && OR2_LIB_INTERFACE > 1
         .skip_category_request = -1,
#endif
         .call_files = 0,
         .allow_collect_calls = 0,
         .charge_calls = 1,
         .accept_on_offer = 1,
         .forced_release = 0,
         .double_answer = 0,
         .immediate_accept = -1,
         .logdir = "",
         .r2proto_file = "",
         .loglevel = OR2_LOG_ERROR | OR2_LOG_WARNING,
         .category = OR2_CALLING_PARTY_CATEGORY_NATIONAL_SUBSCRIBER
      },
#endif
      .chan = {
         .context = "default",
         .cid_num = "",
         .cid_name = "",
         .mohinterpret = "default",
         .mohsuggest = "",
         .parkinglot = "",
         .transfertobusy = 1,
         .cid_signalling = CID_SIG_BELL,
         .cid_start = CID_START_RING,
         .dahditrcallerid = 0,
         .use_callerid = 1,
         .sig = -1,
         .outsigmod = -1,
         .cid_rxgain = +5.0,
         .tonezone = -1,
         .echocancel.head.tap_length = 1,
         .busycount = 3,
         .accountcode = "",
         .mailbox = "",
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
         .mwisend_fsk = 1,
#endif
         .polarityonanswerdelay = 600,
         .sendcalleridafter = DEFAULT_CIDRINGS,
         .buf_policy = DAHDI_POLICY_IMMEDIATE,
         .buf_no = numbufs,
         .usefaxbuffers = 0,
         .faxbuf_policy = DAHDI_POLICY_IMMEDIATE,
         .faxbuf_no = numbufs,
      },
      .timing = {
         .prewinktime = -1,
         .preflashtime = -1,
         .winktime = -1,
         .flashtime = -1,
         .starttime = -1,
         .rxwinktime = -1,
         .rxflashtime = -1,
         .debouncetime = -1
      },
      .is_sig_auto = 1,
      .smdi_port = "/dev/ttyS0",
   };
   return conf;
}
static void dahdi_close (int fd) [static]
Definition at line 2137 of file chan_dahdi.c.
Referenced by dahdi_close_sub().
{
   if (fd > 0)
      close(fd);
}
static void dahdi_close_sub (struct dahdi_pvt * chan_pvt, int sub_num) [static]
Definition at line 2143 of file chan_dahdi.c.
References dahdi_close(), dahdi_subchannel::dfd, and dahdi_pvt::subs.
Referenced by alloc_sub(), destroy_dahdi_pvt(), and unalloc_sub().
{
   dahdi_close(chan_pvt->subs[sub_num].dfd);
   chan_pvt->subs[sub_num].dfd = -1;
}
static int dahdi_confmute (struct dahdi_pvt * p, int muted) [inline, static]
Definition at line 2880 of file chan_dahdi.c.
References ast_log(), dahdi_pvt::channel, dahdi_subchannel::dfd, errno, LOG_WARNING, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, SIG_SS7, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_handle_dtmfup(), dahdi_handle_event(), dahdi_hangup(), dahdi_new(), and dahdi_read().
{
   int x, y, res;
   x = muted;
   if ((p->sig == SIG_PRI) || (p->sig == SIG_SS7) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) {
      y = 1;
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_AUDIOMODE, &y);
      if (res)
         ast_log(LOG_WARNING, "Unable to set audio mode on %d: %s\n", p->channel, strerror(errno));
   }
   res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_CONFMUTE, &x);
   if (res < 0)
      ast_log(LOG_WARNING, "DAHDI confmute(%d) failed on channel %d: %s\n", muted, p->channel, strerror(errno));
   return res;
}
static char* dahdi_destroy_channel (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14287 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_destroy_channel_bynum(), RESULT_SUCCESS, and ast_cli_entry::usage.
14288 {
14289    int channel;
14290    int ret;
14291    switch (cmd) {
14292    case CLI_INIT:
14293       e->command = "dahdi destroy channel";
14294       e->usage =
14295          "Usage: dahdi destroy channel <chan num>\n"
14296          "  DON'T USE THIS UNLESS YOU KNOW WHAT YOU ARE DOING.  Immediately removes a given channel, whether it is in use or not\n";
14297       return NULL;
14298    case CLI_GENERATE:
14299       return NULL;
14300    }
14301    if (a->argc != 4)
14302       return CLI_SHOWUSAGE;
14303
14304    channel = atoi(a->argv[3]);
14305    ret = dahdi_destroy_channel_bynum(channel);
14306    return (RESULT_SUCCESS == ret) ? CLI_SUCCESS : CLI_FAILURE;
14307 }
static int dahdi_destroy_channel_bynum (int channel) [static]
Definition at line 9249 of file chan_dahdi.c.
References ast_module_unref(), dahdi_pvt::channel, destroy_channel(), dahdi_subchannel::dfd, iflist, dahdi_pvt::next, dahdi_pvt::prev, RESULT_FAILURE, RESULT_SUCCESS, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_destroy_channel(), and do_monitor().
{
   struct dahdi_pvt *tmp = NULL;
   struct dahdi_pvt *prev = NULL;
   tmp = iflist;
   while (tmp) {
      if (tmp->channel == channel) {
         int x = DAHDI_FLASH;
         ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_HOOK, &x); /* important to create an event for dahdi_wait_event to register so that all ss_threads terminate */
         destroy_channel(prev, tmp, 1);
         ast_module_unref(ast_module_info->self);
         return RESULT_SUCCESS;
      }
      prev = tmp;
      tmp = tmp->next;
   }
   return RESULT_FAILURE;
}
static int dahdi_digit_begin (struct ast_channel * ast, char digit) [static]
Definition at line 2245 of file chan_dahdi.c.
References ast_channel::_state, ast_debug, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), AST_STATE_DIALING, dahdi_pvt::begindigit, dahdi_get_index(), dahdi_subchannel::dfd, dahdi_pvt::dialdest, dahdi_pvt::dialing, digit_to_dtmfindex(), errno, dahdi_pvt::lock, LOG_WARNING, dahdi_pvt::owner, dahdi_pvt::pulse, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, dahdi_pvt::span, SUB_REAL, dahdi_pvt::subs, and ast_channel::tech_pvt.
{
   struct dahdi_pvt *pvt;
   int idx;
   int dtmf = -1;
   pvt = chan->tech_pvt;
   ast_mutex_lock(&pvt->lock);
   idx = dahdi_get_index(chan, pvt, 0);
   if ((idx != SUB_REAL) || !pvt->owner)
      goto out;
#ifdef HAVE_PRI
   if (((pvt->sig == SIG_PRI) || (pvt->sig == SIG_BRI) || (pvt->sig == SIG_BRI_PTMP))
         && (chan->_state == AST_STATE_DIALING) && !pvt->proceeding) {
      if (pvt->setup_ack) {
         if (!pri_grab(pvt, pvt->pri)) {
            pri_information(pvt->pri->pri, pvt->call, digit);
            pri_rel(pvt->pri);
         } else
            ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", pvt->span);
      } else if (strlen(pvt->dialdest) < sizeof(pvt->dialdest) - 1) {
         int res;
         ast_debug(1, "Queueing digit '%c' since setup_ack not yet received\n", digit);
         res = strlen(pvt->dialdest);
         pvt->dialdest[res++] = digit;
         pvt->dialdest[res] = '\0';
      }
      goto out;
   }
#endif
   if ((dtmf = digit_to_dtmfindex(digit)) == -1)
      goto out;
   if (pvt->pulse || ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_SENDTONE, &dtmf)) {
      int res;
      struct dahdi_dialoperation zo = {
         .op = DAHDI_DIAL_OP_APPEND,
      };
      zo.dialstr[0] = 'T';
      zo.dialstr[1] = digit;
      zo.dialstr[2] = '\0';
      if ((res = ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_DIAL, &zo)))
         ast_log(LOG_WARNING, "Couldn't dial digit %c: %s\n", digit, strerror(errno));
      else
         pvt->dialing = 1;
   } else {
      ast_debug(1, "Started VLDTMF digit '%c'\n", digit);
      pvt->dialing = 1;
      pvt->begindigit = digit;
   }
out:
   ast_mutex_unlock(&pvt->lock);
   return 0;
}
static int dahdi_digit_end (struct ast_channel * ast, char digit, unsigned int duration) [static]
Definition at line 2307 of file chan_dahdi.c.
References ast_debug, ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::begindigit, dahdi_get_index(), dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::lock, dahdi_pvt::owner, dahdi_pvt::pulse, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, SUB_REAL, dahdi_pvt::subs, and ast_channel::tech_pvt.
{
   struct dahdi_pvt *pvt;
   int res = 0;
   int idx;
   int x;
   pvt = chan->tech_pvt;
   ast_mutex_lock(&pvt->lock);
   idx = dahdi_get_index(chan, pvt, 0);
   if ((idx != SUB_REAL) || !pvt->owner || pvt->pulse)
      goto out;
#ifdef HAVE_PRI
   /* This means that the digit was already sent via PRI signalling */
   if (((pvt->sig == SIG_PRI) || (pvt->sig == SIG_BRI) || (pvt->sig == SIG_BRI_PTMP))
         && !pvt->begindigit)
      goto out;
#endif
   if (pvt->begindigit) {
      x = -1;
      ast_debug(1, "Ending VLDTMF digit '%c'\n", digit);
      res = ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_SENDTONE, &x);
      pvt->dialing = 0;
      pvt->begindigit = 0;
   }
out:
   ast_mutex_unlock(&pvt->lock);
   return res;
}
static void dahdi_disable_ec (struct dahdi_pvt * p) [static]
Definition at line 2709 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::channel, dahdi_subchannel::dfd, dahdi_pvt::echocanon, errno, LOG_WARNING, SUB_REAL, and dahdi_pvt::subs.
Referenced by __dahdi_exception(), dahdi_bridge(), dahdi_handle_event(), dahdi_hangup(), dahdi_setoption(), and handle_init_event().
{
   int res;
   if (p->echocanon) {
      struct dahdi_echocanparams ecp = { .tap_length = 0 };
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_ECHOCANCEL_PARAMS, &ecp);
      if (res)
         ast_log(LOG_WARNING, "Unable to disable echo cancellation on channel %d: %s\n", p->channel, strerror(errno));
      else
         ast_debug(1, "Disabled echo cancellation on channel %d\n", p->channel);
   }
   p->echocanon = 0;
}
static void dahdi_dnd (struct dahdi_pvt * dahdichan, int on) [static]
enable or disable the chan_dahdi Do-Not-Disturb mode for a DAHDI channel
Parameters:
dahdichan "Physical" DAHDI channel (e.g: DAHDI/5)
on 1 to enable, 0 to disable
chan_dahdi has a DND (Do Not Disturb) mode for each dahdichan (physical DAHDI channel). Use this to enable or disable it.
Bug:
the use of the word "channel" for those dahdichans is really confusing.
Definition at line 7662 of file chan_dahdi.c.
References ast_verb, dahdi_pvt::channel, dahdi_pvt::dnd, EVENT_FLAG_SYSTEM, and manager_event.
Referenced by dahdi_set_dnd(), and ss_thread().
{
   /* Do not disturb */
   dahdichan->dnd = on;
   ast_verb(3, "%s DND on channel %d\n",
         on? "Enabled" : "Disabled",
         dahdichan->channel);
   manager_event(EVENT_FLAG_SYSTEM, "DNDState",
         "Channel: DAHDI/%d\r\n"
         "Status: %s\r\n", dahdichan->channel,
         on? "enabled" : "disabled");
}
static void dahdi_enable_ec (struct dahdi_pvt * p) [static]
Definition at line 2660 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::channel, dahdi_subchannel::dfd, dahdi_pvt::digital, dahdi_pvt::echocancel, dahdi_pvt::echocanon, errno, dahdi_pvt::head, LOG_WARNING, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, SIG_SS7, SUB_REAL, and dahdi_pvt::subs.
Referenced by __dahdi_exception(), dahdi_answer(), dahdi_bridge(), dahdi_handle_event(), dahdi_indicate(), dahdi_setoption(), handle_init_event(), and ss_thread().
{
   int x;
   int res;
   if (!p)
      return;
   if (p->echocanon) {
      ast_debug(1, "Echo cancellation already on\n");
      return;
   }
   if (p->digital) {
      ast_debug(1, "Echo cancellation isn't required on digital connection\n");
      return;
   }
   if (p->echocancel.head.tap_length) {
      if ((p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP) || (p->sig == SIG_PRI) || (p->sig == SIG_SS7)) {
         x = 1;
         res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_AUDIOMODE, &x);
         if (res)
            ast_log(LOG_WARNING, "Unable to enable audio mode on channel %d (%s)\n", p->channel, strerror(errno));
      }
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_ECHOCANCEL_PARAMS, &p->echocancel);
      if (res) {
         ast_log(LOG_WARNING, "Unable to enable echo cancellation on channel %d (%s)\n", p->channel, strerror(errno));
      } else {
         p->echocanon = 1;
         ast_debug(1, "Enabled echo cancellation on channel %d\n", p->channel);
      }
   } else
      ast_debug(1, "No echo cancellation requested\n");
}
static struct ast_frame * dahdi_exception (struct ast_channel * ast) [static, read]
Definition at line 6707 of file chan_dahdi.c.
References __dahdi_exception(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::lock, and ast_channel::tech_pvt.
{
   struct dahdi_pvt *p = ast->tech_pvt;
   struct ast_frame *f;
   ast_mutex_lock(&p->lock);
   f = __dahdi_exception(ast);
   ast_mutex_unlock(&p->lock);
   return f;
}
static int dahdi_fake_event (struct dahdi_pvt * p, int mode) [static]
Definition at line 15185 of file chan_dahdi.c.
References ast_log(), dahdi_pvt::fake_event, HANGUP, LOG_WARNING, dahdi_pvt::owner, and TRANSFER.
Referenced by action_transfer(), and action_transferhangup().
15186 {
15187    if (p) {
15188       switch (mode) {
15189          case TRANSFER:
15190             p->fake_event = DAHDI_EVENT_WINKFLASH;
15191             break;
15192          case HANGUP:
15193             p->fake_event = DAHDI_EVENT_ONHOOK;
15194             break;
15195          default:
15196             ast_log(LOG_WARNING, "I don't know how to handle transfer event with this: %d on channel %s\n",mode, p->owner->name);
15197       }
15198    }
15199    return 0;
15200 }
static int dahdi_fixup (struct ast_channel * oldchan, struct ast_channel * newchan) [static]
Definition at line 5448 of file chan_dahdi.c.
References ast_channel::_state, AST_CONTROL_RINGING, ast_debug, ast_mutex_lock(), ast_mutex_unlock(), AST_STATE_RINGING, dahdi_pvt::channel, dahdi_indicate(), dahdi_unlink(), dahdi_pvt::lock, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::subs, ast_channel::tech_pvt, and update_conf().
{
   struct dahdi_pvt *p = newchan->tech_pvt;
   int x;
   ast_mutex_lock(&p->lock);
   ast_debug(1, "New owner for channel %d is %s\n", p->channel, newchan->name);
   if (p->owner == oldchan) {
      p->owner = newchan;
   }
   for (x = 0; x < 3; x++)
      if (p->subs[x].owner == oldchan) {
         if (!x)
            dahdi_unlink(NULL, p, 0);
         p->subs[x].owner = newchan;
      }
   if (newchan->_state == AST_STATE_RINGING)
      dahdi_indicate(newchan, AST_CONTROL_RINGING, NULL, 0);
   update_conf(p);
   ast_mutex_unlock(&p->lock);
   return 0;
}
static int dahdi_func_read (struct ast_channel * chan, const char * function, char * data, char * buf, size_t len) [static]
Definition at line 5025 of file chan_dahdi.c.
References ast_copy_string(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::lock, dahdi_pvt::rxgain, ast_channel::tech_pvt, and dahdi_pvt::txgain.
{
   struct dahdi_pvt *p = chan->tech_pvt;
   if (!strcasecmp(data, "rxgain")) {
      ast_mutex_lock(&p->lock);
      snprintf(buf, len, "%f", p->rxgain);
      ast_mutex_unlock(&p->lock);
   } else if (!strcasecmp(data, "txgain")) {
      ast_mutex_lock(&p->lock);
      snprintf(buf, len, "%f", p->txgain);
      ast_mutex_unlock(&p->lock);
   } else {
      ast_copy_string(buf, "", len);
   }
   return 0;
}
static int dahdi_get_event (int fd) [inline, static]
Avoid the silly dahdi_getevent which ignores a bunch of events.
Definition at line 376 of file chan_dahdi.c.
Referenced by __dahdi_exception(), dahdi_handle_event(), do_monitor(), mwi_thread(), and ss_thread().
{
   int j;
   if (ioctl(fd, DAHDI_GETEVENT, &j) == -1)
      return -1;
   return j;
}
static int dahdi_get_index (struct ast_channel * ast, struct dahdi_pvt * p, int nullok) [static]
Definition at line 1503 of file chan_dahdi.c.
References ast_log(), LOG_WARNING, dahdi_subchannel::owner, SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, and dahdi_pvt::subs.
Referenced by __dahdi_exception(), dahdi_answer(), dahdi_bridge(), dahdi_call(), dahdi_digit_begin(), dahdi_digit_end(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_read(), dahdi_sendtext(), dahdi_setoption(), dahdi_write(), and ss_thread().
{
   int res;
   if (p->subs[SUB_REAL].owner == ast)
      res = 0;
   else if (p->subs[SUB_CALLWAIT].owner == ast)
      res = 1;
   else if (p->subs[SUB_THREEWAY].owner == ast)
      res = 2;
   else {
      res = -1;
      if (!nullok)
         ast_log(LOG_WARNING, "Unable to get index, and nullok is not asserted\n");
   }
   return res;
}
static void dahdi_handle_dtmfup (struct ast_channel * ast, int idx, struct ast_frame ** dest) [static]
Definition at line 5607 of file chan_dahdi.c.
References ast_async_goto(), ast_channel_lock, ast_channel_unlock, AST_CONTROL_ANSWER, ast_debug, ast_exists_extension(), AST_FRAME_CONTROL, AST_FRAME_NULL, ast_free, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_verb, dahdi_pvt::bufsize, dahdi_pvt::callprogress, CALLPROGRESS_FAX, dahdi_pvt::callwaitcas, ast_channel::cid, ast_callerid::cid_num, dahdi_pvt::cidspill, dahdi_pvt::confirmanswer, ast_channel::context, dahdi_confmute(), dahdi_subchannel::dfd, errno, ast_channel::exten, dahdi_subchannel::f, dahdi_pvt::faxbuf_no, dahdi_pvt::faxbuf_policy, dahdi_pvt::faxbuffersinuse, dahdi_pvt::faxhandled, ast_frame::frametype, dahdi_pvt::lock, LOG_NOTICE, LOG_WARNING, ast_channel::macrocontext, pbx_builtin_setvar_helper(), S_OR, send_cwcidspill(), ast_frame::subclass, dahdi_pvt::subs, ast_channel::tech_pvt, and dahdi_pvt::usefaxbuffers.
Referenced by dahdi_handle_event(), and dahdi_read().
{
   struct dahdi_pvt *p = ast->tech_pvt;
   struct ast_frame *f = *dest;
   ast_debug(1, "DTMF digit: %c on %s\n", f->subclass, ast->name);
   if (p->confirmanswer) {
      ast_debug(1, "Confirm answer on %s!\n", ast->name);
      /* Upon receiving a DTMF digit, consider this an answer confirmation instead
         of a DTMF digit */
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
      *dest = &p->subs[idx].f;
      /* Reset confirmanswer so DTMF's will behave properly for the duration of the call */
      p->confirmanswer = 0;
   } else if (p->callwaitcas) {
      if ((f->subclass == 'A') || (f->subclass == 'D')) {
         ast_debug(1, "Got some DTMF, but it's for the CAS\n");
         if (p->cidspill)
            ast_free(p->cidspill);
         send_cwcidspill(p);
      }
      p->callwaitcas = 0;
      p->subs[idx].f.frametype = AST_FRAME_NULL;
      p->subs[idx].f.subclass = 0;
      *dest = &p->subs[idx].f;
   } else if (f->subclass == 'f') {
      /* Fax tone -- Handle and return NULL */
      if ((p->callprogress & CALLPROGRESS_FAX) && !p->faxhandled) {
         /* If faxbuffers are configured, use them for the fax transmission */
         if (p->usefaxbuffers && !p->faxbuffersinuse) {
            struct dahdi_bufferinfo bi = {
               .txbufpolicy = p->faxbuf_policy,
               .bufsize = p->bufsize,
               .numbufs = p->faxbuf_no
            };
            int res;
            if ((res = ioctl(p->subs[idx].dfd, DAHDI_SET_BUFINFO, &bi)) < 0) {
               ast_log(LOG_WARNING, "Channel '%s' unable to set faxbuffer policy, reason: %s\n", ast->name, strerror(errno));
            } else {
               p->faxbuffersinuse = 1;
            }
         }
         p->faxhandled = 1;
         if (strcmp(ast->exten, "fax")) {
            const char *target_context = S_OR(ast->macrocontext, ast->context);
            /* We need to unlock 'ast' here because ast_exists_extension has the
             * potential to start autoservice on the channel. Such action is prone
             * to deadlock.
             */
            ast_mutex_unlock(&p->lock);
            ast_channel_unlock(ast);
            if (ast_exists_extension(ast, target_context, "fax", 1, ast->cid.cid_num)) {
               ast_channel_lock(ast);
               ast_mutex_lock(&p->lock);
               ast_verb(3, "Redirecting %s to fax extension\n", ast->name);
               /* Save the DID/DNIS when we transfer the fax call to a "fax" extension */
               pbx_builtin_setvar_helper(ast, "FAXEXTEN", ast->exten);
               if (ast_async_goto(ast, target_context, "fax", 1))
                  ast_log(LOG_WARNING, "Failed to async goto '%s' into fax of '%s'\n", ast->name, target_context);
            } else {
               ast_channel_lock(ast);
               ast_mutex_lock(&p->lock);
               ast_log(LOG_NOTICE, "Fax detected, but no fax extension\n");
            }
         } else {
            ast_debug(1, "Already in a fax extension, not redirecting\n");
         }
      } else {
         ast_debug(1, "Fax already handled\n");
      }
      dahdi_confmute(p, 0);
      p->subs[idx].f.frametype = AST_FRAME_NULL;
      p->subs[idx].f.subclass = 0;
      *dest = &p->subs[idx].f;
   }
}
static struct ast_frame* dahdi_handle_event (struct ast_channel * ast) [static, read]
< Digits (or equivalent) have been dialed
< Remote end is ringing
< Line is up
< Line is ringing
< Channel is down and available
< Channel is down, but reserved
< Channel is off hook
< Line is busy
< Digits (or equivalent) have been dialed while offhook
< Channel has detected an incoming call and is waiting for ring
< Digits (or equivalent) have been dialed
< Remote end is ringing
< Line is up
< Line is ringing
Definition at line 5699 of file chan_dahdi.c.
References ast_channel::_softhangup, ast_channel::_state, alloc_sub(), dahdi_pvt::answeronpolarityswitch, ast_bridged_channel(), AST_CAUSE_NO_ANSWER, ast_channel_trylock, ast_channel_unlock, AST_CONTROL_ANSWER, AST_CONTROL_HOLD, AST_CONTROL_OFFHOOK, AST_CONTROL_RADIO_KEY, AST_CONTROL_RADIO_UNKEY, AST_CONTROL_RING, AST_CONTROL_RINGING, AST_CONTROL_UNHOLD, ast_copy_string(), ast_debug, AST_FRAME_CONTROL, AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_NULL, ast_free, ast_hangup(), ast_log(), ast_pthread_create_detached, ast_queue_control(), ast_queue_control_data(), ast_queue_hangup_with_cause(), ast_setstate(), ast_softhangup(), AST_SOFTHANGUP_DEV, AST_SOFTHANGUP_EXPLICIT, AST_STATE_BUSY, AST_STATE_DIALING, AST_STATE_DIALING_OFFHOOK, AST_STATE_DOWN, AST_STATE_OFFHOOK, AST_STATE_PRERING, AST_STATE_RESERVED, AST_STATE_RING, AST_STATE_RINGING, AST_STATE_UP, ast_strdup, ast_strlen_zero(), ast_tvdiff_ms(), ast_tvnow(), ast_verb, attempt_transfer(), dahdi_pvt::callprogress, CALLPROGRESS_PROGRESS, dahdi_pvt::callwaitcas, dahdi_pvt::callwaitingrepeat, CANPROGRESSDETECT, ast_channel::cdr, dahdi_pvt::channel, CHANNEL_DEADLOCK_AVOIDANCE, check_for_conference(), ast_channel::cid, ast_callerid::cid_ani, ast_callerid::cid_ani2, dahdi_pvt::cid_name, ast_callerid::cid_name, cid_name, dahdi_pvt::cid_num, ast_callerid::cid_num, cid_num, dahdi_pvt::cidcwexpire, dahdi_pvt::cidrings, dahdi_pvt::cidspill, dahdi_pvt::confirmanswer, dahdi_confmute(), dahdi_disable_ec(), dahdi_enable_ec(), dahdi_get_event(), dahdi_get_index(), dahdi_handle_dtmfup(), dahdi_new(), DAHDI_OVERLAPDIAL_INCOMING, dahdi_ring_phone(), dahdi_set_hook(), dahdi_train_ec(), dahdi_pvt::dahditrcallerid, ast_frame::data, ast_frame::datalen, dahdi_subchannel::dfd, dahdi_pvt::dialdest, dahdi_pvt::dialednone, dahdi_pvt::dialing, DLA_LOCK, DLA_UNLOCK, dahdi_pvt::dop, dahdi_pvt::dsp, dahdi_pvt::echobreak, dahdi_pvt::echocanon, dahdi_pvt::echorest, dahdi_pvt::echotraining, errno, event2str(), EVENT_FLAG_SYSTEM, dahdi_subchannel::f, dahdi_pvt::fake_event, dahdi_pvt::finaldial, dahdi_pvt::flashtime, ast_frame::frametype, dahdi_pvt::fxsoffhookstate, get_alarms(), handle_alarms(), dahdi_pvt::hanguponpolarityswitch, has_voicemail(), dahdi_pvt::inalarm, dahdi_subchannel::inthreeway, dahdi_pvt::lock, LOG_DEBUG, LOG_NOTICE, LOG_WARNING, ast_frame::mallocd, manager_event, MIN_MS_SINCE_FLASH, dahdi_pvt::mohsuggest, dahdi_pvt::msgstate, dahdi_subchannel::needanswer, dahdi_subchannel::needflash, dahdi_subchannel::needhold, dahdi_subchannel::needringing, dahdi_subchannel::needunhold, ast_frame::offset, dahdi_pvt::onhooktime, dahdi_pvt::oprmode, dahdi_pvt::oprpeer, option_debug, dahdi_pvt::origcid_name, dahdi_pvt::origcid_num, dahdi_pvt::outgoing, dahdi_pvt::outsigmod, dahdi_subchannel::owner, dahdi_pvt::owner, ast_channel::pbx, dahdi_pvt::polarity, POLARITY_IDLE, POLARITY_REV, dahdi_pvt::polaritydelaytv, dahdi_pvt::polarityonanswerdelay, ast_frame::ptr, dahdi_pvt::pulsedial, dahdi_pvt::radio, restore_conference(), ast_channel::rings, dahdi_pvt::ringt, dahdi_pvt::ringt_base, S_OR, ast_frame::samples, save_conference(), dahdi_pvt::sig, sig2str, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, SIG_SS7, ast_frame::src, ss_thread(), SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, ast_frame::subclass, dahdi_pvt::subs, swap_subs(), ast_channel::tech_pvt, dahdi_pvt::threewaycalling, dahdi_pvt::transfer, dahdi_pvt::transfertobusy, unalloc_sub(), update_conf(), dahdi_pvt::waitingfordt, and dahdi_pvt::whichwink.
Referenced by __dahdi_exception().
{
   int res, x;
   int idx, mysig;
   char *c;
   struct dahdi_pvt *p = ast->tech_pvt;
   pthread_t threadid;
   struct ast_channel *chan;
   struct ast_frame *f;
   idx = dahdi_get_index(ast, p, 0);
   mysig = p->sig;
   if (p->outsigmod > -1)
      mysig = p->outsigmod;
   p->subs[idx].f.frametype = AST_FRAME_NULL;
   p->subs[idx].f.subclass = 0;
   p->subs[idx].f.datalen = 0;
   p->subs[idx].f.samples = 0;
   p->subs[idx].f.mallocd = 0;
   p->subs[idx].f.offset = 0;
   p->subs[idx].f.src = "dahdi_handle_event";
   p->subs[idx].f.data.ptr = NULL;
   f = &p->subs[idx].f;
   if (idx < 0)
      return &p->subs[idx].f;
   if (p->fake_event) {
      res = p->fake_event;
      p->fake_event = 0;
   } else
      res = dahdi_get_event(p->subs[idx].dfd);
   ast_debug(1, "Got event %s(%d) on channel %d (index %d)\n", event2str(res), res, p->channel, idx);
   if (res & (DAHDI_EVENT_PULSEDIGIT | DAHDI_EVENT_DTMFUP)) {
      p->pulsedial = (res & DAHDI_EVENT_PULSEDIGIT) ? 1 : 0;
      ast_debug(1, "Detected %sdigit '%c'\n", p->pulsedial ? "pulse ": "", res & 0xff);
#ifdef HAVE_PRI
      if (!p->proceeding && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) && p->pri && (p->pri->overlapdial & DAHDI_OVERLAPDIAL_INCOMING)) {
         /* absorb event */
      } else {
#endif
         dahdi_confmute(p, 0);
         p->subs[idx].f.frametype = AST_FRAME_DTMF_END;
         p->subs[idx].f.subclass = res & 0xff;
#ifdef HAVE_PRI
      }
#endif
      dahdi_handle_dtmfup(ast, idx, &f);
      return f;
   }
   if (res & DAHDI_EVENT_DTMFDOWN) {
      ast_debug(1, "DTMF Down '%c'\n", res & 0xff);
      /* Mute conference */
      dahdi_confmute(p, 1);
      p->subs[idx].f.frametype = AST_FRAME_DTMF_BEGIN;
      p->subs[idx].f.subclass = res & 0xff;
      return &p->subs[idx].f;
   }
   switch (res) {
      case DAHDI_EVENT_EC_DISABLED:
         ast_verb(3, "Channel %d echo canceler disabled due to CED detection\n", p->channel);
         p->echocanon = 0;
         break;
      case DAHDI_EVENT_BITSCHANGED:
#ifdef HAVE_OPENR2
         if (p->sig != SIG_MFCR2) {
            ast_log(LOG_WARNING, "Received bits changed on %s signalling?\n", sig2str(p->sig));
         } else {
            ast_log(LOG_DEBUG, "bits changed in chan %d\n", p->channel);
            openr2_chan_handle_cas(p->r2chan);
         }
#else
         ast_log(LOG_WARNING, "Received bits changed on %s signalling?\n", sig2str(p->sig));
#endif
      case DAHDI_EVENT_PULSE_START:
         /* Stop tone if there's a pulse start and the PBX isn't started */
         if (!ast->pbx)
            tone_zone_play_tone(p->subs[idx].dfd, -1);
         break;
      case DAHDI_EVENT_DIALCOMPLETE:
#ifdef HAVE_OPENR2
         if ((p->sig & SIG_MFCR2) && p->r2chan && ast->_state != AST_STATE_UP) {
            /* we don't need to do anything for this event for R2 signaling
               if the call is being setup */
            break;
         }
#endif
         if (p->inalarm) break;
         if ((p->radio || (p->oprmode < 0))) break;
         if (ioctl(p->subs[idx].dfd,DAHDI_DIALING,&x) == -1) {
            ast_log(LOG_DEBUG, "DAHDI_DIALING ioctl failed on %s: %s\n",ast->name, strerror(errno));
            return NULL;
         }
         if (!x) { /* if not still dialing in driver */
            dahdi_enable_ec(p);
            if (p->echobreak) {
               dahdi_train_ec(p);
               ast_copy_string(p->dop.dialstr, p->echorest, sizeof(p->dop.dialstr));
               p->dop.op = DAHDI_DIAL_OP_REPLACE;
               res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop);
               p->echobreak = 0;
            } else {
               p->dialing = 0;
               if ((mysig == SIG_E911) || (mysig == SIG_FGC_CAMA) || (mysig == SIG_FGC_CAMAMF)) {
                  /* if thru with dialing after offhook */
                  if (ast->_state == AST_STATE_DIALING_OFFHOOK) {
                     ast_setstate(ast, AST_STATE_UP);
                     p->subs[idx].f.frametype = AST_FRAME_CONTROL;
                     p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
                     break;
                  } else { /* if to state wait for offhook to dial rest */
                     /* we now wait for off hook */
                     ast_setstate(ast,AST_STATE_DIALING_OFFHOOK);
                  }
               }
               if (ast->_state == AST_STATE_DIALING) {
                  if ((p->callprogress & CALLPROGRESS_PROGRESS) && CANPROGRESSDETECT(p) && p->dsp && p->outgoing) {
                     ast_debug(1, "Done dialing, but waiting for progress detection before doing more...\n");
                  } else if (p->confirmanswer || (!p->dialednone
                     && ((mysig == SIG_EM) || (mysig == SIG_EM_E1)
                        || (mysig == SIG_EMWINK) || (mysig == SIG_FEATD)
                        || (mysig == SIG_FEATDMF_TA) || (mysig == SIG_FEATDMF)
                        || (mysig == SIG_E911) || (mysig == SIG_FGC_CAMA)
                        || (mysig == SIG_FGC_CAMAMF) || (mysig == SIG_FEATB)
                        || (mysig == SIG_SF) || (mysig == SIG_SFWINK)
                        || (mysig == SIG_SF_FEATD) || (mysig == SIG_SF_FEATDMF)
                        || (mysig == SIG_SF_FEATB)))) {
                     ast_setstate(ast, AST_STATE_RINGING);
                  } else if (!p->answeronpolarityswitch) {
                     ast_setstate(ast, AST_STATE_UP);
                     p->subs[idx].f.frametype = AST_FRAME_CONTROL;
                     p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
                     /* If aops=0 and hops=1, this is necessary */
                     p->polarity = POLARITY_REV;
                  } else {
                     /* Start clean, so we can catch the change to REV polarity when party answers */
                     p->polarity = POLARITY_IDLE;
                  }
               }
            }
         }
         break;
      case DAHDI_EVENT_ALARM:
#ifdef HAVE_PRI
         if ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) {
            if (!p->pri || !p->pri->pri || (pri_get_timer(p->pri->pri, PRI_TIMER_T309) < 0)) {
               /* T309 is not enabled : hangup calls when alarm occurs */
               if (p->call) {
                  if (p->pri && p->pri->pri) {
                     if (!pri_grab(p, p->pri)) {
                        pri_hangup(p->pri->pri, p->call, -1);
                        pri_destroycall(p->pri->pri, p->call);
                        p->call = NULL;
                        pri_rel(p->pri);
                     } else
                        ast_log(LOG_WARNING, "Failed to grab PRI!\n");
                  } else
                     ast_log(LOG_WARNING, "The PRI Call has not been destroyed\n");
               }
               if (p->owner)
                  p->owner->_softhangup |= AST_SOFTHANGUP_DEV;
            }
         }
         if (p->bearer)
            p->bearer->inalarm = 1;
         else
#endif
         p->inalarm = 1;
         res = get_alarms(p);
         handle_alarms(p, res);
#ifdef HAVE_PRI
         if (!p->pri || !p->pri->pri || pri_get_timer(p->pri->pri, PRI_TIMER_T309) < 0) {
            /* fall through intentionally */
         } else {
            break;
         }
#endif
#ifdef HAVE_SS7
         if (p->sig == SIG_SS7)
            break;
#endif
#ifdef HAVE_OPENR2
         if (p->sig == SIG_MFCR2)
            break;
#endif
      case DAHDI_EVENT_ONHOOK:
         if (p->radio) {
            p->subs[idx].f.frametype = AST_FRAME_CONTROL;
            p->subs[idx].f.subclass = AST_CONTROL_RADIO_UNKEY;
            break;
         }
         if (p->oprmode < 0)
         {
            if (p->oprmode != -1) break;
            if ((p->sig == SIG_FXOLS) || (p->sig == SIG_FXOKS) || (p->sig == SIG_FXOGS))
            {
               /* Make sure it starts ringing */
               dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_RINGOFF);
               dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_RING);
               save_conference(p->oprpeer);
               tone_zone_play_tone(p->oprpeer->subs[SUB_REAL].dfd, DAHDI_TONE_RINGTONE);
            }
            break;
         }
         switch (p->sig) {
         case SIG_FXOLS:
         case SIG_FXOGS:
         case SIG_FXOKS:
            p->onhooktime = time(NULL);
            p->fxsoffhookstate = 0;
            p->msgstate = -1;
            /* Check for some special conditions regarding call waiting */
            if (idx == SUB_REAL) {
               /* The normal line was hung up */
               if (p->subs[SUB_CALLWAIT].owner) {
                  /* There's a call waiting call, so ring the phone, but make it unowned in the mean time */
                  swap_subs(p, SUB_CALLWAIT, SUB_REAL);
                  ast_verb(3, "Channel %d still has (callwait) call, ringing phone\n", p->channel);
                  unalloc_sub(p, SUB_CALLWAIT);
#if 0
                  p->subs[idx].needanswer = 0;
                  p->subs[idx].needringing = 0;
#endif
                  p->callwaitingrepeat = 0;
                  p->cidcwexpire = 0;
                  p->owner = NULL;
                  /* Don't start streaming audio yet if the incoming call isn't up yet */
                  if (p->subs[SUB_REAL].owner->_state != AST_STATE_UP)
                     p->dialing = 1;
                  dahdi_ring_phone(p);
               } else if (p->subs[SUB_THREEWAY].owner) {
                  unsigned int mssinceflash;
                  /* Here we have to retain the lock on both the main channel, the 3-way channel, and
                     the private structure -- not especially easy or clean */
                  while (p->subs[SUB_THREEWAY].owner && ast_channel_trylock(p->subs[SUB_THREEWAY].owner)) {
                     /* Yuck, didn't get the lock on the 3-way, gotta release everything and re-grab! */
                     DLA_UNLOCK(&p->lock);
                     CHANNEL_DEADLOCK_AVOIDANCE(ast);
                     /* We can grab ast and p in that order, without worry.  We should make sure
                        nothing seriously bad has happened though like some sort of bizarre double
                        masquerade! */
                     DLA_LOCK(&p->lock);
                     if (p->owner != ast) {
                        ast_log(LOG_WARNING, "This isn't good...\n");
                        return NULL;
                     }
                  }
                  if (!p->subs[SUB_THREEWAY].owner) {
                     ast_log(LOG_NOTICE, "Whoa, threeway disappeared kinda randomly.\n");
                     return NULL;
                  }
                  mssinceflash = ast_tvdiff_ms(ast_tvnow(), p->flashtime);
                  ast_debug(1, "Last flash was %d ms ago\n", mssinceflash);
                  if (mssinceflash < MIN_MS_SINCE_FLASH) {
                     /* It hasn't been long enough since the last flashook.  This is probably a bounce on
                        hanging up.  Hangup both channels now */
                     if (p->subs[SUB_THREEWAY].owner)
                        ast_queue_hangup_with_cause(p->subs[SUB_THREEWAY].owner, AST_CAUSE_NO_ANSWER);
                     p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
                     ast_debug(1, "Looks like a bounced flash, hanging up both calls on %d\n", p->channel);
                     ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                  } else if ((ast->pbx) || (ast->_state == AST_STATE_UP)) {
                     if (p->transfer) {
                        /* In any case this isn't a threeway call anymore */
                        p->subs[SUB_REAL].inthreeway = 0;
                        p->subs[SUB_THREEWAY].inthreeway = 0;
                        /* Only attempt transfer if the phone is ringing; why transfer to busy tone eh? */
                        if (!p->transfertobusy && ast->_state == AST_STATE_BUSY) {
                           ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                           /* Swap subs and dis-own channel */
                           swap_subs(p, SUB_THREEWAY, SUB_REAL);
                           p->owner = NULL;
                           /* Ring the phone */
                           dahdi_ring_phone(p);
                        } else {
                           if ((res = attempt_transfer(p)) < 0) {
                              p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
                              if (p->subs[SUB_THREEWAY].owner)
                                 ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                           } else if (res) {
                              /* Don't actually hang up at this point */
                              if (p->subs[SUB_THREEWAY].owner)
                                 ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                              break;
                           }
                        }
                     } else {
                        p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
                        if (p->subs[SUB_THREEWAY].owner)
                           ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                     }
                  } else {
                     ast_channel_unlock(p->subs[SUB_THREEWAY].owner);
                     /* Swap subs and dis-own channel */
                     swap_subs(p, SUB_THREEWAY, SUB_REAL);
                     p->owner = NULL;
                     /* Ring the phone */
                     dahdi_ring_phone(p);
                  }
               }
            } else {
               ast_log(LOG_WARNING, "Got a hangup and my index is %d?\n", idx);
            }
            /* Fall through */
         default:
            dahdi_disable_ec(p);
            return NULL;
         }
         break;
      case DAHDI_EVENT_RINGOFFHOOK:
         if (p->inalarm) break;
         if (p->oprmode < 0)
         {
            if ((p->sig == SIG_FXOLS) || (p->sig == SIG_FXOKS) || (p->sig == SIG_FXOGS))
            {
               /* Make sure it stops ringing */
               dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_RINGOFF);
               tone_zone_play_tone(p->oprpeer->subs[SUB_REAL].dfd, -1);
               restore_conference(p->oprpeer);
            }
            break;
         }
         if (p->radio)
         {
            p->subs[idx].f.frametype = AST_FRAME_CONTROL;
            p->subs[idx].f.subclass = AST_CONTROL_RADIO_KEY;
            break;
         }
         /* for E911, its supposed to wait for offhook then dial
            the second half of the dial string */
         if (((mysig == SIG_E911) || (mysig == SIG_FGC_CAMA) || (mysig == SIG_FGC_CAMAMF)) && (ast->_state == AST_STATE_DIALING_OFFHOOK)) {
            c = strchr(p->dialdest, '/');
            if (c)
               c++;
            else
               c = p->dialdest;
            if (*c) snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*0%s#", c);
            else ast_copy_string(p->dop.dialstr,"M*2#", sizeof(p->dop.dialstr));
            if (strlen(p->dop.dialstr) > 4) {
               memset(p->echorest, 'w', sizeof(p->echorest) - 1);
               strcpy(p->echorest + (p->echotraining / 401) + 1, p->dop.dialstr + strlen(p->dop.dialstr) - 2);
               p->echorest[sizeof(p->echorest) - 1] = '\0';
               p->echobreak = 1;
               p->dop.dialstr[strlen(p->dop.dialstr)-2] = '\0';
            } else
               p->echobreak = 0;
            if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop)) {
               int saveerr = errno;
               x = DAHDI_ONHOOK;
               ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x);
               ast_log(LOG_WARNING, "Dialing failed on channel %d: %s\n", p->channel, strerror(saveerr));
               return NULL;
               }
            p->dialing = 1;
            return &p->subs[idx].f;
         }
         switch (p->sig) {
         case SIG_FXOLS:
         case SIG_FXOGS:
         case SIG_FXOKS:
            p->fxsoffhookstate = 1;
            switch (ast->_state) {
            case AST_STATE_RINGING:
               dahdi_enable_ec(p);
               dahdi_train_ec(p);
               p->subs[idx].f.frametype = AST_FRAME_CONTROL;
               p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
               /* Make sure it stops ringing */
               dahdi_set_hook(p->subs[idx].dfd, DAHDI_OFFHOOK);
               ast_debug(1, "channel %d answered\n", p->channel);
               if (p->cidspill) {
                  /* Cancel any running CallerID spill */
                  ast_free(p->cidspill);
                  p->cidspill = NULL;
               }
               p->dialing = 0;
               p->callwaitcas = 0;
               if (p->confirmanswer) {
                  /* Ignore answer if "confirm answer" is enabled */
                  p->subs[idx].f.frametype = AST_FRAME_NULL;
                  p->subs[idx].f.subclass = 0;
               } else if (!ast_strlen_zero(p->dop.dialstr)) {
                  /* nick@dccinc.com 4/3/03 - fxo should be able to do deferred dialing */
                  res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop);
                  if (res < 0) {
                     ast_log(LOG_WARNING, "Unable to initiate dialing on trunk channel %d: %s\n", p->channel, strerror(errno));
                     p->dop.dialstr[0] = '\0';
                     return NULL;
                  } else {
                     ast_debug(1, "Sent FXO deferred digit string: %s\n", p->dop.dialstr);
                     p->subs[idx].f.frametype = AST_FRAME_NULL;
                     p->subs[idx].f.subclass = 0;
                     p->dialing = 1;
                  }
                  p->dop.dialstr[0] = '\0';
                  ast_setstate(ast, AST_STATE_DIALING);
               } else
                  ast_setstate(ast, AST_STATE_UP);
               return &p->subs[idx].f;
            case AST_STATE_DOWN:
               ast_setstate(ast, AST_STATE_RING);
               ast->rings = 1;
               p->subs[idx].f.frametype = AST_FRAME_CONTROL;
               p->subs[idx].f.subclass = AST_CONTROL_OFFHOOK;
               ast_debug(1, "channel %d picked up\n", p->channel);
               return &p->subs[idx].f;
            case AST_STATE_UP:
               /* Make sure it stops ringing */
               dahdi_set_hook(p->subs[idx].dfd, DAHDI_OFFHOOK);
               /* Okay -- probably call waiting*/
               if (ast_bridged_channel(p->owner))
                  ast_queue_control(p->owner, AST_CONTROL_UNHOLD);
               p->subs[idx].needunhold = 1;
               break;
            case AST_STATE_RESERVED:
               /* Start up dialtone */
               if (has_voicemail(p))
                  res = tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_STUTTER);
               else
                  res = tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_DIALTONE);
               break;
            default:
               ast_log(LOG_WARNING, "FXO phone off hook in weird state %d??\n", ast->_state);
            }
            break;
         case SIG_FXSLS:
         case SIG_FXSGS:
         case SIG_FXSKS:
            if (ast->_state == AST_STATE_RING) {
               p->ringt = p->ringt_base;
            }
            /* If we get a ring then we cannot be in
             * reversed polarity. So we reset to idle */
            ast_debug(1, "Setting IDLE polarity due "
               "to ring. Old polarity was %d\n",
               p->polarity);
            p->polarity = POLARITY_IDLE;
            /* Fall through */
         case SIG_EM:
         case SIG_EM_E1:
         case SIG_EMWINK:
         case SIG_FEATD:
         case SIG_FEATDMF:
         case SIG_FEATDMF_TA:
         case SIG_E911:
         case SIG_FGC_CAMA:
         case SIG_FGC_CAMAMF:
         case SIG_FEATB:
         case SIG_SF:
         case SIG_SFWINK:
         case SIG_SF_FEATD:
         case SIG_SF_FEATDMF:
         case SIG_SF_FEATB:
            if (ast->_state == AST_STATE_PRERING)
               ast_setstate(ast, AST_STATE_RING);
            if ((ast->_state == AST_STATE_DOWN) || (ast->_state == AST_STATE_RING)) {
               ast_debug(1, "Ring detected\n");
               p->subs[idx].f.frametype = AST_FRAME_CONTROL;
               p->subs[idx].f.subclass = AST_CONTROL_RING;
            } else if (p->outgoing && ((ast->_state == AST_STATE_RINGING) || (ast->_state == AST_STATE_DIALING))) {
               ast_debug(1, "Line answered\n");
               if (p->confirmanswer) {
                  p->subs[idx].f.frametype = AST_FRAME_NULL;
                  p->subs[idx].f.subclass = 0;
               } else {
                  p->subs[idx].f.frametype = AST_FRAME_CONTROL;
                  p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
                  ast_setstate(ast, AST_STATE_UP);
               }
            } else if (ast->_state != AST_STATE_RING)
               ast_log(LOG_WARNING, "Ring/Off-hook in strange state %d on channel %d\n", ast->_state, p->channel);
            break;
         default:
            ast_log(LOG_WARNING, "Don't know how to handle ring/off hook for signalling %d\n", p->sig);
         }
         break;
      case DAHDI_EVENT_RINGBEGIN:
         switch (p->sig) {
         case SIG_FXSLS:
         case SIG_FXSGS:
         case SIG_FXSKS:
            if (ast->_state == AST_STATE_RING) {
               p->ringt = p->ringt_base;
            }
            break;
         }
         break;
      case DAHDI_EVENT_RINGEROFF:
         if (p->inalarm) break;
         if ((p->radio || (p->oprmode < 0))) break;
         ast->rings++;
         if ((ast->rings > p->cidrings) && (p->cidspill)) {
            ast_log(LOG_WARNING, "Didn't finish Caller-ID spill.  Cancelling.\n");
            ast_free(p->cidspill);
            p->cidspill = NULL;
            p->callwaitcas = 0;
         }
         p->subs[idx].f.frametype = AST_FRAME_CONTROL;
         p->subs[idx].f.subclass = AST_CONTROL_RINGING;
         break;
      case DAHDI_EVENT_RINGERON:
         break;
      case DAHDI_EVENT_NOALARM:
         p->inalarm = 0;
#ifdef HAVE_PRI
         /* Extremely unlikely but just in case */
         if (p->bearer)
            p->bearer->inalarm = 0;
#endif
         ast_log(LOG_NOTICE, "Alarm cleared on channel %d\n", p->channel);
         manager_event(EVENT_FLAG_SYSTEM, "AlarmClear",
                        "Channel: %d\r\n", p->channel);
         break;
      case DAHDI_EVENT_WINKFLASH:
         if (p->inalarm) break;
         if (p->radio) break;
         if (p->oprmode < 0) break;
         if (p->oprmode > 1)
         {
            struct dahdi_params par;
            memset(&par, 0, sizeof(par));
            if (ioctl(p->oprpeer->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &par) != -1)
            {
               if (!par.rxisoffhook)
               {
                  /* Make sure it stops ringing */
                  dahdi_set_hook(p->oprpeer->subs[SUB_REAL].dfd, DAHDI_RINGOFF);
                  dahdi_set_hook(p->oprpeer->subs[SUB_REAL].dfd, DAHDI_RING);
                  save_conference(p);
                  tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_RINGTONE);
               }
            }
            break;
         }
         /* Remember last time we got a flash-hook */
         p->flashtime = ast_tvnow();
         switch (mysig) {
         case SIG_FXOLS:
         case SIG_FXOGS:
         case SIG_FXOKS:
            ast_debug(1, "Winkflash, index: %d, normal: %d, callwait: %d, thirdcall: %d\n",
               idx, p->subs[SUB_REAL].dfd, p->subs[SUB_CALLWAIT].dfd, p->subs[SUB_THREEWAY].dfd);
            p->callwaitcas = 0;
            if (idx != SUB_REAL) {
               ast_log(LOG_WARNING, "Got flash hook with index %d on channel %d?!?\n", idx, p->channel);
               goto winkflashdone;
            }
            if (p->subs[SUB_CALLWAIT].owner) {
               /* Swap to call-wait */
               swap_subs(p, SUB_REAL, SUB_CALLWAIT);
               tone_zone_play_tone(p->subs[SUB_REAL].dfd, -1);
               p->owner = p->subs[SUB_REAL].owner;
               ast_debug(1, "Making %s the new owner\n", p->owner->name);
               if (p->owner->_state == AST_STATE_RINGING) {
                  ast_setstate(p->owner, AST_STATE_UP);
                  p->subs[SUB_REAL].needanswer = 1;
               }
               p->callwaitingrepeat = 0;
               p->cidcwexpire = 0;
               /* Start music on hold if appropriate */
               if (!p->subs[SUB_CALLWAIT].inthreeway && ast_bridged_channel(p->subs[SUB_CALLWAIT].owner)) {
                  ast_queue_control_data(p->subs[SUB_CALLWAIT].owner, AST_CONTROL_HOLD,
                     S_OR(p->mohsuggest, NULL),
                     !ast_strlen_zero(p->mohsuggest) ? strlen(p->mohsuggest) + 1 : 0);
               }
               p->subs[SUB_CALLWAIT].needhold = 1;
               if (ast_bridged_channel(p->subs[SUB_REAL].owner)) {
                  ast_queue_control_data(p->subs[SUB_REAL].owner, AST_CONTROL_HOLD,
                     S_OR(p->mohsuggest, NULL),
                     !ast_strlen_zero(p->mohsuggest) ? strlen(p->mohsuggest) + 1 : 0);
               }
               p->subs[SUB_REAL].needunhold = 1;
            } else if (!p->subs[SUB_THREEWAY].owner) {
               if (!p->threewaycalling) {
                  /* Just send a flash if no 3-way calling */
                  p->subs[SUB_REAL].needflash = 1;
                  goto winkflashdone;
               } else if (!check_for_conference(p)) {
                  char cid_num[256];
                  char cid_name[256];
                  cid_num[0] = 0;
                  cid_name[0] = 0;
                  if (p->dahditrcallerid && p->owner) {
                     if (p->owner->cid.cid_num)
                        ast_copy_string(cid_num, p->owner->cid.cid_num, sizeof(cid_num));
                     if (p->owner->cid.cid_name)
                        ast_copy_string(cid_name, p->owner->cid.cid_name, sizeof(cid_name));
                  }
                  /* XXX This section needs much more error checking!!! XXX */
                  /* Start a 3-way call if feasible */
                  if (!((ast->pbx) ||
                     (ast->_state == AST_STATE_UP) ||
                     (ast->_state == AST_STATE_RING))) {
                     ast_debug(1, "Flash when call not up or ringing\n");
                     goto winkflashdone;
                  }
                  if (alloc_sub(p, SUB_THREEWAY)) {
                     ast_log(LOG_WARNING, "Unable to allocate three-way subchannel\n");
                     goto winkflashdone;
                  }
                  /* Make new channel */
                  chan = dahdi_new(p, AST_STATE_RESERVED, 0, SUB_THREEWAY, 0, 0);
                  if (p->dahditrcallerid) {
                     if (!p->origcid_num)
                        p->origcid_num = ast_strdup(p->cid_num);
                     if (!p->origcid_name)
                        p->origcid_name = ast_strdup(p->cid_name);
                     ast_copy_string(p->cid_num, cid_num, sizeof(p->cid_num));
                     ast_copy_string(p->cid_name, cid_name, sizeof(p->cid_name));
                  }
                  /* Swap things around between the three-way and real call */
                  swap_subs(p, SUB_THREEWAY, SUB_REAL);
                  /* Disable echo canceller for better dialing */
                  dahdi_disable_ec(p);
                  res = tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_DIALRECALL);
                  if (res)
                     ast_log(LOG_WARNING, "Unable to start dial recall tone on channel %d\n", p->channel);
                  p->owner = chan;
                  if (!chan) {
                     ast_log(LOG_WARNING, "Cannot allocate new structure on channel %d\n", p->channel);
                  } else if (ast_pthread_create_detached(&threadid, NULL, ss_thread, chan)) {
                     ast_log(LOG_WARNING, "Unable to start simple switch on channel %d\n", p->channel);
                     res = tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
                     dahdi_enable_ec(p);
                     ast_hangup(chan);
                  } else {
                     struct ast_channel *other = ast_bridged_channel(p->subs[SUB_THREEWAY].owner);
                     int way3bridge = 0, cdr3way = 0;
                     if (!other) {
                        other = ast_bridged_channel(p->subs[SUB_REAL].owner);
                     } else
                        way3bridge = 1;
                     if (p->subs[SUB_THREEWAY].owner->cdr)
                        cdr3way = 1;
                     ast_verb(3, "Started three way call on channel %d\n", p->channel);
                     /* Start music on hold if appropriate */
                     if (ast_bridged_channel(p->subs[SUB_THREEWAY].owner)) {
                        ast_queue_control_data(p->subs[SUB_THREEWAY].owner, AST_CONTROL_HOLD,
                           S_OR(p->mohsuggest, NULL),
                           !ast_strlen_zero(p->mohsuggest) ? strlen(p->mohsuggest) + 1 : 0);
                     }
                     p->subs[SUB_THREEWAY].needhold = 1;
                  }
               }
            } else {
               /* Already have a 3 way call */
               if (p->subs[SUB_THREEWAY].inthreeway) {
                  /* Call is already up, drop the last person */
                  ast_debug(1, "Got flash with three way call up, dropping last call on %d\n", p->channel);
                  /* If the primary call isn't answered yet, use it */
                  if ((p->subs[SUB_REAL].owner->_state != AST_STATE_UP) && (p->subs[SUB_THREEWAY].owner->_state == AST_STATE_UP)) {
                     /* Swap back -- we're dropping the real 3-way that isn't finished yet*/
                     swap_subs(p, SUB_THREEWAY, SUB_REAL);
                     p->owner = p->subs[SUB_REAL].owner;
                  }
                  /* Drop the last call and stop the conference */
                  ast_verb(3, "Dropping three-way call on %s\n", p->subs[SUB_THREEWAY].owner->name);
                  p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
                  p->subs[SUB_REAL].inthreeway = 0;
                  p->subs[SUB_THREEWAY].inthreeway = 0;
               } else {
                  /* Lets see what we're up to */
                  if (((ast->pbx) || (ast->_state == AST_STATE_UP)) &&
                     (p->transfertobusy || (ast->_state != AST_STATE_BUSY))) {
                     int otherindex = SUB_THREEWAY;
                     struct ast_channel *other = ast_bridged_channel(p->subs[SUB_THREEWAY].owner);
                     int way3bridge = 0, cdr3way = 0;
                     if (!other) {
                        other = ast_bridged_channel(p->subs[SUB_REAL].owner);
                     } else
                        way3bridge = 1;
                     if (p->subs[SUB_THREEWAY].owner->cdr)
                        cdr3way = 1;
                     ast_verb(3, "Building conference on call on %s and %s\n", p->subs[SUB_THREEWAY].owner->name, p->subs[SUB_REAL].owner->name);
                     /* Put them in the threeway, and flip */
                     p->subs[SUB_THREEWAY].inthreeway = 1;
                     p->subs[SUB_REAL].inthreeway = 1;
                     if (ast->_state == AST_STATE_UP) {
                        swap_subs(p, SUB_THREEWAY, SUB_REAL);
                        otherindex = SUB_REAL;
                     }
                     if (p->subs[otherindex].owner && ast_bridged_channel(p->subs[otherindex].owner))
                        ast_queue_control(p->subs[otherindex].owner, AST_CONTROL_UNHOLD);
                     p->subs[otherindex].needunhold = 1;
                     p->owner = p->subs[SUB_REAL].owner;
                     if (ast->_state == AST_STATE_RINGING) {
                        ast_debug(1, "Enabling ringtone on real and threeway\n");
                        res = tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_RINGTONE);
                        res = tone_zone_play_tone(p->subs[SUB_THREEWAY].dfd, DAHDI_TONE_RINGTONE);
                     }
                  } else {
                     ast_verb(3, "Dumping incomplete call on on %s\n", p->subs[SUB_THREEWAY].owner->name);
                     swap_subs(p, SUB_THREEWAY, SUB_REAL);
                     p->subs[SUB_THREEWAY].owner->_softhangup |= AST_SOFTHANGUP_DEV;
                     p->owner = p->subs[SUB_REAL].owner;
                     if (p->subs[SUB_REAL].owner && ast_bridged_channel(p->subs[SUB_REAL].owner))
                        ast_queue_control(p->subs[SUB_REAL].owner, AST_CONTROL_UNHOLD);
                     p->subs[SUB_REAL].needunhold = 1;
                     dahdi_enable_ec(p);
                  }
               }
            }
winkflashdone:
            update_conf(p);
            break;
         case SIG_EM:
         case SIG_EM_E1:
         case SIG_FEATD:
         case SIG_SF:
         case SIG_SFWINK:
         case SIG_SF_FEATD:
         case SIG_FXSLS:
         case SIG_FXSGS:
            if (option_debug) {
               if (p->dialing)
                  ast_debug(1, "Ignoring wink on channel %d\n", p->channel);
               else
                  ast_debug(1, "Got wink in weird state %d on channel %d\n", ast->_state, p->channel);
            }
            break;
         case SIG_FEATDMF_TA:
            switch (p->whichwink) {
            case 0:
               ast_debug(1, "ANI2 set to '%d' and ANI is '%s'\n", p->owner->cid.cid_ani2, p->owner->cid.cid_ani);
               snprintf(p->dop.dialstr, sizeof(p->dop.dialstr), "M*%d%s#", p->owner->cid.cid_ani2, p->owner->cid.cid_ani);
               break;
            case 1:
               ast_copy_string(p->dop.dialstr, p->finaldial, sizeof(p->dop.dialstr));
               break;
            case 2:
               ast_log(LOG_WARNING, "Received unexpected wink on channel of type SIG_FEATDMF_TA\n");
               return NULL;
            }
            p->whichwink++;
            /* Fall through */
         case SIG_FEATDMF:
         case SIG_E911:
         case SIG_FGC_CAMAMF:
         case SIG_FGC_CAMA:
         case SIG_FEATB:
         case SIG_SF_FEATDMF:
         case SIG_SF_FEATB:
         case SIG_EMWINK:
            /* FGD MF and EMWINK *Must* wait for wink */
            if (!ast_strlen_zero(p->dop.dialstr)) {
               res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop);
               if (res < 0) {
                  ast_log(LOG_WARNING, "Unable to initiate dialing on trunk channel %d: %s\n", p->channel, strerror(errno));
                  p->dop.dialstr[0] = '\0';
                  return NULL;
               } else
                  ast_debug(1, "Sent deferred digit string: %s\n", p->dop.dialstr);
            }
            p->dop.dialstr[0] = '\0';
            break;
         default:
            ast_log(LOG_WARNING, "Don't know how to handle ring/off hook for signalling %d\n", p->sig);
         }
         break;
      case DAHDI_EVENT_HOOKCOMPLETE:
         if (p->inalarm) break;
         if ((p->radio || (p->oprmode < 0))) break;
         if (p->waitingfordt.tv_sec) break;
         switch (mysig) {
         case SIG_FXSLS:  /* only interesting for FXS */
         case SIG_FXSGS:
         case SIG_FXSKS:
         case SIG_EM:
         case SIG_EM_E1:
         case SIG_EMWINK:
         case SIG_FEATD:
         case SIG_SF:
         case SIG_SFWINK:
         case SIG_SF_FEATD:
            if (!ast_strlen_zero(p->dop.dialstr)) {
               res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop);
               if (res < 0) {
                  ast_log(LOG_WARNING, "Unable to initiate dialing on trunk channel %d: %s\n", p->channel, strerror(errno));
                  p->dop.dialstr[0] = '\0';
                  return NULL;
               } else
                  ast_debug(1, "Sent deferred digit string: %s\n", p->dop.dialstr);
            }
            p->dop.dialstr[0] = '\0';
            p->dop.op = DAHDI_DIAL_OP_REPLACE;
            break;
         case SIG_FEATDMF:
         case SIG_FEATDMF_TA:
         case SIG_E911:
         case SIG_FGC_CAMA:
         case SIG_FGC_CAMAMF:
         case SIG_FEATB:
         case SIG_SF_FEATDMF:
         case SIG_SF_FEATB:
            ast_debug(1, "Got hook complete in MF FGD, waiting for wink now on channel %d\n",p->channel);
            break;
         default:
            break;
         }
         break;
      case DAHDI_EVENT_POLARITY:
         /*
          * If we get a Polarity Switch event, this could be
          * due to line seizure, remote end connect or remote end disconnect.
          *
          * Check to see if we should change the polarity state and
          * mark the channel as UP or if this is an indication
          * of remote end disconnect.
          */
         if (p->polarityonanswerdelay > 0) {
            /* check if event is not too soon after OffHook or Answer */
            if (ast_tvdiff_ms(ast_tvnow(), p->polaritydelaytv) > p->polarityonanswerdelay) {
               switch (ast->_state) {
               case AST_STATE_DIALING:       /*!< Digits (or equivalent) have been dialed */
               case AST_STATE_RINGING:       /*!< Remote end is ringing */
                  if (p->answeronpolarityswitch) {
                     ast_debug(1, "Answering on polarity switch! channel %d\n", p->channel);
                     ast_setstate(p->owner, AST_STATE_UP);
                     p->polarity = POLARITY_REV;
                     if (p->hanguponpolarityswitch) {
                        p->polaritydelaytv = ast_tvnow();
                     }
                  } else {
                     ast_debug(1, "Ignore Answer on polarity switch, channel %d\n", p->channel);
                  }
                  break;
               case AST_STATE_UP:         /*!< Line is up */
               case AST_STATE_RING:       /*!< Line is ringing */
                  if (p->hanguponpolarityswitch) {
                     ast_debug(1, "HangingUp on polarity switch! channel %d\n", p->channel);
                     ast_softhangup(p->owner, AST_SOFTHANGUP_EXPLICIT);
                     p->polarity = POLARITY_IDLE;
                  } else {
                     ast_debug(1, "Ignore Hangup on polarity switch, channel %d\n", p->channel);
                  }
                  break;
               case AST_STATE_DOWN:       /*!< Channel is down and available */
               case AST_STATE_RESERVED:      /*!< Channel is down, but reserved */
               case AST_STATE_OFFHOOK:       /*!< Channel is off hook */
               case AST_STATE_BUSY:       /*!< Line is busy */
               case AST_STATE_DIALING_OFFHOOK:     /*!< Digits (or equivalent) have been dialed while offhook */
               case AST_STATE_PRERING:       /*!< Channel has detected an incoming call and is waiting for ring */
               default:
                  if (p->answeronpolarityswitch || p->hanguponpolarityswitch) {
                     ast_debug(1, "Ignoring Polarity switch on channel %d, state %d\n", p->channel, ast->_state);
                  }
               }
            } else {
               /* event is too soon after OffHook or Answer */
               switch (ast->_state) {
               case AST_STATE_DIALING:       /*!< Digits (or equivalent) have been dialed */
               case AST_STATE_RINGING:       /*!< Remote end is ringing */
                  if (p->answeronpolarityswitch) {
                     ast_debug(1, "Polarity switch detected but NOT answering (too close to OffHook event) on channel %d, state %d\n", p->channel, ast->_state);
                  }
                  break;
               case AST_STATE_UP:         /*!< Line is up */
               case AST_STATE_RING:       /*!< Line is ringing */
                  if (p->hanguponpolarityswitch) {
                     ast_debug(1, "Polarity switch detected but NOT hanging up (too close to Answer event) on channel %d, state %d\n", p->channel, ast->_state);
                  }
                  break;
               default:
                  if (p->answeronpolarityswitch || p->hanguponpolarityswitch) {
                     ast_debug(1, "Polarity switch detected (too close to previous event) on channel %d, state %d\n", p->channel, ast->_state);
                  }
               }
            }
         }
         /* Added more log_debug information below to provide a better indication of what is going on */
         ast_debug(1, "Polarity Reversal event occured - DEBUG 2: channel %d, state %d, pol= %d, aonp= %d, honp= %d, pdelay= %d, tv= %d\n", p->channel, ast->_state, p->polarity, p->answeronpolarityswitch, p->hanguponpolarityswitch, p->polarityonanswerdelay, ast_tvdiff_ms(ast_tvnow(), p->polaritydelaytv) );
         break;
      default:
         ast_debug(1, "Dunno what to do with event %d on channel %d\n", res, p->channel);
   }
   return &p->subs[idx].f;
}
static int dahdi_hangup (struct ast_channel * ast) [static]
Definition at line 4313 of file chan_dahdi.c.
References ast_channel::_state, ast_bridged_channel(), ast_channel_setoption(), AST_CONTROL_HOLD, AST_CONTROL_UNHOLD, ast_copy_string(), ast_debug, ast_dsp_free(), ast_dsp_set_digitmode(), ast_free, ast_log(), ast_module_unref(), ast_mutex_lock(), ast_mutex_unlock(), AST_OPTION_AUDIO_MODE, AST_OPTION_TDD, AST_OPTION_TONE_VERIFY, ast_queue_control(), ast_queue_control_data(), AST_STATE_RESERVED, AST_STATE_UP, ast_strlen_zero(), ast_verb, dahdi_pvt::buf_no, dahdi_pvt::buf_policy, dahdi_pvt::bufsize, dahdi_pvt::callwaitcas, dahdi_pvt::callwaiting, dahdi_pvt::callwaitingrepeat, dahdi_pvt::channel, dahdi_pvt::cid_name, dahdi_pvt::cid_num, dahdi_pvt::cidcwexpire, dahdi_pvt::cidrings, dahdi_pvt::cidspill, dahdi_pvt::confirmanswer, dahdi_confmute(), dahdi_disable_ec(), dahdi_get_index(), dahdi_set_hook(), dahdi_setlinear(), dahdi_pvt::destroy, destroy_channel(), dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::didtdd, dahdi_pvt::digital, dahdi_pvt::distinctivering, dahdi_pvt::dsp, DSP_DIGITMODE_DTMF, dahdi_pvt::dtmfrelax, errno, dahdi_pvt::exten, dahdi_pvt::faxbuffersinuse, dahdi_pvt::faxhandled, dahdi_pvt::fxsoffhookstate, dahdi_pvt::guardtime, ast_channel::hangupcause, dahdi_pvt::hidecallerid, iflist, dahdi_pvt::ignoredtmf, dahdi_subchannel::inthreeway, dahdi_pvt::law, dahdi_subchannel::linear, dahdi_pvt::lock, LOG_DEBUG, LOG_WARNING, dahdi_pvt::mohsuggest, dahdi_pvt::muting, dahdi_subchannel::needanswer, dahdi_subchannel::needbusy, dahdi_subchannel::needcallerid, dahdi_subchannel::needcongestion, dahdi_subchannel::needflash, dahdi_subchannel::needringing, dahdi_pvt::next, dahdi_pvt::onhooktime, dahdi_pvt::oprmode, dahdi_pvt::origcid_name, dahdi_pvt::origcid_num, dahdi_pvt::outgoing, dahdi_pvt::owner, dahdi_subchannel::owner, pbx_builtin_getvar_helper(), dahdi_pvt::permcallwaiting, dahdi_pvt::permhidecallerid, dahdi_pvt::polarity, POLARITY_IDLE, dahdi_pvt::prev, dahdi_pvt::pulsedial, dahdi_pvt::radio, dahdi_pvt::rdnis, reset_conf(), restart_monitor(), dahdi_pvt::restartpending, restore_gains(), dahdi_pvt::ringt, S_OR, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_MFCR2, SIG_PRI, SIG_SS7, dahdi_pvt::span, SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, dahdi_pvt::subs, swap_subs(), ast_channel::tech_pvt, unalloc_sub(), update_conf(), and dahdi_pvt::waitingfordt.
{
   int res;
   int idx,x, law;
   /*static int restore_gains(struct dahdi_pvt *p);*/
   struct dahdi_pvt *p = ast->tech_pvt;
   struct dahdi_pvt *tmp = NULL;
   struct dahdi_pvt *prev = NULL;
   struct dahdi_params par;
   ast_debug(1, "dahdi_hangup(%s)\n", ast->name);
   if (!ast->tech_pvt) {
      ast_log(LOG_WARNING, "Asked to hangup channel not connected\n");
      return 0;
   }
   ast_mutex_lock(&p->lock);
   idx = dahdi_get_index(ast, p, 1);
   if ((p->sig == SIG_PRI) || (p->sig == SIG_SS7) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) {
      x = 1;
      ast_channel_setoption(ast,AST_OPTION_AUDIO_MODE,&x,sizeof(char),0);
      p->cid_num[0] = '\0';
      p->cid_name[0] = '\0';
   }
   x = 0;
   dahdi_confmute(p, 0);
   p->muting = 0;
   restore_gains(p);
   if (p->origcid_num) {
      ast_copy_string(p->cid_num, p->origcid_num, sizeof(p->cid_num));
      ast_free(p->origcid_num);
      p->origcid_num = NULL;
   }
   if (p->origcid_name) {
      ast_copy_string(p->cid_name, p->origcid_name, sizeof(p->cid_name));
      ast_free(p->origcid_name);
      p->origcid_name = NULL;
   }
   if (p->dsp)
      ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_DTMF | p->dtmfrelax);
   p->exten[0] = '\0';
   ast_debug(1, "Hangup: channel: %d index = %d, normal = %d, callwait = %d, thirdcall = %d\n",
      p->channel, idx, p->subs[SUB_REAL].dfd, p->subs[SUB_CALLWAIT].dfd, p->subs[SUB_THREEWAY].dfd);
   p->ignoredtmf = 0;
   if (idx > -1) {
      /* Real channel, do some fixup */
      p->subs[idx].owner = NULL;
      p->subs[idx].needanswer = 0;
      p->subs[idx].needflash = 0;
      p->subs[idx].needringing = 0;
      p->subs[idx].needbusy = 0;
      p->subs[idx].needcongestion = 0;
      p->subs[idx].linear = 0;
      p->subs[idx].needcallerid = 0;
      p->polarity = POLARITY_IDLE;
      dahdi_setlinear(p->subs[idx].dfd, 0);
      if (idx == SUB_REAL) {
         if ((p->subs[SUB_CALLWAIT].dfd > -1) && (p->subs[SUB_THREEWAY].dfd > -1)) {
            ast_debug(1, "Normal call hung up with both three way call and a call waiting call in place?\n");
            if (p->subs[SUB_CALLWAIT].inthreeway) {
               /* We had flipped over to answer a callwait and now it's gone */
               ast_debug(1, "We were flipped over to the callwait, moving back and unowning.\n");
               /* Move to the call-wait, but un-own us until they flip back. */
               swap_subs(p, SUB_CALLWAIT, SUB_REAL);
               unalloc_sub(p, SUB_CALLWAIT);
               p->owner = NULL;
            } else {
               /* The three way hung up, but we still have a call wait */
               ast_debug(1, "We were in the threeway and have a callwait still.  Ditching the threeway.\n");
               swap_subs(p, SUB_THREEWAY, SUB_REAL);
               unalloc_sub(p, SUB_THREEWAY);
               if (p->subs[SUB_REAL].inthreeway) {
                  /* This was part of a three way call.  Immediately make way for
                     another call */
                  ast_debug(1, "Call was complete, setting owner to former third call\n");
                  p->owner = p->subs[SUB_REAL].owner;
               } else {
                  /* This call hasn't been completed yet...  Set owner to NULL */
                  ast_debug(1, "Call was incomplete, setting owner to NULL\n");
                  p->owner = NULL;
               }
               p->subs[SUB_REAL].inthreeway = 0;
            }
         } else if (p->subs[SUB_CALLWAIT].dfd > -1) {
            /* Move to the call-wait and switch back to them. */
            swap_subs(p, SUB_CALLWAIT, SUB_REAL);
            unalloc_sub(p, SUB_CALLWAIT);
            p->owner = p->subs[SUB_REAL].owner;
            if (p->owner->_state != AST_STATE_UP)
               p->subs[SUB_REAL].needanswer = 1;
            if (ast_bridged_channel(p->subs[SUB_REAL].owner))
               ast_queue_control(p->subs[SUB_REAL].owner, AST_CONTROL_UNHOLD);
         } else if (p->subs[SUB_THREEWAY].dfd > -1) {
            swap_subs(p, SUB_THREEWAY, SUB_REAL);
            unalloc_sub(p, SUB_THREEWAY);
            if (p->subs[SUB_REAL].inthreeway) {
               /* This was part of a three way call.  Immediately make way for
                  another call */
               ast_debug(1, "Call was complete, setting owner to former third call\n");
               p->owner = p->subs[SUB_REAL].owner;
            } else {
               /* This call hasn't been completed yet...  Set owner to NULL */
               ast_debug(1, "Call was incomplete, setting owner to NULL\n");
               p->owner = NULL;
            }
            p->subs[SUB_REAL].inthreeway = 0;
         }
      } else if (idx == SUB_CALLWAIT) {
         /* Ditch the holding callwait call, and immediately make it availabe */
         if (p->subs[SUB_CALLWAIT].inthreeway) {
            /* This is actually part of a three way, placed on hold.  Place the third part
               on music on hold now */
            if (p->subs[SUB_THREEWAY].owner && ast_bridged_channel(p->subs[SUB_THREEWAY].owner)) {
               ast_queue_control_data(p->subs[SUB_THREEWAY].owner, AST_CONTROL_HOLD,
                  S_OR(p->mohsuggest, NULL),
                  !ast_strlen_zero(p->mohsuggest) ? strlen(p->mohsuggest) + 1 : 0);
            }
            p->subs[SUB_THREEWAY].inthreeway = 0;
            /* Make it the call wait now */
            swap_subs(p, SUB_CALLWAIT, SUB_THREEWAY);
            unalloc_sub(p, SUB_THREEWAY);
         } else
            unalloc_sub(p, SUB_CALLWAIT);
      } else if (idx == SUB_THREEWAY) {
         if (p->subs[SUB_CALLWAIT].inthreeway) {
            /* The other party of the three way call is currently in a call-wait state.
               Start music on hold for them, and take the main guy out of the third call */
            if (p->subs[SUB_CALLWAIT].owner && ast_bridged_channel(p->subs[SUB_CALLWAIT].owner)) {
               ast_queue_control_data(p->subs[SUB_CALLWAIT].owner, AST_CONTROL_HOLD,
                  S_OR(p->mohsuggest, NULL),
                  !ast_strlen_zero(p->mohsuggest) ? strlen(p->mohsuggest) + 1 : 0);
            }
            p->subs[SUB_CALLWAIT].inthreeway = 0;
         }
         p->subs[SUB_REAL].inthreeway = 0;
         /* If this was part of a three way call index, let us make
            another three way call */
         unalloc_sub(p, SUB_THREEWAY);
      } else {
         /* This wasn't any sort of call, but how are we an index? */
         ast_log(LOG_WARNING, "Index found but not any type of call?\n");
      }
   }
   if (!p->subs[SUB_REAL].owner && !p->subs[SUB_CALLWAIT].owner && !p->subs[SUB_THREEWAY].owner) {
      p->owner = NULL;
      p->ringt = 0;
      p->distinctivering = 0;
      p->confirmanswer = 0;
      p->cidrings = 1;
      p->outgoing = 0;
      p->digital = 0;
      p->faxhandled = 0;
      p->pulsedial = 0;
      p->onhooktime = time(NULL);
#if defined(HAVE_PRI) || defined(HAVE_SS7)
      p->proceeding = 0;
      p->dialing = 0;
      p->progress = 0;
      p->alerting = 0;
      p->setup_ack = 0;
      p->rlt = 0;
#endif
      if (p->dsp) {
         ast_dsp_free(p->dsp);
         p->dsp = NULL;
      }
      if (p->faxbuffersinuse) {
         /* faxbuffers are in use, revert them */
         struct dahdi_bufferinfo bi = {
            .txbufpolicy = p->buf_policy,
            .rxbufpolicy = p->buf_policy,
            .bufsize = p->bufsize,
            .numbufs = p->buf_no
         };
         int bpres;
         if ((bpres = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SET_BUFINFO, &bi)) < 0) {
            ast_log(LOG_WARNING, "Channel '%s' unable to revert faxbuffer policy: %s\n", ast->name, strerror(errno));
         }
         p->faxbuffersinuse = 0;
      }
      law = DAHDI_LAW_DEFAULT;
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETLAW, &law);
      if (res < 0)
         ast_log(LOG_WARNING, "Unable to set law on channel %d to default: %s\n", p->channel, strerror(errno));
      /* Perform low level hangup if no owner left */
#ifdef HAVE_SS7
      if (p->ss7) {
         if (p->ss7call) {
            if (!ss7_grab(p, p->ss7)) {
               if (!p->alreadyhungup) {
                  const char *cause = pbx_builtin_getvar_helper(ast,"SS7_CAUSE");
                  int icause = ast->hangupcause ? ast->hangupcause : -1;
                  if (cause) {
                     if (atoi(cause))
                        icause = atoi(cause);
                  }
                  isup_rel(p->ss7->ss7, p->ss7call, icause);
                  ss7_rel(p->ss7);
                  p->alreadyhungup = 1;
               } else
                  ast_log(LOG_WARNING, "Trying to hangup twice!\n");
            } else {
               ast_log(LOG_WARNING, "Unable to grab SS7 on CIC %d\n", p->cic);
               res = -1;
            }
         }
      }
#endif
#ifdef HAVE_OPENR2
      p->cid_num[0] = '\0';
      p->cid_name[0] = '\0';
      if (p->mfcr2 && p->mfcr2call && openr2_chan_get_direction(p->r2chan) != OR2_DIR_STOPPED) {
         ast_log(LOG_DEBUG, "disconnecting MFC/R2 call on chan %d\n", p->channel);
         /* If it's an incoming call, check the mfcr2_forced_release setting */
         if (openr2_chan_get_direction(p->r2chan) == OR2_DIR_BACKWARD && p->mfcr2_forced_release) {
            dahdi_r2_disconnect_call(p, OR2_CAUSE_FORCED_RELEASE);
         } else {
            const char *r2causestr = pbx_builtin_getvar_helper(ast, "MFCR2_CAUSE");
            int r2cause_user = r2causestr ? atoi(r2causestr) : 0;
            openr2_call_disconnect_cause_t r2cause = r2cause_user ? dahdi_ast_cause_to_r2_cause(r2cause_user)
                                                             : dahdi_ast_cause_to_r2_cause(ast->hangupcause);
            dahdi_r2_disconnect_call(p, r2cause);
         }
      } else if (p->mfcr2call) {
         ast_log(LOG_DEBUG, "Clearing call request on channel %d\n", p->channel);
         /* since ast_request() was called but not ast_call() we have not yet dialed
         and the openr2 stack will not call on_call_end callback, we need to unset
         the mfcr2call flag and bump the monitor count so the monitor thread can take
         care of this channel events from now on */
         p->mfcr2call = 0;
      }
#endif
#ifdef HAVE_PRI
      if (p->pri) {
#ifdef SUPPORT_USERUSER
         const char *useruser = pbx_builtin_getvar_helper(ast,"USERUSERINFO");
#endif
         /* Make sure we have a call (or REALLY have a call in the case of a PRI) */
         if (p->call && (!p->bearer || (p->bearer->call == p->call))) {
            if (!pri_grab(p, p->pri)) {
               if (p->alreadyhungup) {
                  ast_debug(1, "Already hungup...  Calling hangup once, and clearing call\n");
#ifdef SUPPORT_USERUSER
                  pri_call_set_useruser(p->call, useruser);
#endif
                  pri_hangup(p->pri->pri, p->call, -1);
                  p->call = NULL;
                  if (p->bearer)
                     p->bearer->call = NULL;
               } else {
                  const char *cause = pbx_builtin_getvar_helper(ast,"PRI_CAUSE");
                  int icause = ast->hangupcause ? ast->hangupcause : -1;
                  ast_debug(1, "Not yet hungup...  Calling hangup once with icause, and clearing call\n");
#ifdef SUPPORT_USERUSER
                  pri_call_set_useruser(p->call, useruser);
#endif
                  p->alreadyhungup = 1;
                  if (p->bearer)
                     p->bearer->alreadyhungup = 1;
                  if (cause) {
                     if (atoi(cause))
                        icause = atoi(cause);
                  }
                  pri_hangup(p->pri->pri, p->call, icause);
               }
               if (res < 0)
                  ast_log(LOG_WARNING, "pri_disconnect failed\n");
               pri_rel(p->pri);
            } else {
               ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
               res = -1;
            }
         } else {
            if (p->bearer)
               ast_debug(1, "Bearer call is %p, while ours is still %p\n", p->bearer->call, p->call);
            p->call = NULL;
            res = 0;
         }
      }
#endif
      if (p->sig && ((p->sig != SIG_PRI) && (p->sig != SIG_SS7)
         && (p->sig != SIG_BRI)
         && (p->sig != SIG_BRI_PTMP))
         && (p->sig != SIG_MFCR2))
         res = dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_ONHOOK);
      if (res < 0) {
         ast_log(LOG_WARNING, "Unable to hangup line %s\n", ast->name);
      }
      switch (p->sig) {
      case SIG_FXOGS:
      case SIG_FXOLS:
      case SIG_FXOKS:
         memset(&par, 0, sizeof(par));
         res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &par);
         if (!res) {
#if 0
            ast_debug(1, "Hanging up channel %d, offhook = %d\n", p->channel, par.rxisoffhook);
#endif
            /* If they're off hook, try playing congestion */
            if ((par.rxisoffhook) && (!(p->radio || (p->oprmode < 0))))
               tone_zone_play_tone(p->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
            else
               tone_zone_play_tone(p->subs[SUB_REAL].dfd, -1);
            p->fxsoffhookstate = par.rxisoffhook;
         }
         break;
      case SIG_FXSGS:
      case SIG_FXSLS:
      case SIG_FXSKS:
         /* Make sure we're not made available for at least two seconds assuming
            we were actually used for an inbound or outbound call. */
         if (ast->_state != AST_STATE_RESERVED) {
            time(&p->guardtime);
            p->guardtime += 2;
         }
         break;
      default:
         tone_zone_play_tone(p->subs[SUB_REAL].dfd, -1);
      }
      if (p->cidspill)
         ast_free(p->cidspill);
      if (p->sig)
         dahdi_disable_ec(p);
      x = 0;
      ast_channel_setoption(ast,AST_OPTION_TONE_VERIFY,&x,sizeof(char),0);
      ast_channel_setoption(ast,AST_OPTION_TDD,&x,sizeof(char),0);
      p->didtdd = 0;
      p->cidspill = NULL;
      p->callwaitcas = 0;
      p->callwaiting = p->permcallwaiting;
      p->hidecallerid = p->permhidecallerid;
      p->waitingfordt.tv_sec = 0;
      p->dialing = 0;
      p->rdnis[0] = '\0';
      update_conf(p);
      reset_conf(p);
      /* Restore data mode */
      if ((p->sig == SIG_PRI) || (p->sig == SIG_SS7) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) {
         x = 0;
         ast_channel_setoption(ast,AST_OPTION_AUDIO_MODE,&x,sizeof(char),0);
      }
#ifdef HAVE_PRI
      if (p->bearer) {
         ast_debug(1, "Freeing up bearer channel %d\n", p->bearer->channel);
         /* Free up the bearer channel as well, and
            don't use its file descriptor anymore */
         update_conf(p->bearer);
         reset_conf(p->bearer);
         p->bearer->owner = NULL;
         p->bearer->realcall = NULL;
         p->bearer = NULL;
         p->subs[SUB_REAL].dfd = -1;
         p->pri = NULL;
      }
#endif
      if (num_restart_pending == 0)
         restart_monitor();
   }
   p->callwaitingrepeat = 0;
   p->cidcwexpire = 0;
   p->oprmode = 0;
   ast->tech_pvt = NULL;
   ast_mutex_unlock(&p->lock);
   ast_module_unref(ast_module_info->self);
   ast_verb(3, "Hungup '%s'\n", ast->name);
   ast_mutex_lock(&iflock);
   if (p->restartpending) {
      num_restart_pending--;
   }
   tmp = iflist;
   prev = NULL;
   if (p->destroy) {
      while (tmp) {
         if (tmp == p) {
            destroy_channel(prev, tmp, 0);
            break;
         } else {
            prev = tmp;
            tmp = tmp->next;
         }
      }
   }
   ast_mutex_unlock(&iflock);
   return 0;
}
static int dahdi_indicate (struct ast_channel * chan, int condition, const void * data, size_t datalen) [static]
Definition at line 7170 of file chan_dahdi.c.
References ast_channel::_softhangup, ast_channel::_state, AST_CAUSE_CONGESTION, AST_CAUSE_SWITCH_CONGESTION, AST_CAUSE_USER_BUSY, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_FLASH, AST_CONTROL_HOLD, AST_CONTROL_PROCEEDING, AST_CONTROL_PROGRESS, AST_CONTROL_RADIO_KEY, AST_CONTROL_RADIO_UNKEY, AST_CONTROL_RINGING, AST_CONTROL_SRCUPDATE, AST_CONTROL_UNHOLD, ast_debug, ast_log(), ast_moh_start(), ast_moh_stop(), ast_mutex_lock(), ast_mutex_unlock(), ast_setstate(), AST_SOFTHANGUP_DEV, AST_STATE_RING, AST_STATE_RINGING, AST_STATE_UP, dahdi_enable_ec(), dahdi_get_index(), dahdi_set_hook(), dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::digital, dahdi_pvt::dop, errno, ast_channel::hangupcause, ISTRUNK, dahdi_pvt::lock, LOG_WARNING, dahdi_pvt::mohinterpret, dahdi_pvt::outgoing, dahdi_pvt::priindication_oob, dahdi_pvt::radio, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_PRI, SIG_SS7, dahdi_pvt::span, SUB_REAL, dahdi_pvt::subs, and ast_channel::tech_pvt.
Referenced by dahdi_fixup().
{
   struct dahdi_pvt *p = chan->tech_pvt;
   int res=-1;
   int idx;
   int func = DAHDI_FLASH;
   ast_mutex_lock(&p->lock);
   idx = dahdi_get_index(chan, p, 0);
   ast_debug(1, "Requested indication %d on channel %s\n", condition, chan->name);
#ifdef HAVE_OPENR2
   if (p->mfcr2 && !p->mfcr2_call_accepted) {
      ast_mutex_unlock(&p->lock);
      /* if this is an R2 call and the call is not yet accepted, we don't want the
         tone indications to mess up with the MF tones */
      return 0;
   }
#endif
   if (idx == SUB_REAL) {
      switch (condition) {
      case AST_CONTROL_BUSY:
#ifdef HAVE_PRI
         if (p->priindication_oob && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))) {
            chan->hangupcause = AST_CAUSE_USER_BUSY;
            chan->_softhangup |= AST_SOFTHANGUP_DEV;
            res = 0;
         } else if (!p->progress &&
               ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))
               && p->pri && !p->outgoing) {
            if (p->pri->pri) {
               if (!pri_grab(p, p->pri)) {
#ifdef HAVE_PRI_PROG_W_CAUSE
                  pri_progress_with_cause(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1, PRI_CAUSE_USER_BUSY); /* cause = 17 */
#else
                  pri_progress(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1);
#endif
                  pri_rel(p->pri);
               }
               else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
            }
            p->progress = 1;
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_BUSY);
         } else
#endif
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_BUSY);
         break;
      case AST_CONTROL_RINGING:
#ifdef HAVE_PRI
         if ((!p->alerting) && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))
               && p->pri && !p->outgoing && (chan->_state != AST_STATE_UP)) {
            if (p->pri->pri) {
               if (!pri_grab(p, p->pri)) {
                  pri_acknowledge(p->pri->pri,p->call, PVT_TO_CHANNEL(p), !p->digital);
                  pri_rel(p->pri);
               }
               else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
            }
            p->alerting = 1;
         }
#endif
#ifdef HAVE_SS7
         if ((!p->alerting) && (p->sig == SIG_SS7) && p->ss7 && !p->outgoing && (chan->_state != AST_STATE_UP)) {
            if (p->ss7->ss7) {
               ss7_grab(p, p->ss7);
               if ((isup_far(p->ss7->ss7, p->ss7call)) != -1)
                  p->rlt = 1;
               if (p->rlt != 1) /* No need to send CPG if call will be RELEASE */
                  isup_cpg(p->ss7->ss7, p->ss7call, CPG_EVENT_ALERTING);
               p->alerting = 1;
               ss7_rel(p->ss7);
            }
         }
#endif
         res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_RINGTONE);
         if (chan->_state != AST_STATE_UP) {
            if ((chan->_state != AST_STATE_RING) ||
               ((p->sig != SIG_FXSKS) &&
             (p->sig != SIG_FXSLS) &&
             (p->sig != SIG_FXSGS)))
            ast_setstate(chan, AST_STATE_RINGING);
         }
         break;
      case AST_CONTROL_PROCEEDING:
         ast_debug(1,"Received AST_CONTROL_PROCEEDING on %s\n",chan->name);
#ifdef HAVE_PRI
         if (!p->proceeding && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))
               && p->pri && !p->outgoing) {
            if (p->pri->pri) {
               if (!pri_grab(p, p->pri)) {
                  pri_proceeding(p->pri->pri,p->call, PVT_TO_CHANNEL(p), !p->digital);
                  pri_rel(p->pri);
               }
               else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
            }
            p->proceeding = 1;
            p->dialing = 0;
         }
#endif
#ifdef HAVE_SS7
         /* This IF sends the FAR for an answered ALEG call */
         if (chan->_state == AST_STATE_UP && (p->rlt != 1) && (p->sig == SIG_SS7)){
            if ((isup_far(p->ss7->ss7, p->ss7call)) != -1)
               p->rlt = 1;
         }
         if (!p->proceeding && p->sig == SIG_SS7 && p->ss7 && !p->outgoing) {
            if (p->ss7->ss7) {
               ss7_grab(p, p->ss7);
               isup_acm(p->ss7->ss7, p->ss7call);
               p->proceeding = 1;
               ss7_rel(p->ss7);
            }
         }
#endif
         /* don't continue in ast_indicate */
         res = 0;
         break;
      case AST_CONTROL_PROGRESS:
         ast_debug(1,"Received AST_CONTROL_PROGRESS on %s\n",chan->name);
#ifdef HAVE_PRI
         p->digital = 0;   /* Digital-only calls isn't allows any inband progress messages */
         if (!p->progress && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))
               && p->pri && !p->outgoing) {
            if (p->pri->pri) {
               if (!pri_grab(p, p->pri)) {
#ifdef HAVE_PRI_PROG_W_CAUSE
                  pri_progress_with_cause(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1, -1);  /* no cause at all */
#else
                  pri_progress(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1);
#endif
                  pri_rel(p->pri);
               }
               else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
            }
            p->progress = 1;
         }
#endif
#ifdef HAVE_SS7
         if (!p->progress && p->sig==SIG_SS7 && p->ss7 && !p->outgoing) {
            if (p->ss7->ss7) {
               ss7_grab(p, p->ss7);
               isup_cpg(p->ss7->ss7, p->ss7call, CPG_EVENT_INBANDINFO);
               p->progress = 1;
               ss7_rel(p->ss7);
               /* enable echo canceler here on SS7 calls */
               dahdi_enable_ec(p);
            }
         }
#endif
         /* don't continue in ast_indicate */
         res = 0;
         break;
      case AST_CONTROL_CONGESTION:
         chan->hangupcause = AST_CAUSE_CONGESTION;
#ifdef HAVE_PRI
         if (p->priindication_oob && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))) {
            chan->hangupcause = AST_CAUSE_SWITCH_CONGESTION;
            chan->_softhangup |= AST_SOFTHANGUP_DEV;
            res = 0;
         } else if (!p->progress && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP))
               && p->pri && !p->outgoing) {
            if (p->pri) {
               if (!pri_grab(p, p->pri)) {
#ifdef HAVE_PRI_PROG_W_CAUSE
                  pri_progress_with_cause(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1, PRI_CAUSE_SWITCH_CONGESTION); /* cause = 42 */
#else
                  pri_progress(p->pri->pri,p->call, PVT_TO_CHANNEL(p), 1);
#endif
                  pri_rel(p->pri);
               } else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
            }
            p->progress = 1;
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
         } else
#endif
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
         break;
      case AST_CONTROL_HOLD:
#ifdef HAVE_PRI
         if (p->pri && !strcasecmp(p->mohinterpret, "passthrough")) {
            if (!pri_grab(p, p->pri)) {
               res = pri_notify(p->pri->pri, p->call, p->prioffset, PRI_NOTIFY_REMOTE_HOLD);
               pri_rel(p->pri);
            } else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
         } else
#endif
            ast_moh_start(chan, data, p->mohinterpret);
         break;
      case AST_CONTROL_UNHOLD:
#ifdef HAVE_PRI
         if (p->pri && !strcasecmp(p->mohinterpret, "passthrough")) {
            if (!pri_grab(p, p->pri)) {
               res = pri_notify(p->pri->pri, p->call, p->prioffset, PRI_NOTIFY_REMOTE_RETRIEVAL);
               pri_rel(p->pri);
            } else
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
         } else
#endif
            ast_moh_stop(chan);
         break;
      case AST_CONTROL_RADIO_KEY:
         if (p->radio)
            res = dahdi_set_hook(p->subs[idx].dfd, DAHDI_OFFHOOK);
         res = 0;
         break;
      case AST_CONTROL_RADIO_UNKEY:
         if (p->radio)
            res = dahdi_set_hook(p->subs[idx].dfd, DAHDI_RINGOFF);
         res = 0;
         break;
      case AST_CONTROL_FLASH:
         /* flash hookswitch */
         if (ISTRUNK(p) && (p->sig != SIG_PRI)) {
            /* Clear out the dial buffer */
            p->dop.dialstr[0] = '\0';
            if ((ioctl(p->subs[SUB_REAL].dfd,DAHDI_HOOK,&func) == -1) && (errno != EINPROGRESS)) {
               ast_log(LOG_WARNING, "Unable to flash external trunk on channel %s: %s\n",
                  chan->name, strerror(errno));
            } else
               res = 0;
         } else
            res = 0;
         break;
      case AST_CONTROL_SRCUPDATE:
         res = 0;
         break;
      case -1:
         res = tone_zone_play_tone(p->subs[idx].dfd, -1);
         break;
      }
   } else
      res = 0;
   ast_mutex_unlock(&p->lock);
   return res;
}
static void dahdi_link (struct dahdi_pvt * slave, struct dahdi_pvt * master) [static]
Definition at line 5100 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::channel, LOG_WARNING, dahdi_pvt::master, MAX_SLAVES, and dahdi_pvt::slaves.
Referenced by dahdi_bridge().
{
   int x;
   if (!slave || !master) {
      ast_log(LOG_WARNING, "Tried to link to/from NULL??\n");
      return;
   }
   for (x = 0; x < MAX_SLAVES; x++) {
      if (!master->slaves[x]) {
         master->slaves[x] = slave;
         break;
      }
   }
   if (x >= MAX_SLAVES) {
      ast_log(LOG_WARNING, "Replacing slave %d with new slave, %d\n", master->slaves[MAX_SLAVES - 1]->channel, slave->channel);
      master->slaves[MAX_SLAVES - 1] = slave;
   }
   if (slave->master)
      ast_log(LOG_WARNING, "Replacing master %d with new master, %d\n", slave->master->channel, master->channel);
   slave->master = master;
   ast_debug(1, "Making %d slave to master %d at %d\n", slave->channel, master->channel, x);
}
static struct ast_channel * dahdi_new (struct dahdi_pvt * i, int state, int startpbx, int idx, int law, int transfercapability) [static, read]
Definition at line 7417 of file chan_dahdi.c.
References accountcode, dahdi_pvt::accountcode, dahdi_pvt::adsi, ast_channel::adsicpe, ast_channel::amaflags, dahdi_pvt::amaflags, AST_ADSI_UNAVAILABLE, ast_channel_alloc, ast_channel_set_fd(), ast_copy_string(), ast_debug, ast_devstate_changed_literal(), ast_dsp_new(), ast_dsp_set_busy_count(), ast_dsp_set_busy_pattern(), ast_dsp_set_call_progress_zone(), ast_dsp_set_digitmode(), ast_dsp_set_features(), AST_FORMAT_ALAW, AST_FORMAT_ULAW, ast_hangup(), ast_jb_configure(), ast_log(), ast_module_ref(), ast_pbx_start(), ast_random(), ast_state_chan2dev(), AST_STATE_RING, ast_str_alloca, ast_str_buffer(), ast_str_set(), ast_strdup, ast_string_field_set, ast_strlen_zero(), AST_TRANS_CAP_DIGITAL, ast_transfercapability2str(), dahdi_pvt::busy_quietlength, dahdi_pvt::busy_tonelength, dahdi_pvt::busycount, dahdi_pvt::busydetect, dahdi_pvt::call_forward, dahdi_pvt::callgroup, ast_channel::callgroup, dahdi_pvt::callingpres, dahdi_pvt::callprogress, CALLPROGRESS_FAX_INCOMING, CALLPROGRESS_FAX_OUTGOING, CALLPROGRESS_PROGRESS, CANBUSYDETECT, CANPROGRESSDETECT, CHAN_PSEUDO, dahdi_pvt::channel, ast_channel::cid, ast_callerid::cid_ani, dahdi_pvt::cid_ani2, ast_callerid::cid_ani2, ast_callerid::cid_dnid, dahdi_pvt::cid_name, dahdi_pvt::cid_num, ast_callerid::cid_pres, ast_callerid::cid_rdnis, dahdi_pvt::cid_ton, ast_callerid::cid_ton, ast_channel::context, dahdi_pvt::context, dahdi_confmute(), dahdi_setlinear(), dahdi_subchannel::dfd, dahdi_pvt::digital, dahdi_pvt::dnid, dahdi_pvt::dsp, DSP_DIGITMODE_DTMF, DSP_FEATURE_BUSY_DETECT, DSP_FEATURE_CALL_PROGRESS, DSP_FEATURE_DIGIT_DETECT, DSP_FEATURE_FAX_DETECT, DSP_FEATURE_WAITDIALTONE, dahdi_pvt::dsp_features, DSP_PROGRESS_TALK, dahdi_pvt::dtmfrelax, errno, ast_channel::exten, dahdi_pvt::exten, dahdi_pvt::fake_event, global_jbconf, dahdi_pvt::hardwaredtmf, language, dahdi_pvt::language, dahdi_subchannel::linear, LOG_WARNING, dahdi_pvt::muting, ast_variable::name, ast_channel::nativeformats, NEED_MFDETECT, ast_variable::next, dahdi_pvt::outgoing, dahdi_pvt::owner, dahdi_subchannel::owner, dahdi_pvt::parkinglot, pbx_builtin_setvar_helper(), dahdi_pvt::pickupgroup, ast_channel::pickupgroup, ast_channel::rawreadformat, ast_channel::rawwriteformat, dahdi_pvt::rdnis, ast_channel::readformat, ast_channel::rings, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSKS, SIG_PRI, SIG_SS7, SUB_REAL, dahdi_pvt::subs, ast_channel::tech, ast_channel::tech_pvt, ast_channel::transfercapability, ast_variable::value, dahdi_pvt::vars, dahdi_pvt::waitfordialtone, and ast_channel::writeformat.
Referenced by dahdi_handle_event(), dahdi_request(), handle_init_event(), and mwi_thread().
{
   struct ast_channel *tmp;
   int deflaw;
   int res;
   int x,y;
   int features;
   struct ast_str *chan_name;
   struct ast_variable *v;
   struct dahdi_params ps;
   if (i->subs[idx].owner) {
      ast_log(LOG_WARNING, "Channel %d already has a %s call\n", i->channel,subnames[idx]);
      return NULL;
   }
   y = 1;
   chan_name = ast_str_alloca(32);
   do {
#ifdef HAVE_PRI
      if (i->bearer || (i->pri && (i->sig == SIG_FXSKS)))
         ast_str_set(&chan_name, 0, "%d:%d-%d", i->pri->trunkgroup, i->channel, y);
      else
#endif
      if (i->channel == CHAN_PSEUDO)
         ast_str_set(&chan_name, 0, "pseudo-%ld", ast_random());
      else
         ast_str_set(&chan_name, 0, "%d-%d", i->channel, y);
      for (x = 0; x < 3; x++) {
         if ((idx != x) && i->subs[x].owner && !strcasecmp(ast_str_buffer(chan_name), i->subs[x].owner->name + 6))
            break;
      }
      y++;
   } while (x < 3);
   tmp = ast_channel_alloc(0, state, i->cid_num, i->cid_name, i->accountcode, i->exten, i->context, i->amaflags, "DAHDI/%s", ast_str_buffer(chan_name));
   if (!tmp)
      return NULL;
   tmp->tech = &dahdi_tech;
   memset(&ps, 0, sizeof(ps));
   ps.channo = i->channel;
   res = ioctl(i->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &ps);
   if (res) {
      ast_log(LOG_WARNING, "Unable to get parameters, assuming MULAW: %s\n", strerror(errno));
      ps.curlaw = DAHDI_LAW_MULAW;
   }
   if (ps.curlaw == DAHDI_LAW_ALAW)
      deflaw = AST_FORMAT_ALAW;
   else
      deflaw = AST_FORMAT_ULAW;
   if (law) {
      if (law == DAHDI_LAW_ALAW)
         deflaw = AST_FORMAT_ALAW;
      else
         deflaw = AST_FORMAT_ULAW;
   }
   ast_channel_set_fd(tmp, 0, i->subs[idx].dfd);
   tmp->nativeformats = deflaw;
   /* Start out assuming ulaw since it's smaller :) */
   tmp->rawreadformat = deflaw;
   tmp->readformat = deflaw;
   tmp->rawwriteformat = deflaw;
   tmp->writeformat = deflaw;
   i->subs[idx].linear = 0;
   dahdi_setlinear(i->subs[idx].dfd, i->subs[idx].linear);
   features = 0;
   if (idx == SUB_REAL) {
      if (i->busydetect && CANBUSYDETECT(i))
         features |= DSP_FEATURE_BUSY_DETECT;
      if ((i->callprogress & CALLPROGRESS_PROGRESS) && CANPROGRESSDETECT(i))
         features |= DSP_FEATURE_CALL_PROGRESS;
      if ((i->waitfordialtone) && CANPROGRESSDETECT(i))
         features |= DSP_FEATURE_WAITDIALTONE;
      if ((!i->outgoing && (i->callprogress & CALLPROGRESS_FAX_INCOMING)) ||
         (i->outgoing && (i->callprogress & CALLPROGRESS_FAX_OUTGOING))) {
         features |= DSP_FEATURE_FAX_DETECT;
      }
      x = DAHDI_TONEDETECT_ON | DAHDI_TONEDETECT_MUTE;
      if (ioctl(i->subs[idx].dfd, DAHDI_TONEDETECT, &x)) {
         i->hardwaredtmf = 0;
         features |= DSP_FEATURE_DIGIT_DETECT;
      } else if (NEED_MFDETECT(i)) {
         i->hardwaredtmf = 1;
         features |= DSP_FEATURE_DIGIT_DETECT;
      }
   }
   if (features) {
      if (i->dsp) {
         ast_debug(1, "Already have a dsp on %s?\n", tmp->name);
      } else {
         if (i->channel != CHAN_PSEUDO)
            i->dsp = ast_dsp_new();
         else
            i->dsp = NULL;
         if (i->dsp) {
            i->dsp_features = features;
#if defined(HAVE_PRI) || defined(HAVE_SS7)
            /* We cannot do progress detection until receives PROGRESS message */
            if (i->outgoing && ((i->sig == SIG_PRI) || (i->sig == SIG_BRI) || (i->sig == SIG_BRI_PTMP) || (i->sig == SIG_SS7))) {
               /* Remember requested DSP features, don't treat
                  talking as ANSWER */
               i->dsp_features = features & ~DSP_PROGRESS_TALK;
               features = 0;
            }
#endif
            ast_dsp_set_features(i->dsp, features);
            ast_dsp_set_digitmode(i->dsp, DSP_DIGITMODE_DTMF | i->dtmfrelax);
            if (!ast_strlen_zero(progzone))
               ast_dsp_set_call_progress_zone(i->dsp, progzone);
            if (i->busydetect && CANBUSYDETECT(i)) {
               ast_dsp_set_busy_count(i->dsp, i->busycount);
               ast_dsp_set_busy_pattern(i->dsp, i->busy_tonelength, i->busy_quietlength);
            }
         }
      }
   }
   if (state == AST_STATE_RING)
      tmp->rings = 1;
   tmp->tech_pvt = i;
   if ((i->sig == SIG_FXOKS) || (i->sig == SIG_FXOGS) || (i->sig == SIG_FXOLS)) {
      /* Only FXO signalled stuff can be picked up */
      tmp->callgroup = i->callgroup;
      tmp->pickupgroup = i->pickupgroup;
   }
   if (!ast_strlen_zero(i->parkinglot))
      ast_string_field_set(tmp, parkinglot, i->parkinglot);
   if (!ast_strlen_zero(i->language))
      ast_string_field_set(tmp, language, i->language);
   if (!i->owner)
      i->owner = tmp;
   if (!ast_strlen_zero(i->accountcode))
      ast_string_field_set(tmp, accountcode, i->accountcode);
   if (i->amaflags)
      tmp->amaflags = i->amaflags;
   i->subs[idx].owner = tmp;
   ast_copy_string(tmp->context, i->context, sizeof(tmp->context));
   ast_string_field_set(tmp, call_forward, i->call_forward);
   /* If we've been told "no ADSI" then enforce it */
   if (!i->adsi)
      tmp->adsicpe = AST_ADSI_UNAVAILABLE;
   if (!ast_strlen_zero(i->exten))
      ast_copy_string(tmp->exten, i->exten, sizeof(tmp->exten));
   if (!ast_strlen_zero(i->rdnis))
      tmp->cid.cid_rdnis = ast_strdup(i->rdnis);
   if (!ast_strlen_zero(i->dnid))
      tmp->cid.cid_dnid = ast_strdup(i->dnid);
   /* Don't use ast_set_callerid() here because it will
    * generate a needless NewCallerID event */
#ifdef PRI_ANI
   if (!ast_strlen_zero(i->cid_ani))
      tmp->cid.cid_ani = ast_strdup(i->cid_ani);
   else
      tmp->cid.cid_ani = ast_strdup(i->cid_num);
#else
   tmp->cid.cid_ani = ast_strdup(i->cid_num);
#endif
   tmp->cid.cid_pres = i->callingpres;
   tmp->cid.cid_ton = i->cid_ton;
   tmp->cid.cid_ani2 = i->cid_ani2;
#if defined(HAVE_PRI) || defined(HAVE_SS7)
   tmp->transfercapability = transfercapability;
   pbx_builtin_setvar_helper(tmp, "TRANSFERCAPABILITY", ast_transfercapability2str(transfercapability));
   if (transfercapability & AST_TRANS_CAP_DIGITAL)
      i->digital = 1;
   /* Assume calls are not idle calls unless we're told differently */
   i->isidlecall = 0;
   i->alreadyhungup = 0;
#endif
   /* clear the fake event in case we posted one before we had ast_channel */
   i->fake_event = 0;
   /* Assure there is no confmute on this channel */
   dahdi_confmute(i, 0);
   i->muting = 0;
   /* Configure the new channel jb */
   ast_jb_configure(tmp, &global_jbconf);
   ast_devstate_changed_literal(ast_state_chan2dev(state), tmp->name);
   for (v = i->vars ; v ; v = v->next)
      pbx_builtin_setvar_helper(tmp, v->name, v->value);
   if (startpbx) {
#ifdef HAVE_OPENR2
      if (i->mfcr2call) {
         pbx_builtin_setvar_helper(tmp, "MFCR2_CATEGORY", openr2_proto_get_category_string(i->mfcr2_recvd_category));
      }
#endif
      if (ast_pbx_start(tmp)) {
         ast_log(LOG_WARNING, "Unable to start PBX on %s\n", tmp->name);
         ast_hangup(tmp);
         i->owner = NULL;
         return NULL;
      }
   }
   ast_module_ref(ast_module_info->self);
   return tmp;
}
static int dahdi_open (char * fn) [static]
Definition at line 2090 of file chan_dahdi.c.
References ast_log(), chan, errno, LOG_WARNING, and READ_SIZE.
Referenced by alloc_sub(), duplicate_pseudo(), and mkintf().
{
   int fd;
   int isnum;
   int chan = 0;
   int bs;
   int x;
   isnum = 1;
   for (x = 0; x < strlen(fn); x++) {
      if (!isdigit(fn[x])) {
         isnum = 0;
         break;
      }
   }
   if (isnum) {
      chan = atoi(fn);
      if (chan < 1) {
         ast_log(LOG_WARNING, "Invalid channel number '%s'\n", fn);
         return -1;
      }
      fn = "/dev/dahdi/channel";
   }
   fd = open(fn, O_RDWR | O_NONBLOCK);
   if (fd < 0) {
      ast_log(LOG_WARNING, "Unable to open '%s': %s\n", fn, strerror(errno));
      return -1;
   }
   if (chan) {
      if (ioctl(fd, DAHDI_SPECIFY, &chan)) {
         x = errno;
         close(fd);
         errno = x;
         ast_log(LOG_WARNING, "Unable to specify channel %d: %s\n", chan, strerror(errno));
         return -1;
      }
   }
   bs = READ_SIZE;
   if (ioctl(fd, DAHDI_SET_BLOCKSIZE, &bs) == -1) {
      ast_log(LOG_WARNING, "Unable to set blocksize '%d': %s\n", bs,  strerror(errno));
      x = errno;
      close(fd);
      errno = x;
      return -1;
   }
   return fd;
}
static void dahdi_queue_frame (struct dahdi_pvt * p, struct ast_frame * f, void * data) [static]
Definition at line 1544 of file chan_dahdi.c.
References ast_channel_trylock, ast_channel_unlock, ast_mutex_lock(), ast_mutex_unlock(), ast_queue_frame(), DEADLOCK_AVOIDANCE, dahdi_pvt::lock, dahdi_pvt::owner, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, and SIG_SS7.
Referenced by action_dahdidialoffhook().
{
#ifdef HAVE_PRI
   struct dahdi_pri *pri = (struct dahdi_pri*) data;
#endif
#ifdef HAVE_SS7
   struct dahdi_ss7 *ss7 = (struct dahdi_ss7*) data;
#endif
   /* We must unlock the PRI to avoid the possibility of a deadlock */
#if defined(HAVE_PRI) || defined(HAVE_SS7)
   if (data) {
      switch (p->sig) {
#ifdef HAVE_PRI
      case SIG_BRI:
      case SIG_BRI_PTMP:
      case SIG_PRI:
         ast_mutex_unlock(&pri->lock);
         break;
#endif
#ifdef HAVE_SS7
      case SIG_SS7:
         ast_mutex_unlock(&ss7->lock);
         break;
#endif
      default:
         break;
      }
   }
#endif
   for (;;) {
      if (p->owner) {
         if (ast_channel_trylock(p->owner)) {
            DEADLOCK_AVOIDANCE(&p->lock);
         } else {
            ast_queue_frame(p->owner, f);
            ast_channel_unlock(p->owner);
            break;
         }
      } else
         break;
   }
#if defined(HAVE_PRI) || defined(HAVE_SS7)
   if (data) {
      switch (p->sig) {
#ifdef HAVE_PRI
      case SIG_BRI:
      case SIG_BRI_PTMP:
      case SIG_PRI:
         ast_mutex_lock(&pri->lock);
         break;
#endif
#ifdef HAVE_SS7
      case SIG_SS7:
         ast_mutex_lock(&ss7->lock);
         break;
#endif
      default:
         break;
      }
   }
#endif
}
static struct ast_frame * dahdi_read (struct ast_channel * ast) [static, read]
Definition at line 6717 of file chan_dahdi.c.
References __dahdi_exception(), ast_channel::_state, ast_clear_flag, AST_CONTROL_ANSWER, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_FLASH, AST_CONTROL_HOLD, AST_CONTROL_RADIO_KEY, AST_CONTROL_RADIO_UNKEY, AST_CONTROL_RINGING, AST_CONTROL_UNHOLD, ast_debug, ast_dsp_get_tcount(), ast_dsp_get_tstate(), ast_dsp_process(), ast_dsp_set_features(), ast_dsp_was_muted(), AST_FLAG_BLOCKING, AST_FLAG_EXCEPTION, AST_FORMAT_ALAW, AST_FORMAT_SLINEAR, AST_FORMAT_ULAW, AST_FRAME_CONTROL, AST_FRAME_DTMF, AST_FRAME_NULL, AST_FRAME_TEXT, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_getformatname(), ast_log(), ast_mutex_trylock(), ast_mutex_unlock(), ast_null_frame, ast_set_callerid(), ast_set_flag, ast_setstate(), AST_STATE_DIALING, AST_STATE_RINGING, AST_STATE_UP, ast_strlen_zero(), ast_tv(), ast_tvdiff_ms(), ast_tvnow(), ast_verb, dahdi_subchannel::buffer, dahdi_pvt::busydetect, dahdi_pvt::callprogress, dahdi_pvt::callwaitcas, dahdi_pvt::callwaitingrepeat, dahdi_pvt::callwaitrings, dahdi_pvt::channel, CHANNEL_DEADLOCK_AVOIDANCE, CHECK_BLOCKING, dahdi_pvt::cidcwexpire, dahdi_pvt::cidrings, dahdi_pvt::cidspill, dahdi_callwait(), dahdi_confmute(), dahdi_get_index(), dahdi_handle_dtmfup(), DAHDI_OVERLAPDIAL_INCOMING, DAHDI_OVERLAPDIAL_OUTGOING, dahdi_setlinear(), ast_frame::data, ast_frame::datalen, ast_frame::delivery, dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::dop, dahdi_pvt::dsp, DSP_FEATURE_WAITDIALTONE, dahdi_pvt::dsp_features, DSP_TONE_STATE_DIALTONE, DSP_TONE_STATE_RINGING, errno, dahdi_subchannel::f, dahdi_pvt::fake_event, dahdi_pvt::firstradio, ast_frame::frametype, dahdi_pvt::ignoredtmf, dahdi_pvt::inalarm, dahdi_subchannel::inthreeway, dahdi_pvt::lastcid_name, dahdi_pvt::lastcid_num, dahdi_subchannel::linear, dahdi_pvt::lock, LOG_DEBUG, LOG_WARNING, ast_frame::mallocd, dahdi_pvt::muting, dahdi_subchannel::needanswer, dahdi_subchannel::needbusy, dahdi_subchannel::needcallerid, dahdi_subchannel::needcongestion, dahdi_subchannel::needflash, dahdi_subchannel::needhold, dahdi_subchannel::needringing, dahdi_subchannel::needunhold, ast_frame::offset, dahdi_pvt::oprmode, dahdi_pvt::outgoing, dahdi_pvt::owner, ast_frame::ptr, dahdi_pvt::pulsedial, dahdi_pvt::radio, ast_channel::rawreadformat, READ_SIZE, restore_conference(), ast_channel::rings, dahdi_pvt::ringt, S_OR, ast_frame::samples, send_callerid(), dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_PRI, ast_frame::src, SUB_CALLWAIT, SUB_REAL, ast_frame::subclass, dahdi_pvt::subs, dahdi_pvt::tdd, tdd_feed(), ast_channel::tech_pvt, dahdi_pvt::waitfordialtone, and dahdi_pvt::waitingfordt.
{
   struct dahdi_pvt *p = ast->tech_pvt;
   int res;
   int idx;
   void *readbuf;
   struct ast_frame *f;
   while (ast_mutex_trylock(&p->lock)) {
      CHANNEL_DEADLOCK_AVOIDANCE(ast);
   }
   idx = dahdi_get_index(ast, p, 0);
   /* Hang up if we don't really exist */
   if (idx < 0)   {
      ast_log(LOG_WARNING, "We dont exist?\n");
      ast_mutex_unlock(&p->lock);
      return NULL;
   }
   if ((p->radio || (p->oprmode < 0)) && p->inalarm) {
      ast_mutex_unlock(&p->lock);
      return NULL;
   }
   p->subs[idx].f.frametype = AST_FRAME_NULL;
   p->subs[idx].f.datalen = 0;
   p->subs[idx].f.samples = 0;
   p->subs[idx].f.mallocd = 0;
   p->subs[idx].f.offset = 0;
   p->subs[idx].f.subclass = 0;
   p->subs[idx].f.delivery = ast_tv(0,0);
   p->subs[idx].f.src = "dahdi_read";
   p->subs[idx].f.data.ptr = NULL;
   /* make sure it sends initial key state as first frame */
   if ((p->radio || (p->oprmode < 0)) && (!p->firstradio))
   {
      struct dahdi_params ps;
      memset(&ps, 0, sizeof(ps));
      ps.channo = p->channel;
      if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &ps) < 0) {
         ast_mutex_unlock(&p->lock);
         return NULL;
      }
      p->firstradio = 1;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      if (ps.rxisoffhook)
      {
         p->subs[idx].f.subclass = AST_CONTROL_RADIO_KEY;
      }
      else
      {
         p->subs[idx].f.subclass = AST_CONTROL_RADIO_UNKEY;
      }
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
   if (p->ringt == 1) {
      ast_mutex_unlock(&p->lock);
      return NULL;
   }
   else if (p->ringt > 0)
      p->ringt--;
#ifdef HAVE_OPENR2
   if (p->mfcr2) {
      openr2_chan_process_event(p->r2chan);
   }
#endif
   if (p->subs[idx].needringing) {
      /* Send ringing frame if requested */
      p->subs[idx].needringing = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_RINGING;
      ast_setstate(ast, AST_STATE_RINGING);
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
   if (p->subs[idx].needbusy) {
      /* Send busy frame if requested */
      p->subs[idx].needbusy = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_BUSY;
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
   if (p->subs[idx].needcongestion) {
      /* Send congestion frame if requested */
      p->subs[idx].needcongestion = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_CONGESTION;
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
   if (p->subs[idx].needcallerid) {
      ast_set_callerid(ast, S_OR(p->lastcid_num, NULL),
                     S_OR(p->lastcid_name, NULL),
                     S_OR(p->lastcid_num, NULL)
                     );
      p->subs[idx].needcallerid = 0;
   }
   if (p->subs[idx].needanswer) {
      /* Send answer frame if requested */
      p->subs[idx].needanswer = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_ANSWER;
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
#ifdef HAVE_OPENR2
   if (p->mfcr2 && openr2_chan_get_read_enabled(p->r2chan)) {
      /* openr2 took care of reading and handling any event
        (needanswer, needbusy etc), if we continue we will read()
        twice, lets just return a null frame. This should only
        happen when openr2 is dialing out */
      ast_mutex_unlock(&p->lock);
      return &ast_null_frame;
   }
#endif
   if (p->subs[idx].needflash) {
      /* Send answer frame if requested */
      p->subs[idx].needflash = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_FLASH;
      ast_mutex_unlock(&p->lock);
      return &p->subs[idx].f;
   }
   if (p->subs[idx].needhold) {
      /* Send answer frame if requested */
      p->subs[idx].needhold = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_HOLD;
      ast_mutex_unlock(&p->lock);
      ast_debug(1, "Sending hold on '%s'\n", ast->name);
      return &p->subs[idx].f;
   }
   if (p->subs[idx].needunhold) {
      /* Send answer frame if requested */
      p->subs[idx].needunhold = 0;
      p->subs[idx].f.frametype = AST_FRAME_CONTROL;
      p->subs[idx].f.subclass = AST_CONTROL_UNHOLD;
      ast_mutex_unlock(&p->lock);
      ast_debug(1, "Sending unhold on '%s'\n", ast->name);
      return &p->subs[idx].f;
   }
   if (ast->rawreadformat == AST_FORMAT_SLINEAR) {
      if (!p->subs[idx].linear) {
         p->subs[idx].linear = 1;
         res = dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
         if (res)
            ast_log(LOG_WARNING, "Unable to set channel %d (index %d) to linear mode.\n", p->channel, idx);
      }
   } else if ((ast->rawreadformat == AST_FORMAT_ULAW) ||
      (ast->rawreadformat == AST_FORMAT_ALAW)) {
      if (p->subs[idx].linear) {
         p->subs[idx].linear = 0;
         res = dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
         if (res)
            ast_log(LOG_WARNING, "Unable to set channel %d (index %d) to companded mode.\n", p->channel, idx);
      }
   } else {
      ast_log(LOG_WARNING, "Don't know how to read frames in format %s\n", ast_getformatname(ast->rawreadformat));
      ast_mutex_unlock(&p->lock);
      return NULL;
   }
   readbuf = ((unsigned char *)p->subs[idx].buffer) + AST_FRIENDLY_OFFSET;
   CHECK_BLOCKING(ast);
   res = read(p->subs[idx].dfd, readbuf, p->subs[idx].linear ? READ_SIZE * 2 : READ_SIZE);
   ast_clear_flag(ast, AST_FLAG_BLOCKING);
   /* Check for hangup */
   if (res < 0) {
      f = NULL;
      if (res == -1) {
         if (errno == EAGAIN) {
            /* Return "NULL" frame if there is nobody there */
            ast_mutex_unlock(&p->lock);
            return &p->subs[idx].f;
         } else if (errno == ELAST) {
            f = __dahdi_exception(ast);
         } else
            ast_log(LOG_WARNING, "dahdi_rec: %s\n", strerror(errno));
      }
      ast_mutex_unlock(&p->lock);
      return f;
   }
   if (res != (p->subs[idx].linear ? READ_SIZE * 2 : READ_SIZE)) {
      ast_debug(1, "Short read (%d/%d), must be an event...\n", res, p->subs[idx].linear ? READ_SIZE * 2 : READ_SIZE);
      f = __dahdi_exception(ast);
      ast_mutex_unlock(&p->lock);
      return f;
   }
   if (p->tdd) { /* if in TDD mode, see if we receive that */
      int c;
      c = tdd_feed(p->tdd,readbuf,READ_SIZE);
      if (c < 0) {
         ast_debug(1,"tdd_feed failed\n");
         ast_mutex_unlock(&p->lock);
         return NULL;
      }
      if (c) { /* if a char to return */
         p->subs[idx].f.subclass = 0;
         p->subs[idx].f.frametype = AST_FRAME_TEXT;
         p->subs[idx].f.mallocd = 0;
         p->subs[idx].f.offset = AST_FRIENDLY_OFFSET;
         p->subs[idx].f.data.ptr = p->subs[idx].buffer + AST_FRIENDLY_OFFSET;
         p->subs[idx].f.datalen = 1;
         *((char *) p->subs[idx].f.data.ptr) = c;
         ast_mutex_unlock(&p->lock);
         return &p->subs[idx].f;
      }
   }
   /* Ensure the CW timer decrements only on a single subchannel */
   if (p->callwaitingrepeat && dahdi_get_index(ast, p, 1) == SUB_REAL) {
      p->callwaitingrepeat--;
   }
   if (p->cidcwexpire)
      p->cidcwexpire--;
   /* Repeat callwaiting */
   if (p->callwaitingrepeat == 1) {
      p->callwaitrings++;
      dahdi_callwait(ast);
   }
   /* Expire CID/CW */
   if (p->cidcwexpire == 1) {
      ast_verb(3, "CPE does not support Call Waiting Caller*ID.\n");
      restore_conference(p);
   }
   if (p->subs[idx].linear) {
      p->subs[idx].f.datalen = READ_SIZE * 2;
   } else
      p->subs[idx].f.datalen = READ_SIZE;
   /* Handle CallerID Transmission */
   if ((p->owner == ast) && p->cidspill &&((ast->_state == AST_STATE_UP) || (ast->rings == p->cidrings))) {
      send_callerid(p);
   }
   p->subs[idx].f.frametype = AST_FRAME_VOICE;
   p->subs[idx].f.subclass = ast->rawreadformat;
   p->subs[idx].f.samples = READ_SIZE;
   p->subs[idx].f.mallocd = 0;
   p->subs[idx].f.offset = AST_FRIENDLY_OFFSET;
   p->subs[idx].f.data.ptr = p->subs[idx].buffer + AST_FRIENDLY_OFFSET / sizeof(p->subs[idx].buffer[0]);
#if 0
   ast_debug(1, "Read %d of voice on %s\n", p->subs[idx].f.datalen, ast->name);
#endif
   if (p->dialing || /* Transmitting something */
      (idx && (ast->_state != AST_STATE_UP)) || /* Three-way or callwait that isn't up */
      ((idx == SUB_CALLWAIT) && !p->subs[SUB_CALLWAIT].inthreeway) /* Inactive and non-confed call-wait */
      ) {
      /* Whoops, we're still dialing, or in a state where we shouldn't transmit....
         don't send anything */
      p->subs[idx].f.frametype = AST_FRAME_NULL;
      p->subs[idx].f.subclass = 0;
      p->subs[idx].f.samples = 0;
      p->subs[idx].f.mallocd = 0;
      p->subs[idx].f.offset = 0;
      p->subs[idx].f.data.ptr = NULL;
      p->subs[idx].f.datalen= 0;
   }
   if (p->dsp && (!p->ignoredtmf || p->callwaitcas || p->busydetect || p->callprogress || p->waitingfordt.tv_sec) && !idx) {
      /* Perform busy detection etc on the dahdi line */
      int mute;
      f = ast_dsp_process(ast, p->dsp, &p->subs[idx].f);
      /* Check if DSP code thinks we should be muting this frame and mute the conference if so */
      mute = ast_dsp_was_muted(p->dsp);
      if (p->muting != mute) {
         p->muting = mute;
         dahdi_confmute(p, mute);
      }
      if (f) {
         if ((f->frametype == AST_FRAME_CONTROL) && (f->subclass == AST_CONTROL_BUSY)) {
            if ((ast->_state == AST_STATE_UP) && !p->outgoing) {
               /* Treat this as a "hangup" instead of a "busy" on the assumption that
                  a busy */
               f = NULL;
            }
         } else if (f->frametype == AST_FRAME_DTMF) {
#ifdef HAVE_PRI
            if (!p->proceeding && ((p->sig == SIG_PRI) || (p->sig == SIG_BRI) || (p->sig == SIG_BRI_PTMP)) && p->pri &&
               ((!p->outgoing && (p->pri->overlapdial & DAHDI_OVERLAPDIAL_INCOMING)) ||
               (p->outgoing && (p->pri->overlapdial & DAHDI_OVERLAPDIAL_OUTGOING)))) {
               /* Don't accept in-band DTMF when in overlap dial mode */
               f->frametype = AST_FRAME_NULL;
               f->subclass = 0;
            }
#endif
            /* DSP clears us of being pulse */
            p->pulsedial = 0;
         } else if (p->waitingfordt.tv_sec) {
            if (ast_tvdiff_ms(ast_tvnow(), p->waitingfordt) >= p->waitfordialtone ) {
               p->waitingfordt.tv_sec = 0;
               ast_log(LOG_WARNING, "Never saw dialtone on channel %d\n", p->channel);
               f=NULL;
            } else if (f->frametype == AST_FRAME_VOICE) {
               f->frametype = AST_FRAME_NULL;
               f->subclass = 0;
               if ((ast_dsp_get_tstate(p->dsp) == DSP_TONE_STATE_DIALTONE || ast_dsp_get_tstate(p->dsp) == DSP_TONE_STATE_RINGING) && ast_dsp_get_tcount(p->dsp) > 9) {
                  p->waitingfordt.tv_sec = 0;
                  p->dsp_features &= ~DSP_FEATURE_WAITDIALTONE;
                  ast_dsp_set_features(p->dsp, p->dsp_features);
                  ast_log(LOG_DEBUG, "Got 10 samples of dialtone!\n");
                  if (!ast_strlen_zero(p->dop.dialstr)) { /* Dial deferred digits */
                     res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_DIAL, &p->dop);
                     if (res < 0) {
                        ast_log(LOG_WARNING, "Unable to initiate dialing on trunk channel %d\n", p->channel);
                        p->dop.dialstr[0] = '\0';
                        ast_mutex_unlock(&p->lock);
                        return NULL;
                     } else {
                        ast_log(LOG_DEBUG, "Sent deferred digit string: %s\n", p->dop.dialstr);
                        p->dialing = 1;
                        p->dop.dialstr[0] = '\0';
                        p->dop.op = DAHDI_DIAL_OP_REPLACE;
                        ast_setstate(ast, AST_STATE_DIALING);
                     }
                  }
               }
            }
         }
      }
   } else
      f = &p->subs[idx].f;
   if (f && (f->frametype == AST_FRAME_DTMF))
      dahdi_handle_dtmfup(ast, idx, &f);
   /* If we have a fake_event, trigger exception to handle it */
   if (p->fake_event)
      ast_set_flag(ast, AST_FLAG_EXCEPTION);
   ast_mutex_unlock(&p->lock);
   return f;
}
static struct ast_channel * dahdi_request (const char * type, int format, void * data, int * cause) [static, read]
Definition at line 10834 of file chan_dahdi.c.
References alloc_sub(), AST_CAUSE_BUSY, AST_CAUSE_CONGESTION, AST_CDR_CALLWAIT, ast_debug, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), AST_STATE_RESERVED, ast_strdupa, AST_TRANS_CAP_DIGITAL, ast_verbose, available(), ast_channel::cdrflags, CHAN_PSEUDO, dahdi_pvt::channel, dahdi_pvt::confirmanswer, dahdi_new(), dahdi_subchannel::dfd, dahdi_pvt::digital, dahdi_pvt::distinctivering, duplicate_pseudo(), iflist, dahdi_pvt::inalarm, dahdi_pvt::lock, lock, LOG_DEBUG, LOG_NOTICE, LOG_WARNING, dahdi_pvt::next, dahdi_pvt::outgoing, dahdi_pvt::owner, dahdi_pvt::prev, restart_monitor(), s, dahdi_pvt::sig, SIG_FXSKS, strsep(), SUB_CALLWAIT, SUB_REAL, dahdi_pvt::subs, and ast_channel::transfercapability.
10835 {
10836    ast_group_t groupmatch = 0;
10837    int channelmatch = -1;
10838    int roundrobin = 0;
10839    int callwait = 0;
10840    int busy = 0;
10841    struct dahdi_pvt *p;
10842    struct ast_channel *tmp = NULL;
10843    char *dest=NULL;
10844    int x;
10845    char *s;
10846    char opt=0;
10847    int res=0, y=0;
10848    int backwards = 0;
10849 #ifdef HAVE_PRI
10850    int crv;
10851    int bearer = -1;
10852    int trunkgroup;
10853    struct dahdi_pri *pri=NULL;
10854 #endif
10855    struct dahdi_pvt *exitpvt, *start, *end;
10856    ast_mutex_t *lock;
10857    int channelmatched = 0;
10858    int groupmatched = 0;
10859
10860    /*
10861     * data is ---v
10862     * Dial(DAHDI/pseudo[/extension])
10863     * Dial(DAHDI/<channel#>[c|r<cadance#>|d][/extension])
10864     * Dial(DAHDI/<trunk_group#>:<crv#>[c|r<cadance#>|d][/extension])
10865     * Dial(DAHDI/(g|G|r|R)<group#(0-63)>[c|r<cadance#>|d][/extension])
10866     *
10867     * g - channel group allocation search forward
10868     * G - channel group allocation search backward
10869     * r - channel group allocation round robin search forward
10870     * R - channel group allocation round robin search backward
10871     *
10872     * c - Wait for DTMF digit to confirm answer
10873     * r<cadance#> - Set distintive ring cadance number
10874     * d - Force bearer capability for ISDN/SS7 call to digital.
10875     */
10876
10877    /* Assume we're locking the iflock */
10878    lock = &iflock;
10879    start = iflist;
10880    end = ifend;
10881    if (data) {
10882       dest = ast_strdupa((char *)data);
10883    } else {
10884       ast_log(LOG_WARNING, "Channel requested with no data\n");
10885       return NULL;
10886    }
10887    if (toupper(dest[0]) == 'G' || toupper(dest[0])=='R') {
10888       /* Retrieve the group number */
10889       char *stringp;
10890
10891       stringp = dest + 1;
10892       s = strsep(&stringp, "/");
10893       if ((res = sscanf(s, "%30d%1c%30d", &x, &opt, &y)) < 1) {
10894          ast_log(LOG_WARNING, "Unable to determine group for data %s\n", (char *)data);
10895          return NULL;
10896       }
10897       groupmatch = ((ast_group_t) 1 << x);
10898       if (toupper(dest[0]) == 'G') {
10899          if (dest[0] == 'G') {
10900             backwards = 1;
10901             p = ifend;
10902          } else
10903             p = iflist;
10904       } else {
10905          if (dest[0] == 'R') {
10906             backwards = 1;
10907             p = round_robin[x]?round_robin[x]->prev:ifend;
10908             if (!p)
10909                p = ifend;
10910          } else {
10911             p = round_robin[x]?round_robin[x]->next:iflist;
10912             if (!p)
10913                p = iflist;
10914          }
10915          roundrobin = 1;
10916       }
10917    } else {
10918       char *stringp;
10919
10920       stringp = dest;
10921       s = strsep(&stringp, "/");
10922       p = iflist;
10923       if (!strcasecmp(s, "pseudo")) {
10924          /* Special case for pseudo */
10925          x = CHAN_PSEUDO;
10926          channelmatch = x;
10927       }
10928 #ifdef HAVE_PRI
10929       else if ((res = sscanf(s, "%30d:%30d%1c%30d", &trunkgroup, &crv, &opt, &y)) > 1) {
10930          if ((trunkgroup < 1) || (crv < 1)) {
10931             ast_log(LOG_WARNING, "Unable to determine trunk group and CRV for data %s\n", (char *)data);
10932             return NULL;
10933          }
10934          res--;
10935          for (x = 0; x < NUM_SPANS; x++) {
10936             if (pris[x].trunkgroup == trunkgroup) {
10937                pri = pris + x;
10938                lock = &pri->lock;
10939                start = pri->crvs;
10940                end = pri->crvend;
10941                break;
10942             }
10943          }
10944          if (!pri) {
10945             ast_log(LOG_WARNING, "Unable to find trunk group %d\n", trunkgroup);
10946             return NULL;
10947          }
10948          channelmatch = crv;
10949          p = pris[x].crvs;
10950       }
10951 #endif
10952       else if ((res = sscanf(s, "%30d%1c%30d", &x, &opt, &y)) < 1) {
10953          ast_log(LOG_WARNING, "Unable to determine channel for data %s\n", (char *)data);
10954          return NULL;
10955       } else {
10956          channelmatch = x;
10957       }
10958    }
10959    /* Search for an unowned channel */
10960    ast_mutex_lock(lock);
10961    exitpvt = p;
10962    while (p && !tmp) {
10963       if (roundrobin)
10964          round_robin[x] = p;
10965 #if 0
10966       ast_verbose("name = %s, %d, %d, %llu\n",p->owner ? p->owner->name : "<none>", p->channel, channelmatch, groupmatch);
10967 #endif
10968
10969       if (p && available(p, channelmatch, groupmatch, &busy, &channelmatched, &groupmatched)) {
10970          ast_debug(1, "Using channel %d\n", p->channel);
10971          if (p->inalarm)
10972             goto next;
10973
10974          callwait = (p->owner != NULL);
10975 #ifdef HAVE_PRI
10976          if (pri && (p->subs[SUB_REAL].dfd < 0)) {
10977             if (p->sig != SIG_FXSKS) {
10978                /* Gotta find an actual channel to use for this
10979                   CRV if this isn't a callwait */
10980                bearer = pri_find_empty_chan(pri, 0);
10981                if (bearer < 0) {
10982                   ast_log(LOG_NOTICE, "Out of bearer channels on span %d for call to CRV %d:%d\n", pri->span, trunkgroup, crv);
10983                   p = NULL;
10984                   break;
10985                }
10986                pri_assign_bearer(p, pri, pri->pvts[bearer]);
10987             } else {
10988                if (alloc_sub(p, 0)) {
10989                   ast_log(LOG_NOTICE, "Failed to allocate place holder pseudo channel!\n");
10990                   p = NULL;
10991                   break;
10992                } else
10993                   ast_debug(1, "Allocated placeholder pseudo channel\n");
10994
10995                p->pri = pri;
10996             }
10997          }
10998 #endif
10999 #ifdef HAVE_OPENR2
11000          if (p->mfcr2) {
11001             ast_mutex_lock(&p->lock);
11002             if (p->mfcr2call) {
11003                ast_mutex_unlock(&p->lock);
11004                ast_log(LOG_DEBUG, "Yay!, someone just beat us in the race for channel %d.\n", p->channel);
11005                goto next;
11006             }
11007             p->mfcr2call = 1;
11008             ast_mutex_unlock(&p->lock);
11009          }
11010 #endif
11011          if (p->channel == CHAN_PSEUDO) {
11012             p = duplicate_pseudo(p);
11013             if (!p) {
11014                break;
11015             }
11016          }
11017          if (p->owner) {
11018             if (alloc_sub(p, SUB_CALLWAIT)) {
11019                p = NULL;
11020                break;
11021             }
11022          }
11023          p->outgoing = 1;
11024          tmp = dahdi_new(p, AST_STATE_RESERVED, 0, p->owner ? SUB_CALLWAIT : SUB_REAL, 0, 0);
11025          if (!tmp) {
11026             p->outgoing = 0;
11027          }
11028 #ifdef HAVE_PRI
11029          if (p->bearer) {
11030             /* Log owner to bearer channel, too */
11031             p->bearer->owner = tmp;
11032          }
11033 #endif
11034          /* Make special notes */
11035          if (res > 1) {
11036             if (opt == 'c') {
11037                /* Confirm answer */
11038                p->confirmanswer = 1;
11039             } else if (opt == 'r') {
11040                /* Distinctive ring */
11041                if (res < 3)
11042                   ast_log(LOG_WARNING, "Distinctive ring missing identifier in '%s'\n", (char *)data);
11043                else
11044                   p->distinctivering = y;
11045             } else if (opt == 'd') {
11046                /* If this is an ISDN call, make it digital */
11047                p->digital = 1;
11048                if (tmp)
11049                   tmp->transfercapability = AST_TRANS_CAP_DIGITAL;
11050             } else {
11051                ast_log(LOG_WARNING, "Unknown option '%c' in '%s'\n", opt, (char *)data);
11052             }
11053          }
11054          /* Note if the call is a call waiting call */
11055          if (tmp && callwait)
11056             tmp->cdrflags |= AST_CDR_CALLWAIT;
11057          break;
11058       }
11059 next:
11060       if (backwards) {
11061          p = p->prev;
11062          if (!p)
11063             p = end;
11064       } else {
11065          p = p->next;
11066          if (!p)
11067             p = start;
11068       }
11069       /* stop when you roll to the one that we started from */
11070       if (p == exitpvt)
11071          break;
11072    }
11073    ast_mutex_unlock(lock);
11074    restart_monitor();
11075    if (callwait)
11076       *cause = AST_CAUSE_BUSY;
11077    else if (!tmp) {
11078       if (channelmatched) {
11079          if (busy)
11080             *cause = AST_CAUSE_BUSY;
11081       } else if (groupmatched) {
11082          *cause = AST_CAUSE_CONGESTION;
11083       }
11084    }
11085
11086    return tmp;
11087 }
static int dahdi_restart (void) [static]
Definition at line 14338 of file chan_dahdi.c.
References ast_active_channels(), ast_cond_wait(), ast_debug, ast_log(), ast_mutex_init(), ast_mutex_lock(), ast_mutex_unlock(), AST_PTHREADT_NULL, AST_PTHREADT_STOP, ast_verb, dahdi_softhangup_all(), destroy_all_channels(), dahdi_subchannel::dfd, iflist, lock, LOG_WARNING, master, dahdi_pvt::next, dahdi_pvt::owner, setup_dahdi(), and dahdi_pvt::subs.
Referenced by action_dahdirestart(), and dahdi_restart_cmd().
14339 {
14340 #if defined(HAVE_PRI) || defined(HAVE_SS7)
14341    int i, j;
14342 #endif
14343    int cancel_code;
14344    struct dahdi_pvt *p;
14345
14346    ast_mutex_lock(&restart_lock);
14347    ast_verb(1, "Destroying channels and reloading DAHDI configuration.\n");
14348    dahdi_softhangup_all();
14349    ast_verb(4, "Initial softhangup of all DAHDI channels complete.\n");
14350 #ifdef HAVE_OPENR2
14351    dahdi_r2_destroy_links();
14352 #endif
14353
14354 #if defined(HAVE_PRI)
14355    for (i = 0; i < NUM_SPANS; i++) {
14356       if (pris[i].master && (pris[i].master != AST_PTHREADT_NULL)) {
14357          cancel_code = pthread_cancel(pris[i].master);
14358          pthread_kill(pris[i].master, SIGURG);
14359          ast_debug(4, "Waiting to join thread of span %d with pid=%p, cancel_code=%d\n", i, (void *) pris[i].master, cancel_code);
14360          pthread_join(pris[i].master, NULL);
14361          ast_debug(4, "Joined thread of span %d\n", i);
14362       }
14363    }
14364 #endif
14365
14366 #if defined(HAVE_SS7)
14367    for (i = 0; i < NUM_SPANS; i++) {
14368       if (linksets[i].master && (linksets[i].master != AST_PTHREADT_NULL)) {
14369          cancel_code = pthread_cancel(linksets[i].master);
14370          pthread_kill(linksets[i].master, SIGURG);
14371          ast_debug(4, "Waiting to join thread of span %d with pid=%p, cancel_code=%d\n", i, (void *) linksets[i].master, cancel_code);
14372          pthread_join(linksets[i].master, NULL);
14373          ast_debug(4, "Joined thread of span %d\n", i);
14374       }
14375    }
14376 #endif
14377
14378    ast_mutex_lock(&monlock);
14379    if (monitor_thread && (monitor_thread != AST_PTHREADT_STOP) && (monitor_thread != AST_PTHREADT_NULL)) {
14380       cancel_code = pthread_cancel(monitor_thread);
14381       pthread_kill(monitor_thread, SIGURG);
14382       ast_debug(4, "Waiting to join monitor thread with pid=%p, cancel_code=%d\n", (void *) monitor_thread, cancel_code);
14383       pthread_join(monitor_thread, NULL);
14384       ast_debug(4, "Joined monitor thread\n");
14385    }
14386    monitor_thread = AST_PTHREADT_NULL; /* prepare to restart thread in setup_dahdi once channels are reconfigured */
14387
14388    ast_mutex_lock(&ss_thread_lock);
14389    while (ss_thread_count > 0) { /* let ss_threads finish and run dahdi_hangup before dahvi_pvts are destroyed */
14390       int x = DAHDI_FLASH;
14391       ast_debug(3, "Waiting on %d ss_thread(s) to finish\n", ss_thread_count);
14392
14393       for (p = iflist; p; p = p->next) {
14394          if (p->owner)
14395             ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x); /* important to create an event for dahdi_wait_event to register so that all ss_threads terminate */
14396          }
14397          ast_cond_wait(&ss_thread_complete, &ss_thread_lock);
14398       }
14399
14400    /* ensure any created channels before monitor threads were stopped are hungup */
14401    dahdi_softhangup_all();
14402    ast_verb(4, "Final softhangup of all DAHDI channels complete.\n");
14403    destroy_all_channels();
14404    ast_debug(1, "Channels destroyed. Now re-reading config. %d active channels remaining.\n", ast_active_channels());
14405
14406    ast_mutex_unlock(&monlock);
14407
14408 #ifdef HAVE_PRI
14409    for (i = 0; i < NUM_SPANS; i++) {
14410       for (j = 0; j < NUM_DCHANS; j++)
14411          dahdi_close_pri_fd(&(pris[i]), j);
14412    }
14413
14414    memset(pris, 0, sizeof(pris));
14415    for (i = 0; i < NUM_SPANS; i++) {
14416       ast_mutex_init(&pris[i].lock);
14417       pris[i].offset = -1;
14418       pris[i].master = AST_PTHREADT_NULL;
14419       for (j = 0; j < NUM_DCHANS; j++)
14420          pris[i].fds[j] = -1;
14421       }
14422    pri_set_error(dahdi_pri_error);
14423    pri_set_message(dahdi_pri_message);
14424 #endif
14425 #ifdef HAVE_SS7
14426    for (i = 0; i < NUM_SPANS; i++) {
14427       for (j = 0; j < NUM_DCHANS; j++)
14428          dahdi_close_ss7_fd(&(linksets[i]), j);
14429    }
14430
14431    memset(linksets, 0, sizeof(linksets));
14432    for (i = 0; i < NUM_SPANS; i++) {
14433       ast_mutex_init(&linksets[i].lock);
14434       linksets[i].master = AST_PTHREADT_NULL;
14435       for (j = 0; j < NUM_DCHANS; j++)
14436          linksets[i].fds[j] = -1;
14437    }
14438    ss7_set_error(dahdi_ss7_error);
14439    ss7_set_message(dahdi_ss7_message);
14440 #endif
14441
14442    if (setup_dahdi(2) != 0) {
14443       ast_log(LOG_WARNING, "Reload channels from dahdi config failed!\n");
14444       ast_mutex_unlock(&ss_thread_lock);
14445       return 1;
14446    }
14447    ast_mutex_unlock(&ss_thread_lock);
14448    ast_mutex_unlock(&restart_lock);
14449    return 0;
14450 }
static char* dahdi_restart_cmd (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14452 of file chan_dahdi.c.
References ast_cli_args::argc, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_restart(), and ast_cli_entry::usage.
14453 {
14454    switch (cmd) {
14455    case CLI_INIT:
14456       e->command = "dahdi restart";
14457       e->usage =
14458          "Usage: dahdi restart\n"
14459          "  Restarts the DAHDI channels: destroys them all and then\n"
14460          "  re-reads them from chan_dahdi.conf.\n"
14461          "  Note that this will STOP any running CALL on DAHDI channels.\n"
14462          "";
14463       return NULL;
14464    case CLI_GENERATE:
14465       return NULL;
14466    }
14467    if (a->argc != 2)
14468       return CLI_SHOWUSAGE;
14469
14470    if (dahdi_restart() != 0)
14471       return CLI_FAILURE;
14472    return CLI_SUCCESS;
14473 }
static int dahdi_ring_phone (struct dahdi_pvt * p) [static]
Definition at line 5470 of file chan_dahdi.c.
References ast_log(), dahdi_subchannel::dfd, errno, LOG_WARNING, SUB_REAL, and dahdi_pvt::subs.
Referenced by __dahdi_exception(), and dahdi_handle_event().
{
   int x;
   int res;
   /* Make sure our transmit state is on hook */
   x = 0;
   x = DAHDI_ONHOOK;
   res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x);
   do {
      x = DAHDI_RING;
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_HOOK, &x);
      if (res) {
         switch (errno) {
         case EBUSY:
         case EINTR:
            /* Wait just in case */
            usleep(10000);
            continue;
         case EINPROGRESS:
            res = 0;
            break;
         default:
            ast_log(LOG_WARNING, "Couldn't ring the phone: %s\n", strerror(errno));
            res = 0;
         }
      }
   } while (res);
   return res;
}
static int dahdi_sendtext (struct ast_channel * c, const char * text) [static]
Definition at line 17380 of file chan_dahdi.c.
References ASCII_BYTES_PER_CHAR, ast_check_hangup(), ast_debug, ast_free, AST_LAW, ast_log(), ast_malloc, dahdi_pvt::channel, dahdi_get_index(), dahdi_subchannel::dfd, END_SILENCE_LEN, errno, HEADER_LEN, HEADER_MS, LOG_ERROR, LOG_WARNING, dahdi_pvt::mate, PUT_CLID, PUT_CLID_MARKMS, READ_SIZE, dahdi_pvt::subs, dahdi_pvt::tdd, TDD_BYTES_PER_CHAR, tdd_generate(), ast_channel::tech_pvt, and TRAILER_MS.
17381 {
17382 #define  END_SILENCE_LEN 400
17383 #define  HEADER_MS 50
17384 #define  TRAILER_MS 5
17385 #define  HEADER_LEN ((HEADER_MS + TRAILER_MS) * 8)
17386 #define  ASCII_BYTES_PER_CHAR 80
17387
17388    unsigned char *buf,*mybuf;
17389    struct dahdi_pvt *p = c->tech_pvt;
17390    struct pollfd fds[1];
17391    int size,res,fd,len,x;
17392    int bytes=0;
17393    /* Initial carrier (imaginary) */
17394    float cr = 1.0;
17395    float ci = 0.0;
17396    float scont = 0.0;
17397    int idx;
17398
17399    idx = dahdi_get_index(c, p, 0);
17400    if (idx < 0) {
17401       ast_log(LOG_WARNING, "Huh?  I don't exist?\n");
17402       return -1;
17403    }
17404    if (!text[0]) return(0); /* if nothing to send, dont */
17405    if ((!p->tdd) && (!p->mate)) return(0);  /* if not in TDD mode, just return */
17406    if (p->mate)
17407       buf = ast_malloc(((strlen(text) + 1) * ASCII_BYTES_PER_CHAR) + END_SILENCE_LEN + HEADER_LEN);
17408    else
17409       buf = ast_malloc(((strlen(text) + 1) * TDD_BYTES_PER_CHAR) + END_SILENCE_LEN);
17410    if (!buf)
17411       return -1;
17412    mybuf = buf;
17413    if (p->mate) {
17414       int codec = AST_LAW(p);
17415       for (x = 0; x < HEADER_MS; x++) {   /* 50 ms of Mark */
17416          PUT_CLID_MARKMS;
17417       }
17418       /* Put actual message */
17419       for (x = 0; text[x]; x++) {
17420          PUT_CLID(text[x]);
17421       }
17422       for (x = 0; x < TRAILER_MS; x++) {  /* 5 ms of Mark */
17423          PUT_CLID_MARKMS;
17424       }
17425       len = bytes;
17426       buf = mybuf;
17427    } else {
17428       len = tdd_generate(p->tdd, buf, text);
17429       if (len < 1) {
17430          ast_log(LOG_ERROR, "TDD generate (len %d) failed!!\n", (int)strlen(text));
17431          ast_free(mybuf);
17432          return -1;
17433       }
17434    }
17435    memset(buf + len, 0x7f, END_SILENCE_LEN);
17436    len += END_SILENCE_LEN;
17437    fd = p->subs[idx].dfd;
17438    while (len) {
17439       if (ast_check_hangup(c)) {
17440          ast_free(mybuf);
17441          return -1;
17442       }
17443       size = len;
17444       if (size > READ_SIZE)
17445          size = READ_SIZE;
17446       fds[0].fd = fd;
17447       fds[0].events = POLLOUT | POLLPRI;
17448       fds[0].revents = 0;
17449       res = poll(fds, 1, -1);
17450       if (!res) {
17451          ast_debug(1, "poll (for write) ret. 0 on channel %d\n", p->channel);
17452          continue;
17453       }
17454       /* if got exception */
17455       if (fds[0].revents & POLLPRI) {
17456          ast_free(mybuf);
17457          return -1;
17458       }
17459       if (!(fds[0].revents & POLLOUT)) {
17460          ast_debug(1, "write fd not ready on channel %d\n", p->channel);
17461          continue;
17462       }
17463       res = write(fd, buf, size);
17464       if (res != size) {
17465          if (res == -1) {
17466             ast_free(mybuf);
17467             return -1;
17468          }
17469          ast_debug(1, "Write returned %d (%s) on channel %d\n", res, strerror(errno), p->channel);
17470          break;
17471       }
17472       len -= size;
17473       buf += size;
17474    }
17475    ast_free(mybuf);
17476    return(0);
17477 }
static char* dahdi_set_dnd (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 15112 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_false(), ast_mutex_lock(), ast_mutex_unlock(), ast_true(), dahdi_pvt::channel, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_dnd(), ast_cli_args::fd, iflist, dahdi_pvt::next, and ast_cli_entry::usage.
15113 {
15114    int channel;
15115    int on;
15116    struct dahdi_pvt *dahdi_chan = NULL;
15117
15118    switch (cmd) {
15119    case CLI_INIT:
15120       e->command = "dahdi set dnd";
15121       e->usage =
15122          "Usage: dahdi set dnd <chan#> <on|off>\n"
15123          "  Sets/resets DND (Do Not Disturb) mode on a channel.\n"
15124          "  Changes take effect immediately.\n"
15125          "  <chan num> is the channel number\n"
15126          "  <on|off> Enable or disable DND mode?\n"
15127          ;
15128       return NULL;
15129    case CLI_GENERATE:
15130       return NULL;
15131    }
15132
15133    if (a->argc != 5)
15134       return CLI_SHOWUSAGE;
15135
15136    if ((channel = atoi(a->argv[3])) <= 0) {
15137       ast_cli(a->fd, "Expected channel number, got '%s'\n", a->argv[3]);
15138       return CLI_SHOWUSAGE;
15139    }
15140
15141    if (ast_true(a->argv[4]))
15142       on = 1;
15143    else if (ast_false(a->argv[4]))
15144       on = 0;
15145    else {
15146       ast_cli(a->fd, "Expected 'on' or 'off', got '%s'\n", a->argv[4]);
15147       return CLI_SHOWUSAGE;
15148    }
15149
15150    ast_mutex_lock(&iflock);
15151    for (dahdi_chan = iflist; dahdi_chan; dahdi_chan = dahdi_chan->next) {
15152       if (dahdi_chan->channel != channel)
15153          continue;
15154
15155       /* Found the channel. Actually set it */
15156       dahdi_dnd(dahdi_chan, on);
15157       break;
15158    }
15159    ast_mutex_unlock(&iflock);
15160
15161    if (!dahdi_chan) {
15162       ast_cli(a->fd, "Unable to find given channel %d\n", channel);
15163       return CLI_FAILURE;
15164    }
15165
15166    return CLI_SUCCESS;
15167 }
static int dahdi_set_hook (int fd, int hs) [inline, static]
Definition at line 2863 of file chan_dahdi.c.
References ast_log(), errno, and LOG_WARNING.
Referenced by __dahdi_exception(), dahdi_answer(), dahdi_handle_event(), dahdi_hangup(), dahdi_indicate(), dahdi_wink(), handle_init_event(), mkintf(), mwi_send_process_buffer(), mwi_send_process_event(), and ss_thread().
{
   int x, res;
   x = hs;
   res = ioctl(fd, DAHDI_HOOK, &x);
   if (res < 0) {
      if (errno == EINPROGRESS)
         return 0;
      ast_log(LOG_WARNING, "DAHDI hook failed returned %d (trying %d): %s\n", res, hs, strerror(errno));
      /* will expectedly fail if phone is off hook during operation, such as during a restart */
   }
   return res;
}
static char* dahdi_set_hwgain (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14969 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::channel, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_subchannel::dfd, errno, ast_cli_args::fd, iflist, dahdi_pvt::next, dahdi_pvt::subs, and ast_cli_entry::usage.
14970 {
14971    int channel;
14972    int gain;
14973    int tx;
14974    struct dahdi_hwgain hwgain;
14975    struct dahdi_pvt *tmp = NULL;
14976
14977    switch (cmd) {
14978    case CLI_INIT:
14979       e->command = "dahdi set hwgain";
14980       e->usage =
14981          "Usage: dahdi set hwgain <rx|tx> <chan#> <gain>\n"
14982          "  Sets the hardware gain on a a given channel, overriding the\n"
14983          "   value provided at module loadtime, whether the channel is in\n"
14984          "   use or not.  Changes take effect immediately.\n"
14985          "   <rx|tx> which direction do you want to change (relative to our module)\n"
14986          "   <chan num> is the channel number relative to the device\n"
14987          "   <gain> is the gain in dB (e.g. -3.5 for -3.5dB)\n";
14988       return NULL;
14989    case CLI_GENERATE:
14990       return NULL;
14991    }
14992
14993    if (a->argc != 6)
14994       return CLI_SHOWUSAGE;
14995
14996    if (!strcasecmp("rx", a->argv[3]))
14997       tx = 0; /* rx */
14998    else if (!strcasecmp("tx", a->argv[3]))
14999       tx = 1; /* tx */
15000    else
15001       return CLI_SHOWUSAGE;
15002
15003    channel = atoi(a->argv[4]);
15004    gain = atof(a->argv[5])*10.0;
15005
15006    ast_mutex_lock(&iflock);
15007
15008    for (tmp = iflist; tmp; tmp = tmp->next) {
15009
15010       if (tmp->channel != channel)
15011          continue;
15012
15013       if (tmp->subs[SUB_REAL].dfd == -1)
15014          break;
15015
15016       hwgain.newgain = gain;
15017       hwgain.tx = tx;
15018       if (ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_SET_HWGAIN, &hwgain) < 0) {
15019          ast_cli(a->fd, "Unable to set the hardware gain for channel %d: %s\n", channel, strerror(errno));
15020          ast_mutex_unlock(&iflock);
15021          return CLI_FAILURE;
15022       }
15023       ast_cli(a->fd, "hardware %s gain set to %d (%.1f dB) on channel %d\n",
15024          tx ? "tx" : "rx", gain, (float)gain/10.0, channel);
15025       break;
15026    }
15027
15028    ast_mutex_unlock(&iflock);
15029
15030    if (tmp)
15031       return CLI_SUCCESS;
15032
15033    ast_cli(a->fd, "Unable to find given channel %d\n", channel);
15034    return CLI_FAILURE;
15035
15036 }
static char* dahdi_set_swgain (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 15038 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::channel, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_subchannel::dfd, ast_cli_args::fd, iflist, dahdi_pvt::law, lock, dahdi_pvt::next, set_actual_rxgain(), set_actual_txgain(), dahdi_pvt::subs, and ast_cli_entry::usage.
15039 {
15040    int channel;
15041    float gain;
15042    int tx;
15043    int res;
15044    ast_mutex_t *lock;
15045    struct dahdi_pvt *tmp = NULL;
15046
15047    switch (cmd) {
15048    case CLI_INIT:
15049       e->command = "dahdi set swgain";
15050       e->usage =
15051          "Usage: dahdi set swgain <rx|tx> <chan#> <gain>\n"
15052          "  Sets the software gain on a a given channel, overriding the\n"
15053          "   value provided at module loadtime, whether the channel is in\n"
15054          "   use or not.  Changes take effect immediately.\n"
15055          "   <rx|tx> which direction do you want to change (relative to our module)\n"
15056          "   <chan num> is the channel number relative to the device\n"
15057          "   <gain> is the gain in dB (e.g. -3.5 for -3.5dB)\n";
15058       return NULL;
15059    case CLI_GENERATE:
15060       return NULL;
15061    }
15062
15063    lock = &iflock;
15064
15065    if (a->argc != 6)
15066       return CLI_SHOWUSAGE;
15067
15068    if (!strcasecmp("rx", a->argv[3]))
15069       tx = 0; /* rx */
15070    else if (!strcasecmp("tx", a->argv[3]))
15071       tx = 1; /* tx */
15072    else
15073       return CLI_SHOWUSAGE;
15074
15075    channel = atoi(a->argv[4]);
15076    gain = atof(a->argv[5]);
15077
15078    ast_mutex_lock(lock);
15079    for (tmp = iflist; tmp; tmp = tmp->next) {
15080
15081       if (tmp->channel != channel)
15082          continue;
15083
15084       if (tmp->subs[SUB_REAL].dfd == -1)
15085          break;
15086
15087       if (tx)
15088          res = set_actual_txgain(tmp->subs[SUB_REAL].dfd, channel, gain, tmp->law);
15089       else
15090          res = set_actual_rxgain(tmp->subs[SUB_REAL].dfd, channel, gain, tmp->law);
15091
15092       if (res) {
15093          ast_cli(a->fd, "Unable to set the software gain for channel %d\n", channel);
15094          ast_mutex_unlock(lock);
15095          return CLI_FAILURE;
15096       }
15097
15098       ast_cli(a->fd, "software %s gain set to %.1f on channel %d\n",
15099          tx ? "tx" : "rx", gain, channel);
15100       break;
15101    }
15102    ast_mutex_unlock(lock);
15103
15104    if (tmp)
15105       return CLI_SUCCESS;
15106
15107    ast_cli(a->fd, "Unable to find given channel %d\n", channel);
15108    return CLI_FAILURE;
15109
15110 }
static int dahdi_setlinear (int dfd, int linear) [static]
Definition at line 2165 of file chan_dahdi.c.
Referenced by dahdi_hangup(), dahdi_new(), dahdi_read(), dahdi_write(), send_callerid(), and ss_thread().
{
   int res;
   res = ioctl(dfd, DAHDI_SETLINEAR, &linear);
   if (res)
      return res;
   return 0;
}
static int dahdi_setoption (struct ast_channel * chan, int option, void * data, int datalen) [static]
Todo:
XXX This is an abuse of the stack!!
Definition at line 4837 of file chan_dahdi.c.
References ast_check_hangup(), ast_debug, ast_dsp_set_digitmode(), ast_log(), AST_OPTION_AUDIO_MODE, AST_OPTION_ECHOCAN, AST_OPTION_OPRMODE, AST_OPTION_RELAXDTMF, AST_OPTION_RXGAIN, AST_OPTION_TDD, AST_OPTION_TONE_VERIFY, AST_OPTION_TXGAIN, ast_tdd_gen_ecdisa(), buf, dahdi_pvt::channel, dahdi_disable_ec(), dahdi_enable_ec(), dahdi_get_index(), dahdi_subchannel::dfd, dahdi_pvt::didtdd, dahdi_pvt::dsp, DSP_DIGITMODE_DTMF, DSP_DIGITMODE_MUTECONF, DSP_DIGITMODE_MUTEMAX, DSP_DIGITMODE_RELAXDTMF, dahdi_pvt::dtmfrelax, errno, dahdi_pvt::law, len(), LOG_NOTICE, LOG_WARNING, dahdi_pvt::mate, oprmode::mode, dahdi_pvt::oprmode, dahdi_pvt::oprpeer, oprmode::peer, pp, READ_SIZE, dahdi_pvt::rxgain, set_actual_rxgain(), set_actual_txgain(), SUB_REAL, dahdi_pvt::subs, dahdi_pvt::tdd, tdd_free(), tdd_new(), ast_channel::tech, ast_channel::tech_pvt, dahdi_pvt::txgain, and ast_channel_tech::type.
{
   char *cp;
   signed char *scp;
   int x;
   int idx;
   struct dahdi_pvt *p = chan->tech_pvt, *pp;
   struct oprmode *oprmode;
   /* all supported options require data */
   if (!data || (datalen < 1)) {
      errno = EINVAL;
      return -1;
   }
   switch (option) {
   case AST_OPTION_TXGAIN:
      scp = (signed char *) data;
      idx = dahdi_get_index(chan, p, 0);
      if (idx < 0) {
         ast_log(LOG_WARNING, "No index in TXGAIN?\n");
         return -1;
      }
      ast_debug(1, "Setting actual tx gain on %s to %f\n", chan->name, p->txgain + (float) *scp);
      return set_actual_txgain(p->subs[idx].dfd, 0, p->txgain + (float) *scp, p->law);
   case AST_OPTION_RXGAIN:
      scp = (signed char *) data;
      idx = dahdi_get_index(chan, p, 0);
      if (idx < 0) {
         ast_log(LOG_WARNING, "No index in RXGAIN?\n");
         return -1;
      }
      ast_debug(1, "Setting actual rx gain on %s to %f\n", chan->name, p->rxgain + (float) *scp);
      return set_actual_rxgain(p->subs[idx].dfd, 0, p->rxgain + (float) *scp, p->law);
   case AST_OPTION_TONE_VERIFY:
      if (!p->dsp)
         break;
      cp = (char *) data;
      switch (*cp) {
      case 1:
         ast_debug(1, "Set option TONE VERIFY, mode: MUTECONF(1) on %s\n",chan->name);
         ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_MUTECONF | p->dtmfrelax);  /* set mute mode if desired */
         break;
      case 2:
         ast_debug(1, "Set option TONE VERIFY, mode: MUTECONF/MAX(2) on %s\n",chan->name);
         ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_MUTECONF | DSP_DIGITMODE_MUTEMAX | p->dtmfrelax);  /* set mute mode if desired */
         break;
      default:
         ast_debug(1, "Set option TONE VERIFY, mode: OFF(0) on %s\n",chan->name);
         ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_DTMF | p->dtmfrelax);  /* set mute mode if desired */
         break;
      }
      break;
   case AST_OPTION_TDD:
      /* turn on or off TDD */
      cp = (char *) data;
      p->mate = 0;
      if (!*cp) { /* turn it off */
         ast_debug(1, "Set option TDD MODE, value: OFF(0) on %s\n",chan->name);
         if (p->tdd)
            tdd_free(p->tdd);
         p->tdd = 0;
         break;
      }
      ast_debug(1, "Set option TDD MODE, value: %s(%d) on %s\n",
         (*cp == 2) ? "MATE" : "ON", (int) *cp, chan->name);
      dahdi_disable_ec(p);
      /* otherwise, turn it on */
      if (!p->didtdd) { /* if havent done it yet */
         unsigned char mybuf[41000];/*! \todo XXX This is an abuse of the stack!! */
         unsigned char *buf;
         int size, res, fd, len;
         struct pollfd fds[1];
         buf = mybuf;
         memset(buf, 0x7f, sizeof(mybuf)); /* set to silence */
         ast_tdd_gen_ecdisa(buf + 16000, 16000);  /* put in tone */
         len = 40000;
         idx = dahdi_get_index(chan, p, 0);
         if (idx < 0) {
            ast_log(LOG_WARNING, "No index in TDD?\n");
            return -1;
         }
         fd = p->subs[idx].dfd;
         while (len) {
            if (ast_check_hangup(chan))
               return -1;
            size = len;
            if (size > READ_SIZE)
               size = READ_SIZE;
            fds[0].fd = fd;
            fds[0].events = POLLPRI | POLLOUT;
            fds[0].revents = 0;
            res = poll(fds, 1, -1);
            if (!res) {
               ast_debug(1, "poll (for write) ret. 0 on channel %d\n", p->channel);
               continue;
            }
            /* if got exception */
            if (fds[0].revents & POLLPRI)
               return -1;
            if (!(fds[0].revents & POLLOUT)) {
               ast_debug(1, "write fd not ready on channel %d\n", p->channel);
               continue;
            }
            res = write(fd, buf, size);
            if (res != size) {
               if (res == -1) return -1;
               ast_debug(1, "Write returned %d (%s) on channel %d\n", res, strerror(errno), p->channel);
               break;
            }
            len -= size;
            buf += size;
         }
         p->didtdd = 1; /* set to have done it now */
      }
      if (*cp == 2) { /* Mate mode */
         if (p->tdd)
            tdd_free(p->tdd);
         p->tdd = 0;
         p->mate = 1;
         break;
      }
      if (!p->tdd) { /* if we dont have one yet */
         p->tdd = tdd_new(); /* allocate one */
      }
      break;
   case AST_OPTION_RELAXDTMF:  /* Relax DTMF decoding (or not) */
      if (!p->dsp)
         break;
      cp = (char *) data;
      ast_debug(1, "Set option RELAX DTMF, value: %s(%d) on %s\n",
         *cp ? "ON" : "OFF", (int) *cp, chan->name);
      ast_dsp_set_digitmode(p->dsp, ((*cp) ? DSP_DIGITMODE_RELAXDTMF : DSP_DIGITMODE_DTMF) | p->dtmfrelax);
      break;
   case AST_OPTION_AUDIO_MODE:  /* Set AUDIO mode (or not) */
      cp = (char *) data;
      if (!*cp) {
         ast_debug(1, "Set option AUDIO MODE, value: OFF(0) on %s\n", chan->name);
         x = 0;
         dahdi_disable_ec(p);
      } else {
         ast_debug(1, "Set option AUDIO MODE, value: ON(1) on %s\n", chan->name);
         x = 1;
      }
      if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_AUDIOMODE, &x) == -1)
         ast_log(LOG_WARNING, "Unable to set audio mode on channel %d to %d: %s\n", p->channel, x, strerror(errno));
      break;
   case AST_OPTION_OPRMODE:  /* Operator services mode */
      oprmode = (struct oprmode *) data;
      /* We don't support operator mode across technologies */
      if (strcasecmp(chan->tech->type, oprmode->peer->tech->type)) {
         ast_log(LOG_NOTICE, "Operator mode not supported on %s to %s calls.\n",
               chan->tech->type, oprmode->peer->tech->type);
         errno = EINVAL;
         return -1;
      }
      pp = oprmode->peer->tech_pvt;
      p->oprmode = pp->oprmode = 0;
      /* setup peers */
      p->oprpeer = pp;
      pp->oprpeer = p;
      /* setup modes, if any */
      if (oprmode->mode)
      {
         pp->oprmode = oprmode->mode;
         p->oprmode = -oprmode->mode;
      }
      ast_debug(1, "Set Operator Services mode, value: %d on %s/%s\n",
         oprmode->mode, chan->name,oprmode->peer->name);
      break;
   case AST_OPTION_ECHOCAN:
      cp = (char *) data;
      if (*cp) {
         ast_debug(1, "Enabling echo cancelation on %s\n", chan->name);
         dahdi_enable_ec(p);
      } else {
         ast_debug(1, "Disabling echo cancelation on %s\n", chan->name);
         dahdi_disable_ec(p);
      }
      break;
   }
   errno = 0;
   return 0;
}
static char* dahdi_show_channel (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14609 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_log(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::busy_quietlength, dahdi_pvt::busy_tonelength, dahdi_pvt::busycount, dahdi_pvt::busydetect, dahdi_pvt::callwaitcas, dahdi_pvt::channel, dahdi_pvt::cid_name, dahdi_pvt::cid_num, dahdi_pvt::cid_ton, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_pvt::confno, dahdi_pvt::context, dahdi_pvt::destroy, dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::dnd, dahdi_pvt::dsp, dahdi_pvt::dtmfrelax, dahdi_pvt::echocanbridged, dahdi_pvt::echocancel, dahdi_pvt::echocanon, errno, dahdi_pvt::exten, dahdi_pvt::faxhandled, ast_cli_args::fd, dahdi_pvt::head, iflist, dahdi_pvt::inalarm, dahdi_pvt::inconference, dahdi_subchannel::inthreeway, dahdi_pvt::law, dahdi_subchannel::linear, lock, LOG_WARNING, dahdi_pvt::mailbox, dahdi_pvt::master, MAX_SLAVES, ast_variable::name, dahdi_pvt::next, ast_variable::next, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::params, dahdi_pvt::propconfno, dahdi_pvt::pulsedial, dahdi_pvt::radio, S_OR, dahdi_pvt::sig, sig2str, dahdi_pvt::slaves, dahdi_pvt::span, SUB_CALLWAIT, SUB_THREEWAY, dahdi_pvt::subs, dahdi_pvt::tdd, ast_cli_entry::usage, ast_variable::value, dahdi_pvt::vars, and dahdi_pvt::waitfordialtone.
14610 {
14611    int channel;
14612    struct dahdi_pvt *tmp = NULL;
14613    struct dahdi_confinfo ci;
14614    struct dahdi_params ps;
14615    int x;
14616    ast_mutex_t *lock;
14617    struct dahdi_pvt *start;
14618 #ifdef HAVE_PRI
14619    char *c;
14620    int trunkgroup;
14621    struct dahdi_pri *pri=NULL;
14622 #endif
14623    switch (cmd) {
14624    case CLI_INIT:
14625       e->command = "dahdi show channel";
14626       e->usage =
14627          "Usage: dahdi show channel <chan num>\n"
14628          "  Detailed information about a given channel\n";
14629       return NULL;
14630    case CLI_GENERATE:
14631       return NULL;
14632    }
14633
14634    lock = &iflock;
14635    start = iflist;
14636
14637    if (a->argc != 4)
14638       return CLI_SHOWUSAGE;
14639 #ifdef HAVE_PRI
14640    if ((c = strchr(a->argv[3], ':'))) {
14641       if (sscanf(a->argv[3], "%30d:%30d", &trunkgroup, &channel) != 2)
14642          return CLI_SHOWUSAGE;
14643       if ((trunkgroup < 1) || (channel < 1))
14644          return CLI_SHOWUSAGE;
14645       for (x = 0; x < NUM_SPANS; x++) {
14646          if (pris[x].trunkgroup == trunkgroup) {
14647             pri = pris + x;
14648             break;
14649          }
14650       }
14651       if (pri) {
14652          start = pri->crvs;
14653          lock = &pri->lock;
14654       } else {
14655          ast_cli(a->fd, "No such trunk group %d\n", trunkgroup);
14656          return CLI_FAILURE;
14657       }
14658    } else
14659 #endif
14660       channel = atoi(a->argv[3]);
14661
14662    ast_mutex_lock(lock);
14663    tmp = start;
14664    while (tmp) {
14665       if (tmp->channel == channel) {
14666 #ifdef HAVE_PRI
14667          if (pri)
14668             ast_cli(a->fd, "Trunk/CRV: %d/%d\n", trunkgroup, tmp->channel);
14669          else
14670 #endif
14671          ast_cli(a->fd, "Channel: %d\n", tmp->channel);
14672          ast_cli(a->fd, "File Descriptor: %d\n", tmp->subs[SUB_REAL].dfd);
14673          ast_cli(a->fd, "Span: %d\n", tmp->span);
14674          ast_cli(a->fd, "Extension: %s\n", tmp->exten);
14675          ast_cli(a->fd, "Dialing: %s\n", tmp->dialing ? "yes" : "no");
14676          ast_cli(a->fd, "Context: %s\n", tmp->context);
14677          ast_cli(a->fd, "Caller ID: %s\n", tmp->cid_num);
14678          ast_cli(a->fd, "Calling TON: %d\n", tmp->cid_ton);
14679          ast_cli(a->fd, "Caller ID name: %s\n", tmp->cid_name);
14680          ast_cli(a->fd, "Mailbox: %s\n", S_OR(tmp->mailbox, "none"));
14681          if (tmp->vars) {
14682             struct ast_variable *v;
14683             ast_cli(a->fd, "Variables:\n");
14684             for (v = tmp->vars ; v ; v = v->next)
14685                ast_cli(a->fd, "       %s = %s\n", v->name, v->value);
14686          }
14687          ast_cli(a->fd, "Destroy: %d\n", tmp->destroy);
14688          ast_cli(a->fd, "InAlarm: %d\n", tmp->inalarm);
14689          ast_cli(a->fd, "Signalling Type: %s\n", sig2str(tmp->sig));
14690          ast_cli(a->fd, "Radio: %d\n", tmp->radio);
14691          ast_cli(a->fd, "Owner: %s\n", tmp->owner ? tmp->owner->name : "<None>");
14692          ast_cli(a->fd, "Real: %s%s%s\n", tmp->subs[SUB_REAL].owner ? tmp->subs[SUB_REAL].owner->name : "<None>", tmp->subs[SUB_REAL].inthreeway ? " (Confed)" : "", tmp->subs[SUB_REAL].linear ? " (Linear)" : "");
14693          ast_cli(a->fd, "Callwait: %s%s%s\n", tmp->subs[SUB_CALLWAIT].owner ? tmp->subs[SUB_CALLWAIT].owner->name : "<None>", tmp->subs[SUB_CALLWAIT].inthreeway ? " (Confed)" : "", tmp->subs[SUB_CALLWAIT].linear ? " (Linear)" : "");
14694          ast_cli(a->fd, "Threeway: %s%s%s\n", tmp->subs[SUB_THREEWAY].owner ? tmp->subs[SUB_THREEWAY].owner->name : "<None>", tmp->subs[SUB_THREEWAY].inthreeway ? " (Confed)" : "", tmp->subs[SUB_THREEWAY].linear ? " (Linear)" : "");
14695          ast_cli(a->fd, "Confno: %d\n", tmp->confno);
14696          ast_cli(a->fd, "Propagated Conference: %d\n", tmp->propconfno);
14697          ast_cli(a->fd, "Real in conference: %d\n", tmp->inconference);
14698          ast_cli(a->fd, "DSP: %s\n", tmp->dsp ? "yes" : "no");
14699          ast_cli(a->fd, "Busy Detection: %s\n", tmp->busydetect ? "yes" : "no");
14700          if (tmp->busydetect) {
14701 #if defined(BUSYDETECT_TONEONLY)
14702             ast_cli(a->fd, "    Busy Detector Helper: BUSYDETECT_TONEONLY\n");
14703 #elif defined(BUSYDETECT_COMPARE_TONE_AND_SILENCE)
14704             ast_cli(a->fd, "    Busy Detector Helper: BUSYDETECT_COMPARE_TONE_AND_SILENCE\n");
14705 #endif
14706 #ifdef BUSYDETECT_DEBUG
14707             ast_cli(a->fd, "    Busy Detector Debug: Enabled\n");
14708 #endif
14709             ast_cli(a->fd, "    Busy Count: %d\n", tmp->busycount);
14710             ast_cli(a->fd, "    Busy Pattern: %d,%d\n", tmp->busy_tonelength, tmp->busy_quietlength);
14711          }
14712          ast_cli(a->fd, "TDD: %s\n", tmp->tdd ? "yes" : "no");
14713          ast_cli(a->fd, "Relax DTMF: %s\n", tmp->dtmfrelax ? "yes" : "no");
14714          ast_cli(a->fd, "Dialing/CallwaitCAS: %d/%d\n", tmp->dialing, tmp->callwaitcas);
14715          ast_cli(a->fd, "Default law: %s\n", tmp->law == DAHDI_LAW_MULAW ? "ulaw" : tmp->law == DAHDI_LAW_ALAW ? "alaw" : "unknown");
14716          ast_cli(a->fd, "Fax Handled: %s\n", tmp->faxhandled ? "yes" : "no");
14717          ast_cli(a->fd, "Pulse phone: %s\n", tmp->pulsedial ? "yes" : "no");
14718          ast_cli(a->fd, "DND: %s\n", tmp->dnd ? "yes" : "no");
14719          ast_cli(a->fd, "Echo Cancellation:\n");
14720
14721          if (tmp->echocancel.head.tap_length) {
14722             ast_cli(a->fd, "\t%d taps\n", tmp->echocancel.head.tap_length);
14723             for (x = 0; x < tmp->echocancel.head.param_count; x++) {
14724                ast_cli(a->fd, "\t\t%s: %ud\n", tmp->echocancel.params[x].name, tmp->echocancel.params[x].value);
14725             }
14726             ast_cli(a->fd, "\t%scurrently %s\n", tmp->echocanbridged ? "" : "(unless TDM bridged) ", tmp->echocanon ? "ON" : "OFF");
14727          } else {
14728             ast_cli(a->fd, "\tnone\n");
14729          }
14730          ast_cli(a->fd, "Wait for dialtone: %dms\n", tmp->waitfordialtone);
14731          if (tmp->master)
14732             ast_cli(a->fd, "Master Channel: %d\n", tmp->master->channel);
14733          for (x = 0; x < MAX_SLAVES; x++) {
14734             if (tmp->slaves[x])
14735                ast_cli(a->fd, "Slave Channel: %d\n", tmp->slaves[x]->channel);
14736          }
14737 #ifdef HAVE_OPENR2
14738          if (tmp->mfcr2) {
14739             char calldir[OR2_MAX_PATH];
14740             openr2_context_t *r2context = openr2_chan_get_context(tmp->r2chan);
14741             openr2_variant_t r2variant = openr2_context_get_variant(r2context);
14742             ast_cli(a->fd, "MFC/R2 MF State: %s\n", openr2_chan_get_mf_state_string(tmp->r2chan));
14743             ast_cli(a->fd, "MFC/R2 MF Group: %s\n", openr2_chan_get_mf_group_string(tmp->r2chan));
14744             ast_cli(a->fd, "MFC/R2 State: %s\n", openr2_chan_get_r2_state_string(tmp->r2chan));
14745             ast_cli(a->fd, "MFC/R2 Call State: %s\n", openr2_chan_get_call_state_string(tmp->r2chan));
14746             ast_cli(a->fd, "MFC/R2 Call Files Enabled: %s\n", openr2_chan_get_call_files_enabled(tmp->r2chan) ? "Yes" : "No");
14747             ast_cli(a->fd, "MFC/R2 Variant: %s\n", openr2_proto_get_variant_string(r2variant));
14748             ast_cli(a->fd, "MFC/R2 Max ANI: %d\n", openr2_context_get_max_ani(r2context));
14749             ast_cli(a->fd, "MFC/R2 Max DNIS: %d\n", openr2_context_get_max_dnis(r2context));
14750             ast_cli(a->fd, "MFC/R2 Get ANI First: %s\n", openr2_context_get_ani_first(r2context) ? "Yes" : "No");
14751 #if defined(OR2_LIB_INTERFACE) && OR2_LIB_INTERFACE > 1
14752             ast_cli(a->fd, "MFC/R2 Skip Category Request: %s\n", openr2_context_get_skip_category_request(r2context) ? "Yes" : "No");
14753 #endif
14754             ast_cli(a->fd, "MFC/R2 Immediate Accept: %s\n", openr2_context_get_immediate_accept(r2context) ? "Yes" : "No");
14755             ast_cli(a->fd, "MFC/R2 Accept on Offer: %s\n", tmp->mfcr2_accept_on_offer ? "Yes" : "No");
14756             ast_cli(a->fd, "MFC/R2 Charge Calls: %s\n", tmp->mfcr2_charge_calls ? "Yes" : "No");
14757             ast_cli(a->fd, "MFC/R2 Allow Collect Calls: %s\n", tmp->mfcr2_allow_collect_calls ? "Yes" : "No");
14758             ast_cli(a->fd, "MFC/R2 Forced Release: %s\n", tmp->mfcr2_forced_release ? "Yes" : "No");
14759             ast_cli(a->fd, "MFC/R2 MF Back Timeout: %dms\n", openr2_context_get_mf_back_timeout(r2context));
14760             ast_cli(a->fd, "MFC/R2 R2 Metering Pulse Timeout: %dms\n", openr2_context_get_metering_pulse_timeout(r2context));
14761             ast_cli(a->fd, "MFC/R2 Rx CAS: %s\n", openr2_chan_get_rx_cas_string(tmp->r2chan));
14762             ast_cli(a->fd, "MFC/R2 Tx CAS: %s\n", openr2_chan_get_tx_cas_string(tmp->r2chan));
14763             ast_cli(a->fd, "MFC/R2 MF Tx Signal: %d\n", openr2_chan_get_tx_mf_signal(tmp->r2chan));
14764             ast_cli(a->fd, "MFC/R2 MF Rx Signal: %d\n", openr2_chan_get_rx_mf_signal(tmp->r2chan));
14765             ast_cli(a->fd, "MFC/R2 Call Files Directory: %s\n", openr2_context_get_log_directory(r2context, calldir, sizeof(calldir)));
14766          }
14767 #endif
14768 #ifdef HAVE_SS7
14769          if (tmp->ss7) {
14770             ast_cli(a->fd, "CIC: %d\n", tmp->cic);
14771          }
14772 #endif
14773 #ifdef HAVE_PRI
14774          if (tmp->pri) {
14775             ast_cli(a->fd, "PRI Flags: ");
14776             if (tmp->resetting)
14777                ast_cli(a->fd, "Resetting ");
14778             if (tmp->call)
14779                ast_cli(a->fd, "Call ");
14780             if (tmp->bearer)
14781                ast_cli(a->fd, "Bearer ");
14782             ast_cli(a->fd, "\n");
14783             if (tmp->logicalspan)
14784                ast_cli(a->fd, "PRI Logical Span: %d\n", tmp->logicalspan);
14785             else
14786                ast_cli(a->fd, "PRI Logical Span: Implicit\n");
14787          }
14788 #endif
14789          memset(&ci, 0, sizeof(ci));
14790          ps.channo = tmp->channel;
14791          if (tmp->subs[SUB_REAL].dfd > -1) {
14792             memset(&ci, 0, sizeof(ci));
14793             if (!ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GETCONF, &ci)) {
14794                ast_cli(a->fd, "Actual Confinfo: Num/%d, Mode/0x%04x\n", ci.confno, ci.confmode);
14795             }
14796             if (!ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GETCONFMUTE, &x)) {
14797                ast_cli(a->fd, "Actual Confmute: %s\n", x ? "Yes" : "No");
14798             }
14799             memset(&ps, 0, sizeof(ps));
14800             if (ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &ps) < 0) {
14801                ast_log(LOG_WARNING, "Failed to get parameters on channel %d: %s\n", tmp->channel, strerror(errno));
14802             } else {
14803                ast_cli(a->fd, "Hookstate (FXS only): %s\n", ps.rxisoffhook ? "Offhook" : "Onhook");
14804             }
14805          }
14806          ast_mutex_unlock(lock);
14807          return CLI_SUCCESS;
14808       }
14809       tmp = tmp->next;
14810    }
14811
14812    ast_cli(a->fd, "Unable to find given channel %d\n", channel);
14813    ast_mutex_unlock(lock);
14814    return CLI_FAILURE;
14815 }
static char* dahdi_show_channels (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14485 of file chan_dahdi.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_copy_string(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::channel, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, dahdi_pvt::context, dahdi_pvt::exten, ast_cli_args::fd, FORMAT, FORMAT2, dahdi_pvt::group, iflist, dahdi_pvt::language, dahdi_pvt::locallyblocked, lock, dahdi_pvt::mohinterpret, dahdi_pvt::next, dahdi_pvt::remotelyblocked, and ast_cli_entry::usage.
14486 {
14487 #define FORMAT "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
14488 #define FORMAT2 "%7s %-10.10s %-15.15s %-10.10s %-20.20s %-10.10s %-10.10s\n"
14489    unsigned int targetnum = 0;
14490    int filtertype = 0;
14491    struct dahdi_pvt *tmp = NULL;
14492    char tmps[20] = "";
14493    char statestr[20] = "";
14494    char blockstr[20] = "";
14495    ast_mutex_t *lock;
14496    struct dahdi_pvt *start;
14497 #ifdef HAVE_PRI
14498    int trunkgroup;
14499    struct dahdi_pri *pri = NULL;
14500    int x;
14501 #endif
14502    switch (cmd) {
14503    case CLI_INIT:
14504       e->command = "dahdi show channels [trunkgroup|group|context]";
14505       e->usage =
14506          "Usage: dahdi show channels [ trunkgroup <trunkgroup> | group <group> | context <context> ]\n"
14507          "  Shows a list of available channels with optional filtering\n"
14508          "  <group> must be a number between 0 and 63\n";
14509       return NULL;
14510    case CLI_GENERATE:
14511       return NULL;
14512    }
14513
14514    lock = &iflock;
14515    start = iflist;
14516
14517    /* syntax: dahdi show channels [ group <group> | context <context> | trunkgroup <trunkgroup> ] */
14518
14519    if (!((a->argc == 3) || (a->argc == 5)))
14520       return CLI_SHOWUSAGE;
14521
14522    if (a->argc == 5) {
14523 #ifdef HAVE_PRI
14524       if (!strcasecmp(a->argv[3], "trunkgroup")) {
14525          /* this option requires no special handling, so leave filtertype to zero */
14526          if ((trunkgroup = atoi(a->argv[4])) < 1)
14527             return CLI_SHOWUSAGE;
14528          for (x = 0; x < NUM_SPANS; x++) {
14529             if (pris[x].trunkgroup == trunkgroup) {
14530                pri = pris + x;
14531                break;
14532             }
14533          }
14534          if (pri) {
14535             start = pri->crvs;
14536             lock = &pri->lock;
14537          } else {
14538             ast_cli(a->fd, "No such trunk group %d\n", trunkgroup);
14539             return CLI_FAILURE;
14540          }
14541       } else
14542 #endif
14543       if (!strcasecmp(a->argv[3], "group")) {
14544          targetnum = atoi(a->argv[4]);
14545          if ((targetnum < 0) || (targetnum > 63))
14546             return CLI_SHOWUSAGE;
14547          targetnum = 1 << targetnum;
14548          filtertype = 1;
14549       } else if (!strcasecmp(a->argv[3], "context")) {
14550          filtertype = 2;
14551       }
14552    }
14553
14554    ast_mutex_lock(lock);
14555 #ifdef HAVE_PRI
14556    ast_cli(a->fd, FORMAT2, pri ? "CRV" : "Chan", "Extension", "Context", "Language", "MOH Interpret", "Blocked", "State");
14557 #else
14558    ast_cli(a->fd, FORMAT2, "Chan", "Extension", "Context", "Language", "MOH Interpret", "Blocked", "State");
14559 #endif
14560
14561    tmp = start;
14562    while (tmp) {
14563       if (filtertype) {
14564          switch(filtertype) {
14565          case 1: /* dahdi show channels group <group> */
14566             if (!(tmp->group & targetnum)) {
14567                tmp = tmp->next;
14568                continue;
14569             }
14570             break;
14571          case 2: /* dahdi show channels context <context> */
14572             if (strcasecmp(tmp->context, a->argv[4])) {
14573                tmp = tmp->next;
14574                continue;
14575             }
14576             break;
14577          default:
14578             ;
14579          }
14580       }
14581       if (tmp->channel > 0) {
14582          snprintf(tmps, sizeof(tmps), "%d", tmp->channel);
14583       } else
14584          ast_copy_string(tmps, "pseudo", sizeof(tmps));
14585
14586       if (tmp->locallyblocked)
14587          blockstr[0] = 'L';
14588       else
14589          blockstr[0] = ' ';
14590
14591       if (tmp->remotelyblocked)
14592          blockstr[1] = 'R';
14593       else
14594          blockstr[1] = ' ';
14595
14596       blockstr[2] = '\0';
14597
14598       snprintf(statestr, sizeof(statestr), "%s", "In Service");
14599
14600       ast_cli(a->fd, FORMAT, tmps, tmp->exten, tmp->context, tmp->language, tmp->mohinterpret, blockstr, statestr);
14601       tmp = tmp->next;
14602    }
14603    ast_mutex_unlock(lock);
14604    return CLI_SUCCESS;
14605 #undef FORMAT
14606 #undef FORMAT2
14607 }
static char* dahdi_show_status (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14854 of file chan_dahdi.c.
References ast_cli(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, errno, ast_cli_args::fd, FORMAT, FORMAT2, and ast_cli_entry::usage.
14855 {
14856    #define FORMAT "%-40.40s %-7.7s %-6d %-6d %-6d %-3.3s %-4.4s %-8.8s %s\n"
14857    #define FORMAT2 "%-40.40s %-7.7s %-6.6s %-6.6s %-6.6s %-3.3s %-4.4s %-8.8s %s\n"
14858    int span;
14859    int res;
14860    char alarmstr[50];
14861
14862    int ctl;
14863    struct dahdi_spaninfo s;
14864
14865    switch (cmd) {
14866    case CLI_INIT:
14867       e->command = "dahdi show status";
14868       e->usage =
14869          "Usage: dahdi show status\n"
14870          "       Shows a list of DAHDI cards with status\n";
14871       return NULL;
14872    case CLI_GENERATE:
14873       return NULL;
14874    }
14875    ctl = open("/dev/dahdi/ctl", O_RDWR);
14876    if (ctl < 0) {
14877       ast_cli(a->fd, "No DAHDI found. Unable to open /dev/dahdi/ctl: %s\n", strerror(errno));
14878       return CLI_FAILURE;
14879    }
14880    ast_cli(a->fd, FORMAT2, "Description", "Alarms", "IRQ", "bpviol", "CRC4", "Framing", "Coding", "Options", "LBO");
14881
14882    for (span = 1; span < DAHDI_MAX_SPANS; ++span) {
14883       s.spanno = span;
14884       res = ioctl(ctl, DAHDI_SPANSTAT, &s);
14885       if (res) {
14886          continue;
14887       }
14888       alarmstr[0] = '\0';
14889       if (s.alarms > 0) {
14890          if (s.alarms & DAHDI_ALARM_BLUE)
14891             strcat(alarmstr, "BLU/");
14892          if (s.alarms & DAHDI_ALARM_YELLOW)
14893             strcat(alarmstr, "YEL/");
14894          if (s.alarms & DAHDI_ALARM_RED)
14895             strcat(alarmstr, "RED/");
14896          if (s.alarms & DAHDI_ALARM_LOOPBACK)
14897             strcat(alarmstr, "LB/");
14898          if (s.alarms & DAHDI_ALARM_RECOVER)
14899             strcat(alarmstr, "REC/");
14900          if (s.alarms & DAHDI_ALARM_NOTOPEN)
14901             strcat(alarmstr, "NOP/");
14902          if (!strlen(alarmstr))
14903             strcat(alarmstr, "UUU/");
14904          if (strlen(alarmstr)) {
14905             /* Strip trailing / */
14906             alarmstr[strlen(alarmstr) - 1] = '\0';
14907          }
14908       } else {
14909          if (s.numchans)
14910             strcpy(alarmstr, "OK");
14911          else
14912             strcpy(alarmstr, "UNCONFIGURED");
14913       }
14914
14915       ast_cli(a->fd, FORMAT, s.desc, alarmstr, s.irqmisses, s.bpvcount, s.crc4count,
14916          s.lineconfig & DAHDI_CONFIG_D4 ? "D4" :
14917          s.lineconfig & DAHDI_CONFIG_ESF ? "ESF" :
14918          s.lineconfig & DAHDI_CONFIG_CCS ? "CCS" :
14919          "CAS",
14920          s.lineconfig & DAHDI_CONFIG_B8ZS ? "B8ZS" :
14921          s.lineconfig & DAHDI_CONFIG_HDB3 ? "HDB3" :
14922          s.lineconfig & DAHDI_CONFIG_AMI ? "AMI" :
14923          "Unk",
14924          s.lineconfig & DAHDI_CONFIG_CRC4 ?
14925          s.lineconfig & DAHDI_CONFIG_NOTOPEN ? "CRC4/YEL" : "CRC4" : "YEL",
14926          lbostr[s.lbo]
14927);
14928    }
14929    close(ctl);
14930
14931    return CLI_SUCCESS;
14932 #undef FORMAT
14933 #undef FORMAT2
14934 }
static char* dahdi_show_version (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14936 of file chan_dahdi.c.
References ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, errno, ast_cli_args::fd, and ast_cli_entry::usage.
14937 {
14938    int pseudo_fd = -1;
14939    struct dahdi_versioninfo vi;
14940
14941    switch (cmd) {
14942    case CLI_INIT:
14943       e->command = "dahdi show version";
14944       e->usage =
14945          "Usage: dahdi show version\n"
14946          "       Shows the DAHDI version in use\n";
14947       return NULL;
14948    case CLI_GENERATE:
14949       return NULL;
14950    }
14951    if ((pseudo_fd = open("/dev/dahdi/ctl", O_RDONLY)) < 0) {
14952       ast_cli(a->fd, "Failed to open control file to get version.\n");
14953       return CLI_SUCCESS;
14954    }
14955
14956    strcpy(vi.version, "Unknown");
14957    strcpy(vi.echo_canceller, "Unknown");
14958
14959    if (ioctl(pseudo_fd, DAHDI_GETVERSION, &vi))
14960       ast_cli(a->fd, "Failed to get DAHDI version: %s\n", strerror(errno));
14961    else
14962       ast_cli(a->fd, "DAHDI Version: %s Echo Canceller: %s\n", vi.version, vi.echo_canceller);
14963
14964    close(pseudo_fd);
14965
14966    return CLI_SUCCESS;
14967 }
static char* dahdi_sig2str (int sig) [static]
Definition at line 2408 of file chan_dahdi.c.
References buf, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_GR303FXOKS, SIG_GR303FXSKS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, and SIG_SS7.
{
   static char buf[256];
   switch (sig) {
   case SIG_EM:
      return "E & M Immediate";
   case SIG_EMWINK:
      return "E & M Wink";
   case SIG_EM_E1:
      return "E & M E1";
   case SIG_FEATD:
      return "Feature Group D (DTMF)";
   case SIG_FEATDMF:
      return "Feature Group D (MF)";
   case SIG_FEATDMF_TA:
      return "Feature Groud D (MF) Tandem Access";
   case SIG_FEATB:
      return "Feature Group B (MF)";
   case SIG_E911:
      return "E911 (MF)";
   case SIG_FGC_CAMA:
      return "FGC/CAMA (Dialpulse)";
   case SIG_FGC_CAMAMF:
      return "FGC/CAMA (MF)";
   case SIG_FXSLS:
      return "FXS Loopstart";
   case SIG_FXSGS:
      return "FXS Groundstart";
   case SIG_FXSKS:
      return "FXS Kewlstart";
   case SIG_FXOLS:
      return "FXO Loopstart";
   case SIG_FXOGS:
      return "FXO Groundstart";
   case SIG_FXOKS:
      return "FXO Kewlstart";
   case SIG_PRI:
      return "ISDN PRI";
   case SIG_BRI:
      return "ISDN BRI Point to Point";
   case SIG_BRI_PTMP:
      return "ISDN BRI Point to MultiPoint";
   case SIG_SS7:
      return "SS7";
   case SIG_MFCR2:
      return "MFC/R2";
   case SIG_SF:
      return "SF (Tone) Immediate";
   case SIG_SFWINK:
      return "SF (Tone) Wink";
   case SIG_SF_FEATD:
      return "SF (Tone) with Feature Group D (DTMF)";
   case SIG_SF_FEATDMF:
      return "SF (Tone) with Feature Group D (MF)";
   case SIG_SF_FEATB:
      return "SF (Tone) with Feature Group B (MF)";
   case SIG_GR303FXOKS:
      return "GR-303 with FXOKS";
   case SIG_GR303FXSKS:
      return "GR-303 with FXSKS";
   case 0:
      return "Pseudo";
   default:
      snprintf(buf, sizeof(buf), "Unknown signalling %d", sig);
      return buf;
   }
}
static void dahdi_softhangup_all (void) [static]
Definition at line 14309 of file chan_dahdi.c.
References ast_channel_trylock, ast_channel_unlock, ast_mutex_lock(), ast_mutex_unlock(), AST_SOFTHANGUP_EXPLICIT, ast_softhangup_nolock(), ast_verbose, iflist, dahdi_pvt::lock, dahdi_pvt::next, option_debug, dahdi_pvt::owner, and dahdi_pvt::restartpending.
Referenced by dahdi_restart().
14310 {
14311    struct dahdi_pvt *p;
14312 retry:
14313    ast_mutex_lock(&iflock);
14314    for (p = iflist; p; p = p->next) {
14315       ast_mutex_lock(&p->lock);
14316       if (p->owner && !p->restartpending) {
14317          if (ast_channel_trylock(p->owner)) {
14318             if (option_debug > 2)
14319                ast_verbose("Avoiding deadlock\n");
14320             /* Avoid deadlock since you're not supposed to lock iflock or pvt before a channel */
14321             ast_mutex_unlock(&p->lock);
14322             ast_mutex_unlock(&iflock);
14323             goto retry;
14324          }
14325          if (option_debug > 2)
14326             ast_verbose("Softhanging up on %s\n", p->owner->name);
14327          ast_softhangup_nolock(p->owner, AST_SOFTHANGUP_EXPLICIT);
14328          p->restartpending = 1;
14329          num_restart_pending++;
14330          ast_channel_unlock(p->owner);
14331       }
14332       ast_mutex_unlock(&p->lock);
14333    }
14334    ast_mutex_unlock(&iflock);
14335 }
static void dahdi_train_ec (struct dahdi_pvt * p) [static]
Definition at line 2692 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_pvt::channel, dahdi_subchannel::dfd, dahdi_pvt::echocanon, dahdi_pvt::echotraining, errno, LOG_WARNING, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_answer(), and dahdi_handle_event().
{
   int x;
   int res;
   if (p && p->echocanon && p->echotraining) {
      x = p->echotraining;
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_ECHOTRAIN, &x);
      if (res)
         ast_log(LOG_WARNING, "Unable to request echo training on channel %d: %s\n", p->channel, strerror(errno));
      else
         ast_debug(1, "Engaged echo training on channel %d\n", p->channel);
   } else {
      ast_debug(1, "No echo training requested\n");
   }
}
static void dahdi_unlink (struct dahdi_pvt * slave, struct dahdi_pvt * master, int needlock) [static]
Definition at line 5044 of file chan_dahdi.c.
References ast_debug, ast_mutex_lock(), ast_mutex_trylock(), ast_mutex_unlock(), dahdi_pvt::channel, conf_del(), DEADLOCK_AVOIDANCE, dahdi_pvt::inconference, dahdi_pvt::lock, dahdi_pvt::master, MAX_SLAVES, dahdi_pvt::slaves, SUB_REAL, dahdi_pvt::subs, and update_conf().
Referenced by dahdi_bridge(), and dahdi_fixup().
{
   /* Unlink a specific slave or all slaves/masters from a given master */
   int x;
   int hasslaves;
   if (!master)
      return;
   if (needlock) {
      ast_mutex_lock(&master->lock);
      if (slave) {
         while (ast_mutex_trylock(&slave->lock)) {
            DEADLOCK_AVOIDANCE(&master->lock);
         }
      }
   }
   hasslaves = 0;
   for (x = 0; x < MAX_SLAVES; x++) {
      if (master->slaves[x]) {
         if (!slave || (master->slaves[x] == slave)) {
            /* Take slave out of the conference */
            ast_debug(1, "Unlinking slave %d from %d\n", master->slaves[x]->channel, master->channel);
            conf_del(master, &master->slaves[x]->subs[SUB_REAL], SUB_REAL);
            conf_del(master->slaves[x], &master->subs[SUB_REAL], SUB_REAL);
            master->slaves[x]->master = NULL;
            master->slaves[x] = NULL;
         } else
            hasslaves = 1;
      }
      if (!hasslaves)
         master->inconference = 0;
   }
   if (!slave) {
      if (master->master) {
         /* Take master out of the conference */
         conf_del(master->master, &master->subs[SUB_REAL], SUB_REAL);
         conf_del(master, &master->master->subs[SUB_REAL], SUB_REAL);
         hasslaves = 0;
         for (x = 0; x < MAX_SLAVES; x++) {
            if (master->master->slaves[x] == master)
               master->master->slaves[x] = NULL;
            else if (master->master->slaves[x])
               hasslaves = 1;
         }
         if (!hasslaves)
            master->master->inconference = 0;
      }
      master->master = NULL;
   }
   update_conf(master);
   if (needlock) {
      if (slave)
         ast_mutex_unlock(&slave->lock);
      ast_mutex_unlock(&master->lock);
   }
}
static int dahdi_wait_event (int fd) [inline, static]
Avoid the silly dahdi_waitevent which ignores a bunch of events.
Definition at line 385 of file chan_dahdi.c.
Referenced by ss_thread().
{
   int i, j = 0;
   i = DAHDI_IOMUX_SIGEVENT;
   if (ioctl(fd, DAHDI_IOMUX, &i) == -1)
      return -1;
   if (ioctl(fd, DAHDI_GETEVENT, &j) == -1)
      return -1;
   return j;
}
static int dahdi_wink (struct dahdi_pvt * p, int idx) [static]
Definition at line 7635 of file chan_dahdi.c.
References dahdi_set_hook(), dahdi_subchannel::dfd, and dahdi_pvt::subs.
Referenced by ss_thread().
{
   int j;
   dahdi_set_hook(p->subs[idx].dfd, DAHDI_WINK);
   for (;;)
   {
      /* set bits of interest */
      j = DAHDI_IOMUX_SIGEVENT;
      /* wait for some happening */
      if (ioctl(p->subs[idx].dfd,DAHDI_IOMUX,&j) == -1) return(-1);
      /* exit loop if we have it */
      if (j & DAHDI_IOMUX_SIGEVENT) break;
   }
   /* get the event info */
   if (ioctl(p->subs[idx].dfd,DAHDI_GETEVENT,&j) == -1) return(-1);
   return 0;
}
static int dahdi_write (struct ast_channel * ast, struct ast_frame * frame) [static]
Definition at line 7090 of file chan_dahdi.c.
References ast_debug, AST_FORMAT_ALAW, AST_FORMAT_SLINEAR, AST_FORMAT_ULAW, AST_FRAME_IMAGE, AST_FRAME_VOICE, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), dahdi_pvt::channel, dahdi_pvt::cidspill, dahdi_get_index(), dahdi_setlinear(), ast_frame::data, ast_frame::datalen, dahdi_subchannel::dfd, dahdi_pvt::dialing, dahdi_pvt::digital, errno, ast_frame::frametype, dahdi_subchannel::linear, dahdi_pvt::lock, LOG_WARNING, my_dahdi_write(), dahdi_pvt::outgoing, dahdi_pvt::owner, ast_frame::ptr, dahdi_pvt::sig, SIG_PRI, dahdi_pvt::span, ast_frame::subclass, dahdi_pvt::subs, and ast_channel::tech_pvt.
{
   struct dahdi_pvt *p = ast->tech_pvt;
   int res;
   int idx;
   idx = dahdi_get_index(ast, p, 0);
   if (idx < 0) {
      ast_log(LOG_WARNING, "%s doesn't really exist?\n", ast->name);
      return -1;
   }
#if 0
#ifdef HAVE_PRI
   ast_mutex_lock(&p->lock);
   if (!p->proceeding && p->sig==SIG_PRI && p->pri && !p->outgoing) {
      if (p->pri->pri) {
         if (!pri_grab(p, p->pri)) {
               pri_progress(p->pri->pri,p->call, PVT_TO_CHANNEL(p), !p->digital);
               pri_rel(p->pri);
         } else
               ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
      }
      p->proceeding=1;
   }
   ast_mutex_unlock(&p->lock);
#endif
#endif
   /* Write a frame of (presumably voice) data */
   if (frame->frametype != AST_FRAME_VOICE) {
      if (frame->frametype != AST_FRAME_IMAGE)
         ast_log(LOG_WARNING, "Don't know what to do with frame type '%d'\n", frame->frametype);
      return 0;
   }
   if ((frame->subclass != AST_FORMAT_SLINEAR) &&
      (frame->subclass != AST_FORMAT_ULAW) &&
      (frame->subclass != AST_FORMAT_ALAW)) {
      ast_log(LOG_WARNING, "Cannot handle frames in %d format\n", frame->subclass);
      return -1;
   }
   if (p->dialing) {
      ast_debug(1, "Dropping frame since I'm still dialing on %s...\n",ast->name);
      return 0;
   }
   if (!p->owner) {
      ast_debug(1, "Dropping frame since there is no active owner on %s...\n",ast->name);
      return 0;
   }
   if (p->cidspill) {
      ast_debug(1, "Dropping frame since I've still got a callerid spill\n");
      return 0;
   }
   /* Return if it's not valid data */
   if (!frame->data.ptr || !frame->datalen)
      return 0;
   if (frame->subclass == AST_FORMAT_SLINEAR) {
      if (!p->subs[idx].linear) {
         p->subs[idx].linear = 1;
         res = dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
         if (res)
            ast_log(LOG_WARNING, "Unable to set linear mode on channel %d\n", p->channel);
      }
      res = my_dahdi_write(p, (unsigned char *)frame->data.ptr, frame->datalen, idx, 1);
   } else {
      /* x-law already */
      if (p->subs[idx].linear) {
         p->subs[idx].linear = 0;
         res = dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
         if (res)
            ast_log(LOG_WARNING, "Unable to set companded mode on channel %d\n", p->channel);
      }
      res = my_dahdi_write(p, (unsigned char *)frame->data.ptr, frame->datalen, idx, 0);
   }
   if (res < 0) {
      ast_log(LOG_WARNING, "write failed: %s\n", strerror(errno));
      return -1;
   }
   return 0;
}
static void destroy_all_channels (void) [static]
Definition at line 3929 of file chan_dahdi.c.
References ast_free, ast_mutex_lock(), ast_mutex_unlock(), ast_verbose, dahdi_pvt::channel, dahdi_pvt::cidspill, destroy_dahdi_pvt(), iflist, dahdi_pvt::next, option_verbose, and VERBOSE_PREFIX_2.
Referenced by __unload_module(), and dahdi_restart().
{
   int x;
   struct dahdi_pvt *p, *pl;
   while (num_restart_pending) {
      usleep(1);
   }
   ast_mutex_lock(&iflock);
   /* Destroy all the interfaces and free their memory */
   p = iflist;
   while (p) {
      /* Free any callerid */
      if (p->cidspill)
         ast_free(p->cidspill);
      pl = p;
      p = p->next;
      x = pl->channel;
      /* Free associated memory */
      if (pl)
         destroy_dahdi_pvt(&pl);
      if (option_verbose > 2)
         ast_verbose(VERBOSE_PREFIX_2 "Unregistered channel %d\n", x);
   }
   iflist = NULL;
   ifcount = 0;
   ast_mutex_unlock(&iflock);
}
static int destroy_channel (struct dahdi_pvt * prev, struct dahdi_pvt * cur, int now) [static]
Definition at line 3879 of file chan_dahdi.c.
References destroy_dahdi_pvt(), iflist, dahdi_pvt::next, dahdi_subchannel::owner, dahdi_pvt::owner, dahdi_pvt::prev, and dahdi_pvt::subs.
Referenced by dahdi_destroy_channel_bynum(), and dahdi_hangup().
{
   int owned = 0;
   int i = 0;
   if (!now) {
      if (cur->owner) {
         owned = 1;
      }
      for (i = 0; i < 3; i++) {
         if (cur->subs[i].owner) {
            owned = 1;
         }
      }
      if (!owned) {
         if (prev) {
            prev->next = cur->next;
            if (prev->next)
               prev->next->prev = prev;
            else
               ifend = prev;
         } else {
            iflist = cur->next;
            if (iflist)
               iflist->prev = NULL;
            else
               ifend = NULL;
         }
         destroy_dahdi_pvt(&cur);
      }
   } else {
      if (prev) {
         prev->next = cur->next;
         if (prev->next)
            prev->next->prev = prev;
         else
            ifend = prev;
      } else {
         iflist = cur->next;
         if (iflist)
            iflist->prev = NULL;
         else
            ifend = NULL;
      }
      destroy_dahdi_pvt(&cur);
   }
   return 0;
}
static void destroy_dahdi_pvt (struct dahdi_pvt ** pvt) [static]
Definition at line 3856 of file chan_dahdi.c.
References ast_event_unsubscribe(), ast_mutex_destroy(), ast_smdi_interface_unref(), ast_variables_destroy(), dahdi_close_sub(), free, dahdi_pvt::lock, dahdi_pvt::mwi_event_sub, dahdi_pvt::next, dahdi_pvt::owner, dahdi_pvt::prev, dahdi_pvt::smdi_iface, SUB_REAL, ast_channel::tech_pvt, dahdi_pvt::use_smdi, and dahdi_pvt::vars.
Referenced by destroy_all_channels(), destroy_channel(), duplicate_pseudo(), and mkintf().
{
   struct dahdi_pvt *p = *pvt;
   /* Remove channel from the list */
   if (p->prev)
      p->prev->next = p->next;
   if (p->next)
      p->next->prev = p->prev;
   if (p->use_smdi)
      ast_smdi_interface_unref(p->smdi_iface);
   if (p->mwi_event_sub)
      ast_event_unsubscribe(p->mwi_event_sub);
   if (p->vars) {
      ast_variables_destroy(p->vars);
   }
   ast_mutex_destroy(&p->lock);
   dahdi_close_sub(p, SUB_REAL);
   if (p->owner)
      p->owner->tech_pvt = NULL;
   free(p);
   *pvt = NULL;
}
static int digit_to_dtmfindex (char digit) [static]
Definition at line 2229 of file chan_dahdi.c.
Referenced by dahdi_digit_begin().
{
   if (isdigit(digit))
      return DAHDI_TONE_DTMF_BASE + (digit - '0');
   else if (digit >= 'A' && digit <= 'D')
      return DAHDI_TONE_DTMF_A + (digit - 'A');
   else if (digit >= 'a' && digit <= 'd')
      return DAHDI_TONE_DTMF_A + (digit - 'a');
   else if (digit == '*')
      return DAHDI_TONE_DTMF_s;
   else if (digit == '#')
      return DAHDI_TONE_DTMF_p;
   else
      return -1;
}
static void disable_dtmf_detect (struct dahdi_pvt * p) [static]
Definition at line 5123 of file chan_dahdi.c.
References ast_dsp_set_features(), dahdi_subchannel::dfd, dahdi_pvt::dsp, DSP_FEATURE_DIGIT_DETECT, dahdi_pvt::dsp_features, dahdi_pvt::hardwaredtmf, dahdi_pvt::ignoredtmf, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_bridge().
{
   int val;
   p->ignoredtmf = 1;
   val = 0;
   ioctl(p->subs[SUB_REAL].dfd, DAHDI_TONEDETECT, &val);
   if (!p->hardwaredtmf && p->dsp) {
      p->dsp_features &= ~DSP_FEATURE_DIGIT_DETECT;
      ast_dsp_set_features(p->dsp, p->dsp_features);
   }
}
static void* do_monitor (void * data) [static]
Definition at line 9496 of file chan_dahdi.c.
References ast_calloc, ast_debug, ast_fdisset(), ast_free, AST_LAW, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_pthread_create_background, ast_strlen_zero(), mwi_thread_data::buf, buf, calc_energy(), dahdi_pvt::channel, dahdi_pvt::cidspill, dahdi_destroy_channel_bynum(), dahdi_get_event(), dahdi_subchannel::dfd, errno, event2str(), dahdi_pvt::fxsoffhookstate, handle_init_event(), has_voicemail(), iflist, last, mwi_thread_data::len, LOG_DEBUG, LOG_WARNING, dahdi_pvt::mailbox, dahdi_pvt::msgstate, mwi_send_init(), mwi_send_process_buffer(), mwi_send_process_event(), mwi_thread(), dahdi_pvt::mwimonitor_fsk, dahdi_pvt::mwimonitoractive, dahdi_pvt::mwisendactive, dahdi_pvt::next, dahdi_pvt::onhooktime, dahdi_subchannel::owner, dahdi_pvt::owner, mwi_thread_data::pvt, dahdi_pvt::radio, dahdi_pvt::sig, SIG_MFCR2, SUB_REAL, and dahdi_pvt::subs.
Referenced by restart_monitor().
{
   int count, res, res2, spoint, pollres=0;
   struct dahdi_pvt *i;
   struct dahdi_pvt *last = NULL;
   struct dahdi_pvt *doomed;
   time_t thispass = 0, lastpass = 0;
   int found;
   char buf[1024];
   struct pollfd *pfds=NULL;
   int lastalloc = -1;
   /* This thread monitors all the frame relay interfaces which are not yet in use
      (and thus do not have a separate thread) indefinitely */
   /* From here on out, we die whenever asked */
#if 0
   if (pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL)) {
      ast_log(LOG_WARNING, "Unable to set cancel type to asynchronous\n");
      return NULL;
   }
   ast_debug(1, "Monitor starting...\n");
#endif
   pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
   for (;;) {
      /* Lock the interface list */
      ast_mutex_lock(&iflock);
      if (!pfds || (lastalloc != ifcount)) {
         if (pfds) {
            ast_free(pfds);
            pfds = NULL;
         }
         if (ifcount) {
            if (!(pfds = ast_calloc(1, ifcount * sizeof(*pfds)))) {
               ast_mutex_unlock(&iflock);
               return NULL;
            }
         }
         lastalloc = ifcount;
      }
      /* Build the stuff we're going to poll on, that is the socket of every
         dahdi_pvt that does not have an associated owner channel */
      count = 0;
      i = iflist;
      while (i) {
         if ((i->subs[SUB_REAL].dfd > -1) && i->sig && (!i->radio) && !(i->sig & SIG_MFCR2)) {
            if (!i->owner && !i->subs[SUB_REAL].owner && !i->mwimonitoractive ) {
               /* This needs to be watched, as it lacks an owner */
               pfds[count].fd = i->subs[SUB_REAL].dfd;
               pfds[count].events = POLLPRI;
               pfds[count].revents = 0;
               /* If we are monitoring for VMWI or sending CID, we need to
                  read from the channel as well */
               if (i->cidspill || i->mwisendactive || i->mwimonitor_fsk)
                  pfds[count].events |= POLLIN;
               count++;
            }
         }
         i = i->next;
      }
      /* Okay, now that we know what to do, release the interface lock */
      ast_mutex_unlock(&iflock);
      pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
      pthread_testcancel();
      /* Wait at least a second for something to happen */
      res = poll(pfds, count, 1000);
      pthread_testcancel();
      pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
      /* Okay, poll has finished.  Let's see what happened.  */
      if (res < 0) {
         if ((errno != EAGAIN) && (errno != EINTR))
            ast_log(LOG_WARNING, "poll return %d: %s\n", res, strerror(errno));
         continue;
      }
      /* Alright, lock the interface list again, and let's look and see what has
         happened */
      ast_mutex_lock(&iflock);
      found = 0;
      spoint = 0;
      lastpass = thispass;
      thispass = time(NULL);
      i = iflist;
      doomed = NULL;
      for (i = iflist;; i = i->next) {
         if (doomed) {
            int res;
            res = dahdi_destroy_channel_bynum(doomed->channel);
            if (!res) {
               ast_log(LOG_WARNING, "Couldn't find channel to destroy, hopefully another destroy operation just happened.\n");
            }
            doomed = NULL;
         }
         if (!i) {
            break;
         }
         if (thispass != lastpass) {
            if (!found && ((i == last) || ((i == iflist) && !last))) {
               last = i;
               if (last) {
                  /* Only allow MWI to be initiated on a quiescent fxs port */
                  if (!last->mwisendactive &&   last->sig & __DAHDI_SIG_FXO &&
                        !last->fxsoffhookstate && !last->owner &&
                        !ast_strlen_zero(last->mailbox) && (thispass - last->onhooktime > 3)) {
                     res = has_voicemail(last);
                     if (last->msgstate != res) {
                        /* Set driver resources for signalling VMWI */
                        res2 = ioctl(last->subs[SUB_REAL].dfd, DAHDI_VMWI, &res);
                        if (res2) {
                           /* TODO: This message will ALWAYS be generated on some cards; any way to restrict it to those cards where it is interesting? */
                           ast_debug(3, "Unable to control message waiting led on channel %d: %s\n", last->channel, strerror(errno));
                        }
                        /* If enabled for FSK spill then initiate it */
                        if (mwi_send_init(last)) {
                           ast_log(LOG_WARNING, "Unable to initiate mwi send sequence on channel %d\n", last->channel);
                        }
                        last->msgstate = res;
                        found ++;
                     }
                  }
                  last = last->next;
               }
            }
         }
         if ((i->subs[SUB_REAL].dfd > -1) && i->sig) {
            if (i->radio && !i->owner)
            {
               res = dahdi_get_event(i->subs[SUB_REAL].dfd);
               if (res)
               {
                  ast_debug(1, "Monitor doohicky got event %s on radio channel %d\n", event2str(res), i->channel);
                  /* Don't hold iflock while handling init events */
                  ast_mutex_unlock(&iflock);
                  doomed = handle_init_event(i, res);
                  ast_mutex_lock(&iflock);
               }
               continue;
            }
            pollres = ast_fdisset(pfds, i->subs[SUB_REAL].dfd, count, &spoint);
            if (pollres & POLLIN) {
               if (i->owner || i->subs[SUB_REAL].owner) {
#ifdef HAVE_PRI
                  if (!i->pri)
#endif
                     ast_log(LOG_WARNING, "Whoa....  I'm owned but found (%d) in read...\n", i->subs[SUB_REAL].dfd);
                  continue;
               }
               if (!i->mwimonitor_fsk && !i->mwisendactive) {
                  ast_log(LOG_WARNING, "Whoa....  I'm not looking for MWI or sending MWI but am reading (%d)...\n", i->subs[SUB_REAL].dfd);
                  continue;
               }
               res = read(i->subs[SUB_REAL].dfd, buf, sizeof(buf));
               if (res > 0) {
                  if (i->mwimonitor_fsk) {
                     if (calc_energy((unsigned char *) buf, res, AST_LAW(i)) > mwilevel) {
                        pthread_attr_t attr;
                        pthread_t threadid;
                        struct mwi_thread_data *mtd;
                        pthread_attr_init(&attr);
                        pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
                        ast_log(LOG_DEBUG, "Maybe some MWI on port %d!\n", i->channel);
                        if ((mtd = ast_calloc(1, sizeof(*mtd)))) {
                           mtd->pvt = i;
                           memcpy(mtd->buf, buf, res);
                           mtd->len = res;
                           if (ast_pthread_create_background(&threadid, &attr, mwi_thread, mtd)) {
                              ast_log(LOG_WARNING, "Unable to start mwi thread on channel %d\n", i->channel);
                              ast_free(mtd);
                           }
                           i->mwimonitoractive = 1;
                        }
                     }
                  }
                  if (i->mwisendactive) {
                     mwi_send_process_buffer(i, res);
                  }
               } else {
                  ast_log(LOG_WARNING, "Read failed with %d: %s\n", res, strerror(errno));
               }
            }
            if (pollres & POLLPRI) {
               if (i->owner || i->subs[SUB_REAL].owner) {
#ifdef HAVE_PRI
                  if (!i->pri)
#endif
                     ast_log(LOG_WARNING, "Whoa....  I'm owned but found (%d)...\n", i->subs[SUB_REAL].dfd);
                  continue;
               }
               res = dahdi_get_event(i->subs[SUB_REAL].dfd);
               ast_debug(1, "Monitor doohicky got event %s on channel %d\n", event2str(res), i->channel);
               /* Don't hold iflock while handling init events */
               ast_mutex_unlock(&iflock);
               if (0 == i->mwisendactive || 0 == mwi_send_process_event(i, res)) {
                  doomed = handle_init_event(i, res);
               }
               ast_mutex_lock(&iflock);
            }
         }
      }
      ast_mutex_unlock(&iflock);
   }
   /* Never reached */
   return NULL;
}
static struct dahdi_pvt* duplicate_pseudo (struct dahdi_pvt * src) [static, read]
Definition at line 10771 of file chan_dahdi.c.
References ast_log(), ast_malloc, ast_mutex_init(), dahdi_pvt::buf_no, dahdi_pvt::buf_policy, dahdi_open(), dahdi_pvt::destroy, destroy_dahdi_pvt(), dahdi_subchannel::dfd, errno, iflist, dahdi_pvt::lock, LOG_ERROR, LOG_WARNING, dahdi_pvt::next, dahdi_pvt::prev, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_request().
10772 {
10773    struct dahdi_pvt *p;
10774    struct dahdi_bufferinfo bi;
10775    int res;
10776
10777    if ((p = ast_malloc(sizeof(*p)))) {
10778       memcpy(p, src, sizeof(struct dahdi_pvt));
10779       ast_mutex_init(&p->lock);
10780       p->subs[SUB_REAL].dfd = dahdi_open("/dev/dahdi/pseudo");
10781       if (p->subs[SUB_REAL].dfd < 0) {
10782          ast_log(LOG_ERROR, "Unable to dup channel: %s\n", strerror(errno));
10783          destroy_dahdi_pvt(&p);
10784          return NULL;
10785       }
10786       res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_GET_BUFINFO, &bi);
10787       if (!res) {
10788          bi.txbufpolicy = src->buf_policy;
10789          bi.rxbufpolicy = src->buf_policy;
10790          bi.numbufs = src->buf_no;
10791          res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SET_BUFINFO, &bi);
10792          if (res < 0) {
10793             ast_log(LOG_WARNING, "Unable to set buffer policy on dup channel: %s\n", strerror(errno));
10794          }
10795       } else
10796          ast_log(LOG_WARNING, "Unable to check buffer policy on dup channel: %s\n", strerror(errno));
10797    }
10798    p->destroy = 1;
10799    p->next = iflist;
10800    p->prev = NULL;
10801    iflist = p;
10802    if (iflist->next)
10803       iflist->next->prev = p;
10804    return p;
10805 }
static void enable_dtmf_detect (struct dahdi_pvt * p) [static]
Definition at line 5138 of file chan_dahdi.c.
References ast_dsp_set_features(), CHAN_PSEUDO, dahdi_pvt::channel, dahdi_subchannel::dfd, dahdi_pvt::dsp, DSP_FEATURE_DIGIT_DETECT, dahdi_pvt::dsp_features, dahdi_pvt::hardwaredtmf, dahdi_pvt::ignoredtmf, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_bridge().
{
   int val;
   if (p->channel == CHAN_PSEUDO)
      return;
   p->ignoredtmf = 0;
   val = DAHDI_TONEDETECT_ON | DAHDI_TONEDETECT_MUTE;
   ioctl(p->subs[SUB_REAL].dfd, DAHDI_TONEDETECT, &val);
   if (!p->hardwaredtmf && p->dsp) {
      p->dsp_features |= DSP_FEATURE_DIGIT_DETECT;
      ast_dsp_set_features(p->dsp, p->dsp_features);
   }
}
static char* event2str (int event) [static]
Definition at line 2389 of file chan_dahdi.c.
References ARRAY_LEN, and buf.
Referenced by __dahdi_exception(), dahdi_handle_event(), do_monitor(), mwi_thread(), and ss_thread().
{
   static char buf[256];
   if ((event < (ARRAY_LEN(events))) && (event > -1))
      return events[event];
   sprintf(buf, "Event %d", event); /* safe */
   return buf;
}
static void fill_rxgain (struct dahdi_gains * g, float gain, int law) [static]
Definition at line 2761 of file chan_dahdi.c.
References ARRAY_LEN, AST_ALAW, AST_LIN2A, AST_LIN2MU, and AST_MULAW.
Referenced by set_actual_rxgain().
{
   int j;
   int k;
   float linear_gain = pow(10.0, gain / 20.0);
   switch (law) {
   case DAHDI_LAW_ALAW:
      for (j = 0; j < ARRAY_LEN(g->rxgain); j++) {
         if (gain) {
            k = (int) (((float) AST_ALAW(j)) * linear_gain);
            if (k > 32767) k = 32767;
            if (k < -32767) k = -32767;
            g->rxgain[j] = AST_LIN2A(k);
         } else {
            g->rxgain[j] = j;
         }
      }
      break;
   case DAHDI_LAW_MULAW:
      for (j = 0; j < ARRAY_LEN(g->rxgain); j++) {
         if (gain) {
            k = (int) (((float) AST_MULAW(j)) * linear_gain);
            if (k > 32767) k = 32767;
            if (k < -32767) k = -32767;
            g->rxgain[j] = AST_LIN2MU(k);
         } else {
            g->rxgain[j] = j;
         }
      }
      break;
   }
}
static void fill_txgain (struct dahdi_gains * g, float gain, int law) [static]
Definition at line 2727 of file chan_dahdi.c.
References ARRAY_LEN, AST_ALAW, AST_LIN2A, AST_LIN2MU, and AST_MULAW.
Referenced by set_actual_txgain().
{
   int j;
   int k;
   float linear_gain = pow(10.0, gain / 20.0);
   switch (law) {
   case DAHDI_LAW_ALAW:
      for (j = 0; j < ARRAY_LEN(g->txgain); j++) {
         if (gain) {
            k = (int) (((float) AST_ALAW(j)) * linear_gain);
            if (k > 32767) k = 32767;
            if (k < -32767) k = -32767;
            g->txgain[j] = AST_LIN2A(k);
         } else {
            g->txgain[j] = j;
         }
      }
      break;
   case DAHDI_LAW_MULAW:
      for (j = 0; j < ARRAY_LEN(g->txgain); j++) {
         if (gain) {
            k = (int) (((float) AST_MULAW(j)) * linear_gain);
            if (k > 32767) k = 32767;
            if (k < -32767) k = -32767;
            g->txgain[j] = AST_LIN2MU(k);
         } else {
            g->txgain[j] = j;
         }
      }
      break;
   }
}
static struct dahdi_pvt* find_channel (int channel) [static, read]
Definition at line 15201 of file chan_dahdi.c.
References dahdi_pvt::channel, iflist, and dahdi_pvt::next.
Referenced by action_dahdidialoffhook(), action_dahdidndoff(), action_dahdidndon(), action_transfer(), and action_transferhangup().
15202 {
15203    struct dahdi_pvt *p = iflist;
15204    while (p) {
15205       if (p->channel == channel) {
15206          break;
15207       }
15208       p = p->next;
15209    }
15210    return p;
15211 }
static int get_alarms (struct dahdi_pvt * p) [static]
Checks channel for alarms
Parameters:
p a channel to check for alarms.
Returns:
the alarms on the span to which the channel belongs, or alarms on the channel if no span alarms.
Definition at line 5580 of file chan_dahdi.c.
References ast_log(), dahdi_pvt::channel, dahdi_subchannel::dfd, errno, LOG_WARNING, dahdi_pvt::span, SUB_REAL, and dahdi_pvt::subs.
Referenced by action_dahdishowchannels(), dahdi_handle_event(), handle_init_event(), mkintf(), and mwi_thread().
{
   int res;
   struct dahdi_spaninfo zi;
   struct dahdi_params params;
   memset(&zi, 0, sizeof(zi));
   zi.spanno = p->span;
   if ((res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SPANSTAT, &zi)) >= 0) {
      if (zi.alarms != DAHDI_ALARM_NONE)
         return zi.alarms;
   } else {
      ast_log(LOG_WARNING, "Unable to determine alarm on channel %d: %s\n", p->channel, strerror(errno));
      return 0;
   }
   /* No alarms on the span. Check for channel alarms. */
   memset(&params, 0, sizeof(params));
   if ((res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &params)) >= 0)
      return params.chan_alarms;
   ast_log(LOG_WARNING, "Unable to determine alarm on channel %d\n", p->channel);
   return DAHDI_ALARM_NONE;
}
static void handle_alarms (struct dahdi_pvt * p, int alms) [static]
Definition at line 5688 of file chan_dahdi.c.
References alarm2str(), ast_log(), dahdi_pvt::channel, EVENT_FLAG_SYSTEM, LOG_WARNING, and manager_event.
Referenced by dahdi_handle_event(), handle_init_event(), mkintf(), and mwi_thread().
{
   const char *alarm_str = alarm2str(alms);
   ast_log(LOG_WARNING, "Detected alarm on channel %d: %s\n", p->channel, alarm_str);
   manager_event(EVENT_FLAG_SYSTEM, "Alarm",
      "Alarm: %s\r\n"
      "Channel: %d\r\n",
      alarm_str, p->channel);
}
static char* handle_dahdi_show_cadences (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 14817 of file chan_dahdi.c.
References ast_cli(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, COLOR_BLACK, COLOR_GREEN, COLOR_MAGENTA, ast_cli_entry::command, ast_cli_args::fd, term_color(), and ast_cli_entry::usage.
14818 {
14819    int i, j;
14820    switch (cmd) {
14821    case CLI_INIT:
14822       e->command = "dahdi show cadences";
14823       e->usage =
14824          "Usage: dahdi show cadences\n"
14825          "       Shows all cadences currently defined\n";
14826       return NULL;
14827    case CLI_GENERATE:
14828       return NULL;
14829    }
14830    for (i = 0; i < num_cadence; i++) {
14831       char output[1024];
14832       char tmp[16], tmp2[64];
14833       snprintf(tmp, sizeof(tmp), "r%d: ", i + 1);
14834       term_color(output, tmp, COLOR_GREEN, COLOR_BLACK, sizeof(output));
14835
14836       for (j = 0; j < 16; j++) {
14837          if (cadences[i].ringcadence[j] == 0)
14838             break;
14839          snprintf(tmp, sizeof(tmp), "%d", cadences[i].ringcadence[j]);
14840          if (cidrings[i] * 2 - 1 == j)
14841             term_color(tmp2, tmp, COLOR_MAGENTA, COLOR_BLACK, sizeof(tmp2) - 1);
14842          else
14843             term_color(tmp2, tmp, COLOR_GREEN, COLOR_BLACK, sizeof(tmp2) - 1);
14844          if (j != 0)
14845             strncat(output, ",", sizeof(output) - strlen(output) - 1);
14846          strncat(output, tmp2, sizeof(output) - strlen(output) - 1);
14847       }
14848       ast_cli(a->fd,"%s\n",output);
14849    }
14850    return CLI_SUCCESS;
14851 }
static struct dahdi_pvt * handle_init_event (struct dahdi_pvt * i, int event) [static, read]
Definition at line 9269 of file chan_dahdi.c.
References ast_free, ast_hangup(), ast_log(), ast_pthread_create_detached, AST_STATE_PRERING, AST_STATE_RESERVED, AST_STATE_RING, ast_verb, dahdi_pvt::channel, dahdi_pvt::cid_start, CID_START_POLARITY, CID_START_POLARITY_IN, dahdi_pvt::cidspill, dahdi_disable_ec(), dahdi_enable_ec(), dahdi_new(), dahdi_set_hook(), dahdi_subchannel::dfd, errno, EVENT_FLAG_SYSTEM, dahdi_pvt::fxsoffhookstate, get_alarms(), handle_alarms(), dahdi_pvt::hanguponpolarityswitch, has_voicemail(), dahdi_pvt::immediate, dahdi_pvt::inalarm, LOG_NOTICE, LOG_WARNING, dahdi_pvt::mailbox, manager_event, dahdi_pvt::mwimonitor_neon, notify_message(), dahdi_pvt::polarity, POLARITY_REV, dahdi_pvt::radio, dahdi_pvt::ringt, dahdi_pvt::ringt_base, dahdi_pvt::sig, sig2str, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_GR303FXOKS, SIG_GR303FXSKS, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, SIG_SS7, ss_thread(), SUB_REAL, and dahdi_pvt::subs.
Referenced by do_monitor().
{
   int res;
   pthread_t threadid;
   struct ast_channel *chan;
   /* Handle an event on a given channel for the monitor thread. */
   switch (event) {
   case DAHDI_EVENT_NONE:
   case DAHDI_EVENT_BITSCHANGED:
      break;
   case DAHDI_EVENT_WINKFLASH:
   case DAHDI_EVENT_RINGOFFHOOK:
      if (i->inalarm) break;
      if (i->radio) break;
      /* Got a ring/answer.  What kind of channel are we? */
      switch (i->sig) {
      case SIG_FXOLS:
      case SIG_FXOGS:
      case SIG_FXOKS:
         res = dahdi_set_hook(i->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
         i->fxsoffhookstate = 1;
         if (res && (errno == EBUSY))
            break;
         if (i->cidspill) {
            /* Cancel VMWI spill */
            ast_free(i->cidspill);
            i->cidspill = NULL;
         }
         if (i->immediate) {
            dahdi_enable_ec(i);
            /* The channel is immediately up.  Start right away */
            res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_RINGTONE);
            chan = dahdi_new(i, AST_STATE_RING, 1, SUB_REAL, 0, 0);
            if (!chan) {
               ast_log(LOG_WARNING, "Unable to start PBX on channel %d\n", i->channel);
               res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
               if (res < 0)
                  ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", i->channel);
            }
         } else {
            /* Check for callerid, digits, etc */
            chan = dahdi_new(i, AST_STATE_RESERVED, 0, SUB_REAL, 0, 0);
            if (chan) {
               if (has_voicemail(i))
                  res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_STUTTER);
               else
                  res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_DIALTONE);
               if (res < 0)
                  ast_log(LOG_WARNING, "Unable to play dialtone on channel %d, do you have defaultzone and loadzone defined?\n", i->channel);
               if (ast_pthread_create_detached(&threadid, NULL, ss_thread, chan)) {
                  ast_log(LOG_WARNING, "Unable to start simple switch thread on channel %d\n", i->channel);
                  res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
                  if (res < 0)
                     ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", i->channel);
                  ast_hangup(chan);
               }
            } else
               ast_log(LOG_WARNING, "Unable to create channel\n");
         }
         break;
      case SIG_FXSLS:
      case SIG_FXSGS:
      case SIG_FXSKS:
            i->ringt = i->ringt_base;
            /* Fall through */
      case SIG_EMWINK:
      case SIG_FEATD:
      case SIG_FEATDMF:
      case SIG_FEATDMF_TA:
      case SIG_E911:
      case SIG_FGC_CAMA:
      case SIG_FGC_CAMAMF:
      case SIG_FEATB:
      case SIG_EM:
      case SIG_EM_E1:
      case SIG_SFWINK:
      case SIG_SF_FEATD:
      case SIG_SF_FEATDMF:
      case SIG_SF_FEATB:
      case SIG_SF:
         /* Check for callerid, digits, etc */
         if (i->cid_start == CID_START_POLARITY_IN) {
            chan = dahdi_new(i, AST_STATE_PRERING, 0, SUB_REAL, 0, 0);
         } else {
            chan = dahdi_new(i, AST_STATE_RING, 0, SUB_REAL, 0, 0);
         }
         if (!chan) {
            ast_log(LOG_WARNING, "Cannot allocate new structure on channel %d\n", i->channel);
         } else if (ast_pthread_create_detached(&threadid, NULL, ss_thread, chan)) {
            ast_log(LOG_WARNING, "Unable to start simple switch thread on channel %d\n", i->channel);
            res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
            if (res < 0) {
               ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", i->channel);
            }
            ast_hangup(chan);
         }
         break;
      default:
         ast_log(LOG_WARNING, "Don't know how to handle ring/answer with signalling %s on channel %d\n", sig2str(i->sig), i->channel);
         res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
         if (res < 0)
            ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", i->channel);
         return NULL;
      }
      break;
   case DAHDI_EVENT_NOALARM:
      i->inalarm = 0;
      ast_log(LOG_NOTICE, "Alarm cleared on channel %d\n", i->channel);
      manager_event(EVENT_FLAG_SYSTEM, "AlarmClear",
         "Channel: %d\r\n", i->channel);
      break;
   case DAHDI_EVENT_ALARM:
      i->inalarm = 1;
      res = get_alarms(i);
      handle_alarms(i, res);
      /* fall thru intentionally */
   case DAHDI_EVENT_ONHOOK:
      if (i->radio)
         break;
      /* Back on hook.  Hang up. */
      switch (i->sig) {
      case SIG_FXOLS:
      case SIG_FXOGS:
      case SIG_FEATD:
      case SIG_FEATDMF:
      case SIG_FEATDMF_TA:
      case SIG_E911:
      case SIG_FGC_CAMA:
      case SIG_FGC_CAMAMF:
      case SIG_FEATB:
      case SIG_EM:
      case SIG_EM_E1:
      case SIG_EMWINK:
      case SIG_SF_FEATD:
      case SIG_SF_FEATDMF:
      case SIG_SF_FEATB:
      case SIG_SF:
      case SIG_SFWINK:
      case SIG_FXSLS:
      case SIG_FXSGS:
      case SIG_FXSKS:
      case SIG_GR303FXSKS:
         dahdi_disable_ec(i);
         res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, -1);
         dahdi_set_hook(i->subs[SUB_REAL].dfd, DAHDI_ONHOOK);
         break;
      case SIG_GR303FXOKS:
      case SIG_FXOKS:
         dahdi_disable_ec(i);
         /* Diddle the battery for the zhone */
#ifdef ZHONE_HACK
         dahdi_set_hook(i->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
         usleep(1);
#endif
         res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, -1);
         dahdi_set_hook(i->subs[SUB_REAL].dfd, DAHDI_ONHOOK);
         break;
      case SIG_PRI:
      case SIG_SS7:
      case SIG_BRI:
      case SIG_BRI_PTMP:
         dahdi_disable_ec(i);
         res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, -1);
         break;
      default:
         ast_log(LOG_WARNING, "Don't know how to handle on hook with signalling %s on channel %d\n", sig2str(i->sig), i->channel);
         res = tone_zone_play_tone(i->subs[SUB_REAL].dfd, -1);
         return NULL;
      }
      if (i->sig & __DAHDI_SIG_FXO) {
         i->fxsoffhookstate = 0;
      }
      break;
   case DAHDI_EVENT_POLARITY:
      switch (i->sig) {
      case SIG_FXSLS:
      case SIG_FXSKS:
      case SIG_FXSGS:
         /* We have already got a PR before the channel was
            created, but it wasn't handled. We need polarity
            to be REV for remote hangup detection to work.
            At least in Spain */
         if (i->hanguponpolarityswitch)
            i->polarity = POLARITY_REV;
         if (i->cid_start == CID_START_POLARITY || i->cid_start == CID_START_POLARITY_IN) {
            i->polarity = POLARITY_REV;
            ast_verb(2, "Starting post polarity "
               "CID detection on channel %d\n",
               i->channel);
            chan = dahdi_new(i, AST_STATE_PRERING, 0, SUB_REAL, 0, 0);
            if (!chan) {
               ast_log(LOG_WARNING, "Cannot allocate new structure on channel %d\n", i->channel);
            } else if (ast_pthread_create_detached(&threadid, NULL, ss_thread, chan)) {
               ast_log(LOG_WARNING, "Unable to start simple switch thread on channel %d\n", i->channel);
            }
         }
         break;
      default:
         ast_log(LOG_WARNING, "handle_init_event detected "
            "polarity reversal on non-FXO (SIG_FXS) "
            "interface %d\n", i->channel);
      }
      break;
   case DAHDI_EVENT_REMOVED: /* destroy channel, will actually do so in do_monitor */
      ast_log(LOG_NOTICE,
            "Got DAHDI_EVENT_REMOVED. Destroying channel %d\n",
            i->channel);
      return i;
   case DAHDI_EVENT_NEONMWI_ACTIVE:
      if (i->mwimonitor_neon) {
         notify_message(i->mailbox, 1);
         ast_log(LOG_NOTICE, "NEON MWI set for channel %d, mailbox %s \n", i->channel, i->mailbox);
      }
      break;
   case DAHDI_EVENT_NEONMWI_INACTIVE:
      if (i->mwimonitor_neon) {
         notify_message(i->mailbox, 0);
         ast_log(LOG_NOTICE, "NEON MWI cleared for channel %d, mailbox %s\n", i->channel, i->mailbox);
      }
      break;
   }
   return NULL;
}
static int has_voicemail (struct dahdi_pvt * p) [static]
Definition at line 3001 of file chan_dahdi.c.
References ast_app_has_voicemail(), ast_event_destroy(), ast_event_get_cached(), ast_event_get_ie_uint(), AST_EVENT_IE_CONTEXT, AST_EVENT_IE_END, AST_EVENT_IE_MAILBOX, AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_MWI, ast_strdupa, ast_strlen_zero(), context, dahdi_pvt::mailbox, mailbox, and strsep().
Referenced by dahdi_handle_event(), do_monitor(), handle_init_event(), and mwi_send_init().
{
   int new_msgs;
   struct ast_event *event;
   char *mailbox, *context;
   mailbox = context = ast_strdupa(p->mailbox);
   strsep(&context, "@");
   if (ast_strlen_zero(context))
      context = "default";
   event = ast_event_get_cached(AST_EVENT_MWI,
      AST_EVENT_IE_MAILBOX, AST_EVENT_IE_PLTYPE_STR, mailbox,
      AST_EVENT_IE_CONTEXT, AST_EVENT_IE_PLTYPE_STR, context,
      AST_EVENT_IE_END);
   if (event) {
      new_msgs = ast_event_get_ie_uint(event, AST_EVENT_IE_NEWMSGS);
      ast_event_destroy(event);
   } else
      new_msgs = ast_app_has_voicemail(p->mailbox, NULL);
   return new_msgs;
}
static int isourconf (struct dahdi_pvt * p, struct dahdi_subchannel * c) [static]
Definition at line 2516 of file chan_dahdi.c.
References dahdi_pvt::channel, dahdi_pvt::confno, and dahdi_subchannel::curconf.
Referenced by conf_del().
{
   /* If they're listening to our channel, they're ours */
   if ((p->channel == c->curconf.confno) && (c->curconf.confmode == DAHDI_CONF_DIGITALMON))
      return 1;
   /* If they're a talker on our (allocated) conference, they're ours */
   if ((p->confno > 0) && (p->confno == c->curconf.confno) && (c->curconf.confmode & DAHDI_CONF_TALKER))
      return 1;
   return 0;
}
static int isslavenative (struct dahdi_pvt * p, struct dahdi_pvt ** out) [static]
Definition at line 2546 of file chan_dahdi.c.
References dahdi_subchannel::dfd, dahdi_subchannel::inthreeway, dahdi_pvt::law, MAX_SLAVES, dahdi_pvt::slaves, and dahdi_pvt::subs.
Referenced by update_conf().
{
   int x;
   int useslavenative;
   struct dahdi_pvt *slave = NULL;
   /* Start out optimistic */
   useslavenative = 1;
   /* Update conference state in a stateless fashion */
   for (x = 0; x < 3; x++) {
      /* Any three-way calling makes slave native mode *definitely* out
         of the question */
      if ((p->subs[x].dfd > -1) && p->subs[x].inthreeway)
         useslavenative = 0;
   }
   /* If we don't have any 3-way calls, check to see if we have
      precisely one slave */
   if (useslavenative) {
      for (x = 0; x < MAX_SLAVES; x++) {
         if (p->slaves[x]) {
            if (slave) {
               /* Whoops already have a slave!  No
                  slave native and stop right away */
               slave = NULL;
               useslavenative = 0;
               break;
            } else {
               /* We have one slave so far */
               slave = p->slaves[x];
            }
         }
      }
   }
   /* If no slave, slave native definitely out */
   if (!slave)
      useslavenative = 0;
   else if (slave->law != p->law) {
      useslavenative = 0;
      slave = NULL;
   }
   if (out)
      *out = slave;
   return useslavenative;
}
static int load_module (void) [static]
Definition at line 17308 of file chan_dahdi.c.
References __unload_module(), action_dahdidialoffhook(), action_dahdidndoff(), action_dahdidndon(), action_dahdirestart(), action_dahdishowchannels(), action_transfer(), action_transferhangup(), ARRAY_LEN, ast_channel_register(), ast_cli_register_multiple(), ast_cond_init(), ast_log(), ast_manager_register, AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_FAILURE, ast_mutex_init(), AST_PTHREADT_NULL, ast_register_application_xml, ast_string_field_init, ast_string_field_set, inuse, lock, LOG_ERROR, name, and setup_dahdi().
17309 {
17310    int res;
17311 #if defined(HAVE_PRI) || defined(HAVE_SS7)
17312    int y, i;
17313 #endif
17314
17315 #ifdef HAVE_PRI
17316    memset(pris, 0, sizeof(pris));
17317    for (y = 0; y < NUM_SPANS; y++) {
17318       ast_mutex_init(&pris[y].lock);
17319       pris[y].offset = -1;
17320       pris[y].master = AST_PTHREADT_NULL;
17321       for (i = 0; i < NUM_DCHANS; i++)
17322          pris[y].fds[i] = -1;
17323    }
17324    pri_set_error(dahdi_pri_error);
17325    pri_set_message(dahdi_pri_message);
17326    ast_register_application_xml(dahdi_send_keypad_facility_app, dahdi_send_keypad_facility_exec);
17327 #ifdef HAVE_PRI_PROG_W_CAUSE
17328    ast_register_application_xml(dahdi_send_callrerouting_facility_app, dahdi_send_callrerouting_facility_exec);
17329 #endif
17330 #endif
17331 #ifdef HAVE_SS7
17332    memset(linksets, 0, sizeof(linksets));
17333    for (y = 0; y < NUM_SPANS; y++) {
17334       ast_mutex_init(&linksets[y].lock);
17335       linksets[y].master = AST_PTHREADT_NULL;
17336       for (i = 0; i < NUM_DCHANS; i++)
17337          linksets[y].fds[i] = -1;
17338    }
17339    ss7_set_error(dahdi_ss7_error);
17340    ss7_set_message(dahdi_ss7_message);
17341 #endif /* HAVE_SS7 */
17342    res = setup_dahdi(0);
17343    /* Make sure we can register our DAHDI channel type */
17344    if (res)
17345       return AST_MODULE_LOAD_DECLINE;
17346    if (ast_channel_register(&dahdi_tech)) {
17347       ast_log(LOG_ERROR, "Unable to register channel class 'DAHDI'\n");
17348       __unload_module();
17349       return AST_MODULE_LOAD_FAILURE;
17350    }
17351 #ifdef HAVE_PRI
17352    ast_string_field_init(&inuse, 16);
17353    ast_string_field_set(&inuse, name, "GR-303InUse");
17354    ast_cli_register_multiple(dahdi_pri_cli, ARRAY_LEN(dahdi_pri_cli));
17355 #endif
17356 #ifdef HAVE_SS7
17357    ast_cli_register_multiple(dahdi_ss7_cli, ARRAY_LEN(dahdi_ss7_cli));
17358 #endif
17359 #ifdef HAVE_OPENR2
17360    ast_cli_register_multiple(dahdi_mfcr2_cli, sizeof(dahdi_mfcr2_cli)/sizeof(dahdi_mfcr2_cli[0]));
17361    ast_register_application_xml(dahdi_accept_r2_call_app, dahdi_accept_r2_call_exec);
17362 #endif
17363
17364    ast_cli_register_multiple(dahdi_cli, ARRAY_LEN(dahdi_cli));
17365
17366    memset(round_robin, 0, sizeof(round_robin));
17367    ast_manager_register("DAHDITransfer", 0, action_transfer, "Transfer DAHDI Channel");
17368    ast_manager_register("DAHDIHangup", 0, action_transferhangup, "Hangup DAHDI Channel");
17369    ast_manager_register("DAHDIDialOffhook", 0, action_dahdidialoffhook, "Dial over DAHDI channel while offhook");
17370    ast_manager_register("DAHDIDNDon", 0, action_dahdidndon, "Toggle DAHDI channel Do Not Disturb status ON");
17371    ast_manager_register("DAHDIDNDoff", 0, action_dahdidndoff, "Toggle DAHDI channel Do Not Disturb status OFF");
17372    ast_manager_register("DAHDIShowChannels", 0, action_dahdishowchannels, "Show status DAHDI channels");
17373    ast_manager_register("DAHDIRestart", 0, action_dahdirestart, "Fully Restart DAHDI channels (terminates calls)");
17374
17375    ast_cond_init(&ss_thread_complete, NULL);
17376
17377    return res;
17378 }
static struct dahdi_pvt* mkintf (int channel, const struct dahdi_chan_conf * conf, struct dahdi_pri * pri, int reloading) [static, read]
Definition at line 9990 of file chan_dahdi.c.
References dahdi_pvt::accountcode, dahdi_pvt::adsi, dahdi_pvt::amaflags, dahdi_pvt::answeronpolarityswitch, ast_calloc, ast_copy_string(), ast_dsp_set_digitmode(), AST_EVENT_IE_CONTEXT, AST_EVENT_IE_END, AST_EVENT_IE_MAILBOX, AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_EXISTS, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_MWI, ast_event_subscribe(), ast_log(), ast_mutex_init(), ast_smdi_interface_find(), ast_strdupa, ast_strlen_zero(), ast_variable_new(), dahdi_pvt::buf_no, dahdi_pvt::buf_policy, dahdi_pvt::bufsize, dahdi_pvt::busy_quietlength, dahdi_pvt::busy_tonelength, dahdi_pvt::busycount, dahdi_pvt::busydetect, dahdi_pvt::callgroup, dahdi_pvt::callprogress, dahdi_pvt::callreturn, dahdi_pvt::callwaiting, dahdi_pvt::callwaitingcallerid, dahdi_pvt::cancallforward, dahdi_pvt::canpark, dahdi_chan_conf::chan, CHAN_PSEUDO, dahdi_pvt::channel, dahdi_pvt::cid_name, dahdi_pvt::cid_num, dahdi_pvt::cid_rxgain, CID_SIG_SMDI, dahdi_pvt::cid_signalling, dahdi_pvt::cid_start, dahdi_pvt::cid_ton, dahdi_pvt::confno, context, dahdi_pvt::context, dahdi_open(), dahdi_set_hook(), dahdi_pvt::dahditrcallerid, dahdi_pvt::defcontext, dahdi_pvt::destroy, destroy_dahdi_pvt(), dahdi_subchannel::dfd, dahdi_pvt::drings, dahdi_pvt::dsp, DSP_DIGITMODE_DTMF, dahdi_pvt::dtmfrelax, dahdi_pvt::echocanbridged, dahdi_pvt::echocancel, dahdi_pvt::echotraining, errno, dahdi_pvt::faxbuf_no, dahdi_pvt::faxbuf_policy, ast_variable::file, dahdi_pvt::firstradio, free, dahdi_pvt::fxsoffhookstate, get_alarms(), dahdi_pvt::group, handle_alarms(), dahdi_pvt::hanguponpolarityswitch, dahdi_pvt::head, dahdi_pvt::hidecallerid, iflist, dahdi_pvt::immediate, dahdi_pvt::inalarm, dahdi_pvt::inservice, dahdi_chan_conf::is_sig_auto, dahdi_pvt::language, dahdi_pvt::law, dahdi_pvt::locallyblocked, dahdi_pvt::lock, LOG_ERROR, LOG_NOTICE, LOG_WARNING, mailbox, dahdi_pvt::mailbox, MAX_CHANNELS, dahdi_pvt::mohinterpret, dahdi_pvt::mohsuggest, dahdi_pvt::msgstate, mwi_event_cb(), dahdi_pvt::mwi_event_sub, dahdi_pvt::mwimonitor_fsk, dahdi_pvt::mwimonitor_neon, dahdi_pvt::mwimonitor_rpas, ast_variable::name, ast_variable::next, dahdi_pvt::next, dahdi_pvt::onhooktime, dahdi_pvt::outsigmod, dahdi_pvt::parkinglot, dahdi_pvt::permcallwaiting, dahdi_pvt::permhidecallerid, dahdi_pvt::pickupgroup, dahdi_pvt::polarityonanswerdelay, dahdi_pvt::prev, dahdi_pvt::priexclusive, dahdi_pvt::priindication_oob, dahdi_pvt::propconfno, dahdi_pvt::pulse, dahdi_pvt::radio, distRingData::range, dahdi_pvt::remotelyblocked, dahdi_pvt::restrictcid, dahdi_distRings::ringnum, dahdi_pvt::ringt_base, dahdi_pvt::rxgain, dahdi_pvt::sendcalleridafter, set_actual_gain(), dahdi_pvt::sig, sig2str, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSKS, SIG_FXSLS, SIG_GR303FXOKS, SIG_GR303FXSKS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, SIG_SS7, sigtype_to_signalling(), dahdi_pvt::smdi_iface, dahdi_chan_conf::smdi_port, dahdi_pvt::span, dahdi_pvt::stripmsd, strsep(), SUB_REAL, dahdi_pvt::subs, dahdi_pvt::threewaycalling, dahdi_chan_conf::timing, dahdi_pvt::tonezone, dahdi_pvt::transfer, dahdi_pvt::transfertobusy, dahdi_pvt::txgain, update_conf(), dahdi_pvt::use_callerid, dahdi_pvt::use_callingpres, dahdi_pvt::use_smdi, dahdi_pvt::usedistinctiveringdetection, dahdi_pvt::usefaxbuffers, ast_variable::value, dahdi_pvt::vars, and dahdi_pvt::waitfordialtone.
Referenced by build_channels(), and process_dahdi().
{
   /* Make a dahdi_pvt structure for this interface (or CRV if "pri" is specified) */
   struct dahdi_pvt *tmp = NULL, *tmp2, *prev = NULL;
   char fn[80];
   struct dahdi_bufferinfo bi;
   int res;
   int span = 0;
   int here = 0;
10000    int x;
10001    struct dahdi_pvt **wlist;
10002    struct dahdi_pvt **wend;
10003    struct dahdi_params p;
10004
10005    wlist = &iflist;
10006    wend = &ifend;
10007
10008 #ifdef HAVE_PRI
10009    if (pri) {
10010       wlist = &pri->crvs;
10011       wend = &pri->crvend;
10012    }
10013 #endif
10014
10015    tmp2 = *wlist;
10016    prev = NULL;
10017
10018    while (tmp2) {
10019       if (!tmp2->destroy) {
10020          if (tmp2->channel == channel) {
10021             tmp = tmp2;
10022             here = 1;
10023             break;
10024          }
10025          if (tmp2->channel > channel) {
10026             break;
10027          }
10028       }
10029       prev = tmp2;
10030       tmp2 = tmp2->next;
10031    }
10032
10033    if (!here && reloading != 1) {
10034       if (!(tmp = ast_calloc(1, sizeof(*tmp)))) {
10035          if (tmp)
10036             free(tmp);
10037          return NULL;
10038       }
10039       ast_mutex_init(&tmp->lock);
10040       ifcount++;
10041       for (x = 0; x < 3; x++)
10042          tmp->subs[x].dfd = -1;
10043       tmp->channel = channel;
10044       tmp->priindication_oob = conf->chan.priindication_oob;
10045    }
10046
10047    if (tmp) {
10048       int chan_sig = conf->chan.sig;
10049       if (!here) {
10050          if ((channel != CHAN_PSEUDO) && !pri) {
10051             int count = 0;
10052             snprintf(fn, sizeof(fn), "%d", channel);
10053             /* Open non-blocking */
10054             tmp->subs[SUB_REAL].dfd = dahdi_open(fn);
10055             while (tmp->subs[SUB_REAL].dfd < 0 && reloading == 2 && count < 1000) { /* the kernel may not call dahdi_release fast enough for the open flagbit to be cleared in time */
10056                usleep(1);
10057                tmp->subs[SUB_REAL].dfd = dahdi_open(fn);
10058                count++;
10059             }
10060             /* Allocate a DAHDI structure */
10061             if (tmp->subs[SUB_REAL].dfd < 0) {
10062                ast_log(LOG_ERROR, "Unable to open channel %d: %s\nhere = %d, tmp->channel = %d, channel = %d\n", channel, strerror(errno), here, tmp->channel, channel);
10063                destroy_dahdi_pvt(&tmp);
10064                return NULL;
10065             }
10066             memset(&p, 0, sizeof(p));
10067             res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &p);
10068             if (res < 0) {
10069                ast_log(LOG_ERROR, "Unable to get parameters: %s\n", strerror(errno));
10070                destroy_dahdi_pvt(&tmp);
10071                return NULL;
10072             }
10073             if (conf->is_sig_auto)
10074                chan_sig = sigtype_to_signalling(p.sigtype);
10075             if (p.sigtype != (chan_sig & 0x3ffff)) {
10076                ast_log(LOG_ERROR, "Signalling requested on channel %d is %s but line is in %s signalling\n", channel, sig2str(chan_sig), sig2str(p.sigtype));
10077                destroy_dahdi_pvt(&tmp);
10078                return NULL;
10079             }
10080             tmp->law = p.curlaw;
10081             tmp->span = p.spanno;
10082             span = p.spanno - 1;
10083          } else {
10084             if (channel == CHAN_PSEUDO)
10085                chan_sig = 0;
10086             else if ((chan_sig != SIG_FXOKS) && (chan_sig != SIG_FXSKS)) {
10087                ast_log(LOG_ERROR, "CRV's must use FXO/FXS Kewl Start (fxo_ks/fxs_ks) signalling only.\n");
10088                return NULL;
10089             }
10090          }
10091 #ifdef HAVE_SS7
10092          if (chan_sig == SIG_SS7) {
10093             struct dahdi_ss7 *ss7;
10094             int clear = 0;
10095             if (ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_AUDIOMODE, &clear)) {
10096                ast_log(LOG_ERROR, "Unable to set clear mode on clear channel %d of span %d: %s\n", channel, p.spanno, strerror(errno));
10097                destroy_dahdi_pvt(&tmp);
10098                return NULL;
10099             }
10100
10101             ss7 = ss7_resolve_linkset(cur_linkset);
10102             if (!ss7) {
10103                ast_log(LOG_ERROR, "Unable to find linkset %d\n", cur_linkset);
10104                destroy_dahdi_pvt(&tmp);
10105                return NULL;
10106             }
10107             if (cur_cicbeginswith < 0) {
10108                ast_log(LOG_ERROR, "Need to set cicbeginswith for the channels!\n");
10109                destroy_dahdi_pvt(&tmp);
10110                return NULL;
10111             }
10112
10113             tmp->cic = cur_cicbeginswith++;
10114
10115             /* DB: Add CIC's DPC information */
10116             tmp->dpc = cur_defaultdpc;
10117
10118             tmp->ss7 = ss7;
10119             tmp->ss7call = NULL;
10120             ss7->pvts[ss7->numchans++] = tmp;
10121
10122             ast_copy_string(ss7->internationalprefix, conf->ss7.internationalprefix, sizeof(ss7->internationalprefix));
10123             ast_copy_string(ss7->nationalprefix, conf->ss7.nationalprefix, sizeof(ss7->nationalprefix));
10124             ast_copy_string(ss7->subscriberprefix, conf->ss7.subscriberprefix, sizeof(ss7->subscriberprefix));
10125             ast_copy_string(ss7->unknownprefix, conf->ss7.unknownprefix, sizeof(ss7->unknownprefix));
10126
10127             ss7->called_nai = conf->ss7.called_nai;
10128             ss7->calling_nai = conf->ss7.calling_nai;
10129          }
10130 #endif
10131 #ifdef HAVE_OPENR2
10132          if (chan_sig == SIG_MFCR2 && reloading != 1) {
10133             struct dahdi_mfcr2 *r2_link;
10134             r2_link = dahdi_r2_get_link();
10135             if (!r2_link) {
10136                ast_log(LOG_WARNING, "Cannot get another R2 DAHDI context!\n");
10137                destroy_dahdi_pvt(&tmp);
10138                return NULL;
10139             }
10140             if (!r2_link->protocol_context && dahdi_r2_set_context(r2_link, conf)) {
10141                ast_log(LOG_ERROR, "Cannot create OpenR2 protocol context.\n");
10142                destroy_dahdi_pvt(&tmp);
10143                return NULL;
10144             }
10145             if (r2_link->numchans == (sizeof(r2_link->pvts)/sizeof(r2_link->pvts[0]))) {
10146                ast_log(LOG_ERROR, "Cannot add more channels to this link!\n");
10147                destroy_dahdi_pvt(&tmp);
10148                return NULL;
10149             }
10150             r2_link->pvts[r2_link->numchans++] = tmp;
10151             tmp->r2chan = openr2_chan_new_from_fd(r2_link->protocol_context,
10152                                         tmp->subs[SUB_REAL].dfd,
10153                                         NULL, NULL);
10154             if (!tmp->r2chan) {
10155                openr2_liberr_t err = openr2_context_get_last_error(r2_link->protocol_context);
10156                ast_log(LOG_ERROR, "Cannot create OpenR2 channel: %s\n", openr2_context_error_string(err));
10157                destroy_dahdi_pvt(&tmp);
10158                return NULL;
10159             }
10160             tmp->mfcr2 = r2_link;
10161             if (conf->mfcr2.call_files) {
10162                openr2_chan_enable_call_files(tmp->r2chan);
10163             }
10164             openr2_chan_set_client_data(tmp->r2chan, tmp);
10165             /* cast seems to be needed to get rid of the annoying warning regarding format attribute  */
10166             openr2_chan_set_logging_func(tmp->r2chan, (openr2_logging_func_t)dahdi_r2_on_chan_log);
10167             openr2_chan_set_log_level(tmp->r2chan, conf->mfcr2.loglevel);
10168             tmp->mfcr2_category = conf->mfcr2.category;
10169             tmp->mfcr2_charge_calls = conf->mfcr2.charge_calls;
10170             tmp->mfcr2_allow_collect_calls = conf->mfcr2.allow_collect_calls;
10171             tmp->mfcr2_forced_release = conf->mfcr2.forced_release;
10172             tmp->mfcr2_accept_on_offer = conf->mfcr2.accept_on_offer;
10173             tmp->mfcr2call = 0;
10174             tmp->mfcr2_dnis_index = 0;
10175             tmp->mfcr2_ani_index = 0;
10176             r2_link->monitored_count++;
10177          }
10178 #endif
10179 #ifdef HAVE_PRI
10180          if ((chan_sig == SIG_PRI) || (chan_sig == SIG_BRI) || (chan_sig == SIG_BRI_PTMP) || (chan_sig == SIG_GR303FXOKS) || (chan_sig == SIG_GR303FXSKS)) {
10181             int offset;
10182             int myswitchtype;
10183             int matchesdchan;
10184             int x,y;
10185             offset = 0;
10186             if (((chan_sig == SIG_PRI) || (chan_sig == SIG_BRI) || (chan_sig == SIG_BRI_PTMP))
10187                   && ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_AUDIOMODE, &offset)) {
10188                ast_log(LOG_ERROR, "Unable to set clear mode on clear channel %d of span %d: %s\n", channel, p.spanno, strerror(errno));
10189                destroy_dahdi_pvt(&tmp);
10190                return NULL;
10191             }
10192             if (span >= NUM_SPANS) {
10193                ast_log(LOG_ERROR, "Channel %d does not lie on a span I know of (%d)\n", channel, span);
10194                destroy_dahdi_pvt(&tmp);
10195                return NULL;
10196             } else {
10197                struct dahdi_spaninfo si;
10198                si.spanno = 0;
10199                if (ioctl(tmp->subs[SUB_REAL].dfd,DAHDI_SPANSTAT,&si) == -1) {
10200                   ast_log(LOG_ERROR, "Unable to get span status: %s\n", strerror(errno));
10201                   destroy_dahdi_pvt(&tmp);
10202                   return NULL;
10203                }
10204                /* Store the logical span first based upon the real span */
10205                tmp->logicalspan = pris[span].prilogicalspan;
10206                pri_resolve_span(&span, channel, (channel - p.chanpos), &si);
10207                if (span < 0) {
10208                   ast_log(LOG_WARNING, "Channel %d: Unable to find locate channel/trunk group!\n", channel);
10209                   destroy_dahdi_pvt(&tmp);
10210                   return NULL;
10211                }
10212                if ((chan_sig == SIG_PRI) ||
10213                      (chan_sig == SIG_BRI) ||
10214                      (chan_sig == SIG_BRI_PTMP))
10215                   myswitchtype = conf->pri.switchtype;
10216                else
10217                   myswitchtype = PRI_SWITCH_GR303_TMC;
10218                /* Make sure this isn't a d-channel */
10219                matchesdchan=0;
10220                for (x = 0; x < NUM_SPANS; x++) {
10221                   for (y = 0; y < NUM_DCHANS; y++) {
10222                      if (pris[x].dchannels[y] == tmp->channel) {
10223                         matchesdchan = 1;
10224                         break;
10225                      }
10226                   }
10227                }
10228                offset = p.chanpos;
10229                if (!matchesdchan) {
10230                   if (pris[span].nodetype && (pris[span].nodetype != conf->pri.nodetype)) {
10231                      ast_log(LOG_ERROR, "Span %d is already a %s node\n", span + 1, pri_node2str(pris[span].nodetype));
10232                      destroy_dahdi_pvt(&tmp);
10233                      return NULL;
10234                   }
10235                   if (pris[span].switchtype && (pris[span].switchtype != myswitchtype)) {
10236                      ast_log(LOG_ERROR, "Span %d is already a %s switch\n", span + 1, pri_switch2str(pris[span].switchtype));
10237                      destroy_dahdi_pvt(&tmp);
10238                      return NULL;
10239                   }
10240                   if ((pris[span].dialplan) && (pris[span].dialplan != conf->pri.dialplan)) {
10241                      ast_log(LOG_ERROR, "Span %d is already a %s dialing plan\n", span + 1, dialplan2str(pris[span].dialplan));
10242                      destroy_dahdi_pvt(&tmp);
10243                      return NULL;
10244                   }
10245                   if (!ast_strlen_zero(pris[span].idledial) && strcmp(pris[span].idledial, conf->pri.idledial)) {
10246                      ast_log(LOG_ERROR, "Span %d already has idledial '%s'.\n", span + 1, conf->pri.idledial);
10247                      destroy_dahdi_pvt(&tmp);
10248                      return NULL;
10249                   }
10250                   if (!ast_strlen_zero(pris[span].idleext) && strcmp(pris[span].idleext, conf->pri.idleext)) {
10251                      ast_log(LOG_ERROR, "Span %d already has idleext '%s'.\n", span + 1, conf->pri.idleext);
10252                      destroy_dahdi_pvt(&tmp);
10253                      return NULL;
10254                   }
10255                   if (pris[span].minunused && (pris[span].minunused != conf->pri.minunused)) {
10256                      ast_log(LOG_ERROR, "Span %d already has minunused of %d.\n", span + 1, conf->pri.minunused);
10257                      destroy_dahdi_pvt(&tmp);
10258                      return NULL;
10259                   }
10260                   if (pris[span].minidle && (pris[span].minidle != conf->pri.minidle)) {
10261                      ast_log(LOG_ERROR, "Span %d already has minidle of %d.\n", span + 1, conf->pri.minidle);
10262                      destroy_dahdi_pvt(&tmp);
10263                      return NULL;
10264                   }
10265                   if (pris[span].numchans >= MAX_CHANNELS) {
10266                      ast_log(LOG_ERROR, "Unable to add channel %d: Too many channels in trunk group %d!\n", channel,
10267                         pris[span].trunkgroup);
10268                      destroy_dahdi_pvt(&tmp);
10269                      return NULL;
10270                   }
10271
10272                   pris[span].sig = chan_sig;
10273                   pris[span].nodetype = conf->pri.nodetype;
10274                   pris[span].switchtype = myswitchtype;
10275                   pris[span].nsf = conf->pri.nsf;
10276                   pris[span].dialplan = conf->pri.dialplan;
10277                   pris[span].localdialplan = conf->pri.localdialplan;
10278                   pris[span].pvts[pris[span].numchans++] = tmp;
10279                   pris[span].minunused = conf->pri.minunused;
10280                   pris[span].minidle = conf->pri.minidle;
10281                   pris[span].overlapdial = conf->pri.overlapdial;
10282                   pris[span].qsigchannelmapping = conf->pri.qsigchannelmapping;
10283                   pris[span].discardremoteholdretrieval = conf->pri.discardremoteholdretrieval;
10284 #ifdef HAVE_PRI_INBANDDISCONNECT
10285                   pris[span].inbanddisconnect = conf->pri.inbanddisconnect;
10286 #endif
10287                   pris[span].facilityenable = conf->pri.facilityenable;
10288                   ast_copy_string(pris[span].idledial, conf->pri.idledial, sizeof(pris[span].idledial));
10289                   ast_copy_string(pris[span].idleext, conf->pri.idleext, sizeof(pris[span].idleext));
10290                   ast_copy_string(pris[span].internationalprefix, conf->pri.internationalprefix, sizeof(pris[span].internationalprefix));
10291                   ast_copy_string(pris[span].nationalprefix, conf->pri.nationalprefix, sizeof(pris[span].nationalprefix));
10292                   ast_copy_string(pris[span].localprefix, conf->pri.localprefix, sizeof(pris[span].localprefix));
10293                   ast_copy_string(pris[span].privateprefix, conf->pri.privateprefix, sizeof(pris[span].privateprefix));
10294                   ast_copy_string(pris[span].unknownprefix, conf->pri.unknownprefix, sizeof(pris[span].unknownprefix));
10295                   pris[span].resetinterval = conf->pri.resetinterval;
10296
10297                   tmp->pri = &pris[span];
10298                   tmp->prioffset = offset;
10299                   tmp->call = NULL;
10300                } else {
10301                   ast_log(LOG_ERROR, "Channel %d is reserved for D-channel.\n", offset);
10302                   destroy_dahdi_pvt(&tmp);
10303                   return NULL;
10304                }
10305             }
10306          } else {
10307             tmp->prioffset = 0;
10308          }
10309 #endif
10310       } else {
10311          chan_sig = tmp->sig;
10312          if (tmp->subs[SUB_REAL].dfd > -1) {
10313             memset(&p, 0, sizeof(p));
10314             res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &p);
10315          }
10316       }
10317       /* Adjust starttime on loopstart and kewlstart trunks to reasonable values */
10318       switch (chan_sig) {
10319       case SIG_FXSKS:
10320       case SIG_FXSLS:
10321       case SIG_EM:
10322       case SIG_EM_E1:
10323       case SIG_EMWINK:
10324       case SIG_FEATD:
10325       case SIG_FEATDMF:
10326       case SIG_FEATDMF_TA:
10327       case SIG_FEATB:
10328       case SIG_E911:
10329       case SIG_SF:
10330       case SIG_SFWINK:
10331       case SIG_FGC_CAMA:
10332       case SIG_FGC_CAMAMF:
10333       case SIG_SF_FEATD:
10334       case SIG_SF_FEATDMF:
10335       case SIG_SF_FEATB:
10336          p.starttime = 250;
10337          break;
10338       }
10339
10340       if (tmp->radio) {
10341          /* XXX Waiting to hear back from Jim if these should be adjustable XXX */
10342          p.channo = channel;
10343          p.rxwinktime = 1;
10344          p.rxflashtime = 1;
10345          p.starttime = 1;
10346          p.debouncetime = 5;
10347       }
10348       if (!tmp->radio) {
10349          p.channo = channel;
10350          /* Override timing settings based on config file */
10351          if (conf->timing.prewinktime >= 0)
10352             p.prewinktime = conf->timing.prewinktime;
10353          if (conf->timing.preflashtime >= 0)
10354             p.preflashtime = conf->timing.preflashtime;
10355          if (conf->timing.winktime >= 0)
10356             p.winktime = conf->timing.winktime;
10357          if (conf->timing.flashtime >= 0)
10358             p.flashtime = conf->timing.flashtime;
10359          if (conf->timing.starttime >= 0)
10360             p.starttime = conf->timing.starttime;
10361          if (conf->timing.rxwinktime >= 0)
10362             p.rxwinktime = conf->timing.rxwinktime;
10363          if (conf->timing.rxflashtime >= 0)
10364             p.rxflashtime = conf->timing.rxflashtime;
10365          if (conf->timing.debouncetime >= 0)
10366             p.debouncetime = conf->timing.debouncetime;
10367       }
10368
10369       /* dont set parms on a pseudo-channel (or CRV) */
10370       if (tmp->subs[SUB_REAL].dfd >= 0)
10371       {
10372          res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_SET_PARAMS, &p);
10373          if (res < 0) {
10374             ast_log(LOG_ERROR, "Unable to set parameters: %s\n", strerror(errno));
10375             destroy_dahdi_pvt(&tmp);
10376             return NULL;
10377          }
10378       }
10379 #if 1
10380       if (!here && (tmp->subs[SUB_REAL].dfd > -1)) {
10381          memset(&bi, 0, sizeof(bi));
10382          res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GET_BUFINFO, &bi);
10383          if (!res) {
10384             bi.txbufpolicy = conf->chan.buf_policy;
10385             bi.rxbufpolicy = conf->chan.buf_policy;
10386             bi.numbufs = conf->chan.buf_no;
10387             res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_SET_BUFINFO, &bi);
10388             if (res < 0) {
10389                ast_log(LOG_WARNING, "Unable to set buffer policy on channel %d: %s\n", channel, strerror(errno));
10390             }
10391          } else {
10392             ast_log(LOG_WARNING, "Unable to check buffer policy on channel %d: %s\n", channel, strerror(errno));
10393          }
10394          tmp->buf_policy = conf->chan.buf_policy;
10395          tmp->buf_no = conf->chan.buf_no;
10396          tmp->usefaxbuffers = conf->chan.usefaxbuffers;
10397          tmp->faxbuf_policy = conf->chan.faxbuf_policy;
10398          tmp->faxbuf_no = conf->chan.faxbuf_no;
10399          /* This is not as gnarly as it may first appear.  If the ioctl above failed, we'd be setting
10400           * tmp->bufsize to zero which would cause subsequent faxbuffer-related ioctl calls to fail.
10401           * The reason the ioctl call above failed should to be determined before worrying about the
10402           * faxbuffer-related ioctl calls */
10403          tmp->bufsize = bi.bufsize;
10404       }
10405 #endif
10406       tmp->immediate = conf->chan.immediate;
10407       tmp->transfertobusy = conf->chan.transfertobusy;
10408       if (chan_sig & __DAHDI_SIG_FXS) {
10409          tmp->mwimonitor_fsk = conf->chan.mwimonitor_fsk;
10410          tmp->mwimonitor_neon = conf->chan.mwimonitor_neon;
10411          tmp->mwimonitor_rpas = conf->chan.mwimonitor_rpas;
10412       }
10413       tmp->sig = chan_sig;
10414       tmp->outsigmod = conf->chan.outsigmod;
10415       tmp->ringt_base = ringt_base;
10416       tmp->firstradio = 0;
10417       if ((chan_sig == SIG_FXOKS) || (chan_sig == SIG_FXOLS) || (chan_sig == SIG_FXOGS))
10418          tmp->permcallwaiting = conf->chan.callwaiting;
10419       else
10420          tmp->permcallwaiting = 0;
10421       /* Flag to destroy the channel must be cleared on new mkif.  Part of changes for reload to work */
10422       tmp->destroy = 0;
10423       tmp->drings = conf->chan.drings;
10424
10425       /* 10 is a nice default. */
10426       if (tmp->drings.ringnum[0].range == 0)
10427          tmp->drings.ringnum[0].range = 10;
10428       if (tmp->drings.ringnum[1].range == 0)
10429          tmp->drings.ringnum[1].range = 10;
10430       if (tmp->drings.ringnum[2].range == 0)
10431          tmp->drings.ringnum[2].range = 10;
10432
10433       tmp->usedistinctiveringdetection = usedistinctiveringdetection;
10434       tmp->callwaitingcallerid = conf->chan.callwaitingcallerid;
10435       tmp->threewaycalling = conf->chan.threewaycalling;
10436       tmp->adsi = conf->chan.adsi;
10437       tmp->use_smdi = conf->chan.use_smdi;
10438       tmp->permhidecallerid = conf->chan.hidecallerid;
10439       tmp->callreturn = conf->chan.callreturn;
10440       tmp->echocancel = conf->chan.echocancel;
10441       tmp->echotraining = conf->chan.echotraining;
10442       tmp->pulse = conf->chan.pulse;
10443       if (tmp->echocancel.head.tap_length) {
10444          tmp->echocanbridged = conf->chan.echocanbridged;
10445       } else {
10446          if (conf->chan.echocanbridged)
10447             ast_log(LOG_NOTICE, "echocancelwhenbridged requires echocancel to be enabled; ignoring\n");
10448          tmp->echocanbridged = 0;
10449       }
10450       tmp->busydetect = conf->chan.busydetect;
10451       tmp->busycount = conf->chan.busycount;
10452       tmp->busy_tonelength = conf->chan.busy_tonelength;
10453       tmp->busy_quietlength = conf->chan.busy_quietlength;
10454       tmp->callprogress = conf->chan.callprogress;
10455       tmp->waitfordialtone = conf->chan.waitfordialtone;
10456       tmp->cancallforward = conf->chan.cancallforward;
10457       tmp->dtmfrelax = conf->chan.dtmfrelax;
10458       tmp->callwaiting = tmp->permcallwaiting;
10459       tmp->hidecallerid = tmp->permhidecallerid;
10460       tmp->channel = channel;
10461       tmp->stripmsd = conf->chan.stripmsd;
10462       tmp->use_callerid = conf->chan.use_callerid;
10463       tmp->cid_signalling = conf->chan.cid_signalling;
10464       tmp->cid_start = conf->chan.cid_start;
10465       tmp->dahditrcallerid = conf->chan.dahditrcallerid;
10466       tmp->restrictcid = conf->chan.restrictcid;
10467       tmp->use_callingpres = conf->chan.use_callingpres;
10468       tmp->priexclusive = conf->chan.priexclusive;
10469       if (tmp->usedistinctiveringdetection) {
10470          if (!tmp->use_callerid) {
10471             ast_log(LOG_NOTICE, "Distinctive Ring detect requires 'usecallerid' be on\n");
10472             tmp->use_callerid = 1;
10473          }
10474       }
10475
10476       if (tmp->cid_signalling == CID_SIG_SMDI) {
10477          if (!tmp->use_smdi) {
10478             ast_log(LOG_WARNING, "SMDI callerid requires SMDI to be enabled, enabling...\n");
10479             tmp->use_smdi = 1;
10480          }
10481       }
10482       if (tmp->use_smdi) {
10483          tmp->smdi_iface = ast_smdi_interface_find(conf->smdi_port);
10484          if (!(tmp->smdi_iface)) {
10485             ast_log(LOG_ERROR, "Invalid SMDI port specfied, disabling SMDI support\n");
10486             tmp->use_smdi = 0;
10487          }
10488       }
10489
10490       ast_copy_string(tmp->accountcode, conf->chan.accountcode, sizeof(tmp->accountcode));
10491       tmp->amaflags = conf->chan.amaflags;
10492       if (!here) {
10493          tmp->confno = -1;
10494          tmp->propconfno = -1;
10495       }
10496       tmp->canpark = conf->chan.canpark;
10497       tmp->transfer = conf->chan.transfer;
10498       ast_copy_string(tmp->defcontext,conf->chan.context,sizeof(tmp->defcontext));
10499       ast_copy_string(tmp->language, conf->chan.language, sizeof(tmp->language));
10500       ast_copy_string(tmp->mohinterpret, conf->chan.mohinterpret, sizeof(tmp->mohinterpret));
10501       ast_copy_string(tmp->mohsuggest, conf->chan.mohsuggest, sizeof(tmp->mohsuggest));
10502       ast_copy_string(tmp->context, conf->chan.context, sizeof(tmp->context));
10503       ast_copy_string(tmp->parkinglot, conf->chan.parkinglot, sizeof(tmp->parkinglot));
10504       tmp->cid_ton = 0;
10505       if ((tmp->sig != SIG_PRI) || (tmp->sig != SIG_SS7) || (tmp->sig != SIG_BRI) || (tmp->sig != SIG_BRI_PTMP) || (tmp->sig != SIG_MFCR2)) {
10506          ast_copy_string(tmp->cid_num, conf->chan.cid_num, sizeof(tmp->cid_num));
10507          ast_copy_string(tmp->cid_name, conf->chan.cid_name, sizeof(tmp->cid_name));
10508       } else {
10509          tmp->cid_num[0] = '\0';
10510          tmp->cid_name[0] = '\0';
10511       }
10512       ast_copy_string(tmp->mailbox, conf->chan.mailbox, sizeof(tmp->mailbox));
10513       if (channel != CHAN_PSEUDO && !ast_strlen_zero(tmp->mailbox)) {
10514          char *mailbox, *context;
10515          mailbox = context = ast_strdupa(tmp->mailbox);
10516          strsep(&context, "@");
10517          if (ast_strlen_zero(context))
10518             context = "default";
10519          tmp->mwi_event_sub = ast_event_subscribe(AST_EVENT_MWI, mwi_event_cb, NULL,
10520             AST_EVENT_IE_MAILBOX, AST_EVENT_IE_PLTYPE_STR, mailbox,
10521             AST_EVENT_IE_CONTEXT, AST_EVENT_IE_PLTYPE_STR, context,
10522             AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_EXISTS,
10523             AST_EVENT_IE_END);
10524       }
10525       tmp->msgstate = -1;
10526 #ifdef HAVE_DAHDI_LINEREVERSE_VMWI
10527       tmp->mwisend_setting = conf->chan.mwisend_setting;
10528       tmp->mwisend_fsk  = conf->chan.mwisend_fsk;
10529       tmp->mwisend_rpas = conf->chan.mwisend_rpas;
10530 #endif
10531       if (chan_sig & __DAHDI_SIG_FXO) {
10532          memset(&p, 0, sizeof(p));
10533          res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_GET_PARAMS, &p);
10534          if (!res) {
10535             tmp->fxsoffhookstate = p.rxisoffhook;
10536          }
10537 #ifdef HAVE_DAHDI_LINEREVERSE_VMWI
10538          res = ioctl(tmp->subs[SUB_REAL].dfd, DAHDI_VMWI_CONFIG, &tmp->mwisend_setting);
10539 #endif
10540       }
10541       tmp->onhooktime = time(NULL);
10542       tmp->group = conf->chan.group;
10543       tmp->callgroup = conf->chan.callgroup;
10544       tmp->pickupgroup= conf->chan.pickupgroup;
10545       if (conf->chan.vars) {
10546          struct ast_variable *v, *tmpvar;
10547                    for (v = conf->chan.vars ; v ; v = v->next) {
10548                          if ((tmpvar = ast_variable_new(v->name, v->value, v->file))) {
10549                                   tmpvar->next = tmp->vars;
10550                                    tmp->vars = tmpvar;
10551                            }
10552                   }
10553       }
10554       tmp->cid_rxgain = conf->chan.cid_rxgain;
10555       tmp->rxgain = conf->chan.rxgain;
10556       tmp->txgain = conf->chan.txgain;
10557       tmp->tonezone = conf->chan.tonezone;
10558       if (tmp->subs[SUB_REAL].dfd > -1) {
10559          set_actual_gain(tmp->subs[SUB_REAL].dfd, 0, tmp->rxgain, tmp->txgain, tmp->law);
10560          if (tmp->dsp)
10561             ast_dsp_set_digitmode(tmp->dsp, DSP_DIGITMODE_DTMF | tmp->dtmfrelax);
10562          update_conf(tmp);
10563          if (!here) {
10564             if ((chan_sig != SIG_BRI) && (chan_sig != SIG_BRI_PTMP) && (chan_sig != SIG_PRI)
10565                 && (chan_sig != SIG_SS7) && (chan_sig != SIG_MFCR2))
10566                /* Hang it up to be sure it's good */
10567                dahdi_set_hook(tmp->subs[SUB_REAL].dfd, DAHDI_ONHOOK);
10568          }
10569          ioctl(tmp->subs[SUB_REAL].dfd,DAHDI_SETTONEZONE,&tmp->tonezone);
10570 #ifdef HAVE_PRI
10571          /* the dchannel is down so put the channel in alarm */
10572          if (tmp->pri && !pri_is_up(tmp->pri))
10573             tmp->inalarm = 1;
10574 #endif
10575          if ((res = get_alarms(tmp)) != DAHDI_ALARM_NONE) {
10576             tmp->inalarm = 1;
10577             handle_alarms(tmp, res);
10578          }
10579       }
10580
10581       tmp->polarityonanswerdelay = conf->chan.polarityonanswerdelay;
10582       tmp->answeronpolarityswitch = conf->chan.answeronpolarityswitch;
10583       tmp->hanguponpolarityswitch = conf->chan.hanguponpolarityswitch;
10584       tmp->sendcalleridafter = conf->chan.sendcalleridafter;
10585       if (!here) {
10586          tmp->locallyblocked = tmp->remotelyblocked = 0;
10587          if ((chan_sig == SIG_PRI) || (chan_sig == SIG_BRI) || (chan_sig == SIG_BRI_PTMP) || (chan_sig == SIG_SS7))
10588             tmp->inservice = 0;
10589          else /* We default to in service on protocols that don't have a reset */
10590             tmp->inservice = 1;
10591       }
10592    }
10593    if (tmp && !here) {
10594       /* nothing on the iflist */
10595       if (!*wlist) {
10596          *wlist = tmp;
10597          tmp->prev = NULL;
10598          tmp->next = NULL;
10599          *wend = tmp;
10600       } else {
10601          /* at least one member on the iflist */
10602          struct dahdi_pvt *working = *wlist;
10603
10604          /* check if we maybe have to put it on the begining */
10605          if (working->channel > tmp->channel) {
10606             tmp->next = *wlist;
10607             tmp->prev = NULL;
10608             (*wlist)->prev = tmp;
10609             *wlist = tmp;
10610          } else {
10611          /* go through all the members and put the member in the right place */
10612             while (working) {
10613                /* in the middle */
10614                if (working->next) {
10615                   if (working->channel < tmp->channel && working->next->channel > tmp->channel) {
10616                      tmp->next = working->next;
10617                      tmp->prev = working;
10618                      working->next->prev = tmp;
10619                      working->next = tmp;
10620                      break;
10621                   }
10622                } else {
10623                /* the last */
10624                   if (working->channel < tmp->channel) {
10625                      working->next = tmp;
10626                      tmp->next = NULL;
10627                      tmp->prev = working;
10628                      *wend = tmp;
10629                      break;
10630                   }
10631                }
10632                working = working->next;
10633             }
10634          }
10635       }
10636    }
10637    return tmp;
10638 }
static void mwi_event_cb (const struct ast_event * event, void * userdata) [static]
Definition at line 367 of file chan_dahdi.c.
Referenced by mkintf().
{
   /* This module does not handle MWI in an event-based manner.  However, it
    * subscribes to MWI for each mailbox that is configured so that the core
    * knows that we care about it.  Then, chan_dahdi will get the MWI from the
    * event cache instead of checking the mailbox directly. */
}
static int mwi_send_init (struct dahdi_pvt * pvt) [static]
Definition at line 9063 of file chan_dahdi.c.
References ast_calloc, ast_free, AST_LAW, ast_log(), CID_MWI_TYPE_MDMF_FULL, dahdi_pvt::cid_name, dahdi_pvt::cid_num, dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, dahdi_subchannel::dfd, has_voicemail(), LOG_WARNING, MAX_CALLERID_SIZE, MWI_SEND_SA, MWI_SEND_SPILL, mwisend_info::mwisend_current, dahdi_pvt::mwisend_data, dahdi_pvt::mwisendactive, SUB_REAL, dahdi_pvt::subs, and vmwi_generate().
Referenced by do_monitor().
{
   int x, res;
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
   /* Determine how this spill is to be sent */
   if (pvt->mwisend_rpas) {
      pvt->mwisend_data.mwisend_current = MWI_SEND_SA;
      pvt->mwisendactive = 1;
   } else if (pvt->mwisend_fsk) {
      pvt->mwisend_data.mwisend_current = MWI_SEND_SPILL;
      pvt->mwisendactive = 1;
   } else {
      pvt->mwisendactive = 0;
      return 0;
   }
#else
   if (mwisend_rpas) {
      pvt->mwisend_data.mwisend_current = MWI_SEND_SA;
   } else {
      pvt->mwisend_data.mwisend_current = MWI_SEND_SPILL;
   }
   pvt->mwisendactive = 1;
#endif
   if (pvt->cidspill) {
      ast_log(LOG_WARNING, "cidspill already exists when trying to send FSK MWI\n");
      ast_free(pvt->cidspill);
      pvt->cidspill = NULL;
      pvt->cidpos = 0;
      pvt->cidlen = 0;
   }
   pvt->cidspill = ast_calloc(1, MAX_CALLERID_SIZE);
   if (!pvt->cidspill) {
      pvt->mwisendactive = 0;
      return -1;
   }
   x = DAHDI_FLUSH_BOTH;
   res = ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_FLUSH, &x);
   x = 3000;
   ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_ONHOOKTRANSFER, &x);
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
   if (pvt->mwisend_fsk) {
#endif
      pvt->cidlen = vmwi_generate(pvt->cidspill, has_voicemail(pvt), CID_MWI_TYPE_MDMF_FULL,
                        AST_LAW(pvt), pvt->cid_name, pvt->cid_num, 0);
      pvt->cidpos = 0;
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
   }
#endif
   return 0;
}
static int mwi_send_process_buffer (struct dahdi_pvt * pvt, int num_read) [static]
Definition at line 9116 of file chan_dahdi.c.
References ast_free, ast_log(), dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, dahdi_set_hook(), dahdi_subchannel::dfd, errno, LOG_WARNING, MWI_SEND_CLEANUP, MWI_SEND_DONE, MWI_SEND_PAUSE, MWI_SEND_SA, MWI_SEND_SA_WAIT, MWI_SEND_SPILL, mwisend_info::mwisend_current, dahdi_pvt::mwisend_data, dahdi_pvt::mwisendactive, mwisend_info::pause, quit, SUB_REAL, and dahdi_pvt::subs.
Referenced by do_monitor().
{
   struct timeval    now;
   int         res;
   /* sanity check to catch if this had been interrupted previously
   *  i.e. state says there is more to do but there is no spill allocated
   */
   if (MWI_SEND_DONE != pvt->mwisend_data.mwisend_current && !pvt->cidspill) {
      pvt->mwisend_data.mwisend_current = MWI_SEND_DONE;
   } else if (MWI_SEND_DONE != pvt->mwisend_data.mwisend_current) {
      /* Normal processing -- Perform mwi send action */
      switch ( pvt->mwisend_data.mwisend_current) {
      case MWI_SEND_SA:
         /* Send the Ring Pulse Signal Alert */
         res = ioctl(pvt->subs[SUB_REAL].dfd, DAHDI_SETCADENCE, &AS_RP_cadence);
         if (res) {
            ast_log(LOG_WARNING, "Unable to set RP-AS ring cadence: %s\n", strerror(errno));
            goto quit;
         }
         res = dahdi_set_hook(pvt->subs[SUB_REAL].dfd, DAHDI_RING);
         pvt->mwisend_data.mwisend_current = MWI_SEND_SA_WAIT;
         break;
      case MWI_SEND_SA_WAIT:  /* do nothing until I get RINGEROFF event */
         break;
      case MWI_SEND_PAUSE:  /* Wait between alert and spill - min of 500 mS*/
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
         if (pvt->mwisend_fsk) {
#endif
            gettimeofday(&now, NULL);
            if ((int)(now.tv_sec - pvt->mwisend_data.pause.tv_sec) * 1000000 + (int)now.tv_usec - (int)pvt->mwisend_data.pause.tv_usec > 500000) {
               pvt->mwisend_data.mwisend_current = MWI_SEND_SPILL;
            }
#ifdef HAVE_DAHDI_LINEREVERSE_VMWI
         } else { /* support for mwisendtype=nofsk */
            pvt->mwisend_data.mwisend_current = MWI_SEND_CLEANUP;
         }
#endif
         break;
      case MWI_SEND_SPILL:
         /* We read some number of bytes.  Write an equal amount of data */
         if(0 < num_read) {
            if (num_read > pvt->cidlen - pvt->cidpos)
               num_read = pvt->cidlen - pvt->cidpos;
            res = write(pvt->subs[SUB_REAL].dfd, pvt->cidspill + pvt->cidpos, num_read);
            if (res > 0) {
               pvt->cidpos += res;
               if (pvt->cidpos >= pvt->cidlen) {
                  pvt->mwisend_data.mwisend_current = MWI_SEND_CLEANUP;
               }
            } else {
               ast_log(LOG_WARNING, "MWI FSK Send Write failed: %s\n", strerror(errno));
               goto quit;
            }
         }
         break;
      case MWI_SEND_CLEANUP:
         /* For now, do nothing */
         pvt->mwisend_data.mwisend_current = MWI_SEND_DONE;
         break;
      default:
         /* Should not get here, punt*/
         goto quit;
      }
   }
   if (MWI_SEND_DONE == pvt->mwisend_data.mwisend_current) {
      if (pvt->cidspill) {
         ast_free(pvt->cidspill);
         pvt->cidspill = NULL;
         pvt->cidpos = 0;
         pvt->cidlen = 0;
      }
      pvt->mwisendactive = 0;
   }
   return 0;
quit:
   if (pvt->cidspill) {
      ast_free(pvt->cidspill);
      pvt->cidspill = NULL;
      pvt->cidpos = 0;
      pvt->cidlen = 0;
   }
   pvt->mwisendactive = 0;
   return -1;
}
static int mwi_send_process_event (struct dahdi_pvt * pvt, int event) [static]
Definition at line 9203 of file chan_dahdi.c.
References ast_free, ast_log(), dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, dahdi_set_hook(), dahdi_subchannel::dfd, errno, LOG_WARNING, MWI_SEND_DONE, MWI_SEND_PAUSE, MWI_SEND_SA_WAIT, mwisend_info::mwisend_current, dahdi_pvt::mwisend_data, dahdi_pvt::mwisendactive, mwisend_info::pause, SUB_REAL, and dahdi_pvt::subs.
Referenced by do_monitor().
{
   int handled = 0;
   if (MWI_SEND_DONE != pvt->mwisend_data.mwisend_current) {
      switch (event) {
      case DAHDI_EVENT_RINGEROFF:
         if(pvt->mwisend_data.mwisend_current == MWI_SEND_SA_WAIT) {
            handled = 1;
            if (dahdi_set_hook(pvt->subs[SUB_REAL].dfd, DAHDI_RINGOFF) ) {
               ast_log(LOG_WARNING, "Unable to finsh RP-AS: %s mwi send aborted\n", strerror(errno));
               if(pvt->cidspill) {
                  ast_free(pvt->cidspill);
                  pvt->cidspill = NULL;
               }
               pvt->mwisend_data.mwisend_current = MWI_SEND_DONE;
               pvt->mwisendactive = 0;
            } else {
               pvt->mwisend_data.mwisend_current = MWI_SEND_PAUSE;
               gettimeofday(&pvt->mwisend_data.pause, NULL);
            }
         }
         break;
      /* Going off hook, I need to punt this spill */
      case DAHDI_EVENT_RINGOFFHOOK:
         if (pvt->cidspill) {
            ast_free(pvt->cidspill);
            pvt->cidspill = NULL;
            pvt->cidpos = 0;
            pvt->cidlen = 0;
         }
         pvt->mwisend_data.mwisend_current = MWI_SEND_DONE;
         pvt->mwisendactive = 0;
         break;
      case DAHDI_EVENT_RINGERON:
      case DAHDI_EVENT_HOOKCOMPLETE:
         break;
      default:
         break;
      }
   }
   return handled;
}
static void* mwi_thread (void * data) [static]
Definition at line 8925 of file chan_dahdi.c.
References ast_free, ast_hangup(), AST_LAW, ast_log(), ast_pthread_create_detached, AST_STATE_RING, mwi_thread_data::buf, bump_gains(), calc_energy(), callerid_feed(), callerid_free(), callerid_get(), callerid_new(), dahdi_pvt::channel, CID_MSGWAITING, CID_NOMSGWAITING, dahdi_pvt::cid_signalling, dahdi_get_event(), dahdi_new(), dahdi_subchannel::dfd, errno, event2str(), EVENT_FLAG_SYSTEM, callerid_state::flags, get_alarms(), handle_alarms(), dahdi_pvt::inalarm, mwi_thread_data::len, LOG_NOTICE, LOG_WARNING, dahdi_pvt::mailbox, manager_event, dahdi_pvt::mwimonitoractive, name, notify_message(), mwi_thread_data::pvt, quit, restore_gains(), dahdi_pvt::ringt, dahdi_pvt::ringt_base, ss_thread(), SUB_REAL, and dahdi_pvt::subs.
Referenced by do_monitor().
{
   struct mwi_thread_data *mtd = data;
   struct callerid_state *cs;
   pthread_t threadid;
   int samples = 0;
   char *name, *number;
   int flags;
   int i, res;
   unsigned int spill_done = 0;
   int spill_result = -1;
   if (!(cs = callerid_new(mtd->pvt->cid_signalling))) {
      mtd->pvt->mwimonitoractive = 0;
      return NULL;
   }
   callerid_feed(cs, mtd->buf, mtd->len, AST_LAW(mtd->pvt));
   bump_gains(mtd->pvt);
   for (;;) {
      i = DAHDI_IOMUX_READ | DAHDI_IOMUX_SIGEVENT;
      if ((res = ioctl(mtd->pvt->subs[SUB_REAL].dfd, DAHDI_IOMUX, &i))) {
         ast_log(LOG_WARNING, "I/O MUX failed: %s\n", strerror(errno));
         goto quit;
      }
      if (i & DAHDI_IOMUX_SIGEVENT) {
         struct ast_channel *chan;
         /* If we get an event, screen out events that we do not act on.
          * Otherwise, cancel and go to the simple switch to let it deal with it.
          */
         res = dahdi_get_event(mtd->pvt->subs[SUB_REAL].dfd);
         switch (res) {
         case DAHDI_EVENT_NEONMWI_ACTIVE:
         case DAHDI_EVENT_NEONMWI_INACTIVE:
         case DAHDI_EVENT_NONE:
         case DAHDI_EVENT_BITSCHANGED:
            break;
         case DAHDI_EVENT_NOALARM:
            mtd->pvt->inalarm = 0;
            ast_log(LOG_NOTICE, "Alarm cleared on channel %d\n", mtd->pvt->channel);
            manager_event(EVENT_FLAG_SYSTEM, "AlarmClear",
               "Channel: %d\r\n", mtd->pvt->channel);
            break;
         case DAHDI_EVENT_ALARM:
            mtd->pvt->inalarm = 1;
            res = get_alarms(mtd->pvt);
            handle_alarms(mtd->pvt, res);
            break; /* What to do on channel alarm ???? -- fall thru intentionally?? */
         default:
            ast_log(LOG_NOTICE, "Got event %d (%s)...  Passing along to ss_thread\n", res, event2str(res));
            callerid_free(cs);
            restore_gains(mtd->pvt);
            mtd->pvt->ringt = mtd->pvt->ringt_base;
            if ((chan = dahdi_new(mtd->pvt, AST_STATE_RING, 0, SUB_REAL, 0, 0))) {
               if (ast_pthread_create_detached(&threadid, NULL, ss_thread, chan)) {
                  ast_log(LOG_WARNING, "Unable to start simple switch thread on channel %d\n", mtd->pvt->channel);
                  res = tone_zone_play_tone(mtd->pvt->subs[SUB_REAL].dfd, DAHDI_TONE_CONGESTION);
                  if (res < 0)
                     ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", mtd->pvt->channel);
                  ast_hangup(chan);
                  goto quit;
               }
               goto quit_no_clean;
            } else {
               ast_log(LOG_WARNING, "Could not create channel to handle call\n");
            }
         }
      } else if (i & DAHDI_IOMUX_READ) {
         if ((res = read(mtd->pvt->subs[SUB_REAL].dfd, mtd->buf, sizeof(mtd->buf))) < 0) {
            if (errno != ELAST) {
               ast_log(LOG_WARNING, "read returned error: %s\n", strerror(errno));
               goto quit;
            }
            break;
         }
         samples += res;
         if (!spill_done) {
            if ((spill_result = callerid_feed(cs, mtd->buf, res, AST_LAW(mtd->pvt))) < 0) {
               ast_log(LOG_WARNING, "CallerID feed failed: %s\n", strerror(errno));
               break;
            } else if (spill_result) {
               spill_done = 1;
            }
         } else {
            /* keep reading data until the energy level drops below the threshold
               so we don't get another 'trigger' on the remaining carrier signal
            */
            if (calc_energy(mtd->buf, res, AST_LAW(mtd->pvt)) <= mwilevel)
               break;
         }
         if (samples > (8000 * 4)) /*Termination case - time to give up*/
            break;
      }
   }
   if (spill_result == 1) {
      callerid_get(cs, &name, &number, &flags);
      if (flags & CID_MSGWAITING) {
         ast_log(LOG_NOTICE, "mwi: Have Messages on channel %d\n", mtd->pvt->channel);
         notify_message(mtd->pvt->mailbox, 1);
      } else if (flags & CID_NOMSGWAITING) {
         ast_log(LOG_NOTICE, "mwi: No Messages on channel %d\n", mtd->pvt->channel);
         notify_message(mtd->pvt->mailbox, 0);
      } else {
         ast_log(LOG_NOTICE, "mwi: Status unknown on channel %d\n", mtd->pvt->channel);
      }
   }
quit:
   callerid_free(cs);
   restore_gains(mtd->pvt);
quit_no_clean:
   mtd->pvt->mwimonitoractive = 0;
   ast_free(mtd);
   return NULL;
}
static int my_dahdi_write (struct dahdi_pvt * p, unsigned char * buf, int len, int idx, int linear) [static]
Definition at line 7068 of file chan_dahdi.c.
References ast_debug, dahdi_pvt::channel, dahdi_subchannel::dfd, errno, READ_SIZE, and dahdi_pvt::subs.
Referenced by dahdi_write().
{
   int sent=0;
   int size;
   int res;
   int fd;
   fd = p->subs[idx].dfd;
   while (len) {
      size = len;
      if (size > (linear ? READ_SIZE * 2 : READ_SIZE))
         size = (linear ? READ_SIZE * 2 : READ_SIZE);
      res = write(fd, buf, size);
      if (res != size) {
         ast_debug(1, "Write returned %d (%s) on channel %d\n", res, strerror(errno), p->channel);
         return sent;
      }
      len -= size;
      buf += size;
   }
   return sent;
}
static int my_getsigstr (struct ast_channel * chan, char * str, const char * term, int ms) [static]
Definition at line 7616 of file chan_dahdi.c.
References ast_waitfordigit().
Referenced by ss_thread().
{
   char c;
   *str = 0; /* start with empty output buffer */
   for (;;)
   {
      /* Wait for the first digit (up to specified ms). */
      c = ast_waitfordigit(chan, ms);
      /* if timeout, hangup or error, return as such */
      if (c < 1)
         return c;
      *str++ = c;
      *str = 0;
      if (strchr(term, c))
         return 1;
   }
}
static void notify_message (char * mailbox_full, int thereornot) [static]
Send MWI state change.
mailbox_full This is the mailbox associated with the FXO line that the MWI state has changed on.
thereornot This argument should simply be set to 1 or 0, to indicate whether there are messages waiting or not.
Returns:
nothing
This function does two things:
1) It generates an internal Asterisk event notifying any other module that cares about MWI that the state of a mailbox has changed.
2) It runs the script specified by the mwimonitornotify option to allow some custom handling of the state change.
Definition at line 2940 of file chan_dahdi.c.
References AST_EVENT_IE_CONTEXT, AST_EVENT_IE_END, AST_EVENT_IE_MAILBOX, AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_OLDMSGS, AST_EVENT_IE_PLTYPE_STR, AST_EVENT_IE_PLTYPE_UINT, AST_EVENT_MWI, ast_event_new(), ast_event_queue_and_cache(), ast_safe_system(), ast_strdupa, ast_strlen_zero(), context, mailbox, s, and strsep().
Referenced by handle_init_event(), mwi_thread(), and ss_thread().
{
   char s[sizeof(mwimonitornotify) + 80];
   struct ast_event *event;
   char *mailbox, *context;
   /* Strip off @default */
   context = mailbox = ast_strdupa(mailbox_full);
   strsep(&context, "@");
   if (ast_strlen_zero(context))
      context = "default";
   if (!(event = ast_event_new(AST_EVENT_MWI,
         AST_EVENT_IE_MAILBOX, AST_EVENT_IE_PLTYPE_STR, mailbox,
         AST_EVENT_IE_CONTEXT, AST_EVENT_IE_PLTYPE_STR, context,
         AST_EVENT_IE_NEWMSGS, AST_EVENT_IE_PLTYPE_UINT, thereornot,
         AST_EVENT_IE_OLDMSGS, AST_EVENT_IE_PLTYPE_UINT, thereornot,
         AST_EVENT_IE_END))) {
      return;
   }
   ast_event_queue_and_cache(event);
   if (!ast_strlen_zero(mailbox) && !ast_strlen_zero(mwimonitornotify)) {
      snprintf(s, sizeof(s), "%s %s %d", mwimonitornotify, mailbox, thereornot);
      ast_safe_system(s);
   }
}
static int process_dahdi (struct dahdi_chan_conf * confp, const char * cat, struct ast_variable * v, int reload, int options) [static]
Definition at line 16096 of file chan_dahdi.c.
References dahdi_pvt::accountcode, dahdi_pvt::adsi, dahdi_pvt::amaflags, dahdi_pvt::answeronpolarityswitch, ast_callerid_split(), ast_cdr_amaflags2int(), ast_copy_string(), ast_get_group(), ast_jb_read_conf(), ast_log(), AST_MAX_EXTENSION, ast_strdupa, ast_strlen_zero(), ast_true(), ast_variable_new(), ast_verb, dahdi_pvt::buf_no, dahdi_pvt::buf_policy, build_channels(), dahdi_pvt::busy_quietlength, dahdi_pvt::busy_tonelength, dahdi_pvt::busycount, dahdi_pvt::busydetect, dahdi_pvt::callgroup, dahdi_pvt::callprogress, CALLPROGRESS_FAX, CALLPROGRESS_FAX_INCOMING, CALLPROGRESS_FAX_OUTGOING, CALLPROGRESS_PROGRESS, dahdi_pvt::callreturn, dahdi_pvt::callwaiting, dahdi_pvt::callwaitingcallerid, dahdi_pvt::cancallforward, dahdi_pvt::canpark, dahdi_chan_conf::chan, CHAN_PSEUDO, dahdi_pvt::cid_name, dahdi_pvt::cid_num, dahdi_pvt::cid_rxgain, CID_SIG_BELL, CID_SIG_DTMF, CID_SIG_SMDI, CID_SIG_V23, CID_SIG_V23_JP, dahdi_pvt::cid_signalling, dahdi_pvt::cid_start, CID_START_POLARITY, CID_START_POLARITY_IN, CID_START_RING, dahdi_pvt::context, ringContextData::contextData, dahdi_chan_conf_default(), DAHDI_CHAN_MAPPING_LOGICAL, DAHDI_CHAN_MAPPING_PHYSICAL, DAHDI_OVERLAPDIAL_BOTH, DAHDI_OVERLAPDIAL_INCOMING, DAHDI_OVERLAPDIAL_NONE, DAHDI_OVERLAPDIAL_OUTGOING, dahdi_pvt::dahditrcallerid, dahdi_pvt::drings, DSP_DIGITMODE_RELAXDTMF, dahdi_pvt::dtmfrelax, dahdi_pvt::echocanbridged, dahdi_pvt::echotraining, errno, dahdi_pvt::faxbuf_no, dahdi_pvt::faxbuf_policy, global_jbconf, dahdi_pvt::group, dahdi_pvt::hanguponpolarityswitch, dahdi_pvt::hidecallerid, dahdi_pvt::hidecalleridname, dahdi_pvt::immediate, dahdi_chan_conf::is_sig_auto, dahdi_pvt::language, ast_variable::lineno, LOG_DEBUG, LOG_ERROR, LOG_NOTICE, LOG_WARNING, dahdi_pvt::mailbox, MAX_CHANLIST_LEN, mkintf(), dahdi_pvt::mohinterpret, dahdi_pvt::mohsuggest, dahdi_pvt::mwimonitor_fsk, dahdi_pvt::mwimonitor_neon, dahdi_pvt::mwimonitor_rpas, ast_variable::name, ast_variable::next, NUM_CADENCE_MAX, dahdi_pvt::outsigmod, dahdi_pvt::parkinglot, dahdi_pvt::pickupgroup, dahdi_pvt::polarityonanswerdelay, dahdi_pvt::priexclusive, dahdi_pvt::priindication_oob, PROC_DAHDI_OPT_NOCHAN, PROC_DAHDI_OPT_NOWARN, process_echocancel(), dahdi_pvt::pulse, dahdi_pvt::radio, distRingData::range, READ_SIZE, dahdi_pvt::restrictcid, distRingData::ring, dahdi_distRings::ringContext, dahdi_distRings::ringnum, dahdi_pvt::rxgain, dahdi_pvt::sendcalleridafter, dahdi_pvt::sig, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_GR303FXOKS, SIG_GR303FXSKS, SIG_MFCR2, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SFWINK, SIG_SS7, dahdi_chan_conf::smdi_port, strcasestr(), dahdi_pvt::stripmsd, strsep(), dahdi_pvt::threewaycalling, timer, dahdi_chan_conf::timing, dahdi_pvt::tonezone, dahdi_pvt::transfer, dahdi_pvt::transfertobusy, dahdi_pvt::txgain, dahdi_pvt::use_callerid, dahdi_pvt::use_callingpres, dahdi_pvt::use_smdi, dahdi_pvt::usefaxbuffers, ast_variable::value, dahdi_pvt::vars, and dahdi_pvt::waitfordialtone.
Referenced by setup_dahdi().
16097 {
16098    struct dahdi_pvt *tmp;
16099    int y;
16100    int found_pseudo = 0;
16101    char dahdichan[MAX_CHANLIST_LEN] = {};
16102
16103    for (; v; v = v->next) {
16104       if (!ast_jb_read_conf(&global_jbconf, v->name, v->value))
16105          continue;
16106
16107       /* must have parkinglot in confp before build_channels is called */
16108       if (!strcasecmp(v->name, "parkinglot")) {
16109          ast_copy_string(confp->chan.parkinglot, v->value, sizeof(confp->chan.parkinglot));
16110       }
16111
16112       /* Create the interface list */
16113       if (!strcasecmp(v->name, "channel")
16114 #ifdef HAVE_PRI
16115          || !strcasecmp(v->name, "crv")
16116 #endif
16117) {
16118          int iscrv;
16119          if (options & PROC_DAHDI_OPT_NOCHAN) {
16120             ast_log(LOG_WARNING, "Channel '%s' ignored.\n", v->value);
16121             continue;
16122          }
16123          iscrv = !strcasecmp(v->name, "crv");
16124          if (build_channels(confp, iscrv, v->value, reload, v->lineno, &found_pseudo))
16125                return -1;
16126          ast_log(LOG_DEBUG, "Channel '%s' configured.\n", v->value);
16127       } else if (!strcasecmp(v->name, "buffers")) {
16128          int res;
16129          char policy[21] = "";
16130
16131          res = sscanf(v->value, "%30d,%20s", &confp->chan.buf_no, policy);
16132          if (res != 2) {
16133             ast_log(LOG_WARNING, "Parsing buffers option data failed, using defaults.\n");
16134             confp->chan.buf_no = numbufs;
16135             continue;
16136          }
16137          if (confp->chan.buf_no < 0)
16138             confp->chan.buf_no = numbufs;
16139          if (!strcasecmp(policy, "full")) {
16140             confp->chan.buf_policy = DAHDI_POLICY_WHEN_FULL;
16141          } else if (!strcasecmp(policy, "immediate")) {
16142             confp->chan.buf_policy = DAHDI_POLICY_IMMEDIATE;
16143 #ifdef HAVE_DAHDI_HALF_FULL
16144          } else if (!strcasecmp(policy, "half_full")) {
16145             confp->chan.buf_policy = DAHDI_POLICY_HALF_FULL;
16146 #endif
16147          } else {
16148             ast_log(LOG_WARNING, "Invalid policy name given (%s).\n", policy);
16149          }
16150       } else if (!strcasecmp(v->name, "faxbuffers")) {
16151          int res;
16152          char policy[21] = "";
16153
16154          res = sscanf(v->value, "%30d,%20s", &confp->chan.faxbuf_no, policy);
16155          if (res != 2) {
16156             ast_log(LOG_WARNING, "Parsing faxbuffers option data failed, using defaults.\n");
16157             confp->chan.faxbuf_no = numbufs;
16158             continue;
16159          }
16160          confp->chan.usefaxbuffers = 1;
16161          if (confp->chan.faxbuf_no < 0)
16162             confp->chan.faxbuf_no = numbufs;
16163          if (!strcasecmp(policy, "full")) {
16164             confp->chan.faxbuf_policy = DAHDI_POLICY_WHEN_FULL;
16165          } else if (!strcasecmp(policy, "immediate")) {
16166             confp->chan.faxbuf_policy = DAHDI_POLICY_IMMEDIATE;
16167          } else {
16168             ast_log(LOG_WARNING, "Invalid policy name given (%s).\n", policy);
16169             confp->chan.usefaxbuffers = 0;
16170          }
16171       } else if (!strcasecmp(v->name, "dahdichan")) {
16172          ast_copy_string(dahdichan, v->value, sizeof(dahdichan));
16173       } else if (!strcasecmp(v->name, "usedistinctiveringdetection")) {
16174          usedistinctiveringdetection = ast_true(v->value);
16175       } else if (!strcasecmp(v->name, "distinctiveringaftercid")) {
16176          distinctiveringaftercid = ast_true(v->value);
16177       } else if (!strcasecmp(v->name, "dring1context")) {
16178          ast_copy_string(confp->chan.drings.ringContext[0].contextData,v->value,sizeof(confp->chan.drings.ringContext[0].contextData));
16179       } else if (!strcasecmp(v->name, "dring2context")) {
16180          ast_copy_string(confp->chan.drings.ringContext[1].contextData,v->value,sizeof(confp->chan.drings.ringContext[1].contextData));
16181       } else if (!strcasecmp(v->name, "dring3context")) {
16182          ast_copy_string(confp->chan.drings.ringContext[2].contextData,v->value,sizeof(confp->chan.drings.ringContext[2].contextData));
16183       } else if (!strcasecmp(v->name, "dring1range")) {
16184          confp->chan.drings.ringnum[0].range = atoi(v->value);
16185       } else if (!strcasecmp(v->name, "dring2range")) {
16186          confp->chan.drings.ringnum[1].range = atoi(v->value);
16187       } else if (!strcasecmp(v->name, "dring3range")) {
16188          confp->chan.drings.ringnum[2].range = atoi(v->value);
16189       } else if (!strcasecmp(v->name, "dring1")) {
16190          sscanf(v->value, "%30d,%30d,%30d", &confp->chan.drings.ringnum[0].ring[0], &confp->chan.drings.ringnum[0].ring[1], &confp->chan.drings.ringnum[0].ring[2]);
16191       } else if (!strcasecmp(v->name, "dring2")) {
16192          sscanf(v->value, "%30d,%30d,%30d", &confp->chan.drings.ringnum[1].ring[0], &confp->chan.drings.ringnum[1].ring[1], &confp->chan.drings.ringnum[1].ring[2]);
16193       } else if (!strcasecmp(v->name, "dring3")) {
16194          sscanf(v->value, "%30d,%30d,%30d", &confp->chan.drings.ringnum[2].ring[0], &confp->chan.drings.ringnum[2].ring[1], &confp->chan.drings.ringnum[2].ring[2]);
16195       } else if (!strcasecmp(v->name, "usecallerid")) {
16196          confp->chan.use_callerid = ast_true(v->value);
16197       } else if (!strcasecmp(v->name, "cidsignalling")) {
16198          if (!strcasecmp(v->value, "bell"))
16199             confp->chan.cid_signalling = CID_SIG_BELL;
16200          else if (!strcasecmp(v->value, "v23"))
16201             confp->chan.cid_signalling = CID_SIG_V23;
16202          else if (!strcasecmp(v->value, "dtmf"))
16203             confp->chan.cid_signalling = CID_SIG_DTMF;
16204          else if (!strcasecmp(v->value, "smdi"))
16205             confp->chan.cid_signalling = CID_SIG_SMDI;
16206          else if (!strcasecmp(v->value, "v23_jp"))
16207             confp->chan.cid_signalling = CID_SIG_V23_JP;
16208          else if (ast_true(v->value))
16209             confp->chan.cid_signalling = CID_SIG_BELL;
16210       } else if (!strcasecmp(v->name, "cidstart")) {
16211          if (!strcasecmp(v->value, "ring"))
16212             confp->chan.cid_start = CID_START_RING;
16213          else if (!strcasecmp(v->value, "polarity_in"))
16214             confp->chan.cid_start = CID_START_POLARITY_IN;
16215          else if (!strcasecmp(v->value, "polarity"))
16216             confp->chan.cid_start = CID_START_POLARITY;
16217          else if (ast_true(v->value))
16218             confp->chan.cid_start = CID_START_RING;
16219       } else if (!strcasecmp(v->name, "threewaycalling")) {
16220          confp->chan.threewaycalling = ast_true(v->value);
16221       } else if (!strcasecmp(v->name, "cancallforward")) {
16222          confp->chan.cancallforward = ast_true(v->value);
16223       } else if (!strcasecmp(v->name, "relaxdtmf")) {
16224          if (ast_true(v->value))
16225             confp->chan.dtmfrelax = DSP_DIGITMODE_RELAXDTMF;
16226          else
16227             confp->chan.dtmfrelax = 0;
16228       } else if (!strcasecmp(v->name, "mailbox")) {
16229          ast_copy_string(confp->chan.mailbox, v->value, sizeof(confp->chan.mailbox));
16230       } else if (!strcasecmp(v->name, "hasvoicemail")) {
16231          if (ast_true(v->value) && ast_strlen_zero(confp->chan.mailbox)) {
16232             ast_copy_string(confp->chan.mailbox, cat, sizeof(confp->chan.mailbox));
16233          }
16234       } else if (!strcasecmp(v->name, "adsi")) {
16235          confp->chan.adsi = ast_true(v->value);
16236       } else if (!strcasecmp(v->name, "usesmdi")) {
16237          confp->chan.use_smdi = ast_true(v->value);
16238       } else if (!strcasecmp(v->name, "smdiport")) {
16239          ast_copy_string(confp->smdi_port, v->value, sizeof(confp->smdi_port));
16240       } else if (!strcasecmp(v->name, "transfer")) {
16241          confp->chan.transfer = ast_true(v->value);
16242       } else if (!strcasecmp(v->name, "canpark")) {
16243          confp->chan.canpark = ast_true(v->value);
16244       } else if (!strcasecmp(v->name, "echocancelwhenbridged")) {
16245          confp->chan.echocanbridged = ast_true(v->value);
16246       } else if (!strcasecmp(v->name, "busydetect")) {
16247          confp->chan.busydetect = ast_true(v->value);
16248       } else if (!strcasecmp(v->name, "busycount")) {
16249          confp->chan.busycount = atoi(v->value);
16250       } else if (!strcasecmp(v->name, "busypattern")) {
16251          if (sscanf(v->value, "%30d,%30d", &confp->chan.busy_tonelength, &confp->chan.busy_quietlength) != 2) {
16252             ast_log(LOG_ERROR, "busypattern= expects busypattern=tonelength,quietlength at line %d.\n", v->lineno);
16253          }
16254       } else if (!strcasecmp(v->name, "callprogress")) {
16255          confp->chan.callprogress &= ~CALLPROGRESS_PROGRESS;
16256          if (ast_true(v->value))
16257             confp->chan.callprogress |= CALLPROGRESS_PROGRESS;
16258       } else if (!strcasecmp(v->name, "waitfordialtone")) {
16259          confp->chan.waitfordialtone = atoi(v->value);
16260       } else if (!strcasecmp(v->name, "faxdetect")) {
16261          confp->chan.callprogress &= ~CALLPROGRESS_FAX;
16262          if (!strcasecmp(v->value, "incoming")) {
16263             confp->chan.callprogress |= CALLPROGRESS_FAX_INCOMING;
16264          } else if (!strcasecmp(v->value, "outgoing")) {
16265             confp->chan.callprogress |= CALLPROGRESS_FAX_OUTGOING;
16266          } else if (!strcasecmp(v->value, "both") || ast_true(v->value))
16267             confp->chan.callprogress |= CALLPROGRESS_FAX_INCOMING | CALLPROGRESS_FAX_OUTGOING;
16268       } else if (!strcasecmp(v->name, "echocancel")) {
16269          process_echocancel(confp, v->value, v->lineno);
16270       } else if (!strcasecmp(v->name, "echotraining")) {
16271          if (sscanf(v->value, "%30d", &y) == 1) {
16272             if ((y < 10) || (y > 4000)) {
16273                ast_log(LOG_WARNING, "Echo training time must be within the range of 10 to 4000 ms at line %d.\n", v->lineno);
16274             } else {
16275                confp->chan.echotraining = y;
16276             }
16277          } else if (ast_true(v->value)) {
16278             confp->chan.echotraining = 400;
16279          } else
16280             confp->chan.echotraining = 0;
16281       } else if (!strcasecmp(v->name, "hidecallerid")) {
16282          confp->chan.hidecallerid = ast_true(v->value);
16283       } else if (!strcasecmp(v->name, "hidecalleridname")) {
16284          confp->chan.hidecalleridname = ast_true(v->value);
16285       } else if (!strcasecmp(v->name, "pulsedial")) {
16286          confp->chan.pulse = ast_true(v->value);
16287       } else if (!strcasecmp(v->name, "callreturn")) {
16288          confp->chan.callreturn = ast_true(v->value);
16289       } else if (!strcasecmp(v->name, "callwaiting")) {
16290          confp->chan.callwaiting = ast_true(v->value);
16291       } else if (!strcasecmp(v->name, "callwaitingcallerid")) {
16292          confp->chan.callwaitingcallerid = ast_true(v->value);
16293       } else if (!strcasecmp(v->name, "context")) {
16294          ast_copy_string(confp->chan.context, v->value, sizeof(confp->chan.context));
16295       } else if (!strcasecmp(v->name, "language")) {
16296          ast_copy_string(confp->chan.language, v->value, sizeof(confp->chan.language));
16297       } else if (!strcasecmp(v->name, "progzone")) {
16298          ast_copy_string(progzone, v->value, sizeof(progzone));
16299       } else if (!strcasecmp(v->name, "mohinterpret")
16300          ||!strcasecmp(v->name, "musiconhold") || !strcasecmp(v->name, "musicclass")) {
16301          ast_copy_string(confp->chan.mohinterpret, v->value, sizeof(confp->chan.mohinterpret));
16302       } else if (!strcasecmp(v->name, "mohsuggest")) {
16303          ast_copy_string(confp->chan.mohsuggest, v->value, sizeof(confp->chan.mohsuggest));
16304       } else if (!strcasecmp(v->name, "parkinglot")) {
16305          ast_copy_string(parkinglot, v->value, sizeof(parkinglot));
16306       } else if (!strcasecmp(v->name, "stripmsd")) {
16307          ast_log(LOG_NOTICE, "Configuration option \"%s\" has been deprecated. Please use dialplan instead\n", v->name);
16308          confp->chan.stripmsd = atoi(v->value);
16309       } else if (!strcasecmp(v->name, "jitterbuffers")) {
16310          numbufs = atoi(v->value);
16311       } else if (!strcasecmp(v->name, "group")) {
16312          confp->chan.group = ast_get_group(v->value);
16313       } else if (!strcasecmp(v->name, "callgroup")) {
16314          if (!strcasecmp(v->value, "none"))
16315             confp->chan.callgroup = 0;
16316          else
16317             confp->chan.callgroup = ast_get_group(v->value);
16318       } else if (!strcasecmp(v->name, "pickupgroup")) {
16319          if (!strcasecmp(v->value, "none"))
16320             confp->chan.pickupgroup = 0;
16321          else
16322             confp->chan.pickupgroup = ast_get_group(v->value);
16323       } else if (!strcasecmp(v->name, "setvar")) {
16324          char *varname = ast_strdupa(v->value), *varval = NULL;
16325          struct ast_variable *tmpvar;
16326          if (varname && (varval = strchr(varname, '='))) {
16327             *varval++ = '\0';
16328             if ((tmpvar = ast_variable_new(varname, varval, ""))) {
16329                tmpvar->next = confp->chan.vars;
16330                confp->chan.vars = tmpvar;
16331             }
16332          }
16333       } else if (!strcasecmp(v->name, "immediate")) {
16334          confp->chan.immediate = ast_true(v->value);
16335       } else if (!strcasecmp(v->name, "transfertobusy")) {
16336          confp->chan.transfertobusy = ast_true(v->value);
16337       } else if (!strcasecmp(v->name, "mwimonitor")) {
16338          confp->chan.mwimonitor_neon = 0;
16339          confp->chan.mwimonitor_fsk = 0;
16340          confp->chan.mwimonitor_rpas = 0;
16341          if (strcasestr(v->value, "fsk")) {
16342             confp->chan.mwimonitor_fsk = 1;
16343          }
16344          if (strcasestr(v->value, "rpas")) {
16345             confp->chan.mwimonitor_rpas = 1;
16346          }
16347          if (strcasestr(v->value, "neon")) {
16348             confp->chan.mwimonitor_neon = 1;
16349          }
16350          /* If set to true or yes, assume that simple fsk is desired */
16351          if (ast_true(v->value)) {
16352             confp->chan.mwimonitor_fsk = 1;
16353          }
16354       } else if (!strcasecmp(v->name, "cid_rxgain")) {
16355          if (sscanf(v->value, "%30f", &confp->chan.cid_rxgain) != 1) {
16356             ast_log(LOG_WARNING, "Invalid cid_rxgain: %s at line %d.\n", v->value, v->lineno);
16357          }
16358       } else if (!strcasecmp(v->name, "rxgain")) {
16359          if (sscanf(v->value, "%30f", &confp->chan.rxgain) != 1) {
16360             ast_log(LOG_WARNING, "Invalid rxgain: %s at line %d.\n", v->value, v->lineno);
16361          }
16362       } else if (!strcasecmp(v->name, "txgain")) {
16363          if (sscanf(v->value, "%30f", &confp->chan.txgain) != 1) {
16364             ast_log(LOG_WARNING, "Invalid txgain: %s at line %d.\n", v->value, v->lineno);
16365          }
16366       } else if (!strcasecmp(v->name, "tonezone")) {
16367          if (sscanf(v->value, "%30d", &confp->chan.tonezone) != 1) {
16368             ast_log(LOG_WARNING, "Invalid tonezone: %s at line %d.\n", v->value, v->lineno);
16369          }
16370       } else if (!strcasecmp(v->name, "callerid")) {
16371          if (!strcasecmp(v->value, "asreceived")) {
16372             confp->chan.cid_num[0] = '\0';
16373             confp->chan.cid_name[0] = '\0';
16374          } else {
16375             ast_callerid_split(v->value, confp->chan.cid_name, sizeof(confp->chan.cid_name), confp->chan.cid_num, sizeof(confp->chan.cid_num));
16376          }
16377       } else if (!strcasecmp(v->name, "fullname")) {
16378          ast_copy_string(confp->chan.cid_name, v->value, sizeof(confp->chan.cid_name));
16379       } else if (!strcasecmp(v->name, "cid_number")) {
16380          ast_copy_string(confp->chan.cid_num, v->value, sizeof(confp->chan.cid_num));
16381       } else if (!strcasecmp(v->name, "useincomingcalleridondahditransfer")) {
16382          confp->chan.dahditrcallerid = ast_true(v->value);
16383       } else if (!strcasecmp(v->name, "restrictcid")) {
16384          confp->chan.restrictcid = ast_true(v->value);
16385       } else if (!strcasecmp(v->name, "usecallingpres")) {
16386          confp->chan.use_callingpres = ast_true(v->value);
16387       } else if (!strcasecmp(v->name, "accountcode")) {
16388          ast_copy_string(confp->chan.accountcode, v->value, sizeof(confp->chan.accountcode));
16389       } else if (!strcasecmp(v->name, "amaflags")) {
16390          y = ast_cdr_amaflags2int(v->value);
16391          if (y < 0)
16392             ast_log(LOG_WARNING, "Invalid AMA flags: %s at line %d.\n", v->value, v->lineno);
16393          else
16394             confp->chan.amaflags = y;
16395       } else if (!strcasecmp(v->name, "polarityonanswerdelay")) {
16396          confp->chan.polarityonanswerdelay = atoi(v->value);
16397       } else if (!strcasecmp(v->name, "answeronpolarityswitch")) {
16398          confp->chan.answeronpolarityswitch = ast_true(v->value);
16399       } else if (!strcasecmp(v->name, "hanguponpolarityswitch")) {
16400          confp->chan.hanguponpolarityswitch = ast_true(v->value);
16401       } else if (!strcasecmp(v->name, "sendcalleridafter")) {
16402          confp->chan.sendcalleridafter = atoi(v->value);
16403       } else if (!strcasecmp(v->name, "mwimonitornotify")) {
16404          ast_copy_string(mwimonitornotify, v->value, sizeof(mwimonitornotify));
16405       } else if (!strcasecmp(v->name, "mwisendtype")) {
16406 #ifndef HAVE_DAHDI_LINEREVERSE_VMWI  /* backward compatibility for older dahdi VMWI implementation */
16407          if (!strcasecmp(v->value, "rpas")) { /* Ring Pulse Alert Signal */
16408             mwisend_rpas = 1;
16409          } else {
16410             mwisend_rpas = 0;
16411          }
16412 #else
16413          /* Default is fsk, to turn it off you must specify nofsk */
16414          memset(&confp->chan.mwisend_setting, 0, sizeof(confp->chan.mwisend_setting));
16415          if (strcasestr(v->value, "nofsk")) {      /* NoFSK */
16416             confp->chan.mwisend_fsk = 0;
16417          } else {             /* Default FSK */
16418             confp->chan.mwisend_fsk = 1;
16419          }
16420          if (strcasestr(v->value, "rpas")) {       /* Ring Pulse Alert Signal, normally followed by FSK */
16421             confp->chan.mwisend_rpas = 1;
16422          } else {
16423             confp->chan.mwisend_rpas = 0;
16424          }
16425          if (strcasestr(v->value, "lrev")) {       /* Line Reversal */
16426             confp->chan.mwisend_setting.vmwi_type |= DAHDI_VMWI_LREV;
16427          }
16428          if (strcasestr(v->value, "hvdc")) {       /* HV 90VDC */
16429             confp->chan.mwisend_setting.vmwi_type |= DAHDI_VMWI_HVDC;
16430          }
16431          if ((strcasestr(v->value, "neon")) || (strcasestr(v->value, "hvac"))){   /* 90V DC pulses */
16432             confp->chan.mwisend_setting.vmwi_type |= DAHDI_VMWI_HVAC;
16433          }
16434 #endif
16435       } else if (reload != 1) {
16436           if (!strcasecmp(v->name, "signalling") || !strcasecmp(v->name, "signaling")) {
16437             int orig_radio = confp->chan.radio;
16438             int orig_outsigmod = confp->chan.outsigmod;
16439             int orig_auto = confp->is_sig_auto;
16440
16441             confp->chan.radio = 0;
16442             confp->chan.outsigmod = -1;
16443             confp->is_sig_auto = 0;
16444             if (!strcasecmp(v->value, "em")) {
16445                confp->chan.sig = SIG_EM;
16446             } else if (!strcasecmp(v->value, "em_e1")) {
16447                confp->chan.sig = SIG_EM_E1;
16448             } else if (!strcasecmp(v->value, "em_w")) {
16449                confp->chan.sig = SIG_EMWINK;
16450             } else if (!strcasecmp(v->value, "fxs_ls")) {
16451                confp->chan.sig = SIG_FXSLS;
16452             } else if (!strcasecmp(v->value, "fxs_gs")) {
16453                confp->chan.sig = SIG_FXSGS;
16454             } else if (!strcasecmp(v->value, "fxs_ks")) {
16455                confp->chan.sig = SIG_FXSKS;
16456             } else if (!strcasecmp(v->value, "fxo_ls")) {
16457                confp->chan.sig = SIG_FXOLS;
16458             } else if (!strcasecmp(v->value, "fxo_gs")) {
16459                confp->chan.sig = SIG_FXOGS;
16460             } else if (!strcasecmp(v->value, "fxo_ks")) {
16461                confp->chan.sig = SIG_FXOKS;
16462             } else if (!strcasecmp(v->value, "fxs_rx")) {
16463                confp->chan.sig = SIG_FXSKS;
16464                confp->chan.radio = 1;
16465             } else if (!strcasecmp(v->value, "fxo_rx")) {
16466                confp->chan.sig = SIG_FXOLS;
16467                confp->chan.radio = 1;
16468             } else if (!strcasecmp(v->value, "fxs_tx")) {
16469                confp->chan.sig = SIG_FXSLS;
16470                confp->chan.radio = 1;
16471             } else if (!strcasecmp(v->value, "fxo_tx")) {
16472                confp->chan.sig = SIG_FXOGS;
16473                confp->chan.radio = 1;
16474             } else if (!strcasecmp(v->value, "em_rx")) {
16475                confp->chan.sig = SIG_EM;
16476                confp->chan.radio = 1;
16477             } else if (!strcasecmp(v->value, "em_tx")) {
16478                confp->chan.sig = SIG_EM;
16479                confp->chan.radio = 1;
16480             } else if (!strcasecmp(v->value, "em_rxtx")) {
16481                confp->chan.sig = SIG_EM;
16482                confp->chan.radio = 2;
16483             } else if (!strcasecmp(v->value, "em_txrx")) {
16484                confp->chan.sig = SIG_EM;
16485                confp->chan.radio = 2;
16486             } else if (!strcasecmp(v->value, "sf")) {
16487                confp->chan.sig = SIG_SF;
16488             } else if (!strcasecmp(v->value, "sf_w")) {
16489                confp->chan.sig = SIG_SFWINK;
16490             } else if (!strcasecmp(v->value, "sf_featd")) {
16491                confp->chan.sig = SIG_FEATD;
16492             } else if (!strcasecmp(v->value, "sf_featdmf")) {
16493                confp->chan.sig = SIG_FEATDMF;
16494             } else if (!strcasecmp(v->value, "sf_featb")) {
16495                confp->chan.sig = SIG_SF_FEATB;
16496             } else if (!strcasecmp(v->value, "sf")) {
16497                confp->chan.sig = SIG_SF;
16498             } else if (!strcasecmp(v->value, "sf_rx")) {
16499                confp->chan.sig = SIG_SF;
16500                confp->chan.radio = 1;
16501             } else if (!strcasecmp(v->value, "sf_tx")) {
16502                confp->chan.sig = SIG_SF;
16503                confp->chan.radio = 1;
16504             } else if (!strcasecmp(v->value, "sf_rxtx")) {
16505                confp->chan.sig = SIG_SF;
16506                confp->chan.radio = 2;
16507             } else if (!strcasecmp(v->value, "sf_txrx")) {
16508                confp->chan.sig = SIG_SF;
16509                confp->chan.radio = 2;
16510             } else if (!strcasecmp(v->value, "featd")) {
16511                confp->chan.sig = SIG_FEATD;
16512             } else if (!strcasecmp(v->value, "featdmf")) {
16513                confp->chan.sig = SIG_FEATDMF;
16514             } else if (!strcasecmp(v->value, "featdmf_ta")) {
16515                confp->chan.sig = SIG_FEATDMF_TA;
16516             } else if (!strcasecmp(v->value, "e911")) {
16517                confp->chan.sig = SIG_E911;
16518             } else if (!strcasecmp(v->value, "fgccama")) {
16519                confp->chan.sig = SIG_FGC_CAMA;
16520             } else if (!strcasecmp(v->value, "fgccamamf")) {
16521                confp->chan.sig = SIG_FGC_CAMAMF;
16522             } else if (!strcasecmp(v->value, "featb")) {
16523                confp->chan.sig = SIG_FEATB;
16524 #ifdef HAVE_PRI
16525             } else if (!strcasecmp(v->value, "pri_net")) {
16526                confp->chan.sig = SIG_PRI;
16527                confp->pri.nodetype = PRI_NETWORK;
16528             } else if (!strcasecmp(v->value, "pri_cpe")) {
16529                confp->chan.sig = SIG_PRI;
16530                confp->pri.nodetype = PRI_CPE;
16531             } else if (!strcasecmp(v->value, "bri_cpe")) {
16532                confp->chan.sig = SIG_BRI;
16533                confp->pri.nodetype = PRI_CPE;
16534             } else if (!strcasecmp(v->value, "bri_net")) {
16535                confp->chan.sig = SIG_BRI;
16536                confp->pri.nodetype = PRI_NETWORK;
16537             } else if (!strcasecmp(v->value, "bri_cpe_ptmp")) {
16538                confp->chan.sig = SIG_BRI_PTMP;
16539                confp->pri.nodetype = PRI_CPE;
16540             } else if (!strcasecmp(v->value, "bri_net_ptmp")) {
16541                ast_log(LOG_WARNING, "How cool would it be if someone implemented this mode!  For now, sucks for you. (line %d)\n", v->lineno);
16542             } else if (!strcasecmp(v->value, "gr303fxoks_net")) {
16543                confp->chan.sig = SIG_GR303FXOKS;
16544                confp->pri.nodetype = PRI_NETWORK;
16545             } else if (!strcasecmp(v->value, "gr303fxsks_cpe")) {
16546                confp->chan.sig = SIG_GR303FXSKS;
16547                confp->pri.nodetype = PRI_CPE;
16548 #endif
16549 #ifdef HAVE_SS7
16550             } else if (!strcasecmp(v->value, "ss7")) {
16551                confp->chan.sig = SIG_SS7;
16552 #endif
16553 #ifdef HAVE_OPENR2
16554             } else if (!strcasecmp(v->value, "mfcr2")) {
16555                confp->chan.sig = SIG_MFCR2;
16556 #endif
16557             } else if (!strcasecmp(v->value, "auto")) {
16558                confp->is_sig_auto = 1;
16559             } else {
16560                confp->chan.outsigmod = orig_outsigmod;
16561                confp->chan.radio = orig_radio;
16562                confp->is_sig_auto = orig_auto;
16563                ast_log(LOG_ERROR, "Unknown signalling method '%s' at line %d.\n", v->value, v->lineno);
16564             }
16565           } else if (!strcasecmp(v->name, "outsignalling") || !strcasecmp(v->name, "outsignaling")) {
16566             if (!strcasecmp(v->value, "em")) {
16567                confp->chan.outsigmod = SIG_EM;
16568             } else if (!strcasecmp(v->value, "em_e1")) {
16569                confp->chan.outsigmod = SIG_EM_E1;
16570             } else if (!strcasecmp(v->value, "em_w")) {
16571                confp->chan.outsigmod = SIG_EMWINK;
16572             } else if (!strcasecmp(v->value, "sf")) {
16573                confp->chan.outsigmod = SIG_SF;
16574             } else if (!strcasecmp(v->value, "sf_w")) {
16575                confp->chan.outsigmod = SIG_SFWINK;
16576             } else if (!strcasecmp(v->value, "sf_featd")) {
16577                confp->chan.outsigmod = SIG_FEATD;
16578             } else if (!strcasecmp(v->value, "sf_featdmf")) {
16579                confp->chan.outsigmod = SIG_FEATDMF;
16580             } else if (!strcasecmp(v->value, "sf_featb")) {
16581                confp->chan.outsigmod = SIG_SF_FEATB;
16582             } else if (!strcasecmp(v->value, "sf")) {
16583                confp->chan.outsigmod = SIG_SF;
16584             } else if (!strcasecmp(v->value, "featd")) {
16585                confp->chan.outsigmod = SIG_FEATD;
16586             } else if (!strcasecmp(v->value, "featdmf")) {
16587                confp->chan.outsigmod = SIG_FEATDMF;
16588             } else if (!strcasecmp(v->value, "featdmf_ta")) {
16589                confp->chan.outsigmod = SIG_FEATDMF_TA;
16590             } else if (!strcasecmp(v->value, "e911")) {
16591                confp->chan.outsigmod = SIG_E911;
16592             } else if (!strcasecmp(v->value, "fgccama")) {
16593                confp->chan.outsigmod = SIG_FGC_CAMA;
16594             } else if (!strcasecmp(v->value, "fgccamamf")) {
16595                confp->chan.outsigmod = SIG_FGC_CAMAMF;
16596             } else if (!strcasecmp(v->value, "featb")) {
16597                confp->chan.outsigmod = SIG_FEATB;
16598             } else {
16599                ast_log(LOG_ERROR, "Unknown signalling method '%s' at line %d.\n", v->value, v->lineno);
16600             }
16601 #ifdef HAVE_PRI
16602          } else if (!strcasecmp(v->name, "pridialplan")) {
16603             if (!strcasecmp(v->value, "national")) {
16604                confp->pri.dialplan = PRI_NATIONAL_ISDN + 1;
16605             } else if (!strcasecmp(v->value, "unknown")) {
16606                confp->pri.dialplan = PRI_UNKNOWN + 1;
16607             } else if (!strcasecmp(v->value, "private")) {
16608                confp->pri.dialplan = PRI_PRIVATE + 1;
16609             } else if (!strcasecmp(v->value, "international")) {
16610                confp->pri.dialplan = PRI_INTERNATIONAL_ISDN + 1;
16611             } else if (!strcasecmp(v->value, "local")) {
16612                confp->pri.dialplan = PRI_LOCAL_ISDN + 1;
16613             } else if (!strcasecmp(v->value, "dynamic")) {
16614                confp->pri.dialplan = -1;
16615             } else if (!strcasecmp(v->value, "redundant")) {
16616                confp->pri.dialplan = -2;
16617             } else {
16618                ast_log(LOG_WARNING, "Unknown PRI dialplan '%s' at line %d.\n", v->value, v->lineno);
16619             }
16620          } else if (!strcasecmp(v->name, "prilocaldialplan")) {
16621             if (!strcasecmp(v->value, "national")) {
16622                confp->pri.localdialplan = PRI_NATIONAL_ISDN + 1;
16623             } else if (!strcasecmp(v->value, "unknown")) {
16624                confp->pri.localdialplan = PRI_UNKNOWN + 1;
16625             } else if (!strcasecmp(v->value, "private")) {
16626                confp->pri.localdialplan = PRI_PRIVATE + 1;
16627             } else if (!strcasecmp(v->value, "international")) {
16628                confp->pri.localdialplan = PRI_INTERNATIONAL_ISDN + 1;
16629             } else if (!strcasecmp(v->value, "local")) {
16630                confp->pri.localdialplan = PRI_LOCAL_ISDN + 1;
16631             } else if (!strcasecmp(v->value, "dynamic")) {
16632                confp->pri.localdialplan = -1;
16633             } else if (!strcasecmp(v->value, "redundant")) {
16634                confp->pri.localdialplan = -2;
16635             } else {
16636                ast_log(LOG_WARNING, "Unknown PRI localdialplan '%s' at line %d.\n", v->value, v->lineno);
16637             }
16638          } else if (!strcasecmp(v->name, "switchtype")) {
16639             if (!strcasecmp(v->value, "national"))
16640                confp->pri.switchtype = PRI_SWITCH_NI2;
16641             else if (!strcasecmp(v->value, "ni1"))
16642                confp->pri.switchtype = PRI_SWITCH_NI1;
16643             else if (!strcasecmp(v->value, "dms100"))
16644                confp->pri.switchtype = PRI_SWITCH_DMS100;
16645             else if (!strcasecmp(v->value, "4ess"))
16646                confp->pri.switchtype = PRI_SWITCH_ATT4ESS;
16647             else if (!strcasecmp(v->value, "5ess"))
16648                confp->pri.switchtype = PRI_SWITCH_LUCENT5E;
16649             else if (!strcasecmp(v->value, "euroisdn"))
16650                confp->pri.switchtype = PRI_SWITCH_EUROISDN_E1;
16651             else if (!strcasecmp(v->value, "qsig"))
16652                confp->pri.switchtype = PRI_SWITCH_QSIG;
16653             else {
16654                ast_log(LOG_ERROR, "Unknown switchtype '%s' at line %d.\n", v->value, v->lineno);
16655                return -1;
16656             }
16657          } else if (!strcasecmp(v->name, "nsf")) {
16658             if (!strcasecmp(v->value, "sdn"))
16659                confp->pri.nsf = PRI_NSF_SDN;
16660             else if (!strcasecmp(v->value, "megacom"))
16661                confp->pri.nsf = PRI_NSF_MEGACOM;
16662             else if (!strcasecmp(v->value, "tollfreemegacom"))
16663                confp->pri.nsf = PRI_NSF_TOLL_FREE_MEGACOM;
16664             else if (!strcasecmp(v->value, "accunet"))
16665                confp->pri.nsf = PRI_NSF_ACCUNET;
16666             else if (!strcasecmp(v->value, "none"))
16667                confp->pri.nsf = PRI_NSF_NONE;
16668             else {
16669                ast_log(LOG_WARNING, "Unknown network-specific facility '%s' at line %d.\n", v->value, v->lineno);
16670                confp->pri.nsf = PRI_NSF_NONE;
16671             }
16672          } else if (!strcasecmp(v->name, "priindication")) {
16673             if (!strcasecmp(v->value, "outofband"))
16674                confp->chan.priindication_oob = 1;
16675             else if (!strcasecmp(v->value, "inband"))
16676                confp->chan.priindication_oob = 0;
16677             else
16678                ast_log(LOG_WARNING, "'%s' is not a valid pri indication value, should be 'inband' or 'outofband' at line %d.\n",
16679                   v->value, v->lineno);
16680          } else if (!strcasecmp(v->name, "priexclusive")) {
16681             confp->chan.priexclusive = ast_true(v->value);
16682          } else if (!strcasecmp(v->name, "internationalprefix")) {
16683             ast_copy_string(confp->pri.internationalprefix, v->value, sizeof(confp->pri.internationalprefix));
16684          } else if (!strcasecmp(v->name, "nationalprefix")) {
16685             ast_copy_string(confp->pri.nationalprefix, v->value, sizeof(confp->pri.nationalprefix));
16686          } else if (!strcasecmp(v->name, "localprefix")) {
16687             ast_copy_string(confp->pri.localprefix, v->value, sizeof(confp->pri.localprefix));
16688          } else if (!strcasecmp(v->name, "privateprefix")) {
16689             ast_copy_string(confp->pri.privateprefix, v->value, sizeof(confp->pri.privateprefix));
16690          } else if (!strcasecmp(v->name, "unknownprefix")) {
16691             ast_copy_string(confp->pri.unknownprefix, v->value, sizeof(confp->pri.unknownprefix));
16692          } else if (!strcasecmp(v->name, "resetinterval")) {
16693             if (!strcasecmp(v->value, "never"))
16694                confp->pri.resetinterval = -1;
16695             else if (atoi(v->value) >= 60)
16696                confp->pri.resetinterval = atoi(v->value);
16697             else
16698                ast_log(LOG_WARNING, "'%s' is not a valid reset interval, should be >= 60 seconds or 'never' at line %d.\n",
16699                   v->value, v->lineno);
16700          } else if (!strcasecmp(v->name, "minunused")) {
16701             confp->pri.minunused = atoi(v->value);
16702          } else if (!strcasecmp(v->name, "minidle")) {
16703             confp->pri.minidle = atoi(v->value);
16704          } else if (!strcasecmp(v->name, "idleext")) {
16705             ast_copy_string(confp->pri.idleext, v->value, sizeof(confp->pri.idleext));
16706          } else if (!strcasecmp(v->name, "idledial")) {
16707             ast_copy_string(confp->pri.idledial, v->value, sizeof(confp->pri.idledial));
16708          } else if (!strcasecmp(v->name, "overlapdial")) {
16709             if (ast_true(v->value)) {
16710                confp->pri.overlapdial = DAHDI_OVERLAPDIAL_BOTH;
16711             } else if (!strcasecmp(v->value, "incoming")) {
16712                confp->pri.overlapdial = DAHDI_OVERLAPDIAL_INCOMING;
16713             } else if (!strcasecmp(v->value, "outgoing")) {
16714                confp->pri.overlapdial = DAHDI_OVERLAPDIAL_OUTGOING;
16715             } else if (!strcasecmp(v->value, "both") || ast_true(v->value)) {
16716                confp->pri.overlapdial = DAHDI_OVERLAPDIAL_BOTH;
16717             } else {
16718                confp->pri.overlapdial = DAHDI_OVERLAPDIAL_NONE;
16719             }
16720 #ifdef HAVE_PRI_PROG_W_CAUSE
16721          } else if (!strcasecmp(v->name, "qsigchannelmapping")) {
16722             if (!strcasecmp(v->value, "logical")) {
16723                confp->pri.qsigchannelmapping = DAHDI_CHAN_MAPPING_LOGICAL;
16724             } else if (!strcasecmp(v->value, "physical")) {
16725                confp->pri.qsigchannelmapping = DAHDI_CHAN_MAPPING_PHYSICAL;
16726             } else {
16727                confp->pri.qsigchannelmapping = DAHDI_CHAN_MAPPING_PHYSICAL;
16728             }
16729 #endif
16730          } else if (!strcasecmp(v->name, "discardremoteholdretrieval")) {
16731             confp->pri.discardremoteholdretrieval = ast_true(v->value);
16732 #ifdef HAVE_PRI_INBANDDISCONNECT
16733          } else if (!strcasecmp(v->name, "inbanddisconnect")) {
16734             confp->pri.inbanddisconnect = ast_true(v->value);
16735 #endif
16736          } else if (!strcasecmp(v->name, "pritimer")) {
16737 #ifdef PRI_GETSET_TIMERS
16738             char tmp[20];
16739             char *timerc;
16740             char *c;
16741             int timer;
16742             int timeridx;
16743
16744             ast_copy_string(tmp, v->value, sizeof(tmp));
16745             c = tmp;
16746             timerc = strsep(&c, ",");
16747             if (!ast_strlen_zero(timerc) && !ast_strlen_zero(c)) {
16748                timeridx = pri_timer2idx(timerc);
16749                timer = atoi(c);
16750                if (timeridx < 0 || PRI_MAX_TIMERS <= timeridx) {
16751                   ast_log(LOG_WARNING,
16752                      "'%s' is not a valid ISDN timer at line %d.\n", timerc,
16753                      v->lineno);
16754                } else if (!timer) {
16755                   ast_log(LOG_WARNING,
16756                      "'%s' is not a valid value for ISDN timer '%s' at line %d.\n",
16757                      c, timerc, v->lineno);
16758                } else {
16759                   pritimers[timeridx] = timer;
16760                }
16761             } else {
16762                ast_log(LOG_WARNING,
16763                   "'%s' is not a valid ISDN timer configuration string at line %d.\n",
16764                   v->value, v->lineno);
16765             }
16766
16767          } else if (!strcasecmp(v->name, "facilityenable")) {
16768             confp->pri.facilityenable = ast_true(v->value);
16769 #endif /* PRI_GETSET_TIMERS */
16770 #endif /* HAVE_PRI */
16771 #ifdef HAVE_SS7
16772          } else if (!strcasecmp(v->name, "ss7type")) {
16773             if (!strcasecmp(v->value, "itu")) {
16774                cur_ss7type = SS7_ITU;
16775             } else if (!strcasecmp(v->value, "ansi")) {
16776                cur_ss7type = SS7_ANSI;
16777             } else
16778                ast_log(LOG_WARNING, "'%s' is an unknown ss7 switch type at line %d.!\n", v->value, v->lineno);
16779          } else if (!strcasecmp(v->name, "linkset")) {
16780             cur_linkset = atoi(v->value);
16781          } else if (!strcasecmp(v->name, "pointcode")) {
16782             cur_pointcode = parse_pointcode(v->value);
16783          } else if (!strcasecmp(v->name, "adjpointcode")) {
16784             cur_adjpointcode = parse_pointcode(v->value);
16785          } else if (!strcasecmp(v->name, "defaultdpc")) {
16786             cur_defaultdpc = parse_pointcode(v->value);
16787          } else if (!strcasecmp(v->name, "cicbeginswith")) {
16788             cur_cicbeginswith = atoi(v->value);
16789          } else if (!strcasecmp(v->name, "networkindicator")) {
16790             if (!strcasecmp(v->value, "national"))
16791                cur_networkindicator = SS7_NI_NAT;
16792             else if (!strcasecmp(v->value, "national_spare"))
16793                cur_networkindicator = SS7_NI_NAT_SPARE;
16794             else if (!strcasecmp(v->value, "international"))
16795                cur_networkindicator = SS7_NI_INT;
16796             else if (!strcasecmp(v->value, "international_spare"))
16797                cur_networkindicator = SS7_NI_INT_SPARE;
16798             else
16799                cur_networkindicator = -1;
16800          } else if (!strcasecmp(v->name, "ss7_internationalprefix")) {
16801             ast_copy_string(confp->ss7.internationalprefix, v->value, sizeof(confp->ss7.internationalprefix));
16802          } else if (!strcasecmp(v->name, "ss7_nationalprefix")) {
16803             ast_copy_string(confp->ss7.nationalprefix, v->value, sizeof(confp->ss7.nationalprefix));
16804          } else if (!strcasecmp(v->name, "ss7_subscriberprefix")) {
16805             ast_copy_string(confp->ss7.subscriberprefix, v->value, sizeof(confp->ss7.subscriberprefix));
16806          } else if (!strcasecmp(v->name, "ss7_unknownprefix")) {
16807             ast_copy_string(confp->ss7.unknownprefix, v->value, sizeof(confp->ss7.unknownprefix));
16808          } else if (!strcasecmp(v->name, "ss7_called_nai")) {
16809             if (!strcasecmp(v->value, "national")) {
16810                confp->ss7.called_nai = SS7_NAI_NATIONAL;
16811             } else if (!strcasecmp(v->value, "international")) {
16812                confp->ss7.called_nai = SS7_NAI_INTERNATIONAL;
16813             } else if (!strcasecmp(v->value, "subscriber")) {
16814                confp->ss7.called_nai = SS7_NAI_SUBSCRIBER;
16815             } else if (!strcasecmp(v->value, "dynamic")) {
16816                confp->ss7.called_nai = SS7_NAI_DYNAMIC;
16817             } else {
16818                ast_log(LOG_WARNING, "Unknown SS7 called_nai '%s' at line %d.\n", v->value, v->lineno);
16819             }
16820          } else if (!strcasecmp(v->name, "ss7_calling_nai")) {
16821             if (!strcasecmp(v->value, "national")) {
16822                confp->ss7.calling_nai = SS7_NAI_NATIONAL;
16823             } else if (!strcasecmp(v->value, "international")) {
16824                confp->ss7.calling_nai = SS7_NAI_INTERNATIONAL;
16825             } else if (!strcasecmp(v->value, "subscriber")) {
16826                confp->ss7.calling_nai = SS7_NAI_SUBSCRIBER;
16827             } else if (!strcasecmp(v->value, "dynamic")) {
16828                confp->ss7.calling_nai = SS7_NAI_DYNAMIC;
16829             } else {
16830                ast_log(LOG_WARNING, "Unknown SS7 calling_nai '%s' at line %d.\n", v->value, v->lineno);
16831             }
16832          } else if (!strcasecmp(v->name, "sigchan")) {
16833             int sigchan, res;
16834             sigchan = atoi(v->value);
16835             res = linkset_addsigchan(sigchan);
16836             if (res < 0)
16837                return -1;
16838
16839          } else if (!strcasecmp(v->name, "ss7_explicitacm")) {
16840             struct dahdi_ss7 *link;
16841             link = ss7_resolve_linkset(cur_linkset);
16842             if (!link) {
16843                ast_log(LOG_ERROR, "Invalid linkset number.  Must be between 1 and %d\n", NUM_SPANS + 1);
16844                return -1;
16845             }
16846             if (ast_true(v->value))
16847                link->flags |= LINKSET_FLAG_EXPLICITACM;
16848 #endif /* HAVE_SS7 */
16849 #ifdef HAVE_OPENR2
16850          } else if (!strcasecmp(v->name, "mfcr2_advanced_protocol_file")) {
16851             ast_copy_string(confp->mfcr2.r2proto_file, v->value, sizeof(confp->mfcr2.r2proto_file));
16852             ast_log(LOG_WARNING, "MFC/R2 Protocol file '%s' will be used, you only should use this if you *REALLY KNOW WHAT YOU ARE DOING*.\n", confp->mfcr2.r2proto_file);
16853          } else if (!strcasecmp(v->name, "mfcr2_logdir")) {
16854             ast_copy_string(confp->mfcr2.logdir, v->value, sizeof(confp->mfcr2.logdir));
16855          } else if (!strcasecmp(v->name, "mfcr2_variant")) {
16856             confp->mfcr2.variant = openr2_proto_get_variant(v->value);
16857             if (OR2_VAR_UNKNOWN == confp->mfcr2.variant) {
16858                ast_log(LOG_WARNING, "Unknown MFC/R2 variant '%s' at line %d, defaulting to ITU.\n", v->value, v->lineno);
16859                confp->mfcr2.variant = OR2_VAR_ITU;
16860             }
16861          } else if (!strcasecmp(v->name, "mfcr2_mfback_timeout")) {
16862             confp->mfcr2.mfback_timeout = atoi(v->value);
16863             if (!confp->mfcr2.mfback_timeout) {
16864                ast_log(LOG_WARNING, "MF timeout of 0? hum, I will protect you from your ignorance. Setting default.\n");
16865                confp->mfcr2.mfback_timeout = -1;
16866             } else if (confp->mfcr2.mfback_timeout > 0 && confp->mfcr2.mfback_timeout < 500) {
16867                ast_log(LOG_WARNING, "MF timeout less than 500ms is not recommended, you have been warned!\n");
16868             }
16869          } else if (!strcasecmp(v->name, "mfcr2_metering_pulse_timeout")) {
16870             confp->mfcr2.metering_pulse_timeout = atoi(v->value);
16871             if (confp->mfcr2.metering_pulse_timeout > 500) {
16872                ast_log(LOG_WARNING, "Metering pulse timeout greater than 500ms is not recommended, you have been warned!\n");
16873             }
16874          } else if (!strcasecmp(v->name, "mfcr2_get_ani_first")) {
16875             confp->mfcr2.get_ani_first = ast_true(v->value) ? 1 : 0;
16876          } else if (!strcasecmp(v->name, "mfcr2_double_answer")) {
16877             confp->mfcr2.double_answer = ast_true(v->value) ? 1 : 0;
16878          } else if (!strcasecmp(v->name, "mfcr2_charge_calls")) {
16879             confp->mfcr2.charge_calls = ast_true(v->value) ? 1 : 0;
16880          } else if (!strcasecmp(v->name, "mfcr2_accept_on_offer")) {
16881             confp->mfcr2.accept_on_offer = ast_true(v->value) ? 1 : 0;
16882          } else if (!strcasecmp(v->name, "mfcr2_allow_collect_calls")) {
16883             confp->mfcr2.allow_collect_calls = ast_true(v->value) ? 1 : 0;
16884          } else if (!strcasecmp(v->name, "mfcr2_forced_release")) {
16885             confp->mfcr2.forced_release = ast_true(v->value) ? 1 : 0;
16886          } else if (!strcasecmp(v->name, "mfcr2_immediate_accept")) {
16887             confp->mfcr2.immediate_accept = ast_true(v->value) ? 1 : 0;
16888          } else if (!strcasecmp(v->name, "mfcr2_call_files")) {
16889             confp->mfcr2.call_files = ast_true(v->value) ? 1 : 0;
16890          } else if (!strcasecmp(v->name, "mfcr2_max_ani")) {
16891             confp->mfcr2.max_ani = atoi(v->value);
16892             if (confp->mfcr2.max_ani >= AST_MAX_EXTENSION){
16893                confp->mfcr2.max_ani = AST_MAX_EXTENSION - 1;
16894             }
16895          } else if (!strcasecmp(v->name, "mfcr2_max_dnis")) {
16896             confp->mfcr2.max_dnis = atoi(v->value);
16897             if (confp->mfcr2.max_dnis >= AST_MAX_EXTENSION){
16898                confp->mfcr2.max_dnis = AST_MAX_EXTENSION - 1;
16899             }
16900          } else if (!strcasecmp(v->name, "mfcr2_category")) {
16901             confp->mfcr2.category = openr2_proto_get_category(v->value);
16902             if (OR2_CALLING_PARTY_CATEGORY_UNKNOWN == confp->mfcr2.category) {
16903                confp->mfcr2.category = OR2_CALLING_PARTY_CATEGORY_NATIONAL_SUBSCRIBER;
16904                ast_log(LOG_WARNING, "Invalid MFC/R2 caller category '%s' at line %d. Using national subscriber as default.\n",
16905                      v->value, v->lineno);
16906             }
16907          } else if (!strcasecmp(v->name, "mfcr2_logging")) {
16908             openr2_log_level_t tmplevel;
16909             char *clevel;
16910             char *logval = ast_strdupa(v->value);
16911             while (logval) {
16912                clevel = strsep(&logval,",");
16913                if (-1 == (tmplevel = openr2_log_get_level(clevel))) {
16914                   ast_log(LOG_WARNING, "Ignoring invalid logging level: '%s' at line %d.\n", clevel, v->lineno);
16915                   continue;
16916                }
16917                confp->mfcr2.loglevel |= tmplevel;
16918             }
16919 #endif /* HAVE_OPENR2 */
16920          } else if (!strcasecmp(v->name, "cadence")) {
16921             /* setup to scan our argument */
16922             int element_count, c[16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
16923             int i;
16924             struct dahdi_ring_cadence new_cadence;
16925             int cid_location = -1;
16926             int firstcadencepos = 0;
16927             char original_args[80];
16928             int cadence_is_ok = 1;
16929
16930             ast_copy_string(original_args, v->value, sizeof(original_args));
16931             /* 16 cadences allowed (8 pairs) */
16932             element_count = sscanf(v->value, "%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d,%30d", &c[0], &c[1], &c[2], &c[3], &c[4], &c[5], &c[6], &c[7], &c[8], &c[9], &c[10], &c[11], &c[12], &c[13], &c[14], &c[15]);
16933
16934             /* Cadence must be even (on/off) */
16935             if (element_count % 2 == 1) {
16936                ast_log(LOG_ERROR, "Must be a silence duration for each ring duration: %s at line %d.\n", original_args, v->lineno);
16937                cadence_is_ok = 0;
16938             }
16939
16940             /* Ring cadences cannot be negative */
16941             for (i = 0; i < element_count; i++) {
16942                if (c[i] == 0) {
16943                   ast_log(LOG_ERROR, "Ring or silence duration cannot be zero: %s at line %d.\n", original_args, v->lineno);
16944                   cadence_is_ok = 0;
16945                   break;
16946                } else if (c[i] < 0) {
16947                   if (i % 2 == 1) {
16948                      /* Silence duration, negative possibly okay */
16949                      if (cid_location == -1) {
16950                         cid_location = i;
16951                         c[i] *= -1;
16952                      } else {
16953                         ast_log(LOG_ERROR, "CID location specified twice: %s at line %d.\n", original_args, v->lineno);
16954                         cadence_is_ok = 0;
16955                         break;
16956                      }
16957                   } else {
16958                      if (firstcadencepos == 0) {
16959                         firstcadencepos = i; /* only recorded to avoid duplicate specification */
16960                                  /* duration will be passed negative to the DAHDI driver */
16961                      } else {
16962                          ast_log(LOG_ERROR, "First cadence position specified twice: %s at line %d.\n", original_args, v->lineno);
16963                         cadence_is_ok = 0;
16964                         break;
16965                      }
16966                   }
16967                }
16968             }
16969
16970             /* Substitute our scanned cadence */
16971             for (i = 0; i < 16; i++) {
16972                new_cadence.ringcadence[i] = c[i];
16973             }
16974
16975             if (cadence_is_ok) {
16976                /* ---we scanned it without getting annoyed; now some sanity checks--- */
16977                if (element_count < 2) {
16978                   ast_log(LOG_ERROR, "Minimum cadence is ring,pause: %s at line %d.\n", original_args, v->lineno);
16979                } else {
16980                   if (cid_location == -1) {
16981                      /* user didn't say; default to first pause */
16982                      cid_location = 1;
16983                   } else {
16984                      /* convert element_index to cidrings value */
16985                      cid_location = (cid_location + 1) / 2;
16986                   }
16987                   /* ---we like their cadence; try to install it--- */
16988                   if (!user_has_defined_cadences++)
16989                      /* this is the first user-defined cadence; clear the default user cadences */
16990                      num_cadence = 0;
16991                   if ((num_cadence+1) >= NUM_CADENCE_MAX)
16992                      ast_log(LOG_ERROR, "Already %d cadences; can't add another: %s at line %d.\n", NUM_CADENCE_MAX, original_args, v->lineno);
16993                   else {
16994                      cadences[num_cadence] = new_cadence;
16995                      cidrings[num_cadence++] = cid_location;
16996                      ast_verb(3, "cadence 'r%d' added: %s\n",num_cadence,original_args);
16997                   }
16998                }
16999             }
17000          } else if (!strcasecmp(v->name, "ringtimeout")) {
17001             ringt_base = (atoi(v->value) * 8) / READ_SIZE;
17002          } else if (!strcasecmp(v->name, "prewink")) {
17003             confp->timing.prewinktime = atoi(v->value);
17004          } else if (!strcasecmp(v->name, "preflash")) {
17005             confp->timing.preflashtime = atoi(v->value);
17006          } else if (!strcasecmp(v->name, "wink")) {
17007             confp->timing.winktime = atoi(v->value);
17008          } else if (!strcasecmp(v->name, "flash")) {
17009             confp->timing.flashtime = atoi(v->value);
17010          } else if (!strcasecmp(v->name, "start")) {
17011             confp->timing.starttime = atoi(v->value);
17012          } else if (!strcasecmp(v->name, "rxwink")) {
17013             confp->timing.rxwinktime = atoi(v->value);
17014          } else if (!strcasecmp(v->name, "rxflash")) {
17015             confp->timing.rxflashtime = atoi(v->value);
17016          } else if (!strcasecmp(v->name, "debounce")) {
17017             confp->timing.debouncetime = atoi(v->value);
17018          } else if (!strcasecmp(v->name, "toneduration")) {
17019             int toneduration;
17020             int ctlfd;
17021             int res;
17022             struct dahdi_dialparams dps;
17023
17024             ctlfd = open("/dev/dahdi/ctl", O_RDWR);
17025             if (ctlfd == -1) {
17026                ast_log(LOG_ERROR, "Unable to open /dev/dahdi/ctl to set toneduration at line %d.\n", v->lineno);
17027                return -1;
17028             }
17029
17030             toneduration = atoi(v->value);
17031             if (toneduration > -1) {
17032                memset(&dps, 0, sizeof(dps));
17033
17034                dps.dtmf_tonelen = dps.mfv1_tonelen = toneduration;
17035                res = ioctl(ctlfd, DAHDI_SET_DIALPARAMS, &dps);
17036                if (res < 0) {
17037                   ast_log(LOG_ERROR, "Invalid tone duration: %d ms at line %d: %s\n", toneduration, v->lineno, strerror(errno));
17038                   return -1;
17039                }
17040             }
17041             close(ctlfd);
17042          } else if (!strcasecmp(v->name, "defaultcic")) {
17043             ast_copy_string(defaultcic, v->value, sizeof(defaultcic));
17044          } else if (!strcasecmp(v->name, "defaultozz")) {
17045             ast_copy_string(defaultozz, v->value, sizeof(defaultozz));
17046          } else if (!strcasecmp(v->name, "mwilevel")) {
17047             mwilevel = atoi(v->value);
17048          }
17049       } else if (!(options & PROC_DAHDI_OPT_NOWARN))
17050          ast_log(LOG_WARNING, "Ignoring any changes to '%s' (on reload) at line %d.\n", v->name, v->lineno);
17051    }
17052    if (dahdichan[0]) {
17053       /* The user has set 'dahdichan' */
17054       /*< \todo pass proper line number instead of 0 */
17055       if (build_channels(confp, 0, dahdichan, reload, 0, &found_pseudo)) {
17056          return -1;
17057       }
17058    }
17059    /*< \todo why check for the pseudo in the per-channel section.
17060     * Any actual use for manual setup of the pseudo channel? */
17061    if (!found_pseudo && reload != 1) {
17062       /* use the default configuration for a channel, so
17063          that any settings from real configured channels
17064          don't "leak" into the pseudo channel config
17065       */
17066       struct dahdi_chan_conf conf = dahdi_chan_conf_default();
17067
17068       tmp = mkintf(CHAN_PSEUDO, &conf, NULL, reload);
17069
17070       if (tmp) {
17071          ast_verb(3, "Automatically generated pseudo channel\n");
17072       } else {
17073          ast_log(LOG_WARNING, "Unable to register pseudo channel!\n");
17074       }
17075    }
17076    return 0;
17077 }
static void process_echocancel (struct dahdi_chan_conf * confp, const char * data, unsigned int line) [static]
Definition at line 16040 of file chan_dahdi.c.
References ARRAY_LEN, ast_app_separate_args, ast_log(), ast_strdupa, ast_strlen_zero(), ast_true(), dahdi_chan_conf::chan, dahdi_pvt::echocancel, dahdi_pvt::head, LOG_WARNING, name, and dahdi_pvt::params.
Referenced by process_dahdi().
16041 {
16042    char *parse = ast_strdupa(data);
16043    char *params[DAHDI_MAX_ECHOCANPARAMS + 1];
16044    unsigned int param_count;
16045    unsigned int x;
16046
16047    if (!(param_count = ast_app_separate_args(parse, ',', params, ARRAY_LEN(params))))
16048       return;
16049
16050    memset(&confp->chan.echocancel, 0, sizeof(confp->chan.echocancel));
16051
16052    /* first parameter is tap length, process it here */
16053
16054    x = ast_strlen_zero(params[0]) ? 0 : atoi(params[0]);
16055
16056    if ((x == 32) || (x == 64) || (x == 128) || (x == 256) || (x == 512) || (x == 1024))
16057       confp->chan.echocancel.head.tap_length = x;
16058    else if ((confp->chan.echocancel.head.tap_length = ast_true(params[0])))
16059       confp->chan.echocancel.head.tap_length = 128;
16060
16061    /* now process any remaining parameters */
16062
16063    for (x = 1; x < param_count; x++) {
16064       struct {
16065          char *name;
16066          char *value;
16067       } param;
16068
16069       if (ast_app_separate_args(params[x], '=', (char **) &param, 2) < 1) {
16070          ast_log(LOG_WARNING, "Invalid echocancel parameter supplied at line %d: '%s'\n", line, params[x]);
16071          continue;
16072       }
16073
16074       if (ast_strlen_zero(param.name) || (strlen(param.name) > sizeof(confp->chan.echocancel.params[0].name)-1)) {
16075          ast_log(LOG_WARNING, "Invalid echocancel parameter supplied at line %d: '%s'\n", line, param.name);
16076          continue;
16077       }
16078
16079       strcpy(confp->chan.echocancel.params[confp->chan.echocancel.head.param_count].name, param.name);
16080
16081       if (param.value) {
16082          if (sscanf(param.value, "%30d", &confp->chan.echocancel.params[confp->chan.echocancel.head.param_count].value) != 1) {
16083             ast_log(LOG_WARNING, "Invalid echocancel parameter value supplied at line %d: '%s'\n", line, param.value);
16084             continue;
16085          }
16086       }
16087       confp->chan.echocancel.head.param_count++;
16088    }
16089 }
static int reload (void) [static]
Definition at line 17480 of file chan_dahdi.c.
References ast_log(), LOG_WARNING, and setup_dahdi().
17481 {
17482    int res = 0;
17483
17484    res = setup_dahdi(1);
17485    if (res) {
17486       ast_log(LOG_WARNING, "Reload of chan_dahdi.so is unsuccessful!\n");
17487       return -1;
17488    }
17489    return 0;
17490 }
static int reset_conf (struct dahdi_pvt * p) [static]
Definition at line 2590 of file chan_dahdi.c.
References ast_log(), dahdi_pvt::channel, dahdi_pvt::confno, dahdi_subchannel::curconf, dahdi_subchannel::dfd, errno, LOG_WARNING, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_hangup().
{
   p->confno = -1;
   memset(&p->subs[SUB_REAL].curconf, 0, sizeof(p->subs[SUB_REAL].curconf));
   if (p->subs[SUB_REAL].dfd > -1) {
      struct dahdi_confinfo zi;
      memset(&zi, 0, sizeof(zi));
      if (ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETCONF, &zi))
         ast_log(LOG_WARNING, "Failed to reset conferencing on channel %d: %s\n", p->channel, strerror(errno));
   }
   return 0;
}
static int restart_monitor (void) [static]
Definition at line 9705 of file chan_dahdi.c.
References ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_pthread_create_background, AST_PTHREADT_NULL, AST_PTHREADT_STOP, do_monitor(), LOG_ERROR, and LOG_WARNING.
Referenced by dahdi_hangup(), dahdi_request(), and setup_dahdi().
{
   /* If we're supposed to be stopped -- stay stopped */
   if (monitor_thread == AST_PTHREADT_STOP)
      return 0;
   ast_mutex_lock(&monlock);
   if (monitor_thread == pthread_self()) {
      ast_mutex_unlock(&monlock);
      ast_log(LOG_WARNING, "Cannot kill myself\n");
      return -1;
   }
   if (monitor_thread != AST_PTHREADT_NULL) {
      /* Wake up the thread */
      pthread_kill(monitor_thread, SIGURG);
   } else {
      /* Start a new monitor */
      if (ast_pthread_create_background(&monitor_thread, NULL, do_monitor, NULL) < 0) {
         ast_mutex_unlock(&monlock);
         ast_log(LOG_ERROR, "Unable to start monitor thread.\n");
         return -1;
      }
   }
   ast_mutex_unlock(&monlock);
   return 0;
}
static int restore_conference (struct dahdi_pvt * p) [static]
Definition at line 2969 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_subchannel::dfd, errno, LOG_WARNING, dahdi_pvt::saveconf, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_handle_event(), dahdi_read(), and send_callerid().
{
   int res;
   if (p->saveconf.confmode) {
      res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETCONF, &p->saveconf);
      p->saveconf.confmode = 0;
      if (res) {
         ast_log(LOG_WARNING, "Unable to restore conference info: %s\n", strerror(errno));
         return -1;
      }
   }
   ast_debug(1, "Restored conferencing\n");
   return 0;
}
static int restore_gains (struct dahdi_pvt * p) [static]
Definition at line 2850 of file chan_dahdi.c.
References ast_log(), dahdi_subchannel::dfd, errno, dahdi_pvt::law, LOG_WARNING, dahdi_pvt::rxgain, set_actual_gain(), SUB_REAL, dahdi_pvt::subs, and dahdi_pvt::txgain.
Referenced by dahdi_hangup(), mwi_thread(), and ss_thread().
{
   int res;
   res = set_actual_gain(p->subs[SUB_REAL].dfd, 0, p->rxgain, p->txgain, p->law);
   if (res) {
      ast_log(LOG_WARNING, "Unable to restore gains: %s\n", strerror(errno));
      return -1;
   }
   return 0;
}
static int save_conference (struct dahdi_pvt * p) [static]
Definition at line 2896 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_subchannel::dfd, errno, LOG_WARNING, dahdi_pvt::saveconf, SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_callwait(), and dahdi_handle_event().
{
   struct dahdi_confinfo c;
   int res;
   if (p->saveconf.confmode) {
      ast_log(LOG_WARNING, "Can't save conference -- already in use\n");
      return -1;
   }
   p->saveconf.chan = 0;
   res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_GETCONF, &p->saveconf);
   if (res) {
      ast_log(LOG_WARNING, "Unable to get conference info: %s\n", strerror(errno));
      p->saveconf.confmode = 0;
      return -1;
   }
   memset(&c, 0, sizeof(c));
   c.confmode = DAHDI_CONF_NORMAL;
   res = ioctl(p->subs[SUB_REAL].dfd, DAHDI_SETCONF, &c);
   if (res) {
      ast_log(LOG_WARNING, "Unable to set conference info: %s\n", strerror(errno));
      return -1;
   }
   ast_debug(1, "Disabled conferencing\n");
   return 0;
}
static int send_callerid (struct dahdi_pvt * p) [static]
Definition at line 3026 of file chan_dahdi.c.
References ast_free, ast_log(), dahdi_pvt::callwaitcas, CIDCW_EXPIRE_SAMPLES, dahdi_pvt::cidcwexpire, dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, dahdi_setlinear(), dahdi_subchannel::dfd, errno, dahdi_subchannel::linear, LOG_WARNING, restore_conference(), SUB_REAL, and dahdi_pvt::subs.
Referenced by dahdi_call(), dahdi_callwait(), dahdi_read(), and send_cwcidspill().
{
   /* Assumes spill in p->cidspill, p->cidlen in length and we're p->cidpos into it */
   int res;
   /* Take out of linear mode if necessary */
   if (p->subs[SUB_REAL].linear) {
      p->subs[SUB_REAL].linear = 0;
      dahdi_setlinear(p->subs[SUB_REAL].dfd, 0);
   }
   while (p->cidpos < p->cidlen) {
      res = write(p->subs[SUB_REAL].dfd, p->cidspill + p->cidpos, p->cidlen - p->cidpos);
      if (res < 0) {
         if (errno == EAGAIN)
            return 0;
         else {
            ast_log(LOG_WARNING, "write failed: %s\n", strerror(errno));
            return -1;
         }
      }
      if (!res)
         return 0;
      p->cidpos += res;
   }
   ast_free(p->cidspill);
   p->cidspill = NULL;
   if (p->callwaitcas) {
      /* Wait for CID/CW to expire */
      p->cidcwexpire = CIDCW_EXPIRE_SAMPLES;
   } else
      restore_conference(p);
   return 0;
}
static int send_cwcidspill (struct dahdi_pvt * p) [static]
Definition at line 2986 of file chan_dahdi.c.
References ast_callerid_callwaiting_generate(), AST_LAW, ast_malloc, ast_verb, dahdi_pvt::callwait_name, dahdi_pvt::callwait_num, dahdi_pvt::callwaitcas, dahdi_pvt::cidcwexpire, dahdi_pvt::cidlen, dahdi_pvt::cidpos, dahdi_pvt::cidspill, MAX_CALLERID_SIZE, READ_SIZE, and send_callerid().
Referenced by dahdi_handle_dtmfup().
{
   p->callwaitcas = 0;
   p->cidcwexpire = 0;
   if (!(p->cidspill = ast_malloc(MAX_CALLERID_SIZE)))
      return -1;
   p->cidlen = ast_callerid_callwaiting_generate(p->cidspill, p->callwait_name, p->callwait_num, AST_LAW(p));
   /* Make sure we account for the end */
   p->cidlen += READ_SIZE * 4;
   p->cidpos = 0;
   send_callerid(p);
   ast_verb(3, "CPE supports Call Waiting Caller*ID.  Sending '%s/%s'\n", p->callwait_name, p->callwait_num);
   return 0;
}
static int set_actual_gain (int fd, int chan, float rxgain, float txgain, int law) [static]
Definition at line 2831 of file chan_dahdi.c.
References set_actual_rxgain(), and set_actual_txgain().
Referenced by bump_gains(), dahdi_call(), mkintf(), and restore_gains().
{
   return set_actual_txgain(fd, chan, txgain, law) | set_actual_rxgain(fd, chan, rxgain, law);
}
static int set_actual_rxgain (int fd, int chan, float gain, int law) [static]
Definition at line 2813 of file chan_dahdi.c.
References ast_debug, errno, and fill_rxgain().
Referenced by dahdi_set_swgain(), dahdi_setoption(), and set_actual_gain().
{
   struct dahdi_gains g;
   int res;
   memset(&g, 0, sizeof(g));
   g.chan = chan;
   res = ioctl(fd, DAHDI_GETGAINS, &g);
   if (res) {
      ast_debug(1, "Failed to read gains: %s\n", strerror(errno));
      return res;
   }
   fill_rxgain(&g, gain, law);
   return ioctl(fd, DAHDI_SETGAINS, &g);
}
static int set_actual_txgain (int fd, int chan, float gain, int law) [static]
Definition at line 2795 of file chan_dahdi.c.
References ast_debug, errno, and fill_txgain().
Referenced by dahdi_set_swgain(), dahdi_setoption(), and set_actual_gain().
{
   struct dahdi_gains g;
   int res;
   memset(&g, 0, sizeof(g));
   g.chan = chan;
   res = ioctl(fd, DAHDI_GETGAINS, &g);
   if (res) {
      ast_debug(1, "Failed to read gains: %s\n", strerror(errno));
      return res;
   }
   fill_txgain(&g, gain, law);
   return ioctl(fd, DAHDI_SETGAINS, &g);
}
static int setup_dahdi (int reload) [static]
Definition at line 17079 of file chan_dahdi.c.
References ast_category_browse(), ast_clear_flag, ast_config_destroy(), ast_config_load, ast_log(), ast_mutex_lock(), ast_mutex_unlock(), ast_pthread_create, ast_strlen_zero(), ast_variable_browse(), ast_variable_retrieve(), ast_verb, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEUNCHANGED, dahdi_chan_conf_default(), global_jbconf, ast_variable::lineno, LOG_ERROR, LOG_NOTICE, LOG_WARNING, master, ast_variable::name, ast_variable::next, PROC_DAHDI_OPT_NOCHAN, PROC_DAHDI_OPT_NOWARN, process_dahdi(), pvts, restart_monitor(), and ast_variable::value.
Referenced by dahdi_restart(), load_module(), and reload().
17080 {
17081    struct ast_config *cfg, *ucfg;
17082    struct ast_variable *v;
17083    struct dahdi_chan_conf base_conf = dahdi_chan_conf_default();
17084    struct dahdi_chan_conf conf;
17085    struct ast_flags config_flags = { reload == 1 ? CONFIG_FLAG_FILEUNCHANGED : 0 };
17086    const char *cat;
17087    int res;
17088
17089 #ifdef HAVE_PRI
17090    char *c;
17091    int spanno;
17092    int i;
17093    int logicalspan;
17094    int trunkgroup;
17095    int dchannels[NUM_DCHANS];
17096 #endif
17097
17098    cfg = ast_config_load(config, config_flags);
17099
17100    /* Error if we have no config file */
17101    if (!cfg) {
17102       ast_log(LOG_ERROR, "Unable to load config %s\n", config);
17103       return 0;
17104    } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
17105       ucfg = ast_config_load("users.conf", config_flags);
17106       if (ucfg == CONFIG_STATUS_FILEUNCHANGED) {
17107          return 0;
17108       } else if (ucfg == CONFIG_STATUS_FILEINVALID) {
17109          ast_log(LOG_ERROR, "File users.conf cannot be parsed.  Aborting.\n");
17110          return 0;
17111       }
17112       ast_clear_flag(&config_flags, CONFIG_FLAG_FILEUNCHANGED);
17113       if ((cfg = ast_config_load(config, config_flags)) == CONFIG_STATUS_FILEINVALID) {
17114          ast_log(LOG_ERROR, "File %s cannot be parsed.  Aborting.\n", config);
17115          ast_config_destroy(ucfg);
17116          return 0;
17117       }
17118    } else if (cfg == CONFIG_STATUS_FILEINVALID) {
17119       ast_log(LOG_ERROR, "File %s cannot be parsed.  Aborting.\n", config);
17120       return 0;
17121    } else {
17122       ast_clear_flag(&config_flags, CONFIG_FLAG_FILEUNCHANGED);
17123       if ((ucfg = ast_config_load("users.conf", config_flags)) == CONFIG_STATUS_FILEINVALID) {
17124          ast_log(LOG_ERROR, "File users.conf cannot be parsed.  Aborting.\n");
17125          ast_config_destroy(cfg);
17126          return 0;
17127       }
17128    }
17129
17130    /* It's a little silly to lock it, but we mind as well just to be sure */
17131    ast_mutex_lock(&iflock);
17132 #ifdef HAVE_PRI
17133    if (reload != 1) {
17134       /* Process trunkgroups first */
17135       v = ast_variable_browse(cfg, "trunkgroups");
17136       while (v) {
17137          if (!strcasecmp(v->name, "trunkgroup")) {
17138             trunkgroup = atoi(v->value);
17139             if (trunkgroup > 0) {
17140                if ((c = strchr(v->value, ','))) {
17141                   i = 0;
17142                   memset(dchannels, 0, sizeof(dchannels));
17143                   while (c && (i < NUM_DCHANS)) {
17144                      dchannels[i] = atoi(c + 1);
17145                      if (dchannels[i] < 0) {
17146                         ast_log(LOG_WARNING, "D-channel for trunk group %d must be a postiive number at line %d of chan_dahdi.conf\n", trunkgroup, v->lineno);
17147                      } else
17148                         i++;
17149                      c = strchr(c + 1, ',');
17150                   }
17151                   if (i) {
17152                      if (pri_create_trunkgroup(trunkgroup, dchannels)) {
17153                         ast_log(LOG_WARNING, "Unable to create trunk group %d with Primary D-channel %d at line %d of chan_dahdi.conf\n", trunkgroup, dchannels[0], v->lineno);
17154                   } else
17155                         ast_verb(2, "Created trunk group %d with Primary D-channel %d and %d backup%s\n", trunkgroup, dchannels[0], i - 1, (i == 1) ? "" : "s");
17156                   } else
17157                      ast_log(LOG_WARNING, "Trunk group %d lacks any valid D-channels at line %d of chan_dahdi.conf\n", trunkgroup, v->lineno);
17158                } else
17159                   ast_log(LOG_WARNING, "Trunk group %d lacks a primary D-channel at line %d of chan_dahdi.conf\n", trunkgroup, v->lineno);
17160             } else
17161                ast_log(LOG_WARNING, "Trunk group identifier must be a positive integer at line %d of chan_dahdi.conf\n", v->lineno);
17162          } else if (!strcasecmp(v->name, "spanmap")) {
17163             spanno = atoi(v->value);
17164             if (spanno > 0) {
17165                if ((c = strchr(v->value, ','))) {
17166                   trunkgroup = atoi(c + 1);
17167                   if (trunkgroup > 0) {
17168                      if ((c = strchr(c + 1, ',')))
17169                         logicalspan = atoi(c + 1);
17170                      else
17171                         logicalspan = 0;
17172                      if (logicalspan >= 0) {
17173                         if (pri_create_spanmap(spanno - 1, trunkgroup, logicalspan)) {
17174                            ast_log(LOG_WARNING, "Failed to map span %d to trunk group %d (logical span %d)\n", spanno, trunkgroup, logicalspan);
17175                      } else
17176                            ast_verb(2, "Mapped span %d to trunk group %d (logical span %d)\n", spanno, trunkgroup, logicalspan);
17177                      } else
17178                         ast_log(LOG_WARNING, "Logical span must be a postive number, or '0' (for unspecified) at line %d of chan_dahdi.conf\n", v->lineno);
17179                   } else
17180                      ast_log(LOG_WARNING, "Trunk group must be a postive number at line %d of chan_dahdi.conf\n", v->lineno);
17181                } else
17182                   ast_log(LOG_WARNING, "Missing trunk group for span map at line %d of chan_dahdi.conf\n", v->lineno);
17183             } else
17184                ast_log(LOG_WARNING, "Span number must be a postive integer at line %d of chan_dahdi.conf\n", v->lineno);
17185          } else {
17186             ast_log(LOG_NOTICE, "Ignoring unknown keyword '%s' in trunkgroups\n", v->name);
17187          }
17188          v = v->next;
17189       }
17190    }
17191 #endif
17192
17193    /* Copy the default jb config over global_jbconf */
17194    memcpy(&global_jbconf, &default_jbconf, sizeof(global_jbconf));
17195
17196    mwimonitornotify[0] = '\0';
17197
17198    v = ast_variable_browse(cfg, "channels");
17199    if ((res = process_dahdi(&base_conf, "", v, reload, 0))) {
17200       ast_mutex_unlock(&iflock);
17201       ast_config_destroy(cfg);
17202       if (ucfg) {
17203          ast_config_destroy(ucfg);
17204       }
17205       return res;
17206    }
17207
17208    /* Now get configuration from all normal sections in chan_dahdi.conf: */
17209    for (cat = ast_category_browse(cfg, NULL); cat ; cat = ast_category_browse(cfg, cat)) {
17210       /* [channels] and [trunkgroups] are used. Let's also reserve
17211        * [globals] and [general] for future use
17212        */
17213       if (!strcasecmp(cat, "general") ||
17214          !strcasecmp(cat, "trunkgroups") ||
17215          !strcasecmp(cat, "globals") ||
17216          !strcasecmp(cat, "channels")) {
17217          continue;
17218       }
17219
17220       memcpy(&conf, &base_conf, sizeof(conf));
17221
17222       if ((res = process_dahdi(&conf, cat, ast_variable_browse(cfg, cat), reload, PROC_DAHDI_OPT_NOCHAN))) {
17223          ast_mutex_unlock(&iflock);
17224          ast_config_destroy(cfg);
17225          if (ucfg) {
17226             ast_config_destroy(cfg);
17227          }
17228          return res;
17229       }
17230    }
17231
17232    ast_config_destroy(cfg);
17233
17234    if (ucfg) {
17235       const char *chans;
17236
17237       process_dahdi(&base_conf, "", ast_variable_browse(ucfg, "general"), 1, 0);
17238
17239       for (cat = ast_category_browse(ucfg, NULL); cat ; cat = ast_category_browse(ucfg, cat)) {
17240          if (!strcasecmp(cat, "general")) {
17241             continue;
17242          }
17243
17244          chans = ast_variable_retrieve(ucfg, cat, "dahdichan");
17245
17246          if (ast_strlen_zero(chans)) {
17247             continue;
17248          }
17249
17250          memcpy(&conf, &base_conf, sizeof(conf));
17251
17252          if ((res = process_dahdi(&conf, cat, ast_variable_browse(ucfg, cat), reload, PROC_DAHDI_OPT_NOCHAN | PROC_DAHDI_OPT_NOWARN))) {
17253             ast_config_destroy(ucfg);
17254             ast_mutex_unlock(&iflock);
17255             return res;
17256          }
17257       }
17258       ast_config_destroy(ucfg);
17259    }
17260    ast_mutex_unlock(&iflock);
17261
17262 #ifdef HAVE_PRI
17263    if (reload != 1) {
17264       int x;
17265       for (x = 0; x < NUM_SPANS; x++) {
17266          if (pris[x].pvts[0]) {
17267             if (start_pri(pris + x)) {
17268                ast_log(LOG_ERROR, "Unable to start D-channel on span %d\n", x + 1);
17269                return -1;
17270             } else
17271                ast_verb(2, "Starting D-Channel on span %d\n", x + 1);
17272          }
17273       }
17274    }
17275 #endif
17276 #ifdef HAVE_SS7
17277    if (reload != 1) {
17278       int x;
17279       for (x = 0; x < NUM_SPANS; x++) {
17280          if (linksets[x].ss7) {
17281             if (ast_pthread_create(&linksets[x].master, NULL, ss7_linkset, &linksets[x])) {
17282                ast_log(LOG_ERROR, "Unable to start SS7 linkset on span %d\n", x + 1);
17283                return -1;
17284             } else
17285                ast_verb(2, "Starting SS7 linkset on span %d\n", x + 1);
17286          }
17287       }
17288    }
17289 #endif
17290 #ifdef HAVE_OPENR2
17291    if (reload != 1) {
17292       int x;
17293       for (x = 0; x < r2links_count; x++) {
17294          if (ast_pthread_create(&r2links[x]->r2master, NULL, mfcr2_monitor, r2links[x])) {
17295             ast_log(LOG_ERROR, "Unable to start R2 monitor on channel group %d\n", x + 1);
17296             return -1;
17297          } else {
17298             ast_verb(2, "Starting R2 monitor on channel group %d\n", x + 1);
17299          }
17300       }
17301    }
17302 #endif
17303    /* And start the monitor for the first time */
17304    restart_monitor();
17305    return 0;
17306 }
static int sigtype_to_signalling (int sigtype) [static]
Definition at line 9985 of file chan_dahdi.c.
Referenced by mkintf().
{
   return sigtype;
}
static void * ss_thread (void * data) [static]
Definition at line 7675 of file chan_dahdi.c.
References ast_channel::_state, alloc_sub(), ARRAY_LEN, ast_bridged_channel(), ast_canmatch_extension(), AST_CAUSE_UNALLOCATED, ast_cond_signal(), AST_CONTROL_RING, AST_CONTROL_UNHOLD, ast_copy_string(), ast_db_put(), ast_debug, ast_dsp_digitreset(), ast_dsp_free(), ast_dsp_set_digitmode(), ast_exists_extension(), AST_FRAME_CONTROL, AST_FRAME_DTMF, ast_free, ast_frfree, ast_hangup(), ast_ignore_pattern(), AST_LAW, ast_log(), ast_masq_park_call(), ast_matchmore_extension(), AST_MAX_EXTENSION, ast_mutex_lock(), ast_mutex_unlock(), ast_parking_ext(), ast_pbx_run(), ast_pickup_call(), ast_pickup_ext(), ast_queue_control(), ast_read(), ast_safe_sleep(), ast_say_digit_str(), ast_set_callerid(), ast_setstate(), ast_shrink_phone_number(), ast_smdi_md_message_destroy(), ast_smdi_md_message_wait(), AST_STATE_PRERING, AST_STATE_RING, AST_STATE_RINGING, ast_streamfile(), ast_strlen_zero(), ast_verb, ast_waitfor(), ast_waitfordigit(), ast_waitstream(), ASTOBJ_UNREF, buf, bump_gains(), dahdi_pvt::call_forward, callerid_feed(), callerid_feed_jp(), callerid_free(), callerid_get(), callerid_get_dtmf(), callerid_new(), ast_smdi_md_message::calling_st, dahdi_pvt::callreturn, dahdi_pvt::callwaiting, dahdi_pvt::cancallforward, dahdi_pvt::canpark, dahdi_pvt::channel, ast_channel::cid, CID_MSGWAITING, ast_callerid::cid_name, dahdi_pvt::cid_name, CID_NOMSGWAITING, ast_callerid::cid_num, dahdi_pvt::cid_num, CID_SIG_DTMF, CID_SIG_SMDI, CID_SIG_V23, CID_SIG_V23_JP, dahdi_pvt::cid_signalling, dahdi_pvt::cid_start, CID_START_POLARITY, CID_START_POLARITY_IN, CID_START_RING, dahdi_pvt::context, ast_channel::context, ringContextData::contextData, dahdi_dnd(), dahdi_enable_ec(), dahdi_get_event(), dahdi_get_index(), DAHDI_OVERLAPDIAL_INCOMING, dahdi_set_hook(), dahdi_setlinear(), dahdi_wait_event(), dahdi_wink(), dahdi_pvt::defcontext, dahdi_subchannel::dfd, dahdi_pvt::dop, dahdi_pvt::drings, dahdi_pvt::dsp, DSP_DIGITMODE_DTMF, DSP_DIGITMODE_MF, dahdi_pvt::dtmfrelax, errno, event2str(), ast_channel::exten, dahdi_pvt::exten, exten, ast_frame::frametype, ast_smdi_md_message::fwd_st, ast_channel::hangupcause, dahdi_pvt::hanguponpolarityswitch, dahdi_pvt::hardwaredtmf, dahdi_pvt::hidecallerid, dahdi_pvt::immediate, dahdi_pvt::inalarm, ISTRUNK, dahdi_pvt::lastcid_num, len(), dahdi_subchannel::linear, LOG_DEBUG, LOG_NOTICE, LOG_WARNING, dahdi_pvt::mailbox, dahdi_pvt::mwimonitor_rpas, my_getsigstr(), name, NEED_MFDETECT, notify_message(), dahdi_pvt::owner, dahdi_subchannel::owner, pbx_builtin_setvar_helper(), dahdi_pvt::polarity, POLARITY_IDLE, POLARITY_REV, quit, distRingData::range, restore_gains(), distRingData::ring, dahdi_distRings::ringContext, dahdi_distRings::ringnum, ast_channel::rings, dahdi_pvt::ringt, dahdi_pvt::ringt_base, dahdi_pvt::sig, sig2str, SIG_BRI, SIG_BRI_PTMP, SIG_E911, SIG_EM, SIG_EM_E1, SIG_EMWINK, SIG_FEATB, SIG_FEATD, SIG_FEATDMF, SIG_FEATDMF_TA, SIG_FGC_CAMA, SIG_FGC_CAMAMF, SIG_FXOGS, SIG_FXOKS, SIG_FXOLS, SIG_FXSGS, SIG_FXSKS, SIG_FXSLS, SIG_PRI, SIG_SF, SIG_SF_FEATB, SIG_SF_FEATD, SIG_SF_FEATDMF, SIG_SFWINK, dahdi_pvt::smdi_iface, SMDI_MD_WAIT_TIMEOUT, dahdi_pvt::span, strsep(), SUB_CALLWAIT, SUB_REAL, SUB_THREEWAY, ast_frame::subclass, dahdi_pvt::subs, swap_subs(), ast_channel::tech, ast_channel::tech_pvt, dahdi_pvt::transfer, ast_smdi_md_message::type, unalloc_sub(), dahdi_pvt::use_callerid, dahdi_pvt::use_smdi, and dahdi_pvt::usedistinctiveringdetection.
Referenced by dahdi_handle_event(), handle_init_event(), and mwi_thread().
{
   struct ast_channel *chan = data;
   struct dahdi_pvt *p = chan->tech_pvt;
   char exten[AST_MAX_EXTENSION] = "";
   char exten2[AST_MAX_EXTENSION] = "";
   unsigned char buf[256];
   char dtmfcid[300];
   char dtmfbuf[300];
   struct callerid_state *cs = NULL;
   char *name = NULL, *number = NULL;
   int distMatches;
   int curRingData[3];
   int receivedRingT;
   int counter1;
   int counter;
   int samples = 0;
   struct ast_smdi_md_message *smdi_msg = NULL;
   int flags = 0;
   int i;
   int timeout;
   int getforward = 0;
   char *s1, *s2;
   int len = 0;
   int res;
   int idx;
   ast_mutex_lock(&ss_thread_lock);
   ss_thread_count++;
   ast_mutex_unlock(&ss_thread_lock);
   /* in the bizarre case where the channel has become a zombie before we
      even get started here, abort safely
   */
   if (!p) {
      ast_log(LOG_WARNING, "Channel became a zombie before simple switch could be started (%s)\n", chan->name);
      ast_hangup(chan);
      goto quit;
   }
   ast_verb(3, "Starting simple switch on '%s'\n", chan->name);
   idx = dahdi_get_index(chan, p, 1);
   if (idx < 0) {
      ast_log(LOG_WARNING, "Huh?\n");
      ast_hangup(chan);
      goto quit;
   }
   if (p->dsp)
      ast_dsp_digitreset(p->dsp);
   switch (p->sig) {
#ifdef HAVE_PRI
   case SIG_PRI:
   case SIG_BRI:
   case SIG_BRI_PTMP:
      /* Now loop looking for an extension */
      ast_copy_string(exten, p->exten, sizeof(exten));
      len = strlen(exten);
      res = 0;
      while ((len < AST_MAX_EXTENSION-1) && ast_matchmore_extension(chan, chan->context, exten, 1, p->cid_num)) {
         if (len && !ast_ignore_pattern(chan->context, exten))
            tone_zone_play_tone(p->subs[idx].dfd, -1);
         else
            tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALTONE);
         if (ast_exists_extension(chan, chan->context, exten, 1, p->cid_num))
            timeout = matchdigittimeout;
         else
            timeout = gendigittimeout;
         res = ast_waitfordigit(chan, timeout);
         if (res < 0) {
            ast_debug(1, "waitfordigit returned < 0...\n");
            ast_hangup(chan);
            goto quit;
         } else if (res) {
            exten[len++] = res;
            exten[len] = '\0';
         } else
            break;
      }
      /* if no extension was received ('unspecified') on overlap call, use the 's' extension */
      if (ast_strlen_zero(exten)) {
         ast_verb(3, "Going to extension s|1 because of empty extension received on overlap call\n");
         exten[0] = 's';
         exten[1] = '\0';
      }
      tone_zone_play_tone(p->subs[idx].dfd, -1);
      if (ast_exists_extension(chan, chan->context, exten, 1, p->cid_num)) {
         /* Start the real PBX */
         ast_copy_string(chan->exten, exten, sizeof(chan->exten));
         if (p->dsp) {
            ast_dsp_digitreset(p->dsp);
         }
         if (p->pri->overlapdial & DAHDI_OVERLAPDIAL_INCOMING) {
            if (p->pri->pri) {
               if (!pri_grab(p, p->pri)) {
                  pri_proceeding(p->pri->pri, p->call, PVT_TO_CHANNEL(p), 0);
                  p->proceeding = 1;
                  pri_rel(p->pri);
               } else {
                  ast_log(LOG_WARNING, "Unable to grab PRI on span %d\n", p->span);
               }
            }
         }
         dahdi_enable_ec(p);
         ast_setstate(chan, AST_STATE_RING);
         res = ast_pbx_run(chan);
         if (res) {
            ast_log(LOG_WARNING, "PBX exited non-zero!\n");
         }
      } else {
         ast_debug(1, "No such possible extension '%s' in context '%s'\n", exten, chan->context);
         chan->hangupcause = AST_CAUSE_UNALLOCATED;
         ast_hangup(chan);
         p->exten[0] = '\0';
         /* Since we send release complete here, we won't get one */
         p->call = NULL;
      }
      goto quit;
      break;
#endif
   case SIG_FEATD:
   case SIG_FEATDMF:
   case SIG_FEATDMF_TA:
   case SIG_E911:
   case SIG_FGC_CAMAMF:
   case SIG_FEATB:
   case SIG_EMWINK:
   case SIG_SF_FEATD:
   case SIG_SF_FEATDMF:
   case SIG_SF_FEATB:
   case SIG_SFWINK:
      if (dahdi_wink(p, idx))
         goto quit;
      /* Fall through */
   case SIG_EM:
   case SIG_EM_E1:
   case SIG_SF:
   case SIG_FGC_CAMA:
      res = tone_zone_play_tone(p->subs[idx].dfd, -1);
      if (p->dsp)
         ast_dsp_digitreset(p->dsp);
      /* set digit mode appropriately */
      if (p->dsp) {
         if (NEED_MFDETECT(p))
            ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_MF | p->dtmfrelax);
         else
            ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_DTMF | p->dtmfrelax);
      }
      memset(dtmfbuf, 0, sizeof(dtmfbuf));
      /* Wait for the first digit only if immediate=no */
      if (!p->immediate)
         /* Wait for the first digit (up to 5 seconds). */
         res = ast_waitfordigit(chan, 5000);
      else
         res = 0;
      if (res > 0) {
         /* save first char */
         dtmfbuf[0] = res;
         switch (p->sig) {
         case SIG_FEATD:
         case SIG_SF_FEATD:
            res = my_getsigstr(chan, dtmfbuf + 1, "*", 3000);
            if (res > 0)
               res = my_getsigstr(chan, dtmfbuf + strlen(dtmfbuf), "*", 3000);
            if ((res < 1) && (p->dsp)) ast_dsp_digitreset(p->dsp);
            break;
         case SIG_FEATDMF_TA:
            res = my_getsigstr(chan, dtmfbuf + 1, "#", 3000);
            if ((res < 1) && (p->dsp)) ast_dsp_digitreset(p->dsp);
            if (dahdi_wink(p, idx)) goto quit;
            dtmfbuf[0] = 0;
            /* Wait for the first digit (up to 5 seconds). */
            res = ast_waitfordigit(chan, 5000);
            if (res <= 0) break;
            dtmfbuf[0] = res;
            /* fall through intentionally */
         case SIG_FEATDMF:
         case SIG_E911:
         case SIG_FGC_CAMAMF:
         case SIG_SF_FEATDMF:
            res = my_getsigstr(chan, dtmfbuf + 1, "#", 3000);
            /* if international caca, do it again to get real ANO */
            if ((p->sig == SIG_FEATDMF) && (dtmfbuf[1] != '0') && (strlen(dtmfbuf) != 14))
            {
               if (dahdi_wink(p, idx)) goto quit;
               dtmfbuf[0] = 0;
               /* Wait for the first digit (up to 5 seconds). */
               res = ast_waitfordigit(chan, 5000);
               if (res <= 0) break;
               dtmfbuf[0] = res;
               res = my_getsigstr(chan, dtmfbuf + 1, "#", 3000);
            }
            if (res > 0) {
               /* if E911, take off hook */
               if (p->sig == SIG_E911)
                  dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
               res = my_getsigstr(chan, dtmfbuf + strlen(dtmfbuf), "#", 3000);
            }
            if ((res < 1) && (p->dsp)) ast_dsp_digitreset(p->dsp);
            break;
         case SIG_FEATB:
         case SIG_SF_FEATB:
            res = my_getsigstr(chan, dtmfbuf + 1, "#", 3000);
            if ((res < 1) && (p->dsp)) ast_dsp_digitreset(p->dsp);
            break;
         case SIG_EMWINK:
            /* if we received a '*', we are actually receiving Feature Group D
               dial syntax, so use that mode; otherwise, fall through to normal
               mode
            */
            if (res == '*') {
               res = my_getsigstr(chan, dtmfbuf + 1, "*", 3000);
               if (res > 0)
                  res = my_getsigstr(chan, dtmfbuf + strlen(dtmfbuf), "*", 3000);
               if ((res < 1) && (p->dsp)) ast_dsp_digitreset(p->dsp);
               break;
            }
         default:
            /* If we got the first digit, get the rest */
            len = 1;
            dtmfbuf[len] = '\0';
            while ((len < AST_MAX_EXTENSION-1) && ast_matchmore_extension(chan, chan->context, dtmfbuf, 1, p->cid_num)) {
               if (ast_exists_extension(chan, chan->context, dtmfbuf, 1, p->cid_num)) {
                  timeout = matchdigittimeout;
               } else {
                  timeout = gendigittimeout;
               }
               res = ast_waitfordigit(chan, timeout);
               if (res < 0) {
                  ast_debug(1, "waitfordigit returned < 0...\n");
                  ast_hangup(chan);
                  goto quit;
               } else if (res) {
                  dtmfbuf[len++] = res;
                  dtmfbuf[len] = '\0';
               } else {
                  break;
               }
            }
            break;
         }
      }
      if (res == -1) {
         ast_log(LOG_WARNING, "getdtmf on channel %d: %s\n", p->channel, strerror(errno));
         ast_hangup(chan);
         goto quit;
      } else if (res < 0) {
         ast_debug(1, "Got hung up before digits finished\n");
         ast_hangup(chan);
         goto quit;
      }
      if (p->sig == SIG_FGC_CAMA) {
         char anibuf[100];
         if (ast_safe_sleep(chan,1000) == -1) {
            ast_hangup(chan);
            goto quit;
         }
         dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
         ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_MF | p->dtmfrelax);
         res = my_getsigstr(chan, anibuf, "#", 10000);
         if ((res > 0) && (strlen(anibuf) > 2)) {
            if (anibuf[strlen(anibuf) - 1] == '#')
               anibuf[strlen(anibuf) - 1] = 0;
            ast_set_callerid(chan, anibuf + 2, NULL, anibuf + 2);
         }
         ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_DTMF | p->dtmfrelax);
      }
      ast_copy_string(exten, dtmfbuf, sizeof(exten));
      if (ast_strlen_zero(exten))
         ast_copy_string(exten, "s", sizeof(exten));
      if (p->sig == SIG_FEATD || p->sig == SIG_EMWINK) {
         /* Look for Feature Group D on all E&M Wink and Feature Group D trunks */
         if (exten[0] == '*') {
            char *stringp=NULL;
            ast_copy_string(exten2, exten, sizeof(exten2));
            /* Parse out extension and callerid */
            stringp=exten2 +1;
            s1 = strsep(&stringp, "*");
            s2 = strsep(&stringp, "*");
            if (s2) {
               if (!ast_strlen_zero(p->cid_num))
                  ast_set_callerid(chan, p->cid_num, NULL, p->cid_num);
               else
                  ast_set_callerid(chan, s1, NULL, s1);
               ast_copy_string(exten, s2, sizeof(exten));
            } else
               ast_copy_string(exten, s1, sizeof(exten));
         } else if (p->sig == SIG_FEATD)
            ast_log(LOG_WARNING, "Got a non-Feature Group D input on channel %d.  Assuming E&M Wink instead\n", p->channel);
      }
      if ((p->sig == SIG_FEATDMF) || (p->sig == SIG_FEATDMF_TA)) {
         if (exten[0] == '*') {
            char *stringp=NULL;
            ast_copy_string(exten2, exten, sizeof(exten2));
            /* Parse out extension and callerid */
            stringp=exten2 +1;
            s1 = strsep(&stringp, "#");
            s2 = strsep(&stringp, "#");
            if (s2) {
               if (!ast_strlen_zero(p->cid_num))
                  ast_set_callerid(chan, p->cid_num, NULL, p->cid_num);
               else
                  if (*(s1 + 2))
                     ast_set_callerid(chan, s1 + 2, NULL, s1 + 2);
               ast_copy_string(exten, s2 + 1, sizeof(exten));
            } else
               ast_copy_string(exten, s1 + 2, sizeof(exten));
         } else
            ast_log(LOG_WARNING, "Got a non-Feature Group D input on channel %d.  Assuming E&M Wink instead\n", p->channel);
      }
      if ((p->sig == SIG_E911) || (p->sig == SIG_FGC_CAMAMF)) {
         if (exten[0] == '*') {
            char *stringp=NULL;
            ast_copy_string(exten2, exten, sizeof(exten2));
            /* Parse out extension and callerid */
            stringp=exten2 +1;
            s1 = strsep(&stringp, "#");
            s2 = strsep(&stringp, "#");
            if (s2 && (*(s2 + 1) == '0')) {
               if (*(s2 + 2))
                  ast_set_callerid(chan, s2 + 2, NULL, s2 + 2);
            }
            if (s1)  ast_copy_string(exten, s1, sizeof(exten));
            else ast_copy_string(exten, "911", sizeof(exten));
         } else
            ast_log(LOG_WARNING, "Got a non-E911/FGC CAMA input on channel %d.  Assuming E&M Wink instead\n", p->channel);
      }
      if (p->sig == SIG_FEATB) {
         if (exten[0] == '*') {
            char *stringp=NULL;
            ast_copy_string(exten2, exten, sizeof(exten2));
            /* Parse out extension and callerid */
            stringp=exten2 +1;
            s1 = strsep(&stringp, "#");
            ast_copy_string(exten, exten2 + 1, sizeof(exten));
         } else
            ast_log(LOG_WARNING, "Got a non-Feature Group B input on channel %d.  Assuming E&M Wink instead\n", p->channel);
      }
      if ((p->sig == SIG_FEATDMF) || (p->sig == SIG_FEATDMF_TA)) {
         dahdi_wink(p, idx);
         /* some switches require a minimum guard time between
            the last FGD wink and something that answers
            immediately. This ensures it */
         if (ast_safe_sleep(chan,100)) goto quit;
      }
      dahdi_enable_ec(p);
      if (NEED_MFDETECT(p)) {
         if (p->dsp) {
            if (!p->hardwaredtmf)
               ast_dsp_set_digitmode(p->dsp, DSP_DIGITMODE_DTMF | p->dtmfrelax);
            else {
               ast_dsp_free(p->dsp);
               p->dsp = NULL;
            }
         }
      }
      if (ast_exists_extension(chan, chan->context, exten, 1, chan->cid.cid_num)) {
         ast_copy_string(chan->exten, exten, sizeof(chan->exten));
         if (p->dsp) ast_dsp_digitreset(p->dsp);
         res = ast_pbx_run(chan);
         if (res) {
            ast_log(LOG_WARNING, "PBX exited non-zero\n");
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
         }
         goto quit;
      } else {
         ast_verb(2, "Unknown extension '%s' in context '%s' requested\n", exten, chan->context);
         sleep(2);
         res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_INFO);
         if (res < 0)
            ast_log(LOG_WARNING, "Unable to start special tone on %d\n", p->channel);
         else
            sleep(1);
         res = ast_streamfile(chan, "ss-noservice", chan->language);
         if (res >= 0)
            ast_waitstream(chan, "");
         res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
         ast_hangup(chan);
         goto quit;
      }
      break;
   case SIG_FXOLS:
   case SIG_FXOGS:
   case SIG_FXOKS:
      /* Read the first digit */
      timeout = firstdigittimeout;
      /* If starting a threeway call, never timeout on the first digit so someone
         can use flash-hook as a "hold" feature */
      if (p->subs[SUB_THREEWAY].owner)
         timeout = 999999;
      while (len < AST_MAX_EXTENSION-1) {
         /* Read digit unless it's supposed to be immediate, in which case the
            only answer is 's' */
         if (p->immediate)
            res = 's';
         else
            res = ast_waitfordigit(chan, timeout);
         timeout = 0;
         if (res < 0) {
            ast_debug(1, "waitfordigit returned < 0...\n");
            res = tone_zone_play_tone(p->subs[idx].dfd, -1);
            ast_hangup(chan);
            goto quit;
         } else if (res) {
            ast_debug(1,"waitfordigit returned '%c' (%d), timeout = %d\n", res, res, timeout);
            exten[len++]=res;
            exten[len] = '\0';
         }
         if (!ast_ignore_pattern(chan->context, exten))
            tone_zone_play_tone(p->subs[idx].dfd, -1);
         else
            tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALTONE);
         if (ast_exists_extension(chan, chan->context, exten, 1, p->cid_num) && strcmp(exten, ast_parking_ext())) {
            if (!res || !ast_matchmore_extension(chan, chan->context, exten, 1, p->cid_num)) {
               if (getforward) {
                  /* Record this as the forwarding extension */
                  ast_copy_string(p->call_forward, exten, sizeof(p->call_forward));
                  ast_verb(3, "Setting call forward to '%s' on channel %d\n", p->call_forward, p->channel);
                  res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
                  if (res)
                     break;
                  usleep(500000);
                  res = tone_zone_play_tone(p->subs[idx].dfd, -1);
                  sleep(1);
                  memset(exten, 0, sizeof(exten));
                  res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALTONE);
                  len = 0;
                  getforward = 0;
               } else {
                  res = tone_zone_play_tone(p->subs[idx].dfd, -1);
                  ast_copy_string(chan->exten, exten, sizeof(chan->exten));
                  if (!ast_strlen_zero(p->cid_num)) {
                     if (!p->hidecallerid)
                        ast_set_callerid(chan, p->cid_num, NULL, p->cid_num);
                     else
                        ast_set_callerid(chan, NULL, NULL, p->cid_num);
                  }
                  if (!ast_strlen_zero(p->cid_name)) {
                     if (!p->hidecallerid)
                        ast_set_callerid(chan, NULL, p->cid_name, NULL);
                  }
                  ast_setstate(chan, AST_STATE_RING);
                  dahdi_enable_ec(p);
                  res = ast_pbx_run(chan);
                  if (res) {
                     ast_log(LOG_WARNING, "PBX exited non-zero\n");
                     res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
                  }
                  goto quit;
               }
            } else {
               /* It's a match, but they just typed a digit, and there is an ambiguous match,
                  so just set the timeout to matchdigittimeout and wait some more */
               timeout = matchdigittimeout;
            }
         } else if (res == 0) {
            ast_debug(1, "not enough digits (and no ambiguous match)...\n");
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
            dahdi_wait_event(p->subs[idx].dfd);
            ast_hangup(chan);
            goto quit;
         } else if (p->callwaiting && !strcmp(exten, "*70")) {
            ast_verb(3, "Disabling call waiting on %s\n", chan->name);
            /* Disable call waiting if enabled */
            p->callwaiting = 0;
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            if (res) {
               ast_log(LOG_WARNING, "Unable to do dial recall on channel %s: %s\n",
                  chan->name, strerror(errno));
            }
            len = 0;
            ioctl(p->subs[idx].dfd,DAHDI_CONFDIAG,&len);
            memset(exten, 0, sizeof(exten));
            timeout = firstdigittimeout;
         } else if (!strcmp(exten,ast_pickup_ext())) {
            /* Scan all channels and see if there are any
             * ringing channels that have call groups
             * that equal this channels pickup group
             */
            if (idx == SUB_REAL) {
               /* Switch us from Third call to Call Wait */
               if (p->subs[SUB_THREEWAY].owner) {
                  /* If you make a threeway call and the *8# a call, it should actually
                     look like a callwait */
                  alloc_sub(p, SUB_CALLWAIT);
                  swap_subs(p, SUB_CALLWAIT, SUB_THREEWAY);
                  unalloc_sub(p, SUB_THREEWAY);
               }
               dahdi_enable_ec(p);
               if (ast_pickup_call(chan)) {
                  ast_debug(1, "No call pickup possible...\n");
                  res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
                  dahdi_wait_event(p->subs[idx].dfd);
               }
               ast_hangup(chan);
               goto quit;
            } else {
               ast_log(LOG_WARNING, "Huh?  Got *8# on call not on real\n");
               ast_hangup(chan);
               goto quit;
            }
         } else if (!p->hidecallerid && !strcmp(exten, "*67")) {
            ast_verb(3, "Disabling Caller*ID on %s\n", chan->name);
            /* Disable Caller*ID if enabled */
            p->hidecallerid = 1;
            if (chan->cid.cid_num)
               ast_free(chan->cid.cid_num);
            chan->cid.cid_num = NULL;
            if (chan->cid.cid_name)
               ast_free(chan->cid.cid_name);
            chan->cid.cid_name = NULL;
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            if (res) {
               ast_log(LOG_WARNING, "Unable to do dial recall on channel %s: %s\n",
                  chan->name, strerror(errno));
            }
            len = 0;
            memset(exten, 0, sizeof(exten));
            timeout = firstdigittimeout;
         } else if (p->callreturn && !strcmp(exten, "*69")) {
            res = 0;
            if (!ast_strlen_zero(p->lastcid_num)) {
               res = ast_say_digit_str(chan, p->lastcid_num, "", chan->language);
            }
            if (!res)
               res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            break;
         } else if (!strcmp(exten, "*78")) {
            dahdi_dnd(p, 1);
            /* Do not disturb */
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            getforward = 0;
            memset(exten, 0, sizeof(exten));
            len = 0;
         } else if (!strcmp(exten, "*79")) {
            dahdi_dnd(p, 0);
            /* Do not disturb */
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            getforward = 0;
            memset(exten, 0, sizeof(exten));
            len = 0;
         } else if (p->cancallforward && !strcmp(exten, "*72")) {
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            getforward = 1;
            memset(exten, 0, sizeof(exten));
            len = 0;
         } else if (p->cancallforward && !strcmp(exten, "*73")) {
            ast_verb(3, "Cancelling call forwarding on channel %d\n", p->channel);
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            memset(p->call_forward, 0, sizeof(p->call_forward));
            getforward = 0;
            memset(exten, 0, sizeof(exten));
            len = 0;
         } else if ((p->transfer || p->canpark) && !strcmp(exten, ast_parking_ext()) &&
                  p->subs[SUB_THREEWAY].owner &&
                  ast_bridged_channel(p->subs[SUB_THREEWAY].owner)) {
            /* This is a three way call, the main call being a real channel,
               and we're parking the first call. */
            ast_masq_park_call(ast_bridged_channel(p->subs[SUB_THREEWAY].owner), chan, 0, NULL);
            ast_verb(3, "Parking call to '%s'\n", chan->name);
            break;
         } else if (!ast_strlen_zero(p->lastcid_num) && !strcmp(exten, "*60")) {
            ast_verb(3, "Blacklisting number %s\n", p->lastcid_num);
            res = ast_db_put("blacklist", p->lastcid_num, "1");
            if (!res) {
               res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
               memset(exten, 0, sizeof(exten));
               len = 0;
            }
         } else if (p->hidecallerid && !strcmp(exten, "*82")) {
            ast_verb(3, "Enabling Caller*ID on %s\n", chan->name);
            /* Enable Caller*ID if enabled */
            p->hidecallerid = 0;
            if (chan->cid.cid_num)
               ast_free(chan->cid.cid_num);
            chan->cid.cid_num = NULL;
            if (chan->cid.cid_name)
               ast_free(chan->cid.cid_name);
            chan->cid.cid_name = NULL;
            ast_set_callerid(chan, p->cid_num, p->cid_name, NULL);
            res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_DIALRECALL);
            if (res) {
               ast_log(LOG_WARNING, "Unable to do dial recall on channel %s: %s\n",
                  chan->name, strerror(errno));
            }
            len = 0;
            memset(exten, 0, sizeof(exten));
            timeout = firstdigittimeout;
         } else if (!strcmp(exten, "*0")) {
            struct ast_channel *nbridge =
               p->subs[SUB_THREEWAY].owner;
            struct dahdi_pvt *pbridge = NULL;
            /* set up the private struct of the bridged one, if any */
            if (nbridge && ast_bridged_channel(nbridge))
               pbridge = ast_bridged_channel(nbridge)->tech_pvt;
            if (nbridge && pbridge &&
               (nbridge->tech == &dahdi_tech) &&
               (ast_bridged_channel(nbridge)->tech == &dahdi_tech) &&
               ISTRUNK(pbridge)) {
               int func = DAHDI_FLASH;
               /* Clear out the dial buffer */
               p->dop.dialstr[0] = '\0';
               /* flash hookswitch */
               if ((ioctl(pbridge->subs[SUB_REAL].dfd,DAHDI_HOOK,&func) == -1) && (errno != EINPROGRESS)) {
                  ast_log(LOG_WARNING, "Unable to flash external trunk on channel %s: %s\n",
                     nbridge->name, strerror(errno));
               }
               swap_subs(p, SUB_REAL, SUB_THREEWAY);
               unalloc_sub(p, SUB_THREEWAY);
               p->owner = p->subs[SUB_REAL].owner;
               if (ast_bridged_channel(p->subs[SUB_REAL].owner))
                  ast_queue_control(p->subs[SUB_REAL].owner, AST_CONTROL_UNHOLD);
               ast_hangup(chan);
               goto quit;
            } else {
               tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
               dahdi_wait_event(p->subs[idx].dfd);
               tone_zone_play_tone(p->subs[idx].dfd, -1);
               swap_subs(p, SUB_REAL, SUB_THREEWAY);
               unalloc_sub(p, SUB_THREEWAY);
               p->owner = p->subs[SUB_REAL].owner;
               ast_hangup(chan);
               goto quit;
            }
         } else if (!ast_canmatch_extension(chan, chan->context, exten, 1, chan->cid.cid_num) &&
                     ((exten[0] != '*') || (strlen(exten) > 2))) {
            ast_debug(1, "Can't match %s from '%s' in context %s\n", exten, chan->cid.cid_num ? chan->cid.cid_num : "<Unknown Caller>", chan->context);
            break;
         }
         if (!timeout)
            timeout = gendigittimeout;
         if (len && !ast_ignore_pattern(chan->context, exten))
            tone_zone_play_tone(p->subs[idx].dfd, -1);
      }
      break;
   case SIG_FXSLS:
   case SIG_FXSGS:
   case SIG_FXSKS:
#ifdef HAVE_PRI
      if (p->pri) {
         /* This is a GR-303 trunk actually.  Wait for the first ring... */
         struct ast_frame *f;
         int res;
         time_t start;
         time(&start);
         ast_setstate(chan, AST_STATE_RING);
         while (time(NULL) < start + 3) {
            res = ast_waitfor(chan, 1000);
            if (res) {
               f = ast_read(chan);
               if (!f) {
                  ast_log(LOG_WARNING, "Whoa, hangup while waiting for first ring!\n");
                  ast_hangup(chan);
                  goto quit;
               } else if ((f->frametype == AST_FRAME_CONTROL) && (f->subclass == AST_CONTROL_RING)) {
                  res = 1;
               } else
                  res = 0;
               ast_frfree(f);
               if (res) {
                  ast_debug(1, "Got ring!\n");
                  res = 0;
                  break;
               }
            }
         }
      }
#endif
      /* check for SMDI messages */
      if (p->use_smdi && p->smdi_iface) {
         smdi_msg = ast_smdi_md_message_wait(p->smdi_iface, SMDI_MD_WAIT_TIMEOUT);
         if (smdi_msg != NULL) {
            ast_copy_string(chan->exten, smdi_msg->fwd_st, sizeof(chan->exten));
            if (smdi_msg->type == 'B')
               pbx_builtin_setvar_helper(chan, "_SMDI_VM_TYPE", "b");
            else if (smdi_msg->type == 'N')
               pbx_builtin_setvar_helper(chan, "_SMDI_VM_TYPE", "u");
            ast_debug(1, "Received SMDI message on %s\n", chan->name);
         } else {
            ast_log(LOG_WARNING, "SMDI enabled but no SMDI message present\n");
         }
      }
      if (p->use_callerid && (p->cid_signalling == CID_SIG_SMDI && smdi_msg)) {
         number = smdi_msg->calling_st;
      /* If we want caller id, we're in a prering state due to a polarity reversal
       * and we're set to use a polarity reversal to trigger the start of caller id,
       * grab the caller id and wait for ringing to start... */
      } else if (p->use_callerid && (chan->_state == AST_STATE_PRERING && (p->cid_start == CID_START_POLARITY || p->cid_start == CID_START_POLARITY_IN))) {
         /* If set to use DTMF CID signalling, listen for DTMF */
         if (p->cid_signalling == CID_SIG_DTMF) {
            int k = 0;
            cs = NULL;
            ast_debug(1, "Receiving DTMF cid on "
               "channel %s\n", chan->name);
            dahdi_setlinear(p->subs[idx].dfd, 0);
            res = 2000;
            for (;;) {
               struct ast_frame *f;
               res = ast_waitfor(chan, res);
               if (res <= 0) {
                  ast_log(LOG_WARNING, "DTMFCID timed out waiting for ring. "
                     "Exiting simple switch\n");
                  ast_hangup(chan);
                  goto quit;
               }
               f = ast_read(chan);
               if (!f)
                  break;
               if (f->frametype == AST_FRAME_DTMF) {
                  dtmfbuf[k++] = f->subclass;
                  ast_debug(1, "CID got digit '%c'\n", f->subclass);
                  res = 2000;
               }
               ast_frfree(f);
               if (chan->_state == AST_STATE_RING ||
                  chan->_state == AST_STATE_RINGING)
                  break; /* Got ring */
            }
            dtmfbuf[k] = '\0';
            dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
            /* Got cid and ring. */
            ast_debug(1, "CID got string '%s'\n", dtmfbuf);
            callerid_get_dtmf(dtmfbuf, dtmfcid, &flags);
            ast_debug(1, "CID is '%s', flags %d\n",
               dtmfcid, flags);
            /* If first byte is NULL, we have no cid */
            if (!ast_strlen_zero(dtmfcid))
               number = dtmfcid;
            else
               number = NULL;
         /* If set to use V23 Signalling, launch our FSK gubbins and listen for it */
         } else if ((p->cid_signalling == CID_SIG_V23) || (p->cid_signalling == CID_SIG_V23_JP)) {
            cs = callerid_new(p->cid_signalling);
            if (cs) {
               samples = 0;
#if 1
               bump_gains(p);
#endif
               /* Take out of linear mode for Caller*ID processing */
               dahdi_setlinear(p->subs[idx].dfd, 0);
               /* First we wait and listen for the Caller*ID */
               for (;;) {
                  i = DAHDI_IOMUX_READ | DAHDI_IOMUX_SIGEVENT;
                  if ((res = ioctl(p->subs[idx].dfd, DAHDI_IOMUX, &i))) {
                     ast_log(LOG_WARNING, "I/O MUX failed: %s\n", strerror(errno));
                     callerid_free(cs);
                     ast_hangup(chan);
                     goto quit;
                  }
                  if (i & DAHDI_IOMUX_SIGEVENT) {
                     res = dahdi_get_event(p->subs[idx].dfd);
                     ast_log(LOG_NOTICE, "Got event %d (%s)...\n", res, event2str(res));
                     if (res == DAHDI_EVENT_NOALARM) {
                        p->inalarm = 0;
                     }
                     if (p->cid_signalling == CID_SIG_V23_JP) {
                        if (res == DAHDI_EVENT_RINGBEGIN) {
                           res = dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_OFFHOOK);
                           usleep(1);
                        }
                     } else {
                        res = 0;
                        break;
                     }
                  } else if (i & DAHDI_IOMUX_READ) {
                     res = read(p->subs[idx].dfd, buf, sizeof(buf));
                     if (res < 0) {
                        if (errno != ELAST) {
                           ast_log(LOG_WARNING, "read returned error: %s\n", strerror(errno));
                           callerid_free(cs);
                           ast_hangup(chan);
                           goto quit;
                        }
                        break;
                     }
                     samples += res;
                     if (p->cid_signalling == CID_SIG_V23_JP) {
                        res = callerid_feed_jp(cs, buf, res, AST_LAW(p));
                     } else {
                        res = callerid_feed(cs, buf, res, AST_LAW(p));
                     }
                     if (res < 0) {
                        ast_log(LOG_WARNING, "CallerID feed failed on channel '%s'\n", chan->name);
                        break;
                     } else if (res)
                        break;
                     else if (samples > (8000 * 10))
                        break;
                  }
               }
               if (res == 1) {
                  callerid_get(cs, &name, &number, &flags);
                  ast_log(LOG_NOTICE, "CallerID number: %s, name: %s, flags=%d\n", number, name, flags);
               }
               if (p->cid_signalling == CID_SIG_V23_JP) {
                  res = dahdi_set_hook(p->subs[SUB_REAL].dfd, DAHDI_ONHOOK);
                  usleep(1);
                  res = 4000;
               } else {
                  /* Finished with Caller*ID, now wait for a ring to make sure there really is a call coming */
                  res = 2000;
               }
               for (;;) {
                  struct ast_frame *f;
                  res = ast_waitfor(chan, res);
                  if (res <= 0) {
                     ast_log(LOG_WARNING, "CID timed out waiting for ring. "
                        "Exiting simple switch\n");
                     ast_hangup(chan);
                     goto quit;
                  }
                  if (!(f = ast_read(chan))) {
                     ast_log(LOG_WARNING, "Hangup received waiting for ring. Exiting simple switch\n");
                     ast_hangup(chan);
                     goto quit;
                  }
                  ast_frfree(f);
                  if (chan->_state == AST_STATE_RING ||
                     chan->_state == AST_STATE_RINGING)
                     break; /* Got ring */
               }
               /* We must have a ring by now, so, if configured, lets try to listen for
                * distinctive ringing */
               if (p->usedistinctiveringdetection) {
                  len = 0;
                  distMatches = 0;
                  /* Clear the current ring data array so we dont have old data in it. */
                  for (receivedRingT = 0; receivedRingT < ARRAY_LEN(curRingData); receivedRingT++)
                     curRingData[receivedRingT] = 0;
                  receivedRingT = 0;
                  counter = 0;
                  counter1 = 0;
                  /* Check to see if context is what it should be, if not set to be. */
                  if (strcmp(p->context,p->defcontext) != 0) {
                     ast_copy_string(p->context, p->defcontext, sizeof(p->context));
                     ast_copy_string(chan->context,p->defcontext,sizeof(chan->context));
                  }
                  for (;;) {
                     i = DAHDI_IOMUX_READ | DAHDI_IOMUX_SIGEVENT;
                     if ((res = ioctl(p->subs[idx].dfd, DAHDI_IOMUX, &i))) {
                        ast_log(LOG_WARNING, "I/O MUX failed: %s\n", strerror(errno));
                        callerid_free(cs);
                        ast_hangup(chan);
                        goto quit;
                     }
                     if (i & DAHDI_IOMUX_SIGEVENT) {
                        res = dahdi_get_event(p->subs[idx].dfd);
                        ast_log(LOG_NOTICE, "Got event %d (%s)...\n", res, event2str(res));
                        if (res == DAHDI_EVENT_NOALARM) {
                           p->inalarm = 0;
                        }
                        res = 0;
                        /* Let us detect distinctive ring */
                        curRingData[receivedRingT] = p->ringt;
                        if (p->ringt < p->ringt_base/2)
                           break;
                        /* Increment the ringT counter so we can match it against
                           values in chan_dahdi.conf for distinctive ring */
                        if (++receivedRingT == ARRAY_LEN(curRingData))
                           break;
                     } else if (i & DAHDI_IOMUX_READ) {
                        res = read(p->subs[idx].dfd, buf, sizeof(buf));
                        if (res < 0) {
                           if (errno != ELAST) {
                              ast_log(LOG_WARNING, "read returned error: %s\n", strerror(errno));
                              callerid_free(cs);
                              ast_hangup(chan);
                              goto quit;
                           }
                           break;
                        }
                        if (p->ringt)
                           p->ringt--;
                        if (p->ringt == 1) {
                           res = -1;
                           break;
                        }
                     }
                  }
                     /* this only shows up if you have n of the dring patterns filled in */
                  ast_verb(3, "Detected ring pattern: %d,%d,%d\n",curRingData[0],curRingData[1],curRingData[2]);
                  for (counter = 0; counter < 3; counter++) {
                     /* Check to see if the rings we received match any of the ones in chan_dahdi.conf for this
                     channel */
                     distMatches = 0;
                     for (counter1 = 0; counter1 < 3; counter1++) {
                        ast_verb(3, "Ring pattern check range: %d\n", p->drings.ringnum[counter].range);
                        if (p->drings.ringnum[counter].ring[counter1] == -1) {
                           ast_verb(3, "Pattern ignore (-1) detected, so matching pattern %d regardless.\n",
                           curRingData[counter1]);
                           distMatches++;
                        } else if (curRingData[counter1] <= (p->drings.ringnum[counter].ring[counter1] + p->drings.ringnum[counter].range) &&
                              curRingData[counter1] >= (p->drings.ringnum[counter].ring[counter1] - p->drings.ringnum[counter].range)) {
                           ast_verb(3, "Ring pattern matched in range: %d to %d\n",
                           (p->drings.ringnum[counter].ring[counter1] - p->drings.ringnum[counter].range),
                           (p->drings.ringnum[counter].ring[counter1] + p->drings.ringnum[counter].range));
                           distMatches++;
                        }
                     }
                     if (distMatches == 3) {
                        /* The ring matches, set the context to whatever is for distinctive ring.. */
                        ast_copy_string(p->context, p->drings.ringContext[counter].contextData, sizeof(p->context));
                        ast_copy_string(chan->context, p->drings.ringContext[counter].contextData, sizeof(chan->context));
                        ast_verb(3, "Distinctive Ring matched context %s\n",p->context);
                        break;
                     }
                  }
               }
               /* Restore linear mode (if appropriate) for Caller*ID processing */
               dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
#if 1
               restore_gains(p);
#endif
            } else
               ast_log(LOG_WARNING, "Unable to get caller ID space\n");
         } else {
            ast_log(LOG_WARNING, "Channel %s in prering "
               "state, but I have nothing to do. "
               "Terminating simple switch, should be "
               "restarted by the actual ring.\n",
               chan->name);
            ast_hangup(chan);
            goto quit;
         }
      } else if (p->use_callerid && p->cid_start == CID_START_RING) {
         if (p->cid_signalling == CID_SIG_DTMF) {
            int k = 0;
            cs = NULL;
            dahdi_setlinear(p->subs[idx].dfd, 0);
            res = 2000;
            for (;;) {
               struct ast_frame *f;
               res = ast_waitfor(chan, res);
               if (res <= 0) {
                  ast_log(LOG_WARNING, "DTMFCID timed out waiting for ring. "
                     "Exiting simple switch\n");
                  ast_hangup(chan);
                  return NULL;
               }
               f = ast_read(chan);
               if (f->frametype == AST_FRAME_DTMF) {
                  dtmfbuf[k++] = f->subclass;
                  ast_log(LOG_DEBUG, "CID got digit '%c'\n", f->subclass);
                  res = 2000;
               }
               ast_frfree(f);
               if (p->ringt_base == p->ringt)
                  break;
            }
            dtmfbuf[k] = '\0';
            dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
            /* Got cid and ring. */
            callerid_get_dtmf(dtmfbuf, dtmfcid, &flags);
            ast_log(LOG_DEBUG, "CID is '%s', flags %d\n",
               dtmfcid, flags);
            /* If first byte is NULL, we have no cid */
            if (!ast_strlen_zero(dtmfcid))
               number = dtmfcid;
            else
               number = NULL;
            /* If set to use V23 Signalling, launch our FSK gubbins and listen for it */
         } else {
            /* FSK Bell202 callerID */
            cs = callerid_new(p->cid_signalling);
            if (cs) {
#if 1
               bump_gains(p);
#endif
               samples = 0;
               len = 0;
               distMatches = 0;
               /* Clear the current ring data array so we dont have old data in it. */
               for (receivedRingT = 0; receivedRingT < ARRAY_LEN(curRingData); receivedRingT++)
                  curRingData[receivedRingT] = 0;
               receivedRingT = 0;
               counter = 0;
               counter1 = 0;
               /* Check to see if context is what it should be, if not set to be. */
               if (strcmp(p->context,p->defcontext) != 0) {
                  ast_copy_string(p->context, p->defcontext, sizeof(p->context));
                  ast_copy_string(chan->context,p->defcontext,sizeof(chan->context));
               }
               /* Take out of linear mode for Caller*ID processing */
               dahdi_setlinear(p->subs[idx].dfd, 0);
               for (;;) {
                  i = DAHDI_IOMUX_READ | DAHDI_IOMUX_SIGEVENT;
                  if ((res = ioctl(p->subs[idx].dfd, DAHDI_IOMUX, &i))) {
                     ast_log(LOG_WARNING, "I/O MUX failed: %s\n", strerror(errno));
                     callerid_free(cs);
                     ast_hangup(chan);
                     goto quit;
                  }
                  if (i & DAHDI_IOMUX_SIGEVENT) {
                     res = dahdi_get_event(p->subs[idx].dfd);
                     ast_log(LOG_NOTICE, "Got event %d (%s)...\n", res, event2str(res));
                     if (res == DAHDI_EVENT_NOALARM) {
                        p->inalarm = 0;
                     }
                     /* If we get a PR event, they hung up while processing calerid */
                     if ( res == DAHDI_EVENT_POLARITY && p->hanguponpolarityswitch && p->polarity == POLARITY_REV) {
                        ast_log(LOG_DEBUG, "Hanging up due to polarity reversal on channel %d while detecting callerid\n", p->channel);
                        p->polarity = POLARITY_IDLE;
                        callerid_free(cs);
                        ast_hangup(chan);
                        goto quit;
                     }
                     res = 0;
                     /* Let us detect callerid when the telco uses distinctive ring */
                     curRingData[receivedRingT] = p->ringt;
                     if (p->ringt < p->ringt_base/2)
                        break;
                     /* Increment the ringT counter so we can match it against
                        values in chan_dahdi.conf for distinctive ring */
                     if (++receivedRingT == ARRAY_LEN(curRingData))
                        break;
                  } else if (i & DAHDI_IOMUX_READ) {
                     res = read(p->subs[idx].dfd, buf, sizeof(buf));
                     if (res < 0) {
                        if (errno != ELAST) {
                           ast_log(LOG_WARNING, "read returned error: %s\n", strerror(errno));
                           callerid_free(cs);
                           ast_hangup(chan);
                           goto quit;
                        }
                        break;
                     }
                     if (p->ringt)
                        p->ringt--;
                     if (p->ringt == 1) {
                        res = -1;
                        break;
                     }
                     samples += res;
                     res = callerid_feed(cs, buf, res, AST_LAW(p));
                     if (res < 0) {
                        ast_log(LOG_WARNING, "CallerID feed failed: %s\n", strerror(errno));
                        break;
                     } else if (res)
                        break;
                     else if (samples > (8000 * 10))
                        break;
                  }
               }
               if (res == 1) {
                  callerid_get(cs, &name, &number, &flags);
                  ast_debug(1, "CallerID number: %s, name: %s, flags=%d\n", number, name, flags);
               }
               if (distinctiveringaftercid == 1) {
                  /* Clear the current ring data array so we dont have old data in it. */
                  for (receivedRingT = 0; receivedRingT < 3; receivedRingT++) {
                     curRingData[receivedRingT] = 0;
                  }
                  receivedRingT = 0;
                  ast_verb(3, "Detecting post-CID distinctive ring\n");
                  for (;;) {
                     i = DAHDI_IOMUX_READ | DAHDI_IOMUX_SIGEVENT;
                     if ((res = ioctl(p->subs[idx].dfd, DAHDI_IOMUX, &i))) {
                        ast_log(LOG_WARNING, "I/O MUX failed: %s\n", strerror(errno));
                        callerid_free(cs);
                        ast_hangup(chan);
                        goto quit;
                     }
                     if (i & DAHDI_IOMUX_SIGEVENT) {
                        res = dahdi_get_event(p->subs[idx].dfd);
                        ast_log(LOG_NOTICE, "Got event %d (%s)...\n", res, event2str(res));
                        if (res == DAHDI_EVENT_NOALARM) {
                           p->inalarm = 0;
                        }
                        res = 0;
                        /* Let us detect callerid when the telco uses distinctive ring */
                        curRingData[receivedRingT] = p->ringt;
                        if (p->ringt < p->ringt_base/2)
                           break;
                        /* Increment the ringT counter so we can match it against
                           values in chan_dahdi.conf for distinctive ring */
                        if (++receivedRingT == ARRAY_LEN(curRingData))
                           break;
                     } else if (i & DAHDI_IOMUX_READ) {
                        res = read(p->subs[idx].dfd, buf, sizeof(buf));
                        if (res < 0) {
                           if (errno != ELAST) {
                              ast_log(LOG_WARNING, "read returned error: %s\n", strerror(errno));
                              callerid_free(cs);
                              ast_hangup(chan);
                              goto quit;
                           }
                           break;
                        }
                     if (p->ringt)
                        p->ringt--;
                        if (p->ringt == 1) {
                           res = -1;
                           break;
                        }
                     }
                  }
               }
               if (p->usedistinctiveringdetection) {
                  /* this only shows up if you have n of the dring patterns filled in */
                  ast_verb(3, "Detected ring pattern: %d,%d,%d\n",curRingData[0],curRingData[1],curRingData[2]);
                  for (counter = 0; counter < 3; counter++) {
                     /* Check to see if the rings we received match any of the ones in chan_dahdi.conf for this
                     channel */
                     /* this only shows up if you have n of the dring patterns filled in */
                     ast_verb(3, "Checking %d,%d,%d\n",
                           p->drings.ringnum[counter].ring[0],
                           p->drings.ringnum[counter].ring[1],
                           p->drings.ringnum[counter].ring[2]);
                     distMatches = 0;
                     for (counter1 = 0; counter1 < 3; counter1++) {
                        ast_verb(3, "Ring pattern check range: %d\n", p->drings.ringnum[counter].range);
                        if (p->drings.ringnum[counter].ring[counter1] == -1) {
                           ast_verb(3, "Pattern ignore (-1) detected, so matching pattern %d regardless.\n",
                           curRingData[counter1]);
                           distMatches++;
                        }
                        else if (curRingData[counter1] <= (p->drings.ringnum[counter].ring[counter1] + p->drings.ringnum[counter].range) &&
                           curRingData[counter1] >= (p->drings.ringnum[counter].ring[counter1] - p->drings.ringnum[counter].range)) {
                           ast_verb(3, "Ring pattern matched in range: %d to %d\n",
                           (p->drings.ringnum[counter].ring[counter1] - p->drings.ringnum[counter].range),
                           (p->drings.ringnum[counter].ring[counter1] + p->drings.ringnum[counter].range));
                           distMatches++;
                        }
                     }
                     if (distMatches == 3) {
                        /* The ring matches, set the context to whatever is for distinctive ring.. */
                        ast_copy_string(p->context, p->drings.ringContext[counter].contextData, sizeof(p->context));
                        ast_copy_string(chan->context, p->drings.ringContext[counter].contextData, sizeof(chan->context));
                        ast_verb(3, "Distinctive Ring matched context %s\n",p->context);
                        break;
                     }
                  }
               }
               /* Restore linear mode (if appropriate) for Caller*ID processing */
               dahdi_setlinear(p->subs[idx].dfd, p->subs[idx].linear);
#if 1
               restore_gains(p);
#endif
               if (res < 0) {
                  ast_log(LOG_WARNING, "CallerID returned with error on channel '%s'\n", chan->name);
               }
            } else
               ast_log(LOG_WARNING, "Unable to get caller ID space\n");
         }
      } else
         cs = NULL;
      if (number)
         ast_shrink_phone_number(number);
      ast_set_callerid(chan, number, name, number);
      if (smdi_msg)
         ASTOBJ_UNREF(smdi_msg, ast_smdi_md_message_destroy);
      if (cs)
         callerid_free(cs);
      /* If the CID had Message waiting payload, assume that this for MWI only and hangup the call */
      if (flags & CID_MSGWAITING) {
         ast_log(LOG_NOTICE, "MWI: Channel %d message waiting!\n", p->channel);
         notify_message(p->mailbox, 1);
         /* If generated using Ring Pulse Alert, then ring has been answered as a call and needs to be hungup */
         if (p->mwimonitor_rpas) {
            ast_hangup(chan);
            return NULL;
         }
      } else if (flags & CID_NOMSGWAITING) {
         ast_log(LOG_NOTICE, "MWI: Channel %d no message waiting!\n", p->channel);
         notify_message(p->mailbox, 0);
         /* If generated using Ring Pulse Alert, then ring has been answered as a call and needs to be hungup */
         if (p->mwimonitor_rpas) {
            ast_hangup(chan);
            return NULL;
         }
      }
      ast_setstate(chan, AST_STATE_RING);
      chan->rings = 1;
      p->ringt = p->ringt_base;
      res = ast_pbx_run(chan);
      if (res) {
         ast_hangup(chan);
         ast_log(LOG_WARNING, "PBX exited non-zero\n");
      }
      goto quit;
   default:
      ast_log(LOG_WARNING, "Don't know how to handle simple switch with signalling %s on channel %d\n", sig2str(p->sig), p->channel);
      res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
      if (res < 0)
            ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", p->channel);
   }
   res = tone_zone_play_tone(p->subs[idx].dfd, DAHDI_TONE_CONGESTION);
   if (res < 0)
         ast_log(LOG_WARNING, "Unable to play congestion tone on channel %d\n", p->channel);
   ast_hangup(chan);
quit:
   ast_mutex_lock(&ss_thread_lock);
   ss_thread_count--;
   ast_cond_signal(&ss_thread_complete);
   ast_mutex_unlock(&ss_thread_lock);
   return NULL;
}
static void swap_subs (struct dahdi_pvt * p, int a, int b) [static]
Definition at line 2062 of file chan_dahdi.c.
References ast_channel_set_fd(), ast_debug, dahdi_subchannel::chan, dahdi_subchannel::dfd, dahdi_subchannel::inthreeway, dahdi_subchannel::owner, dahdi_pvt::subs, and wakeup_sub().
Referenced by attempt_transfer(), dahdi_answer(), dahdi_handle_event(), dahdi_hangup(), and ss_thread().
{
   int tchan;
   int tinthreeway;
   struct ast_channel *towner;
   ast_debug(1, "Swapping %d and %d\n", a, b);
   tchan = p->subs[a].chan;
   towner = p->subs[a].owner;
   tinthreeway = p->subs[a].inthreeway;
   p->subs[a].chan = p->subs[b].chan;
   p->subs[a].owner = p->subs[b].owner;
   p->subs[a].inthreeway = p->subs[b].inthreeway;
   p->subs[b].chan = tchan;
   p->subs[b].owner = towner;
   p->subs[b].inthreeway = tinthreeway;
   if (p->subs[a].owner)
      ast_channel_set_fd(p->subs[a].owner, 0, p->subs[a].dfd);
   if (p->subs[b].owner)
      ast_channel_set_fd(p->subs[b].owner, 0, p->subs[b].dfd);
   wakeup_sub(p, a, NULL);
   wakeup_sub(p, b, NULL);
}
static int unalloc_sub (struct dahdi_pvt * p, int x) [static]
Definition at line 2212 of file chan_dahdi.c.
References ast_debug, ast_log(), dahdi_subchannel::chan, dahdi_pvt::channel, dahdi_subchannel::curconf, dahdi_close_sub(), dahdi_subchannel::inthreeway, dahdi_subchannel::linear, LOG_WARNING, dahdi_subchannel::owner, dahdi_pvt::polarity, POLARITY_IDLE, and dahdi_pvt::subs.
Referenced by attempt_transfer(), dahdi_handle_event(), dahdi_hangup(), and ss_thread().
{
   if (!x) {
      ast_log(LOG_WARNING, "Trying to unalloc the real channel %d?!?\n", p->channel);
      return -1;
   }
   ast_debug(1, "Released sub %d of channel %d\n", x, p->channel);
   dahdi_close_sub(p, x);
   p->subs[x].linear = 0;
   p->subs[x].chan = 0;
   p->subs[x].owner = NULL;
   p->subs[x].inthreeway = 0;
   p->polarity = POLARITY_IDLE;
   memset(&p->subs[x].curconf, 0, sizeof(p->subs[x].curconf));
   return 0;
}
static int unload_module (void) [static]
Definition at line 15932 of file chan_dahdi.c.
References __unload_module(), ast_mutex_destroy(), and lock.
15933 {
15934 #if defined(HAVE_PRI) || defined(HAVE_SS7)
15935    int y;
15936 #endif
15937 #ifdef HAVE_PRI
15938    for (y = 0; y < NUM_SPANS; y++)
15939       ast_mutex_destroy(&pris[y].lock);
15940 #endif
15941 #ifdef HAVE_SS7
15942    for (y = 0; y < NUM_SPANS; y++)
15943       ast_mutex_destroy(&linksets[y].lock);
15944 #endif /* HAVE_SS7 */
15945    return __unload_module();
15946 }
static int update_conf (struct dahdi_pvt * p) [static]
Definition at line 2604 of file chan_dahdi.c.
References ast_debug, dahdi_pvt::channel, conf_add(), conf_del(), dahdi_pvt::confno, dahdi_subchannel::dfd, GET_CHANNEL, dahdi_pvt::inconference, dahdi_subchannel::inthreeway, isslavenative(), dahdi_pvt::master, MAX_SLAVES, dahdi_pvt::slaves, SUB_REAL, and dahdi_pvt::subs.
Referenced by __dahdi_exception(), dahdi_bridge(), dahdi_fixup(), dahdi_handle_event(), dahdi_hangup(), dahdi_unlink(), and mkintf().
{
   int needconf = 0;
   int x;
   int useslavenative;
   struct dahdi_pvt *slave = NULL;
   useslavenative = isslavenative(p, &slave);
   /* Start with the obvious, general stuff */
   for (x = 0; x < 3; x++) {
      /* Look for three way calls */
      if ((p->subs[x].dfd > -1) && p->subs[x].inthreeway) {
         conf_add(p, &p->subs[x], x, 0);
         needconf++;
      } else {
         conf_del(p, &p->subs[x], x);
      }
   }
   /* If we have a slave, add him to our conference now. or DAX
      if this is slave native */
   for (x = 0; x < MAX_SLAVES; x++) {
      if (p->slaves[x]) {
         if (useslavenative)
            conf_add(p, &p->slaves[x]->subs[SUB_REAL], SUB_REAL, GET_CHANNEL(p));
         else {
            conf_add(p, &p->slaves[x]->subs[SUB_REAL], SUB_REAL, 0);
            needconf++;
         }
      }
   }
   /* If we're supposed to be in there, do so now */
   if (p->inconference && !p->subs[SUB_REAL].inthreeway) {
      if (useslavenative)
         conf_add(p, &p->subs[SUB_REAL], SUB_REAL, GET_CHANNEL(slave));
      else {
         conf_add(p, &p->subs[SUB_REAL], SUB_REAL, 0);
         needconf++;
      }
   }
   /* If we have a master, add ourselves to his conference */
   if (p->master) {
      if (isslavenative(p->master, NULL)) {
         conf_add(p->master, &p->subs[SUB_REAL], SUB_REAL, GET_CHANNEL(p->master));
      } else {
         conf_add(p->master, &p->subs[SUB_REAL], SUB_REAL, 0);
      }
   }
   if (!needconf) {
      /* Nobody is left (or should be left) in our conference.
         Kill it. */
      p->confno = -1;
   }
   ast_debug(1, "Updated conferencing on %d, with %d conference users\n", p->channel, needconf);
   return 0;
}
static void wakeup_sub (struct dahdi_pvt * p, int a, struct dahdi_pri * pri) [static]
Definition at line 1520 of file chan_dahdi.c.
References ast_channel_trylock, ast_channel_unlock, ast_mutex_lock(), ast_mutex_unlock(), ast_null_frame, ast_queue_frame(), DEADLOCK_AVOIDANCE, dahdi_pvt::lock, dahdi_subchannel::owner, and dahdi_pvt::subs.
Referenced by swap_subs().
{
#ifdef HAVE_PRI
   if (pri)
      ast_mutex_unlock(&pri->lock);
#endif
   for (;;) {
      if (p->subs[a].owner) {
         if (ast_channel_trylock(p->subs[a].owner)) {
            DEADLOCK_AVOIDANCE(&p->lock);
         } else {
            ast_queue_frame(p->subs[a].owner, &ast_null_frame);
            ast_channel_unlock(p->subs[a].owner);
            break;
         }
      } else
         break;
   }
#ifdef HAVE_PRI
   if (pri)
      ast_mutex_lock(&pri->lock);
#endif
}
Variable Documentation
int alarm
Definition at line 2367 of file chan_dahdi.c.
struct { ... } alarms[] [static]
Referenced by alarm2str().
struct dahdi_ring_cadence AS_RP_cadence = {{250, 10000}} [static]
Definition at line 1495 of file chan_dahdi.c.
struct dahdi_ring_cadence cadences[NUM_CADENCE_MAX] [static]
Definition at line 1476 of file chan_dahdi.c.
int cidrings[NUM_CADENCE_MAX] [static]
cidrings says in which pause to transmit the cid information, where the first pause is 1, the second pause is 2 and so on.
Definition at line 1487 of file chan_dahdi.c.
const char config[] = "chan_dahdi.conf" [static]
Definition at line 238 of file chan_dahdi.c.
struct ast_cli_entry dahdi_cli[] [static]
Definition at line 15169 of file chan_dahdi.c.
struct ast_channel_tech dahdi_tech [static]
Definition at line 1401 of file chan_dahdi.c.
struct ast_jb_conf default_jbconf [static]
Global jitterbuffer configuration - by default, jb is disabled
Definition at line 173 of file chan_dahdi.c.
char defaultcic[64] = "" [static]
Definition at line 296 of file chan_dahdi.c.
char defaultozz[64] = "" [static]
Definition at line 297 of file chan_dahdi.c.
int distinctiveringaftercid = 0 [static]
Definition at line 310 of file chan_dahdi.c.
char* events[] [static]
Definition at line 2344 of file chan_dahdi.c.
int firstdigittimeout = 16000 [static]
Wait up to 16 seconds for first digit (FXO logic).
Definition at line 326 of file chan_dahdi.c.
Referenced by disa_exec().
int gendigittimeout = 8000 [static]
How long to wait for following digits (FXO logic).
Definition at line 329 of file chan_dahdi.c.
struct ast_jb_conf global_jbconf [static]
Definition at line 181 of file chan_dahdi.c.
Referenced by dahdi_new(), process_dahdi(), and setup_dahdi().
int ifcount = 0 [static]
Definition at line 342 of file chan_dahdi.c.
struct dahdi_pvt * ifend [static]
struct dahdi_pvt * iflist [static]
Referenced by __unload_module(), action_dahdishowchannels(), dahdi_destroy_channel_bynum(), dahdi_hangup(), dahdi_request(), dahdi_restart(), dahdi_set_dnd(), dahdi_set_hwgain(), dahdi_set_swgain(), dahdi_show_channel(), dahdi_show_channels(), dahdi_softhangup_all(), destroy_all_channels(), destroy_channel(), do_monitor(), duplicate_pseudo(), find_channel(), load_module(), mkintf(), and phone_request().
const char* lbostr[] [static]
Definition at line 161 of file chan_dahdi.c.
int matchdigittimeout = 3000 [static]
How long to wait for an extra digit, if there is an ambiguous match.
Definition at line 332 of file chan_dahdi.c.
pthread_t monitor_thread = AST_PTHREADT_NULL [static]
This is the thread for the monitor which checks for input on the channels which are not currently in use.
Definition at line 354 of file chan_dahdi.c.
int mwilevel = 512 [static]
Definition at line 314 of file chan_dahdi.c.
char mwimonitornotify[PATH_MAX] = "" [static]
Run this script when the MWI state changes on an FXO line, if mwimonitor is enabled
Definition at line 302 of file chan_dahdi.c.
int mwisend_rpas = 0 [static]
Definition at line 304 of file chan_dahdi.c.
char* name
Definition at line 2368 of file chan_dahdi.c.
int num_cadence = 4 [static]
Definition at line 1473 of file chan_dahdi.c.
int num_restart_pending = 0 [static]
Definition at line 359 of file chan_dahdi.c.
int numbufs = 4 [static]
Definition at line 312 of file chan_dahdi.c.
char parkinglot[AST_MAX_EXTENSION] = "" [static]
Default parking lot for this channel
Definition at line 299 of file chan_dahdi.c.
Referenced by __find_callno(), ast_iax2_new(), build_parkinglot(), build_peer(), build_user(), check_access(), check_peer_ok(), create_addr_from_peer(), find_parkinglot(), findparkinglotname(), func_channel_write(), gtalk_load_config(), gtalk_new(), park_space_reserve(), parkinglot_cmp_cb(), parkinglot_hash_cb(), set_pvt_defaults(), sip_alloc(), sip_new(), sip_park(), skinny_new(), and store_config_core().
char progzone[10] = "" [static]
Definition at line 307 of file chan_dahdi.c.
int ringt_base = DEFAULT_RINGT [static]
Configured ring timeout base.
Note:
Value computed from "ringtimeout" read in from chan_dahdi.conf if it exists.
Definition at line 414 of file chan_dahdi.c.
struct dahdi_pvt* round_robin[32]
Definition at line 1428 of file chan_dahdi.c.
ast_cond_t ss_thread_complete [static]
Definition at line 355 of file chan_dahdi.c.
int ss_thread_count = 0 [static]
Definition at line 358 of file chan_dahdi.c.
char* subnames[] [static]
Initial value:
 {
   "Real",
   "Callwait",
   "Threeway"
}
Definition at line 600 of file chan_dahdi.c.
const char tdesc[] = "DAHDI Telephony Driver" [static]
Definition at line 215 of file chan_dahdi.c.
int usedistinctiveringdetection = 0 [static]
Definition at line 309 of file chan_dahdi.c.
int user_has_defined_cadences = 0 [static]
Definition at line 1474 of file chan_dahdi.c.