Wed May 5 15:21:54 2010
Asterisk developer's documentation
cli.c File Reference
Standard Command Line Interface.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/paths.h"
#include <sys/signal.h>
#include <signal.h>
#include <ctype.h>
#include <regex.h>
#include <pwd.h>
#include <grp.h>
#include "asterisk/cli.h"
#include "asterisk/linkedlists.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
#include "asterisk/channel.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
#include "asterisk/lock.h"
#include "editline/readline/readline.h"
#include "asterisk/threadstorage.h"
Data Structures
struct ast_debug_file
map a debug or verbose value to a filename
struct cli_perm
List of restrictions per user.
struct cli_perm_head
struct cli_perms
List of users and permissions.
struct debug_file_list
struct helpers
struct usergroup_cli_perm
list of users to apply restrictions.
Defines
#define AST_CLI_INITLEN 256
Initial buffer size for resulting strings in ast_cli().
#define CONCISE_FORMAT_STRING "%s!%s!%s!%d!%s!%s!%s!%s!%s!%d!%s!%s!%s\n"
#define DAY (HOUR*24)
#define FORMAT_STRING "%-25s %-20s %-20s\n"
#define FORMAT_STRING "%-20.20s %-20.20s %-7.7s %-30.30s\n"
#define FORMAT_STRING2 "%-20.20s %-20.20s %-7.7s %-30.30s\n"
#define HOUR (MINUTE*60)
#define MINUTE (SECOND*60)
#define MODLIST_FORMAT "%-30s %-40.40s %-10d\n"
#define MODLIST_FORMAT2 "%-30s %-40.40s %-10s\n"
#define NEEDCOMMA(x) ((x)? ",": "")
#define SECOND (1)
#define VERBOSE_FORMAT_STRING "%-20.20s %-20.20s %-16.16s %4d %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
#define VERBOSE_FORMAT_STRING2 "%-20.20s %-20.20s %-16.16s %-4.4s %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
#define WEEK (DAY*7)
#define YEAR (DAY*365)
Functions
static char * __ast_cli_generator (const char *text, const char *word, int state, int lock)
static int __ast_cli_register (struct ast_cli_entry *e, struct ast_cli_entry *ed)
static int __ast_cli_unregister (struct ast_cli_entry *e, struct ast_cli_entry *ed)
static void __init_ast_cli_buf (void)
void ast_builtins_init (void)
initialize the _full_cmd string in * each of the builtins.
void ast_cli (int fd, const char *fmt,...)
int ast_cli_command_full (int uid, int gid, int fd, const char *s)
Interprets a command Interpret a command s, sending output to fd if uid:gid has permissions to run this command. uid = CLI_NO_PERMS to avoid checking user permissions gid = CLI_NO_PERMS to avoid checking group permissions.
int ast_cli_command_multiple_full (int uid, int gid, int fd, size_t size, const char *s)
Executes multiple CLI commands Interpret strings separated by NULL and execute each one, sending output to fd if uid has permissions, uid = CLI_NO_PERMS to avoid checking users permissions. gid = CLI_NO_PERMS to avoid checking group permissions.
char * ast_cli_complete (const char *word, char *const choices[], int state)
char ** ast_cli_completion_matches (const char *text, const char *word)
Generates a NULL-terminated array of strings that 1) begin with the string in the second parameter, and 2) are valid in a command after the string in the first parameter.
char * ast_cli_generator (const char *text, const char *word, int state)
Readline madness Useful for readline, that's about it.
int ast_cli_generatornummatches (const char *text, const char *word)
Return the number of unique matches for the generator.
int ast_cli_perms_init (int reload)
int ast_cli_register (struct ast_cli_entry *e)
Registers a command or an array of commands.
int ast_cli_register_multiple (struct ast_cli_entry *e, int len)
Register multiple commands.
int ast_cli_unregister (struct ast_cli_entry *e)
Unregisters a command or an array of commands.
int ast_cli_unregister_multiple (struct ast_cli_entry *e, int len)
Unregister multiple commands.
char * ast_complete_channels (const char *line, const char *word, int pos, int state, int rpos)
Command completion for the list of active channels.
unsigned int ast_debug_get_by_file (const char *file)
Get the debug level for a file.
unsigned int ast_verbose_get_by_file (const char *file)
Get the debug level for a file.
static int cli_has_permissions (int uid, int gid, const char *command)
static struct ast_cli_entry * cli_next (struct ast_cli_entry *e)
static char * complete_fn (const char *word, int state)
static char * complete_number (const char *partial, unsigned int min, unsigned int max, int n)
static void destroy_user_perms (void)
cleanup (free) cli_perms linkedlist.
static char * find_best (char *argv[])
static struct ast_cli_entry * find_cli (char *const cmds[], int match_type)
static struct ast_debug_file * find_debug_file (const char *fn, unsigned int debug)
Find the debug or verbose file setting.
static char * group_show_channels (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_chanlist (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_cli_check_permissions (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handles CLI command 'cli check permissions'
static char * handle_cli_reload_permissions (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handles CLI command 'cli reload permissions'
static char * handle_cli_show_permissions (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
handles CLI command 'cli show permissions'
static char * handle_commandcomplete (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_commandmatchesarray (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_commandnummatches (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_core_set_debug_channel (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_help (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_load (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_logger_mute (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_modlist (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_nodebugchan_deprecated (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_reload (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_showcalls (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_showchan (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_showuptime (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_softhangup (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_unload (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * handle_verbose (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * help1 (int fd, char *match[], int locked)
helper for final part of handle_help if locked = 1, assume the list is already locked
static char * is_prefix (const char *word, const char *token, int pos, int *actual)
if word is a valid prefix for token, returns the pos-th match as a malloced string, or NULL otherwise. Always tell in *actual how many matches we got.
static int modlist_modentry (const char *module, const char *description, int usecnt, const char *like)
static int more_words (char *const *dst)
returns true if there are more words to match
static char * parse_args (const char *s, int *argc, char *argv[], int max, int *trailingwhitespace)
static void print_uptimestr (int fd, struct timeval timeval, const char *prefix, int printsec)
static int set_full_cmd (struct ast_cli_entry *e)
static int word_match (const char *cmd, const char *cli_word)
Variables
static struct ast_threadstorage ast_cli_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_ast_cli_buf , .custom_init = NULL , }
static struct ast_cli_entry cli_cli []
static int cli_default_perm = 1
Default permissions value 1=Permit 0=Deny.
static const char cli_rsvd [] = "[]{}|*%"
static int climodentryfd = -1
static ast_mutex_t climodentrylock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER)
static struct debug_file_list debug_files
static const char perms_config [] = "cli_permissions.conf"
CLI permissions config file.
static ast_mutex_t permsconfiglock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER)
mutex used to prevent a user from running the 'cli reload permissions' command while it is already running.
static struct debug_file_list verbose_files
Detailed Description
Standard Command Line Interface.
Author:
Mark Spencer <markster@digium.com>
Definition in file cli.c.
Define Documentation
#define AST_CLI_INITLEN 256
Initial buffer size for resulting strings in ast_cli().
Definition at line 98 of file cli.c.
Referenced by ast_cli().
#define CONCISE_FORMAT_STRING "%s!%s!%s!%d!%s!%s!%s!%s!%s!%d!%s!%s!%s\n"
Referenced by handle_chanlist().
#define DAY (HOUR*24)
Referenced by print_uptimestr().
#define FORMAT_STRING "%-25s %-20s %-20s\n"
#define FORMAT_STRING "%-20.20s %-20.20s %-7.7s %-30.30s\n"
Referenced by group_show_channels(), and handle_chanlist().
#define FORMAT_STRING2 "%-20.20s %-20.20s %-7.7s %-30.30s\n"
Referenced by handle_chanlist().
#define HOUR (MINUTE*60)
Referenced by print_uptimestr().
#define MINUTE (SECOND*60)
Referenced by print_uptimestr().
#define MODLIST_FORMAT "%-30s %-40.40s %-10d\n"
Definition at line 589 of file cli.c.
Referenced by modlist_modentry().
#define MODLIST_FORMAT2 "%-30s %-40.40s %-10s\n"
Definition at line 590 of file cli.c.
Referenced by handle_modlist().
#define NEEDCOMMA (x) ((x)? ",": "")
Referenced by print_uptimestr().
#define SECOND (1)
#define VERBOSE_FORMAT_STRING "%-20.20s %-20.20s %-16.16s %4d %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
Referenced by handle_chanlist().
#define VERBOSE_FORMAT_STRING2 "%-20.20s %-20.20s %-16.16s %-4.4s %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
Referenced by handle_chanlist().
#define WEEK (DAY*7)
Referenced by print_uptimestr().
#define YEAR (DAY*365)
Referenced by print_uptimestr().
Function Documentation
static char * __ast_cli_generator (const char * text, const char * word, int state, int lock) [static]
Definition at line 2170 of file cli.c.
References ARRAY_LEN, ast_free, ast_join(), AST_MAX_ARGS, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_strlen_zero(), CLI_GENERATE, cli_next(), ast_cli_entry::cmda, ast_cli_entry::command, ast_cli_entry::handler, is_prefix(), ast_cli_args::line, more_words(), parse_args(), and word_match().
Referenced by ast_cli_generator(), handle_commandcomplete(), and handle_help().
{
   char *argv[AST_MAX_ARGS];
   struct ast_cli_entry *e = NULL;
   int x = 0, argindex, matchlen;
   int matchnum=0;
   char *ret = NULL;
   char matchstr[80] = "";
   int tws = 0;
   /* Split the argument into an array of words */
   char *duplicate = parse_args(text, &x, argv, ARRAY_LEN(argv), &tws);
   if (!duplicate)   /* malloc error */
      return NULL;
   /* Compute the index of the last argument (could be an empty string) */
   argindex = (!ast_strlen_zero(word) && x>0) ? x-1 : x;
   /* rebuild the command, ignore terminating white space and flatten space */
   ast_join(matchstr, sizeof(matchstr)-1, argv);
   matchlen = strlen(matchstr);
   if (tws) {
      strcat(matchstr, " "); /* XXX */
      if (matchlen)
         matchlen++;
   }
   if (lock)
      AST_RWLIST_RDLOCK(&helpers);
   while ( (e = cli_next(e)) ) {
      /* XXX repeated code */
      int src = 0, dst = 0, n = 0;
      if (e->command[0] == '_')
         continue;
      /*
       * Try to match words, up to and excluding the last word, which
       * is either a blank or something that we want to extend.
       */
      for (;src < argindex; dst++, src += n) {
         n = word_match(argv[src], e->cmda[dst]);
         if (n < 0)
            break;
      }
      if (src != argindex && more_words(e->cmda + dst))  /* not a match */
         continue;
      ret = is_prefix(argv[src], e->cmda[dst], state - matchnum, &n);
      matchnum += n; /* this many matches here */
      if (ret) {
         /*
          * argv[src] is a valid prefix of the next word in this
          * command. If this is also the correct entry, return it.
          */
         if (matchnum > state)
            break;
         ast_free(ret);
         ret = NULL;
      } else if (ast_strlen_zero(e->cmda[dst])) {
         /*
          * This entry is a prefix of the command string entered
          * (only one entry in the list should have this property).
          * Run the generator if one is available. In any case we are done.
          */
         if (e->handler) { /* new style command */
            struct ast_cli_args a = {
               .line = matchstr, .word = word,
               .pos = argindex,
               .n = state - matchnum,
               .argv = argv,
               .argc = x};
            ret = e->handler(e, CLI_GENERATE, &a);
         }
         if (ret)
            break;
      }
   }
   if (lock)
      AST_RWLIST_UNLOCK(&helpers);
   ast_free(duplicate);
   return ret;
}
static int __ast_cli_register (struct ast_cli_entry * e, struct ast_cli_entry * ed) [static]
Definition at line 1857 of file cli.c.
References ast_cli_entry::_full_cmd, ast_log(), AST_MAX_CMD_LEN, AST_RWLIST_INSERT_BEFORE_CURRENT, AST_RWLIST_INSERT_TAIL, AST_RWLIST_TRAVERSE_SAFE_BEGIN, AST_RWLIST_TRAVERSE_SAFE_END, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_skip_blanks(), ast_skip_nonblanks(), ast_strdup, ast_strlen_zero(), CLI_INIT, ast_cli_entry::cmda, ast_cli_entry::cmdlen, ast_cli_entry::command, find_cli(), ast_cli_entry::handler, len(), LOG_WARNING, s, S_OR, and set_full_cmd().
Referenced by ast_cli_register().
{
   struct ast_cli_entry *cur;
   int i, lf, ret = -1;
   struct ast_cli_args a;  /* fake argument */
   char **dst = (char **)e->cmda;   /* need to cast as the entry is readonly */
   char *s;
   memset(&a, '\0', sizeof(a));
   e->handler(e, CLI_INIT, &a);
   /* XXX check that usage and command are filled up */
   s = ast_skip_blanks(e->command);
   s = e->command = ast_strdup(s);
   for (i=0; !ast_strlen_zero(s) && i < AST_MAX_CMD_LEN-1; i++) {
      *dst++ = s; /* store string */
      s = ast_skip_nonblanks(s);
      if (*s == '\0')   /* we are done */
         break;
      *s++ = '\0';
      s = ast_skip_blanks(s);
   }
   *dst++ = NULL;
   AST_RWLIST_WRLOCK(&helpers);
   if (find_cli(e->cmda, 1)) {
      ast_log(LOG_WARNING, "Command '%s' already registered (or something close enough)\n", S_OR(e->_full_cmd, e->command));
      goto done;
   }
   if (set_full_cmd(e))
      goto done;
   lf = e->cmdlen;
   AST_RWLIST_TRAVERSE_SAFE_BEGIN(&helpers, cur, list) {
      int len = cur->cmdlen;
      if (lf < len)
         len = lf;
      if (strncasecmp(e->_full_cmd, cur->_full_cmd, len) < 0) {
         AST_RWLIST_INSERT_BEFORE_CURRENT(e, list);
         break;
      }
   }
   AST_RWLIST_TRAVERSE_SAFE_END;
   if (!cur)
      AST_RWLIST_INSERT_TAIL(&helpers, e, list);
   ret = 0; /* success */
done:
   AST_RWLIST_UNLOCK(&helpers);
   return ret;
}
static int __ast_cli_unregister (struct ast_cli_entry * e, struct ast_cli_entry * ed) [static]
Definition at line 1835 of file cli.c.
References ast_cli_entry::_full_cmd, ast_free, ast_log(), AST_RWLIST_REMOVE, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_cli_entry::cmda, ast_cli_entry::command, ast_cli_entry::handler, ast_cli_entry::inuse, LOG_WARNING, and ast_cli_entry::usage.
Referenced by ast_cli_unregister().
{
   if (e->inuse) {
      ast_log(LOG_WARNING, "Can't remove command that is in use\n");
   } else {
      AST_RWLIST_WRLOCK(&helpers);
      AST_RWLIST_REMOVE(&helpers, e, list);
      AST_RWLIST_UNLOCK(&helpers);
      ast_free(e->_full_cmd);
      e->_full_cmd = NULL;
      if (e->handler) {
         /* this is a new-style entry. Reset fields and free memory. */
         char *cmda = (char *) e->cmda;
         memset(cmda, '\0', sizeof(e->cmda));
         ast_free(e->command);
         e->command = NULL;
         e->usage = NULL;
      }
   }
   return 0;
}
static void __init_ast_cli_buf (void) [static]
Definition at line 95 of file cli.c.
{
void ast_builtins_init (void)
initialize the _full_cmd string in * each of the builtins.
Provided by cli.c
Definition at line 1677 of file cli.c.
References ARRAY_LEN, and ast_cli_register_multiple().
Referenced by main().
{
   ast_cli_register_multiple(cli_cli, ARRAY_LEN(cli_cli));
}
void ast_cli (int fd, const char * fmt, ...)
Definition at line 100 of file cli.c.
References ast_carefulwrite(), AST_CLI_INITLEN, AST_DYNSTR_BUILD_FAILED, ast_str_buffer(), ast_str_set_va(), ast_str_strlen(), ast_str_thread_get(), and buf.
Referenced by __iax2_show_peers(), __say_cli_init(), _sip_qualify_peer(), _sip_show_peer(), _sip_show_peers(), _skinny_show_device(), _skinny_show_devices(), _skinny_show_line(), _skinny_show_lines(), agent_logoff_cmd(), agents_show(), agents_show_online(), ais_clm_show_members(), ais_evt_show_event_channels(), aji_do_reload(), aji_do_set_debug(), aji_show_buddies(), aji_show_clients(), aji_test(), alias_show(), ast_cli_command_full(), ast_cli_netstats(), ast_console_toggle_mute(), cli_console_active(), cli_console_answer(), cli_console_autoanswer(), cli_console_dial(), cli_console_flash(), cli_console_hangup(), cli_console_mute(), cli_console_sendtext(), cli_list_available(), cli_list_devices(), cli_match_char_tree(), cli_odbc_read(), cli_odbc_write(), cli_realtime_destroy(), cli_realtime_load(), cli_realtime_store(), cli_realtime_update(), cli_realtime_update2(), cli_tps_ping(), cli_tps_report(), console_active(), console_answer(), console_autoanswer(), console_boost(), console_cmd(), console_dial(), console_do_answer(), console_flash(), console_hangup(), console_mute(), console_sendtext(), console_transfer(), dahdi_set_dnd(), dahdi_set_hwgain(), dahdi_set_swgain(), dahdi_show_channel(), dahdi_show_channels(), dahdi_show_status(), dahdi_show_version(), dialog_dump_func(), do_print(), dundi_do_lookup(), dundi_do_precache(), dundi_do_query(), dundi_flush(), dundi_set_debug(), dundi_show_entityid(), dundi_show_mappings(), dundi_show_peer(), dundi_show_peers(), dundi_show_precache(), dundi_show_requests(), dundi_show_trans(), dundi_store_history(), group_show_channels(), gtalk_show_channels(), handle_chanlist(), handle_cli_agi_debug(), handle_cli_agi_dump_html(), handle_cli_agi_show(), handle_cli_check_permissions(), handle_cli_config_list(), handle_cli_core_show_channeltype(), handle_cli_core_show_channeltypes(), handle_cli_core_show_config_mappings(), handle_cli_core_show_file_formats(), handle_cli_core_show_translation(), handle_cli_database_del(), handle_cli_database_deltree(), handle_cli_database_get(), handle_cli_database_put(), handle_cli_database_show(), handle_cli_database_showkey(), handle_cli_devstate_change(), handle_cli_devstate_list(), handle_cli_dialplan_add_extension(), handle_cli_dialplan_add_ignorepat(), handle_cli_dialplan_add_include(), handle_cli_dialplan_reload(), handle_cli_dialplan_remove_extension(), handle_cli_dialplan_remove_ignorepat(), handle_cli_dialplan_remove_include(), handle_cli_dialplan_save(), handle_cli_file_convert(), handle_cli_h323_set_debug(), handle_cli_h323_set_trace(), handle_cli_iax2_provision(), handle_cli_iax2_prune_realtime(), handle_cli_iax2_set_debug(), handle_cli_iax2_set_debug_jb(), handle_cli_iax2_set_debug_trunk(), handle_cli_iax2_set_mtu(), handle_cli_iax2_show_cache(), handle_cli_iax2_show_callno_limits(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_firmware(), handle_cli_iax2_show_netstats(), handle_cli_iax2_show_peer(), handle_cli_iax2_show_registry(), handle_cli_iax2_show_stats(), handle_cli_iax2_show_threads(), handle_cli_iax2_show_users(), handle_cli_iax2_unregister(), handle_cli_indication_show(), handle_cli_keys_show(), handle_cli_misdn_reload(), handle_cli_misdn_send_digit(), handle_cli_misdn_send_display(), handle_cli_misdn_set_debug(), handle_cli_misdn_show_channels(), handle_cli_misdn_show_config(), handle_cli_misdn_show_port(), handle_cli_misdn_show_ports_stats(), handle_cli_misdn_show_stacks(), handle_cli_misdn_toggle_echocancel(), handle_cli_mixmonitor(), handle_cli_moh_show_classes(), handle_cli_moh_show_files(), handle_cli_odbc_show(), handle_cli_osp_show(), handle_cli_realtime_pgsql_cache(), handle_cli_realtime_pgsql_status(), handle_cli_refresh(), handle_cli_rtcp_set_debug(), handle_cli_rtcp_set_stats(), handle_cli_rtp_set_debug(), handle_cli_show_permissions(), handle_cli_show_sqlite_status(), handle_cli_sqlite_show_tables(), handle_cli_status(), handle_cli_stun_set_debug(), handle_cli_submit(), handle_cli_transcoder_show(), handle_cli_udptl_set_debug(), handle_cli_ulimit(), handle_commandcomplete(), handle_commandmatchesarray(), handle_commandnummatches(), handle_core_set_debug_channel(), handle_core_show_image_formats(), handle_dahdi_show_cadences(), handle_debug_dialplan(), handle_feature_show(), handle_help(), handle_load(), handle_logger_reload(), handle_logger_rotate(), handle_logger_set_level(), handle_logger_show_channels(), handle_mandebug(), handle_memory_show(), handle_memory_show_summary(), handle_mgcp_audit_endpoint(), handle_mgcp_set_debug(), handle_mgcp_show_endpoints(), handle_minivm_list_templates(), handle_minivm_reload(), handle_minivm_show_settings(), handle_minivm_show_stats(), handle_minivm_show_users(), handle_minivm_show_zones(), handle_modlist(), handle_parkedcalls(), handle_queue_add_member(), handle_queue_pause_member(), handle_queue_remove_member(), handle_queue_rule_show(), handle_queue_set_member_penalty(), handle_redirect(), handle_reload(), handle_restart_when_convenient(), handle_set_chanvar(), handle_set_extenpatternmatchnew(), handle_set_global(), handle_show_application(), handle_show_applications(), handle_show_chanvar(), handle_show_dialplan(), handle_show_function(), handle_show_functions(), handle_show_globals(), handle_show_hint(), handle_show_hints(), handle_show_http(), handle_show_profile(), handle_show_routes(), handle_show_settings(), handle_show_switches(), handle_show_threads(), handle_show_version_files(), handle_showcalls(), handle_showchan(), handle_showmanager(), handle_showmanagers(), handle_showmancmd(), handle_showmancmds(), handle_showmanconn(), handle_showmaneventq(), handle_skinny_set_debug(), handle_skinny_show_settings(), handle_softhangup(), handle_stop_when_convenient(), handle_unload(), handle_unset_extenpatternmatchnew(), handle_verbose(), handle_version(), handle_voicemail_reload(), handle_voicemail_show_users(), handle_voicemail_show_zones(), help1(), help_workhorse(), iax_show_provisioning(), jingle_show_channels(), locals_show(), meetme_cmd(), meetme_show_cmd(), modlist_modentry(), orig_app(), orig_exten(), peer_dump_func(), print_app_docs(), print_bc_info(), print_codec_to_cli(), print_group(), print_uptimestr(), radio_active(), radio_set_debug(), radio_set_debug_off(), radio_set_xpmr_debug(), radio_tune(), realtime_ldap_status(), rpt_do_cmd(), rpt_do_debug(), rpt_do_dump(), rpt_do_fun(), rpt_do_local_nodes(), rpt_do_lstats(), rpt_do_nodes(), rpt_do_stats(), rtcp_do_debug_ip(), rtp_do_debug_ip(), show_channels_cb(), show_chanstats_cb(), show_codec_n(), show_codecs(), show_config_description(), show_debug_helper(), show_dialplan_helper(), show_license(), show_users_realtime(), show_warranty(), sip_cli_notify(), sip_do_debug(), sip_do_debug_ip(), sip_do_debug_peer(), sip_prune_realtime(), sip_set_history(), sip_show_channel(), sip_show_channels(), sip_show_channelstats(), sip_show_domains(), sip_show_history(), sip_show_inuse(), sip_show_mwi(), sip_show_objects(), sip_show_registry(), sip_show_sched(), sip_show_settings(), sip_show_tcp(), sip_show_user(), sip_show_users(), sip_unregister(), sla_show_stations(), sla_show_trunks(), timing_test(), tune_rxctcss(), tune_rxinput(), tune_rxvoice(), tune_txoutput(), unistim_do_debug(), unistim_info(), and unistim_sp().
{
   int res;
   struct ast_str *buf;
   va_list ap;
   if (!(buf = ast_str_thread_get(&ast_cli_buf, AST_CLI_INITLEN)))
      return;
   va_start(ap, fmt);
   res = ast_str_set_va(&buf, 0, fmt, ap);
   va_end(ap);
   if (res != AST_DYNSTR_BUILD_FAILED) {
      ast_carefulwrite(fd, ast_str_buffer(buf), ast_str_strlen(buf), 100);
   }
}
int ast_cli_command_full (int uid, int gid, int fd, const char * s)
Interprets a command Interpret a command s, sending output to fd if uid:gid has permissions to run this command. uid = CLI_NO_PERMS to avoid checking user permissions gid = CLI_NO_PERMS to avoid checking group permissions.
Parameters:
uid User ID that is trying to run the command.
gid Group ID that is trying to run the command.
fd pipe
s incoming string
Return values:
0 on success
-1 on failure
Definition at line 2258 of file cli.c.
References ast_atomic_fetchadd_int(), ast_cli(), ast_free, ast_join(), AST_MAX_ARGS, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, CLI_FAILURE, CLI_HANDLER, cli_has_permissions(), CLI_SHOWUSAGE, ast_cli_args::fd, find_best(), find_cli(), ast_cli_entry::handler, ast_cli_entry::inuse, parse_args(), S_OR, and ast_cli_entry::usage.
Referenced by ast_cli_command_multiple_full().
{
   char *args[AST_MAX_ARGS + 1];
   struct ast_cli_entry *e;
   int x;
   char *duplicate = parse_args(s, &x, args + 1, AST_MAX_ARGS, NULL);
   char tmp[AST_MAX_ARGS + 1];
   char *retval = NULL;
   struct ast_cli_args a = {
      .fd = fd, .argc = x, .argv = args+1 };
   if (duplicate == NULL)
      return -1;
   if (x < 1)  /* We need at least one entry, otherwise ignore */
      goto done;
   AST_RWLIST_RDLOCK(&helpers);
   e = find_cli(args + 1, 0);
   if (e)
      ast_atomic_fetchadd_int(&e->inuse, 1);
   AST_RWLIST_UNLOCK(&helpers);
   if (e == NULL) {
      ast_cli(fd, "No such command '%s' (type 'core show help %s' for other possible commands)\n", s, find_best(args + 1));
      goto done;
   }
   ast_join(tmp, sizeof(tmp), args + 1);
   /* Check if the user has rights to run this command. */
   if (!cli_has_permissions(uid, gid, tmp)) {
      ast_cli(fd, "You don't have permissions to run '%s' command\n", tmp);
      ast_free(duplicate);
      return 0;
   }
   /*
    * Within the handler, argv[-1] contains a pointer to the ast_cli_entry.
    * Remember that the array returned by parse_args is NULL-terminated.
    */
   args[0] = (char *)e;
   retval = e->handler(e, CLI_HANDLER, &a);
   if (retval == CLI_SHOWUSAGE) {
      ast_cli(fd, "%s", S_OR(e->usage, "Invalid usage, but no usage information available.\n"));
   } else {
      if (retval == CLI_FAILURE)
         ast_cli(fd, "Command '%s' failed.\n", s);
   }
   ast_atomic_fetchadd_int(&e->inuse, -1);
done:
   ast_free(duplicate);
   return 0;
}
int ast_cli_command_multiple_full (int uid, int gid, int fd, size_t size, const char * s)
Executes multiple CLI commands Interpret strings separated by NULL and execute each one, sending output to fd if uid has permissions, uid = CLI_NO_PERMS to avoid checking users permissions. gid = CLI_NO_PERMS to avoid checking group permissions.
Parameters:
uid User ID that is trying to run the command.
gid Group ID that is trying to run the command.
fd pipe
size is the total size of the string
s incoming string
Return values:
number of commands executed
Definition at line 2313 of file cli.c.
References ast_cli_command_full().
Referenced by netconsole().
{
   char cmd[512];
   int x, y = 0, count = 0;
   for (x = 0; x < size; x++) {
      cmd[y] = s[x];
      y++;
      if (s[x] == '\0') {
         ast_cli_command_full(uid, gid, fd, cmd);
         y = 0;
         count++;
      }
   }
   return count;
}
char* ast_cli_complete (const char * word, char *const choices[], int pos)
Helper function to generate cli entries from a NULL-terminated array. Returns the n-th matching entry from the array, or NULL if not found. Can be used to implement generate() for static entries as below (in this example we complete the word in position 2):
    char *my_generate(const char *line, const char *word, int pos, int n)
    {
        static char *choices = { "one", "two", "three", NULL };
   if (pos == 2)
         return ast_cli_complete(word, choices, n);
   else
      return NULL;
    }
Definition at line 1378 of file cli.c.
References ast_strdup, ast_strlen_zero(), and len().
Referenced by complete_meetmecmd(), handle_cli_devstate_change(), handle_cli_iax2_prune_realtime(), handle_orig(), handle_show_applications(), and sip_prune_realtime().
{
   int i, which = 0, len;
   len = ast_strlen_zero(word) ? 0 : strlen(word);
   for (i = 0; choices[i]; i++) {
      if ((!len || !strncasecmp(word, choices[i], len)) && ++which > state)
         return ast_strdup(choices[i]);
   }
   return NULL;
}
char** ast_cli_completion_matches (const char * , const char *)
Generates a NULL-terminated array of strings that 1) begin with the string in the second parameter, and 2) are valid in a command after the string in the first parameter.
The first entry (offset 0) of the result is the longest common substring in the results, useful to extend the string that has been completed. Subsequent entries are all possible values, followed by a NULL. All strings and the array itself are malloc'ed and must be freed by the caller.
Definition at line 2109 of file cli.c.
References ast_cli_generator(), ast_copy_string(), ast_malloc, and ast_realloc.
Referenced by cli_complete(), and handle_commandmatchesarray().
{
   char **match_list = NULL, *retstr, *prevstr;
   size_t match_list_len, max_equal, which, i;
   int matches = 0;
   /* leave entry 0 free for the longest common substring */
   match_list_len = 1;
   while ((retstr = ast_cli_generator(text, word, matches)) != NULL) {
      if (matches + 1 >= match_list_len) {
         match_list_len <<= 1;
         if (!(match_list = ast_realloc(match_list, match_list_len * sizeof(*match_list))))
            return NULL;
      }
      match_list[++matches] = retstr;
   }
   if (!match_list)
      return match_list; /* NULL */
   /* Find the longest substring that is common to all results
    * (it is a candidate for completion), and store a copy in entry 0.
    */
   prevstr = match_list[1];
   max_equal = strlen(prevstr);
   for (which = 2; which <= matches; which++) {
      for (i = 0; i < max_equal && toupper(prevstr[i]) == toupper(match_list[which][i]); i++)
         continue;
      max_equal = i;
   }
   if (!(retstr = ast_malloc(max_equal + 1)))
      return NULL;
   ast_copy_string(retstr, match_list[1], max_equal + 1);
   match_list[0] = retstr;
   /* ensure that the array is NULL terminated */
   if (matches + 1 >= match_list_len) {
      if (!(match_list = ast_realloc(match_list, (match_list_len + 1) * sizeof(*match_list))))
         return NULL;
   }
   match_list[matches + 1] = NULL;
   return match_list;
}
char* ast_cli_generator (const char * , const char * , int)
Readline madness Useful for readline, that's about it.
Return values:
0 on success
-1 on failure
Definition at line 2253 of file cli.c.
References __ast_cli_generator().
Referenced by ast_cli_completion_matches(), ast_cli_generatornummatches(), cli_alias_passthrough(), and handle_cli_check_permissions().
{
   return __ast_cli_generator(text, word, state, 1);
}
int ast_cli_generatornummatches (const char * text, const char * word)
Return the number of unique matches for the generator.
Definition at line 2092 of file cli.c.
References ast_cli_generator(), ast_free, and buf.
Referenced by handle_commandnummatches().
{
   int matches = 0, i = 0;
   char *buf = NULL, *oldbuf = NULL;
   while ((buf = ast_cli_generator(text, word, i++))) {
      if (!oldbuf || strcmp(buf,oldbuf))
         matches++;
      if (oldbuf)
         ast_free(oldbuf);
      oldbuf = buf;
   }
   if (oldbuf)
      ast_free(oldbuf);
   return matches;
}
int ast_cli_perms_init (int reload)
Provided by cli.c
Definition at line 1554 of file cli.c.
References ast_calloc, ast_category_browse(), ast_config_destroy(), ast_config_load2(), ast_free, AST_LIST_INSERT_TAIL, AST_LIST_TRAVERSE, ast_log(), ast_mutex_trylock(), ast_mutex_unlock(), AST_RWLIST_INSERT_TAIL, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_strdup, ast_strlen_zero(), ast_variable_browse(), cli_perm::command, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEUNCHANGED, destroy_user_perms(), usergroup_cli_perm::gid, LOG_NOTICE, LOG_WARNING, ast_variable::name, ast_variable::next, cli_perm::permit, usergroup_cli_perm::perms, perms_config, usergroup_cli_perm::uid, and ast_variable::value.
Referenced by handle_cli_reload_permissions(), and main().
{
   struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
   struct ast_config *cfg;
   char *cat = NULL;
   struct ast_variable *v;
   struct usergroup_cli_perm *user_group, *cp_entry;
   struct cli_perm *perm = NULL;
   struct passwd *pw;
   struct group *gr;
   if (ast_mutex_trylock(&permsconfiglock)) {
      ast_log(LOG_NOTICE, "You must wait until last 'cli reload permissions' command finish\n");
      return 1;
   }
   cfg = ast_config_load2(perms_config, "" /* core, can't reload */, config_flags);
   if (!cfg) {
      ast_mutex_unlock(&permsconfiglock);
      return 1;
   } else if (cfg == CONFIG_STATUS_FILEUNCHANGED) {
      ast_mutex_unlock(&permsconfiglock);
      return 0;
   }
   /* free current structures. */
   destroy_user_perms();
   while ((cat = ast_category_browse(cfg, cat))) {
      if (!strcasecmp(cat, "general")) {
         /* General options */
         for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
            if (!strcasecmp(v->name, "default_perm")) {
               cli_default_perm = (!strcasecmp(v->value, "permit")) ? 1: 0;
            }
         }
         continue;
      }
      /* users or groups */
      gr = NULL, pw = NULL;
      if (cat[0] == '@') {
         /* This is a group */
         gr = getgrnam(&cat[1]);
         if (!gr) {
            ast_log (LOG_WARNING, "Unknown group '%s'\n", &cat[1]);
            continue;
         }
      } else {
         /* This is a user */
         pw = getpwnam(cat);
         if (!pw) {
            ast_log (LOG_WARNING, "Unknown user '%s'\n", cat);
            continue;
         }
      }
      user_group = NULL;
      /* Check for duplicates */
      AST_RWLIST_WRLOCK(&cli_perms);
      AST_LIST_TRAVERSE(&cli_perms, cp_entry, list) {
         if ((pw && cp_entry->uid == pw->pw_uid) || (gr && cp_entry->gid == gr->gr_gid)) {
            /* if it is duplicated, just added this new settings, to
            the current list. */
            user_group = cp_entry;
            break;
         }
      }
      AST_RWLIST_UNLOCK(&cli_perms);
      if (!user_group) {
         /* alloc space for the new user config. */
         user_group = ast_calloc(1, sizeof(*user_group));
         if (!user_group) {
            continue;
         }
         user_group->uid = (pw ? pw->pw_uid : -1);
         user_group->gid = (gr ? gr->gr_gid : -1);
         user_group->perms = ast_calloc(1, sizeof(*user_group->perms));
         if (!user_group->perms) {
            ast_free(user_group);
            continue;
         }
      }
      for (v = ast_variable_browse(cfg, cat); v; v = v->next) {
         if (ast_strlen_zero(v->value)) {
            /* we need to check this condition cause it could break security. */
            ast_log(LOG_WARNING, "Empty permit/deny option in user '%s'\n", cat);
            continue;
         }
         if (!strcasecmp(v->name, "permit")) {
            perm = ast_calloc(1, sizeof(*perm));
            if (perm) {
               perm->permit = 1;
               perm->command = ast_strdup(v->value);
            }
         } else if (!strcasecmp(v->name, "deny")) {
            perm = ast_calloc(1, sizeof(*perm));
            if (perm) {
               perm->permit = 0;
               perm->command = ast_strdup(v->value);
            }
         } else {
            /* up to now, only 'permit' and 'deny' are possible values. */
            ast_log(LOG_WARNING, "Unknown '%s' option\n", v->name);
            continue;
         }
         if (perm) {
            /* Added the permission to the user's list. */
            AST_LIST_INSERT_TAIL(user_group->perms, perm, list);
            perm = NULL;
         }
      }
      AST_RWLIST_WRLOCK(&cli_perms);
      AST_RWLIST_INSERT_TAIL(&cli_perms, user_group, list);
      AST_RWLIST_UNLOCK(&cli_perms);
   }
   ast_config_destroy(cfg);
   ast_mutex_unlock(&permsconfiglock);
   return 0;
}
int ast_cli_register (struct ast_cli_entry * e)
Registers a command or an array of commands.
Parameters:
e which cli entry to register. Register your own command
Return values:
0 on success
-1 on failure
Definition at line 1919 of file cli.c.
References __ast_cli_register().
Referenced by ast_cdr_engine_init(), ast_cli_register_multiple(), dnsmgr_init(), do_reload(), load_config(), and load_module().
{
   return __ast_cli_register(e, NULL);
}
int ast_cli_register_multiple (struct ast_cli_entry * e, int len)
Register multiple commands.
Parameters:
e pointer to first cli entry to register
len number of entries to register
Definition at line 1927 of file cli.c.
References ast_cli_register().
Referenced by __ast_mm_init(), __ast_register_translator(), __init_manager(), ast_ais_clm_load_module(), ast_ais_evt_load_module(), ast_builtins_init(), ast_channels_init(), ast_features_init(), ast_file_init(), ast_http_init(), ast_image_init(), ast_indications_init(), ast_rtp_init(), ast_timing_init(), ast_tps_init(), ast_udptl_init(), ast_utils_init(), astdb_init(), astobj2_init(), crypto_init(), iax_provision_init(), init_framer(), init_logger(), load_module(), load_pbx(), main(), and register_config_cli().
{
   int i, res = 0;
   for (i = 0; i < len; i++)
      res |= ast_cli_register(e + i);
   return res;
}
int ast_cli_unregister (struct ast_cli_entry * e)
Unregisters a command or an array of commands.
Parameters:
e which cli entry to unregister Unregister your own command. You must pass a completed ast_cli_entry structure
Returns:
0
Definition at line 1913 of file cli.c.
References __ast_cli_unregister().
Referenced by alias_destroy(), ast_cli_unregister_multiple(), do_reload(), load_module(), and unload_module().
{
   return __ast_cli_unregister(e, NULL);
}
int ast_cli_unregister_multiple (struct ast_cli_entry * e, int len)
Unregister multiple commands.
Parameters:
e pointer to first cli entry to unregister
len number of entries to unregister
Definition at line 1937 of file cli.c.
References ast_cli_unregister().
Referenced by __unload_module(), ast_ais_clm_unload_module(), iax_provision_unload(), load_module(), and unload_module().
{
   int i, res = 0;
   for (i = 0; i < len; i++)
      res |= ast_cli_unregister(e + i);
   return res;
}
char* ast_complete_channels (const char * line, const char * word, int pos, int state, int rpos)
Command completion for the list of active channels.
This can be called from a CLI command completion function that wants to complete from the list of active channels. 'rpos' is the required position in the command. This function will return NULL immediately if 'rpos' is not the same as the current position, 'pos'.
Definition at line 1390 of file cli.c.
References ast_channel_unlock, ast_channel_walk_locked(), and ast_strdup.
Referenced by complete_ch(), handle_cli_agi_add_cmd(), handle_cli_mixmonitor(), handle_core_set_debug_channel(), handle_redirect(), handle_set_chanvar(), handle_show_chanvar(), handle_showchan(), and handle_softhangup().
{
   struct ast_channel *c = NULL;
   int which = 0;
   int wordlen;
   char notfound = '\0';
   char *ret = &notfound; /* so NULL can break the loop */
   if (pos != rpos)
      return NULL;
   wordlen = strlen(word);
   while (ret == &notfound && (c = ast_channel_walk_locked(c))) {
      if (!strncasecmp(word, c->name, wordlen) && ++which > state)
         ret = ast_strdup(c->name);
      ast_channel_unlock(c);
   }
   return ret == &notfound ? NULL : ret;
}
unsigned int ast_debug_get_by_file (const char * file)
Get the debug level for a file.
Parameters:
file the filename
Returns:
the debug level
Definition at line 118 of file cli.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_debug_file::filename, and ast_debug_file::level.
{
   struct ast_debug_file *adf;
   unsigned int res = 0;
   AST_RWLIST_RDLOCK(&debug_files);
   AST_LIST_TRAVERSE(&debug_files, adf, entry) {
      if (!strncasecmp(adf->filename, file, strlen(adf->filename))) {
         res = adf->level;
         break;
      }
   }
   AST_RWLIST_UNLOCK(&debug_files);
   return res;
}
unsigned int ast_verbose_get_by_file (const char * file)
Get the debug level for a file.
Parameters:
file the filename
Returns:
the debug level
Definition at line 135 of file cli.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, ast_debug_file::filename, and ast_debug_file::level.
{
   struct ast_debug_file *adf;
   unsigned int res = 0;
   AST_RWLIST_RDLOCK(&verbose_files);
   AST_LIST_TRAVERSE(&verbose_files, adf, entry) {
      if (!strncasecmp(adf->filename, file, strlen(file))) {
         res = adf->level;
         break;
      }
   }
   AST_RWLIST_UNLOCK(&verbose_files);
   return res;
}
static int cli_has_permissions (int uid, int gid, const char * command) [static]
Definition at line 165 of file cli.c.
References AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, CLI_NO_PERMS, cli_perm::command, usergroup_cli_perm::gid, cli_perm::permit, usergroup_cli_perm::perms, and usergroup_cli_perm::uid.
Referenced by ast_cli_command_full(), and handle_cli_check_permissions().
{
   struct usergroup_cli_perm *user_perm;
   struct cli_perm *perm;
   /* set to the default permissions general option. */
   int isallowg = cli_default_perm, isallowu = -1, ispattern;
   regex_t regexbuf;
   /* if uid == -1 or gid == -1 do not check permissions.
      if uid == -2 and gid == -2 is because rasterisk client didn't send
      the credentials, so the cli_default_perm will be applied. */
   if ((uid == CLI_NO_PERMS && gid == CLI_NO_PERMS) || command[0] == '_') {
      return 1;
   }
   if (gid < 0 && uid < 0) {
      return cli_default_perm;
   }
   AST_RWLIST_RDLOCK(&cli_perms);
   AST_LIST_TRAVERSE(&cli_perms, user_perm, list) {
      if (user_perm->gid != gid && user_perm->uid != uid) {
         continue;
      }
      AST_LIST_TRAVERSE(user_perm->perms, perm, list) {
         if (strcasecmp(perm->command, "all") && strncasecmp(perm->command, command, strlen(perm->command))) {
            /* if the perm->command is a pattern, check it against command. */
            ispattern = !regcomp(&regexbuf, perm->command, REG_EXTENDED | REG_NOSUB | REG_ICASE);
            if (ispattern && regexec(&regexbuf, command, 0, NULL, 0)) {
               regfree(&regexbuf);
               continue;
            }
            if (!ispattern) {
               continue;
            }
            regfree(&regexbuf);
         }
         if (user_perm->uid == uid) {
            /* this is a user definition. */
            isallowu = perm->permit;
         } else {
            /* otherwise is a group definition. */
            isallowg = perm->permit;
         }
      }
   }
   AST_RWLIST_UNLOCK(&cli_perms);
   if (isallowu > -1) {
      /* user definition override group definition. */
      isallowg = isallowu;
   }
   return isallowg;
}
static struct ast_cli_entry* cli_next (struct ast_cli_entry * e) [static, read]
Definition at line 656 of file cli.c.
References AST_LIST_FIRST, and AST_LIST_NEXT.
Referenced by __ast_cli_generator(), find_cli(), handle_cli_check_permissions(), and help1().
{
   if (e) {
      return AST_LIST_NEXT(e, list);
   } else {
      return AST_LIST_FIRST(&helpers);
   }
}
static char* complete_fn (const char * word, int state) [static]
Definition at line 222 of file cli.c.
References ast_config_AST_MODULE_DIR, ast_copy_string(), ast_strdup, and free.
Referenced by handle_load().
{
   char *c, *d;
   char filename[PATH_MAX];
   if (word[0] == '/')
      ast_copy_string(filename, word, sizeof(filename));
   else
      snprintf(filename, sizeof(filename), "%s/%s", ast_config_AST_MODULE_DIR, word);
   c = d = filename_completion_function(filename, state);
   if (c && word[0] != '/')
      c += (strlen(ast_config_AST_MODULE_DIR) + 1);
   if (c)
      c = ast_strdup(c);
   free(d);
   return c;
}
static char* complete_number (const char * partial, unsigned int min, unsigned int max, int n) [static]
Definition at line 321 of file cli.c.
References ast_strdup, ast_strlen_zero(), and cli_perm::next.
Referenced by handle_verbose().
{
   int i, count = 0;
   unsigned int prospective[2];
   unsigned int part = strtoul(partial, NULL, 10);
   char next[12];
   if (part < min || part > max) {
      return NULL;
   }
   for (i = 0; i < 21; i++) {
      if (i == 0) {
         prospective[0] = prospective[1] = part;
      } else if (part == 0 && !ast_strlen_zero(partial)) {
         break;
      } else if (i < 11) {
         prospective[0] = prospective[1] = part * 10 + (i - 1);
      } else {
         prospective[0] = (part * 10 + (i - 11)) * 10;
         prospective[1] = prospective[0] + 9;
      }
      if (i < 11 && (prospective[0] < min || prospective[0] > max)) {
         continue;
      } else if (prospective[1] < min || prospective[0] > max) {
         continue;
      }
      if (++count > n) {
         if (i < 11) {
            snprintf(next, sizeof(next), "%u", prospective[0]);
         } else {
            snprintf(next, sizeof(next), "%u...", prospective[0] / 10);
         }
         return ast_strdup(next);
      }
   }
   return NULL;
}
static void destroy_user_perms (void) [static]
cleanup (free) cli_perms linkedlist.
Definition at line 1538 of file cli.c.
References ast_free, AST_LIST_REMOVE_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, cli_perm::command, and usergroup_cli_perm::perms.
Referenced by ast_cli_perms_init().
{
   struct cli_perm *perm;
   struct usergroup_cli_perm *user_perm;
   AST_RWLIST_WRLOCK(&cli_perms);
   while ((user_perm = AST_LIST_REMOVE_HEAD(&cli_perms, list))) {
      while ((perm = AST_LIST_REMOVE_HEAD(user_perm->perms, list))) {
         ast_free(perm->command);
         ast_free(perm);
      }
      ast_free(user_perm);
   }
   AST_RWLIST_UNLOCK(&cli_perms);
}
static char* find_best (char * argv[]) [static]
Definition at line 1816 of file cli.c.
References ast_join(), AST_MAX_CMD_LEN, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, and find_cli().
Referenced by ast_cli_command_full().
{
   static char cmdline[80];
   int x;
   /* See how close we get, then print the candidate */
   char *myargv[AST_MAX_CMD_LEN];
   for (x=0;x<AST_MAX_CMD_LEN;x++)
      myargv[x]=NULL;
   AST_RWLIST_RDLOCK(&helpers);
   for (x=0;argv[x];x++) {
      myargv[x] = argv[x];
      if (!find_cli(myargv, -1))
         break;
   }
   AST_RWLIST_UNLOCK(&helpers);
   ast_join(cmdline, sizeof(cmdline), myargv);
   return cmdline;
}
static struct ast_cli_entry* find_cli (char *const cmds[], int match_type) [static, read]
Definition at line 1772 of file cli.c.
References ast_strlen_zero(), cli_next(), ast_cli_entry::cmda, and word_match().
Referenced by __ast_cli_register(), ast_cli_command_full(), find_best(), and handle_help().
{
   int matchlen = -1;   /* length of longest match so far */
   struct ast_cli_entry *cand = NULL, *e=NULL;
   while ( (e = cli_next(e)) ) {
      /* word-by word regexp comparison */
      char * const *src = cmds;
      char * const *dst = e->cmda;
      int n = 0;
      for (;; dst++, src += n) {
         n = word_match(*src, *dst);
         if (n < 0)
            break;
      }
      if (ast_strlen_zero(*dst) || ((*dst)[0] == '[' && ast_strlen_zero(dst[1]))) {
         /* no more words in 'e' */
         if (ast_strlen_zero(*src)) /* exact match, cannot do better */
            break;
         /* Here, cmds has more words than the entry 'e' */
         if (match_type != 0) /* but we look for almost exact match... */
            continue;   /* so we skip this one. */
         /* otherwise we like it (case 0) */
      } else { /* still words in 'e' */
         if (ast_strlen_zero(*src))
            continue; /* cmds is shorter than 'e', not good */
         /* Here we have leftover words in cmds and 'e',
          * but there is a mismatch. We only accept this one if match_type == -1
          * and this is the last word for both.
          */
         if (match_type != -1 || !ast_strlen_zero(src[1]) ||
             !ast_strlen_zero(dst[1])) /* not the one we look for */
            continue;
         /* good, we are in case match_type == -1 and mismatch on last word */
      }
      if (src - cmds > matchlen) {  /* remember the candidate */
         matchlen = src - cmds;
         cand = e;
      }
   }
   return e ? e : cand;
}
static struct ast_debug_file* find_debug_file (const char * fn, unsigned int debug) [static, read]
Find the debug or verbose file setting.
debug 1 for debug, 0 for verbose
Definition at line 308 of file cli.c.
References AST_LIST_TRAVERSE, and ast_debug_file::filename.
Referenced by handle_verbose().
{
   struct ast_debug_file *df = NULL;
   struct debug_file_list *dfl = debug ? &debug_files : &verbose_files;
   AST_LIST_TRAVERSE(dfl, df, entry) {
      if (!strcasecmp(df->filename, fn))
         break;
   }
   return df;
}
static char* group_show_channels (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1411 of file cli.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_app_group_list_head(), ast_app_group_list_rdlock(), ast_app_group_list_unlock(), ast_cli(), AST_LIST_NEXT, ast_strlen_zero(), ast_group_info::category, ast_group_info::chan, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ESS, ast_cli_args::fd, FORMAT_STRING, ast_group_info::group, and ast_cli_entry::usage.
{
#define FORMAT_STRING  "%-25s  %-20s  %-20s\n"
   struct ast_group_info *gi = NULL;
   int numchans = 0;
   regex_t regexbuf;
   int havepattern = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "group show channels";
      e->usage =
         "Usage: group show channels [pattern]\n"
         "       Lists all currently active channels with channel group(s) specified.\n"
         "       Optional regular expression pattern is matched to group names for each\n"
         "       channel.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc < 3 || a->argc > 4)
      return CLI_SHOWUSAGE;
   if (a->argc == 4) {
      if (regcomp(&regexbuf, a->argv[3], REG_EXTENDED | REG_NOSUB))
         return CLI_SHOWUSAGE;
      havepattern = 1;
   }
   ast_cli(a->fd, FORMAT_STRING, "Channel", "Group", "Category");
   ast_app_group_list_rdlock();
   gi = ast_app_group_list_head();
   while (gi) {
      if (!havepattern || !regexec(&regexbuf, gi->group, 0, NULL, 0)) {
         ast_cli(a->fd, FORMAT_STRING, gi->chan->name, gi->group, (ast_strlen_zero(gi->category) ? "(default)" : gi->category));
         numchans++;
      }
      gi = AST_LIST_NEXT(gi, group_list);
   }
   ast_app_group_list_unlock();
   if (havepattern)
      regfree(&regexbuf);
   ast_cli(a->fd, "%d active channel%s\n", numchans, ESS(numchans));
   return CLI_SUCCESS;
#undef FORMAT_STRING
}
static char* handle_chanlist (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 790 of file cli.c.
References ast_channel::_state, ast_channel::amaflags, ast_channel::appl, ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_active_calls(), ast_bridged_channel(), ast_channel_unlock, ast_channel_walk_locked(), ast_cli(), ast_processed_calls(), ast_state2str(), ast_strlen_zero(), ast_tvdiff_ms(), ast_tvnow(), ast_tvzero(), ast_channel::cdr, ast_channel::cid, ast_callerid::cid_num, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, CONCISE_FORMAT_STRING, ast_channel::context, ast_channel::data, ESS, ast_channel::exten, ast_cli_args::fd, FORMAT_STRING, FORMAT_STRING2, option_maxcalls, ast_channel::priority, S_OR, ast_cdr::start, ast_cli_entry::usage, VERBOSE_FORMAT_STRING, and VERBOSE_FORMAT_STRING2.
{
#define FORMAT_STRING  "%-20.20s %-20.20s %-7.7s %-30.30s\n"
#define FORMAT_STRING2 "%-20.20s %-20.20s %-7.7s %-30.30s\n"
#define CONCISE_FORMAT_STRING  "%s!%s!%s!%d!%s!%s!%s!%s!%s!%d!%s!%s!%s\n"
#define VERBOSE_FORMAT_STRING  "%-20.20s %-20.20s %-16.16s %4d %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
#define VERBOSE_FORMAT_STRING2 "%-20.20s %-20.20s %-16.16s %-4.4s %-7.7s %-12.12s %-25.25s %-15.15s %8.8s %-11.11s %-20.20s\n"
   struct ast_channel *c = NULL;
   int numchans = 0, concise = 0, verbose = 0, count = 0;
   int fd, argc;
   char **argv;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show channels [concise|verbose|count]";
      e->usage =
         "Usage: core show channels [concise|verbose|count]\n"
         "       Lists currently defined channels and some information about them. If\n"
         "       'concise' is specified, the format is abridged and in a more easily\n"
         "       machine parsable format. If 'verbose' is specified, the output includes\n"
         "       more and longer fields. If 'count' is specified only the channel and call\n"
         "       count is output.\n"
         "  The 'concise' option is deprecated and will be removed from future versions\n"
         "  of Asterisk.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   fd = a->fd;
   argc = a->argc;
   argv = a->argv;
   if (a->argc == e->args) {
      if (!strcasecmp(argv[e->args-1],"concise"))
         concise = 1;
      else if (!strcasecmp(argv[e->args-1],"verbose"))
         verbose = 1;
      else if (!strcasecmp(argv[e->args-1],"count"))
         count = 1;
      else
         return CLI_SHOWUSAGE;
   } else if (a->argc != e->args - 1)
      return CLI_SHOWUSAGE;
   if (!count) {
      if (!concise && !verbose)
         ast_cli(fd, FORMAT_STRING2, "Channel", "Location", "State", "Application(Data)");
      else if (verbose)
         ast_cli(fd, VERBOSE_FORMAT_STRING2, "Channel", "Context", "Extension", "Priority", "State", "Application", "Data",
            "CallerID", "Duration", "Accountcode", "BridgedTo");
   }
   while ((c = ast_channel_walk_locked(c)) != NULL) {
      struct ast_channel *bc = ast_bridged_channel(c);
      char durbuf[10] = "-";
      if (!count) {
         if ((concise || verbose)  && c->cdr && !ast_tvzero(c->cdr->start)) {
            int duration = (int)(ast_tvdiff_ms(ast_tvnow(), c->cdr->start) / 1000);
            if (verbose) {
               int durh = duration / 3600;
               int durm = (duration % 3600) / 60;
               int durs = duration % 60;
               snprintf(durbuf, sizeof(durbuf), "%02d:%02d:%02d", durh, durm, durs);
            } else {
               snprintf(durbuf, sizeof(durbuf), "%d", duration);
            }
         }
         if (concise) {
            ast_cli(fd, CONCISE_FORMAT_STRING, c->name, c->context, c->exten, c->priority, ast_state2str(c->_state),
               c->appl ? c->appl : "(None)",
               S_OR(c->data, ""),   /* XXX different from verbose ? */
               S_OR(c->cid.cid_num, ""),
               S_OR(c->accountcode, ""),
               c->amaflags,
               durbuf,
               bc ? bc->name : "(None)",
               c->uniqueid);
         } else if (verbose) {
            ast_cli(fd, VERBOSE_FORMAT_STRING, c->name, c->context, c->exten, c->priority, ast_state2str(c->_state),
               c->appl ? c->appl : "(None)",
               c->data ? S_OR(c->data, "(Empty)" ): "(None)",
               S_OR(c->cid.cid_num, ""),
               durbuf,
               S_OR(c->accountcode, ""),
               bc ? bc->name : "(None)");
         } else {
            char locbuf[40] = "(None)";
            char appdata[40] = "(None)";
            if (!ast_strlen_zero(c->context) && !ast_strlen_zero(c->exten))
               snprintf(locbuf, sizeof(locbuf), "%s@%s:%d", c->exten, c->context, c->priority);
            if (c->appl)
               snprintf(appdata, sizeof(appdata), "%s(%s)", c->appl, S_OR(c->data, ""));
            ast_cli(fd, FORMAT_STRING, c->name, locbuf, ast_state2str(c->_state), appdata);
         }
      }
      numchans++;
      ast_channel_unlock(c);
   }
   if (!concise) {
      ast_cli(fd, "%d active channel%s\n", numchans, ESS(numchans));
      if (option_maxcalls)
         ast_cli(fd, "%d of %d max active call%s (%5.2f%% of capacity)\n",
            ast_active_calls(), option_maxcalls, ESS(ast_active_calls()),
            ((double)ast_active_calls() / (double)option_maxcalls) * 100.0);
      else
         ast_cli(fd, "%d active call%s\n", ast_active_calls(), ESS(ast_active_calls()));
      ast_cli(fd, "%d call%s processed\n", ast_processed_calls(), ESS(ast_processed_calls()));
   }
   return CLI_SUCCESS;
#undef FORMAT_STRING
#undef FORMAT_STRING2
#undef CONCISE_FORMAT_STRING
#undef VERBOSE_FORMAT_STRING
#undef VERBOSE_FORMAT_STRING2
}
static char* handle_cli_check_permissions (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handles CLI command 'cli check permissions'
Definition at line 1004 of file cli.c.
References ast_cli_entry::_full_cmd, ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_generator(), ast_join(), AST_MAX_ARGS, ast_strdupa, ast_strlen_zero(), CLI_FAILURE, CLI_GENERATE, cli_has_permissions(), CLI_INIT, cli_next(), CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, cli_perm::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, S_OR, ast_cli_entry::summary, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct passwd *pw = NULL;
   struct group *gr;
   int gid = -1, uid = -1;
   char command[AST_MAX_ARGS] = "";
   struct ast_cli_entry *ce = NULL;
   int found = 0;
   char *group, *tmp;
   switch (cmd) {
   case CLI_INIT:
      e->command = "cli check permissions";
      e->usage =
         "Usage: cli check permissions {<username>|@<groupname>|<username>@<groupname>} [<command>]\n"
         "       Check permissions config for a user@group or list the allowed commands for the specified user.\n"
         "       The username or the groupname may be omitted.\n";
      return NULL;
   case CLI_GENERATE:
      if (a->pos >= 4) {
         return ast_cli_generator(a->line + strlen("cli check permissions") + strlen(a->argv[3]) + 1, a->word, a->n);
      }
      return NULL;
   }
   if (a->argc < 4) {
      return CLI_SHOWUSAGE;
   }
   tmp = ast_strdupa(a->argv[3]);
   group = strchr(tmp, '@');
   if (group) {
      gr = getgrnam(&group[1]);
      if (!gr) {
         ast_cli(a->fd, "Unknown group '%s'\n", &group[1]);
         return CLI_FAILURE;
      }
      group[0] = '\0';
      gid = gr->gr_gid;
   }
   if (!group && ast_strlen_zero(tmp)) {
      ast_cli(a->fd, "You didn't supply a username\n");
   } else if (!ast_strlen_zero(tmp) && !(pw = getpwnam(tmp))) {
      ast_cli(a->fd, "Unknown user '%s'\n", tmp);
      return CLI_FAILURE;
   } else if (pw) {
      uid = pw->pw_uid;
   }
   if (a->argc == 4) {
      while ((ce = cli_next(ce))) {
         /* Hide commands that start with '_' */
         if (ce->_full_cmd[0] == '_') {
            continue;
         }
         if (cli_has_permissions(uid, gid, ce->_full_cmd)) {
            ast_cli(a->fd, "%30.30s %s\n", ce->_full_cmd, S_OR(ce->summary, "<no description available>"));
            found++;
         }
      }
      if (!found) {
         ast_cli(a->fd, "You are not allowed to run any command on Asterisk\n");
      }
   } else {
      ast_join(command, sizeof(command), a->argv + 4);
      ast_cli(a->fd, "%s '%s%s%s' is %s to run command: '%s'\n", uid >= 0 ? "User" : "Group", tmp,
         group && uid >= 0 ? "@" : "",
         group ? &group[1] : "",
         cli_has_permissions(uid, gid, command) ? "allowed" : "not allowed", command);
   }
   return CLI_SUCCESS;
}
static char* handle_cli_reload_permissions (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handles CLI command 'cli reload permissions'
Definition at line 985 of file cli.c.
References ast_cli_perms_init(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, and ast_cli_entry::usage.
{
   switch (cmd) {
   case CLI_INIT:
      e->command = "cli reload permissions";
      e->usage =
         "Usage: cli reload permissions\n"
         "       Reload the 'cli_permissions.conf' file.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   ast_cli_perms_init(1);
   return CLI_SUCCESS;
}
static char* handle_cli_show_permissions (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
handles CLI command 'cli show permissions'
Definition at line 940 of file cli.c.
References ast_cli(), AST_LIST_TRAVERSE, AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, cli_perm::command, ast_cli_entry::command, ast_cli_args::fd, usergroup_cli_perm::gid, cli_perm::permit, usergroup_cli_perm::perms, usergroup_cli_perm::uid, and ast_cli_entry::usage.
{
   struct usergroup_cli_perm *cp;
   struct cli_perm *perm;
   struct passwd *pw = NULL;
   struct group *gr = NULL;
   switch (cmd) {
   case CLI_INIT:
      e->command = "cli show permissions";
      e->usage =
         "Usage: cli show permissions\n"
         "       Shows CLI configured permissions.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   AST_RWLIST_RDLOCK(&cli_perms);
   AST_LIST_TRAVERSE(&cli_perms, cp, list) {
      if (cp->uid >= 0) {
         pw = getpwuid(cp->uid);
         if (pw) {
            ast_cli(a->fd, "user: %s [uid=%d]\n", pw->pw_name, cp->uid);
         }
      } else {
         gr = getgrgid(cp->gid);
         if (gr) {
            ast_cli(a->fd, "group: %s [gid=%d]\n", gr->gr_name, cp->gid);
         }
      }
      ast_cli(a->fd, "Permissions:\n");
      if (cp->perms) {
         AST_LIST_TRAVERSE(cp->perms, perm, list) {
            ast_cli(a->fd, "\t%s -> %s\n", perm->permit ? "permit" : "deny", perm->command);
         }
      }
      ast_cli(a->fd, "\n");
   }
   AST_RWLIST_UNLOCK(&cli_perms);
   return CLI_SUCCESS;
}
static char* handle_commandcomplete (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1162 of file cli.c.
References __ast_cli_generator(), ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_free, buf, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, and ast_cli_entry::usage.
{
   char *buf;
   switch (cmd) {
   case CLI_INIT:
      e->command = "_command complete";
      e->usage =
         "Usage: _command complete \"<line>\" text state\n"
         "       This function is used internally to help with command completion and should.\n"
         "       never be called by the user directly.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 5)
      return CLI_SHOWUSAGE;
   buf = __ast_cli_generator(a->argv[2], a->argv[3], atoi(a->argv[4]), 0);
   if (buf) {
      ast_cli(a->fd, "%s", buf);
      ast_free(buf);
   } else
      ast_cli(a->fd, "NULL\n");
   return CLI_SUCCESS;
}
static char* handle_commandmatchesarray (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1081 of file cli.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), AST_CLI_COMPLETE_EOF, ast_cli_completion_matches(), ast_free, ast_malloc, ast_realloc, buf, CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, len(), and ast_cli_entry::usage.
{
   char *buf, *obuf;
   int buflen = 2048;
   int len = 0;
   char **matches;
   int x, matchlen;
   switch (cmd) {
   case CLI_INIT:
      e->command = "_command matchesarray";
      e->usage =
         "Usage: _command matchesarray \"<line>\" text \n"
         "       This function is used internally to help with command completion and should.\n"
         "       never be called by the user directly.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   if (!(buf = ast_malloc(buflen)))
      return CLI_FAILURE;
   buf[len] = '\0';
   matches = ast_cli_completion_matches(a->argv[2], a->argv[3]);
   if (matches) {
      for (x=0; matches[x]; x++) {
         matchlen = strlen(matches[x]) + 1;
         if (len + matchlen >= buflen) {
            buflen += matchlen * 3;
            obuf = buf;
            if (!(buf = ast_realloc(obuf, buflen)))
               /* Memory allocation failure...  Just free old buffer and be done */
               ast_free(obuf);
         }
         if (buf)
            len += sprintf( buf + len, "%s ", matches[x]);
         ast_free(matches[x]);
         matches[x] = NULL;
      }
      ast_free(matches);
   }
   if (buf) {
      ast_cli(a->fd, "%s%s",buf, AST_CLI_COMPLETE_EOF);
      ast_free(buf);
   } else
      ast_cli(a->fd, "NULL\n");
   return CLI_SUCCESS;
}
static char* handle_commandnummatches (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1136 of file cli.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_cli_generatornummatches(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, and ast_cli_entry::usage.
{
   int matches = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "_command nummatches";
      e->usage =
         "Usage: _command nummatches \"<line>\" text \n"
         "       This function is used internally to help with command completion and should.\n"
         "       never be called by the user directly.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   matches = ast_cli_generatornummatches(a->argv[2], a->argv[3]);
   ast_cli(a->fd, "%d", matches);
   return CLI_SUCCESS;
}
static char* handle_core_set_debug_channel (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1187 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_unlock, ast_channel_walk_locked(), ast_cli(), ast_complete_channels(), ast_get_channel_by_name_locked(), ast_strdup, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, DEBUGCHAN_FLAG, ast_cli_args::fd, ast_channel::fin, ast_channel::fout, global_fin, global_fout, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
Referenced by handle_nodebugchan_deprecated().
{
   struct ast_channel *c = NULL;
   int is_all, is_off = 0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core set debug channel";
      e->usage =
         "Usage: core set debug channel <all|channel> [off]\n"
         "       Enables/disables debugging on all or on a specific channel.\n";
      return NULL;
   case CLI_GENERATE:
      /* XXX remember to handle the optional "off" */
      if (a->pos != e->args)
         return NULL;
      return a->n == 0 ? ast_strdup("all") : ast_complete_channels(a->line, a->word, a->pos, a->n - 1, e->args);
   }
   /* 'core set debug channel {all|chan_id}' */
   if (a->argc == e->args + 2) {
      if (!strcasecmp(a->argv[e->args + 1], "off"))
         is_off = 1;
      else
         return CLI_SHOWUSAGE;
   } else if (a->argc != e->args + 1)
      return CLI_SHOWUSAGE;
   is_all = !strcasecmp("all", a->argv[e->args]);
   if (is_all) {
      if (is_off) {
         global_fin &= ~DEBUGCHAN_FLAG;
         global_fout &= ~DEBUGCHAN_FLAG;
      } else {
         global_fin |= DEBUGCHAN_FLAG;
         global_fout |= DEBUGCHAN_FLAG;
      }
      c = ast_channel_walk_locked(NULL);
   } else {
      c = ast_get_channel_by_name_locked(a->argv[e->args]);
      if (c == NULL)
         ast_cli(a->fd, "No such channel %s\n", a->argv[e->args]);
   }
   while (c) {
      if (!(c->fin & DEBUGCHAN_FLAG) || !(c->fout & DEBUGCHAN_FLAG)) {
         if (is_off) {
            c->fin &= ~DEBUGCHAN_FLAG;
            c->fout &= ~DEBUGCHAN_FLAG;
         } else {
            c->fin |= DEBUGCHAN_FLAG;
            c->fout |= DEBUGCHAN_FLAG;
         }
         ast_cli(a->fd, "Debugging %s on channel %s\n", is_off ? "disabled" : "enabled", c->name);
      }
      ast_channel_unlock(c);
      if (!is_all)
         break;
      c = ast_channel_walk_locked(c);
   }
   ast_cli(a->fd, "Debugging on new channels is %s\n", is_off ? "disabled" : "enabled");
   return CLI_SUCCESS;
}
static char * handle_help (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1980 of file cli.c.
References __ast_cli_generator(), ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_join(), AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, find_cli(), help1(), ast_cli_args::line, ast_cli_args::n, ast_cli_entry::usage, and ast_cli_args::word.
{
   char fullcmd[80];
   struct ast_cli_entry *my_e;
   char *res = CLI_SUCCESS;
   if (cmd == CLI_INIT) {
      e->command = "core show help";
      e->usage =
         "Usage: core show help [topic]\n"
         "       When called with a topic as an argument, displays usage\n"
         "       information on the given command. If called without a\n"
         "       topic, it provides a list of commands.\n";
      return NULL;
   } else if (cmd == CLI_GENERATE) {
      /* skip first 14 or 15 chars, "core show help " */
      int l = strlen(a->line);
      if (l > 15) {
         l = 15;
      }
      /* XXX watch out, should stop to the non-generator parts */
      return __ast_cli_generator(a->line + l, a->word, a->n, 0);
   }
   if (a->argc == e->args) {
      return help1(a->fd, NULL, 0);
   }
   AST_RWLIST_RDLOCK(&helpers);
   my_e = find_cli(a->argv + 3, 1); /* try exact match first */
   if (!my_e) {
      res = help1(a->fd, a->argv + 3, 1 /* locked */);
      AST_RWLIST_UNLOCK(&helpers);
      return res;
   }
   if (my_e->usage)
      ast_cli(a->fd, "%s", my_e->usage);
   else {
      ast_join(fullcmd, sizeof(fullcmd), a->argv + 3);
      ast_cli(a->fd, "No help text available for '%s'.\n", fullcmd);
   }
   AST_RWLIST_UNLOCK(&helpers);
   return res;
}
static char* handle_load (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 244 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_load_resource(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_fn(), ast_cli_args::fd, ast_cli_args::n, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   /* "module load <mod>" */
   switch (cmd) {
   case CLI_INIT:
      e->command = "module load";
      e->usage =
         "Usage: module load <module name>\n"
         "       Loads the specified module into Asterisk.\n";
      return NULL;
   case CLI_GENERATE:
      if (a->pos != e->args)
         return NULL;
      return complete_fn(a->word, a->n);
   }
   if (a->argc != e->args + 1)
      return CLI_SHOWUSAGE;
   if (ast_load_resource(a->argv[e->args])) {
      ast_cli(a->fd, "Unable to load module %s\n", a->argv[e->args]);
      return CLI_FAILURE;
   }
   return CLI_SUCCESS;
}
static char* handle_logger_mute (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 517 of file cli.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_console_toggle_mute(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, and ast_cli_entry::usage.
{
   switch (cmd) {
   case CLI_INIT:
      e->command = "logger mute";
      e->usage =
         "Usage: logger mute\n"
         "       Disables logging output to the current console, making it possible to\n"
         "       gather information without being disturbed by scrolling lines.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc < 2 || a->argc > 3)
      return CLI_SHOWUSAGE;
   if (a->argc == 3 && !strcasecmp(a->argv[2], "silent"))
      ast_console_toggle_mute(a->fd, 1);
   else
      ast_console_toggle_mute(a->fd, 0);
   return CLI_SUCCESS;
}
static char* handle_modlist (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 696 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_module_helper(), ast_mutex_lock(), ast_mutex_unlock(), ast_update_module_list(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, climodentrylock, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, MODLIST_FORMAT2, modlist_modentry(), ast_cli_args::n, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   char *like;
   switch (cmd) {
   case CLI_INIT:
      e->command = "module show [like]";
      e->usage =
         "Usage: module show [like keyword]\n"
         "       Shows Asterisk modules currently in use, and usage statistics.\n";
      return NULL;
   case CLI_GENERATE:
      if (a->pos == e->args)
         return ast_module_helper(a->line, a->word, a->pos, a->n, a->pos, 0);
      else
         return NULL;
   }
   /* all the above return, so we proceed with the handler.
    * we are guaranteed to have argc >= e->args
    */
   if (a->argc == e->args - 1)
      like = "";
   else if (a->argc == e->args + 1 && !strcasecmp(a->argv[e->args-1], "like") )
      like = a->argv[e->args];
   else
      return CLI_SHOWUSAGE;
   ast_mutex_lock(&climodentrylock);
   climodentryfd = a->fd; /* global, protected by climodentrylock */
   ast_cli(a->fd, MODLIST_FORMAT2, "Module", "Description", "Use Count");
   ast_cli(a->fd,"%d modules loaded\n", ast_update_module_list(modlist_modentry, like));
   climodentryfd = -1;
   ast_mutex_unlock(&climodentrylock);
   return CLI_SUCCESS;
}
static char* handle_nodebugchan_deprecated (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1250 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, CLI_HANDLER, CLI_INIT, CLI_SHOWUSAGE, ast_cli_entry::command, and handle_core_set_debug_channel().
{
   char *res;
   if (cmd == CLI_HANDLER) {
      if (a->argc != e->args + 1)
         return CLI_SHOWUSAGE;
      /* pretend we have an extra "off" at the end. We can do this as the array
       * is NULL terminated so we overwrite that entry.
       */
      a->argv[e->args+1] = "off";
      a->argc++;
   }
   res = handle_core_set_debug_channel(e, cmd, a);
   if (cmd == CLI_INIT)
      e->command = "no debug channel";
   return res;
}
static char* handle_reload (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 269 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), ast_module_helper(), ast_module_reload(), CLI_GENERATE, CLI_INIT, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   int x;
   switch (cmd) {
   case CLI_INIT:
      e->command = "module reload";
      e->usage =
         "Usage: module reload [module ...]\n"
         "       Reloads configuration files for all listed modules which support\n"
         "       reloading, or for all supported modules if none are listed.\n";
      return NULL;
   case CLI_GENERATE:
      return ast_module_helper(a->line, a->word, a->pos, a->n, a->pos, 1);
   }
   if (a->argc == e->args) {
      ast_module_reload(NULL);
      return CLI_SUCCESS;
   }
   for (x = e->args; x < a->argc; x++) {
      int res = ast_module_reload(a->argv[x]);
      /* XXX reload has multiple error returns, including -1 on error and 2 on success */
      switch (res) {
      case 0:
         ast_cli(a->fd, "No such module '%s'\n", a->argv[x]);
         break;
      case 1:
         ast_cli(a->fd, "Module '%s' does not support reload\n", a->argv[x]);
         break;
      }
   }
   return CLI_SUCCESS;
}
static char* handle_showcalls (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 735 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_active_calls(), ast_cli(), ast_processed_calls(), ast_startuptime, ast_strdup, ast_tvnow(), ast_tvsub(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, ast_cli_entry::command, ESS, ast_cli_args::fd, ast_cli_args::n, option_maxcalls, ast_cli_args::pos, print_uptimestr(), RESULT_SUCCESS, and ast_cli_entry::usage.
{
   struct timeval curtime = ast_tvnow();
   int showuptime, printsec;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show calls [uptime]";
      e->usage =
         "Usage: core show calls [uptime] [seconds]\n"
         "       Lists number of currently active calls and total number of calls\n"
         "       processed through PBX since last restart. If 'uptime' is specified\n"
         "       the system uptime is also displayed. If 'seconds' is specified in\n"
         "       addition to 'uptime', the system uptime is displayed in seconds.\n";
      return NULL;
   case CLI_GENERATE:
      if (a->pos != e->args)
         return NULL;
      return a->n == 0  ? ast_strdup("seconds") : NULL;
   }
   /* regular handler */
   if (a->argc >= e->args && !strcasecmp(a->argv[e->args-1],"uptime")) {
      showuptime = 1;
      if (a->argc == e->args+1 && !strcasecmp(a->argv[e->args],"seconds"))
         printsec = 1;
      else if (a->argc == e->args)
         printsec = 0;
      else
         return CLI_SHOWUSAGE;
   } else if (a->argc == e->args-1) {
      showuptime = 0;
      printsec = 0;
   } else
      return CLI_SHOWUSAGE;
   if (option_maxcalls) {
      ast_cli(a->fd, "%d of %d max active call%s (%5.2f%% of capacity)\n",
         ast_active_calls(), option_maxcalls, ESS(ast_active_calls()),
         ((double)ast_active_calls() / (double)option_maxcalls) * 100.0);
   } else {
      ast_cli(a->fd, "%d active call%s\n", ast_active_calls(), ESS(ast_active_calls()));
   }
   ast_cli(a->fd, "%d call%s processed\n", ast_processed_calls(), ESS(ast_processed_calls()));
   if (ast_startuptime.tv_sec && showuptime) {
      print_uptimestr(a->fd, ast_tvsub(curtime, ast_startuptime), "System uptime", printsec);
   }
   return RESULT_SUCCESS;
}
static char* handle_showchan (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 1268 of file cli.c.
References ast_channel::_bridge, ast_channel::_state, ast_channel::appl, ast_cli_args::argc, ast_cli_args::argv, ast_bridged_channel(), ast_cdr_serialize_variables(), ast_channel_unlock, ast_cli(), ast_complete_channels(), AST_FLAG_BLOCKING, ast_get_channel_by_name_locked(), ast_getformatname_multiple(), ast_state2str(), ast_str_buffer(), ast_str_thread_get(), ast_test_flag, ast_tvnow(), ast_channel::blockproc, ast_channel::callgroup, ast_channel::cdr, ast_channel::cid, ast_callerid::cid_dnid, ast_callerid::cid_name, ast_callerid::cid_num, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_channel::context, ast_channel::data, DEBUGCHAN_FLAG, ast_channel::exten, ast_cli_args::fd, ast_channel::fds, ast_channel::fin, ast_channel::fout, ast_cli_args::line, ast_cli_args::n, name, ast_channel::nativeformats, pbx_builtin_serialize_variables(), ast_channel::pickupgroup, ast_cli_args::pos, ast_channel::priority, ast_channel::readformat, ast_channel::readtrans, ast_channel::rings, S_OR, sec, ast_cdr::start, ast_channel::tech, ast_channel_tech::type, ast_cli_entry::usage, ast_channel::whentohangup, ast_cli_args::word, ast_channel::writeformat, and ast_channel::writetrans.
{
   struct ast_channel *c=NULL;
   struct timeval now;
   struct ast_str *out = ast_str_thread_get(&ast_str_thread_global_buf, 16);
   char cdrtime[256];
   char nf[256], wf[256], rf[256];
   long elapsed_seconds=0;
   int hour=0, min=0, sec=0;
#ifdef CHANNEL_TRACE
   int trace_enabled;
#endif
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show channel";
      e->usage =
         "Usage: core show channel <channel>\n"
         "       Shows lots of information about the specified channel.\n";
      return NULL;
   case CLI_GENERATE:
      return ast_complete_channels(a->line, a->word, a->pos, a->n, 3);
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   now = ast_tvnow();
   c = ast_get_channel_by_name_locked(a->argv[3]);
   if (!c) {
      ast_cli(a->fd, "%s is not a known channel\n", a->argv[3]);
      return CLI_SUCCESS;
   }
   if (c->cdr) {
      elapsed_seconds = now.tv_sec - c->cdr->start.tv_sec;
      hour = elapsed_seconds / 3600;
      min = (elapsed_seconds % 3600) / 60;
      sec = elapsed_seconds % 60;
      snprintf(cdrtime, sizeof(cdrtime), "%dh%dm%ds", hour, min, sec);
   } else
      strcpy(cdrtime, "N/A");
   ast_cli(a->fd,
      " -- General --\n"
      "           Name: %s\n"
      "           Type: %s\n"
      "       UniqueID: %s\n"
      "      Caller ID: %s\n"
      " Caller ID Name: %s\n"
      "    DNID Digits: %s\n"
      "       Language: %s\n"
      "          State: %s (%d)\n"
      "          Rings: %d\n"
      "  NativeFormats: %s\n"
      "    WriteFormat: %s\n"
      "     ReadFormat: %s\n"
      " WriteTranscode: %s\n"
      "  ReadTranscode: %s\n"
      "1st File Descriptor: %d\n"
      "      Frames in: %d%s\n"
      "     Frames out: %d%s\n"
      " Time to Hangup: %ld\n"
      "   Elapsed Time: %s\n"
      "  Direct Bridge: %s\n"
      "Indirect Bridge: %s\n"
      " --   PBX   --\n"
      "        Context: %s\n"
      "      Extension: %s\n"
      "       Priority: %d\n"
      "     Call Group: %llu\n"
      "   Pickup Group: %llu\n"
      "    Application: %s\n"
      "           Data: %s\n"
      "    Blocking in: %s\n",
      c->name, c->tech->type, c->uniqueid,
      S_OR(c->cid.cid_num, "(N/A)"),
      S_OR(c->cid.cid_name, "(N/A)"),
      S_OR(c->cid.cid_dnid, "(N/A)"),
      c->language,
      ast_state2str(c->_state), c->_state, c->rings,
      ast_getformatname_multiple(nf, sizeof(nf), c->nativeformats),
      ast_getformatname_multiple(wf, sizeof(wf), c->writeformat),
      ast_getformatname_multiple(rf, sizeof(rf), c->readformat),
      c->writetrans ? "Yes" : "No",
      c->readtrans ? "Yes" : "No",
      c->fds[0],
      c->fin & ~DEBUGCHAN_FLAG, (c->fin & DEBUGCHAN_FLAG) ? " (DEBUGGED)" : "",
      c->fout & ~DEBUGCHAN_FLAG, (c->fout & DEBUGCHAN_FLAG) ? " (DEBUGGED)" : "",
      (long)c->whentohangup.tv_sec,
      cdrtime, c->_bridge ? c->_bridge->name : "<none>", ast_bridged_channel(c) ? ast_bridged_channel(c)->name : "<none>",
      c->context, c->exten, c->priority, c->callgroup, c->pickupgroup, ( c->appl ? c->appl : "(N/A)" ),
      ( c-> data ? S_OR(c->data, "(Empty)") : "(None)"),
      (ast_test_flag(c, AST_FLAG_BLOCKING) ? c->blockproc : "(Not Blocking)"));
   if (pbx_builtin_serialize_variables(c, &out))
      ast_cli(a->fd,"      Variables:\n%s\n", ast_str_buffer(out));
   if (c->cdr && ast_cdr_serialize_variables(c->cdr, &out, '=', '\n', 1))
      ast_cli(a->fd,"  CDR Variables:\n%s\n", ast_str_buffer(out));
#ifdef CHANNEL_TRACE
   trace_enabled = ast_channel_trace_is_enabled(c);
   ast_cli(a->fd, "  Context Trace: %s\n", trace_enabled ? "Enabled" : "Disabled");
   if (trace_enabled && ast_channel_trace_serialize(c, &out))
      ast_cli(a->fd, "          Trace:\n%s\n", ast_str_buffer(out));
#endif
   ast_channel_unlock(c);
   return CLI_SUCCESS;
}
static char* handle_showuptime (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 665 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_lastreloadtime, ast_startuptime, ast_tvnow(), ast_tvsub(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, print_uptimestr(), and ast_cli_entry::usage.
{
   struct timeval curtime = ast_tvnow();
   int printsec;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show uptime [seconds]";
      e->usage =
         "Usage: core show uptime [seconds]\n"
         "       Shows Asterisk uptime information.\n"
         "       The seconds word returns the uptime in seconds only.\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   /* regular handler */
   if (a->argc == e->args && !strcasecmp(a->argv[e->args-1],"seconds"))
      printsec = 1;
   else if (a->argc == e->args-1)
      printsec = 0;
   else
      return CLI_SHOWUSAGE;
   if (ast_startuptime.tv_sec)
      print_uptimestr(a->fd, ast_tvsub(curtime, ast_startuptime), "System uptime", printsec);
   if (ast_lastreloadtime.tv_sec)
      print_uptimestr(a->fd, ast_tvsub(curtime, ast_lastreloadtime), "Last reload", printsec);
   return CLI_SUCCESS;
}
static char* handle_softhangup (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 912 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_channel_unlock, ast_cli(), ast_complete_channels(), ast_get_channel_by_name_locked(), ast_softhangup(), AST_SOFTHANGUP_EXPLICIT, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, ast_cli_entry::usage, and ast_cli_args::word.
{
   struct ast_channel *c=NULL;
   switch (cmd) {
   case CLI_INIT:
      e->command = "channel request hangup";
      e->usage =
         "Usage: channel request hangup <channel>\n"
         "       Request that a channel be hung up. The hangup takes effect\n"
         "       the next time the driver reads or writes from the channel\n";
      return NULL;
   case CLI_GENERATE:
      return ast_complete_channels(a->line, a->word, a->pos, a->n, e->args);
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   c = ast_get_channel_by_name_locked(a->argv[3]);
   if (c) {
      ast_cli(a->fd, "Requested Hangup on channel '%s'\n", c->name);
      ast_softhangup(c, AST_SOFTHANGUP_EXPLICIT);
      ast_channel_unlock(c);
   } else
      ast_cli(a->fd, "%s is not a known channel\n", a->argv[3]);
   return CLI_SUCCESS;
}
static char* handle_unload (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 542 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_cli(), AST_FORCE_FIRM, AST_FORCE_HARD, AST_FORCE_SOFT, ast_module_helper(), ast_unload_resource(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, ast_cli_args::line, ast_cli_args::n, ast_cli_args::pos, s, ast_cli_entry::usage, and ast_cli_args::word.
{
   /* "module unload mod_1 [mod_2 .. mod_N]" */
   int x;
   int force = AST_FORCE_SOFT;
   char *s;
   switch (cmd) {
   case CLI_INIT:
      e->command = "module unload";
      e->usage =
         "Usage: module unload [-f|-h] <module_1> [<module_2> ... ]\n"
         "       Unloads the specified module from Asterisk. The -f\n"
         "       option causes the module to be unloaded even if it is\n"
         "       in use (may cause a crash) and the -h module causes the\n"
         "       module to be unloaded even if the module says it cannot, \n"
         "       which almost always will cause a crash.\n";
      return NULL;
   case CLI_GENERATE:
      return ast_module_helper(a->line, a->word, a->pos, a->n, a->pos, 0);
   }
   if (a->argc < e->args + 1)
      return CLI_SHOWUSAGE;
   x = e->args;   /* first argument */
   s = a->argv[x];
   if (s[0] == '-') {
      if (s[1] == 'f')
         force = AST_FORCE_FIRM;
      else if (s[1] == 'h')
         force = AST_FORCE_HARD;
      else
         return CLI_SHOWUSAGE;
      if (a->argc < e->args + 2) /* need at least one module name */
         return CLI_SHOWUSAGE;
      x++;  /* skip this argument */
   }
   for (; x < a->argc; x++) {
      if (ast_unload_resource(a->argv[x], force)) {
         ast_cli(a->fd, "Unable to unload resource %s\n", a->argv[x]);
         return CLI_FAILURE;
      }
   }
   return CLI_SUCCESS;
}
static char* handle_verbose (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 361 of file cli.c.
References ast_cli_args::argc, ast_cli_entry::args, ast_cli_args::argv, ast_calloc, ast_clear_flag, ast_cli(), ast_complete_source_filename(), ast_free, AST_OPT_FLAG_DEBUG_FILE, AST_OPT_FLAG_VERBOSE_FILE, ast_options, AST_RWLIST_EMPTY, AST_RWLIST_INSERT_TAIL, AST_RWLIST_REMOVE, AST_RWLIST_REMOVE_HEAD, AST_RWLIST_UNLOCK, AST_RWLIST_WRLOCK, ast_set_flag, ast_strdup, ast_strlen_zero(), CLI_FAILURE, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, complete_number(), debug, ast_cli_args::fd, ast_debug_file::filename, find_debug_file(), ast_debug_file::level, ast_cli_args::n, option_debug, option_verbose, ast_cli_args::pos, S_OR, and ast_cli_entry::usage.
{
   int oldval;
   int newlevel;
   int atleast = 0;
   int fd = a->fd;
   int argc = a->argc;
   char **argv = a->argv;
   char *argv3 = a->argv ? S_OR(a->argv[3], "") : "";
   int *dst;
   char *what;
   struct debug_file_list *dfl;
   struct ast_debug_file *adf;
   char *fn;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core set {debug|verbose}";
      e->usage =
#if !defined(LOW_MEMORY)
         "Usage: core set {debug|verbose} [atleast] <level> [filename]\n"
#else
         "Usage: core set {debug|verbose} [atleast] <level>\n"
#endif
         "       core set {debug|verbose} off\n"
#if !defined(LOW_MEMORY)
         "       Sets level of debug or verbose messages to be displayed or \n"
         "       sets a filename to display debug messages from.\n"
#else
         "       Sets level of debug or verbose messages to be displayed.\n"
#endif
         "  0 or off means no messages should be displayed.\n"
         "  Equivalent to -d[d[...]] or -v[v[v...]] on startup\n";
      return NULL;
   case CLI_GENERATE:
      if (a->pos == 3 || (a->pos == 4 && !strcasecmp(a->argv[3], "atleast"))) {
         char *pos = a->pos == 3 ? argv3 : S_OR(a->argv[4], "");
         int numbermatch = (ast_strlen_zero(pos) || strchr("123456789", pos[0])) ? 0 : 21;
         if (a->n < 21 && numbermatch == 0) {
            return complete_number(pos, 0, 0x7fffffff, a->n);
         } else if (pos[0] == '0') {
            if (a->n == 0) {
               return ast_strdup("0");
            } else {
               return NULL;
            }
         } else if (a->n == (21 - numbermatch)) {
            if (a->pos == 3 && !strncasecmp(argv3, "off", strlen(argv3))) {
               return ast_strdup("off");
            } else if (a->pos == 3 && !strncasecmp(argv3, "atleast", strlen(argv3))) {
               return ast_strdup("atleast");
            }
         } else if (a->n == (22 - numbermatch) && a->pos == 3 && ast_strlen_zero(argv3)) {
            return ast_strdup("atleast");
         }
#if !defined(LOW_MEMORY)
      } else if (a->pos == 4 || (a->pos == 5 && !strcasecmp(argv3, "atleast"))) {
         return ast_complete_source_filename(a->pos == 4 ? S_OR(a->argv[4], "") : S_OR(a->argv[5], ""), a->n);
#endif
      }
      return NULL;
   }
   /* all the above return, so we proceed with the handler.
    * we are guaranteed to be called with argc >= e->args;
    */
   if (argc <= e->args)
      return CLI_SHOWUSAGE;
   if (!strcasecmp(argv[e->args - 1], "debug")) {
      dst = &option_debug;
      oldval = option_debug;
      what = "Core debug";
   } else {
      dst = &option_verbose;
      oldval = option_verbose;
      what = "Verbosity";
   }
   if (argc == e->args + 1 && !strcasecmp(argv[e->args], "off")) {
      unsigned int debug = (*what == 'C');
      newlevel = 0;
      dfl = debug ? &debug_files : &verbose_files;
      AST_RWLIST_WRLOCK(dfl);
      while ((adf = AST_RWLIST_REMOVE_HEAD(dfl, entry)))
         ast_free(adf);
      ast_clear_flag(&ast_options, debug ? AST_OPT_FLAG_DEBUG_FILE : AST_OPT_FLAG_VERBOSE_FILE);
      AST_RWLIST_UNLOCK(dfl);
      goto done;
   }
   if (!strcasecmp(argv[e->args], "atleast"))
      atleast = 1;
   if (argc != e->args + atleast + 1 && argc != e->args + atleast + 2)
      return CLI_SHOWUSAGE;
   if (sscanf(argv[e->args + atleast], "%30d", &newlevel) != 1)
      return CLI_SHOWUSAGE;
   if (argc == e->args + atleast + 2) {
      unsigned int debug = (*what == 'C');
      dfl = debug ? &debug_files : &verbose_files;
      fn = argv[e->args + atleast + 1];
      AST_RWLIST_WRLOCK(dfl);
      if ((adf = find_debug_file(fn, debug)) && !newlevel) {
         AST_RWLIST_REMOVE(dfl, adf, entry);
         if (AST_RWLIST_EMPTY(dfl))
            ast_clear_flag(&ast_options, debug ? AST_OPT_FLAG_DEBUG_FILE : AST_OPT_FLAG_VERBOSE_FILE);
         AST_RWLIST_UNLOCK(dfl);
         ast_cli(fd, "%s was %d and has been set to 0 for '%s'\n", what, adf->level, fn);
         ast_free(adf);
         return CLI_SUCCESS;
      }
      if (adf) {
         if ((atleast && newlevel < adf->level) || adf->level == newlevel) {
            ast_cli(fd, "%s is %d for '%s'\n", what, adf->level, fn);
            AST_RWLIST_UNLOCK(dfl);
            return CLI_SUCCESS;
         }
      } else if (!(adf = ast_calloc(1, sizeof(*adf) + strlen(fn) + 1))) {
         AST_RWLIST_UNLOCK(dfl);
         return CLI_FAILURE;
      }
      oldval = adf->level;
      adf->level = newlevel;
      strcpy(adf->filename, fn);
      ast_set_flag(&ast_options, debug ? AST_OPT_FLAG_DEBUG_FILE : AST_OPT_FLAG_VERBOSE_FILE);
      AST_RWLIST_INSERT_TAIL(dfl, adf, entry);
      AST_RWLIST_UNLOCK(dfl);
      ast_cli(fd, "%s was %d and has been set to %d for '%s'\n", what, oldval, adf->level, adf->filename);
      return CLI_SUCCESS;
   }
done:
   if (!atleast || newlevel > *dst)
      *dst = newlevel;
   if (oldval > 0 && *dst == 0)
      ast_cli(fd, "%s is now OFF\n", what);
   else if (*dst > 0) {
      if (oldval == *dst)
         ast_cli(fd, "%s is at least %d\n", what, *dst);
      else
         ast_cli(fd, "%s was %d and is now %d\n", what, oldval, *dst);
   }
   return CLI_SUCCESS;
}
static char* help1 (int fd, char * match[], int locked) [static]
helper for final part of handle_help if locked = 1, assume the list is already locked
Definition at line 1951 of file cli.c.
References ast_cli_entry::_full_cmd, ast_cli(), ast_join(), AST_RWLIST_RDLOCK, AST_RWLIST_UNLOCK, cli_next(), CLI_SUCCESS, len(), S_OR, and ast_cli_entry::summary.
Referenced by handle_help().
{
   char matchstr[80] = "";
   struct ast_cli_entry *e = NULL;
   int len = 0;
   int found = 0;
   if (match) {
      ast_join(matchstr, sizeof(matchstr), match);
      len = strlen(matchstr);
   }
   if (!locked)
      AST_RWLIST_RDLOCK(&helpers);
   while ( (e = cli_next(e)) ) {
      /* Hide commands that start with '_' */
      if (e->_full_cmd[0] == '_')
         continue;
      if (match && strncasecmp(matchstr, e->_full_cmd, len))
         continue;
      ast_cli(fd, "%30.30s %s\n", e->_full_cmd, S_OR(e->summary, "<no description available>"));
      found++;
   }
   if (!locked)
      AST_RWLIST_UNLOCK(&helpers);
   if (!found && matchstr[0])
      ast_cli(fd, "No such command '%s'.\n", matchstr);
   return CLI_SUCCESS;
}
static char* is_prefix (const char * word, const char * token, int pos, int * actual) [static]
if word is a valid prefix for token, returns the pos-th match as a malloced string, or NULL otherwise. Always tell in *actual how many matches we got.
Definition at line 1722 of file cli.c.
References ast_strdup, ast_strdupa, ast_strlen_zero(), s, and strsep().
Referenced by __ast_cli_generator().
{
   int lw;
   char *s, *t1;
   *actual = 0;
   if (ast_strlen_zero(token))
      return NULL;
   if (ast_strlen_zero(word))
      word = "";  /* dummy */
   lw = strlen(word);
   if (strcspn(word, cli_rsvd) != lw)
      return NULL;   /* no match if word has reserved chars */
   if (strchr(cli_rsvd, token[0]) == NULL) { /* regular match */
      if (strncasecmp(token, word, lw))   /* no match */
         return NULL;
      *actual = 1;
      return (pos != 0) ? NULL : ast_strdup(token);
   }
   /* now handle regexp match */
   /* Wildcard always matches, so we never do is_prefix on them */
   t1 = ast_strdupa(token + 1);  /* copy, skipping first char */
   while (pos >= 0 && (s = strsep(&t1, cli_rsvd)) && *s) {
      if (*s == '%') /* wildcard */
         continue;
      if (strncasecmp(s, word, lw)) /* no match */
         continue;
      (*actual)++;
      if (pos-- == 0)
         return ast_strdup(s);
   }
   return NULL;
}
static int modlist_modentry (const char * module, const char * description, int usecnt, const char * like) [static]
Definition at line 595 of file cli.c.
References ast_cli(), MODLIST_FORMAT, and strcasestr().
Referenced by handle_modlist().
{
   /* Comparing the like with the module */
   if (strcasestr(module, like) ) {
      ast_cli(climodentryfd, MODLIST_FORMAT, module, description, usecnt);
      return 1;
   }
   return 0;
}
static int more_words (char *const * dst) [static]
returns true if there are more words to match
Definition at line 2157 of file cli.c.
Referenced by __ast_cli_generator().
{
   int i;
   for (i = 0; dst[i]; i++) {
      if (dst[i][0] != '[')
         return -1;
   }
   return 0;
}
static char* parse_args (const char * s, int * argc, char * argv[], int max, int * trailingwhitespace) [static]
Definition at line 2026 of file cli.c.
References ast_log(), ast_strdup, dummy(), and LOG_WARNING.
Referenced by __ast_cli_generator(), and ast_cli_command_full().
{
   char *duplicate, *cur;
   int x = 0;
   int quoted = 0;
   int escaped = 0;
   int whitespace = 1;
   int dummy = 0;
   if (trailingwhitespace == NULL)
      trailingwhitespace = &dummy;
   *trailingwhitespace = 0;
   if (s == NULL) /* invalid, though! */
      return NULL;
   /* make a copy to store the parsed string */
   if (!(duplicate = ast_strdup(s)))
      return NULL;
   cur = duplicate;
   /* scan the original string copying into cur when needed */
   for (; *s ; s++) {
      if (x >= max - 1) {
         ast_log(LOG_WARNING, "Too many arguments, truncating at %s\n", s);
         break;
      }
      if (*s == '"' && !escaped) {
         quoted = !quoted;
         if (quoted && whitespace) {
            /* start a quoted string from previous whitespace: new argument */
            argv[x++] = cur;
            whitespace = 0;
         }
      } else if ((*s == ' ' || *s == '\t') && !(quoted || escaped)) {
         /* If we are not already in whitespace, and not in a quoted string or
            processing an escape sequence, and just entered whitespace, then
            finalize the previous argument and remember that we are in whitespace
         */
         if (!whitespace) {
            *cur++ = '\0';
            whitespace = 1;
         }
      } else if (*s == '\\' && !escaped) {
         escaped = 1;
      } else {
         if (whitespace) {
            /* we leave whitespace, and are not quoted. So it's a new argument */
            argv[x++] = cur;
            whitespace = 0;
         }
         *cur++ = *s;
         escaped = 0;
      }
   }
   /* Null terminate */
   *cur++ = '\0';
   /* XXX put a NULL in the last argument, because some functions that take
    * the array may want a null-terminated array.
    * argc still reflects the number of non-NULL entries.
    */
   argv[x] = NULL;
   *argc = x;
   *trailingwhitespace = whitespace;
   return duplicate;
}
static void print_uptimestr (int fd, struct timeval timeval, const char * prefix, int printsec) [static]
Definition at line 605 of file cli.c.
References ast_cli(), ast_str_alloca, ast_str_append(), ast_str_buffer(), ast_str_strlen(), DAY, ESS, HOUR, MINUTE, NEEDCOMMA, WEEK, and YEAR.
Referenced by handle_showcalls(), and handle_showuptime().
{
   int x; /* the main part - years, weeks, etc. */
   struct ast_str *out;
#define SECOND (1)
#define MINUTE (SECOND*60)
#define HOUR (MINUTE*60)
#define DAY (HOUR*24)
#define WEEK (DAY*7)
#define YEAR (DAY*365)
#define NEEDCOMMA(x) ((x)? ",": "") /* define if we need a comma */
   if (timeval.tv_sec < 0) /* invalid, nothing to show */
      return;
   if (printsec)  {  /* plain seconds output */
      ast_cli(fd, "%s: %lu\n", prefix, (u_long)timeval.tv_sec);
      return;
   }
   out = ast_str_alloca(256);
   if (timeval.tv_sec > YEAR) {
      x = (timeval.tv_sec / YEAR);
      timeval.tv_sec -= (x * YEAR);
      ast_str_append(&out, 0, "%d year%s%s ", x, ESS(x),NEEDCOMMA(timeval.tv_sec));
   }
   if (timeval.tv_sec > WEEK) {
      x = (timeval.tv_sec / WEEK);
      timeval.tv_sec -= (x * WEEK);
      ast_str_append(&out, 0, "%d week%s%s ", x, ESS(x),NEEDCOMMA(timeval.tv_sec));
   }
   if (timeval.tv_sec > DAY) {
      x = (timeval.tv_sec / DAY);
      timeval.tv_sec -= (x * DAY);
      ast_str_append(&out, 0, "%d day%s%s ", x, ESS(x),NEEDCOMMA(timeval.tv_sec));
   }
   if (timeval.tv_sec > HOUR) {
      x = (timeval.tv_sec / HOUR);
      timeval.tv_sec -= (x * HOUR);
      ast_str_append(&out, 0, "%d hour%s%s ", x, ESS(x),NEEDCOMMA(timeval.tv_sec));
   }
   if (timeval.tv_sec > MINUTE) {
      x = (timeval.tv_sec / MINUTE);
      timeval.tv_sec -= (x * MINUTE);
      ast_str_append(&out, 0, "%d minute%s%s ", x, ESS(x),NEEDCOMMA(timeval.tv_sec));
   }
   x = timeval.tv_sec;
   if (x > 0 || ast_str_strlen(out) == 0) /* if there is nothing, print 0 seconds */
      ast_str_append(&out, 0, "%d second%s ", x, ESS(x));
   ast_cli(fd, "%s: %s\n", prefix, ast_str_buffer(out));
}
static int set_full_cmd (struct ast_cli_entry * e) [static]
initialize the _full_cmd string and related parameters, return 0 on success, -1 on error.
Definition at line 1519 of file cli.c.
References ast_cli_entry::_full_cmd, ast_cli_entry::args, ast_join(), ast_log(), ast_strdup, buf, ast_cli_entry::cmda, ast_cli_entry::cmdlen, and LOG_WARNING.
Referenced by __ast_cli_register().
{
   int i;
   char buf[80];
   ast_join(buf, sizeof(buf), e->cmda);
   e->_full_cmd = ast_strdup(buf);
   if (!e->_full_cmd) {
      ast_log(LOG_WARNING, "-- cannot allocate <%s>\n", buf);
      return -1;
   }
   e->cmdlen = strcspn(e->_full_cmd, cli_rsvd);
   for (i = 0; e->cmda[i]; i++)
      ;
   e->args = i;
   return 0;
}
static int word_match (const char * cmd, const char * cli_word) [static]
match a word in the CLI entry. returns -1 on mismatch, 0 on match of an optional word, 1 on match of a full word.
The pattern can be any_word match for equal [foo|bar|baz] optionally, one of these words {foo|bar|baz} exactly, one of these words % any word
Definition at line 1693 of file cli.c.
References ast_strlen_zero(), and strcasestr().
Referenced by __ast_cli_generator(), and find_cli().
{
   int l;
   char *pos;
   if (ast_strlen_zero(cmd) || ast_strlen_zero(cli_word))
      return -1;
   if (!strchr(cli_rsvd, cli_word[0])) /* normal match */
      return (strcasecmp(cmd, cli_word) == 0) ? 1 : -1;
   /* regexp match, takes [foo|bar] or {foo|bar} */
   l = strlen(cmd);
   /* wildcard match - will extend in the future */
   if (l > 0 && cli_word[0] == '%') {
      return 1;   /* wildcard */
   }
   pos = strcasestr(cli_word, cmd);
   if (pos == NULL) /* not found, say ok if optional */
      return cli_word[0] == '[' ? 0 : -1;
   if (pos == cli_word) /* no valid match at the beginning */
      return -1;
   if (strchr(cli_rsvd, pos[-1]) && strchr(cli_rsvd, pos[l]))
      return 1;   /* valid match */
   return -1;  /* not found */
}
Variable Documentation
struct ast_threadstorage ast_cli_buf = { .once = PTHREAD_ONCE_INIT , .key_init = __init_ast_cli_buf , .custom_init = NULL , } [static]
Definition at line 95 of file cli.c.
struct ast_cli_entry cli_cli[] [static]
Definition at line 1467 of file cli.c.
int cli_default_perm = 1 [static]
Default permissions value 1=Permit 0=Deny.
Definition at line 71 of file cli.c.
const char cli_rsvd[] = "[]{}|*%" [static]
Some regexp characters in cli arguments are reserved and used as separators.
Definition at line 1513 of file cli.c.
int climodentryfd = -1 [static]
Definition at line 593 of file cli.c.
ast_mutex_t climodentrylock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER) [static]
Definition at line 592 of file cli.c.
Referenced by handle_modlist().
struct debug_file_list debug_files [static]
list of filenames and their debug settings
Definition at line 91 of file cli.c.
const char perms_config[] = "cli_permissions.conf" [static]
CLI permissions config file.
Definition at line 69 of file cli.c.
Referenced by ast_cli_perms_init().
ast_mutex_t permsconfiglock = ((ast_mutex_t) PTHREAD_MUTEX_INITIALIZER) [static]
mutex used to prevent a user from running the 'cli reload permissions' command while it is already running.
Definition at line 75 of file cli.c.
struct debug_file_list verbose_files [static]
list of filenames and their verbose settings
Definition at line 93 of file cli.c.