Wed May 5 15:21:55 2010
Asterisk developer's documentation
codec_ulaw.c File Reference
codec_ulaw.c - translate between signed linear and ulaw
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/translate.h"
#include "asterisk/ulaw.h"
#include "asterisk/utils.h"
#include "asterisk/slin.h"
#include "ex_ulaw.h"
Defines
#define BUFFER_SAMPLES 8096
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_DEFAULT,"mu-Law Coder/Decoder",.load=load_module,.unload=unload_module,.reload=reload,)
static int lintoulaw_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert and store samples in outbuf
static int load_module (void)
static int parse_config (int reload)
static int reload (void)
static int ulawtolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert and store samples in outbuf
static int unload_module (void)
Variables
static struct ast_translator lintoulaw
The complete translator for LinToulaw.
static struct ast_translator ulawtolin
The complete translator for ulawToLin.
Detailed Description
codec_ulaw.c - translate between signed linear and ulaw
Definition in file codec_ulaw.c.
Define Documentation
#define BUFFER_SAMPLES 8096
Definition at line 36 of file codec_ulaw.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_DEFAULT , "mu-Law Coder/Decoder" , . load = load_module, . unload = unload_module, . reload = reload)
static int lintoulaw_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) [static]
convert and store samples in outbuf
Definition at line 60 of file codec_ulaw.c.
References AST_LIN2MU, ast_trans_pvt::c, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::samples, and ast_frame::samples.
{
   int i = f->samples;
   char *dst = pvt->outbuf.c + pvt->samples;
   int16_t *src = f->data.ptr;
   pvt->samples += i;
   pvt->datalen += i;   /* 1 byte/sample */
   while (i--)
      *dst++ = AST_LIN2MU(*src++);
   return 0;
}
static int load_module (void) [static]
Definition at line 138 of file codec_ulaw.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, ast_register_translator, ast_unregister_translator(), and parse_config().
{
   int res;
   if (parse_config(0))
      return AST_MODULE_LOAD_DECLINE;
   res = ast_register_translator(&ulawtolin);
   if (!res)
      res = ast_register_translator(&lintoulaw);
   else
      ast_unregister_translator(&ulawtolin);
   if (res)
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int parse_config (int reload) [static]
Definition at line 104 of file codec_ulaw.c.
References ast_config_destroy(), ast_config_load, ast_true(), ast_variable_browse(), ast_verb, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, ast_variable::name, ast_variable::next, ast_translator::useplc, ast_variable::value, and var.
Referenced by load_module(), and reload().
{
   struct ast_variable *var;
   struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
   struct ast_config *cfg = ast_config_load("codecs.conf", config_flags);
   if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEUNCHANGED || cfg == CONFIG_STATUS_FILEINVALID)
      return 0;
   for (var = ast_variable_browse(cfg, "plc"); var; var = var->next) {
      if (!strcasecmp(var->name, "genericplc")) {
         ulawtolin.useplc = ast_true(var->value) ? 1 : 0;
         ast_verb(3, "codec_ulaw: %susing generic PLC\n", ulawtolin.useplc ? "" : "not ");
      }
   }
   ast_config_destroy(cfg);
   return 0;
}
static int reload (void) [static]
Definition at line 121 of file codec_ulaw.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and parse_config().
{
   if (parse_config(1))
      return AST_MODULE_LOAD_DECLINE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int ulawtolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) [static]
convert and store samples in outbuf
Definition at line 43 of file codec_ulaw.c.
References AST_MULAW, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::i16, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::samples, and ast_frame::samples.
{
   int i = f->samples;
   unsigned char *src = f->data.ptr;
   int16_t *dst = pvt->outbuf.i16 + pvt->samples;
   pvt->samples += i;
   pvt->datalen += i * 2;  /* 2 bytes/sample */
   /* convert and copy in outbuf */
   while (i--)
      *dst++ = AST_MULAW(*src++);
   return 0;
}
static int unload_module (void) [static]
Definition at line 128 of file codec_ulaw.c.
References ast_unregister_translator().
{
   int res;
   res = ast_unregister_translator(&lintoulaw);
   res |= ast_unregister_translator(&ulawtolin);
   return res;
}
Variable Documentation
struct ast_translator lintoulaw [static]
The complete translator for LinToulaw.
Definition at line 94 of file codec_ulaw.c.
struct ast_translator ulawtolin [static]
The complete translator for ulawToLin.
Definition at line 79 of file codec_ulaw.c.