Wed May 5 15:21:55 2010
Asterisk developer's documentation
codec_alaw.c File Reference
codec_alaw.c - translate between signed linear and alaw
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/config.h"
#include "asterisk/translate.h"
#include "asterisk/alaw.h"
#include "asterisk/utils.h"
#include "asterisk/slin.h"
#include "ex_alaw.h"
Defines
#define BUFFER_SAMPLES 8096
Functions
static int alawtolin_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
decode frame into lin and fill output buffer.
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_DEFAULT,"A-law Coder/Decoder",.load=load_module,.unload=unload_module,.reload=reload,)
static int lintoalaw_framein (struct ast_trans_pvt *pvt, struct ast_frame *f)
convert and store input samples in output buffer
static int load_module (void)
static int parse_config (int reload)
static int reload (void)
standard module stuff
static int unload_module (void)
Variables
static struct ast_translator alawtolin
static struct ast_translator lintoalaw
Detailed Description
codec_alaw.c - translate between signed linear and alaw
Definition in file codec_alaw.c.
Define Documentation
#define BUFFER_SAMPLES 8096
Definition at line 36 of file codec_alaw.c.
Function Documentation
static int alawtolin_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) [static]
decode frame into lin and fill output buffer.
Definition at line 43 of file codec_alaw.c.
References AST_ALAW, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::i16, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::samples, and ast_frame::samples.
{
   int i = f->samples;
   unsigned char *src = f->data.ptr;
   int16_t *dst = pvt->outbuf.i16 + pvt->samples;
   pvt->samples += i;
   pvt->datalen += i * 2;  /* 2 bytes/sample */
   while (i--)
      *dst++ = AST_ALAW(*src++);
   return 0;
}
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_DEFAULT , "A-law Coder/Decoder" , . load = load_module, . unload = unload_module, . reload = reload)
static int lintoalaw_framein (struct ast_trans_pvt * pvt, struct ast_frame * f) [static]
convert and store input samples in output buffer
Definition at line 59 of file codec_alaw.c.
References AST_LIN2A, ast_trans_pvt::c, ast_frame::data, ast_trans_pvt::datalen, ast_trans_pvt::outbuf, ast_frame::ptr, ast_trans_pvt::samples, and ast_frame::samples.
{
   int i = f->samples;
   char *dst = pvt->outbuf.c + pvt->samples;
   int16_t *src = f->data.ptr;
   pvt->samples += i;
   pvt->datalen += i;   /* 1 byte/sample */
   while (i--)
      *dst++ = AST_LIN2A(*src++);
   return 0;
}
static int load_module (void) [static]
Definition at line 131 of file codec_alaw.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_FAILURE, AST_MODULE_LOAD_SUCCESS, ast_register_translator, ast_unregister_translator(), and parse_config().
{
   int res;
   if (parse_config(0))
      return AST_MODULE_LOAD_DECLINE;
   res = ast_register_translator(&alawtolin);
   if (!res)
      res = ast_register_translator(&lintoalaw);
   else
      ast_unregister_translator(&alawtolin);
   if (res)
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int parse_config (int reload) [static]
Definition at line 95 of file codec_alaw.c.
References ast_config_destroy(), ast_config_load, ast_true(), ast_variable_browse(), ast_verb, CONFIG_FLAG_FILEUNCHANGED, CONFIG_STATUS_FILEINVALID, CONFIG_STATUS_FILEMISSING, CONFIG_STATUS_FILEUNCHANGED, ast_variable::name, ast_variable::next, ast_translator::useplc, ast_variable::value, and var.
Referenced by load_module(), and reload().
{
   struct ast_variable *var;
   struct ast_flags config_flags = { reload ? CONFIG_FLAG_FILEUNCHANGED : 0 };
   struct ast_config *cfg = ast_config_load("codecs.conf", config_flags);
   if (cfg == CONFIG_STATUS_FILEMISSING || cfg == CONFIG_STATUS_FILEUNCHANGED || cfg == CONFIG_STATUS_FILEINVALID)
      return 0;
   for (var = ast_variable_browse(cfg, "plc"); var; var = var->next) {
      if (!strcasecmp(var->name, "genericplc")) {
         alawtolin.useplc = ast_true(var->value) ? 1 : 0;
         ast_verb(3, "codec_alaw: %susing generic PLC\n", alawtolin.useplc ? "" : "not ");
      }
   }
   ast_config_destroy(cfg);
   return 0;
}
static int reload (void) [static]
standard module stuff
Definition at line 114 of file codec_alaw.c.
References AST_MODULE_LOAD_DECLINE, AST_MODULE_LOAD_SUCCESS, and parse_config().
{
   if (parse_config(1))
      return AST_MODULE_LOAD_DECLINE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 121 of file codec_alaw.c.
References ast_unregister_translator().
{
   int res;
   res = ast_unregister_translator(&lintoalaw);
   res |= ast_unregister_translator(&alawtolin);
   return res;
}
Variable Documentation
struct ast_translator alawtolin [static]
Definition at line 74 of file codec_alaw.c.
struct ast_translator lintoalaw [static]
Definition at line 85 of file codec_alaw.c.