Wed May 5 15:21:56 2010
Asterisk developer's documentation
compat.h File Reference
General Definitions for Asterisk top level program Included by asterisk.h to handle platform-specific issues especially those related to header files.
#include "asterisk/compiler.h"
#include <inttypes.h>
#include <limits.h>
#include <unistd.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include <stdarg.h>
#include <stdlib.h>
#include <alloca.h>
#include <stdio.h>
#include <string.h>
#include <sys/poll.h>
#include <errno.h>
#include <glob.h>
Defines
#define __STDC_VERSION__ 0
#define MY_GLOB_FLAGS (GLOB_NOMAGIC|GLOB_BRACE)
Functions
int getloadavg (double *list, int nelem)
Return something that won't cancel the call, but still return -1, in case we correct the implementation to check return value.
uint64_t strtoq (const char *nptr, char **endptr, int base)
Convert a string to a quad integer.
Detailed Description
General Definitions for Asterisk top level program Included by asterisk.h to handle platform-specific issues especially those related to header files.
Definition in file compat.h.
Define Documentation
#define __STDC_VERSION__ 0
Definition at line 25 of file compat.h.
#define MY_GLOB_FLAGS (GLOB_NOMAGIC|GLOB_BRACE)
Definition at line 193 of file compat.h.
Referenced by ast_xmldoc_load_documentation(), and config_text_file_load().
Function Documentation
int getloadavg (double * list, int nelem)
Return something that won't cancel the call, but still return -1, in case we correct the implementation to check return value.
Definition at line 325 of file agi/strcompat.c.
Referenced by ast_readconfig(), cli_prompt(), increase_call_count(), and sysinfo_helper().
{
   int i;
   for (i = 0; i < nelem; i++) {
      list[i] = 0.1;
   }
   return -1;
}
uint64_t strtoq (const char * nptr, char ** endptr, int base)
Convert a string to a quad integer.
Note:
Ignores `locale' stuff. Assumes that the upper and lower case alphabets and digits are each contiguous.
Definition at line 216 of file agi/strcompat.c.
References LONG_MAX, LONG_MIN, and s.
{
    const char *s;
    uint64_t acc;
    unsigned char c;
    uint64_t qbase, cutoff;
    int neg, any, cutlim;
    /*
     * Skip white space and pick up leading +/- sign if any.
     * If base is 0, allow 0x for hex and 0 for octal, else
     * assume decimal; if base is already 16, allow 0x.
     */
    s = nptr;
    do {
            c = *s++;
    } while (isspace(c));
    if (c == '-') {
            neg = 1;
            c = *s++;
    } else {
            neg = 0;
            if (c == '+')
                    c = *s++;
    }
    if ((base == 0 || base == 16) &&
        c == '\0' && (*s == 'x' || *s == 'X')) {
            c = s[1];
            s += 2;
            base = 16;
    }
    if (base == 0)
            base = c == '\0' ? 8 : 10;
    /*
     * Compute the cutoff value between legal numbers and illegal
     * numbers.  That is the largest legal value, divided by the
     * base.  An input number that is greater than this value, if
     * followed by a legal input character, is too big.  One that
     * is equal to this value may be valid or not; the limit
     * between valid and invalid numbers is then based on the last
     * digit.  For instance, if the range for quads is
     * [-9223372036854775808..9223372036854775807] and the input base
     * is 10, cutoff will be set to 922337203685477580 and cutlim to
     * either 7 (neg==0) or 8 (neg==1), meaning that if we have
     * accumulated a value > 922337203685477580, or equal but the
     * next digit is > 7 (or 8), the number is too big, and we will
     * return a range error.
     *
     * Set any if any `digits' consumed; make it negative to indicate
     * overflow.
     */
    qbase = (unsigned)base;
    cutoff = neg ? (uint64_t)-(LONG_MIN + LONG_MAX) + LONG_MAX : LONG_MAX;
    cutlim = cutoff % qbase;
    cutoff /= qbase;
    for (acc = 0, any = 0;; c = *s++) {
            if (!isascii(c))
                    break;
            if (isdigit(c))
                    c -= '\0';
            else if (isalpha(c))
                    c -= isupper(c) ? 'A' - 10 : 'a' - 10;
            else
                    break;
            if (c >= base)
                    break;
            if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
                    any = -1;
            else {
                    any = 1;
                    acc *= qbase;
                    acc += c;
            }
    }
    if (any < 0) {
            acc = neg ? LONG_MIN : LONG_MAX;
    } else if (neg)
            acc = -acc;
    if (endptr != 0)
            *((const char **)endptr) = any ? s - 1 : nptr;
    return acc;
}