Wed May 5 15:21:58 2010
Asterisk developer's documentation
datastore.c File Reference
Asterisk datastore objects.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/datastore.h"
#include "asterisk/utils.h"
Functions
struct ast_datastore * __ast_datastore_alloc (const struct ast_datastore_info *info, const char *uid, const char *file, int line, const char *function)
Create a data store object.
struct ast_datastore * ast_datastore_alloc (const struct ast_datastore_info *info, const char *uid)
int ast_datastore_free (struct ast_datastore *datastore)
Free a data store object.
Detailed Description
Asterisk datastore objects.
Definition in file datastore.c.
Function Documentation
struct ast_datastore* __ast_datastore_alloc (const struct ast_datastore_info * info, const char * uid, const char * file, int line, const char * function) [read]
Create a data store object.
Parameters:
[in] info information describing the data store object
[in] uid unique identifer
Version:
1.6.1 moved here and renamed from ast_channel_datastore_alloc
Definition at line 31 of file datastore.c.
References __ast_calloc(), ast_calloc, ast_strdup, ast_datastore::info, and ast_datastore::uid.
Referenced by ast_datastore_alloc().
{
   struct ast_datastore *datastore = NULL;
   /* Make sure we at least have type so we can identify this */
   if (!info) {
      return NULL;
   }
#if defined(__AST_DEBUG_MALLOC)
   if (!(datastore = __ast_calloc(1, sizeof(*datastore), file, line, function))) {
      return NULL;
   }
#else
   if (!(datastore = ast_calloc(1, sizeof(*datastore)))) {
      return NULL;
   }
#endif
   datastore->info = info;
   datastore->uid = ast_strdup(uid);
   return datastore;
}
struct ast_datastore * ast_datastore_alloc (const struct ast_datastore_info * info, const char * uid) [read]
Definition at line 91 of file datastore.c.
References __ast_datastore_alloc().
{
   return __ast_datastore_alloc(info, uid, __FILE__, __LINE__, __FUNCTION__);
}
int ast_datastore_free (struct ast_datastore * datastore)
Free a data store object.
Parameters:
[in] datastore datastore to free
Version:
1.6.1 moved here and renamed from ast_channel_datastore_free
Definition at line 58 of file datastore.c.
References ast_free, ast_datastore::data, ast_datastore_info::destroy, ast_datastore::info, and ast_datastore::uid.
Referenced by acf_curlopt_write(), acf_fetch(), add_features_datastores(), add_to_agi(), ast_channel_datastore_free(), ast_channel_free(), ast_iax2_new(), audiohook_volume_get(), authenticate_reply(), chanspy_ds_free(), dial_exec_full(), disable_jack_hook(), exec_odbcfinish(), find_transaction(), free_session(), get_lock(), gosub_exec(), lua_get_state(), pbx_builtin_raise_exception(), setup_inheritance_datastore(), shared_write(), socket_process(), speex_write(), stop_mixmonitor_exec(), try_calling(), and volume_write().
{
   int res = 0;
   /* Using the destroy function (if present) destroy the data */
   if (datastore->info->destroy != NULL && datastore->data != NULL) {
      datastore->info->destroy(datastore->data);
      datastore->data = NULL;
   }
   /* Free allocated UID memory */
   if (datastore->uid != NULL) {
      ast_free((void *) datastore->uid);
      datastore->uid = NULL;
   }
   /* Finally free memory used by ourselves */
   ast_free(datastore);
   return res;
}