Wed May 5 15:22:06 2010
Asterisk developer's documentation
format_g723.c File Reference
Old-style G.723.1 frame/timestamp format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
Defines
#define G723_MAX_SIZE 1024
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"G.723.1 Simple Timestamp File Format",.load=load_module,.unload=unload_module,.load_pri=10,)
static struct ast_frame * g723_read (struct ast_filestream *s, int *whennext)
static int g723_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g723_tell (struct ast_filestream *fs)
static int g723_trunc (struct ast_filestream *fs)
static int g723_write (struct ast_filestream *s, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_format g723_1_f
Detailed Description
Old-style G.723.1 frame/timestamp format.
Extensions: g723, g723sf
Definition in file format_g723.c.
Define Documentation
#define G723_MAX_SIZE 1024
Definition at line 35 of file format_g723.c.
Referenced by g723_read().
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "G.723.1 Simple Timestamp File Format" , . load = load_module, . unload = unload_module, . load_pri = 10)
static struct ast_frame* g723_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 37 of file format_g723.c.
References AST_FORMAT_G723_1, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, G723_MAX_SIZE, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   unsigned short size;
   int res;
   int delay;
   /* Read the delay for the next packet, and schedule again if necessary */
   /* XXX is this ignored ? */
   if (fread(&delay, 1, 4, s->f) == 4)
      delay = ntohl(delay);
   else
      delay = -1;
   if (fread(&size, 1, 2, s->f) != 2) {
      /* Out of data, or the file is no longer valid.  In any case
         go ahead and stop the stream */
      return NULL;
   }
   /* Looks like we have a frame to read from here */
   size = ntohs(size);
   if (size > G723_MAX_SIZE) {
      ast_log(LOG_WARNING, "Size %d is invalid\n", size);
      /* The file is apparently no longer any good, as we
         shouldn't ever get frames even close to this
         size.  */
      return NULL;
   }
   /* Read the data into the buffer */
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_G723_1;
   s->fr.mallocd = 0;
   AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, size);
   if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != size) {
      ast_log(LOG_WARNING, "Short read (%d of %d bytes) (%s)!\n", res, size, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples = 240;
   return &s->fr;
}
static int g723_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 110 of file format_g723.c.
{
   return -1;
}
static off_t g723_tell (struct ast_filestream * fs) [static]
Definition at line 123 of file format_g723.c.
{
   return -1;
}
static int g723_trunc (struct ast_filestream * fs) [static]
Definition at line 115 of file format_g723.c.
References ast_filestream::f.
{
   /* Truncate file to current length */
   if (ftruncate(fileno(fs->f), ftello(fs->f)) < 0)
      return -1;
   return 0;
}
static int g723_write (struct ast_filestream * s, struct ast_frame * f) [static]
Definition at line 75 of file format_g723.c.
References AST_FORMAT_G723_1, AST_FRAME_VOICE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   uint32_t delay;
   uint16_t size;
   int res;
   /* XXX there used to be a check s->fr means a read stream */
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_G723_1) {
      ast_log(LOG_WARNING, "Asked to write non-g723 frame!\n");
      return -1;
   }
   delay = 0;
   if (f->datalen <= 0) {
      ast_log(LOG_WARNING, "Short frame ignored (%d bytes long?)\n", f->datalen);
      return 0;
   }
   if ((res = fwrite(&delay, 1, 4, s->f)) != 4) {
      ast_log(LOG_WARNING, "Unable to write delay: res=%d (%s)\n", res, strerror(errno));
      return -1;
   }
   size = htons(f->datalen);
   if ((res = fwrite(&size, 1, 2, s->f)) != 2) {
      ast_log(LOG_WARNING, "Unable to write size: res=%d (%s)\n", res, strerror(errno));
      return -1;
   }
   if ((res = fwrite(f->data.ptr, 1, f->datalen, s->f)) != f->datalen) {
      ast_log(LOG_WARNING, "Unable to write frame: res=%d (%s)\n", res, strerror(errno));
      return -1;
   }
   return 0;
}
static int load_module (void) [static]
Definition at line 140 of file format_g723.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&g723_1_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 147 of file format_g723.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(g723_1_f.name);
}
Variable Documentation
struct ast_format g723_1_f [static]
Definition at line 128 of file format_g723.c.