Wed May 5 15:22:06 2010
Asterisk developer's documentation
format_g729.c File Reference
Save to raw, headerless G729 data.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
Defines
#define BUF_SIZE 20
#define G729A_SAMPLES 160
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"Raw G729 data",.load=load_module,.unload=unload_module,.load_pri=10,)
static struct ast_frame * g729_read (struct ast_filestream *s, int *whennext)
static int g729_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t g729_tell (struct ast_filestream *fs)
static int g729_trunc (struct ast_filestream *fs)
static int g729_write (struct ast_filestream *fs, struct ast_frame *f)
static int load_module (void)
static int unload_module (void)
Variables
static struct ast_format g729_f
Detailed Description
Save to raw, headerless G729 data.
Note:
This is not an encoder/decoder. The codec fo g729 is only available with a commercial license from Digium, due to patent restrictions. Check http://www.digium.com for information.
Extensions: g729
Definition in file format_g729.c.
Define Documentation
#define BUF_SIZE 20
Definition at line 41 of file format_g729.c.
#define G729A_SAMPLES 160
Definition at line 42 of file format_g729.c.
Referenced by g729_read(), g729_seek(), and g729_tell().
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "Raw G729 data" , . load = load_module, . unload = unload_module, . load_pri = 10)
static struct ast_frame* g729_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 44 of file format_g729.c.
References AST_FORMAT_G729A, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, G729A_SAMPLES, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int res;
   /* Send a frame from the file to the appropriate channel */
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_G729A;
   s->fr.mallocd = 0;
   s->fr.samples = G729A_SAMPLES;
   AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
   if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) != s->fr.datalen) {
      if (res && (res != 10)) /* XXX what for ? */
         ast_log(LOG_WARNING, "Short read (%d) (%s)!\n", res, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples;
   return &s->fr;
}
static int g729_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 84 of file format_g729.c.
References BUF_SIZE, ast_filestream::f, G729A_SAMPLES, ast_frame::offset, and SEEK_FORCECUR.
{
   long bytes;
   off_t min,cur,max,offset=0;
   min = 0;
   cur = ftello(fs->f);
   fseeko(fs->f, 0, SEEK_END);
   max = ftello(fs->f);
   bytes = BUF_SIZE * (sample_offset / G729A_SAMPLES);
   if (whence == SEEK_SET)
      offset = bytes;
   else if (whence == SEEK_CUR || whence == SEEK_FORCECUR)
      offset = cur + bytes;
   else if (whence == SEEK_END)
      offset = max - bytes;
   if (whence != SEEK_FORCECUR) {
      offset = (offset > max)?max:offset;
   }
   /* protect against seeking beyond begining. */
   offset = (offset < min)?min:offset;
   if (fseeko(fs->f, offset, SEEK_SET) < 0)
      return -1;
   return 0;
}
static off_t g729_tell (struct ast_filestream * fs) [static]
Definition at line 118 of file format_g729.c.
References BUF_SIZE, ast_filestream::f, G729A_SAMPLES, and ast_frame::offset.
{
   off_t offset = ftello(fs->f);
   return (offset/BUF_SIZE)*G729A_SAMPLES;
}
static int g729_trunc (struct ast_filestream * fs) [static]
Definition at line 110 of file format_g729.c.
References ast_filestream::f.
{
   /* Truncate file to current length */
   if (ftruncate(fileno(fs->f), ftello(fs->f)) < 0)
      return -1;
   return 0;
}
static int g729_write (struct ast_filestream * fs, struct ast_frame * f) [static]
Definition at line 62 of file format_g729.c.
References AST_FORMAT_G729A, AST_FRAME_VOICE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res;
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_G729A) {
      ast_log(LOG_WARNING, "Asked to write non-G729 frame (%d)!\n", f->subclass);
      return -1;
   }
   if (f->datalen % 10) {
      ast_log(LOG_WARNING, "Invalid data length, %d, should be multiple of 10\n", f->datalen);
      return -1;
   }
   if ((res = fwrite(f->data.ptr, 1, f->datalen, fs->f)) != f->datalen) {
         ast_log(LOG_WARNING, "Bad write (%d/10): %s\n", res, strerror(errno));
         return -1;
   }
   return 0;
}
static int load_module (void) [static]
Definition at line 136 of file format_g729.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&g729_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 143 of file format_g729.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(g729_f.name);
}
Variable Documentation
struct ast_format g729_f [static]
Definition at line 124 of file format_g729.c.