Wed May 5 15:22:07 2010
Asterisk developer's documentation
format_vox.c File Reference
Flat, binary, ADPCM vox file format.
#include "asterisk.h"
#include "asterisk/mod_format.h"
#include "asterisk/module.h"
#include "asterisk/endian.h"
Defines
#define BUF_SIZE 80
#define VOX_SAMPLES 160
Functions
AST_MODULE_INFO (ASTERISK_GPL_KEY, AST_MODFLAG_LOAD_ORDER,"Dialogic VOX (ADPCM) File Format",.load=load_module,.unload=unload_module,.load_pri=10,)
static int load_module (void)
static int unload_module (void)
static struct ast_frame * vox_read (struct ast_filestream *s, int *whennext)
static int vox_seek (struct ast_filestream *fs, off_t sample_offset, int whence)
static off_t vox_tell (struct ast_filestream *fs)
static int vox_trunc (struct ast_filestream *fs)
static int vox_write (struct ast_filestream *s, struct ast_frame *f)
Variables
static struct ast_format vox_f
Detailed Description
Flat, binary, ADPCM vox file format.
File name extensions: vox
Definition in file format_vox.c.
Define Documentation
#define BUF_SIZE 80
Definition at line 35 of file format_vox.c.
#define VOX_SAMPLES 160
Definition at line 36 of file format_vox.c.
Function Documentation
AST_MODULE_INFO (ASTERISK_GPL_KEY , AST_MODFLAG_LOAD_ORDER , "Dialogic VOX (ADPCM) File Format" , . load = load_module, . unload = unload_module, . load_pri = 10)
static int load_module (void) [static]
Definition at line 123 of file format_vox.c.
References ast_format_register, AST_MODULE_LOAD_FAILURE, and AST_MODULE_LOAD_SUCCESS.
{
   if (ast_format_register(&vox_f))
      return AST_MODULE_LOAD_FAILURE;
   return AST_MODULE_LOAD_SUCCESS;
}
static int unload_module (void) [static]
Definition at line 130 of file format_vox.c.
References ast_format_unregister(), and ast_format::name.
{
   return ast_format_unregister(vox_f.name);
}
static struct ast_frame* vox_read (struct ast_filestream * s, int * whennext) [static, read]
Definition at line 38 of file format_vox.c.
References AST_FORMAT_ADPCM, AST_FRAME_SET_BUFFER, AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_filestream::buf, BUF_SIZE, ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_filestream::fr, ast_frame::frametype, LOG_WARNING, ast_frame::mallocd, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int res;
   /* Send a frame from the file to the appropriate channel */
   s->fr.frametype = AST_FRAME_VOICE;
   s->fr.subclass = AST_FORMAT_ADPCM;
   s->fr.mallocd = 0;
   AST_FRAME_SET_BUFFER(&s->fr, s->buf, AST_FRIENDLY_OFFSET, BUF_SIZE);
   if ((res = fread(s->fr.data.ptr, 1, s->fr.datalen, s->f)) < 1) {
      if (res)
         ast_log(LOG_WARNING, "Short read (%d) (%s)!\n", res, strerror(errno));
      return NULL;
   }
   *whennext = s->fr.samples = res * 2;
   s->fr.datalen = res;
   return &s->fr;
}
static int vox_seek (struct ast_filestream * fs, off_t sample_offset, int whence) [static]
Definition at line 75 of file format_vox.c.
References ast_filestream::f, ast_frame::offset, and SEEK_FORCECUR.
{
     off_t offset=0,min,cur,max,distance;
     min = 0;
     cur = ftello(fs->f);
     fseeko(fs->f, 0, SEEK_END);
    max = ftello(fs->f);
     /* have to fudge to frame here, so not fully to sample */
     distance = sample_offset/2;
     if(whence == SEEK_SET)
     offset = distance;
     else if(whence == SEEK_CUR || whence == SEEK_FORCECUR)
     offset = distance + cur;
     else if(whence == SEEK_END)
     offset = max - distance;
     if (whence != SEEK_FORCECUR) {
     offset = (offset > max)?max:offset;
     offset = (offset < min)?min:offset;
     }
     return fseeko(fs->f, offset, SEEK_SET);
}
static off_t vox_tell (struct ast_filestream * fs) [static]
Definition at line 104 of file format_vox.c.
References ast_filestream::f, and ast_frame::offset.
{
     off_t offset;
     offset = ftello(fs->f) << 1;
     return offset;
}
static int vox_trunc (struct ast_filestream * fs) [static]
Definition at line 99 of file format_vox.c.
References ast_filestream::f.
{
     return ftruncate(fileno(fs->f), ftello(fs->f));
}
static int vox_write (struct ast_filestream * s, struct ast_frame * f) [static]
Definition at line 57 of file format_vox.c.
References AST_FORMAT_ADPCM, AST_FRAME_VOICE, ast_log(), ast_frame::data, ast_frame::datalen, errno, ast_filestream::f, ast_frame::frametype, fwrite, LOG_WARNING, ast_frame::ptr, and ast_frame::subclass.
{
   int res;
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Asked to write non-voice frame!\n");
      return -1;
   }
   if (f->subclass != AST_FORMAT_ADPCM) {
      ast_log(LOG_WARNING, "Asked to write non-ADPCM frame (%d)!\n", f->subclass);
      return -1;
   }
   if ((res = fwrite(f->data.ptr, 1, f->datalen, s->f)) != f->datalen) {
         ast_log(LOG_WARNING, "Bad write (%d/%d): %s\n", res, f->datalen, strerror(errno));
         return -1;
   }
   return 0;
}
Variable Documentation
struct ast_format vox_f [static]
Definition at line 111 of file format_vox.c.