Wed May 5 15:22:07 2010
Asterisk developer's documentation
frame.c File Reference
Frame and codec manipulation routines.
#include "asterisk.h"
#include "asterisk/_private.h"
#include "asterisk/lock.h"
#include "asterisk/frame.h"
#include "asterisk/channel.h"
#include "asterisk/cli.h"
#include "asterisk/term.h"
#include "asterisk/utils.h"
#include "asterisk/threadstorage.h"
#include "asterisk/linkedlists.h"
#include "asterisk/translate.h"
#include "asterisk/dsp.h"
#include "asterisk/file.h"
Data Structures
struct ast_codec_alias_table
struct ast_frame_cache
struct ast_frames
This is just so ast_frames, a list head struct for holding a list of ast_frame structures, is defined.
struct ast_smoother
Defines
#define FRAME_CACHE_MAX_SIZE 10
Maximum ast_frame cache size.
#define SMOOTHER_SIZE 8000
#define TYPE_MASK 0x3
Enumerations
enum frame_type { TYPE_HIGH, TYPE_LOW, TYPE_SILENCE, TYPE_DONTSEND }
Functions
int __ast_smoother_feed (struct ast_smoother *s, struct ast_frame *f, int swap)
static void __frame_free (struct ast_frame *fr, int cache)
static void __init_frame_cache (void)
A per-thread cache of frame headers.
char * ast_codec2str (int codec)
Get a name from a format Gets a name from a format.
int ast_codec_choose (struct ast_codec_pref *pref, int formats, int find_best)
Pick a codec.
int ast_codec_get_len (int format, int samples)
Returns the number of bytes for the number of samples of the given format.
int ast_codec_get_samples (struct ast_frame *f)
Returns the number of samples contained in the frame.
int ast_codec_pref_append (struct ast_codec_pref *pref, int format)
Append codec to list.
void ast_codec_pref_convert (struct ast_codec_pref *pref, char *buf, size_t size, int right)
Shift an audio codec preference list up or down 65 bytes so that it becomes an ASCII string.
struct ast_format_list ast_codec_pref_getsize (struct ast_codec_pref *pref, int format)
Get packet size for codec.
int ast_codec_pref_index (struct ast_codec_pref *pref, int idx)
Codec located at a particular place in the preference index.
void ast_codec_pref_prepend (struct ast_codec_pref *pref, int format, int only_if_existing)
Prepend codec to list.
void ast_codec_pref_remove (struct ast_codec_pref *pref, int format)
Remove codec from pref list.
int ast_codec_pref_setsize (struct ast_codec_pref *pref, int format, int framems)
Set packet size for codec.
int ast_codec_pref_string (struct ast_codec_pref *pref, char *buf, size_t size)
Dump audio codec preference list into a string.
static const char * ast_expand_codec_alias (const char *in)
int ast_frame_adjust_volume (struct ast_frame *f, int adjustment)
Adjusts the volume of the audio samples contained in a frame.
void ast_frame_dump (const char *name, struct ast_frame *f, char *prefix)
void ast_frame_free (struct ast_frame *frame, int cache)
Requests a frame to be allocated.
static struct ast_frame * ast_frame_header_new (void)
int ast_frame_slinear_sum (struct ast_frame *f1, struct ast_frame *f2)
Sums two frames of audio samples.
struct ast_frame * ast_frdup (const struct ast_frame *f)
Copies a frame.
struct ast_frame * ast_frisolate (struct ast_frame *fr)
'isolates' a frame by duplicating non-malloc'ed components (header, src, data). On return all components are malloc'ed
struct ast_format_list * ast_get_format_list (size_t *size)
struct ast_format_list * ast_get_format_list_index (int idx)
int ast_getformatbyname (const char *name)
Gets a format from a name.
char * ast_getformatname (int format)
Get the name of a format.
char * ast_getformatname_multiple (char *buf, size_t size, int format)
Get the names of a set of formats.
int ast_parse_allow_disallow (struct ast_codec_pref *pref, int *mask, const char *list, int allowing)
Parse an "allow" or "deny" line in a channel or device configuration and update the capabilities mask and pref if provided. Video codecs are not added to codec preference lists, since we can not transcode.
void ast_smoother_free (struct ast_smoother *s)
int ast_smoother_get_flags (struct ast_smoother *s)
struct ast_smoother * ast_smoother_new (int size)
struct ast_frame * ast_smoother_read (struct ast_smoother *s)
void ast_smoother_reconfigure (struct ast_smoother *s, int bytes)
Reconfigure an existing smoother to output a different number of bytes per frame.
void ast_smoother_reset (struct ast_smoother *s, int bytes)
void ast_smoother_set_flags (struct ast_smoother *s, int flags)
int ast_smoother_test_flag (struct ast_smoother *s, int flag)
void ast_swapcopy_samples (void *dst, const void *src, int samples)
static void frame_cache_cleanup (void *data)
static int g723_len (unsigned char buf)
static int g723_samples (unsigned char *buf, int maxlen)
static unsigned char get_n_bits_at (unsigned char *data, int n, int bit)
int init_framer (void)
static char * show_codec_n (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static char * show_codecs (struct ast_cli_entry *e, int cmd, struct ast_cli_args *a)
static int smoother_frame_feed (struct ast_smoother *s, struct ast_frame *f, int swap)
static int speex_get_wb_sz_at (unsigned char *data, int len, int bit)
static int speex_samples (unsigned char *data, int len)
Variables
static struct ast_format_list AST_FORMAT_LIST []
Definition of supported media formats (codecs).
struct ast_frame ast_null_frame = { AST_FRAME_NULL, }
static struct ast_threadstorage frame_cache = { .once = PTHREAD_ONCE_INIT , .key_init = __init_frame_cache , .custom_init = NULL , }
static struct ast_cli_entry my_clis []
Detailed Description
Frame and codec manipulation routines.
Author:
Mark Spencer <markster@digium.com>
Definition in file frame.c.
Define Documentation
#define FRAME_CACHE_MAX_SIZE 10
Maximum ast_frame cache size.
In most cases where the frame header cache will be useful, the size of the cache will stay very small. However, it is not always the case that the same thread that allocates the frame will be the one freeing them, so sometimes a thread will never have any frames in its cache, or the cache will never be pulled from. For the latter case, we limit the maximum size.
Definition at line 58 of file frame.c.
#define SMOOTHER_SIZE 8000
Definition at line 70 of file frame.c.
Referenced by __ast_smoother_feed().
#define TYPE_MASK 0x3
Definition at line 79 of file frame.c.
Enumeration Type Documentation
enum frame_type
Enumerator:
TYPE_HIGH
TYPE_LOW
TYPE_SILENCE
TYPE_DONTSEND
Definition at line 72 of file frame.c.
                {
   TYPE_HIGH,     /* 0x0 */
   TYPE_LOW,      /* 0x1 */
   TYPE_SILENCE,  /* 0x2 */
   TYPE_DONTSEND  /* 0x3 */
};
Function Documentation
int __ast_smoother_feed (struct ast_smoother * s, struct ast_frame * f, int swap)
Definition at line 201 of file frame.c.
References AST_FRAME_VOICE, ast_log(), AST_MIN_OFFSET, AST_SMOOTHER_FLAG_G729, ast_swapcopy_samples(), ast_frame::data, ast_frame::datalen, ast_smoother::flags, ast_smoother::format, ast_frame::frametype, ast_smoother::len, LOG_WARNING, ast_frame::offset, ast_smoother::opt, ast_smoother::opt_needs_swap, ast_frame::ptr, ast_frame::samples, ast_smoother::samplesperbyte, ast_smoother::size, smoother_frame_feed(), SMOOTHER_SIZE, and ast_frame::subclass.
{
   if (f->frametype != AST_FRAME_VOICE) {
      ast_log(LOG_WARNING, "Huh?  Can't smooth a non-voice frame!\n");
      return -1;
   }
   if (!s->format) {
      s->format = f->subclass;
      s->samplesperbyte = (float)f->samples / (float)f->datalen;
   } else if (s->format != f->subclass) {
      ast_log(LOG_WARNING, "Smoother was working on %d format frames, now trying to feed %d?\n", s->format, f->subclass);
      return -1;
   }
   if (s->len + f->datalen > SMOOTHER_SIZE) {
      ast_log(LOG_WARNING, "Out of smoother space\n");
      return -1;
   }
   if (((f->datalen == s->size) ||
        ((f->datalen < 10) && (s->flags & AST_SMOOTHER_FLAG_G729))) &&
       !s->opt &&
       !s->len &&
       (f->offset >= AST_MIN_OFFSET)) {
      /* Optimize by sending the frame we just got
         on the next read, thus eliminating the douple
         copy */
      if (swap)
         ast_swapcopy_samples(f->data.ptr, f->data.ptr, f->samples);
      s->opt = f;
      s->opt_needs_swap = swap ? 1 : 0;
      return 0;
   }
   return smoother_frame_feed(s, f, swap);
}
static void __frame_free (struct ast_frame * fr, int cache) [static]
Definition at line 333 of file frame.c.
References ast_dsp_frame_freed(), ast_free, AST_FRFLAG_FROM_DSP, AST_FRFLAG_FROM_TRANSLATOR, AST_LIST_INSERT_HEAD, AST_MALLOCD_DATA, AST_MALLOCD_HDR, AST_MALLOCD_SRC, ast_test_flag, ast_threadstorage_get(), ast_translate_frame_freed(), ast_frame::data, frame_cache, FRAME_CACHE_MAX_SIZE, frames, ast_frame_cache::list, ast_frame::mallocd, ast_frame::offset, ast_frame::ptr, ast_frame_cache::size, and ast_frame::src.
Referenced by ast_frame_free().
{
   if (ast_test_flag(fr, AST_FRFLAG_FROM_TRANSLATOR)) {
      ast_translate_frame_freed(fr);
   } else if (ast_test_flag(fr, AST_FRFLAG_FROM_DSP)) {
      ast_dsp_frame_freed(fr);
   }
   if (!fr->mallocd)
      return;
#if !defined(LOW_MEMORY)
   if (cache && fr->mallocd == AST_MALLOCD_HDR) {
      /* Cool, only the header is malloc'd, let's just cache those for now
       * to keep things simple... */
      struct ast_frame_cache *frames;
      if ((frames = ast_threadstorage_get(&frame_cache, sizeof(*frames))) &&
          (frames->size < FRAME_CACHE_MAX_SIZE)) {
         AST_LIST_INSERT_HEAD(&frames->list, fr, frame_list);
         frames->size++;
         return;
      }
   }
#endif
   if (fr->mallocd & AST_MALLOCD_DATA) {
      if (fr->data.ptr)
         ast_free(fr->data.ptr - fr->offset);
   }
   if (fr->mallocd & AST_MALLOCD_SRC) {
      if (fr->src)
         ast_free((void *) fr->src);
   }
   if (fr->mallocd & AST_MALLOCD_HDR) {
      ast_free(fr);
   }
}
static void __init_frame_cache (void) [static]
A per-thread cache of frame headers.
Definition at line 47 of file frame.c.
{
char* ast_codec2str (int codec)
Get a name from a format Gets a name from a format.
Parameters:
codec codec number (1,2,4,8,16,etc.)
Returns:
This returns a static string identifying the format on success, 0 on error.
Definition at line 654 of file frame.c.
References ARRAY_LEN, and ast_format_list::desc.
Referenced by moh_alloc(), show_codec_n(), and show_codecs().
{
   int x;
   char *ret = "unknown";
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == codec) {
         ret = AST_FORMAT_LIST[x].desc;
         break;
      }
   }
   return ret;
}
int ast_codec_choose (struct ast_codec_pref * pref, int formats, int find_best)
Pick a codec.
Select the best audio format according to preference list from supplied options. If "find_best" is non-zero then if nothing is found, the "Best" format of the format list is selected, otherwise 0 is returned.
Definition at line 1211 of file frame.c.
References ARRAY_LEN, ast_best_codec(), ast_debug, AST_FORMAT_AUDIO_MASK, ast_format_list::bits, and ast_codec_pref::order.
Referenced by __oh323_new(), gtalk_new(), jingle_new(), process_sdp(), sip_new(), and socket_process().
{
   int x, ret = 0, slot;
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      slot = pref->order[x];
      if (!slot)
         break;
      if (formats & AST_FORMAT_LIST[slot-1].bits) {
         ret = AST_FORMAT_LIST[slot-1].bits;
         break;
      }
   }
   if (ret & AST_FORMAT_AUDIO_MASK)
      return ret;
   ast_debug(4, "Could not find preferred codec - %s\n", find_best ? "Going for the best codec" : "Returning zero codec");
      return find_best ? ast_best_codec(formats) : 0;
}
int ast_codec_get_len (int format, int samples)
Returns the number of bytes for the number of samples of the given format.
Definition at line 1484 of file frame.c.
References AST_FORMAT_ADPCM, AST_FORMAT_ALAW, AST_FORMAT_G722, AST_FORMAT_G723_1, AST_FORMAT_G726, AST_FORMAT_G726_AAL2, AST_FORMAT_G729A, AST_FORMAT_GSM, AST_FORMAT_ILBC, AST_FORMAT_SIREN14, AST_FORMAT_SIREN7, AST_FORMAT_SLINEAR, AST_FORMAT_SLINEAR16, AST_FORMAT_ULAW, ast_getformatname(), ast_log(), len(), and LOG_WARNING.
Referenced by moh_generate(), and monmp3thread().
{
   int len = 0;
   /* XXX Still need speex, and lpc10 XXX */
   switch(format) {
   case AST_FORMAT_G723_1:
      len = (samples / 240) * 20;
      break;
   case AST_FORMAT_ILBC:
      len = (samples / 240) * 50;
      break;
   case AST_FORMAT_GSM:
      len = (samples / 160) * 33;
      break;
   case AST_FORMAT_G729A:
      len = samples / 8;
      break;
   case AST_FORMAT_SLINEAR:
   case AST_FORMAT_SLINEAR16:
      len = samples * 2;
      break;
   case AST_FORMAT_ULAW:
   case AST_FORMAT_ALAW:
      len = samples;
      break;
   case AST_FORMAT_G722:
   case AST_FORMAT_ADPCM:
   case AST_FORMAT_G726:
   case AST_FORMAT_G726_AAL2:
      len = samples / 2;
      break;
   case AST_FORMAT_SIREN7:
      /* 16,000 samples per second at 32kbps is 4,000 bytes per second */
      len = samples / (16000 / 4000);
      break;
   case AST_FORMAT_SIREN14:
      /* 32,000 samples per second at 48kbps is 6,000 bytes per second */
      len = (int) samples / ((float) 32000 / 6000);
      break;
   default:
      ast_log(LOG_WARNING, "Unable to calculate sample length for format %s\n", ast_getformatname(format));
   }
   return len;
}
int ast_codec_get_samples (struct ast_frame * f)
Returns the number of samples contained in the frame.
Definition at line 1431 of file frame.c.
References AST_FORMAT_ADPCM, AST_FORMAT_ALAW, AST_FORMAT_G722, AST_FORMAT_G723_1, AST_FORMAT_G726, AST_FORMAT_G726_AAL2, AST_FORMAT_G729A, AST_FORMAT_GSM, AST_FORMAT_ILBC, AST_FORMAT_LPC10, AST_FORMAT_SIREN14, AST_FORMAT_SIREN7, AST_FORMAT_SLINEAR, AST_FORMAT_SLINEAR16, AST_FORMAT_SPEEX, AST_FORMAT_ULAW, ast_getformatname(), ast_log(), ast_frame::data, ast_frame::datalen, g723_samples(), LOG_WARNING, ast_frame::ptr, speex_samples(), and ast_frame::subclass.
Referenced by ast_rtp_read(), isAnsweringMachine(), moh_generate(), schedule_delivery(), socket_process(), and socket_process_meta().
{
   int samples = 0;
   switch(f->subclass) {
   case AST_FORMAT_SPEEX:
      samples = speex_samples(f->data.ptr, f->datalen);
      break;
   case AST_FORMAT_G723_1:
      samples = g723_samples(f->data.ptr, f->datalen);
      break;
   case AST_FORMAT_ILBC:
      samples = 240 * (f->datalen / 50);
      break;
   case AST_FORMAT_GSM:
      samples = 160 * (f->datalen / 33);
      break;
   case AST_FORMAT_G729A:
      samples = f->datalen * 8;
      break;
   case AST_FORMAT_SLINEAR:
   case AST_FORMAT_SLINEAR16:
      samples = f->datalen / 2;
      break;
   case AST_FORMAT_LPC10:
      /* assumes that the RTP packet contains one LPC10 frame */
      samples = 22 * 8;
      samples += (((char *)(f->data.ptr))[7] & 0x1) * 8;
      break;
   case AST_FORMAT_ULAW:
   case AST_FORMAT_ALAW:
      samples = f->datalen;
      break;
   case AST_FORMAT_G722:
   case AST_FORMAT_ADPCM:
   case AST_FORMAT_G726:
   case AST_FORMAT_G726_AAL2:
      samples = f->datalen * 2;
      break;
   case AST_FORMAT_SIREN7:
      /* 16,000 samples per second at 32kbps is 4,000 bytes per second */
      samples = f->datalen * (16000 / 4000);
      break;
   case AST_FORMAT_SIREN14:
      /* 32,000 samples per second at 48kbps is 6,000 bytes per second */
      samples = (int) f->datalen * ((float) 32000 / 6000);
      break;
   default:
      ast_log(LOG_WARNING, "Unable to calculate samples for format %s\n", ast_getformatname(f->subclass));
   }
   return samples;
}
int ast_codec_pref_append (struct ast_codec_pref * pref, int format)
Append codec to list.
Append a audio codec to a preference list, removing it first if it was already there.
Definition at line 1071 of file frame.c.
References ARRAY_LEN, ast_codec_pref_remove(), and ast_codec_pref::order.
Referenced by ast_parse_allow_disallow().
{
   int x, newindex = 0;
   ast_codec_pref_remove(pref, format);
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == format) {
         newindex = x + 1;
         break;
      }
   }
   if (newindex) {
      for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
         if (!pref->order[x]) {
            pref->order[x] = newindex;
            break;
         }
      }
   }
   return x;
}
void ast_codec_pref_convert (struct ast_codec_pref * pref, char * buf, size_t size, int right)
Shift an audio codec preference list up or down 65 bytes so that it becomes an ASCII string.
Definition at line 974 of file frame.c.
References ast_codec_pref::order.
Referenced by check_access(), create_addr(), dump_prefs(), and socket_process().
{
   int x, differential = (int) 'A', mem;
   char *from, *to;
   if (right) {
      from = pref->order;
      to = buf;
      mem = size;
   } else {
      to = pref->order;
      from = buf;
      mem = 32;
   }
   memset(to, 0, mem);
   for (x = 0; x < 32 ; x++) {
      if (!from[x])
         break;
      to[x] = right ? (from[x] + differential) : (from[x] - differential);
   }
}
struct ast_format_list ast_codec_pref_getsize (struct ast_codec_pref * pref, int format) [read]
Get packet size for codec.
Definition at line 1172 of file frame.c.
References ARRAY_LEN, ast_format_list::bits, ast_format_list::cur_ms, ast_format_list::def_ms, format, ast_format_list::inc_ms, ast_format_list::max_ms, and ast_format_list::min_ms.
Referenced by add_codec_to_sdp(), ast_rtp_bridge(), ast_rtp_codec_setpref(), ast_rtp_write(), handle_open_receive_channel_ack_message(), skinny_set_rtp_peer(), and transmit_connect().
{
   int x, idx = -1, framems = 0;
   struct ast_format_list fmt = { 0, };
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == format) {
         fmt = AST_FORMAT_LIST[x];
         idx = x;
         break;
      }
   }
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (pref->order[x] == (idx + 1)) {
         framems = pref->framing[x];
         break;
      }
   }
   /* size validation */
   if (!framems)
      framems = AST_FORMAT_LIST[idx].def_ms;
   if (AST_FORMAT_LIST[idx].inc_ms && framems % AST_FORMAT_LIST[idx].inc_ms) /* avoid division by zero */
      framems -= framems % AST_FORMAT_LIST[idx].inc_ms;
   if (framems < AST_FORMAT_LIST[idx].min_ms)
      framems = AST_FORMAT_LIST[idx].min_ms;
   if (framems > AST_FORMAT_LIST[idx].max_ms)
      framems = AST_FORMAT_LIST[idx].max_ms;
   fmt.cur_ms = framems;
   return fmt;
}
int ast_codec_pref_index (struct ast_codec_pref * pref, int index)
Codec located at a particular place in the preference index.
Audio Codec Preferences
Definition at line 1032 of file frame.c.
References ast_format_list::bits, and ast_codec_pref::order.
Referenced by _sip_show_peer(), _skinny_show_line(), add_sdp(), ast_codec_pref_string(), function_iaxpeer(), function_sippeer(), gtalk_invite(), handle_cli_iax2_show_peer(), jingle_accept_call(), print_codec_to_cli(), and socket_process().
{
   int slot = 0;
   if ((idx >= 0) && (idx < sizeof(pref->order))) {
      slot = pref->order[idx];
   }
   return slot ? AST_FORMAT_LIST[slot - 1].bits : 0;
}
void ast_codec_pref_prepend (struct ast_codec_pref * pref, int format, int only_if_existing)
Prepend codec to list.
Prepend an audio codec to a preference list, removing it first if it was already there.
Definition at line 1097 of file frame.c.
References ARRAY_LEN, ast_codec_pref::framing, and ast_codec_pref::order.
Referenced by create_addr().
{
   int x, newindex = 0;
   /* First step is to get the codecs "index number" */
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == format) {
         newindex = x + 1;
         break;
      }
   }
   /* Done if its unknown */
   if (!newindex)
      return;
   /* Now find any existing occurrence, or the end */
   for (x = 0; x < 32; x++) {
      if (!pref->order[x] || pref->order[x] == newindex)
         break;
   }
   if (only_if_existing && !pref->order[x])
      return;
   /* Move down to make space to insert - either all the way to the end,
      or as far as the existing location (which will be overwritten) */
   for (; x > 0; x--) {
      pref->order[x] = pref->order[x - 1];
      pref->framing[x] = pref->framing[x - 1];
   }
   /* And insert the new entry */
   pref->order[0] = newindex;
   pref->framing[0] = 0; /* ? */
}
void ast_codec_pref_remove (struct ast_codec_pref * pref, int format)
Remove codec from pref list.
Remove audio a codec from a preference list.
Definition at line 1044 of file frame.c.
References ARRAY_LEN, ast_codec_pref::framing, and ast_codec_pref::order.
Referenced by ast_codec_pref_append(), and ast_parse_allow_disallow().
{
   struct ast_codec_pref oldorder;
   int x, y = 0;
   int slot;
   int size;
   if (!pref->order[0])
      return;
   memcpy(&oldorder, pref, sizeof(oldorder));
   memset(pref, 0, sizeof(*pref));
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      slot = oldorder.order[x];
      size = oldorder.framing[x];
      if (! slot)
         break;
      if (AST_FORMAT_LIST[slot-1].bits != format) {
         pref->order[y] = slot;
         pref->framing[y++] = size;
      }
   }
}
int ast_codec_pref_setsize (struct ast_codec_pref * pref, int format, int framems)
Set packet size for codec.
Definition at line 1134 of file frame.c.
References ARRAY_LEN, ast_format_list::def_ms, ast_codec_pref::framing, ast_format_list::inc_ms, ast_format_list::max_ms, ast_format_list::min_ms, and ast_codec_pref::order.
Referenced by ast_parse_allow_disallow(), and process_sdp_a_audio().
{
   int x, idx = -1;
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == format) {
         idx = x;
         break;
      }
   }
   if (idx < 0)
      return -1;
   /* size validation */
   if (!framems)
      framems = AST_FORMAT_LIST[idx].def_ms;
   if (AST_FORMAT_LIST[idx].inc_ms && framems % AST_FORMAT_LIST[idx].inc_ms) /* avoid division by zero */
      framems -= framems % AST_FORMAT_LIST[idx].inc_ms;
   if (framems < AST_FORMAT_LIST[idx].min_ms)
      framems = AST_FORMAT_LIST[idx].min_ms;
   if (framems > AST_FORMAT_LIST[idx].max_ms)
      framems = AST_FORMAT_LIST[idx].max_ms;
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (pref->order[x] == (idx + 1)) {
         pref->framing[x] = framems;
         break;
      }
   }
   return x;
}
int ast_codec_pref_string (struct ast_codec_pref * pref, char * buf, size_t size)
Dump audio codec preference list into a string.
Definition at line 997 of file frame.c.
References ast_codec_pref_index(), and ast_getformatname().
Referenced by dump_prefs(), and socket_process().
{
   int x, codec;
   size_t total_len, slen;
   char *formatname;
   memset(buf,0,size);
   total_len = size;
   buf[0] = '(';
   total_len--;
   for(x = 0; x < 32 ; x++) {
      if (total_len <= 0)
         break;
      if (!(codec = ast_codec_pref_index(pref,x)))
         break;
      if ((formatname = ast_getformatname(codec))) {
         slen = strlen(formatname);
         if (slen > total_len)
            break;
         strncat(buf, formatname, total_len - 1); /* safe */
         total_len -= slen;
      }
      if (total_len && x < 31 && ast_codec_pref_index(pref , x + 1)) {
         strncat(buf, "|", total_len - 1); /* safe */
         total_len--;
      }
   }
   if (total_len) {
      strncat(buf, ")", total_len - 1); /* safe */
      total_len--;
   }
   return size - total_len;
}
static const char* ast_expand_codec_alias (const char * in) [static]
Definition at line 625 of file frame.c.
References ARRAY_LEN.
Referenced by ast_getformatbyname().
{
   int x;
   for (x = 0; x < ARRAY_LEN(ast_codec_alias_table); x++) {
      if (!strcmp(in,ast_codec_alias_table[x].alias))
         return ast_codec_alias_table[x].realname;
   }
   return in;
}
int ast_frame_adjust_volume (struct ast_frame * f, int adjustment)
Adjusts the volume of the audio samples contained in a frame.
Parameters:
f The frame containing the samples (must be AST_FRAME_VOICE and AST_FORMAT_SLINEAR)
adjustment The number of dB to adjust up or down.
Returns:
0 for success, non-zero for an error
Definition at line 1531 of file frame.c.
References AST_FORMAT_SLINEAR, AST_FRAME_VOICE, ast_slinear_saturated_divide(), ast_slinear_saturated_multiply(), ast_frame::data, ast_frame::frametype, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
Referenced by audiohook_read_frame_single(), audiohook_volume_callback(), conf_run(), and volume_callback().
{
   int count;
   short *fdata = f->data.ptr;
   short adjust_value = abs(adjustment);
   if ((f->frametype != AST_FRAME_VOICE) || (f->subclass != AST_FORMAT_SLINEAR))
      return -1;
   if (!adjustment)
      return 0;
   for (count = 0; count < f->samples; count++) {
      if (adjustment > 0) {
         ast_slinear_saturated_multiply(&fdata[count], &adjust_value);
      } else if (adjustment < 0) {
         ast_slinear_saturated_divide(&fdata[count], &adjust_value);
      }
   }
   return 0;
}
void ast_frame_dump (const char * name, struct ast_frame * f, char * prefix)
Dump a frame for debugging purposes
Definition at line 756 of file frame.c.
References AST_CONTROL_ANSWER, AST_CONTROL_BUSY, AST_CONTROL_CONGESTION, AST_CONTROL_FLASH, AST_CONTROL_HANGUP, AST_CONTROL_HOLD, AST_CONTROL_OFFHOOK, AST_CONTROL_OPTION, AST_CONTROL_RADIO_KEY, AST_CONTROL_RADIO_UNKEY, AST_CONTROL_RING, AST_CONTROL_RINGING, AST_CONTROL_T38_PARAMETERS, AST_CONTROL_TAKEOFFHOOK, AST_CONTROL_UNHOLD, AST_CONTROL_WINK, ast_copy_string(), AST_FRAME_CONTROL, AST_FRAME_DTMF_BEGIN, AST_FRAME_DTMF_END, AST_FRAME_HTML, AST_FRAME_IAX, AST_FRAME_IMAGE, AST_FRAME_MODEM, AST_FRAME_NULL, AST_FRAME_TEXT, AST_FRAME_VIDEO, AST_FRAME_VOICE, ast_getformatname(), AST_HTML_BEGIN, AST_HTML_DATA, AST_HTML_END, AST_HTML_LDCOMPLETE, AST_HTML_LINKREJECT, AST_HTML_LINKURL, AST_HTML_NOSUPPORT, AST_HTML_UNLINK, AST_HTML_URL, AST_MODEM_T38, AST_MODEM_V150, ast_strlen_zero(), AST_T38_NEGOTIATED, AST_T38_REFUSED, AST_T38_REQUEST_NEGOTIATE, AST_T38_REQUEST_TERMINATE, AST_T38_TERMINATED, ast_verbose, COLOR_BLACK, COLOR_BRCYAN, COLOR_BRGREEN, COLOR_BRMAGENTA, COLOR_BRRED, COLOR_YELLOW, ast_frame::data, ast_frame::datalen, ast_frame::frametype, ast_frame::ptr, ast_control_t38_parameters::request_response, ast_frame::subclass, and term_color().
Referenced by __ast_read(), and ast_write().
{
   const char noname[] = "unknown";
   char ftype[40] = "Unknown Frametype";
   char cft[80];
   char subclass[40] = "Unknown Subclass";
   char csub[80];
   char moreinfo[40] = "";
   char cn[60];
   char cp[40];
   char cmn[40];
   const char *message = "Unknown";
   if (!name)
      name = noname;
   if (!f) {
      ast_verbose("%s [ %s (NULL) ] [%s]\n",
         term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
         term_color(cft, "HANGUP", COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
         term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
      return;
   }
   /* XXX We should probably print one each of voice and video when the format changes XXX */
   if (f->frametype == AST_FRAME_VOICE)
      return;
   if (f->frametype == AST_FRAME_VIDEO)
      return;
   switch(f->frametype) {
   case AST_FRAME_DTMF_BEGIN:
      strcpy(ftype, "DTMF Begin");
      subclass[0] = f->subclass;
      subclass[1] = '\0';
      break;
   case AST_FRAME_DTMF_END:
      strcpy(ftype, "DTMF End");
      subclass[0] = f->subclass;
      subclass[1] = '\0';
      break;
   case AST_FRAME_CONTROL:
      strcpy(ftype, "Control");
      switch(f->subclass) {
      case AST_CONTROL_HANGUP:
         strcpy(subclass, "Hangup");
         break;
      case AST_CONTROL_RING:
         strcpy(subclass, "Ring");
         break;
      case AST_CONTROL_RINGING:
         strcpy(subclass, "Ringing");
         break;
      case AST_CONTROL_ANSWER:
         strcpy(subclass, "Answer");
         break;
      case AST_CONTROL_BUSY:
         strcpy(subclass, "Busy");
         break;
      case AST_CONTROL_TAKEOFFHOOK:
         strcpy(subclass, "Take Off Hook");
         break;
      case AST_CONTROL_OFFHOOK:
         strcpy(subclass, "Line Off Hook");
         break;
      case AST_CONTROL_CONGESTION:
         strcpy(subclass, "Congestion");
         break;
      case AST_CONTROL_FLASH:
         strcpy(subclass, "Flash");
         break;
      case AST_CONTROL_WINK:
         strcpy(subclass, "Wink");
         break;
      case AST_CONTROL_OPTION:
         strcpy(subclass, "Option");
         break;
      case AST_CONTROL_RADIO_KEY:
         strcpy(subclass, "Key Radio");
         break;
      case AST_CONTROL_RADIO_UNKEY:
         strcpy(subclass, "Unkey Radio");
         break;
      case AST_CONTROL_HOLD:
         strcpy(subclass, "Hold");
         break;
      case AST_CONTROL_UNHOLD:
         strcpy(subclass, "Unhold");
         break;
      case AST_CONTROL_T38_PARAMETERS:
         if (f->datalen != sizeof(struct ast_control_t38_parameters)) {
            message = "Invalid";
         } else {
            struct ast_control_t38_parameters *parameters = f->data.ptr;
            enum ast_control_t38 state = parameters->request_response;
            if (state == AST_T38_REQUEST_NEGOTIATE)
               message = "Negotiation Requested";
            else if (state == AST_T38_REQUEST_TERMINATE)
               message = "Negotiation Request Terminated";
            else if (state == AST_T38_NEGOTIATED)
               message = "Negotiated";
            else if (state == AST_T38_TERMINATED)
               message = "Terminated";
            else if (state == AST_T38_REFUSED)
               message = "Refused";
         }
         snprintf(subclass, sizeof(subclass), "T38_Parameters/%s", message);
         break;
      case -1:
         strcpy(subclass, "Stop generators");
         break;
      default:
         snprintf(subclass, sizeof(subclass), "Unknown control '%d'", f->subclass);
      }
      break;
   case AST_FRAME_NULL:
      strcpy(ftype, "Null Frame");
      strcpy(subclass, "N/A");
      break;
   case AST_FRAME_IAX:
      /* Should never happen */
      strcpy(ftype, "IAX Specific");
      snprintf(subclass, sizeof(subclass), "IAX Frametype %d", f->subclass);
      break;
   case AST_FRAME_TEXT:
      strcpy(ftype, "Text");
      strcpy(subclass, "N/A");
      ast_copy_string(moreinfo, f->data.ptr, sizeof(moreinfo));
      break;
   case AST_FRAME_IMAGE:
      strcpy(ftype, "Image");
      snprintf(subclass, sizeof(subclass), "Image format %s\n", ast_getformatname(f->subclass));
      break;
   case AST_FRAME_HTML:
      strcpy(ftype, "HTML");
      switch(f->subclass) {
      case AST_HTML_URL:
         strcpy(subclass, "URL");
         ast_copy_string(moreinfo, f->data.ptr, sizeof(moreinfo));
         break;
      case AST_HTML_DATA:
         strcpy(subclass, "Data");
         break;
      case AST_HTML_BEGIN:
         strcpy(subclass, "Begin");
         break;
      case AST_HTML_END:
         strcpy(subclass, "End");
         break;
      case AST_HTML_LDCOMPLETE:
         strcpy(subclass, "Load Complete");
         break;
      case AST_HTML_NOSUPPORT:
         strcpy(subclass, "No Support");
         break;
      case AST_HTML_LINKURL:
         strcpy(subclass, "Link URL");
         ast_copy_string(moreinfo, f->data.ptr, sizeof(moreinfo));
         break;
      case AST_HTML_UNLINK:
         strcpy(subclass, "Unlink");
         break;
      case AST_HTML_LINKREJECT:
         strcpy(subclass, "Link Reject");
         break;
      default:
         snprintf(subclass, sizeof(subclass), "Unknown HTML frame '%d'\n", f->subclass);
         break;
      }
      break;
   case AST_FRAME_MODEM:
      strcpy(ftype, "Modem");
      switch (f->subclass) {
      case AST_MODEM_T38:
         strcpy(subclass, "T.38");
         break;
      case AST_MODEM_V150:
         strcpy(subclass, "V.150");
         break;
      default:
         snprintf(subclass, sizeof(subclass), "Unknown MODEM frame '%d'\n", f->subclass);
         break;
      }
      break;
   default:
      snprintf(ftype, sizeof(ftype), "Unknown Frametype '%d'", f->frametype);
   }
   if (!ast_strlen_zero(moreinfo))
      ast_verbose("%s [ TYPE: %s (%d) SUBCLASS: %s (%d) '%s' ] [%s]\n",
             term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
             term_color(cft, ftype, COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
             f->frametype,
             term_color(csub, subclass, COLOR_BRCYAN, COLOR_BLACK, sizeof(csub)),
             f->subclass,
             term_color(cmn, moreinfo, COLOR_BRGREEN, COLOR_BLACK, sizeof(cmn)),
             term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
   else
      ast_verbose("%s [ TYPE: %s (%d) SUBCLASS: %s (%d) ] [%s]\n",
             term_color(cp, prefix, COLOR_BRMAGENTA, COLOR_BLACK, sizeof(cp)),
             term_color(cft, ftype, COLOR_BRRED, COLOR_BLACK, sizeof(cft)),
             f->frametype,
             term_color(csub, subclass, COLOR_BRCYAN, COLOR_BLACK, sizeof(csub)),
             f->subclass,
             term_color(cn, name, COLOR_YELLOW, COLOR_BLACK, sizeof(cn)));
}
void ast_frame_free (struct ast_frame * fr, int cache)
Requests a frame to be allocated.
Parameters:
source Request a frame be allocated. source is an optional source of the frame, len is the requested length, or "0" if the caller will supply the buffer
Frees a frame or list of frames
Parameters:
fr Frame to free, or head of list to free
cache Whether to consider this frame for frame caching
Definition at line 373 of file frame.c.
References __frame_free(), and AST_LIST_NEXT.
Referenced by mixmonitor_thread().
{
   struct ast_frame *next;
   for (next = AST_LIST_NEXT(frame, frame_list);
        frame;
        frame = next, next = frame ? AST_LIST_NEXT(frame, frame_list) : NULL) {
      __frame_free(frame, cache);
   }
}
static struct ast_frame* ast_frame_header_new (void) [static, read]
Definition at line 291 of file frame.c.
References ast_calloc, ast_calloc_cache, AST_LIST_REMOVE_HEAD, AST_MALLOCD_HDR, ast_threadstorage_get(), f, frame_cache, frames, ast_frame_cache::list, ast_frame::mallocd, ast_frame::mallocd_hdr_len, and ast_frame_cache::size.
Referenced by ast_frisolate().
{
   struct ast_frame *f;
#if !defined(LOW_MEMORY)
   struct ast_frame_cache *frames;
   if ((frames = ast_threadstorage_get(&frame_cache, sizeof(*frames)))) {
      if ((f = AST_LIST_REMOVE_HEAD(&frames->list, frame_list))) {
         size_t mallocd_len = f->mallocd_hdr_len;
         memset(f, 0, sizeof(*f));
         f->mallocd_hdr_len = mallocd_len;
         f->mallocd = AST_MALLOCD_HDR;
         frames->size--;
         return f;
      }
   }
   if (!(f = ast_calloc_cache(1, sizeof(*f))))
      return NULL;
#else
   if (!(f = ast_calloc(1, sizeof(*f))))
      return NULL;
#endif
   f->mallocd_hdr_len = sizeof(*f);
   return f;
}
int ast_frame_slinear_sum (struct ast_frame * f1, struct ast_frame * f2)
Sums two frames of audio samples.
Parameters:
f1 The first frame (which will contain the result)
f2 The second frame
Returns:
0 for success, non-zero for an error
The frames must be AST_FRAME_VOICE and must contain AST_FORMAT_SLINEAR samples, and must contain the same number of samples.
Definition at line 1554 of file frame.c.
References AST_FORMAT_SLINEAR, AST_FRAME_VOICE, ast_slinear_saturated_add(), ast_frame::data, ast_frame::frametype, ast_frame::ptr, ast_frame::samples, and ast_frame::subclass.
{
   int count;
   short *data1, *data2;
   if ((f1->frametype != AST_FRAME_VOICE) || (f1->subclass != AST_FORMAT_SLINEAR))
      return -1;
   if ((f2->frametype != AST_FRAME_VOICE) || (f2->subclass != AST_FORMAT_SLINEAR))
      return -1;
   if (f1->samples != f2->samples)
      return -1;
   for (count = 0, data1 = f1->data.ptr, data2 = f2->data.ptr;
        count < f1->samples;
        count++, data1++, data2++)
      ast_slinear_saturated_add(data1, data2);
   return 0;
}
struct ast_frame* ast_frdup (const struct ast_frame * fr) [read]
Copies a frame.
Parameters:
fr frame to copy Duplicates a frame -- should only rarely be used, typically frisolate is good enough
Returns:
Returns a frame on success, NULL on error
Definition at line 474 of file frame.c.
References ast_calloc_cache, ast_copy_flags, AST_FRFLAG_HAS_TIMING_INFO, AST_FRIENDLY_OFFSET, AST_LIST_REMOVE_CURRENT, AST_LIST_TRAVERSE_SAFE_BEGIN, AST_LIST_TRAVERSE_SAFE_END, AST_MALLOCD_HDR, ast_threadstorage_get(), buf, ast_frame::data, ast_frame::datalen, ast_frame::delivery, frame_cache, frames, ast_frame::frametype, ast_frame::len, len(), ast_frame_cache::list, ast_frame::mallocd, ast_frame::mallocd_hdr_len, ast_frame::offset, ast_frame::ptr, ast_frame::samples, ast_frame::seqno, ast_frame_cache::size, ast_frame::src, ast_frame::subclass, ast_frame::ts, and ast_frame::uint32.
Referenced by __ast_queue_frame(), ast_frisolate(), ast_jb_put(), ast_rtp_write(), ast_slinfactory_feed(), audiohook_read_frame_both(), audiohook_read_frame_single(), autoservice_run(), recordthread(), rpt(), and rpt_exec().
{
   struct ast_frame *out = NULL;
   int len, srclen = 0;
   void *buf = NULL;
#if !defined(LOW_MEMORY)
   struct ast_frame_cache *frames;
#endif
   /* Start with standard stuff */
   len = sizeof(*out) + AST_FRIENDLY_OFFSET + f->datalen;
   /* If we have a source, add space for it */
   /*
    * XXX Watch out here - if we receive a src which is not terminated
    * properly, we can be easily attacked. Should limit the size we deal with.
    */
   if (f->src)
      srclen = strlen(f->src);
   if (srclen > 0)
      len += srclen + 1;
#if !defined(LOW_MEMORY)
   if ((frames = ast_threadstorage_get(&frame_cache, sizeof(*frames)))) {
      AST_LIST_TRAVERSE_SAFE_BEGIN(&frames->list, out, frame_list) {
         if (out->mallocd_hdr_len >= len) {
            size_t mallocd_len = out->mallocd_hdr_len;
            AST_LIST_REMOVE_CURRENT(frame_list);
            memset(out, 0, sizeof(*out));
            out->mallocd_hdr_len = mallocd_len;
            buf = out;
            frames->size--;
            break;
         }
      }
      AST_LIST_TRAVERSE_SAFE_END;
   }
#endif
   if (!buf) {
      if (!(buf = ast_calloc_cache(1, len)))
         return NULL;
      out = buf;
      out->mallocd_hdr_len = len;
   }
   out->frametype = f->frametype;
   out->subclass = f->subclass;
   out->datalen = f->datalen;
   out->samples = f->samples;
   out->delivery = f->delivery;
   /* Set us as having malloc'd header only, so it will eventually
      get freed. */
   out->mallocd = AST_MALLOCD_HDR;
   out->offset = AST_FRIENDLY_OFFSET;
   if (out->datalen) {
      out->data.ptr = buf + sizeof(*out) + AST_FRIENDLY_OFFSET;
      memcpy(out->data.ptr, f->data.ptr, out->datalen);
   } else {
      out->data.uint32 = f->data.uint32;
   }
   if (srclen > 0) {
      /* This may seem a little strange, but it's to avoid a gcc (4.2.4) compiler warning */
      char *src;
      out->src = buf + sizeof(*out) + AST_FRIENDLY_OFFSET + f->datalen;
      src = (char *) out->src;
      /* Must have space since we allocated for it */
      strcpy(src, f->src);
   }
   ast_copy_flags(out, f, AST_FRFLAG_HAS_TIMING_INFO);
   out->ts = f->ts;
   out->len = f->len;
   out->seqno = f->seqno;
   return out;
}
struct ast_frame* ast_frisolate (struct ast_frame * fr) [read]
'isolates' a frame by duplicating non-malloc'ed components (header, src, data). On return all components are malloc'ed
Makes a frame independent of any static storage.
Definition at line 389 of file frame.c.
References ast_clear_flag, ast_copy_flags, ast_frame_header_new(), ast_frdup(), ast_free, AST_FRFLAG_FROM_DSP, AST_FRFLAG_FROM_TRANSLATOR, AST_FRFLAG_HAS_TIMING_INFO, AST_FRIENDLY_OFFSET, ast_malloc, AST_MALLOCD_DATA, AST_MALLOCD_HDR, AST_MALLOCD_SRC, ast_strdup, ast_test_flag, ast_frame::data, ast_frame::datalen, ast_frame::frametype, ast_frame::len, ast_frame::mallocd, ast_frame::offset, ast_frame::ptr, ast_frame::samples, ast_frame::seqno, ast_frame::src, ast_frame::subclass, ast_frame::ts, and ast_frame::uint32.
Referenced by __ast_answer(), ast_slinfactory_feed(), ast_write(), autoservice_run(), jpeg_read_image(), and read_frame().
{
   struct ast_frame *out;
   void *newdata;
   /* if none of the existing frame is malloc'd, let ast_frdup() do it
      since it is more efficient
   */
   if (fr->mallocd == 0) {
      return ast_frdup(fr);
   }
   /* if everything is already malloc'd, we are done */
   if ((fr->mallocd & (AST_MALLOCD_HDR | AST_MALLOCD_SRC | AST_MALLOCD_DATA)) ==
       (AST_MALLOCD_HDR | AST_MALLOCD_SRC | AST_MALLOCD_DATA)) {
      return fr;
   }
   if (!(fr->mallocd & AST_MALLOCD_HDR)) {
      /* Allocate a new header if needed */
      if (!(out = ast_frame_header_new())) {
         return NULL;
      }
      out->frametype = fr->frametype;
      out->subclass = fr->subclass;
      out->datalen = fr->datalen;
      out->samples = fr->samples;
      out->offset = fr->offset;
      /* Copy the timing data */
      ast_copy_flags(out, fr, AST_FRFLAG_HAS_TIMING_INFO);
      if (ast_test_flag(fr, AST_FRFLAG_HAS_TIMING_INFO)) {
         out->ts = fr->ts;
         out->len = fr->len;
         out->seqno = fr->seqno;
      }
   } else {
      ast_clear_flag(fr, AST_FRFLAG_FROM_TRANSLATOR);
      ast_clear_flag(fr, AST_FRFLAG_FROM_DSP);
      out = fr;
   }
   if (!(fr->mallocd & AST_MALLOCD_SRC) && fr->src) {
      if (!(out->src = ast_strdup(fr->src))) {
         if (out != fr) {
            ast_free(out);
         }
         return NULL;
      }
   } else {
      out->src = fr->src;
      fr->src = NULL;
      fr->mallocd &= ~AST_MALLOCD_SRC;
   }
   if (!(fr->mallocd & AST_MALLOCD_DATA))  {
      if (!fr->datalen) {
         out->data.uint32 = fr->data.uint32;
         out->mallocd = AST_MALLOCD_HDR | AST_MALLOCD_SRC;
         return out;
      }
      if (!(newdata = ast_malloc(fr->datalen + AST_FRIENDLY_OFFSET))) {
         if (out->src != fr->src) {
            ast_free((void *) out->src);
         }
         if (out != fr) {
            ast_free(out);
         }
         return NULL;
      }
      newdata += AST_FRIENDLY_OFFSET;
      out->offset = AST_FRIENDLY_OFFSET;
      out->datalen = fr->datalen;
      memcpy(newdata, fr->data.ptr, fr->datalen);
      out->data.ptr = newdata;
   } else {
      out->data = fr->data;
      memset(&fr->data, 0, sizeof(fr->data));
      fr->mallocd &= ~AST_MALLOCD_DATA;
   }
   out->mallocd = AST_MALLOCD_HDR | AST_MALLOCD_SRC | AST_MALLOCD_DATA;
   return out;
}
struct ast_format_list* ast_get_format_list (size_t * size) [read]
Definition at line 567 of file frame.c.
References ARRAY_LEN.
{
   *size = ARRAY_LEN(AST_FORMAT_LIST);
   return AST_FORMAT_LIST;
}
struct ast_format_list* ast_get_format_list_index (int idx) [read]
Definition at line 562 of file frame.c.
{
   return &AST_FORMAT_LIST[idx];
}
int ast_getformatbyname (const char * name)
Gets a format from a name.
Parameters:
name string of format
Returns:
This returns the form of the format in binary on success, 0 on error.
Definition at line 636 of file frame.c.
References ARRAY_LEN, ast_expand_codec_alias(), ast_format_list::bits, and format.
Referenced by ast_parse_allow_disallow(), iax_template_parse(), load_moh_classes(), local_ast_moh_start(), reload_config(), and try_suggested_sip_codec().
{
   int x, all, format = 0;
   all = strcasecmp(name, "all") ? 0 : 1;
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (all ||
           !strcasecmp(AST_FORMAT_LIST[x].name,name) ||
           !strcasecmp(AST_FORMAT_LIST[x].name, ast_expand_codec_alias(name))) {
         format |= AST_FORMAT_LIST[x].bits;
         if (!all)
            break;
      }
   }
   return format;
}
char* ast_getformatname (int format)
Get the name of a format.
Parameters:
format id of format
Returns:
A static string containing the name of the format or "unknown" if unknown.
Definition at line 573 of file frame.c.
References ARRAY_LEN, ast_format_list::bits, and ast_format_list::name.
Referenced by __ast_play_and_record(), __ast_read(), __ast_register_translator(), _sip_show_peer(), _skinny_show_line(), add_codec_to_answer(), add_codec_to_sdp(), add_tcodec_to_sdp(), add_vcodec_to_sdp(), agent_call(), ast_codec_get_len(), ast_codec_get_samples(), ast_codec_pref_string(), ast_dsp_process(), ast_frame_dump(), ast_openvstream(), ast_rtp_write(), ast_slinfactory_feed(), ast_streamfile(), ast_translator_build_path(), ast_unregister_translator(), ast_writestream(), background_detect_exec(), bridge_channel_join(), bridge_make_compatible(), dahdi_read(), do_waiting(), eagi_exec(), func_channel_read(), function_iaxpeer(), function_sippeer(), gtalk_show_channels(), handle_cli_core_show_file_formats(), handle_cli_core_show_translation(), handle_cli_iax2_show_channels(), handle_cli_iax2_show_peer(), handle_cli_moh_show_classes(), handle_core_show_image_formats(), iax2_request(), iax_show_provisioning(), jingle_show_channels(), login_exec(), moh_release(), oh323_rtp_read(), phone_setup(), print_codec_to_cli(), rebuild_matrix(), register_translator(), set_format(), set_local_capabilities(), set_peer_capabilities(), show_codecs(), sip_request_call(), sip_rtp_read(), socket_process(), start_rtp(), unistim_request(), unistim_rtp_read(), and unistim_write().
{
   int x;
   char *ret = "unknown";
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits == format) {
         ret = AST_FORMAT_LIST[x].name;
         break;
      }
   }
   return ret;
}
char* ast_getformatname_multiple (char * buf, size_t size, int format)
Get the names of a set of formats.
Parameters:
buf a buffer for the output string
size size of buf (bytes)
format the format (combined IDs of codecs) Prints a list of readable codec names corresponding to "format". ex: for format=AST_FORMAT_GSM|AST_FORMAT_SPEEX|AST_FORMAT_ILBC it will return "0x602 (GSM|SPEEX|ILBC)"
Returns:
The return value is buf.
Definition at line 586 of file frame.c.
References ARRAY_LEN, ast_copy_string(), ast_format_list::bits, len(), and name.
Referenced by __ast_read(), _sip_show_peer(), _skinny_show_device(), _skinny_show_line(), add_sdp(), ast_streamfile(), bridge_make_compatible(), function_iaxpeer(), function_sippeer(), gtalk_is_answered(), gtalk_newcall(), handle_cli_iax2_show_peer(), handle_showchan(), iax2_bridge(), process_sdp(), serialize_showchan(), set_format(), show_channels_cb(), sip_new(), sip_request_call(), sip_show_channel(), sip_show_settings(), and sip_write().
{
   int x;
   unsigned len;
   char *start, *end = buf;
   if (!size)
      return buf;
   snprintf(end, size, "0x%x (", format);
   len = strlen(end);
   end += len;
   size -= len;
   start = end;
   for (x = 0; x < ARRAY_LEN(AST_FORMAT_LIST); x++) {
      if (AST_FORMAT_LIST[x].bits & format) {
         snprintf(end, size,"%s|",AST_FORMAT_LIST[x].name);
         len = strlen(end);
         end += len;
         size -= len;
      }
   }
   if (start == end)
      ast_copy_string(start, "nothing)", size);
   else if (size > 1)
      *(end -1) = ')';
   return buf;
}
int ast_parse_allow_disallow (struct ast_codec_pref * pref, int * mask, const char * list, int allowing)
Parse an "allow" or "deny" line in a channel or device configuration and update the capabilities mask and pref if provided. Video codecs are not added to codec preference lists, since we can not transcode.
Returns:
Returns number of errors encountered during parsing
Definition at line 1233 of file frame.c.
References ast_codec_pref_append(), ast_codec_pref_remove(), ast_codec_pref_setsize(), ast_debug, AST_FORMAT_AUDIO_MASK, ast_getformatbyname(), ast_log(), ast_strdupa, format, LOG_WARNING, parse(), and strsep().
Referenced by action_originate(), apply_outgoing(), build_peer(), build_user(), config_parse_variables(), gtalk_create_member(), gtalk_load_config(), jingle_create_member(), jingle_load_config(), reload_config(), set_config(), skinny_unregister(), and update_common_options().
{
   int errors = 0;
   char *parse = NULL, *this = NULL, *psize = NULL;
   int format = 0, framems = 0;
   parse = ast_strdupa(list);
   while ((this = strsep(&parse, ","))) {
      framems = 0;
      if ((psize = strrchr(this, ':'))) {
         *psize++ = '\0';
         ast_debug(1, "Packetization for codec: %s is %s\n", this, psize);
         framems = atoi(psize);
         if (framems < 0) {
            framems = 0;
            errors++;
            ast_log(LOG_WARNING, "Bad packetization value for codec %s\n", this);
         }
      }
      if (!(format = ast_getformatbyname(this))) {
         ast_log(LOG_WARNING, "Cannot %s unknown format '%s'\n", allowing ? "allow" : "disallow", this);
         errors++;
         continue;
      }
      if (mask) {
         if (allowing)
            *mask |= format;
         else
            *mask &= ~format;
      }
      /* Set up a preference list for audio. Do not include video in preferences
         since we can not transcode video and have to use whatever is offered
       */
      if (pref && (format & AST_FORMAT_AUDIO_MASK)) {
         if (strcasecmp(this, "all")) {
            if (allowing) {
               ast_codec_pref_append(pref, format);
               ast_codec_pref_setsize(pref, format, framems);
            }
            else
               ast_codec_pref_remove(pref, format);
         } else if (!allowing) {
            memset(pref, 0, sizeof(*pref));
         }
      }
   }
   return errors;
}
void ast_smoother_free (struct ast_smoother * s)
Definition at line 286 of file frame.c.
References ast_free.
Referenced by ast_rtp_destroy(), and ast_rtp_write().
{
   ast_free(s);
}
int ast_smoother_get_flags (struct ast_smoother * s)
Definition at line 186 of file frame.c.
References ast_smoother::flags.
{
   return s->flags;
}
struct ast_smoother* ast_smoother_new (int size) [read]
Definition at line 176 of file frame.c.
References ast_malloc, ast_smoother_reset(), and s.
Referenced by ast_rtp_codec_setpref(), and ast_rtp_write().
{
   struct ast_smoother *s;
   if (size < 1)
      return NULL;
   if ((s = ast_malloc(sizeof(*s))))
      ast_smoother_reset(s, size);
   return s;
}
struct ast_frame* ast_smoother_read (struct ast_smoother * s) [read]
Definition at line 236 of file frame.c.
References ast_format_rate(), AST_FRAME_VOICE, AST_FRIENDLY_OFFSET, ast_log(), ast_samp2tv(), AST_SMOOTHER_FLAG_G729, ast_tvadd(), ast_tvzero(), ast_smoother::data, ast_frame::data, ast_frame::datalen, ast_smoother::delivery, ast_frame::delivery, ast_smoother::f, ast_smoother::flags, ast_smoother::format, ast_smoother::framedata, ast_frame::frametype, ast_smoother::len, len(), LOG_WARNING, ast_frame::offset, ast_smoother::opt, ast_frame::ptr, ast_frame::samples, ast_smoother::samplesperbyte, ast_smoother::size, and ast_frame::subclass.
Referenced by ast_rtp_write().
{
   struct ast_frame *opt;
   int len;
   /* IF we have an optimization frame, send it */
   if (s->opt) {
      if (s->opt->offset < AST_FRIENDLY_OFFSET)
         ast_log(LOG_WARNING, "Returning a frame of inappropriate offset (%d).\n",
                     s->opt->offset);
      opt = s->opt;
      s->opt = NULL;
      return opt;
   }
   /* Make sure we have enough data */
   if (s->len < s->size) {
      /* Or, if this is a G.729 frame with VAD on it, send it immediately anyway */
      if (!((s->flags & AST_SMOOTHER_FLAG_G729) && (s->len % 10)))
         return NULL;
   }
   len = s->size;
   if (len > s->len)
      len = s->len;
   /* Make frame */
   s->f.frametype = AST_FRAME_VOICE;
   s->f.subclass = s->format;
   s->f.data.ptr = s->framedata + AST_FRIENDLY_OFFSET;
   s->f.offset = AST_FRIENDLY_OFFSET;
   s->f.datalen = len;
   /* Samples will be improper given VAD, but with VAD the concept really doesn't even exist */
   s->f.samples = len * s->samplesperbyte;   /* XXX rounding */
   s->f.delivery = s->delivery;
   /* Fill Data */
   memcpy(s->f.data.ptr, s->data, len);
   s->len -= len;
   /* Move remaining data to the front if applicable */
   if (s->len) {
      /* In principle this should all be fine because if we are sending
         G.729 VAD, the next timestamp will take over anyawy */
      memmove(s->data, s->data + len, s->len);
      if (!ast_tvzero(s->delivery)) {
         /* If we have delivery time, increment it, otherwise, leave it at 0 */
         s->delivery = ast_tvadd(s->delivery, ast_samp2tv(s->f.samples, ast_format_rate(s->format)));
      }
   }
   /* Return frame */
   return &s->f;
}
void ast_smoother_reconfigure (struct ast_smoother * s, int bytes)
Reconfigure an existing smoother to output a different number of bytes per frame.
Parameters:
s the smoother to reconfigure
bytes the desired number of bytes per output frame
Returns:
nothing
Definition at line 154 of file frame.c.
References ast_smoother::opt, ast_smoother::opt_needs_swap, ast_smoother::size, and smoother_frame_feed().
Referenced by ast_rtp_codec_setpref().
{
   /* if there is no change, then nothing to do */
   if (s->size == bytes) {
      return;
   }
   /* set the new desired output size */
   s->size = bytes;
   /* if there is no 'optimized' frame in the smoother,
    *   then there is nothing left to do
    */
   if (!s->opt) {
      return;
   }
   /* there is an 'optimized' frame here at the old size,
    * but it must now be put into the buffer so the data
    * can be extracted at the new size
    */
   smoother_frame_feed(s, s->opt, s->opt_needs_swap);
   s->opt = NULL;
}
void ast_smoother_reset (struct ast_smoother * s, int bytes)
Definition at line 148 of file frame.c.
References ast_smoother::size.
Referenced by ast_smoother_new().
{
   memset(s, 0, sizeof(*s));
   s->size = bytes;
}
void ast_smoother_set_flags (struct ast_smoother * s, int flags)
Definition at line 191 of file frame.c.
References ast_smoother::flags.
Referenced by ast_rtp_codec_setpref(), and ast_rtp_write().
{
   s->flags = flags;
}
int ast_smoother_test_flag (struct ast_smoother * s, int flag)
Definition at line 196 of file frame.c.
References ast_smoother::flags.
Referenced by ast_rtp_write().
{
   return (s->flags & flag);
}
void ast_swapcopy_samples (void * dst, const void * src, int samples)
Definition at line 551 of file frame.c.
Referenced by __ast_smoother_feed(), iax_frame_wrap(), phone_write_buf(), and smoother_frame_feed().
{
   int i;
   unsigned short *dst_s = dst;
   const unsigned short *src_s = src;
   for (i = 0; i < samples; i++)
      dst_s[i] = (src_s[i]<<8) | (src_s[i]>>8);
}
static void frame_cache_cleanup (void * data) [static]
Definition at line 321 of file frame.c.
References ast_free, AST_LIST_REMOVE_HEAD, f, frames, and ast_frame_cache::list.
{
   struct ast_frame_cache *frames = data;
   struct ast_frame *f;
   while ((f = AST_LIST_REMOVE_HEAD(&frames->list, frame_list)))
      ast_free(f);
   ast_free(frames);
}
static int g723_len (unsigned char buf) [static]
Definition at line 1284 of file frame.c.
References ast_log(), LOG_WARNING, type, TYPE_DONTSEND, TYPE_HIGH, TYPE_LOW, TYPE_MASK, and TYPE_SILENCE.
Referenced by g723_samples().
{
   enum frame_type type = buf & TYPE_MASK;
   switch(type) {
   case TYPE_DONTSEND:
      return 0;
      break;
   case TYPE_SILENCE:
      return 4;
      break;
   case TYPE_HIGH:
      return 24;
      break;
   case TYPE_LOW:
      return 20;
      break;
   default:
      ast_log(LOG_WARNING, "Badly encoded frame (%d)\n", type);
   }
   return -1;
}
static int g723_samples (unsigned char * buf, int maxlen) [static]
Definition at line 1307 of file frame.c.
References g723_len().
Referenced by ast_codec_get_samples().
{
   int pos = 0;
   int samples = 0;
   int res;
   while(pos < maxlen) {
      res = g723_len(buf[pos]);
      if (res <= 0)
         break;
      samples += 240;
      pos += res;
   }
   return samples;
}
static unsigned char get_n_bits_at (unsigned char * data, int n, int bit) [static]
Definition at line 1322 of file frame.c.
Referenced by speex_get_wb_sz_at(), and speex_samples().
{
   int byte = bit / 8;       /* byte containing first bit */
   int rem = 8 - (bit % 8);  /* remaining bits in first byte */
   unsigned char ret = 0;
   if (n <= 0 || n > 8)
      return 0;
   if (rem < n) {
      ret = (data[byte] << (n - rem));
      ret |= (data[byte + 1] >> (8 - n + rem));
   } else {
      ret = (data[byte] >> (rem - n));
   }
   return (ret & (0xff >> (8 - n)));
}
int init_framer (void)
Provided by frame.c
Definition at line 968 of file frame.c.
References ARRAY_LEN, and ast_cli_register_multiple().
Referenced by main().
{
   ast_cli_register_multiple(my_clis, ARRAY_LEN(my_clis));
   return 0;
}
static char* show_codec_n (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 722 of file frame.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_codec2str(), CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, and ast_cli_entry::usage.
{
   int codec, i, found=0;
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show codec";
      e->usage =
         "Usage: core show codec <number>\n"
         "       Displays codec mapping\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if (a->argc != 4)
      return CLI_SHOWUSAGE;
   if (sscanf(a->argv[3], "%30d", &codec) != 1)
      return CLI_SHOWUSAGE;
   for (i = 0; i < 32; i++)
      if (codec & (1 << i)) {
         found = 1;
         ast_cli(a->fd, "%11u (1 << %2d)  %s\n",1 << i,i,ast_codec2str(1<<i));
      }
   if (!found)
      ast_cli(a->fd, "Codec %d not found\n", codec);
   return CLI_SUCCESS;
}
static char* show_codecs (struct ast_cli_entry * e, int cmd, struct ast_cli_args * a) [static]
Definition at line 667 of file frame.c.
References ast_cli_args::argc, ast_cli_args::argv, ast_cli(), ast_codec2str(), ast_getformatname(), ast_opt_dont_warn, CLI_GENERATE, CLI_INIT, CLI_SHOWUSAGE, CLI_SUCCESS, ast_cli_entry::command, ast_cli_args::fd, and ast_cli_entry::usage.
{
   int i, found=0;
   char hex[25];
   switch (cmd) {
   case CLI_INIT:
      e->command = "core show codecs [audio|video|image]";
      e->usage =
         "Usage: core show codecs [audio|video|image]\n"
         "       Displays codec mapping\n";
      return NULL;
   case CLI_GENERATE:
      return NULL;
   }
   if ((a->argc < 3) || (a->argc > 4))
      return CLI_SHOWUSAGE;
   if (!ast_opt_dont_warn)
      ast_cli(a->fd, "Disclaimer: this command is for informational purposes only.\n"
            "\tIt does not indicate anything about your configuration.\n");
   ast_cli(a->fd, "%11s %9s %10s   TYPE   %8s   %s\n","INT","BINARY","HEX","NAME","DESC");
   ast_cli(a->fd, "--------------------------------------------------------------------------------\n");
   if ((a->argc == 3) || (!strcasecmp(a->argv[3],"audio"))) {
      found = 1;
      for (i=0;i<13;i++) {
         snprintf(hex,25,"(0x%x)",1<<i);
         ast_cli(a->fd, "%11u (1 << %2d) %10s  audio   %8s   (%s)\n",1 << i,i,hex,ast_getformatname(1<<i),ast_codec2str(1<<i));
      }
   }
   if ((a->argc == 3) || (!strcasecmp(a->argv[3],"image"))) {
      found = 1;
      for (i=16;i<18;i++) {
         snprintf(hex,25,"(0x%x)",1<<i);
         ast_cli(a->fd, "%11u (1 << %2d) %10s  image   %8s   (%s)\n",1 << i,i,hex,ast_getformatname(1<<i),ast_codec2str(1<<i));
      }
   }
   if ((a->argc == 3) || (!strcasecmp(a->argv[3],"video"))) {
      found = 1;
      for (i=18;i<22;i++) {
         snprintf(hex,25,"(0x%x)",1<<i);
         ast_cli(a->fd, "%11u (1 << %2d) %10s  video   %8s   (%s)\n",1 << i,i,hex,ast_getformatname(1<<i),ast_codec2str(1<<i));
      }
   }
   if (!found)
      return CLI_SHOWUSAGE;
   else
      return CLI_SUCCESS;
}
static int smoother_frame_feed (struct ast_smoother * s, struct ast_frame * f, int swap) [static]
Definition at line 126 of file frame.c.
References ast_log(), AST_SMOOTHER_FLAG_G729, ast_swapcopy_samples(), ast_tvzero(), ast_frame::data, ast_smoother::data, ast_frame::datalen, ast_smoother::delivery, ast_frame::delivery, ast_smoother::flags, ast_smoother::len, LOG_NOTICE, ast_frame::ptr, and ast_frame::samples.
Referenced by __ast_smoother_feed(), and ast_smoother_reconfigure().
{
   if (s->flags & AST_SMOOTHER_FLAG_G729) {
      if (s->len % 10) {
         ast_log(LOG_NOTICE, "Dropping extra frame of G.729 since we already have a VAD frame at the end\n");
         return 0;
      }
   }
   if (swap) {
      ast_swapcopy_samples(s->data + s->len, f->data.ptr, f->samples);
   } else {
      memcpy(s->data + s->len, f->data.ptr, f->datalen);
   }
   /* If either side is empty, reset the delivery time */
   if (!s->len || ast_tvzero(f->delivery) || ast_tvzero(s->delivery)) { /* XXX really ? */
      s->delivery = f->delivery;
   }
   s->len += f->datalen;
   return 0;
}
static int speex_get_wb_sz_at (unsigned char * data, int len, int bit) [static]
Definition at line 1341 of file frame.c.
References ast_log(), get_n_bits_at(), and LOG_WARNING.
Referenced by speex_samples().
{
   static int SpeexWBSubModeSz[] = {
      0, 36, 112, 192,
      352, 0, 0, 0 };
   int off = bit;
   unsigned char c;
   /* skip up to two wideband frames */
   if (((len * 8 - off) >= 5) &&
      get_n_bits_at(data, 1, off)) {
      c = get_n_bits_at(data, 3, off + 1);
      off += SpeexWBSubModeSz[c];
      if (((len * 8 - off) >= 5) &&
         get_n_bits_at(data, 1, off)) {
         c = get_n_bits_at(data, 3, off + 1);
         off += SpeexWBSubModeSz[c];
         if (((len * 8 - off) >= 5) &&
            get_n_bits_at(data, 1, off)) {
            ast_log(LOG_WARNING, "Encountered corrupt speex frame; too many wideband frames in a row.\n");
            return -1;
         }
      }
   }
   return off - bit;
}
static int speex_samples (unsigned char * data, int len) [static]
Definition at line 1371 of file frame.c.
References ast_log(), get_n_bits_at(), LOG_WARNING, and speex_get_wb_sz_at().
Referenced by ast_codec_get_samples().
{
   static int SpeexSubModeSz[] = {
      5, 43, 119, 160,
      220, 300, 364, 492,
      79, 0, 0, 0,
      0, 0, 0, 0 };
   static int SpeexInBandSz[] = {
      1, 1, 4, 4,
      4, 4, 4, 4,
      8, 8, 16, 16,
      32, 32, 64, 64 };
   int bit = 0;
   int cnt = 0;
   int off;
   unsigned char c;
   while ((len * 8 - bit) >= 5) {
      /* skip wideband frames */
      off = speex_get_wb_sz_at(data, len, bit);
      if (off < 0)  {
         ast_log(LOG_WARNING, "Had error while reading wideband frames for speex samples\n");
         break;
      }
      bit += off;
      if ((len * 8 - bit) < 5) {
         ast_log(LOG_WARNING, "Not enough bits remaining after wide band for speex samples.\n");
         break;
      }
      /* get control bits */
      c = get_n_bits_at(data, 5, bit);
      bit += 5;
      if (c == 15) {
         /* terminator */
         break;
      } else if (c == 14) {
         /* in-band signal; next 4 bits contain signal id */
         c = get_n_bits_at(data, 4, bit);
         bit += 4;
         bit += SpeexInBandSz[c];
      } else if (c == 13) {
         /* user in-band; next 5 bits contain msg len */
         c = get_n_bits_at(data, 5, bit);
         bit += 5;
         bit += c * 8;
      } else if (c > 8) {
         /* unknown */
         break;
      } else {
         /* skip number bits for submode (less the 5 control bits) */
         bit += SpeexSubModeSz[c] - 5;
         cnt += 160; /* new frame */
      }
   }
   return cnt;
}
Variable Documentation
struct ast_format_list AST_FORMAT_LIST[] [static]
Definition of supported media formats (codecs).
Definition at line 96 of file frame.c.
struct ast_frame ast_null_frame = { AST_FRAME_NULL, }
Queueing a null frame is fairly common, so we declare a global null frame object for this purpose instead of having to declare one on the stack
Definition at line 124 of file frame.c.
Referenced by __ast_read(), __oh323_rtp_create(), __oh323_update_info(), agent_new(), agent_read(), ast_channel_masquerade(), ast_channel_setwhentohangup_tv(), ast_do_masquerade(), ast_rtcp_read(), ast_rtp_read(), ast_softhangup_nolock(), ast_udptl_read(), bridge_read(), conf_run(), console_read(), dahdi_read(), gtalk_rtp_read(), handle_request_invite(), handle_response_invite(), iax2_read(), jingle_rtp_read(), local_read(), mgcp_rtp_read(), oh323_read(), oh323_rtp_read(), process_rfc2833(), process_sdp(), send_dtmf(), sip_read(), sip_rtp_read(), skinny_rtp_read(), unistim_rtp_read(), and wakeup_sub().
struct ast_threadstorage frame_cache = { .once = PTHREAD_ONCE_INIT , .key_init = __init_frame_cache , .custom_init = NULL , } [static]
Definition at line 47 of file frame.c.
Referenced by __frame_free(), ast_frame_header_new(), ast_frdup(), iax_frame_free(), and iax_frame_new().
struct ast_cli_entry my_clis[] [static]
Initial value:
 {
   AST_CLI_DEFINE(show_codecs, "Displays a list of codecs"),
   AST_CLI_DEFINE(show_codec_n, "Shows a specific codec"),
}
Definition at line 963 of file frame.c.