Wed May 5 15:22:09 2010
Asterisk developer's documentation
func_md5.c File Reference
MD5 digest related dialplan functions.
#include "asterisk.h"
#include "asterisk/module.h"
#include "asterisk/pbx.h"
Functions
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"MD5 digest dialplan functions")
static int load_module (void)
static int md5 (struct ast_channel *chan, const char *cmd, char *data, char *buf, size_t len)
static int unload_module (void)
Variables
static struct ast_custom_function md5_function
Detailed Description
MD5 digest related dialplan functions.
Author:
Olle E. Johansson <oej@edvina.net>
Russell Bryant <russelb@clemson.edu>
Definition in file func_md5.c.
Function Documentation
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "MD5 digest dialplan functions")
static int load_module (void) [static]
Definition at line 74 of file func_md5.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&md5_function);
}
static int md5 (struct ast_channel * chan, const char * cmd, char * data, char * buf, size_t len) [static]
Definition at line 50 of file func_md5.c.
References ast_log(), ast_md5_hash(), ast_strlen_zero(), and LOG_WARNING.
{
   if (ast_strlen_zero(data)) {
      ast_log(LOG_WARNING, "Syntax: MD5(<data>) - missing argument!\n");
      return -1;
   }
   ast_md5_hash(buf, data);
   buf[32] = '\0';
   return 0;
}
static int unload_module (void) [static]
Definition at line 69 of file func_md5.c.
References ast_custom_function_unregister().
{
   return ast_custom_function_unregister(&md5_function);
}
Variable Documentation
struct ast_custom_function md5_function [static]
Initial value:
 {
   .name = "MD5",
   .read = md5,
}
Definition at line 64 of file func_md5.c.