Wed May 5 15:22:10 2010
Asterisk developer's documentation
func_vmcount.c File Reference
VMCOUNT dialplan function.
#include "asterisk.h"
#include <dirent.h>
#include "asterisk/file.h"
#include "asterisk/channel.h"
#include "asterisk/pbx.h"
#include "asterisk/module.h"
#include "asterisk/lock.h"
#include "asterisk/utils.h"
#include "asterisk/app.h"
Functions
static int acf_vmcount_exec (struct ast_channel *chan, const char *cmd, char *argsstr, char *buf, size_t len)
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY,"Indicator for whether a voice mailbox has messages in a given folder.")
static int load_module (void)
static int unload_module (void)
Variables
struct ast_custom_function acf_vmcount
Detailed Description
VMCOUNT dialplan function.
Author:
Tilghman Lesher <asterisk-vmcount-func@the-tilghman.com>
Definition in file func_vmcount.c.
Function Documentation
static int acf_vmcount_exec (struct ast_channel * chan, const char * cmd, char * argsstr, char * buf, size_t len) [static]
Definition at line 66 of file func_vmcount.c.
References AST_APP_ARG, ast_app_messagecount(), AST_DECLARE_APP_ARGS, AST_STANDARD_APP_ARGS, ast_strlen_zero(), context, and strsep().
{
   char *context;
   AST_DECLARE_APP_ARGS(args,
      AST_APP_ARG(vmbox);
      AST_APP_ARG(folder);
   );
   buf[0] = '\0';
   if (ast_strlen_zero(argsstr))
      return -1;
   AST_STANDARD_APP_ARGS(args, argsstr);
   if (strchr(args.vmbox, '@')) {
      context = args.vmbox;
      args.vmbox = strsep(&context, "@");
   } else {
      context = "default";
   }
   if (ast_strlen_zero(args.folder)) {
      args.folder = "INBOX";
   }
   snprintf(buf, len, "%d", ast_app_messagecount(context, args.vmbox, args.folder));
   return 0;
}
AST_MODULE_INFO_STANDARD (ASTERISK_GPL_KEY , "Indicator for whether a voice mailbox has messages in a given folder.")
static int load_module (void) [static]
Definition at line 107 of file func_vmcount.c.
References ast_custom_function_register.
{
   return ast_custom_function_register(&acf_vmcount);
}
static int unload_module (void) [static]
Definition at line 102 of file func_vmcount.c.
References ast_custom_function_unregister().
{
   return ast_custom_function_unregister(&acf_vmcount);
}
Variable Documentation
struct ast_custom_function acf_vmcount
Initial value:
 {
   .name = "VMCOUNT",
   .read = acf_vmcount_exec,
}
Definition at line 97 of file func_vmcount.c.