Wed May 5 15:22:11 2010
Asterisk developer's documentation
heap.c File Reference
Max Heap data structure.
#include "asterisk.h"
#include "asterisk/heap.h"
#include "asterisk/utils.h"
#include "asterisk/cli.h"
Data Structures
struct ast_heap
Functions
static void * _ast_heap_remove (struct ast_heap *h, unsigned int index)
struct ast_heap * ast_heap_create (unsigned int init_height, ast_heap_cmp_fn cmp_fn, ssize_t index_offset)
Create a max heap.
struct ast_heap * ast_heap_destroy (struct ast_heap *h)
Destroy a max heap.
void * ast_heap_peek (struct ast_heap *h, unsigned int index)
Peek at an element on a heap.
void * ast_heap_pop (struct ast_heap *h)
Pop the max element off of the heap.
int ast_heap_push (struct ast_heap *h, void *elm)
Push an element on to a heap.
int ast_heap_rdlock (struct ast_heap *h)
Read-Lock a heap.
void * ast_heap_remove (struct ast_heap *h, void *elm)
Remove a specific element from a heap.
size_t ast_heap_size (struct ast_heap *h)
Get the current size of a heap.
int ast_heap_unlock (struct ast_heap *h)
Unlock a heap.
int ast_heap_verify (struct ast_heap *h)
Verify that a heap has been properly constructed.
int ast_heap_wrlock (struct ast_heap *h)
Write-Lock a heap.
static ssize_t get_index (struct ast_heap *h, void *elm)
static int grow_heap (struct ast_heap *h)
Add a row of additional storage for the heap.
static void * heap_get (struct ast_heap *h, int i)
static void heap_set (struct ast_heap *h, int i, void *elm)
static void heap_swap (struct ast_heap *h, int i, int j)
static int left_node (int i)
static void max_heapify (struct ast_heap *h, int i)
static int parent_node (int i)
static int right_node (int i)
Detailed Description
Max Heap data structure.
Author:
Russell Bryant <russell@digium.com>
Definition in file heap.c.
Function Documentation
static void* _ast_heap_remove (struct ast_heap * h, unsigned int index) [static]
Definition at line 259 of file heap.c.
References ast_heap::cur_len, heap_get(), heap_set(), and max_heapify().
Referenced by ast_heap_pop(), and ast_heap_remove().
{
   void *ret;
   if (!index || index > h->cur_len) {
      return NULL;
   }
   ret = heap_get(h, index);
   heap_set(h, index, heap_get(h, (h->cur_len)--));
   max_heapify(h, index);
   return ret;
}
struct ast_heap* ast_heap_create (unsigned int init_height, ast_heap_cmp_fn cmp_fn, ssize_t index_offset) [read]
Create a max heap.
Parameters:
init_height The initial height of the heap to allocate space for. To start out, there will be room for (2 ^ init_height) - 1 entries. However, the heap will grow as needed.
cmp_fn The function that should be used to compare elements in the heap.
index_offset This parameter is optional, but must be provided to be able to use ast_heap_remove(). This is the number of bytes into the element where an ssize_t has been made available for the heap's internal use. The heap will use this field to keep track of the element's current position in the heap. The offsetof() macro is useful for providing a proper value for this argument. If ast_heap_remove() will not be used, then a negative value can be provided to indicate that no field for an offset has been allocated.
Example Usage:
 struct myobj {
    int foo;
    int bar;
    char stuff[8];
    char things[8];
    ssize_t __heap_index;
 };
 ...
 static int myobj_cmp(void *obj1, void *obj2);
 ...
 struct ast_heap *h;
 h = ast_heap_create(8, myobj_cmp, offsetof(struct myobj, __heap_index));
Returns:
An instance of a max heap
Since:
1.6.1
Definition at line 114 of file heap.c.
References __ast_calloc(), ast_calloc, ast_free, ast_log(), ast_rwlock_init(), ast_heap::avail_len, ast_heap::cmp_fn, ast_heap::heap, ast_heap::index_offset, ast_heap::lock, and LOG_ERROR.
Referenced by ast_timing_init(), load_resource_list(), and sched_context_create().
{
   struct ast_heap *h;
   if (!cmp_fn) {
      ast_log(LOG_ERROR, "A comparison function must be provided\n");
      return NULL;
   }
   if (!init_height) {
      init_height = 8;
   }
   if (!(h =
#ifdef MALLOC_DEBUG
         __ast_calloc(1, sizeof(*h), file, lineno, func)
#else
         ast_calloc(1, sizeof(*h))
#endif
      )) {
      return NULL;
   }
   h->cmp_fn = cmp_fn;
   h->index_offset = index_offset;
   h->avail_len = (1 << init_height) - 1;
   if (!(h->heap =
#ifdef MALLOC_DEBUG
         __ast_calloc(1, h->avail_len * sizeof(void *), file, lineno, func)
#else
         ast_calloc(1, h->avail_len * sizeof(void *))
#endif
      )) {
      ast_free(h);
      return NULL;
   }
   ast_rwlock_init(&h->lock);
   return h;
}
struct ast_heap* ast_heap_destroy (struct ast_heap * h) [read]
Destroy a max heap.
Parameters:
h the heap to destroy
Returns:
NULL for convenience
Since:
1.6.1
Definition at line 159 of file heap.c.
References ast_free, ast_rwlock_destroy(), ast_heap::heap, and ast_heap::lock.
Referenced by load_resource_list(), and sched_context_destroy().
{
   ast_free(h->heap);
   h->heap = NULL;
   ast_rwlock_destroy(&h->lock);
   ast_free(h);
   return NULL;
}
void* ast_heap_peek (struct ast_heap * h, unsigned int index)
Peek at an element on a heap.
Parameters:
h the heap
index index of the element to return. The first element is at index 1, and the last element is at the index == the size of the heap.
Returns:
an element at the specified index on the heap. This element will not be removed before being returned.
Note:
If this function is being used in combination with ast_heap_size() for purposes of traversing the heap, the heap must be locked for the entire duration of the traversal.
Example code for a traversal:
 struct ast_heap *h;
 ...
 size_t size, i;
 void *cur_obj;
 ast_heap_rdlock(h);
 size = ast_heap_size(h);
 for (i = 1; i <= size && (cur_obj = ast_heap_peek(h, i)); i++) {
     ... Do stuff with cur_obj ...
 }
 ast_heap_unlock(h);
Since:
1.6.1
Definition at line 291 of file heap.c.
References ast_heap::cur_len, and heap_get().
Referenced by ast_sched_dump(), ast_sched_report(), ast_sched_runq(), ast_sched_wait(), and ast_timer_open().
{
   if (!h->cur_len || !index || index > h->cur_len) {
      return NULL;
   }
   return heap_get(h, index);
}
void* ast_heap_pop (struct ast_heap * h)
Pop the max element off of the heap.
Parameters:
h the heap
Returns:
this will return the element on the top of the heap, which has the largest value according to the element comparison function that was provided when the heap was created. The element will be removed before being returned.
Since:
1.6.1
Definition at line 286 of file heap.c.
References _ast_heap_remove().
Referenced by ast_sched_runq(), load_resource_list(), and sched_context_destroy().
{
   return _ast_heap_remove(h, 1);
}
int ast_heap_push (struct ast_heap * h, void * elm)
Push an element on to a heap.
Parameters:
h the heap being added to
elm the element being put on the heap
Return values:
0 success
non-zero failure
Since:
1.6.1
Definition at line 235 of file heap.c.
References ast_heap::avail_len, ast_heap::cmp_fn, ast_heap::cur_len, grow_heap(), heap_get(), heap_set(), heap_swap(), and parent_node().
Referenced by _ast_register_timing_interface(), load_resource(), and schedule().
{
   int i;
   if (h->cur_len == h->avail_len && grow_heap(h
#ifdef MALLOC_DEBUG
      , file, lineno, func
#endif
      )) {
      return -1;
   }
   heap_set(h, ++(h->cur_len), elm);
   for (i = h->cur_len;
         i > 1 && h->cmp_fn(heap_get(h, parent_node(i)), heap_get(h, i)) < 0;
         i = parent_node(i)) {
      heap_swap(h, i, parent_node(i));
   }
   return 0;
}
int ast_heap_rdlock (struct ast_heap * h)
Read-Lock a heap.
Parameters:
h the heap
A lock is provided for convenience. It can be assumed that none of the ast_heap API calls are thread safe. This lock does not have to be used if another one is already available to protect the heap.
Returns:
see the documentation for pthread_rwlock_rdlock()
Since:
1.6.1
Definition at line 312 of file heap.c.
References ast_rwlock_rdlock(), and ast_heap::lock.
Referenced by ast_timer_open().
{
   return ast_rwlock_rdlock(&h->lock);
}
void* ast_heap_remove (struct ast_heap * h, void * elm)
Remove a specific element from a heap.
Parameters:
h the heap to remove from
elm the element to remove
Returns:
elm, if the removal was successful, or NULL if it failed
Note:
the index_offset parameter to ast_heap_create() is required to be able to use this function.
Since:
1.6.1
Definition at line 275 of file heap.c.
References _ast_heap_remove(), and get_index().
Referenced by ast_sched_del(), and ast_unregister_timing_interface().
{
   ssize_t i = get_index(h, elm);
   if (i == -1) {
      return NULL;
   }
   return _ast_heap_remove(h, i);
}
size_t ast_heap_size (struct ast_heap * h)
Get the current size of a heap.
Parameters:
h the heap
Returns:
the number of elements currently in the heap
Since:
1.6.1
Definition at line 300 of file heap.c.
References ast_heap::cur_len.
Referenced by ast_sched_dump(), and ast_sched_report().
{
   return h->cur_len;
}
int ast_heap_unlock (struct ast_heap * h)
Unlock a heap.
Parameters:
h the heap
Returns:
see the documentation for pthread_rwlock_unlock()
Since:
1.6.1
Definition at line 317 of file heap.c.
References ast_rwlock_unlock(), and ast_heap::lock.
Referenced by _ast_register_timing_interface(), ast_timer_open(), and ast_unregister_timing_interface().
{
   return ast_rwlock_unlock(&h->lock);
}
int ast_heap_verify (struct ast_heap * h)
Verify that a heap has been properly constructed.
Parameters:
h a heap
Return values:
0 success
non-zero failure
Note:
This function is mostly for debugging purposes. It traverses an existing heap and verifies that every node is properly placed relative to its children.
Since:
1.6.1
Definition at line 86 of file heap.c.
References ast_heap::cmp_fn, ast_heap::cur_len, heap_get(), left_node(), and right_node().
{
   unsigned int i;
   for (i = 1; i <= (h->cur_len / 2); i++) {
      int l = left_node(i);
      int r = right_node(i);
      if (l <= h->cur_len) {
         if (h->cmp_fn(heap_get(h, i), heap_get(h, l)) <= 0) {
            return -1;
         }
      }
      if (r <= h->cur_len) {
         if (h->cmp_fn(heap_get(h, i), heap_get(h, r)) <= 0) {
            return -1;
         }
      }
   }
   return 0;
}
int ast_heap_wrlock (struct ast_heap * h)
Write-Lock a heap.
Parameters:
h the heap
A lock is provided for convenience. It can be assumed that none of the ast_heap API calls are thread safe. This lock does not have to be used if another one is already available to protect the heap.
Returns:
see the documentation for pthread_rwlock_wrlock()
Since:
1.6.1
Definition at line 307 of file heap.c.
References ast_rwlock_wrlock(), and ast_heap::lock.
Referenced by _ast_register_timing_interface(), and ast_unregister_timing_interface().
{
   return ast_rwlock_wrlock(&h->lock);
}
static ssize_t get_index (struct ast_heap * h, void * elm) [inline, static]
Definition at line 63 of file heap.c.
References ast_heap::index_offset.
Referenced by ast_heap_remove().
{
   ssize_t *index;
   if (h->index_offset < 0) {
      return -1;
   }
   index = elm + h->index_offset;
   return *index;
}
static int grow_heap (struct ast_heap * h) [static]
Add a row of additional storage for the heap.
Definition at line 174 of file heap.c.
References __ast_realloc(), and ast_realloc.
Referenced by ast_heap_push().
{
   h->avail_len = h->avail_len * 2 + 1;
   if (!(h->heap =
#ifdef MALLOC_DEBUG
         __ast_realloc(h->heap, h->avail_len * sizeof(void *), file, lineno, func)
#else
         ast_realloc(h->heap, h->avail_len * sizeof(void *))
#endif
      )) {
      h->cur_len = h->avail_len = 0;
      return -1;
   }
   return 0;
}
static void* heap_get (struct ast_heap * h, int i) [inline, static]
Definition at line 58 of file heap.c.
References ast_heap::heap.
Referenced by _ast_heap_remove(), ast_heap_peek(), ast_heap_push(), ast_heap_verify(), heap_swap(), and max_heapify().
{
   return h->heap[i - 1];
}
static void heap_set (struct ast_heap * h, int i, void * elm) [inline, static]
Definition at line 76 of file heap.c.
References ast_heap::heap, and ast_heap::index_offset.
Referenced by _ast_heap_remove(), ast_heap_push(), and heap_swap().
{
   h->heap[i - 1] = elm;
   if (h->index_offset >= 0) {
      ssize_t *index = elm + h->index_offset;
      *index = i;
   }
}
static void heap_swap (struct ast_heap * h, int i, int j) [inline, static]
Definition at line 196 of file heap.c.
References heap_get(), and heap_set().
Referenced by ast_heap_push(), and max_heapify().
{
   void *tmp;
   tmp = heap_get(h, i);
   heap_set(h, i, heap_get(h, j));
   heap_set(h, j, tmp);
}
static int left_node (int i) [inline, static]
Definition at line 43 of file heap.c.
Referenced by ast_heap_verify(), and max_heapify().
{
   return 2 * i;
}
static void max_heapify (struct ast_heap * h, int i) [inline, static]
Definition at line 205 of file heap.c.
References ast_heap::cmp_fn, ast_heap::cur_len, heap_get(), heap_swap(), left_node(), and right_node().
Referenced by _ast_heap_remove().
{
   for (;;) {
      int l = left_node(i);
      int r = right_node(i);
      int max;
      if (l <= h->cur_len && h->cmp_fn(heap_get(h, l), heap_get(h, i)) > 0) {
         max = l;
      } else {
         max = i;
      }
      if (r <= h->cur_len && h->cmp_fn(heap_get(h, r), heap_get(h, max)) > 0) {
         max = r;
      }
      if (max == i) {
         break;
      }
      heap_swap(h, i, max);
      i = max;
   }
}
static int parent_node (int i) [inline, static]
Definition at line 53 of file heap.c.
Referenced by ast_heap_push().
{
   return i / 2;
}
static int right_node (int i) [inline, static]
Definition at line 48 of file heap.c.
Referenced by ast_heap_verify(), and max_heapify().
{
   return 2 * i + 1;
}