Wed May 5 15:23:40 2010
Asterisk developer's documentation
ast_datastore_info Struct Reference
Structure for a data store type.
#include <datastore.h>
Data Fields
void(* chan_fixup)(void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references.
void(* destroy)(void *data)
void *(* duplicate)(void *data)
const char * type
Detailed Description
Structure for a data store type.
Definition at line 31 of file datastore.h.
Field Documentation
void(* chan_fixup)(void *data, struct ast_channel *old_chan, struct ast_channel *new_chan)
Fix up channel references.
data The datastore data
old_chan The old channel owning the datastore
new_chan The new channel owning the datastore
This is exactly like the fixup callback of the channel technology interface. It allows a datastore to fix any pointers it saved to the owning channel in case that the owning channel has changed. Generally, this would happen when the datastore is set to be inherited, and a masquerade occurs.
Returns:
nothing.
Referenced by ast_do_masquerade().
void(* destroy)(void *data)
Destroy function
Referenced by ast_datastore_free().
void*(* duplicate)(void *data)
Duplicate item data (used for inheritance)
Referenced by ast_channel_datastore_inherit().
const char* type
Type of data store
Definition at line 32 of file datastore.h.
The documentation for this struct was generated from the following file:
datastore.h