Wed May 5 15:23:41 2010
Asterisk developer's documentation
ast_speech_engine Struct Reference
#include <speech.h>
Data Fields
int(* activate)(struct ast_speech *speech, char *grammar_name)
int(* change)(struct ast_speech *speech, char *name, const char *value)
int(* change_results_type)(struct ast_speech *speech, enum ast_speech_results_type results_type)
int(* create)(struct ast_speech *speech, int format)
int(* deactivate)(struct ast_speech *speech, char *grammar_name)
int(* destroy)(struct ast_speech *speech)
int(* dtmf)(struct ast_speech *speech, const char *dtmf)
int formats
struct ast_speech_result *(* get)(struct ast_speech *speech)
struct {
struct ast_speech_engine * next
} list
int(* load)(struct ast_speech *speech, char *grammar_name, char *grammar)
char * name
int(* start)(struct ast_speech *speech)
int(* unload)(struct ast_speech *speech, char *grammar_name)
int(* write)(struct ast_speech *speech, void *data, int len)
Detailed Description
Definition at line 73 of file speech.h.
Field Documentation
int(* activate)(struct ast_speech *speech, char *grammar_name)
Activate a loaded grammar
Referenced by ast_speech_grammar_activate().
int(* change)(struct ast_speech *speech, char *name, const char *value)
Change an engine specific setting
Referenced by ast_speech_change().
int(* change_results_type)(struct ast_speech *speech, enum ast_speech_results_type results_type)
Change the type of results we want back
Referenced by ast_speech_change_results_type().
int(* create)(struct ast_speech *speech, int format)
Set up the speech structure within the engine
Referenced by ast_speech_new(), and ast_speech_register().
int(* deactivate)(struct ast_speech *speech, char *grammar_name)
Deactivate a loaded grammar
Referenced by ast_speech_grammar_deactivate().
int(* destroy)(struct ast_speech *speech)
Destroy any data set on the speech structure by the engine
Referenced by ast_speech_destroy(), and ast_speech_register().
int(* dtmf)(struct ast_speech *speech, const char *dtmf)
Signal DTMF was received
Referenced by ast_speech_dtmf().
int formats
Accepted formats by the engine
Definition at line 101 of file speech.h.
Referenced by ast_speech_new().
struct ast_speech_result*(* get)(struct ast_speech *speech) [read]
Try to get results
Referenced by ast_speech_results_get().
struct { ... } list
Referenced by ast_speech_register(), ast_speech_unregister(), and find_engine().
int(* load)(struct ast_speech *speech, char *grammar_name, char *grammar)
Load a local grammar on the speech structure
Referenced by ast_speech_grammar_load().
char* name
Name of speech engine
Definition at line 75 of file speech.h.
Referenced by ast_speech_register(), ast_speech_unregister(), and find_engine().
struct ast_speech_engine* next [read]
Definition at line 102 of file speech.h.
int(* start)(struct ast_speech *speech)
Prepare engine to accept audio
Referenced by ast_speech_start().
int(* unload)(struct ast_speech *speech, char *grammar_name)
Unload a local grammar
Referenced by ast_speech_grammar_unload().
int(* write)(struct ast_speech *speech, void *data, int len)
Write audio to the speech engine
Referenced by ast_speech_register(), and ast_speech_write().
The documentation for this struct was generated from the following file:
speech.h