Wed May 5 15:23:41 2010
Asterisk developer's documentation
ast_rtp_protocol Struct Reference
This is the structure that binds a channel (SIP/Jingle/H.323) to the RTP subsystem.
#include <rtp.h>
Data Fields
int(*const get_codec)(struct ast_channel *chan)
enum ast_rtp_get_result(*const get_rtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
enum ast_rtp_get_result(*const get_trtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
enum ast_rtp_get_result(*const get_vrtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
struct {
struct ast_rtp_protocol * next
} list
int(*const set_rtp_peer)(struct ast_channel *chan, struct ast_rtp *peer, struct ast_rtp *vpeer, struct ast_rtp *tpeer, int codecs, int nat_active)
const char *const type
Detailed Description
This is the structure that binds a channel (SIP/Jingle/H.323) to the RTP subsystem.
Definition at line 95 of file rtp.h.
Field Documentation
int(* const get_codec)(struct ast_channel *chan)
Referenced by ast_rtp_bridge(), ast_rtp_early_bridge(), ast_rtp_make_compatible(), and bridge_native_loop().
enum ast_rtp_get_result(* const get_rtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
Get RTP struct, or NULL if unwilling to transfer
Referenced by ast_rtp_bridge(), ast_rtp_early_bridge(), and ast_rtp_make_compatible().
enum ast_rtp_get_result(* const get_trtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
Get RTP struct, or NULL if unwilling to transfer
Referenced by ast_rtp_bridge(), ast_rtp_early_bridge(), and ast_rtp_make_compatible().
enum ast_rtp_get_result(* const get_vrtp_info)(struct ast_channel *chan, struct ast_rtp **rtp)
Get RTP struct, or NULL if unwilling to transfer
Referenced by ast_rtp_bridge(), ast_rtp_early_bridge(), and ast_rtp_make_compatible().
struct { ... } list
Referenced by ast_rtp_proto_register(), and get_proto().
struct ast_rtp_protocol* next [read]
Definition at line 106 of file rtp.h.
int(* const set_rtp_peer)(struct ast_channel *chan, struct ast_rtp *peer, struct ast_rtp *vpeer, struct ast_rtp *tpeer, int codecs, int nat_active)
Set RTP peer
Referenced by ast_rtp_early_bridge(), ast_rtp_make_compatible(), and bridge_native_loop().
const char* const type
Definition at line 105 of file rtp.h.
Referenced by ast_rtp_proto_register(), and get_proto().
The documentation for this struct was generated from the following file:
rtp.h