Wed May 5 15:23:43 2010
Asterisk developer's documentation
misdn_lib_iface Struct Reference
#include <isdn_lib.h>
Data Fields
enum event_response_e(* cb_event)(enum event_e event, struct misdn_bchannel *bc, void *user_data)
int(* cb_jb_empty)(struct misdn_bchannel *bc, char *buffer, int len)
void(* cb_log)(int level, int port, char *tmpl,...)
Detailed Description
Definition at line 577 of file isdn_lib.h.
Field Documentation
enum event_response_e(* cb_event)(enum event_e event, struct misdn_bchannel *bc, void *user_data)
Referenced by load_module(), and misdn_lib_init().
int(* cb_jb_empty)(struct misdn_bchannel *bc, char *buffer, int len)
Referenced by misdn_lib_init().
void(* cb_log)(int level, int port, char *tmpl,...)
Referenced by misdn_lib_init().
The documentation for this struct was generated from the following file:
isdn_lib.h