Wed May 5 15:23:40 2010
Asterisk developer's documentation
ast_bridge_technology Struct Reference
Structure that is the essence of a bridge technology.
#include <bridging_technology.h>
Public Member Functions
AST_RWLIST_ENTRY (ast_bridge_technology) entry
Data Fields
int capabilities
int(* compatible)(struct ast_bridge_channel *bridge_channel)
int(* create)(struct ast_bridge *bridge)
int(* destroy)(struct ast_bridge *bridge)
int(* fd)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel, int fd)
int formats
int(* join)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
int(* leave)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
struct ast_module * mod
const char * name
int(* poke)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
enum ast_bridge_preference preference
void(* suspend)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
unsigned int suspended:1
int(* thread)(struct ast_bridge *bridge)
void(* unsuspend)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
enum ast_bridge_write_result(* write)(struct ast_bridge *bridge, struct ast_bridge_channel *bridged_channel, struct ast_frame *frame)
Detailed Description
Structure that is the essence of a bridge technology.
Definition at line 44 of file bridging_technology.h.
Member Function Documentation
AST_RWLIST_ENTRY (ast_bridge_technology)
Linked list information
Field Documentation
int capabilities
The capabilities that this bridge technology is capable of
Definition at line 48 of file bridging_technology.h.
Referenced by __ast_bridge_technology_register(), ast_bridge_merge(), bridge_channel_join(), find_best_technology(), and smart_bridge_operation().
int(* compatible)(struct ast_bridge_channel *bridge_channel)
Callback to see if a channel is compatible with the bridging technology
int(* create)(struct ast_bridge *bridge)
Callback for when a bridge is being created
Referenced by ast_bridge_new(), and smart_bridge_operation().
int(* destroy)(struct ast_bridge *bridge)
Callback for when a bridge is being destroyed
Referenced by destroy_bridge().
int(* fd)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel, int fd)
Callback for when a file descriptor trips
Referenced by ast_bridge_handle_trip(), and bridge_channel_join_multithreaded().
int formats
Formats that the bridge technology supports
Definition at line 74 of file bridging_technology.h.
Referenced by bridge_make_compatible().
int(* join)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
Callback for when a channel is being added to a bridge
Referenced by ast_bridge_merge(), bridge_channel_join(), and smart_bridge_operation().
int(* leave)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
Callback for when a channel is leaving a bridge
Referenced by ast_bridge_merge(), and bridge_channel_join().
struct ast_module* mod [read]
Module this bridge technology belongs to. Is used for reference counting when creating/destroying a bridge.
Definition at line 78 of file bridging_technology.h.
Referenced by __ast_bridge_technology_register(), ast_bridge_check(), and destroy_bridge().
const char* name
Unique name to this bridge technology
Definition at line 46 of file bridging_technology.h.
Referenced by __ast_bridge_technology_register(), ast_bridge_merge(), ast_bridge_new(), ast_bridge_technology_unregister(), bridge_channel_join(), bridge_make_compatible(), destroy_bridge(), find_best_technology(), and smart_bridge_operation().
int(* poke)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
Callback for poking a bridge thread
Referenced by ast_bridge_handle_trip().
enum ast_bridge_preference preference
Preference level that should be used when determining whether to use this bridge technology or not
Definition at line 50 of file bridging_technology.h.
Referenced by find_best_technology().
void(* suspend)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
Callback for when a channel is suspended from the bridge
Referenced by bridge_channel_suspend().
unsigned int suspended
Bit to indicate whether the bridge technology is currently suspended or not
Definition at line 76 of file bridging_technology.h.
Referenced by ast_bridge_technology_suspend(), ast_bridge_technology_unsuspend(), and find_best_technology().
int(* thread)(struct ast_bridge *bridge)
Callback for replacement thread function
Referenced by bridge_thread().
void(* unsuspend)(struct ast_bridge *bridge, struct ast_bridge_channel *bridge_channel)
Callback for when a channel is unsuspended from the bridge
Referenced by bridge_channel_unsuspend().
enum ast_bridge_write_result(* write)(struct ast_bridge *bridge, struct ast_bridge_channel *bridged_channel, struct ast_frame *frame)
Callback for writing a frame into the bridging technology
Referenced by __ast_bridge_technology_register(), and ast_bridge_handle_trip().
The documentation for this struct was generated from the following file:
bridging_technology.h