Wed May 5 15:23:43 2010
Asterisk developer's documentation
loadupdate Struct Reference
Data Fields
struct {
struct loadupdate * next
} entry
int(* updater)(void)
Detailed Description
Definition at line 107 of file loader.c.
Field Documentation
struct { ... } entry
struct loadupdate* next [read]
Definition at line 109 of file loader.c.
int(* updater)(void)
Referenced by ast_loader_register(), ast_loader_unregister(), and ast_update_use_count().
The documentation for this struct was generated from the following file:
loader.c