Wed May 5 15:23:32 2010
Asterisk developer's documentation
time.h File Reference
Time-related functions and macros.
#include <sys/time.h>
#include "asterisk/inline_api.h"
Functions
struct timeval ast_samp2tv (unsigned int _nsamp, unsigned int _rate)
Returns a timeval corresponding to the duration of n samples at rate r. Useful to convert samples to timevals, or even milliseconds to timevals in the form ast_samp2tv(milliseconds, 1000).
struct timeval ast_tv (ast_time_t sec, ast_suseconds_t usec)
Returns a timeval from sec, usec.
struct timeval ast_tvadd (struct timeval a, struct timeval b)
Returns the sum of two timevals a + b.
int ast_tvcmp (struct timeval _a, struct timeval _b)
Compres two struct timeval instances returning -1, 0, 1 if the first arg is smaller, equal or greater to the second.
int ast_tvdiff_ms (struct timeval end, struct timeval start)
Computes the difference (in milliseconds) between two struct timeval instances.
int ast_tvdiff_sec (struct timeval end, struct timeval start)
Computes the difference (in seconds) between two struct timeval instances.
int64_t ast_tvdiff_us (struct timeval end, struct timeval start)
Computes the difference (in microseconds) between two struct timeval instances.
int ast_tveq (struct timeval _a, struct timeval _b)
Returns true if the two struct timeval arguments are equal.
struct timeval ast_tvnow (void)
Returns current timeval. Meant to replace calls to gettimeofday().
struct timeval ast_tvsub (struct timeval a, struct timeval b)
Returns the difference of two timevals a - b.
int ast_tvzero (const struct timeval t)
Returns true if the argument is 0,0.
typedef typeof (tv.tv_sec) ast_time_t
Variables
struct timeval tv
Detailed Description
Time-related functions and macros.
Definition in file time.h.
Function Documentation
__inline__ struct timeval ast_samp2tv (unsigned int _nsamp, unsigned int _rate) [read]
Returns a timeval corresponding to the duration of n samples at rate r. Useful to convert samples to timevals, or even milliseconds to timevals in the form ast_samp2tv(milliseconds, 1000).
Definition at line 176 of file time.h.
Referenced by __get_from_jb(), agent_hangup(), agent_read(), ast_audiohook_trigger_wait(), ast_channel_bridge(), ast_generic_bridge(), ast_rtp_read(), ast_smoother_read(), ast_translate(), calc_rxstamp(), calc_timestamp(), cli_tps_ping(), conf_run(), do_cdr(), do_parking_thread(), iax2_process_thread(), jb_get_and_deliver(), mb_poll_thread(), monmp3thread(), mp3_exec(), NBScat_exec(), process_rfc2833(), sched_run(), sched_settime(), schedule_delivery(), and sla_process_timers().
__inline__ struct timeval ast_tv (ast_time_t sec, ast_suseconds_t usec) [read]
Returns a timeval from sec, usec.
Definition at line 164 of file time.h.
Referenced by __dahdi_exception(), agent_hangup(), agent_request(), ast_cdr_merge(), ast_rtp_read(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_end(), ast_sched_add_variable(), ast_sched_runq(), ast_translate(), ast_translator_build_path(), cb_events(), dahdi_read(), do_immediate_setup(), do_monitor(), do_timing(), ices_exec(), login_exec(), misdn_read(), msg_timestamp(), mwi_monitor_handler(), phone_exception(), phone_read(), process_rfc2833(), pthread_timer_set_rate(), schedule_delivery(), and smdi_message_wait().
{
struct timeval ast_tvadd (struct timeval a, struct timeval b) [read]
Returns the sum of two timevals a + b.
Definition at line 1365 of file utils.c.
References ONE_MILLION, and tvfix().
Referenced by __get_from_jb(), agent_hangup(), agent_read(), ast_audiohook_trigger_wait(), ast_channel_bridge(), ast_channel_cmpwhentohangup_tv(), ast_channel_setwhentohangup_tv(), ast_generic_bridge(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_end(), ast_sched_runq(), ast_smoother_read(), ast_translate(), calc_rxstamp(), calc_timestamp(), cli_tps_ping(), conf_run(), dial_exec_full(), do_cdr(), do_timing(), iax2_process_thread(), jb_get_and_deliver(), mb_poll_thread(), monmp3thread(), mp3_exec(), mwi_monitor_handler(), NBScat_exec(), sched_run(), sched_settime(), schedule_delivery(), sla_process_timers(), smdi_message_wait(), and timeout_write().
{
   /* consistency checks to guarantee usec in 0..999999 */
   a = tvfix(a);
   b = tvfix(b);
   a.tv_sec += b.tv_sec;
   a.tv_usec += b.tv_usec;
   if (a.tv_usec >= ONE_MILLION) {
      a.tv_sec++;
      a.tv_usec -= ONE_MILLION;
   }
   return a;
}
__inline__ int ast_tvcmp (struct timeval _a, struct timeval _b)
Compres two struct timeval instances returning -1, 0, 1 if the first arg is smaller, equal or greater to the second.
Definition at line 119 of file time.h.
Referenced by ast_bridge_call(), ast_cdr_merge(), ast_sched_runq(), ast_waitfor_nandfds(), find_cache(), sched_settime(), sched_time_cmp(), and send_dtmf().
{
__inline__ int ast_tvdiff_ms (struct timeval end, struct timeval start)
Computes the difference (in milliseconds) between two struct timeval instances.
Parameters:
end end of the time period
start beginning of the time period
Returns:
the difference in milliseconds
Definition at line 89 of file time.h.
Referenced by __ast_read(), __get_from_jb(), __verboser(), action_coreshowchannels(), agent_cont_sleep(), agents_show(), ast_audiohook_write_frame(), ast_bridge_call(), ast_careful_fwrite(), ast_carefulwrite(), ast_cdr_getvar(), ast_channel_bridge(), ast_channel_cmpwhentohangup_tv(), ast_check_hangup(), ast_generic_bridge(), ast_get_enum(), ast_rtp_read(), ast_sched_wait(), ast_wait_for_output(), ast_waitfor_nandfds(), audiohook_read_frame_both(), background_detect_exec(), calc_rxstamp(), calc_timestamp(), calc_txpeerstamp(), calc_txstamp(), check_timer(), conf_run(), dahdi_handle_event(), dahdi_read(), destroy_trans(), disa_exec(), dundi_do_lookup(), dundi_do_precache(), dundi_lookup_internal(), dundi_precache_internal(), dundi_query_eid_internal(), feature_request_and_dial(), fix_peerts(), get_now(), handle_chanlist(), handle_cli_file_convert(), handle_recordfile(), handle_response_peerpoke(), handle_timeout_trip(), login_exec(), manage_parkinglot(), measurenoise(), misdn_overlap_dial_task(), misdn_read(), monmp3thread(), mp3_exec(), NBScat_exec(), process_rfc2833(), purge_old_messages(), receive_dtmf_digits(), rpt(), setformat(), should_skip_dtmf(), show_chanstats_cb(), sla_calc_station_timeouts(), sla_calc_trunk_timeouts(), sla_check_failed_station(), sla_check_station_delay(), smdi_message_wait(), speech_background(), timeout_read(), timing_test(), update_jbsched(), and waituntil_exec().
{
__inline__ int ast_tvdiff_sec (struct timeval end, struct timeval start)
Computes the difference (in seconds) between two struct timeval instances.
Parameters:
end the end of the time period
start the beginning of the time period
Returns:
the difference in seconds
Definition at line 56 of file time.h.
Referenced by ast_odbc_request_obj2(), transmit_audio(), and transmit_t38().
{
__inline__ int64_t ast_tvdiff_us (struct timeval end, struct timeval start)
Computes the difference (in microseconds) between two struct timeval instances.
Parameters:
end the end of the time period
start the beginning of the time period
Returns:
the difference in microseconds
Definition at line 70 of file time.h.
Referenced by ast_merge_contexts_and_delete(), and transmit_t38().
{
__inline__ int ast_tveq (struct timeval _a, struct timeval _b)
Returns true if the two struct timeval arguments are equal.
Definition at line 129 of file time.h.
Referenced by ast_translate().
{
__inline__ struct timeval ast_tvnow (void) [read]
Returns current timeval. Meant to replace calls to gettimeofday().
Definition at line 141 of file time.h.
Referenced by __ast_read(), __ast_verbose_ap(), __dahdi_exception(), __get_from_jb(), __manager_event(), acf_strftime(), action_coreshowchannels(), action_status(), add_agent(), agent_cont_sleep(), agent_hangup(), agent_read(), agent_request(), agents_show(), ast_audiohook_trigger_wait(), ast_audiohook_write_frame(), ast_bridge_call(), ast_careful_fwrite(), ast_carefulwrite(), ast_cdr_answer(), ast_cdr_end(), ast_cdr_getvar(), ast_cdr_start(), ast_channel_bridge(), ast_channel_cmpwhentohangup_tv(), ast_channel_setwhentohangup_tv(), ast_check_hangup(), ast_check_timing(), ast_generic_bridge(), ast_get_enum(), ast_log(), ast_merge_contexts_and_delete(), ast_module_reload(), ast_odbc_prepare_and_execute(), ast_odbc_request_obj2(), ast_odbc_smart_execute(), ast_rtp_sendcng(), ast_rtp_senddigit_begin(), ast_rtp_senddigit_end(), ast_rwlock_timedrdlock(), ast_rwlock_timedwrlock(), ast_say_date_with_format_da(), ast_say_date_with_format_de(), ast_say_date_with_format_en(), ast_say_date_with_format_es(), ast_say_date_with_format_fr(), ast_say_date_with_format_gr(), ast_say_date_with_format_he(), ast_say_date_with_format_it(), ast_say_date_with_format_nl(), ast_say_date_with_format_pl(), ast_say_date_with_format_pt(), ast_say_date_with_format_th(), ast_say_date_with_format_zh(), ast_say_datetime_from_now_en(), ast_say_datetime_from_now_fr(), ast_say_datetime_from_now_he(), ast_say_datetime_from_now_ka(), ast_say_datetime_from_now_pt(), ast_sched_dump(), ast_sched_runq(), ast_sched_wait(), ast_sched_when(), ast_translate(), ast_wait_for_output(), ast_waitfor_nandfds(), audiohook_read_frame_both(), background_detect_exec(), build_device(), calc_rxstamp(), calc_timestamp(), calc_txstamp(), callerid_genmsg(), canary_thread(), cb_events(), check_timer(), cli_prompt(), cli_tps_ping(), conf_run(), create_transaction(), dahdi_answer(), dahdi_call(), dahdi_handle_event(), dahdi_read(), destroy_trans(), dial_exec_full(), disa_exec(), do_cdr(), do_timing(), dundi_do_lookup(), dundi_do_precache(), dundi_lookup_internal(), dundi_precache_internal(), dundi_query_eid_internal(), feature_request_and_dial(), find_cache(), find_conf_realtime(), find_tpeer(), fix_peerts(), get_date(), get_tick_count(), handle_chanlist(), handle_cli_file_convert(), handle_cli_iax2_show_cache(), handle_recordfile(), handle_response_peerpoke(), handle_response_register(), handle_showcalls(), handle_showchan(), handle_showuptime(), handle_time_date_req_message(), handle_timeout_trip(), httpd_helper_thread(), iax2_bridge(), iax2_datetime(), iax2_process_thread(), iax2_trunk_queue(), leave_voicemail(), load_config(), login_exec(), main(), manage_parkinglot(), mb_poll_thread(), measurenoise(), mgcp_postrequest(), misdn_overlap_dial_task(), misdn_read(), monitor_dial(), monmp3thread(), mp3_exec(), mwi_monitor_handler(), NBScat_exec(), odbc_obj_connect(), park_call_full(), phone_call(), phoneprov_callback(), play_message_datetime(), process_text_line(), pthread_timer_set_rate(), purge_old_messages(), qualify_peer(), queue_ringing_trunk(), receive_dtmf_digits(), rpt(), rt_extend_conf(), sched_run(), sched_settime(), send_date_time(), send_date_time2(), send_date_time3(), send_dtmf(), sendmail(), serialize_showchan(), setformat(), should_skip_dtmf(), show_chanstats_cb(), sip_poke_peer(), sla_calc_station_timeouts(), sla_calc_trunk_timeouts(), sla_check_failed_station(), sla_check_station_delay(), sla_create_ringing_station(), sla_process_timers(), sla_ring_station(), smdi_message_wait(), smdi_read(), sms_handleincoming(), sms_handleincoming_proto2(), sms_readfile(), sms_writefile(), socket_process_meta(), speech_background(), static_callback(), store_config(), timeout_read(), timeout_write(), timing_read(), timing_test(), transmit_audio(), transmit_notify_request_with_callerid(), transmit_t38(), update_jbsched(), vmu_tm(), wait_for_answer(), waituntil_exec(), write_history(), and write_metadata().
{
struct timeval ast_tvsub (struct timeval a, struct timeval b) [read]
Returns the difference of two timevals a - b.
Definition at line 1379 of file utils.c.
References ONE_MILLION, and tvfix().
Referenced by ast_channel_bridge(), ast_rwlock_timedrdlock(), ast_rwlock_timedwrlock(), ast_sched_dump(), ast_translate(), ast_waitfor_nandfds(), calc_rxstamp(), calc_timestamp(), cli_tps_ping(), conf_run(), handle_showcalls(), and handle_showuptime().
{
   /* consistency checks to guarantee usec in 0..999999 */
   a = tvfix(a);
   b = tvfix(b);
   a.tv_sec -= b.tv_sec;
   a.tv_usec -= b.tv_usec;
   if (a.tv_usec < 0) {
      a.tv_sec-- ;
      a.tv_usec += ONE_MILLION;
   }
   return a;
}
__inline__ int ast_tvzero (const struct timeval t)
Returns true if the argument is 0,0.
Definition at line 99 of file time.h.
Referenced by __ast_read(), __verboser(), action_coreshowchannels(), append_date(), ast_bridge_call(), ast_cdr_answer(), ast_cdr_end(), ast_cdr_fork(), ast_cdr_merge(), ast_channel_bridge(), ast_channel_cmpwhentohangup_tv(), ast_channel_setwhentohangup_tv(), ast_check_hangup(), ast_generic_bridge(), ast_rtp_raw_write(), ast_smoother_read(), ast_translate(), ast_var_channels_table(), ast_waitfor_nandfds(), calc_rxstamp(), calc_timestamp(), calc_txpeerstamp(), calc_txstamp(), conf_run(), dial_exec_full(), do_monitor(), fix_peerts(), get_date(), handle_chanlist(), iax2_bridge(), misdn_read(), monmp3thread(), sched_settime(), schedule_delivery(), should_skip_dtmf(), show_chanstats_cb(), smoother_frame_feed(), sms_writefile(), socket_process_meta(), timeout_read(), and timeout_write().
{
typedef typeof (tv. tv_sec)
Variable Documentation
struct timeval tv
Referenced by ast_manager_register_struct(), and ast_manager_unregister().