#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  ldconfig
  if [ -d /usr/doc -a ! -e /usr/doc/termcap-compat -a -d /usr/share/doc/termcap-compat ]; then
   ln -sf ../share/doc/termcap-compat /usr/doc/termcap-compat
  fi
fi
